CREATE TABLE FRS_ALTERNATENAME ( 
	STATEFACILITYIDENTIFIER       	VARCHAR2(12) NOT NULL,
	ALTERNATIVENAME               	VARCHAR2(80) NOT NULL,
	ALTERNATIVENAMETYPETEXT       	VARCHAR2(25) NULL,
	DATASOURCENAME                	VARCHAR2(50) NULL,
	LASTREPORTEDDATE              	VARCHAR2(10) NOT NULL,
	STATEFACILITYSYSTEMACRONYMNAME	VARCHAR2(20) NOT NULL 
	);

CREATE TABLE FRS_DELETED_FACILITY ( 
	STATEFACILITYIDENTIFIER	VARCHAR2(12) NOT NULL,
	DELETIONDATE           	VARCHAR2(10) NOT NULL 
	);

CREATE TABLE FRS_ENVIRONMENTALINTEREST ( 
	STATEFACILITYIDENTIFIER       	VARCHAR2(12) NOT NULL,
	INFORMATIONSYSTEMACRONYMNAME  	VARCHAR2(20) NOT NULL,
	INFORMATIONSYSTEMIDENTIFIER   	VARCHAR2(30) NOT NULL,
	ENVIRONMENTALINTERESTTYPETEXT 	VARCHAR2(60) NOT NULL,
	FEDERALSTATEINTERESTINDICATOR 	VARCHAR2(1) NULL,
	ENVIRONMENTALINTERESTSTARTDATE	VARCHAR2(10) NULL,
	INTERESTSTARTDATEQUALIFIERTEXT	VARCHAR2(50) NULL,
	ENVIRONMENTALINTERESTENDDATE  	VARCHAR2(10) NULL,
	INTERESTENDDATEQUALIFIERTEXT  	VARCHAR2(50) NULL,
	DATASOURCENAME                	VARCHAR2(50) NULL,
	LASTREPORTEDDATE              	VARCHAR2(10) NULL,
	STATEFACILITYSYSTEMACRONYMNAME	VARCHAR2(20) NOT NULL 
	);

CREATE TABLE FRS_FACILITYSITE ( 
	STATEFACILITYIDENTIFIER       	VARCHAR2(12) NOT NULL,
	FACILITYREGISTRYIDENTIFIER    	VARCHAR2(20) NULL,
	FACILITYSITENAME              	VARCHAR2(80) NOT NULL,
	FACILITYSITETYPENAME          	VARCHAR2(40) NULL,
	FEDERALFACILITYINDICATOR      	VARCHAR2(1) NOT NULL,
	TRIBALLANDINDICATOR           	VARCHAR2(1) NULL,
	TRIBALLANDNAME                	VARCHAR2(200) NULL,
	CONGRESSIONALDISTRICTNUMBER   	VARCHAR2(2) NULL,
	LEGISLATIVEDISTRICTNUMBER     	VARCHAR2(2) NULL,
	HUCCODE                       	VARCHAR2(8) NULL,
	LOCATIONADDRESSTEXT           	VARCHAR2(50) NULL,
	SUPPLEMENTALLOCATIONTEXT      	VARCHAR2(50) NULL,
	LOCALITYNAME                  	VARCHAR2(60) NULL,
	COUNTYSTATEFIPSCODE           	VARCHAR2(5) NULL,
	COUNTYNAME                    	VARCHAR2(35) NULL,
	STATEUSPSCODE                 	VARCHAR2(2) NULL,
	STATENAME                     	VARCHAR2(35) NULL,
	COUNTRYNAME                   	VARCHAR2(44) NULL,
	LOCATIONZIPCODE               	VARCHAR2(14) NULL,
	LOCATIONDESCRIPTIONTEXT       	VARCHAR2(256) NULL,
	DATASOURCENAME                	VARCHAR2(50) NULL,
	LASTREPORTEDDATE              	VARCHAR2(10) NULL,
	STATEFACILITYSYSTEMACRONYMNAME	VARCHAR2(20) NOT NULL 
	);

CREATE TABLE FRS_GEOGRAPHICCOORDINATES ( 
	STATEFACILITYIDENTIFIER       	VARCHAR2(12) NOT NULL,
	LATITUDEMEASURE               	VARCHAR2(10) NOT NULL,
	LONGITUDEMEASURE              	VARCHAR2(11) NOT NULL,
	HORIZONTALACCURACYMEASURE     	VARCHAR2(6) NULL,
	HORIZONTALCOLLECTIONMETHODTEXT	VARCHAR2(60) NULL,
	HORIZONTALREFERENCEDATUMNAME  	VARCHAR2(7) NULL,
	SOURCEMAPSCALENUMBER          	VARCHAR2(10) NULL,
	REFERENCEPOINTTEXT            	VARCHAR2(60) NULL,
	DATACOLLECTIONDATE            	VARCHAR2(10) NULL,
	GEOMETRICTYPENAME             	VARCHAR2(30) NULL,
	LOCATIONCOMMENTSTEXT          	VARCHAR2(150) NULL,
	VERTICALCOLLECTIONMETHODTEXT  	VARCHAR2(60) NULL,
	VERTICALMEASURE               	VARCHAR2(10) NULL,
	VERTICALACCURACYMEASURE       	VARCHAR2(8) NULL,
	VERTICALREFERENCEDATUMNAME    	VARCHAR2(17) NULL,
	DATASOURCENAME                	VARCHAR2(50) NULL,
	COORDINATEDATASOURCENAME      	VARCHAR2(35) NULL,
	SUBENTITYIDENTIFIER           	VARCHAR2(30) NULL,
	SUBENTITYTYPENAME             	VARCHAR2(30) NULL,
	STATEFACILITYSYSTEMACRONYMNAME	VARCHAR2(20) NOT NULL 
	);

CREATE TABLE FRS_INDIVIDUAL ( 
	PK_ID                         	NUMBER NOT NULL,
	STATEFACILITYIDENTIFIER       	VARCHAR2(12) NOT NULL,
	INFORMATIONSYSTEMACRONYMNAME  	VARCHAR2(20) NOT NULL,
	INFORMATIONSYSTEMIDENTIFIER   	VARCHAR2(30) NOT NULL,
	ENVIRONMENTALINTERESTTYPETEXT 	VARCHAR2(60) NOT NULL,
	AFFILIATIONTYPETEXT           	VARCHAR2(40) NULL,
	AFFILIATIONSTARTDATE          	VARCHAR2(10) NULL,
	AFFILIATIONENDDATE            	VARCHAR2(10) NULL,
	EMAILADDRESSTEXT              	VARCHAR2(120) NULL,
	TELEPHONENUMBER               	VARCHAR2(30) NULL,
	PHONEEXTENSION                	VARCHAR2(5) NULL,
	FAXNUMBER                     	VARCHAR2(30) NULL,
	ALTERNATETELEPHONENUMBER      	VARCHAR2(30) NULL,
	INDIVIDUALFULLNAME            	VARCHAR2(70) NULL,
	INDIVIDUALTITLETEXT           	VARCHAR2(40) NULL,
	MAILINGADDRESSTEXT            	VARCHAR2(50) NULL,
	SUPPLEMENTALADDRESSTEXT       	VARCHAR2(50) NULL,
	MAILINGADDRESSCITYNAME        	VARCHAR2(30) NULL,
	MAILINGADDRESSSTATEUSPSCODE   	VARCHAR2(2) NULL,
	MAILINGADDRESSSTATENAME       	VARCHAR2(35) NULL,
	MAILINGADDRESSCOUNTRYNAME     	VARCHAR2(44) NULL,
	MAILINGADDRESSZIPCODE         	VARCHAR2(14) NULL,
	DATASOURCENAME                	VARCHAR2(50) NULL,
	LASTREPORTEDDATE              	VARCHAR2(10) NULL,
	STATEFACILITYSYSTEMACRONYMNAME	VARCHAR2(20) NOT NULL 
	);

CREATE TABLE FRS_MAILINGADDRESS ( 
	STATEFACILITYIDENTIFIER       	VARCHAR2(12) NOT NULL,
	AFFILIATIONTYPETEXT           	VARCHAR2(40) NULL,
	MAILINGADDRESSTEXT            	VARCHAR2(50) NULL,
	SUPPLEMENTALADDRESSTEXT       	VARCHAR2(50) NULL,
	MAILINGADDRESSCITYNAME        	VARCHAR2(30) NULL,
	MAILINGADDRESSSTATEUSPSCODE   	VARCHAR2(2) NULL,
	MAILINGADDRESSSTATENAME       	VARCHAR2(35) NULL,
	MAILINGADDRESSCOUNTRYNAME     	VARCHAR2(44) NULL,
	MAILINGADDRESSZIPCODE         	VARCHAR2(14) NULL,
	DATASOURCENAME                	VARCHAR2(50) NULL,
	LASTREPORTEDDATE              	VARCHAR2(10) NULL,
	STATEFACILITYSYSTEMACRONYMNAME	VARCHAR2(20) NOT NULL 
	);

CREATE TABLE FRS_NAICSCODE ( 
	STATEFACILITYIDENTIFIER       	VARCHAR2(12) NOT NULL,
	INFORMATIONSYSTEMACRONYMNAME  	VARCHAR2(20) NULL,
	INFORMATIONSYSTEMIDENTIFIER   	VARCHAR2(30) NULL,
	ENVIRONMENTALINTERESTTYPETEXT 	VARCHAR2(60) NULL,
	NAICSCODE                     	VARCHAR2(6) NOT NULL,
	NAICSPRIMARYINDICATOR         	VARCHAR2(10) NOT NULL,
	DATASOURCENAME                	VARCHAR2(50) NULL,
	LASTREPORTEDDATE              	VARCHAR2(10) NULL,
	STATEFACILITYSYSTEMACRONYMNAME	VARCHAR2(20) NOT NULL 
	);

CREATE TABLE FRS_ORGANIZATION ( 
	PK_ID                         	NUMBER NOT NULL,
	STATEFACILITYIDENTIFIER       	VARCHAR2(12) NOT NULL,
	INFORMATIONSYSTEMACRONYMNAME  	VARCHAR2(20) NOT NULL,
	INFORMATIONSYSTEMIDENTIFIER   	VARCHAR2(30) NOT NULL,
	ENVIRONMENTALINTERESTTYPETEXT 	VARCHAR2(60) NOT NULL,
	AFFILIATIONTYPETEXT           	VARCHAR2(40) NULL,
	AFFILIATIONSTARTDATE          	VARCHAR2(10) NULL,
	AFFILIATIONENDDATE            	VARCHAR2(10) NULL,
	EMAILADDRESSTEXT              	VARCHAR2(120) NULL,
	TELEPHONENUMBER               	VARCHAR2(30) NULL,
	PHONEEXTENSION                	VARCHAR2(5) NULL,
	FAXNUMBER                     	VARCHAR2(30) NULL,
	ALTERNATETELEPHONENUMBER      	VARCHAR2(30) NULL,
	ORGANIZATIONFORMALNAME        	VARCHAR2(80) NULL,
	ORGANIZATIONDUNSNUMBER        	VARCHAR2(9) NULL,
	ORGANIZATIONTYPETEXT          	VARCHAR2(10) NULL,
	EMPLOYERIDENTIFIER            	VARCHAR2(14) NULL,
	STATEBUSINESSIDENTIFIER       	VARCHAR2(30) NULL,
	ULTIMATEPARENTNAME            	VARCHAR2(50) NULL,
	ULTIMATEPARENTDUNSNUMBER      	VARCHAR2(9) NULL,
	MAILINGADDRESSTEXT            	VARCHAR2(50) NULL,
	SUPPLEMENTALADDRESSTEXT       	VARCHAR2(50) NULL,
	MAILINGADDRESSCITYNAME        	VARCHAR2(30) NULL,
	MAILINGADDRESSSTATEUSPSCODE   	VARCHAR2(2) NULL,
	MAILINGADDRESSSTATENAME       	VARCHAR2(35) NULL,
	MAILINGADDRESSCOUNTRYNAME     	VARCHAR2(44) NULL,
	MAILINGADDRESSZIPCODE         	VARCHAR2(14) NULL,
	DATASOURCENAME                	VARCHAR2(50) NULL,
	LASTREPORTEDDATE              	VARCHAR2(10) NULL,
	STATEFACILITYSYSTEMACRONYMNAME	VARCHAR2(20) NOT NULL 
	);

CREATE TABLE FRS_SICCODE ( 
	STATEFACILITYIDENTIFIER       	VARCHAR2(12) NOT NULL,
	INFORMATIONSYSTEMACRONYMNAME  	VARCHAR2(20) NULL,
	INFORMATIONSYSTEMIDENTIFIER   	VARCHAR2(30) NULL,
	ENVIRONMENTALINTERESTTYPETEXT 	VARCHAR2(60) NULL,
	SICCODE                       	VARCHAR2(4) NOT NULL,
	SICPRIMARYINDICATOR           	VARCHAR2(10) NULL,
	DATASOURCENAME                	VARCHAR2(50) NULL,
	LASTREPORTEDDATE              	VARCHAR2(10) NULL,
	STATEFACILITYSYSTEMACRONYMNAME	VARCHAR2(20) NOT NULL 
	);


CREATE UNIQUE INDEX PK_FRS_ALTERNATENAME
	ON FRS_ALTERNATENAME(STATEFACILITYIDENTIFIER);

CREATE UNIQUE INDEX PK_FRS_DELETED_FACILITY
	ON FRS_DELETED_FACILITY(STATEFACILITYIDENTIFIER, DELETIONDATE);

CREATE UNIQUE INDEX PK_FRS_ENVIRONMENTALINTEREST
	ON FRS_ENVIRONMENTALINTEREST(INFORMATIONSYSTEMACRONYMNAME, INFORMATIONSYSTEMIDENTIFIER, ENVIRONMENTALINTERESTTYPETEXT, STATEFACILITYIDENTIFIER);

CREATE UNIQUE INDEX PK_FRS_FACILITYSITE
	ON FRS_FACILITYSITE(STATEFACILITYIDENTIFIER);

CREATE UNIQUE INDEX PK_FRS_GEOGRAPHICCOORDINATES
	ON FRS_GEOGRAPHICCOORDINATES(LATITUDEMEASURE, LONGITUDEMEASURE, STATEFACILITYIDENTIFIER);

CREATE UNIQUE INDEX PK_FRS_INDIVIDUAL
	ON FRS_INDIVIDUAL(PK_ID);

CREATE UNIQUE INDEX PK_FRS_MAILINGADDRESS
	ON FRS_MAILINGADDRESS(STATEFACILITYIDENTIFIER);

CREATE UNIQUE INDEX PK_FRS_NAICSCODE
	ON FRS_NAICSCODE(STATEFACILITYIDENTIFIER, NAICSCODE);

CREATE UNIQUE INDEX PK_FRS_ORGANIZATI
	ON FRS_ORGANIZATION(PK_ID);

CREATE UNIQUE INDEX PK_FRS_SICCODE
	ON FRS_SICCODE(SICCODE, STATEFACILITYIDENTIFIER);

ALTER TABLE FRS_ALTERNATENAME
	ADD ( CONSTRAINT PK_FRS_ALTERNATENAME
	PRIMARY KEY (STATEFACILITYIDENTIFIER)
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE FRS_DELETED_FACILITY
	ADD ( CONSTRAINT PK_FRS_DELETED_FACILITY
	PRIMARY KEY (STATEFACILITYIDENTIFIER, DELETIONDATE)
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE FRS_ENVIRONMENTALINTEREST
	ADD ( CONSTRAINT PK_FRS_ENVIRONMENTALINTEREST
	PRIMARY KEY (STATEFACILITYIDENTIFIER, INFORMATIONSYSTEMACRONYMNAME, INFORMATIONSYSTEMIDENTIFIER, ENVIRONMENTALINTERESTTYPETEXT)
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE FRS_FACILITYSITE
	ADD ( CONSTRAINT PK_FRS_FACILITYSITE
	PRIMARY KEY (STATEFACILITYIDENTIFIER)
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE FRS_GEOGRAPHICCOORDINATES
	ADD ( CONSTRAINT PK_FRS_GEOGRAPHICCOORDINATES
	PRIMARY KEY (STATEFACILITYIDENTIFIER, LATITUDEMEASURE, LONGITUDEMEASURE)
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE FRS_INDIVIDUAL
	ADD ( CONSTRAINT PK_FRS_INDIVIDUAL
	PRIMARY KEY (PK_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE FRS_MAILINGADDRESS
	ADD ( CONSTRAINT PK_FRS_MAILINGADDRESS
	PRIMARY KEY (STATEFACILITYIDENTIFIER)
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE FRS_NAICSCODE
	ADD ( CONSTRAINT PK_FRS_NAICSCODE
	PRIMARY KEY (STATEFACILITYIDENTIFIER, NAICSCODE)
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE FRS_ORGANIZATION
	ADD ( CONSTRAINT PK_FRS_ORGANIZATI
	PRIMARY KEY (PK_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE FRS_SICCODE
	ADD ( CONSTRAINT PK_FRS_SICCODE
	PRIMARY KEY (STATEFACILITYIDENTIFIER, SICCODE)
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE FRS_ALTERNATENAME
	ADD ( CONSTRAINT FK_ALTERNATENAME_FACILITYSITE
	FOREIGN KEY(STATEFACILITYIDENTIFIER)
	REFERENCES FRS_FACILITYSITE(STATEFACILITYIDENTIFIER)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE FRS_ENVIRONMENTALINTEREST
	ADD ( CONSTRAINT FK_ENVINT_FACILITYSITE
	FOREIGN KEY(STATEFACILITYIDENTIFIER)
	REFERENCES FRS_FACILITYSITE(STATEFACILITYIDENTIFIER)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE FRS_GEOGRAPHICCOORDINATES
	ADD ( CONSTRAINT FK_GEOCOORD_FACILITYSITE
	FOREIGN KEY(STATEFACILITYIDENTIFIER)
	REFERENCES FRS_FACILITYSITE(STATEFACILITYIDENTIFIER)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE FRS_INDIVIDUAL
	ADD ( CONSTRAINT FK_IND_EI
	FOREIGN KEY(STATEFACILITYIDENTIFIER, INFORMATIONSYSTEMACRONYMNAME, INFORMATIONSYSTEMIDENTIFIER, ENVIRONMENTALINTERESTTYPETEXT)
	REFERENCES FRS_ENVIRONMENTALINTEREST(INFORMATIONSYSTEMACRONYMNAME, INFORMATIONSYSTEMIDENTIFIER, ENVIRONMENTALINTERESTTYPETEXT, STATEFACILITYIDENTIFIER)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE FRS_MAILINGADDRESS
	ADD ( CONSTRAINT FK_MAILADD_FACILITYSITE
	FOREIGN KEY(STATEFACILITYIDENTIFIER)
	REFERENCES FRS_FACILITYSITE(STATEFACILITYIDENTIFIER)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE FRS_NAICSCODE
	ADD ( CONSTRAINT FK_NAICSCODE_EI
	FOREIGN KEY(STATEFACILITYIDENTIFIER, INFORMATIONSYSTEMACRONYMNAME, INFORMATIONSYSTEMIDENTIFIER, ENVIRONMENTALINTERESTTYPETEXT)
	REFERENCES FRS_ENVIRONMENTALINTEREST(INFORMATIONSYSTEMACRONYMNAME, INFORMATIONSYSTEMIDENTIFIER, ENVIRONMENTALINTERESTTYPETEXT, STATEFACILITYIDENTIFIER)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE FRS_ORGANIZATION
	ADD ( CONSTRAINT FK_ORGANIZATION_EI
	FOREIGN KEY(STATEFACILITYIDENTIFIER, INFORMATIONSYSTEMACRONYMNAME, INFORMATIONSYSTEMIDENTIFIER, ENVIRONMENTALINTERESTTYPETEXT)
	REFERENCES FRS_ENVIRONMENTALINTEREST(INFORMATIONSYSTEMACRONYMNAME, INFORMATIONSYSTEMIDENTIFIER, ENVIRONMENTALINTERESTTYPETEXT, STATEFACILITYIDENTIFIER)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE FRS_SICCODE
	ADD ( CONSTRAINT FK_SICCODE_EI
	FOREIGN KEY(STATEFACILITYIDENTIFIER, INFORMATIONSYSTEMACRONYMNAME, INFORMATIONSYSTEMIDENTIFIER, ENVIRONMENTALINTERESTTYPETEXT)
	REFERENCES FRS_ENVIRONMENTALINTEREST(INFORMATIONSYSTEMACRONYMNAME, INFORMATIONSYSTEMIDENTIFIER, ENVIRONMENTALINTERESTTYPETEXT, STATEFACILITYIDENTIFIER)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

