/* This script creates the staging tables for the Beach Notification v2.1 data flow for the Java OpenNode2 */

/* Oracle */

CREATE TABLE "NOTIF_ACTIVITYINDICATOR" ( 
	"ID"                  	NUMBER NOT NULL,
	"ACTIVITY_ID"         	NUMBER NOT NULL,
	"INDICATORTYPE"       	VARCHAR2(60) NOT NULL,
	"INDICATORDESCRIPTION"	VARCHAR2(255) NULL 
	);

CREATE TABLE "NOTIF_ACTIVITYREASON" ( 
	"ID"               	NUMBER NOT NULL,
	"ACTIVITY_ID"      	NUMBER NOT NULL,
	"REASONTYPE"       	VARCHAR2(60) NOT NULL,
	"REASONDESCRIPTION"	VARCHAR2(255) NULL 
	);

CREATE TABLE "NOTIF_ACTIVITYSOURCE" ( 
	"ID"               	NUMBER NOT NULL,
	"ACTIVITY_ID"      	NUMBER NOT NULL,
	"SOURCETYPE"       	VARCHAR2(60) NOT NULL,
	"SOURCEDESCRIPTION"	VARCHAR2(255) NULL 
	);

CREATE TABLE "NOTIF_BEACH" ( 
	"ID"                            	NUMBER NOT NULL,
	"BEACHIDENTIFIER"               	VARCHAR2(8) NOT NULL,
	"BEACHNAME"                     	VARCHAR2(60) NOT NULL,
	"BEACHDESCRIPTION"              	VARCHAR2(255) NOT NULL,
	"BEACHCOMMENT"                  	VARCHAR2(255) NULL,
	"BEACHSTATECODE"                	CHAR(2) NOT NULL,
	"BEACHFIPSCOUNTYCODE"           	VARCHAR2(5) NOT NULL,
	"BEACHACCESSTYPE"               	VARCHAR2(12) NOT NULL,
	"BEACHACCESSCOMMENT"            	VARCHAR2(255) NULL,
	"EFFECTIVEYEAR"                 	VARCHAR2(4) NOT NULL,
	"EXTENTLENGTHMEASURE"           	NUMBER NOT NULL,
	"EXTENTUNITOFMEASURE"           	VARCHAR2(12) NOT NULL,
	"SWIMSEASONSTARTDATE"           	VARCHAR2(25) NULL,
	"SWIMSEASONENDDATE"             	VARCHAR2(25) NULL,
	"SWIMSEASONLENGTH"              	NUMBER NULL,
	"SWIMSEASONUNITOFMEASURE"       	VARCHAR2(12) NULL,
	"SWIMSEASONFREQUENCYMEASURE"    	NUMBER NOT NULL,
	"OFFSEASONFREQUENCYMEASURE"     	NUMBER NOT NULL,
	"MONITORINGFREQUNITOFMEASURE"   	VARCHAR2(255) NOT NULL,
	"MONITOREDIRREGULARLY"          	VARCHAR2(5) NOT NULL,
	"MONITOREDIRREGULARLYCOMMENT"   	VARCHAR2(255) NULL,
	"BEACHTIERRANKING"              	VARCHAR2(1) NOT NULL,
	"BEACHACTBEACHINDICATOR"        	VARCHAR2(5) NOT NULL,
	"NOPOLLUTIONSOURCES"            	VARCHAR2(5) NULL,
	"POLLUTIONSOURCESUNINVESTIGATED"	VARCHAR2(5) NULL,
	"WATERBODYNAMECODE"             	VARCHAR2(25) NULL,
	"WATERBODYTYPECODE"             	VARCHAR2(25) NULL,
	"STARTLATMEASURE"               	VARCHAR2(25) NULL,
	"STARTLONGMEASURE"              	VARCHAR2(25) NULL,
	"ENDLATMEASURE"                 	VARCHAR2(25) NULL,
	"ENDLONGMEASURE"                	VARCHAR2(25) NULL,
	"SOURCEMAPSCALE"                	VARCHAR2(25) NULL,
	"HORIZCOLLMETHOD"               	VARCHAR2(25) NULL,
	"HORIZCOLLDATUM"                	VARCHAR2(25) NULL 
	);

CREATE TABLE "NOTIF_BEACHACTIVITY" ( 
	"ID"                         	NUMBER NOT NULL,
	"BEACH_ID"                   	NUMBER NOT NULL,
	"ACTIVITYTYPECODE"           	VARCHAR2(12) NOT NULL,
	"ACTIVITYNAME"               	VARCHAR2(60) NOT NULL,
	"ACTUALSTARTDATE"            	VARCHAR2(25) NOT NULL,
	"ACTUALSTOPDATE"             	VARCHAR2(25) NOT NULL,
	"MONITORINGSTATIONIDENTIFIER"	VARCHAR2(65) NULL,
	"ACTIVITYDESCRIPTION"        	VARCHAR2(255) NULL,
	"ACTIVITYCOMMENT"            	VARCHAR2(255) NULL,
	"EXTENTSTARTMEASURE"         	NUMBER NULL,
	"EXTENTLENGTHMEASURE"        	NUMBER NULL,
	"EXTENTUNITOFMEASURE"        	VARCHAR2(255) NULL,
	"SENTTOEPA"                  	CHAR(1) NULL 
	);

CREATE TABLE "NOTIF_BEACHACTIVITYDATES" ( 
	"BEACH_ID" 	VARCHAR2(8) NOT NULL,
	"STARTDATE"	DATE NULL,
	"ENDDATE"  	DATE NULL 
	);

CREATE TABLE "NOTIF_BEACHPOLLUTION" ( 
	"ID"                        	NUMBER NOT NULL,
	"BEACH_ID"                  	NUMBER NOT NULL,
	"POLLUTIONSOURCECODE"       	VARCHAR2(12) NOT NULL,
	"POLLUTIONSOURCEDESCRIPTION"	VARCHAR2(255) NULL 
	);

CREATE TABLE "NOTIF_BEACHPROCEDURE" ( 
	"ID"                  	NUMBER NOT NULL,
	"BEACH_ID"            	NUMBER NOT NULL,
	"PROCEDUREIDENTIFIER" 	VARCHAR2(8) NOT NULL,
	"PROCEDURETYPECODE"   	VARCHAR2(12) NOT NULL,
	"PROCEDUREDESCRIPTION"	VARCHAR2(255) NOT NULL 
	);

CREATE TABLE "NOTIF_ORGANIZATION" ( 
	"ID"                      	NUMBER NOT NULL,
	"ORGANIZATIONIDENTIFIER"  	VARCHAR2(12) NOT NULL,
	"ORGANIZATIONTYPECODE"    	VARCHAR2(12) NOT NULL,
	"ORGANIZATIONNAME"        	VARCHAR2(60) NOT NULL,
	"ORGANIZATIONDESCRIPTION" 	VARCHAR2(255) NULL,
	"ORGANIZATIONABBREVIATION"	VARCHAR2(30) NULL 
	);

CREATE TABLE "NOTIF_ORGANIZATIONBEACHROLE" ( 
	"ID"               	NUMBER NOT NULL,
	"BEACH_ID"         	NUMBER NOT NULL,
	"ORGANIZATION_ID"  	NUMBER NOT NULL,
	"ROLETYPECODE"     	VARCHAR2(12) NOT NULL,
	"ROLEEFFECTIVEDATE"	VARCHAR2(25) NOT NULL,
	"ROLESTATUS"       	VARCHAR2(8) NOT NULL 
	);

CREATE TABLE "NOTIF_ORGANIZATIONMAILINGADDR" ( 
	"ID"                      	NUMBER NOT NULL,
	"ORGANIZATION_ID"         	NUMBER NOT NULL,
	"MAILINGADDRTYPECODE"     	VARCHAR2(12) NOT NULL,
	"MAILINGADDRLINE1"        	VARCHAR2(100) NOT NULL,
	"MAILINGADDRLINE2"        	VARCHAR2(100) NULL,
	"MAILINGADDRLINE3"        	VARCHAR2(100) NULL,
	"MAILINGADDRCITY"         	VARCHAR2(50) NOT NULL,
	"STATECODE"               	CHAR(2) NOT NULL,
	"ZIPCODE"                 	VARCHAR2(12) NOT NULL,
	"MAILINGADDREFFECTIVEDATE"	VARCHAR2(25) NOT NULL,
	"MAILINGADDRSTATUS"       	VARCHAR2(8) NOT NULL 
	);

CREATE TABLE "NOTIF_ORGANIZATIONTELEPHONE" ( 
	"ID"                    	NUMBER NOT NULL,
	"ORGANIZATION_ID"       	NUMBER NOT NULL,
	"TELEPHONETYPECODE"     	VARCHAR2(12) NOT NULL,
	"TELEPHONENUMBER"       	VARCHAR2(12) NOT NULL,
	"TELEPHONEEFFECTIVEDATE"	VARCHAR2(25) NOT NULL,
	"TELEPHONESTATUS"       	VARCHAR2(8) NOT NULL 
	);

CREATE TABLE "NOTIF_ORGELECTRONICADDR" ( 
	"ID"                    	NUMBER NOT NULL,
	"ORGANIZATION_ID"       	NUMBER NOT NULL,
	"ELECTRONICADDRTYPECODE"	VARCHAR2(12) NOT NULL,
	"ELECTRONICADDR"        	VARCHAR2(255) NOT NULL,
	"ELECTRONICADDREFFDATE" 	VARCHAR2(25) NOT NULL,
	"ELECTRONICADDRSTATUS"  	VARCHAR2(8) NOT NULL 
	);

CREATE TABLE "NOTIF_PERSON" ( 
	"ID"              	NUMBER NOT NULL,
	"ORGANIZATION_ID" 	NUMBER NOT NULL,
	"PERSONIDENTIFIER"	VARCHAR2(12) NOT NULL,
	"PERSONSTATUS"    	VARCHAR2(8) NOT NULL,
	"FIRSTNAME"       	VARCHAR2(50) NOT NULL,
	"LASTNAME"        	VARCHAR2(50) NOT NULL,
	"MIDDLEINITIAL"   	VARCHAR2(2) NULL,
	"SUFFIX"          	VARCHAR2(5) NULL,
	"TITLE"           	VARCHAR2(60) NULL 
	);

CREATE TABLE "NOTIF_PERSONBEACHROLE" ( 
	"ID"               	NUMBER NOT NULL,
	"BEACH_ID"         	NUMBER NOT NULL,
	"PERSON_ID"        	NUMBER NOT NULL,
	"ROLETYPECODE"     	VARCHAR2(12) NOT NULL,
	"ROLEEFFECTIVEDATE"	VARCHAR2(25) NOT NULL,
	"ROLESTATUS"       	VARCHAR2(8) NOT NULL 
	);

CREATE TABLE "NOTIF_PERSONELECTRONICADDRESS" ( 
	"ID"                            	NUMBER NOT NULL,
	"PERSON_ID"                     	NUMBER NOT NULL,
	"ELECTRONICADDRESSTYPECODE"     	VARCHAR2(12) NOT NULL,
	"ELECTRONICADDRESS"             	VARCHAR2(255) NOT NULL,
	"ELECTRONICADDRESSEFFECTIVEDATE"	VARCHAR2(25) NOT NULL,
	"ELECTRONICADDRESSSTATUS"       	VARCHAR2(8) NOT NULL 
	);

CREATE TABLE "NOTIF_PERSONMAILINGADDRESS" ( 
	"ID"                      	NUMBER NOT NULL,
	"PERSON_ID"               	NUMBER NOT NULL,
	"MAILINGADDRTYPECODE"     	VARCHAR2(12) NOT NULL,
	"MAILINGADDRLINE1"        	VARCHAR2(100) NOT NULL,
	"MAILINGADDRLINE2"        	VARCHAR2(100) NULL,
	"MAILINGADDRLINE3"        	VARCHAR2(100) NULL,
	"MAILINGADDRCITY"         	VARCHAR2(50) NOT NULL,
	"STATECODE"               	CHAR(2) NOT NULL,
	"ZIPCODE"                 	VARCHAR2(12) NOT NULL,
	"MAILINGADDREFFECTIVEDATE"	VARCHAR2(25) NOT NULL,
	"MAILINGADDRSTATUS"       	VARCHAR2(8) NOT NULL 
	);

CREATE TABLE "NOTIF_PERSONTELEPHONE" ( 
	"ID"                    	NUMBER NOT NULL,
	"PERSON_ID"             	NUMBER NOT NULL,
	"TELEPHONETYPECODE"     	VARCHAR2(12) NOT NULL,
	"TELEPHONENUMBER"       	VARCHAR2(12) NOT NULL,
	"TELEPHONEEFFECTIVEDATE"	VARCHAR2(25) NOT NULL,
	"TELEPHONESTATUS"       	VARCHAR2(8) NOT NULL 
	);

CREATE TABLE "NOTIF_YEARCOMPLETION" ( 
	"ID"                           	NUMBER NOT NULL,
	"COMPLETIONYEAR"               	NUMBER NOT NULL,
	"NOTIFICATIONDATACOMPLETIONIND"	VARCHAR2(5) NULL,
	"MONITORINGDATACOMPLETIONIND"  	VARCHAR2(5) NULL,
	"LOCATIONDATACOMPLETIONIND"    	VARCHAR2(5) NULL 
	);

CREATE SEQUENCE "NOTIF_ACTIVITYINDICATOR_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_ACTIVITYREASON_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_ACTIVITYSOURCE_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_BEACHACTIVITY_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_BEACHPOLLUTION_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_BEACHPROCEDURE_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_BEACH_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_ORGANIZATION_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_ORGBEACHROLE_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_ORGELECTRONICADDR_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_ORGMAILINGADDR_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_ORGTELEPHONE_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_PERSONBEACHROLE_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_PERSONELECTRADDR_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_PERSONMAILINGADDR_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_PERSONTELEPHONE_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_PERSON_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE "NOTIF_YEARCOMPLETION_ID_SEQ"
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 0
	NOCYCLE
	NOCACHE
	ORDER;


CREATE UNIQUE INDEX "PK_NOTIF_ACTIVITYINDICATOR"
	ON "NOTIF_ACTIVITYINDICATOR"("ID");

CREATE INDEX "NOTIF_ACTIVITYINDICATOR"
	ON "NOTIF_ACTIVITYINDICATOR"("ACTIVITY_ID");

CREATE UNIQUE INDEX "PK_NOTIF_ACTIVITYREASON"
	ON "NOTIF_ACTIVITYREASON"("ID");

CREATE INDEX "NOTIF_ACTIVITYREASON"
	ON "NOTIF_ACTIVITYREASON"("ACTIVITY_ID");

CREATE UNIQUE INDEX "PK_NOTIF_ACTIVITYSOURCE"
	ON "NOTIF_ACTIVITYSOURCE"("ID");

CREATE INDEX "NOTIF_ACTIVITYSOURCE"
	ON "NOTIF_ACTIVITYSOURCE"("ACTIVITY_ID");

CREATE UNIQUE INDEX "PK_NOTIF_BEACH"
	ON "NOTIF_BEACH"("ID");

CREATE INDEX "NOTIF_SENTTOEPA"
	ON "NOTIF_BEACHACTIVITY"("SENTTOEPA");

CREATE INDEX "NOTIF_BEACHACTIVITY"
	ON "NOTIF_BEACHACTIVITY"("BEACH_ID");

CREATE UNIQUE INDEX "PK_NOTIF_BEACHACTIVITY"
	ON "NOTIF_BEACHACTIVITY"("ID");

CREATE UNIQUE INDEX "PK_NOTIF_BEACHPOLLUTION"
	ON "NOTIF_BEACHPOLLUTION"("ID");

CREATE INDEX "NOTIF_BEACHPOLLUTION"
	ON "NOTIF_BEACHPOLLUTION"("BEACH_ID");

CREATE INDEX "NOTIF_BEACHPROCEDURE"
	ON "NOTIF_BEACHPROCEDURE"("BEACH_ID");

CREATE UNIQUE INDEX "PK_NOTIF_BEACHPROCEDURE"
	ON "NOTIF_BEACHPROCEDURE"("ID");

CREATE UNIQUE INDEX "PK_NOTIF_ORGANIZATION"
	ON "NOTIF_ORGANIZATION"("ID");

CREATE INDEX "NOTIF_ORGANIZATIONBEACHROLE"
	ON "NOTIF_ORGANIZATIONBEACHROLE"("ORGANIZATION_ID");

CREATE UNIQUE INDEX "PK_NOTIF_ORGANIZATIONBEACHROLE"
	ON "NOTIF_ORGANIZATIONBEACHROLE"("ID");

CREATE INDEX "NOTIF_ORGANIZATIONMAILINGADDR"
	ON "NOTIF_ORGANIZATIONMAILINGADDR"("ORGANIZATION_ID");

CREATE UNIQUE INDEX "PK_NOTIF_ORGMAILINGADDR"
	ON "NOTIF_ORGANIZATIONMAILINGADDR"("ID");

CREATE UNIQUE INDEX "PK_NOTIF_ORGANIZATIONTELEPHONE"
	ON "NOTIF_ORGANIZATIONTELEPHONE"("ID");

CREATE INDEX "NOTIF_ORGANIZATIONTELEPHONE"
	ON "NOTIF_ORGANIZATIONTELEPHONE"("ORGANIZATION_ID");

CREATE UNIQUE INDEX "PK_NOTIF_ORGELECTRONICADDR"
	ON "NOTIF_ORGELECTRONICADDR"("ID");

CREATE INDEX "NOTIF_ORGELECTRONICADDR"
	ON "NOTIF_ORGELECTRONICADDR"("ORGANIZATION_ID");

CREATE INDEX "NOTIF_PERSON"
	ON "NOTIF_PERSON"("ORGANIZATION_ID");

CREATE UNIQUE INDEX "PK_NOTIF_PERSON"
	ON "NOTIF_PERSON"("ID");

CREATE UNIQUE INDEX "PK_NOTIF_PERSONBEACHROLE"
	ON "NOTIF_PERSONBEACHROLE"("ID");

CREATE INDEX "NOTIF_PERSONBEACHROLE"
	ON "NOTIF_PERSONBEACHROLE"("BEACH_ID");

CREATE UNIQUE INDEX "PK_NOTIF_PERSONELECTRONICADDR"
	ON "NOTIF_PERSONELECTRONICADDRESS"("ID");

CREATE INDEX "NOTIF_PERSONELECTRONICADDRESS"
	ON "NOTIF_PERSONELECTRONICADDRESS"("PERSON_ID");

CREATE INDEX "NOTIF_PERSONMAILINGADDRESS"
	ON "NOTIF_PERSONMAILINGADDRESS"("PERSON_ID");

CREATE UNIQUE INDEX "PK_NOTIF_PERSONMAILINGADDRESS"
	ON "NOTIF_PERSONMAILINGADDRESS"("ID");

CREATE INDEX "NOTIF_PERSONTELEPHONE"
	ON "NOTIF_PERSONTELEPHONE"("PERSON_ID");

CREATE UNIQUE INDEX "PK_NOTIF_PERSONTELEPHONE"
	ON "NOTIF_PERSONTELEPHONE"("ID");

CREATE UNIQUE INDEX "PK_NOTIF_YEARCOMPLETION"
	ON "NOTIF_YEARCOMPLETION"("ID");

ALTER TABLE "NOTIF_ACTIVITYINDICATOR"
	ADD ( CONSTRAINT "PK_NOTIF_ACTIVITYINDICATOR"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_ACTIVITYREASON"
	ADD ( CONSTRAINT "PK_NOTIF_ACTIVITYREASON"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_ACTIVITYSOURCE"
	ADD ( CONSTRAINT "PK_NOTIF_ACTIVITYSOURCE"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_BEACH"
	ADD ( CONSTRAINT "PK_NOTIF_BEACH"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_BEACHACTIVITY"
	ADD ( CONSTRAINT "PK_NOTIF_BEACHACTIVITY"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_BEACHPOLLUTION"
	ADD ( CONSTRAINT "PK_NOTIF_BEACHPOLLUTION"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_BEACHPROCEDURE"
	ADD ( CONSTRAINT "PK_NOTIF_BEACHPROCEDURE"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_ORGANIZATION"
	ADD ( CONSTRAINT "PK_NOTIF_ORGANIZATION"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_ORGANIZATIONBEACHROLE"
	ADD ( CONSTRAINT "PK_NOTIF_ORGANIZATIONBEACHROLE"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_ORGANIZATIONMAILINGADDR"
	ADD ( CONSTRAINT "PK_NOTIF_ORGMAILINGADDR"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_ORGANIZATIONTELEPHONE"
	ADD ( CONSTRAINT "PK_NOTIF_ORGANIZATIONTELEPHONE"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_ORGELECTRONICADDR"
	ADD ( CONSTRAINT "PK_NOTIF_ORGELECTRONICADDR"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_PERSON"
	ADD ( CONSTRAINT "PK_NOTIF_PERSON"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_PERSONBEACHROLE"
	ADD ( CONSTRAINT "PK_NOTIF_PERSONBEACHROLE"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_PERSONELECTRONICADDRESS"
	ADD ( CONSTRAINT "PK_NOTIF_PERSONELECTRONICADDR"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_PERSONMAILINGADDRESS"
	ADD ( CONSTRAINT "PK_NOTIF_PERSONMAILINGADDRESS"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_PERSONTELEPHONE"
	ADD ( CONSTRAINT "PK_NOTIF_PERSONTELEPHONE"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_YEARCOMPLETION"
	ADD ( CONSTRAINT "PK_NOTIF_YEARCOMPLETION"
	PRIMARY KEY ("ID")
	NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "NOTIF_ACTIVITYINDICATOR"
	ADD ( CONSTRAINT "FK_ACTIVITYINDICATOR_BEACHACT"
	FOREIGN KEY("ACTIVITY_ID")
	REFERENCES "NOTIF_BEACHACTIVITY"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_ACTIVITYREASON"
	ADD ( CONSTRAINT "FK_ACTIVITYREASON_BEACHACT"
	FOREIGN KEY("ACTIVITY_ID")
	REFERENCES "NOTIF_BEACHACTIVITY"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_ACTIVITYSOURCE"
	ADD ( CONSTRAINT "FK_ACTIVITYSOURCE_BEACHACT"
	FOREIGN KEY("ACTIVITY_ID")
	REFERENCES "NOTIF_BEACHACTIVITY"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_BEACHACTIVITY"
	ADD ( CONSTRAINT "FK_BEACHACTIVITY_BEACH"
	FOREIGN KEY("BEACH_ID")
	REFERENCES "NOTIF_BEACH"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_BEACHPOLLUTION"
	ADD ( CONSTRAINT "FK_BEACHPOLLUTION_BEACH"
	FOREIGN KEY("BEACH_ID")
	REFERENCES "NOTIF_BEACH"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_BEACHPROCEDURE"
	ADD ( CONSTRAINT "FK_BEACHPROCEDURE_BEACH"
	FOREIGN KEY("BEACH_ID")
	REFERENCES "NOTIF_BEACH"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_ORGANIZATIONBEACHROLE"
	ADD ( CONSTRAINT "FK_ORGANIZATIONBEACHROLE_ORG"
	FOREIGN KEY("ORGANIZATION_ID")
	REFERENCES "NOTIF_ORGANIZATION"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_ORGANIZATIONBEACHROLE"
	ADD ( CONSTRAINT "FK_ORGANIZATIONBEACHROLE_BEACH"
	FOREIGN KEY("BEACH_ID")
	REFERENCES "NOTIF_BEACH"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_ORGANIZATIONMAILINGADDR"
	ADD ( CONSTRAINT "FK_ORGANIZATION_ORGMAILINGADDR"
	FOREIGN KEY("ORGANIZATION_ID")
	REFERENCES "NOTIF_ORGANIZATION"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_ORGANIZATIONTELEPHONE"
	ADD ( CONSTRAINT "FK_ORGANIZATIONTELEPHONE_ORG"
	FOREIGN KEY("ORGANIZATION_ID")
	REFERENCES "NOTIF_ORGANIZATION"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_ORGELECTRONICADDR"
	ADD ( CONSTRAINT "FK_ORGELECTRONICADDR_ORG"
	FOREIGN KEY("ORGANIZATION_ID")
	REFERENCES "NOTIF_ORGANIZATION"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_PERSON"
	ADD ( CONSTRAINT "FK_PERSON_ORGANIZATION"
	FOREIGN KEY("ORGANIZATION_ID")
	REFERENCES "NOTIF_ORGANIZATION"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_PERSONBEACHROLE"
	ADD ( CONSTRAINT "FK_PERSONBEACHROLE_PERSON"
	FOREIGN KEY("PERSON_ID")
	REFERENCES "NOTIF_PERSON"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_PERSONBEACHROLE"
	ADD ( CONSTRAINT "FK_PERSONBEACHROLE_BEACH"
	FOREIGN KEY("BEACH_ID")
	REFERENCES "NOTIF_BEACH"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_PERSONELECTRONICADDRESS"
	ADD ( CONSTRAINT "FK_PERSONELECTRONICADD_PERSON"
	FOREIGN KEY("PERSON_ID")
	REFERENCES "NOTIF_PERSON"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_PERSONMAILINGADDRESS"
	ADD ( CONSTRAINT "FK_PERSONMAILINGADDRESS_PERSON"
	FOREIGN KEY("PERSON_ID")
	REFERENCES "NOTIF_PERSON"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "NOTIF_PERSONTELEPHONE"
	ADD ( CONSTRAINT "FK_PERSONTELEPHONE_PERSON"
	FOREIGN KEY("PERSON_ID")
	REFERENCES "NOTIF_PERSON"("ID")
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

