
ALTER TABLE "NACCOUNT" MODIFY ("PASSWORDHASH" VARCHAR2(500));

ALTER TABLE "NACCOUNT" ADD ("ISENDPOINTUSER" CHAR(1) NULL);

ALTER TABLE "NTRANSACTION" ADD ("NETWORKENDPOINTUSER" VARCHAR2(50) NULL);

ALTER TABLE "NTRANSACTION" ADD CONSTRAINT "FK_NETENDUSER_TRANS_ACCOUNT" FOREIGN KEY ("NETWORKENDPOINTUSER")
	  REFERENCES "NACCOUNT" ("ID") ENABLE;

ALTER TABLE "NSCHEDULE" ADD ("SOURCEENDPOINTUSER" VARCHAR2(50) NULL);

ALTER TABLE "NSCHEDULE" ADD CONSTRAINT "FK_SRCENDUSER_TRANS_ACCOUNT" FOREIGN KEY ("SOURCEENDPOINTUSER")
	  REFERENCES "NACCOUNT" ("ID") ENABLE;

ALTER TABLE "NSCHEDULE" ADD ("TARGETENDPOINTUSER" VARCHAR2(50) NULL);

ALTER TABLE "NSCHEDULE" ADD CONSTRAINT "FK_TARGENDUSER_TRANS_ACCOUNT" FOREIGN KEY ("TARGETENDPOINTUSER")
	  REFERENCES "NACCOUNT" ("ID") ENABLE;
