/****** Object:  Table [dbo].[NObjectCache]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NObjectCache](
	[Name] [varchar](255) NOT NULL,
	[Data] [varbinary](max) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[Expiration] [datetime] NOT NULL,
 CONSTRAINT [PK_NObjectCache] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NObjectCache_Expiration] ON [NObjectCache] 
(
	[Expiration] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NObjectCache_ModifiedOn] ON [NObjectCache] 
(
	[ModifiedOn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPartner_Name] ON [NObjectCache] 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NAccount]    Script Date: 01/13/2011 09:37:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NAccount](
	[Id] [varchar](50) NOT NULL,
	[NAASAccount] [varchar](500) NOT NULL,
	[IsActive] [char](1) NOT NULL,
	[SystemRole] [varchar](50) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[IsDeleted] [char](1) NULL,
	[IsDemoUser] [char](1) NULL,
	[PasswordHash] [varchar](50) NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_Account_NAASAccount] UNIQUE NONCLUSTERED 
(
	[NAASAccount] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NAccount_IsActive] ON [NAccount] 
(
	[IsActive] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NAccount_ModifiedBy] ON [NAccount] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NAccount_ModifiedOn] ON [NAccount] 
(
	[ModifiedOn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NAccount_NAASAccount] ON [NAccount] 
(
	[NAASAccount] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NAccount_SystemRole] ON [NAccount] 
(
	[SystemRole] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NConnection]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NConnection](
	[Id] [varchar](50) NOT NULL,
	[Code] [varchar](255) NOT NULL,
	[Provider] [varchar](500) NOT NULL,
	[ConnectionString] [varchar](500) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
 CONSTRAINT [PK_Connection] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_Connection_Code] UNIQUE NONCLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NConnection_ModifiedBy] ON [NConnection] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NConfig]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NConfig](
	[Id] [varchar](255) NOT NULL,
	[Value] [varchar](4000) NOT NULL,
	[Description] [varchar](500) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[IsEditable] [char](1) NOT NULL,
 CONSTRAINT [PK_Config] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NConfig_ModifiedBy] ON [NConfig] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NAccountPolicy]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NAccountPolicy](
	[Id] [varchar](50) NOT NULL,
	[AccountId] [varchar](50) NOT NULL,
	[Type] [varchar](50) NOT NULL,
	[Qualifier] [varchar](500) NOT NULL,
	[IsAllowed] [char](1) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
 CONSTRAINT [PK_NAccountPolicy] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NAccountPolicy_AccountId] ON [NAccountPolicy] 
(
	[AccountId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NAccountPolicy_ModifiedBy] ON [NAccountPolicy] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NFlow]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NFlow](
	[Id] [varchar](50) NOT NULL,
	[InfoUrl] [varchar](500) NULL,
	[Contact] [varchar](255) NOT NULL,
	[IsProtected] [char](1) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[Code] [varchar](255) NOT NULL,
	[Description] [varchar](500) NULL,
 CONSTRAINT [PK_Flow] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_Flow_Code] UNIQUE NONCLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NFlow_Code] ON [NFlow] 
(
	[Code] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NFlow_IsProtected] ON [NFlow] 
(
	[IsProtected] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NFlow_ModifiedBy] ON [NFlow] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NFlow_ModifiedOn] ON [NFlow] 
(
	[ModifiedOn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NPartner]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NPartner](
	[Id] [varchar](50) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Url] [varchar](500) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[Version] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Partner] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_NPartner] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_Partner_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NPartner_ModifiedBy] ON [NPartner] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPartner_Name] ON [NPartner] 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NPlugin]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NPlugin](
	[Id] [varchar](50) NOT NULL,
	[FlowId] [varchar](50) NOT NULL,
	[BinaryVersion] [varchar](40) NOT NULL,
	[ZippedBinary] [varbinary](max) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
 CONSTRAINT [PK_NPlugin] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_Plugin_BinaryVersionFlowId] UNIQUE NONCLUSTERED 
(
	[BinaryVersion] ASC,
	[FlowId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NPlugin_FlowId] ON [NPlugin] 
(
	[FlowId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NPlugin_ModifiedBy] ON [NPlugin] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NNotification]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NNotification](
	[Id] [varchar](50) NOT NULL,
	[FlowId] [varchar](50) NOT NULL,
	[AccountId] [varchar](50) NOT NULL,
	[OnSolicit] [char](1) NOT NULL,
	[OnQuery] [char](1) NOT NULL,
	[OnSubmit] [char](1) NOT NULL,
	[OnNotify] [char](1) NOT NULL,
	[OnSchedule] [char](1) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[OnDownload] [char](1) NOT NULL,
	[OnExecute] [char](1) NOT NULL,
 CONSTRAINT [PK_Notification] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_Notification_FlowIdAccountId] UNIQUE NONCLUSTERED 
(
	[FlowId] ASC,
	[AccountId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NNotification_AccountId] ON [NNotification] 
(
	[AccountId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NNotification_FlowId] ON [NNotification] 
(
	[FlowId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NNotification_ModifiedBy] ON [NNotification] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NService]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NService](
	[Id] [varchar](50) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[FlowId] [varchar](50) NOT NULL,
	[IsActive] [char](1) NOT NULL,
	[ServiceType] [varchar](128) NOT NULL,
	[Implementor] [varchar](500) NOT NULL,
	[AuthLevel] [varchar](50) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[PublishFlags] [varchar](50) NULL,
 CONSTRAINT [PK_Service] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_Service_NameFlowId] UNIQUE NONCLUSTERED 
(
	[Name] ASC,
	[FlowId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NService_AuthLevel] ON [NService] 
(
	[AuthLevel] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NService_FlowId] ON [NService] 
(
	[FlowId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NService_IsActive] ON [NService] 
(
	[IsActive] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NService_ModifiedBy] ON [NService] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NService_PublishFlags] ON [NService] 
(
	[PublishFlags] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NService_ScheduleId] ON [NService] 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NService_ServiceType] ON [NService] 
(
	[ServiceType] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NTransaction]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NTransaction](
	[Id] [varchar](50) NOT NULL,
	[FlowId] [varchar](50) NOT NULL,
	[NetworkId] [varchar](255) NOT NULL,
	[Status] [varchar](50) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[StatusDetail] [varchar](4000) NULL,
	[Operation] [varchar](255) NULL,
	[WebMethod] [varchar](50) NOT NULL,
	[EndpointVersion] [varchar](50) NULL,
	[NetworkEndpointVersion] [varchar](50) NULL,
	[NetworkEndpointUrl] [varchar](500) NULL,
	[NetworkEndpointStatus] [varchar](50) NULL,
	[NetworkEndpointStatusDetail] [varchar](4000) NULL,
 CONSTRAINT [PK_Transaction] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NTransaction_EndpointVersion] ON [NTransaction] 
(
	[EndpointVersion] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NTransaction_FlowId] ON [NTransaction] 
(
	[FlowId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NTransaction_ModifiedBy] ON [NTransaction] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NTransaction_ModifiedOn] ON [NTransaction] 
(
	[ModifiedOn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NTransaction_NetworkEndpointStatus] ON [NTransaction] 
(
	[NetworkEndpointStatus] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NTransaction_NetworkEndpointUrl] ON [NTransaction] 
(
	[NetworkEndpointUrl] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NTransaction_NetworkEndpointVersion] ON [NTransaction] 
(
	[NetworkEndpointVersion] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NTransaction_NetworkId] ON [NTransaction] 
(
	[NetworkId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NTransaction_Operation] ON [NTransaction] 
(
	[Operation] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NTransaction_Status] ON [NTransaction] 
(
	[Status] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NTransaction_WebMethod] ON [NTransaction] 
(
	[WebMethod] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NServiceConn]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NServiceConn](
	[Id] [varchar](50) NOT NULL,
	[ServiceId] [varchar](50) NOT NULL,
	[ConnectionId] [varchar](50) NOT NULL,
	[KeyName] [varchar](255) NOT NULL,
 CONSTRAINT [PK_NServiceConn] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_Service_ServiceIdKeyName] UNIQUE NONCLUSTERED 
(
	[ServiceId] ASC,
	[KeyName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NServiceConn_ConnectionId] ON [NServiceConn] 
(
	[ConnectionId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NServiceConn_KeyName] ON [NServiceConn] 
(
	[KeyName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NServiceConn_ServiceId] ON [NServiceConn] 
(
	[ServiceId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NServiceArg]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NServiceArg](
	[Id] [varchar](50) NOT NULL,
	[ServiceId] [varchar](50) NOT NULL,
	[ArgCode] [varchar](255) NOT NULL,
	[Value] [varchar](4000) NULL,
 CONSTRAINT [PK_ServiceArg] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NServiceArg_ServiceId] ON [NServiceArg] 
(
	[ServiceId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NTransactionRecipient]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NTransactionRecipient](
	[Id] [varchar](50) NOT NULL,
	[TransactionId] [varchar](50) NOT NULL,
	[Uri] [varchar](500) NOT NULL,
 CONSTRAINT [PK_NTransactionRecipient] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[NTransactionRealtimeDetails]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NTransactionRealtimeDetails](
	[Id] [varchar](50) NOT NULL,
	[StatusType] [varchar](50) NOT NULL,
	[TransactionId] [varchar](50) NOT NULL,
	[Detail] [varchar](4000) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[OrderIndex] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_TransactionRealtimeActivityDetail] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[NTransactionNotification]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NTransactionNotification](
	[Id] [varchar](50) NOT NULL,
	[TransactionId] [varchar](50) NOT NULL,
	[Uri] [varchar](500) NOT NULL,
	[Type] [varchar](50) NOT NULL,
 CONSTRAINT [PK_NTransactionNotification] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[NAccountAuthRequest]    Script Date: 01/13/2011 09:37:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NAccountAuthRequest](
	[Id] [varchar](50) NOT NULL,
	[TransactionId] [varchar](50) NOT NULL,
	[RequestGeneratedOn] [datetime] NOT NULL,
	[RequestType] [varchar](255) NOT NULL,
	[NAASAccount] [varchar](500) NOT NULL,
	[FullName] [varchar](500) NOT NULL,
	[OrganizationAffiliation] [varchar](500) NOT NULL,
	[TelephoneNumber] [varchar](25) NOT NULL,
	[EmailAddress] [varchar](500) NOT NULL,
	[AffiliatedNodeId] [varchar](50) NOT NULL,
	[AffiliatedCounty] [varchar](255) NULL,
	[PurposeDescription] [varchar](4000) NULL,
	[RequestedNodeIds] [varchar](1000) NOT NULL,
	[AuthorizationAccountId] [varchar](50) NULL,
	[AuthorizationComments] [varchar](4000) NULL,
	[AuthorizationGeneratedOn] [datetime] NULL,
	[DidCreateInNaas] [varchar](1) NULL,
 CONSTRAINT [PK_NAccountAuthenticationRequest] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NAccountAuthRequest_AuthorizationAccountId] ON [NAccountAuthRequest] 
(
	[AuthorizationAccountId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NAccountAuthRequest_TransactionId] ON [NAccountAuthRequest] 
(
	[TransactionId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NDocument]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NDocument](
	[Id] [varchar](50) NOT NULL,
	[TransactionId] [varchar](50) NOT NULL,
	[DocumentName] [varchar](255) NOT NULL,
	[Type] [varchar](255) NOT NULL,
	[DocumentId] [varchar](255) NOT NULL,
	[Status] [varchar](50) NOT NULL,
	[StatusDetail] [varchar](4000) NULL,
 CONSTRAINT [PK_Document] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_Document_TransactionIdDocumentName] UNIQUE NONCLUSTERED 
(
	[TransactionId] ASC,
	[DocumentName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NDocument_DocumentId] ON [NDocument] 
(
	[DocumentId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NDocument_DocumentName] ON [NDocument] 
(
	[DocumentName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NDocument_Status] ON [NDocument] 
(
	[Status] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NDocument_TransactionId] ON [NDocument] 
(
	[TransactionId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NDocument_Type] ON [NDocument] 
(
	[Type] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NActivity]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NActivity](
	[Id] [varchar](50) NOT NULL,
	[Type] [varchar](128) NOT NULL,
	[TransactionId] [varchar](50) NULL,
	[IP] [varchar](64) NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[WebMethod] [varchar](50) NULL,
	[FlowName] [varchar](255) NULL,
	[Operation] [varchar](255) NULL,
 CONSTRAINT [PK_Activity] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NActivity_FlowName] ON [NActivity] 
(
	[FlowName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NActivity_IP] ON [NActivity] 
(
	[IP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NActivity_ModifiedBy] ON [NActivity] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NActivity_ModifiedOn] ON [NActivity] 
(
	[ModifiedOn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NActivity_Operation] ON [NActivity] 
(
	[Operation] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NActivity_TransactionId] ON [NActivity] 
(
	[TransactionId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NActivity_Type] ON [NActivity] 
(
	[Type] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NActivity_WebMethod] ON [NActivity] 
(
	[WebMethod] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NActivityDetail_ModifiedOn] ON [NActivity] 
(
	[ModifiedOn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NNodeNotification]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NNodeNotification](
	[Id] [varchar](50) NOT NULL,
	[TransactionId] [varchar](50) NOT NULL,
	[NotifyData] [varchar](max) NOT NULL,
 CONSTRAINT [PK_NNodeNotification] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[NRequest]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NRequest](
	[Id] [varchar](50) NOT NULL,
	[TransactionId] [varchar](50) NULL,
	[ServiceId] [varchar](50) NOT NULL,
	[RowIndex] [int] NOT NULL,
	[MaxRowCount] [int] NOT NULL,
	[RequestType] [varchar](50) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[ParamsByName] [char](1) NOT NULL,
 CONSTRAINT [PK_Request] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NRequest_ModifiedBy] ON [NRequest] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NRequest_RequestType] ON [NRequest] 
(
	[RequestType] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NRequest_ServiceId] ON [NRequest] 
(
	[ServiceId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NRequest_TransactionId] ON [NRequest] 
(
	[TransactionId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NSchedule]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NSchedule](
	[Id] [varchar](50) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[FlowId] [varchar](50) NULL,
	[StartOn] [datetime] NOT NULL,
	[EndOn] [datetime] NOT NULL,
	[SourceType] [varchar](50) NOT NULL,
	[SourceId] [varchar](255) NOT NULL,
	[SourceFlow] [varchar](255) NULL,
	[SourceOperation] [varchar](255) NULL,
	[TargetType] [varchar](50) NULL,
	[TargetId] [varchar](255) NULL,
	[TargetFlow] [varchar](255) NULL,
	[TargetOperation] [varchar](255) NULL,
	[LastExecutedOn] [datetime] NULL,
	[NextRun] [datetime] NOT NULL,
	[FrequencyType] [varchar](50) NOT NULL,
	[Frequency] [int] NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[IsActive] [varchar](1) NOT NULL,
	[IsRunNow] [varchar](1) NOT NULL,
	[ExecuteStatus] [varchar](50) NOT NULL,
	[LastExecuteActivityId] [varchar](50) NULL,
 CONSTRAINT [PK_Schedule] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_Schedule_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_EndOn] ON [NSchedule] 
(
	[EndOn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_FlowId] ON [NSchedule] 
(
	[FlowId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_Frequency] ON [NSchedule] 
(
	[Frequency] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_FrequencyType] ON [NSchedule] 
(
	[FrequencyType] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_IsActive] ON [NSchedule] 
(
	[IsActive] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_IsRunNow] ON [NSchedule] 
(
	[IsRunNow] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_LastExecuteActivityId] ON [NSchedule] 
(
	[LastExecuteActivityId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_LastExecutedOn] ON [NSchedule] 
(
	[LastExecutedOn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_ModifiedBy] ON [NSchedule] 
(
	[ModifiedBy] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_ModifiedOn] ON [NSchedule] 
(
	[ModifiedOn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_Name] ON [NSchedule] 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_NextRun] ON [NSchedule] 
(
	[NextRun] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NSchedule_StartOn] ON [NSchedule] 
(
	[StartOn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NRequestArg]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NRequestArg](
	[Id] [varchar](50) NOT NULL,
	[RequestId] [varchar](50) NOT NULL,
	[ArgName] [varchar](255) NOT NULL,
	[ArgValue] [varchar](4000) NULL,
 CONSTRAINT [PK_RequestArg] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NRequestArg_RequestId] ON [NRequestArg] 
(
	[RequestId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NDocumentContent]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NDocumentContent](
	[DocumentId] [varchar](50) NOT NULL,
	[Data] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_NDocumentContent] PRIMARY KEY CLUSTERED 
(
	[DocumentId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[NActivityDetail]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NActivityDetail](
	[Id] [varchar](50) NOT NULL,
	[ActivityId] [varchar](50) NOT NULL,
	[Detail] [varchar](max) NOT NULL,
	[ModifiedOn] [datetime] NOT NULL,
	[OrderIndex] [int] NULL,
 CONSTRAINT [PK_ActivityDetail] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NActivityDetail_ActivityId] ON [NActivityDetail] 
(
	[ActivityId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NActivityDetail_ModifiedOn] ON [NActivityDetail] 
(
	[ModifiedOn] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NActivityDetail_OrderIndex] ON [NActivityDetail] 
(
	[OrderIndex] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NAccountAuthRequestFlow]    Script Date: 01/13/2011 09:37:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NAccountAuthRequestFlow](
	[Id] [varchar](50) NOT NULL,
	[AccountAuthRequestId] [varchar](50) NOT NULL,
	[FlowName] [varchar](255) NOT NULL,
	[AccessGranted] [varchar](1) NULL,
 CONSTRAINT [PK_NAccountAuthRequestFlow] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NAccountAuthRequestFlow_AccountAuthRequestId] ON [NAccountAuthRequestFlow] 
(
	[AccountAuthRequestId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NScheduleSourceArg]    Script Date: 01/13/2011 09:37:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [NScheduleSourceArg](
	[Id] [varchar](50) NOT NULL,
	[ScheduleId] [varchar](50) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[Value] [varchar](max) NULL,
 CONSTRAINT [PK_NScheduleSourceArg] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_ScheduleSourceArg_ScheduleIdName] UNIQUE NONCLUSTERED 
(
	[ScheduleId] ASC,
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IDX_NScheduleSourceArg_Name] ON [NScheduleSourceArg] 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_NScheduleSourceArg_ScheduleId] ON [NScheduleSourceArg] 
(
	[ScheduleId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  ForeignKey [FK_Account_Account]    Script Date: 01/13/2011 09:37:02 ******/
ALTER TABLE [NAccount]  WITH CHECK ADD  CONSTRAINT [FK_Account_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
GO
ALTER TABLE [NAccount] CHECK CONSTRAINT [FK_Account_Account]
GO
/****** Object:  ForeignKey [FK_AccountAuthenticationRequest_Transaction]    Script Date: 01/13/2011 09:37:02 ******/
ALTER TABLE [NAccountAuthRequest]  WITH CHECK ADD  CONSTRAINT [FK_AccountAuthenticationRequest_Transaction] FOREIGN KEY([TransactionId])
REFERENCES [NTransaction] ([Id])
GO
ALTER TABLE [NAccountAuthRequest] CHECK CONSTRAINT [FK_AccountAuthenticationRequest_Transaction]
GO
/****** Object:  ForeignKey [FK_AccountAuthRequest_Account]    Script Date: 01/13/2011 09:37:02 ******/
ALTER TABLE [NAccountAuthRequest]  WITH CHECK ADD  CONSTRAINT [FK_AccountAuthRequest_Account] FOREIGN KEY([AuthorizationAccountId])
REFERENCES [NAccount] ([Id])
GO
ALTER TABLE [NAccountAuthRequest] CHECK CONSTRAINT [FK_AccountAuthRequest_Account]
GO
/****** Object:  ForeignKey [FK_AccountAuthRequestFlow_AccountAuthRequest]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NAccountAuthRequestFlow]  WITH CHECK ADD  CONSTRAINT [FK_AccountAuthRequestFlow_AccountAuthRequest] FOREIGN KEY([AccountAuthRequestId])
REFERENCES [NAccountAuthRequest] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [NAccountAuthRequestFlow] CHECK CONSTRAINT [FK_AccountAuthRequestFlow_AccountAuthRequest]
GO
/****** Object:  ForeignKey [FK_AccountIdPolicy_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NAccountPolicy]  WITH CHECK ADD  CONSTRAINT [FK_AccountIdPolicy_Account] FOREIGN KEY([AccountId])
REFERENCES [NAccount] ([Id])
GO
ALTER TABLE [NAccountPolicy] CHECK CONSTRAINT [FK_AccountIdPolicy_Account]
GO
/****** Object:  ForeignKey [FK_AccountPolicy_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NAccountPolicy]  WITH CHECK ADD  CONSTRAINT [FK_AccountPolicy_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
GO
ALTER TABLE [NAccountPolicy] CHECK CONSTRAINT [FK_AccountPolicy_Account]
GO
/****** Object:  ForeignKey [FK_Activity_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NActivity]  WITH CHECK ADD  CONSTRAINT [FK_Activity_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NActivity] CHECK CONSTRAINT [FK_Activity_Account]
GO
/****** Object:  ForeignKey [FK_Activity_Transaction]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NActivity]  WITH CHECK ADD  CONSTRAINT [FK_Activity_Transaction] FOREIGN KEY([TransactionId])
REFERENCES [NTransaction] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NActivity] CHECK CONSTRAINT [FK_Activity_Transaction]
GO
/****** Object:  ForeignKey [FK_ActivityDetail_Activity]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NActivityDetail]  WITH CHECK ADD  CONSTRAINT [FK_ActivityDetail_Activity] FOREIGN KEY([ActivityId])
REFERENCES [NActivity] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NActivityDetail] CHECK CONSTRAINT [FK_ActivityDetail_Activity]
GO
/****** Object:  ForeignKey [FK_Config_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NConfig]  WITH CHECK ADD  CONSTRAINT [FK_Config_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NConfig] CHECK CONSTRAINT [FK_Config_Account]
GO
/****** Object:  ForeignKey [FK_Connection_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NConnection]  WITH CHECK ADD  CONSTRAINT [FK_Connection_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
GO
ALTER TABLE [NConnection] CHECK CONSTRAINT [FK_Connection_Account]
GO
/****** Object:  ForeignKey [FK_Document_Transaction]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NDocument]  WITH CHECK ADD  CONSTRAINT [FK_Document_Transaction] FOREIGN KEY([TransactionId])
REFERENCES [NTransaction] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NDocument] CHECK CONSTRAINT [FK_Document_Transaction]
GO
/****** Object:  ForeignKey [FK_DocumentContent_Document]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NDocumentContent]  WITH CHECK ADD  CONSTRAINT [FK_DocumentContent_Document] FOREIGN KEY([DocumentId])
REFERENCES [NDocument] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NDocumentContent] CHECK CONSTRAINT [FK_DocumentContent_Document]
GO
/****** Object:  ForeignKey [FK_Flow_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NFlow]  WITH CHECK ADD  CONSTRAINT [FK_Flow_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NFlow] CHECK CONSTRAINT [FK_Flow_Account]
GO
/****** Object:  ForeignKey [FK_NodeNotification_Transaction]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NNodeNotification]  WITH CHECK ADD  CONSTRAINT [FK_NodeNotification_Transaction] FOREIGN KEY([TransactionId])
REFERENCES [NTransaction] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NNodeNotification] CHECK CONSTRAINT [FK_NodeNotification_Transaction]
GO
/****** Object:  ForeignKey [FK_ModifiedBy_Notification_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NNotification]  WITH CHECK ADD  CONSTRAINT [FK_ModifiedBy_Notification_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
GO
ALTER TABLE [NNotification] CHECK CONSTRAINT [FK_ModifiedBy_Notification_Account]
GO
/****** Object:  ForeignKey [FK_Notification_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NNotification]  WITH CHECK ADD  CONSTRAINT [FK_Notification_Account] FOREIGN KEY([AccountId])
REFERENCES [NAccount] ([Id])
GO
ALTER TABLE [NNotification] CHECK CONSTRAINT [FK_Notification_Account]
GO
/****** Object:  ForeignKey [FK_Notification_Flow]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NNotification]  WITH CHECK ADD  CONSTRAINT [FK_Notification_Flow] FOREIGN KEY([FlowId])
REFERENCES [NFlow] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NNotification] CHECK CONSTRAINT [FK_Notification_Flow]
GO
/****** Object:  ForeignKey [FK_Partner_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NPartner]  WITH CHECK ADD  CONSTRAINT [FK_Partner_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NPartner] CHECK CONSTRAINT [FK_Partner_Account]
GO
/****** Object:  ForeignKey [FK_Plugin_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NPlugin]  WITH CHECK ADD  CONSTRAINT [FK_Plugin_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
GO
ALTER TABLE [NPlugin] CHECK CONSTRAINT [FK_Plugin_Account]
GO
/****** Object:  ForeignKey [FK_Plugin_Flow]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NPlugin]  WITH CHECK ADD  CONSTRAINT [FK_Plugin_Flow] FOREIGN KEY([FlowId])
REFERENCES [NFlow] ([Id])
GO
ALTER TABLE [NPlugin] CHECK CONSTRAINT [FK_Plugin_Flow]
GO
/****** Object:  ForeignKey [FK_ModifiedBy_Request_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NRequest]  WITH CHECK ADD  CONSTRAINT [FK_ModifiedBy_Request_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
GO
ALTER TABLE [NRequest] CHECK CONSTRAINT [FK_ModifiedBy_Request_Account]
GO
/****** Object:  ForeignKey [FK_Request_Service]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NRequest]  WITH NOCHECK ADD  CONSTRAINT [FK_Request_Service] FOREIGN KEY([ServiceId])
REFERENCES [NService] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NRequest] CHECK CONSTRAINT [FK_Request_Service]
GO
/****** Object:  ForeignKey [FK_Request_Transaction]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NRequest]  WITH NOCHECK ADD  CONSTRAINT [FK_Request_Transaction] FOREIGN KEY([TransactionId])
REFERENCES [NTransaction] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NRequest] CHECK CONSTRAINT [FK_Request_Transaction]
GO
/****** Object:  ForeignKey [FK_RequestArg_Request]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NRequestArg]  WITH NOCHECK ADD  CONSTRAINT [FK_RequestArg_Request] FOREIGN KEY([RequestId])
REFERENCES [NRequest] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NRequestArg] CHECK CONSTRAINT [FK_RequestArg_Request]
GO
/****** Object:  ForeignKey [FK_Schedule_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NSchedule]  WITH CHECK ADD  CONSTRAINT [FK_Schedule_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NSchedule] CHECK CONSTRAINT [FK_Schedule_Account]
GO
/****** Object:  ForeignKey [FK_Schedule_Activity]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NSchedule]  WITH CHECK ADD  CONSTRAINT [FK_Schedule_Activity] FOREIGN KEY([LastExecuteActivityId])
REFERENCES [NActivity] ([Id])
GO
ALTER TABLE [NSchedule] CHECK CONSTRAINT [FK_Schedule_Activity]
GO
/****** Object:  ForeignKey [FK_Schedule_Flow]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NSchedule]  WITH CHECK ADD  CONSTRAINT [FK_Schedule_Flow] FOREIGN KEY([FlowId])
REFERENCES [NFlow] ([Id])
GO
ALTER TABLE [NSchedule] CHECK CONSTRAINT [FK_Schedule_Flow]
GO
/****** Object:  ForeignKey [FK_ScheduleSourceArg_Schedule]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NScheduleSourceArg]  WITH CHECK ADD  CONSTRAINT [FK_ScheduleSourceArg_Schedule] FOREIGN KEY([ScheduleId])
REFERENCES [NSchedule] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NScheduleSourceArg] CHECK CONSTRAINT [FK_ScheduleSourceArg_Schedule]
GO
/****** Object:  ForeignKey [FK_Service_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NService]  WITH CHECK ADD  CONSTRAINT [FK_Service_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
GO
ALTER TABLE [NService] CHECK CONSTRAINT [FK_Service_Account]
GO
/****** Object:  ForeignKey [FK_Service_Flow]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NService]  WITH CHECK ADD  CONSTRAINT [FK_Service_Flow] FOREIGN KEY([FlowId])
REFERENCES [NFlow] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NService] CHECK CONSTRAINT [FK_Service_Flow]
GO
/****** Object:  ForeignKey [FK_ServiceArg_Service]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NServiceArg]  WITH CHECK ADD  CONSTRAINT [FK_ServiceArg_Service] FOREIGN KEY([ServiceId])
REFERENCES [NService] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NServiceArg] CHECK CONSTRAINT [FK_ServiceArg_Service]
GO
/****** Object:  ForeignKey [FK_ServiceConn_Connection]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NServiceConn]  WITH CHECK ADD  CONSTRAINT [FK_ServiceConn_Connection] FOREIGN KEY([ConnectionId])
REFERENCES [NConnection] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NServiceConn] CHECK CONSTRAINT [FK_ServiceConn_Connection]
GO
/****** Object:  ForeignKey [FK_ServiceConn_Service]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NServiceConn]  WITH CHECK ADD  CONSTRAINT [FK_ServiceConn_Service] FOREIGN KEY([ServiceId])
REFERENCES [NService] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NServiceConn] CHECK CONSTRAINT [FK_ServiceConn_Service]
GO
/****** Object:  ForeignKey [FK_ModifiedBy_Transaction_Account]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NTransaction]  WITH CHECK ADD  CONSTRAINT [FK_ModifiedBy_Transaction_Account] FOREIGN KEY([ModifiedBy])
REFERENCES [NAccount] ([Id])
GO
ALTER TABLE [NTransaction] CHECK CONSTRAINT [FK_ModifiedBy_Transaction_Account]
GO
/****** Object:  ForeignKey [FK_Transaction_Flow]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NTransaction]  WITH CHECK ADD  CONSTRAINT [FK_Transaction_Flow] FOREIGN KEY([FlowId])
REFERENCES [NFlow] ([Id])
GO
ALTER TABLE [NTransaction] CHECK CONSTRAINT [FK_Transaction_Flow]
GO
/****** Object:  ForeignKey [FK_TransactionNotification_Transaction]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NTransactionNotification]  WITH CHECK ADD  CONSTRAINT [FK_TransactionNotification_Transaction] FOREIGN KEY([TransactionId])
REFERENCES [NTransaction] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NTransactionNotification] CHECK CONSTRAINT [FK_TransactionNotification_Transaction]
GO
/****** Object:  ForeignKey [FK_TransactionRealtimeActivityDetail_Transaction]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NTransactionRealtimeDetails]  WITH CHECK ADD  CONSTRAINT [FK_TransactionRealtimeActivityDetail_Transaction] FOREIGN KEY([TransactionId])
REFERENCES [NTransaction] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NTransactionRealtimeDetails] CHECK CONSTRAINT [FK_TransactionRealtimeActivityDetail_Transaction]
GO
/****** Object:  ForeignKey [FK_TransactionRecipient_Transaction]    Script Date: 01/13/2011 09:37:03 ******/
ALTER TABLE [NTransactionRecipient]  WITH CHECK ADD  CONSTRAINT [FK_TransactionRecipient_Transaction] FOREIGN KEY([TransactionId])
REFERENCES [NTransaction] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [NTransactionRecipient] CHECK CONSTRAINT [FK_TransactionRecipient_Transaction]
GO
