#! /bin/bash

function showHelp() {
    
    echo
    echo "Counts opening and closing elements in an NY-DWQ xml file."
    echo "Writes results to standar out."
    echo "Usage:"
    echo "dwq-element-count dwq-xml-file"
    echo
    echo " - dwq-xml-file: the file to evaluate"
}

function countElement() {

    echo -n \<$1\>': ' 
    grep \<$1\> $2 | wc -l

    echo -n \</$1\>': ' 
    grep \</$1\> $2 | wc -l
}

if [ -z "$1" ] 
then
    showHelp
    exit 1
fi

countElement 'Analyte' $1;

countElement 'AnalyteGroup' $1;

countElement 'AnnualOperPeriod' $1;

countElement 'Casing' $1;

countElement 'Deficiency' $1;

countElement 'Facility' $1;

countElement 'AnalyteGroup' $1;

countElement 'Laboratory' $1;

countElement 'MCLValue' $1;

countElement 'ObjectiveProcess' $1;

countElement 'Purchase' $1;

countElement 'Sample' $1;

countElement 'SampleResult' $1;

countElement 'SamplingPoint' $1;

countElement 'Screen' $1;

countElement 'ServiceArea' $1;

countElement 'SiteVisit' $1;

countElement 'TreatmentUnit' $1;

countElement 'Violation' $1;

countElement 'WaterSystem' $1;

countElement 'WaterSystemAffiliation' $1;


