--This script creates the two SQL Server tables needed to run the OpenNode2 MapForce Plugin Tutorial

CREATE TABLE BEACH(
	EPA_BEACH_ID VARCHAR(25) NOT NULL,
	BEACH_NAME VARCHAR(50) NOT NULL,
	BEACH_DESCRIPTION VARCHAR(100) NULL,
	STATE_CD char(2) NOT NULL,
	FIPS_CD char(5) NOT NULL,
	WATERBODY_NAME_CD VARCHAR(25) NOT NULL,
	ACCESSIBILITY_TYPE_CD VARCHAR(25) NOT NULL)
GO

ALTER TABLE BEACH 
ADD CONSTRAINT PK_BEACH PRIMARY KEY ( EPA_BEACH_ID )
GO

CREATE TABLE BEACH_ACTIVITY(
	ACTIVITY_ID VARCHAR(40) NOT NULL,
	EPA_BEACH_ID VARCHAR(25) NOT NULL,
	ACTIVITY_TYPE VARCHAR(25) NOT NULL,
	ACTIVITY_NAME VARCHAR(50) NOT NULL,
	START_DATE DATETIME NOT NULL,
	REOPEN_DATE DATETIME NOT NULL,
	REASON_TYPE_CD VARCHAR(25) NOT NULL,
	POLLUTION_SOURCE_CD VARCHAR(25) NOT NULL,
	INDICATOR_TYPE_CD VARCHAR(25) NOT NULL)
GO

ALTER TABLE BEACH_ACTIVITY 
ADD CONSTRAINT PK_BEACH_ACTIVITY PRIMARY KEY ( ACTIVITY_ID )
Go

ALTER TABLE BEACH_ACTIVITY  ADD CONSTRAINT FK_BEACH_ACTIVITY_BEACH FOREIGN KEY(EPA_BEACH_ID)
REFERENCES BEACH (EPA_BEACH_ID)
GO
