select * from UIS_PROGRAMS;


select * from UIS_GEOGRAPHIC_LOCATION where UIS_GEOGRAPHIC_LOCATION.SITE_SEQ in 
(select UIS_SITE.SITE_SEQ from UIS_SITE where UIS_SITE.PROGRAMS_SEQ = 100);

select g.GEOGRAPHIC_LOCATION_SEQ, g.SITE_SEQ, g.GIS_ID, g.COLLECTION_METHOD, g.ACCURACY, 
g.ACCURACY_UNIT, g.DATUM, g.LATITUDE, g.LONGITUDE, g.MODIFIED_BY, g.LAST_MODIFIED, 
s.SITE_SEQ, p.SITE_ID
from UIS_GEOGRAPHIC_LOCATION g, UIS_SITE s, UIS_PROGRAMS p
where s.SITE_SEQ = g.SITE_SEQ and p.PROGRAMS_SEQ = s.PROGRAMS_SEQ
order by p.SITE_ID;


select s.ASSESS_DOH, s.DOH_ASSESS_MOD, p.SITE_ID 
from UIS_SITE s, UIS_PROGRAMS p
where p.PROGRAMS_SEQ = s.PROGRAMS_SEQ
order by p.SITE_ID;

select * from UIS_SITE

select * from UIS_SITE where rownum <= 200 order by SITE_SEQ

select count(*) from UIS_SITE where DOH_ASSESS_MOD  is not null

select max(length(UIS_SITE.DESCRIPTION)) from UIS_SITE

select count(*) from UIS_PROGRAMS

select count(*) from UIS_PROGRAM_AFFILIATION

select count(*) from UIS_GEOGRAPHIC_LOCATION

select * from UIS_PROGRAMS

select count(*) from UIS_REMEDY

select count(*) from UIS_OPERABLE_UNIT

select count(*) from UIS_MATERIAL

select count(*) from UIS_MATERIAL_CODES

select count(*) from UIS_MATERIAL_FAMILY_CODES

select count(*) from UIS_MEDIA_AFFECTED_CODES

select count(*) from UIS_MEDIA_AFFECTED

select * from UIS_MEDIA_AFFECTED

select * from UIS_FACILITY where UIS_FACILITY.PROGRAMS_SEQ = 5;

select * from UIS_PROGRAM_AFFILIATION where UIS_PROGRAM_AFFILIATION.PROGRAMS_SEQ = 340;

select * from UIS_PROGRAMS inner join UIS_FACILITY on UIS_PROGRAMS.PROGRAMS_SEQ = UIS_FACILITY.PROGRAMS_SEQ;

select p.PROGRAMS_SEQ, p.SITE_ID, p.FACILITY_ID, p.PROGRAM_NUMBER, p.PROGRAM_TYPE_CODE, 
    p.PROGRAM_TYPE_NAME, p.FACILITY_NAME, p.START_DATE, p.START_QUALIFIER, p.END_DATE, 
    p.END_QUALIFIER, p.EDOCS_PATH, p.NEW_EDOCS_PATH, p.EDOC_NEW, p.LAST_MODIFIED, 
    f.FACILITY_SEQ, f.ADDRESS_ONE, f.ADDRESS_TWO, f.LOCALITY, f.ZIP_CODE, f.SWIS_CODE 
    from UIS_PROGRAMS p, UIS_FACILITY f 
    where f.FACILITY_ID = p.FACILITY_ID and f.PROGRAMS_SEQ = p.PROGRAMS_SEQ and  ROWNUM <= 50;
    
select * from UIS_PROGRAM_AFFILIATION where UIS_PROGRAM_AFFILIATION.PROGRAMS_SEQ = '17716.0'

SELECT COLUMN_NAME
    FROM ALL_COL_COMMENTS
    WHERE TABLE_NAME LIKE 'UIS_GEOGRAPHIC_LOCATION'
    
select count(*) from UIS_SPILLS

select count(*) from UIS_CLASS_CHANGE where CLASS_CHANGE_SEQ = '10337.0'

SELECT * FROM UIS_PROGRAMS


select a.PROGRAM_AFFILIATION_SEQ, a.PROGRAMS_SEQ, a.AFFILIATION_ID, a.AFFILIATION_TYPE_CODE, a.AFFILIATION_TYPE_NAME, 
    a.AFFILIATION_SUBTYPE_CODE, a.AFFILIATION_SUBTYPE_NAME, a.SEQ_NUMBER, a.START_DATE, a.END_DATE, a.COMPANY, a.FEDERAL_ID, 
    a.CONTACT_TITLE, a.CONTACT_NAME, a.ADDRESS_ONE, a.ADDRESS_TWO, a.CITY, a.STATE, a.ZIP_CODE, a.COUNTRY_CODE, a.PHONE, 
    a.PHONE_EXT, a.EMAIL, a.FAX, a.MODIFIED_BY, a.LAST_MODIFIED, p.SITE_ID, p.FACILITY_ID
from UIS_PROGRAM_AFFILIATION a, UIS_PROGRAMS p 
where a.PROGRAMS_SEQ = 17443 
    and p.PROGRAMS_SEQ = a.PROGRAMS_SEQ

select * from UIS_PROJECTS where UIS_PROJECTS.PROJECT_ID = 12869


SELECT m.MATERIAL_SEQ, m.OPERABLE_UNIT_SEQ, m.MATERIAL_ID, m.MED_RECEPT, m.MATERIAL_CODE, m.TARGET_LEVEL, m.QUANTITY, 
    m.UNITS, m.RECOVERED, m.PM_CONTAMINANT_COMMENTS, m.MODIFIED_BY, m.LAST_MODIFIED, a.MEDIA_AFFECTED_CODE, 
    a.MEDIA_AFFECTED_TARGET_LEVEL, u.OPERABLE_UNIT_ID 
FROM UIS_MATERIAL m, UIS_MEDIA_AFFECTED a, UIS_OPERABLE_UNIT u 
WHERE u.OPERABLE_UNIT_SEQ = m.OPERABLE_UNIT_SEQ or a.MATERIAL_SEQ = m.MATERIAL_SEQ
ORDER BY m.MATERIAL_SEQ;


SELECT m.MATERIAL_SEQ, m.OPERABLE_UNIT_SEQ, m.MATERIAL_ID, m.MED_RECEPT, m.MATERIAL_CODE, m.TARGET_LEVEL, m.QUANTITY, 
    m.UNITS, m.RECOVERED, m.PM_CONTAMINANT_COMMENTS, m.MODIFIED_BY, m.LAST_MODIFIED, u.OPERABLE_UNIT_ID 
FROM UIS_MATERIAL m, UIS_OPERABLE_UNIT u 
WHERE u.OPERABLE_UNIT_SEQ = m.OPERABLE_UNIT_SEQ
ORDER BY m.MATERIAL_SEQ;

select m.MATERIAL_SEQ, m.OPERABLE_UNIT_SEQ, m.MATERIAL_ID, m.MED_RECEPT, m.MATERIAL_CODE, m.TARGET_LEVEL, m.QUANTITY, 
    m.UNITS, m.RECOVERED, m.PM_CONTAMINANT_COMMENTS, m.MODIFIED_BY, m.LAST_MODIFIED, u.OPERABLE_UNIT_ID 
from UIS_MATERIAL m
join UIS_OPERABLE_UNIT u 
on (u.OPERABLE_UNIT_SEQ = m.OPERABLE_UNIT_SEQ)
order by m.MATERIAL_SEQ;

select * from UIS_MEDIA_AFFECTED order by UIS_MEDIA_AFFECTED.MATERIAL_SEQ

-- dates
select count(*) from UIS_CLASS_CHANGE

select * from UIS_CLASS_CHANGE



select 
to_char(ASST_DIV_DIR_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
to_char(BUREAU_APPROV_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
to_char(COMPLETION_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
to_char(DATE_CHANGE_RCVD,'dd-mon-yyyy.hh24:mm:ss'),
    
to_char(DEE_APPROV_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
to_char(DOH_APPROV_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
to_char(DUE_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
to_char(ENGINEER_SIGN_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
    
to_char(FINALIZED_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
to_char(HOLD_START_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
to_char(PKG_HOLD_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
to_char(REGION_APPROV_DATE,'dd-mon-yyyy.hh24:mm:ss'),
    
to_char(REM_APPROV_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
to_char(SEC_CHIEF_APPROV_DATE,'dd-mon-yyyy.hh24:mm:ss'), 
to_char(SECTION_APPROV_DATE,'dd-mon-yyyy.hh24:mm:ss') 
from UIS_CLASS_CHANGE;

SELECT * FROM UIS_SITE WHERE PROGRAMS_SEQ = 12313

select * from UIS_MATERIAL where UIS_MATERIAL.MATERIAL_ID=2156877

delete from DW_CLOB_PROCESS
select * from DW_CLOB_PROCESS

-- testing issues

select START_DATE from UIS_PROGRAM_AFFILIATION

select * from UIS_GEOGRAPHIC_LOCATION

select g.GEOGRAPHIC_LOCATION_SEQ, g.GIS_ID, g.PROGRAMS_SEQ, g.COLLECTION_METHOD, g.ACCURACY, g.ACCURACY_UNIT, 
g.DATUM, g.LATITUDE, g.LONGITUDE, g.MODIFIED_BY, g.LAST_MODIFIED, p.SITE_ID, p.PROGRAMS_SEQ 
from UIS_GEOGRAPHIC_LOCATION g, UIS_PROGRAMS p 
where p.PROGRAMS_SEQ = g.PROGRAMS_SEQ  
order by p.SITE_ID;

select g.GEOGRAPHIC_LOCATION_SEQ, g.PROGRAMS_SEQ, g.GIS_ID, g.COLLECTION_METHOD, g.ACCURACY, g.ACCURACY_UNIT, 
g.DATUM, g.LATITUDE, g.LONGITUDE, g.MODIFIED_BY, g.LAST_MODIFIED, p.SITE_ID 
from UIS_GEOGRAPHIC_LOCATION g, UIS_PROGRAMS p 
where p.PROGRAMS_SEQ = g.PROGRAMS_SEQ 
order by p.SITE_ID


select g.GEOGRAPHIC_LOCATION_SEQ, g.PROGRAMS_SEQ, g.GIS_ID, g.COLLECTION_METHOD, g.ACCURACY, g.ACCURACY_UNIT, 
g.DATUM, g.LATITUDE, g.LONGITUDE, g.MODIFIED_BY, g.LAST_MODIFIED, p.SITE_ID 
from UIS_GEOGRAPHIC_LOCATION g, UIS_PROGRAMS p 
where p.PROGRAMS_SEQ = g.PROGRAMS_SEQ 
and rownum <= ?  
order by p.SITE_ID

select * from DW_FACILITY where FACILITY_IDENTIFIER = 'INACT WL003' 
and WELL_PUMP_TYPE is not null 
and DW_WATER_SYSTEM_ID = 15656  

select WELL_PUMP_TYPE from DW_FACILITY where DW_FACILITY_ID = 18455