/*
Copyright (c) 2016, The Environmental Council of the States (ECOS)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE ;ODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/

/*****************************************************************************************************************************
 *
 *  Script Name:  RCRA_5.13-ORA-DDL.sql
 *
 *  Company:  Windsor Solutions, Inc.
 *
 *  Purpose:  This DDL script will build the Oracle database objects supporting the RCRA v5.13 data flow.
 *
 *  Maintenance:
 *
 *    Analyst         Date            Comment
 *    ----------      ----------      ------------------------------------------------------------------------------
 *    Windsor         03/20/2024      Created
 *
 ****************************************************************************************************************************
 */

CREATE TABLE "RCRA_CA_AREA"(
	"CA_AREA_ID" varchar2(40) NOT NULL,
	"CA_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"AREA_SEQ_NUM" number NULL,
	"FAC_WIDE_IND" char(1) NULL,
	"AREA_NAME" varchar2(40) NULL,
	"AIR_REL_IND" char(1) NULL,
	"GROUNDWATER_REL_IND" char(1) NULL,
	"SOIL_REL_IND" char(1) NULL,
	"SURFACE_WATER_REL_IND" char(1) NULL,
	"REGULATED_UNIT_IND" char(1) NULL,
	"EPA_RESP_PERSON_DATA_OWNER_CDE" char(2) NULL,
	"EPA_RESP_PERSON_ID" varchar2(5) NULL,
	"STA_RESP_PERSON_DATA_OWNER_CDE" char(2) NULL,
	"STA_RESP_PERSON_ID" varchar2(5) NULL,
	"SUPP_INFO_TXT" varchar2(2000) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"A_CREATED_DATE" DATE NULL,
	"DATA_ORIG" char(2) NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_CA_AREA" PRIMARY KEY 
(
	"CA_AREA_ID"
)
);


CREATE TABLE "RCRA_CA_AREA_REL_EVENT"(
	"CA_AREA_REL_EVENT_ID" varchar2(40) NOT NULL,
	"CA_AREA_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"ACT_LOC_CODE" char(2) NOT NULL,
	"CORCT_ACT_EVENT_DATA_OWNER_CDE" char(2) NOT NULL,
	"CORCT_ACT_EVENT_CODE" varchar2(7) NOT NULL,
	"EVENT_AGN_CODE" char(1) NOT NULL,
	"EVENT_SEQ_NUM" number NOT NULL,
 CONSTRAINT "PK_CA_AREA_REL_EVENT" PRIMARY KEY 
(
	"CA_AREA_REL_EVENT_ID"
)
);





CREATE TABLE "RCRA_CA_AUTH_REL_EVENT"(
	"CA_AUTH_REL_EVENT_ID" varchar2(40) NOT NULL,
	"CA_AUTHORITY_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"ACT_LOC_CODE" char(2) NOT NULL,
	"CORCT_ACT_EVENT_DATA_OWNER_CDE" char(2) NOT NULL,
	"CORCT_ACT_EVENT_CODE" varchar2(7) NOT NULL,
	"EVENT_AGN_CODE" char(1) NOT NULL,
	"EVENT_SEQ_NUM" number NOT NULL,
 CONSTRAINT "PK_CA_AUTH_REL_EVENT" PRIMARY KEY 
(
	"CA_AUTH_REL_EVENT_ID"
)
);





CREATE TABLE "RCRA_CA_AUTHORITY"(
	"CA_AUTHORITY_ID" varchar2(40) NOT NULL,
	"CA_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"ACT_LOC_CODE" char(2) NOT NULL,
	"AUTHORITY_DATA_OWNER_CODE" char(2) NOT NULL,
	"AUTHORITY_TYPE_CODE" char(1) NOT NULL,
	"AUTHORITY_AGN_CODE" char(1) NOT NULL,
	"AUTHORITY_EFFC_DATE" DATE NOT NULL,
	"ISSUE_DATE" DATE NULL,
	"END_DATE" DATE NULL,
	"ESTABLISHED_REPOSITORY_CODE" char(1) NULL,
	"RESP_LEAD_PROG_IDEN" char(1) NULL,
	"AUTHORITY_SUBORG_DATA_OWNR_CDE" char(2) NULL,
	"AUTHORITY_SUBORG_CODE" varchar2(10) NULL,
	"RESP_PERSON_DATA_OWNER_CODE" char(2) NULL,
	"RESP_PERSON_ID" varchar2(5) NULL,
	"SUPP_INFO_TXT" varchar2(2000) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"A_CREATED_DATE" DATE NULL,
	"DATA_ORIG" char(2) NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_CA_AUTHORITY" PRIMARY KEY 
(
	"CA_AUTHORITY_ID"
)
);





CREATE TABLE "RCRA_CA_EVENT"(
	"CA_EVENT_ID" varchar2(40) NOT NULL,
	"CA_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"ACT_LOC_CODE" char(2) NOT NULL,
	"CORCT_ACT_EVENT_DATA_OWNER_CDE" char(2) NOT NULL,
	"CORCT_ACT_EVENT_CODE" varchar2(7) NOT NULL,
	"EVENT_AGN_CODE" char(1) NOT NULL,
	"EVENT_SEQ_NUM" number NOT NULL,
	"ACTL_DATE" DATE NULL,
	"ORIGINAL_SCHEDULE_DATE" DATE NULL,
	"NEW_SCHEDULE_DATE" DATE NULL,
	"EVENT_SUBORG_DATA_OWNER_CODE" char(2) NULL,
	"EVENT_SUBORG_CODE" varchar2(10) NULL,
	"RESP_PERSON_DATA_OWNER_CODE" char(2) NULL,
	"RESP_PERSON_ID" varchar2(5) NULL,
	"SUPP_INFO_TXT" varchar2(2000) NULL,
	"PUBLIC_SUPP_INFO_TXT" varchar2(2000) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"A_CREATED_DATE" DATE NULL,
	"DATA_ORIG" char(2) NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_CA_EVENT" PRIMARY KEY 
(
	"CA_EVENT_ID"
)
);





CREATE TABLE "RCRA_CA_EVENT_COMMITMENT"(
	"CA_EVENT_COMMITMENT_ID" varchar2(40) NOT NULL,
	"CA_EVENT_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"COMMIT_LEAD" char(2) NOT NULL,
	"COMMIT_SEQ_NUM" number NOT NULL,
 CONSTRAINT "PK_CA_EVENT_COMMITMENT" PRIMARY KEY 
(
	"CA_EVENT_COMMITMENT_ID"
)
);





CREATE TABLE "RCRA_CA_FAC_SUBM"(
	"CA_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"CA_SUBM_ID" varchar2(40) NOT NULL,
	"HANDLER_ID" varchar2(12) NOT NULL,
 CONSTRAINT "PK_CA_FAC_SUBM" PRIMARY KEY 
(
	"CA_FAC_SUBM_ID"
)
);





CREATE TABLE "RCRA_CA_REL_PERMIT_UNIT"(
	"CA_REL_PERMIT_UNIT_ID" varchar2(40) NOT NULL,
	"CA_AREA_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"PERMIT_UNIT_SEQ_NUM" number NULL,
 CONSTRAINT "PK_CA_REL_PERMIT_UNIT" PRIMARY KEY 
(
	"CA_REL_PERMIT_UNIT_ID"
)
);





CREATE TABLE "RCRA_CA_STATUTORY_CITATION"(
	"CA_STATUTORY_CITATION_ID" varchar2(40) NOT NULL,
	"CA_AUTHORITY_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"STATUTORY_CITTION_DTA_OWNR_CDE" char(2) NOT NULL,
	"STATUTORY_CITATION_IDEN" char(1) NOT NULL,
 CONSTRAINT "PK_CA_STATUTORY_CITATION" PRIMARY KEY 
(
	"CA_STATUTORY_CITATION_ID"
)
);





CREATE TABLE "RCRA_CA_SUBM"(
	"CA_SUBM_ID" varchar2(40) NOT NULL,
 CONSTRAINT "PK_CA_SUBM" PRIMARY KEY 
(
	"CA_SUBM_ID"
)
);





CREATE TABLE "RCRA_CME_CITATION"(
	"CME_CITATION_ID" varchar2(40) NOT NULL,
	"CME_VIOL_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"CITATION_NAME_SEQ_NUM" number NOT NULL,
	"CITATION_NAME" varchar2(80) NULL,
	"CITATION_NAME_OWNER" char(2) NULL,
	"CITATION_NAME_TYPE" char(2) NULL,
	"NOTES" varchar2(4000) NULL,
 CONSTRAINT "PK_CME_CITATION" PRIMARY KEY 
(
	"CME_CITATION_ID"
)
);





CREATE TABLE "RCRA_CME_CSNY_DATE"(
	"CME_CSNY_DATE_ID" varchar2(40) NOT NULL,
	"CME_ENFRC_ACT_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"SNY_DATE" DATE NOT NULL,
 CONSTRAINT "PK_CME_CSNY_DATE" PRIMARY KEY 
(
	"CME_CSNY_DATE_ID"
)
);





CREATE TABLE "RCRA_CME_ENFRC_ACT"(
	"CME_ENFRC_ACT_ID" varchar2(40) NOT NULL,
	"CME_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"ENFRC_AGN_LOC_NAME" char(2) NOT NULL,
	"ENFRC_ACT_IDEN" varchar2(3) NOT NULL,
	"ENFRC_ACT_DATE" DATE NOT NULL,
	"ENFRC_AGN_NAME" char(1) NOT NULL,
	"ENFRC_DOCKET_NUM" varchar2(15) NULL,
	"ENFRC_ATTRY" varchar2(5) NULL,
	"CORCT_ACT_COMPT" char(1) NULL,
	"CNST_AGMT_FINAL_ORDER_SEQ_NUM" number NULL,
	"APPEAL_INIT_DATE" DATE NULL,
	"APPEAL_RSLN_DATE" DATE NULL,
	"DISP_STAT_DATE" DATE NULL,
	"DISP_STAT_OWNER" char(2) NULL,
	"DISP_STAT" char(2) NULL,
	"ENFRC_OWNER" char(2) NULL,
	"ENFRC_TYPE" char(3) NULL,
	"ENFRC_RESP_PERSON_OWNER" char(2) NULL,
	"ENFRC_RESP_PERSON_IDEN" varchar2(5) NULL,
	"ENFRC_RESP_SUBORG_OWNER" char(2) NULL,
	"ENFRC_RESP_SUBORG" varchar2(10) NULL,
	"NOTES" varchar2(4000) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"C_CREATED_DATE" DATE NULL,
	"DATA_ORIG" char(2) NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
	"FA_REQUIRED" char(1) NULL,
 CONSTRAINT "PK_CME_ENFRC_ACT" PRIMARY KEY 
(
	"CME_ENFRC_ACT_ID"
)
);





CREATE TABLE "RCRA_CME_EVAL"(
	"CME_EVAL_ID" varchar2(40) NOT NULL,
	"CME_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"EVAL_ACT_LOC" char(2) NOT NULL,
	"EVAL_IDEN" varchar2(3) NOT NULL,
	"EVAL_START_DATE" DATE NOT NULL,
	"EVAL_RESP_AGN" char(1) NOT NULL,
	"DAY_ZERO" DATE NULL,
	"FOUND_VIOL" char(1) NULL,
	"CTZN_CPLT_IND" char(1) NULL,
	"MULTIMEDIA_IND" char(1) NULL,
	"SAMPL_IND" char(1) NULL,
	"NOT_SUBTL_C_IND" char(1) NULL,
	"EVAL_TYPE_OWNER" char(2) NULL,
	"EVAL_TYPE" varchar2(3) NULL,
	"FOCUS_AREA_OWNER" char(2) NULL,
	"FOCUS_AREA" varchar2(3) NULL,
	"EVAL_RESP_PERSON_IDEN_OWNER" char(2) NULL,
	"EVAL_RESP_PERSON_IDEN" varchar2(5) NULL,
	"EVAL_RESP_SUBORG_OWNER" char(2) NULL,
	"EVAL_RESP_SUBORG" varchar2(10) NULL,
	"NOTES" varchar2(4000) NULL,
	"NOC_DATE" DATE NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"C_CREATED_DATE" DATE NULL,
	"DATA_ORIG" char(2) NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_CME_EVAL" PRIMARY KEY 
(
	"CME_EVAL_ID"
)
);





CREATE TABLE "RCRA_CME_EVAL_COMMIT"(
	"CME_EVAL_COMMIT_ID" varchar2(40) NOT NULL,
	"CME_EVAL_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"COMMIT_LEAD" char(2) NOT NULL,
	"COMMIT_SEQ_NUM" number NOT NULL,
 CONSTRAINT "PK_CME_EVAL_COMMIT" PRIMARY KEY 
(
	"CME_EVAL_COMMIT_ID"
)
);





CREATE TABLE "RCRA_CME_EVAL_VIOL"(
	"CME_EVAL_VIOL_ID" varchar2(40) NOT NULL,
	"CME_EVAL_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"VIOL_ACT_LOC" char(2) NOT NULL,
	"VIOL_SEQ_NUM" number NOT NULL,
	"AGN_WHICH_DTRM_VIOL" char(1) NOT NULL,
 CONSTRAINT "PK_CME_EVAL_VIOL" PRIMARY KEY 
(
	"CME_EVAL_VIOL_ID"
)
);





CREATE TABLE "RCRA_CME_FAC_SUBM"(
	"CME_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"CME_SUBM_ID" varchar2(40) NOT NULL,
	"EPA_HDLR_ID" char(12) NOT NULL,
 CONSTRAINT "PK_CME_FAC_SUBM" PRIMARY KEY 
(
	"CME_FAC_SUBM_ID"
)
);





CREATE TABLE "RCRA_CME_MEDIA"(
	"CME_MEDIA_ID" varchar2(40) NOT NULL,
	"CME_ENFRC_ACT_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"MULTIMEDIA_CODE_OWNER" char(2) NOT NULL,
	"MULTIMEDIA_CODE" varchar2(3) NOT NULL,
	"NOTES" varchar2(4000) NULL,
 CONSTRAINT "PK_CME_MEDIA" PRIMARY KEY 
(
	"CME_MEDIA_ID"
)
);





CREATE TABLE "RCRA_CME_MILESTONE"(
	"CME_MILESTONE_ID" varchar2(40) NOT NULL,
	"CME_ENFRC_ACT_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"MILESTONE_SEQ_NUM" number NOT NULL,
	"TECH_RQMT_IDEN" varchar2(50) NULL,
	"TECH_RQMT_DESC" varchar2(200) NULL,
	"MILESTONE_SCHD_COMP_DATE" DATE NULL,
	"MILESTONE_ACTL_COMP_DATE" DATE NULL,
	"MILESTONE_DFLT_DATE" DATE NULL,
	"NOTES" varchar2(4000) NULL,
 CONSTRAINT "PK_CME_MILESTONE" PRIMARY KEY 
(
	"CME_MILESTONE_ID"
)
);





CREATE TABLE "RCRA_CME_PNLTY"(
	"CME_PNLTY_ID" varchar2(40) NOT NULL,
	"CME_ENFRC_ACT_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"PNLTY_TYPE_OWNER" char(2) NOT NULL,
	"PNLTY_TYPE" varchar2(3) NOT NULL,
	"CASH_CIVIL_PNLTY_SOUGHT_AMOUNT" number(13, 2) NULL,
	"NOTES" varchar2(4000) NULL,
 CONSTRAINT "PK_CME_PNLTY" PRIMARY KEY 
(
	"CME_PNLTY_ID"
)
);





CREATE TABLE "RCRA_CME_PYMT"(
	"CME_PYMT_ID" varchar2(40) NOT NULL,
	"CME_PNLTY_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"PYMT_SEQ_NUM" number NOT NULL,
	"PYMT_DFLT_DATE" DATE NULL,
	"SCHD_PYMT_DATE" DATE NULL,
	"SCHD_PYMT_AMOUNT" number(13, 2) NULL,
	"ACTL_PYMT_DATE" DATE NULL,
	"ACTL_PAID_AMOUNT" number(13, 2) NULL,
	"NOTES" varchar2(4000) NULL,
 CONSTRAINT "PK_CME_PYMT" PRIMARY KEY 
(
	"CME_PYMT_ID"
)
);





CREATE TABLE "RCRA_CME_RQST"(
	"CME_RQST_ID" varchar2(40) NOT NULL,
	"CME_EVAL_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"RQST_SEQ_NUM" number NOT NULL,
	"DATE_OF_RQST" DATE NULL,
	"DATE_RESP_RCVD" DATE NULL,
	"RQST_AGN" char(1) NULL,
	"NOTES" varchar2(4000) NULL,
 CONSTRAINT "PK_CME_RQST" PRIMARY KEY 
(
	"CME_RQST_ID"
)
);





CREATE TABLE "RCRA_CME_SUBM"(
	"CME_SUBM_ID" varchar2(40) NOT NULL,
 CONSTRAINT "PK_CME_SUBM" PRIMARY KEY 
(
	"CME_SUBM_ID"
)
);





CREATE TABLE "RCRA_CME_SUPP_ENVR_PRJT"(
	"CME_SUPP_ENVR_PRJT_ID" varchar2(40) NOT NULL,
	"CME_ENFRC_ACT_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"SEP_SEQ_NUM" number NOT NULL,
	"SEP_EXPND_AMOUNT" number(13, 2) NULL,
	"SEP_SCHD_COMP_DATE" DATE NULL,
	"SEP_ACTL_DATE" DATE NULL,
	"SEP_DFLT_DATE" DATE NULL,
	"SEP_CODE_OWNER" char(2) NULL,
	"SEP_DESC_TXT" varchar2(3) NULL,
	"NOTES" varchar2(4000) NULL,
 CONSTRAINT "PK_CME_SUPP_ENVR_PRJT" PRIMARY KEY 
(
	"CME_SUPP_ENVR_PRJT_ID"
)
);





CREATE TABLE "RCRA_CME_VIOL"(
	"CME_VIOL_ID" varchar2(40) NOT NULL,
	"CME_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"VIOL_ACT_LOC" char(2) NOT NULL,
	"VIOL_SEQ_NUM" number NOT NULL,
	"AGN_WHICH_DTRM_VIOL" char(1) NOT NULL,
	"VIOL_TYPE_OWNER" char(2) NULL,
	"VIOL_TYPE" varchar2(10) NULL,
	"FORMER_CITATION_NAME" varchar2(35) NULL,
	"VIOL_DTRM_DATE" DATE NULL,
	"RTN_COMPL_ACTL_DATE" DATE NULL,
	"RTN_TO_COMPL_QUAL" char(1) NULL,
	"VIOL_RESP_AGN" char(1) NULL,
	"NOTES" varchar2(4000) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"C_CREATED_DATE" DATE NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_CME_VIOL" PRIMARY KEY 
(
	"CME_VIOL_ID"
)
);





CREATE TABLE "RCRA_CME_VIOL_ENFRC"(
	"CME_VIOL_ENFRC_ID" varchar2(40) NOT NULL,
	"CME_ENFRC_ACT_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"VIOL_SEQ_NUM" number NOT NULL,
	"AGN_WHICH_DTRM_VIOL" char(1) NOT NULL,
	"RTN_COMPL_SCHD_DATE" DATE NULL,
 CONSTRAINT "PK_CME_VIOL_ENFRC" PRIMARY KEY 
(
	"CME_VIOL_ENFRC_ID"
)
);





CREATE TABLE "RCRA_EM_EMANIFEST"(
	"EM_EMANIFEST_ID" varchar2(40) NOT NULL,
	"EM_SUBM_ID" varchar2(40) NOT NULL,
	"CREATED_DATE" DATE NULL,
	"UPDATED_DATE" DATE NULL,
	"MAN_TRACKING_NUM" varchar2(12) NULL,
	"STATUS" varchar2(17) NULL,
	"SUBM_TYPE" varchar2(14) NULL,
	"ORIGIN_TYPE" varchar2(7) NULL,
	"SHIPPED_DATE" DATE NULL,
	"RECEIVED_DATE" DATE NULL,
	"CERT_DATE" DATE NULL,
	"GENERATOR_ID" varchar2(15) NULL,
	"GENERATOR_NAME" varchar2(80) NULL,
	"GENERATOR_MAIL_STREET_NUM" varchar2(12) NULL,
	"GENERATOR_MAIL_STREET_1" varchar2(50) NULL,
	"GENERATOR_MAIL_STREET_2" varchar2(50) NULL,
	"GENERATOR_MAIL_CITY" varchar2(35) NULL,
	"GENERATOR_MAIL_CTRY" char(2) NULL,
	"GENERATOR_MAIL_STA" char(2) NULL,
	"GENERATOR_MAIL_ZIP" varchar2(25) NULL,
	"GENERATOR_LOC_STREET_NUM" varchar2(12) NULL,
	"GENERATOR_LOC_STREET_1" varchar2(50) NULL,
	"GENERATOR_LOC_STREET_2" varchar2(50) NULL,
	"GENERATOR_LOC_CITY" varchar2(35) NULL,
	"GENERATOR_LOC_STA" char(2) NULL,
	"GENERATOR_LOC_ZIP" varchar2(25) NULL,
	"GENERATOR_CONTACT_FIRST_NAME" varchar2(38) NULL,
	"GENERATOR_CONTACT_LAST_NAME" varchar2(38) NULL,
	"GENERATOR_CONTACT_PHONE_NUM" varchar2(15) NULL,
	"GENERATOR_CONTACT_PHONE_EXT" varchar2(6) NULL,
	"GENERATOR_CONTACT_EMAIL" varchar2(80) NULL,
	"GENERATOR_CONTACT_COMPANY_NAME" varchar2(80) NULL,
	"EMERGENCY_PHONE_NUM" varchar2(15) NULL,
	"EMERGENCY_PHONE_EXT" varchar2(6) NULL,
	"GENERATOR_PRINTED_NAME" varchar2(80) NULL,
	"GENERATOR_SIGNATURE_DATE" DATE NULL,
	"GENERATOR_ESIG_FIRST_NAME" varchar2(38) NULL,
	"GENERATOR_ESIG_LAST_NAME" varchar2(38) NULL,
	"GENERATOR_ESIG_SIGNATURE_DATE" DATE NULL,
	"GENERATOR_REGISTERED" char(1) NULL,
	"GENERATOR_MODIFIED" char(1) NULL,
	"DES_FAC_ID" varchar2(15) NULL,
	"DES_FAC_NAME" varchar2(80) NULL,
	"DES_FAC_MAIL_STREET_NUM" varchar2(12) NULL,
	"DES_FAC_MAIL_STREET_1" varchar2(50) NULL,
	"DES_FAC_MAIL_STREET_2" varchar2(50) NULL,
	"DES_FAC_MAIL_CITY" varchar2(35) NULL,
	"DES_FAC_MAIL_CTRY" char(2) NULL,
	"DES_FAC_MAIL_STA" char(2) NULL,
	"DES_FAC_MAIL_ZIP" varchar2(25) NULL,
	"DES_FAC_LOC_STREET_NUM" varchar2(12) NULL,
	"DES_FAC_LOC_STREET_1" varchar2(50) NULL,
	"DES_FAC_LOC_STREET_2" varchar2(50) NULL,
	"DES_FAC_LOC_CITY" varchar2(35) NULL,
	"DES_FAC_LOC_STA" char(2) NULL,
	"DES_FAC_LOC_ZIP" varchar2(25) NULL,
	"DES_FAC_CONTACT_FIRST_NAME" varchar2(38) NULL,
	"DES_FAC_CONTACT_LAST_NAME" varchar2(38) NULL,
	"DES_FAC_CONTACT_PHONE_NUM" varchar2(15) NULL,
	"DES_FAC_CONTACT_PHONE_EXT" varchar2(6) NULL,
	"DES_FAC_CONTACT_EMAIL" varchar2(80) NULL,
	"DES_FAC_CONTACT_COMPANY_NAME" varchar2(80) NULL,
	"DES_FAC_PRINTED_NAME" varchar2(80) NULL,
	"DES_FAC_SIGNATURE_DATE" DATE NULL,
	"DES_FAC_ESIG_FIRST_NAME" varchar2(38) NULL,
	"DES_FAC_ESIG_LAST_NAME" varchar2(38) NULL,
	"DES_FAC_ESIG_SIGNATURE_DATE" DATE NULL,
	"DES_FAC_REGISTERED" char(1) NULL,
	"DES_FAC_MODIFIED" char(1) NULL,
	"REJ_IND" char(1) NULL,
	"RESIDUE" char(1) NULL,
	"IMPORT" char(1) NULL,
	"MANIFEST_HANDLING_INSTR" varchar2(4000) NULL,
	"ORIG_SUBM_TYPE" varchar2(14) NULL,
	"COI_ONLY" char(1) NULL,
	"BROKER_ID" varchar2(15) NULL,
	"LAST_EM_UPDT_DATE" DATE NULL,
	"TRANSPORTER_ON_SITE" char(1) NULL,
	"REJECTION_TYPE" varchar2(13) NULL,
	"ALTERNATE_DESIGNATED_FAC_TYPE" varchar2(9) NULL,
	"ALT_FAC_PRINTED_NAME" varchar2(80) NULL,
	"ALT_FAC_SIGNATURE_DATE" DATE NULL,
	"ALT_FAC_ESIG_FIRST_NAME" varchar2(38) NULL,
	"ALT_FAC_ESIG_LAST_NAME" varchar2(38) NULL,
	"ALT_FAC_ESIG_SIGNATURE_DATE" DATE NULL,
	"ALT_FAC_ID" varchar2(12) NULL,
	"ALT_FAC_NAME" varchar2(80) NULL,
	"ALT_FAC_MAIL_STREET_NUM" varchar2(12) NULL,
	"ALT_FAC_MAIL_STREET_1" varchar2(50) NULL,
	"ALT_FAC_MAIL_STREET_2" varchar2(50) NULL,
	"ALT_FAC_MAIL_CITY" varchar2(25) NULL,
	"ALT_FAC_MAIL_STA" char(2) NULL,
	"ALT_FAC_MAIL_ZIP" varchar2(14) NULL,
	"ALT_FAC_LOC_STREET_NUM" varchar2(12) NULL,
	"ALT_FAC_LOC_STREET_1" varchar2(50) NULL,
	"ALT_FAC_LOC_STREET_2" varchar2(50) NULL,
	"ALT_FAC_LOC_CITY" varchar2(25) NULL,
	"ALT_FAC_LOC_STA" char(2) NULL,
	"ALT_FAC_LOC_ZIP" varchar2(14) NULL,
	"ALT_FAC_CONTACT_FIRST_NAME" varchar2(38) NULL,
	"ALT_FAC_CONTACT_LAST_NAME" varchar2(38) NULL,
	"ALT_FAC_CONTACT_PHONE_NO" varchar2(15) NULL,
	"ALT_FAC_CONTACT_PHONE_EXT" varchar2(6) NULL,
	"ALT_FAC_CONTACT_EMAIL" varchar2(80) NULL,
	"ALT_FAC_CONTACT_COMPANY_NAME" varchar2(80) NULL,
	"ALT_FAC_REGISTERED" char(1) NULL,
	"ALT_FAC_MODIFIED" char(1) NULL,
	"FOREIGN_GENERATOR_NAME" varchar2(80) NULL,
	"FOREIGN_GENERATOR_STREET" varchar2(50) NULL,
	"FOREIGN_GENERATOR_CITY" varchar2(25) NULL,
	"FOREIGN_GENERATOR_CTRY_CODE" char(2) NULL,
	"FOREIGN_GENERATOR_CTRY_NAME" varchar2(100) NULL,
	"FOREIGN_GENERATOR_POST_CODE" varchar2(50) NULL,
	"FOREIGN_GENERATOR_PROVINCE" varchar2(50) NULL,
	"PORT_OF_ENTRY_CITY" varchar2(100) NULL,
	"PORT_OF_ENTRY_STA" char(2) NULL,
 CONSTRAINT "PK_EM_EMANIFEST" PRIMARY KEY 
(
	"EM_EMANIFEST_ID"
)
);





CREATE TABLE "RCRA_EM_EMANIFEST_COMMENT"(
	"EM_EMANIFEST_COMMENT_ID" varchar2(40) NOT NULL,
	"EM_EMANIFEST_ID" varchar2(40) NOT NULL,
	"CMNT_LABEL" varchar2(255) NULL,
	"CMNT_DESC" varchar2(255) NULL,
 CONSTRAINT "PK_EM_EMANIFEST_COMMENT" PRIMARY KEY 
(
	"EM_EMANIFEST_COMMENT_ID"
)
);





CREATE TABLE "RCRA_EM_FED_WASTE_CODE_DESC"(
	"EM_FED_WASTE_CODE_DESC_ID" varchar2(40) NOT NULL,
	"EM_WASTE_ID" varchar2(40) NOT NULL,
	"FED_MANIFEST_WASTE_CODE" varchar2(6) NOT NULL,
	"MANIFEST_WASTE_DESC" varchar2(2000) NULL,
	"COI_IND" char(1) NULL,
 CONSTRAINT "PK_EM_FED_WASTE_CODE_DESC" PRIMARY KEY 
(
	"EM_FED_WASTE_CODE_DESC_ID"
)
);





CREATE TABLE "RCRA_EM_STATE_WASTE_CODE_DESC"(
	"EM_STATE_WASTE_CODE_DESC_ID" varchar2(40) NOT NULL,
	"EM_WASTE_ID" varchar2(40) NOT NULL,
	"STA_MANIFEST_WASTE_CODE" varchar2(8) NOT NULL,
	"MANIFEST_WASTE_DESC" varchar2(2000) NULL,
 CONSTRAINT "PK_EM_STATE_WASTE_CODE_DESC" PRIMARY KEY 
(
	"EM_STATE_WASTE_CODE_DESC_ID"
)
);





CREATE TABLE "RCRA_EM_SUBM"(
	"EM_SUBM_ID" varchar2(40) NOT NULL,
 CONSTRAINT "PK_EM_SUBM" PRIMARY KEY 
(
	"EM_SUBM_ID"
)
);





CREATE TABLE "RCRA_EM_TRANSPORTER"(
	"EM_TRANSPORTER_ID" varchar2(40) NOT NULL,
	"EM_EMANIFEST_ID" varchar2(40) NOT NULL,
	"TRANSPORTER_ID" varchar2(15) NULL,
	"TRANSPORTER_NAME" varchar2(80) NULL,
	"TRANSPORTER_PRINTED_NAME" varchar2(80) NULL,
	"TRANSPORTER_SIGNATURE_DATE" DATE NULL,
	"TRANSPORTER_ESIG_FIRST_NAME" varchar2(38) NULL,
	"TRANSPORTER_ESIG_LAST_NAME" varchar2(38) NULL,
	"TRANS_ESIG_SIGNATURE_DATE" DATE NULL,
	"TRANSPORTER_LINE_NUM" varchar2(19) NULL,
	"TRANSPORTER_REGISTERED" char(1) NULL,
 CONSTRAINT "PK_EM_TRANSPORTER" PRIMARY KEY 
(
	"EM_TRANSPORTER_ID"
)
) ;







CREATE TABLE "RCRA_EM_WASTE"(
	"EM_WASTE_ID" varchar2(40) NOT NULL,
	"EM_EMANIFEST_ID" varchar2(40) NOT NULL,
	"DOT_HAZRD" char(1) NULL,
	"DOT_ID_NUM_DESC" varchar2(6) NULL,
	"DOT_PRINTED_INFO" varchar2(500) NULL,
	"NON_HAZ_WASTE_DESC" varchar2(500) NULL,
	"CONTAINER_NUM" number NULL,
	"QNTY_VAL" number(14, 6) NULL,
	"CONTAINER_TYPE_CODE" char(2) NULL,
	"CONTAINER_TYPE_DESC" varchar2(50) NULL,
	"QTY_UNIT_OF_MEAS_CODE" char(1) NULL,
	"QTY_UNIT_OF_MEAS_DESC" varchar2(28) NULL,
	"BR_DENSITY" number(14, 6) NULL,
	"BR_DENSITY_UOM_CODE" char(1) NULL,
	"BR_DENSITY_UOM_DESC" varchar2(240) NULL,
	"BR_FORM_CODE" varchar2(4) NULL,
	"BR_FORM_CODE_DESC" varchar2(240) NULL,
	"BR_SRC_CODE" varchar2(3) NULL,
	"BR_SRC_CODE_DESC" varchar2(240) NULL,
	"BR_WASTE_MIN_CODE" char(1) NULL,
	"BR_WASTE_MIN_DESC" varchar2(240) NULL,
	"BR_MIXED_RADIOACTIVE_WASTE" char(1) NULL,
	"PCB" char(1) NULL,
	"QNTY_DISCREPANCY" char(1) NULL,
	"WASTE_TYPE_DISCREPANCY" char(1) NULL,
	"DISCREPANCY_COMM" varchar2(257) NULL,
	"WASTE_RESIDUE" char(1) NULL,
	"WASTE_RESIDUE_COMM" varchar2(255) NULL,
	"MANAGEMENT_METH_CODE" varchar2(4) NULL,
	"MANAGEMENT_METH_DESC" varchar2(240) NULL,
	"CNST_NUM" varchar2(12) NULL,
	"HANDLING_INSTRUCTIONS" varchar2(4000) NULL,
	"LINE_NUM" number NULL,
	"EPA_WASTE" char(1) NULL,
	"COI_ONLY" char(1) NULL,
	"QNTY_ACUTE_KG" number(14, 6) NULL,
	"QNTY_ACUTE_TONS" number(14, 6) NULL,
	"QNTY_KG" number(14, 6) NULL,
	"QNTY_NON_ACUTE_KG" number(14, 6) NULL,
	"QNTY_NON_ACUTE_TONS" number(14, 6) NULL,
	"QNTY_TONS" number(14, 6) NULL,
 CONSTRAINT "PK_EM_WASTE" PRIMARY KEY 
(
	"EM_WASTE_ID" 
)
);





CREATE TABLE "RCRA_EM_WASTE_CD_TRANS"(
	"EM_WASTE_CD_TRANS_ID" varchar2(40) NOT NULL,
	"EM_WASTE_ID" varchar2(40) NOT NULL,
	"WASTE_CODE" varchar2(12) NOT NULL,
 CONSTRAINT "PK_EM_WASTE_CD_TRANS" PRIMARY KEY 
(
	"EM_WASTE_CD_TRANS_ID"
)
);





CREATE TABLE "RCRA_EM_WASTE_COMMENT"(
	"EM_WASTE_COMMENT_ID" varchar2(40) NOT NULL,
	"EM_WASTE_ID" varchar2(40) NOT NULL,
	"CMNT_LABEL" varchar2(255) NULL,
	"CMNT_DESC" varchar2(255) NULL,
 CONSTRAINT "PK_EM_WASTE_COMMENT" PRIMARY KEY 
(
	"EM_WASTE_COMMENT_ID"
)
);





CREATE TABLE "RCRA_EM_WASTE_PCB"(
	"EM_WASTE_PCB_ID" varchar2(40) NOT NULL,
	"EM_WASTE_ID" varchar2(40) NOT NULL,
	"PCB_LOAD_TYPE_CODE" varchar2(25) NULL,
	"LOAD_TYPE_DESC" varchar2(25) NULL,
	"PCB_ARTICLE_CONT_ID" varchar2(255) NULL,
	"PCB_REMOVAL_DATE" DATE NULL,
	"PCB_WEIGHT" number(14, 6) NULL,
	"PCB_WASTE_TYPE" varchar2(150) NULL,
	"PCB_BULK_IDENTITY" varchar2(255) NULL,
 CONSTRAINT "PK_EM_WASTE_PCB" PRIMARY KEY 
(
	"EM_WASTE_PCB_ID"
)
);





CREATE TABLE "RCRA_FA_COST_EST"(
	"FA_COST_EST_ID" varchar2(40) NOT NULL,
	"FA_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"ACT_LOC_CODE" char(2) NOT NULL,
	"COST_ESTIMATE_TYPE_CODE" char(1) NOT NULL,
	"COST_ESTIMATE_AGN_CODE" char(1) NOT NULL,
	"COST_ESTIMATE_SEQ_NUM" number NOT NULL,
	"RESP_PERSON_DATA_OWNER_CODE" char(2) NULL,
	"RESP_PERSON_ID" varchar2(5) NULL,
	"COST_ESTIMATE_AMOUNT" number(13, 2) NULL,
	"COST_ESTIMATE_DATE" DATE NULL,
	"COST_ESTIMATE_RSN_CODE" char(1) NULL,
	"AREA_UNIT_NOTES_TXT" varchar2(240) NULL,
	"SUPP_INFO_TXT" varchar2(2000) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"F_CREATED_DATE" DATE NULL,
	"DATA_ORIG" char(2) NULL,
	"UPDATE_DUE_DATE" DATE NULL,
	"CURRENT_COST_ESTIMATE_IND" char(1) NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_FA_COST_EST" PRIMARY KEY 
(
	"FA_COST_EST_ID"
)
);





CREATE TABLE "RCRA_FA_COST_EST_REL_MECHANISM"(
	"FA_COST_EST_REL_MECHANISM_ID" varchar2(40) NOT NULL,
	"FA_COST_EST_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"ACT_LOC_CODE" char(2) NOT NULL,
	"MECHANISM_AGN_CODE" char(1) NOT NULL,
	"MECHANISM_SEQ_NUM" number NOT NULL,
	"MECHANISM_DETAIL_SEQ_NUM" number NOT NULL,
 CONSTRAINT "PK_FA_COST_EST_REL_MECHANISM" PRIMARY KEY 
(
	"FA_COST_EST_REL_MECHANISM_ID"
)
);





CREATE TABLE "RCRA_FA_FAC_SUBM"(
	"FA_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"FA_SUBM_ID" varchar2(40) NOT NULL,
	"HANDLER_ID" varchar2(12) NOT NULL,
 CONSTRAINT "PK_FA_FAC_SUBM" PRIMARY KEY 
(
	"FA_FAC_SUBM_ID"
)
);





CREATE TABLE "RCRA_FA_MECHANISM"(
	"FA_MECHANISM_ID" varchar2(40) NOT NULL,
	"FA_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"ACT_LOC_CODE" char(2) NOT NULL,
	"MECHANISM_AGN_CODE" char(1) NOT NULL,
	"MECHANISM_SEQ_NUM" number NOT NULL,
	"MECHANISM_TYPE_DATA_OWNER_CODE" char(2) NULL,
	"MECHANISM_TYPE_CODE" char(1) NULL,
	"PROVIDER_TXT" varchar2(80) NULL,
	"PROVIDER_FULL_CONTACT_NAME" varchar2(33) NULL,
	"TELE_NUM_TXT" varchar2(15) NULL,
	"SUPP_INFO_TXT" varchar2(2000) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"F_CREATED_DATE" DATE NULL,
	"DATA_ORIG" char(2) NULL,
	"PROVIDER_CONTACT_EMAIL" varchar2(80) NULL,
	"ACTIVE_MECHANISM_IND" char(1) NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_FA_MECHANISM" PRIMARY KEY 
(
	"FA_MECHANISM_ID"
)
);





CREATE TABLE "RCRA_FA_MECHANISM_DETAIL"(
	"FA_MECHANISM_DETAIL_ID" varchar2(40) NOT NULL,
	"FA_MECHANISM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"MECHANISM_DETAIL_SEQ_NUM" number NOT NULL,
	"MECHANISM_IDEN_TXT" varchar2(40) NULL,
	"FACE_VAL_AMOUNT" number(13, 2) NULL,
	"EFFC_DATE" DATE NULL,
	"EXPIRATION_DATE" DATE NULL,
	"SUPP_INFO_TXT" varchar2(2000) NULL,
	"CURRENT_MECHANISM_DETAIL_IND" char(1) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"F_CREATED_DATE" DATE NULL,
	"DATA_ORIG" char(2) NULL,
	"FAC_FACE_VAL_AMOUNT" number(14, 6) NULL,
	"ALT_IND" char(1) NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_FA_MECHANISM_DETAIL" PRIMARY KEY 
(
	"FA_MECHANISM_DETAIL_ID"
)
);





CREATE TABLE "RCRA_FA_SUBM"(
	"FA_SUBM_ID" varchar2(40) NOT NULL,
 CONSTRAINT "PK_FA_SUBM" PRIMARY KEY 
(
	"FA_SUBM_ID"
)
);





CREATE TABLE "RCRA_GIS_FAC_SUBM"(
	"GIS_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"GIS_SUBM_ID" varchar2(40) NOT NULL,
	"HANDLER_ID" varchar2(12) NOT NULL,
 CONSTRAINT "PK_GIS_FAC_SUBM" PRIMARY KEY 
(
	"GIS_FAC_SUBM_ID"
)
);





CREATE TABLE "RCRA_GIS_GEO_INFORMATION"(
	"GIS_GEO_INFORMATION_ID" varchar2(40) NOT NULL,
	"GIS_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"GEO_INFO_OWNER" char(2) NOT NULL,
	"GEO_INFO_SEQ_NUM" number NOT NULL,
	"PERMIT_UNIT_SEQ_NUM" number NULL,
	"AREA_SEQ_NUM" number NULL,
	"LOC_COMM_TXT" varchar2(2000) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"G_CREATED_DATE" DATE NULL,
	"DATA_ORIG" char(2) NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
	"AREA_ACREAGE_MEAS" number(13, 2) NULL,
	"AREA_MEAS_SRC_DATA_OWNER_CODE" char(2) NULL,
	"AREA_MEAS_SRC_CODE" varchar2(4) NULL,
	"AREA_MEAS_DATE" DATE NULL,
	"DATA_COLL_DATE" DATE NOT NULL,
	"HORZ_ACC_MEAS" number NULL,
	"SRC_MAP_SCALE_NUM" number NULL,
	"COORD_DATA_SRC_DATA_OWNER_CODE" char(2) NULL,
	"COORD_DATA_SRC_CODE" varchar2(3) NULL,
	"GEO_REF_PT_DATA_OWNER_CODE" char(2) NULL,
	"GEO_REF_PT_CODE" varchar2(3) NULL,
	"GEOM_TYPE_DATA_OWNER_CODE" char(2) NULL,
	"GEOM_TYPE_CODE" varchar2(3) NULL,
	"HORZ_COLL_METH_DATA_OWNER_CODE" char(2) NULL,
	"HORZ_COLL_METH_CODE" varchar2(3) NULL,
	"HRZ_CRD_RF_SYS_DTM_DTA_OWN_CDE" char(2) NULL,
	"HORZ_COORD_REF_SYS_DATUM_CODE" varchar2(3) NULL,
	"VERF_METH_DATA_OWNER_CODE" char(2) NULL,
	"VERF_METH_CODE" varchar2(3) NULL,
	"LATITUDE" number(19, 14) NULL,
	"LONGITUDE" number(19, 14) NULL,
	"ELEVATION" number(19, 14) NULL,
 CONSTRAINT "PK_GIS_GEO_INFORMATION" PRIMARY KEY 
(
	"GIS_GEO_INFORMATION_ID"
)
);





CREATE TABLE "RCRA_GIS_SUBM"(
	"GIS_SUBM_ID" varchar2(40) NOT NULL,
 CONSTRAINT "PK_GIS_SUBM" PRIMARY KEY 
(
	"GIS_SUBM_ID"
)
);





CREATE TABLE "RCRA_HD_ADD_CONTACT"(
	"HD_ADD_CONTACT_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"ADD_CONTACT_SEQ" number NOT NULL,
	"CONTACT_TYPE" char(2) NULL,
	"CONTACT_TYPE_OWNER" char(2) NULL,
	"CONTACT_FIRST_NAME" varchar2(38) NULL,
	"CONTACT_MIDDLE_INITIAL" char(1) NULL,
	"CONTACT_LAST_NAME" varchar2(38) NULL,
	"CONTACT_STREET_NUMBER" varchar2(12) NULL,
	"CONTACT_STREET_1" varchar2(50) NULL,
	"CONTACT_STREET_2" varchar2(50) NULL,
	"CONTACT_CITY" varchar2(25) NULL,
	"CONTACT_STATE" char(2) NULL,
	"CONTACT_ZIP" varchar2(14) NULL,
	"CONTACT_COUNTRY" char(2) NULL,
	"CONTACT_PHONE" varchar2(15) NULL,
	"CONTACT_PHONE_EXT" varchar2(6) NULL,
	"CONTACT_FAX" varchar2(15) NULL,
	"CONTACT_EMAIL" varchar2(80) NULL,
	"CONTACT_TITLE" varchar2(45) NULL,
	"CONTACT_LANG_CODE" char(2) NULL,
	"CONTACT_LANG_DESC" varchar2(50) NULL,
 CONSTRAINT "PK_HD_ADD_CONTACT" PRIMARY KEY 
(
	"HD_ADD_CONTACT_ID"
)
);





CREATE TABLE "RCRA_HD_CERTIFICATION"(
	"HD_CERTIFICATION_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"CERT_SEQ" number NOT NULL,
	"CERT_SIGNED_DATE" varchar2(10) NULL,
	"CERT_TITLE" varchar2(45) NULL,
	"CERT_FIRST_NAME" varchar2(38) NULL,
	"CERT_MIDDLE_INITIAL" char(1) NULL,
	"CERT_LAST_NAME" varchar2(38) NULL,
	"CERT_EMAIL_TEXT" varchar2(80) NULL,
 CONSTRAINT "PK_HD_CERTIFICATION" PRIMARY KEY 
(
	"HD_CERTIFICATION_ID"
)
);





CREATE TABLE "RCRA_HD_ENV_PERMIT"(
	"HD_ENV_PERMIT_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"ENV_PERMIT_NUMBER" varchar2(13) NOT NULL,
	"ENV_PERMIT_OWNER" char(2) NULL,
	"ENV_PERMIT_TYPE" char(1) NULL,
	"ENV_PERMIT_DESC" varchar2(80) NOT NULL,
 CONSTRAINT "PK_HD_ENV_PERMIT" PRIMARY KEY 
(
	"HD_ENV_PERMIT_ID"
)
);





CREATE TABLE "RCRA_HD_EPISODIC_EVENT"(
	"HD_EPISODIC_EVENT_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"EVENT_OWNER" char(2) NULL,
	"EVENT_TYPE" char(1) NULL,
	"START_DATE" DATE NULL,
	"END_DATE" DATE NULL,
	"CONTACT_FIRST_NAME" varchar2(38) NULL,
	"CONTACT_MIDDLE_INITIAL" char(1) NULL,
	"CONTACT_LAST_NAME" varchar2(38) NULL,
	"CONTACT_ORG_NAME" varchar2(80) NULL,
	"CONTACT_TITLE" varchar2(80) NULL,
	"CONTACT_EMAIL_ADDRESS" varchar2(80) NULL,
	"CONTACT_PHONE" varchar2(15) NULL,
	"CONTACT_PHONE_EXT" varchar2(6) NULL,
	"CONTACT_FAX" varchar2(15) NULL,
	"CONTACT_LANG_CODE" char(2) NULL,
	"CONTACT_LANG_DESC" varchar2(50) NULL,
 CONSTRAINT "PK_HD_EPISODIC_EVENT" PRIMARY KEY 
(
	"HD_EPISODIC_EVENT_ID"
)
);





CREATE TABLE "RCRA_HD_EPISODIC_PRJT"(
	"HD_EPISODIC_PRJT_ID" varchar2(40) NOT NULL,
	"HD_EPISODIC_EVENT_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"PRJT_CODE_OWNER" char(2) NOT NULL,
	"PRJT_CODE" char(3) NOT NULL,
	"OTHER_PRJT_DESC" varchar2(255) NULL,
 CONSTRAINT "PK_HD_EPISODIC_PRJT" PRIMARY KEY 
(
	"HD_EPISODIC_PRJT_ID"
)
);





CREATE TABLE "RCRA_HD_EPISODIC_WASTE"(
	"HD_EPISODIC_WASTE_ID" varchar2(40) NOT NULL,
	"HD_EPISODIC_EVENT_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"SEQ_NUMBER" number NOT NULL,
	"WASTE_DESC" varchar2(4000) NULL,
	"EST_QNTY" number NULL,
 CONSTRAINT "PK_HD_EPISODIC_WASTE" PRIMARY KEY 
(
	"HD_EPISODIC_WASTE_ID"
)
);





CREATE TABLE "RCRA_HD_EPISODIC_WASTE_CODE"(
	"HD_EPISODIC_WASTE_CODE_ID" varchar2(40) NOT NULL,
	"HD_EPISODIC_WASTE_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"WASTE_CODE_OWNER" char(2) NULL,
	"WASTE_CODE" varchar2(6) NULL,
	"WASTE_CODE_TEXT" varchar2(80) NULL,
 CONSTRAINT "PK_HD_EPISODIC_WASTE_CODE" PRIMARY KEY 
(
	"HD_EPISODIC_WASTE_CODE_ID"
)
);





CREATE TABLE "RCRA_HD_HANDLER"(
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"HD_HBASIC_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"ACTIVITY_LOCATION" char(2) NOT NULL,
	"SOURCE_TYPE" char(1) NOT NULL,
	"SEQ_NUMBER" number NOT NULL,
	"RECEIVE_DATE" varchar2(10) NULL,
	"HANDLER_NAME" varchar2(80) NULL,
	"ACKNOWLEDGE_DATE" varchar2(10) NULL,
	"NON_NOTIFIER" char(1) NULL,
	"NON_NOTIFIER_TEXT" varchar2(255) NULL,
	"TSD_DATE" varchar2(10) NULL,
	"NATURE_OF_BUSINESS_TEXT" varchar2(4000) NULL,
	"OFF_SITE_RECEIPT" char(1) NULL,
	"ACCESSIBILITY" char(1) NULL,
	"ACCESSIBILITY_TEXT" varchar2(255) NULL,
	"COUNTY_CODE_OWNER" char(2) NULL,
	"COUNTY_CODE" varchar2(5) NULL,
	"NOTES" varchar2(4000) NULL,
	"INTRNL_NOTES" varchar2(4000) NULL,
	"SHORT_TERM_INTRNL_NOTES" varchar2(4000) NULL,
	"ACKNOWLEDGE_FLAG_IND" char(1) NULL,
	"INCLUDE_IN_NATIONAL_REPORT_IND" char(1) NULL,
	"LQHUW_IND" char(1) NULL,
	"HD_REPORT_CYCLE_YEAR" number NULL,
	"HEALTHCARE_FAC" char(1) NULL,
	"REVERSE_DISTRIBUTOR" char(1) NULL,
	"SUBPART_P_WITHDRAWAL" char(1) NULL,
	"CURRENT_RECORD" char(1) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"H_CREATED_DATE" DATE NULL,
	"DATA_ORIG" char(2) NULL,
	"LOCATION_LATITUDE" number(19, 14) NULL,
	"LOCATION_LONGITUDE" number(19, 14) NULL,
	"LOCATION_GIS_PRIM" char(1) NULL,
	"LOCATION_GIS_ORIG" char(2) NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
	"BR_EXEMPT_IND" char(1) NULL,
	"ACKNOWLEDGE_FLAG" char(1) NULL,
	"LOCATION_STREET_NUMBER" varchar2(12) NULL,
	"LOCATION_STREET1" varchar2(50) NULL,
	"LOCATION_STREET2" varchar2(50) NULL,
	"LOCATION_CITY" varchar2(25) NULL,
	"LOCATION_STATE" char(2) NULL,
	"LOCATION_COUNTRY" char(2) NULL,
	"LOCATION_ZIP" varchar2(14) NULL,
	"MAIL_STREET_NUMBER" varchar2(12) NULL,
	"MAIL_STREET1" varchar2(50) NULL,
	"MAIL_STREET2" varchar2(50) NULL,
	"MAIL_CITY" varchar2(25) NULL,
	"MAIL_STATE" char(2) NULL,
	"MAIL_COUNTRY" char(2) NULL,
	"MAIL_ZIP" varchar2(14) NULL,
	"CONTACT_FIRST_NAME" varchar2(38) NULL,
	"CONTACT_MIDDLE_INITIAL" char(1) NULL,
	"CONTACT_LAST_NAME" varchar2(38) NULL,
	"CONTACT_ORG_NAME" varchar2(80) NULL,
	"CONTACT_TITLE" varchar2(80) NULL,
	"CONTACT_EMAIL_ADDRESS" varchar2(80) NULL,
	"CONTACT_PHONE" varchar2(15) NULL,
	"CONTACT_PHONE_EXT" varchar2(6) NULL,
	"CONTACT_FAX" varchar2(15) NULL,
	"CONTACT_LANG_CODE" char(2) NULL,
	"CONTACT_LANG_DESC" varchar2(50) NULL,
	"CONTACT_STREET_NUMBER" varchar2(12) NULL,
	"CONTACT_STREET1" varchar2(50) NULL,
	"CONTACT_STREET2" varchar2(50) NULL,
	"CONTACT_CITY" varchar2(25) NULL,
	"CONTACT_STATE" char(2) NULL,
	"CONTACT_COUNTRY" char(2) NULL,
	"CONTACT_ZIP" varchar2(14) NULL,
	"PCONTACT_FIRST_NAME" varchar2(38) NULL,
	"PCONTACT_MIDDLE_NAME" char(1) NULL,
	"PCONTACT_LAST_NAME" varchar2(38) NULL,
	"PCONTACT_ORG_NAME" varchar2(80) NULL,
	"PCONTACT_TITLE" varchar2(80) NULL,
	"PCONTACT_EMAIL_ADDRESS" varchar2(80) NULL,
	"PCONTACT_PHONE" varchar2(15) NULL,
	"PCONTACT_PHONE_EXT" varchar2(6) NULL,
	"PCONTACT_FAX" varchar2(15) NULL,
	"PCONTACT_LANG_CODE" char(2) NULL,
	"PCONTACT_LANG_DESC" varchar2(50) NULL,
	"PCONTACT_STREET_NUMBER" varchar2(12) NULL,
	"PCONTACT_STREET1" varchar2(50) NULL,
	"PCONTACT_STREET2" varchar2(50) NULL,
	"PCONTACT_CITY" varchar2(25) NULL,
	"PCONTACT_STATE" char(2) NULL,
	"PCONTACT_COUNTRY" char(2) NULL,
	"PCONTACT_ZIP" varchar2(14) NULL,
	"USED_OIL_BURNER" char(1) NULL,
	"USED_OIL_PROCESSOR" char(1) NULL,
	"USED_OIL_REFINER" char(1) NULL,
	"USED_OIL_MARKET_BURNER" char(1) NULL,
	"USED_OIL_SPEC_MARKETER" char(1) NULL,
	"USED_OIL_TRANSFER_FACILITY" char(1) NULL,
	"USED_OIL_TRANSPORTER" char(1) NULL,
	"LAND_TYPE" char(1) NULL,
	"STATE_DISTRICT_OWNER" char(2) NULL,
	"STATE_DISTRICT" varchar2(10) NULL,
	"STATE_DISTRICT_TEXT" varchar2(255) NULL,
	"IMPORTER_ACTIVITY" char(1) NULL,
	"MIXED_WASTE_GENERATOR" char(1) NULL,
	"RECYCLER_ACTIVITY" char(1) NULL,
	"TRANSPORTER_ACTIVITY" char(1) NULL,
	"TSD_ACTIVITY" char(1) NULL,
	"UNDERGROUND_INJECTION_ACTIVITY" char(1) NULL,
	"UNIVERSAL_WASTE_DEST_FACILITY" char(1) NULL,
	"ONSITE_BURNER_EXEMPTION" char(1) NULL,
	"FURNACE_EXEMPTION" char(1) NULL,
	"SHORT_TERM_GEN_IND" char(1) NULL,
	"TRANSFER_FACILITY_IND" char(1) NULL,
	"RECOGNIZED_TRADER_IMPORTER_IND" char(1) NULL,
	"RECOGNIZED_TRADER_EXPORTER_IND" char(1) NULL,
	"SLAB_IMPORTER_IND" char(1) NULL,
	"SLAB_EXPORTER_IND" char(1) NULL,
	"RECYCLER_ACT_NONSTORAGE" char(1) NULL,
	"MANIFEST_BROKER" char(1) NULL,
	"STATE_WASTE_GENERATOR_OWNER" char(2) NULL,
	"STATE_WASTE_GENERATOR" char(1) NULL,
	"FED_WASTE_GENERATOR_OWNER" char(2) NULL,
	"FED_WASTE_GENERATOR" char(1) NULL,
	"COLLEGE_IND" char(1) NULL,
	"HOSPITAL_IND" char(1) NULL,
	"NON_PROFIT_IND" char(1) NULL,
	"WITHDRAWAL_IND" char(1) NULL,
	"TRANS_CODE" char(1) NULL,
	"NOTIFICATION_RSN_CODE" char(1) NULL,
	"EFFC_DATE" DATE NULL,
	"FINANCIAL_ASSURANCE_IND" char(1) NULL,
	"RECYCLER_IND" char(1) NULL,
	"RECYCLER_NOTES" varchar2(4000) NULL,
	"RECYCLING_IND" char(1) NULL,
 CONSTRAINT "PK_HD_HANDLER" PRIMARY KEY 
(
	"HD_HANDLER_ID"
)
);





CREATE TABLE "RCRA_HD_HBASIC"(
	"HD_HBASIC_ID" varchar2(40) NOT NULL,
	"HD_SUBM_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"HANDLER_ID" varchar2(12) NULL,
	"EXTRACT_FLAG" char(1) NULL,
	"FACILITY_IDENTIFIER" varchar2(12) NULL,
 CONSTRAINT "PK_HD_HBASIC" PRIMARY KEY 
(
	"HD_HBASIC_ID"
)
);





CREATE TABLE "RCRA_HD_LQG_CLOSURE"(
	"HD_LQG_CLOSURE_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"CLOSURE_TYPE" char(1) NULL,
	"EXPECTED_CLOSURE_DATE" DATE NULL,
	"NEW_CLOSURE_DATE" DATE NULL,
	"DATE_CLOSED" DATE NULL,
	"IN_COMPLIANCE_IND" char(1) NULL,
 CONSTRAINT "PK_HD_LQG_CLOSURE" PRIMARY KEY 
(
	"HD_LQG_CLOSURE_ID"
)
);





CREATE TABLE "RCRA_HD_LQG_CONSOLIDATION"(
	"HD_LQG_CONSOLIDATION_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"SEQ_NUMBER" number NOT NULL,
	"HANDLER_ID" varchar2(12) NULL,
	"HANDLER_NAME" varchar2(80) NULL,
	"MAIL_STREET_NUMBER" varchar2(12) NULL,
	"MAIL_STREET1" varchar2(50) NULL,
	"MAIL_STREET2" varchar2(50) NULL,
	"MAIL_CITY" varchar2(25) NULL,
	"MAIL_STATE" char(2) NULL,
	"MAIL_COUNTRY" char(2) NULL,
	"MAIL_ZIP" varchar2(14) NULL,
	"CONTACT_FIRST_NAME" varchar2(38) NULL,
	"CONTACT_MIDDLE_INITIAL" char(1) NULL,
	"CONTACT_LAST_NAME" varchar2(38) NULL,
	"CONTACT_ORG_NAME" varchar2(80) NULL,
	"CONTACT_TITLE" varchar2(80) NULL,
	"CONTACT_EMAIL_ADDRESS" varchar2(80) NULL,
	"CONTACT_PHONE" varchar2(15) NULL,
	"CONTACT_PHONE_EXT" varchar2(6) NULL,
	"CONTACT_FAX" varchar2(15) NULL,
	"CONTACT_LANG_CODE" char(2) NULL,
	"CONTACT_LANG_DESC" varchar2(50) NULL,
 CONSTRAINT "PK_HD_LQG_CONSOLIDATION" PRIMARY KEY 
(
	"HD_LQG_CONSOLIDATION_ID"
)
);





CREATE TABLE "RCRA_HD_NAICS"(
	"HD_NAICS_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"NAICS_SEQ" varchar2(4) NOT NULL,
	"NAICS_OWNER" char(2) NULL,
	"NAICS_CODE" varchar2(6) NULL,
 CONSTRAINT "PK_HD_NAICS" PRIMARY KEY 
(
	"HD_NAICS_ID"
)
);





CREATE TABLE "RCRA_HD_OTHER_ID"(
	"HD_OTHER_ID_ID" varchar2(40) NOT NULL,
	"HD_HBASIC_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"OTHER_ID" varchar2(12) NOT NULL,
	"RELATIONSHIP_OWNER" char(2) NULL,
	"RELATIONSHIP_TYPE" char(1) NULL,
	"SAME_FACILITY" char(1) NULL,
	"NOTES" varchar2(4000) NULL,
 CONSTRAINT "PK_HD_OTHER_ID" PRIMARY KEY 
(
	"HD_OTHER_ID_ID"
)
);





CREATE TABLE "RCRA_HD_OWNEROP"(
	"HD_OWNEROP_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"OWNER_OP_SEQ" number NOT NULL,
	"OWNER_OP_IND" char(2) NULL,
	"OWNER_OP_TYPE" char(1) NULL,
	"DATE_BECAME_CURRENT" varchar2(10) NULL,
	"DATE_ENDED_CURRENT" varchar2(10) NULL,
	"NOTES" varchar2(4000) NULL,
	"FIRST_NAME" varchar2(38) NULL,
	"MIDDLE_INITIAL" char(1) NULL,
	"LAST_NAME" varchar2(38) NULL,
	"ORG_NAME" varchar2(80) NULL,
	"TITLE" varchar2(80) NULL,
	"EMAIL_ADDRESS" varchar2(80) NULL,
	"PHONE" varchar2(15) NULL,
	"PHONE_EXT" varchar2(6) NULL,
	"FAX" varchar2(15) NULL,
	"LANG_CODE" char(2) NULL,
	"LANG_DESC" varchar2(50) NULL,
	"MAIL_ADDR_NUM_TXT" varchar2(12) NULL,
	"STREET1" varchar2(50) NULL,
	"STREET2" varchar2(50) NULL,
	"CITY" varchar2(25) NULL,
	"STATE" char(2) NULL,
	"COUNTRY" char(2) NULL,
	"ZIP" varchar2(14) NULL,
 CONSTRAINT "PK_HD_OWNEROP" PRIMARY KEY 
(
	"HD_OWNEROP_ID"
)
);





CREATE TABLE "RCRA_HD_SEC_MATERIAL_ACTIVITY"(
	"HD_SEC_MATERIAL_ACTIVITY_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"HSM_SEQ_NUM" varchar2(4) NOT NULL,
	"FAC_CODE_OWNER_NAME" char(2) NULL,
	"FAC_TYPE_CODE" char(2) NULL,
	"ESTIMATED_SHORT_TONS_QNTY" number NULL,
	"ACTL_SHORT_TONS_QNTY" number NULL,
	"LAND_BASED_UNIT_IND" char(2) NULL,
	"LAND_BASED_UNIT_IND_TEXT" varchar2(255) NULL,
 CONSTRAINT "PK_HD_SEC_MATERIAL_ACTIVITY" PRIMARY KEY 
(
	"HD_SEC_MATERIAL_ACTIVITY_ID"
)
);





CREATE TABLE "RCRA_HD_SEC_WASTE_CODE"(
	"HD_SEC_WASTE_CODE_ID" varchar2(40) NOT NULL,
	"HD_SEC_MATERIAL_ACTIVITY_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"WASTE_CODE_OWNER" char(2) NULL,
	"WASTE_CODE_TYPE" varchar2(6) NULL,
 CONSTRAINT "PK_HD_SEC_WASTE_CODE" PRIMARY KEY 
(
	"HD_SEC_WASTE_CODE_ID"
)
);





CREATE TABLE "RCRA_HD_STATE_ACTIVITY"(
	"HD_STATE_ACTIVITY_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"STATE_ACTIVITY_OWNER" char(2) NOT NULL,
	"STATE_ACTIVITY_TYPE" varchar2(5) NOT NULL,
 CONSTRAINT "PK_HD_STATE_ACTIVITY" PRIMARY KEY 
(
	"HD_STATE_ACTIVITY_ID"
)
);





CREATE TABLE "RCRA_HD_SUBM"(
	"HD_SUBM_ID" varchar2(40) NOT NULL,
 CONSTRAINT "PK_HD_SUBM" PRIMARY KEY 
(
	"HD_SUBM_ID"
)
);





CREATE TABLE "RCRA_HD_UNIVERSAL_WASTE"(
	"HD_UNIVERSAL_WASTE_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"UNIVERSAL_WASTE_OWNER" char(2) NULL,
	"UNIVERSAL_WASTE_TYPE" char(1) NULL,
	"ACCUMULATED" char(1) NULL,
	"GENERATED" char(1) NULL,
 CONSTRAINT "PK_HD_UNIVERSAL_WASTE" PRIMARY KEY 
(
	"HD_UNIVERSAL_WASTE_ID"
)
);





CREATE TABLE "RCRA_HD_WASTE_CODE"(
	"HD_WASTE_CODE_ID" varchar2(40) NOT NULL,
	"HD_HANDLER_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"WASTE_CODE_OWNER" char(2) NULL,
	"WASTE_CODE_TYPE" varchar2(6) NULL,
 CONSTRAINT "PK_HD_WASTE_CODE" PRIMARY KEY 
(
	"HD_WASTE_CODE_ID"
)
);





CREATE TABLE "RCRA_PRM_EVENT"(
	"PRM_EVENT_ID" varchar2(40) NOT NULL,
	"PRM_SERIES_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"ACT_LOC_CODE" char(2) NOT NULL,
	"PERMIT_EVENT_DATA_OWNER_CODE" char(2) NOT NULL,
	"PERMIT_EVENT_CODE" varchar2(7) NOT NULL,
	"EVENT_AGN_CODE" char(1) NOT NULL,
	"EVENT_SEQ_NUM" number NOT NULL,
	"ACTL_DATE" DATE NULL,
	"ORIGINAL_SCHEDULE_DATE" DATE NULL,
	"NEW_SCHEDULE_DATE" DATE NULL,
	"RESP_PERSON_DATA_OWNER_CODE" char(2) NULL,
	"RESP_PERSON_ID" varchar2(5) NULL,
	"EVENT_SUBORG_DATA_OWNER_CODE" char(2) NULL,
	"EVENT_SUBORG_CODE" varchar2(10) NULL,
	"SUPP_INFO_TXT" varchar2(2000) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"P_CREATED_DATE" DATE NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_PRM_EVENT" PRIMARY KEY 
(
	"PRM_EVENT_ID"
)
);





CREATE TABLE "RCRA_PRM_EVENT_COMMITMENT"(
	"PRM_EVENT_COMMITMENT_ID" varchar2(40) NOT NULL,
	"PRM_EVENT_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"COMMIT_LEAD" char(2) NOT NULL,
	"COMMIT_SEQ_NUM" number NOT NULL,
 CONSTRAINT "PK_PRM_EVENT_COMMITMENT" PRIMARY KEY 
(
	"PRM_EVENT_COMMITMENT_ID"
)
);





CREATE TABLE "RCRA_PRM_FAC_SUBM"(
	"PRM_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"PRM_SUBM_ID" varchar2(40) NOT NULL,
	"HANDLER_ID" varchar2(12) NOT NULL,
 CONSTRAINT "PK_PRM_FAC_SUBM" PRIMARY KEY 
(
	"PRM_FAC_SUBM_ID"
)
);





CREATE TABLE "RCRA_PRM_MOD_EVENT"(
	"PRM_MOD_EVENT_ID" varchar2(40) NOT NULL,
	"PRM_EVENT_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"MOD_HANDLER_ID" varchar2(12) NOT NULL,
	"MOD_ACT_LOC_CODE" varchar2(50) NOT NULL,
	"MOD_SERIES_SEQ_NUM" number NOT NULL,
	"MOD_EVENT_SEQ_NUM" number NOT NULL,
	"MOD_EVENT_AGN_CODE" char(1) NOT NULL,
	"MOD_EVENT_DATA_OWNER_CODE" char(2) NOT NULL,
	"MOD_EVENT_CODE" varchar2(7) NOT NULL,
 CONSTRAINT "PK_PRM_MOD_EVENT" PRIMARY KEY 
(
	"PRM_MOD_EVENT_ID"
)
);





CREATE TABLE "RCRA_PRM_RELATED_EVENT"(
	"PRM_RELATED_EVENT_ID" varchar2(40) NOT NULL,
	"PRM_UNIT_DETAIL_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"ACT_LOC_CODE" char(2) NOT NULL,
	"PERMIT_SERIES_SEQ_NUM" number NOT NULL,
	"PERMIT_EVENT_DATA_OWNER_CODE" char(2) NOT NULL,
	"PERMIT_EVENT_CODE" varchar2(7) NOT NULL,
	"EVENT_AGN_CODE" char(1) NOT NULL,
	"EVENT_SEQ_NUM" number NOT NULL,
 CONSTRAINT "PK_PRM_RELATED_EVENT" PRIMARY KEY 
(
	"PRM_RELATED_EVENT_ID"
)
);





CREATE TABLE "RCRA_PRM_SERIES"(
	"PRM_SERIES_ID" varchar2(40) NOT NULL,
	"PRM_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"PERMIT_SERIES_SEQ_NUM" number NOT NULL,
	"PERMIT_SERIES_NAME" varchar2(40) NULL,
	"RESP_PERSON_DATA_OWNER_CODE" char(2) NULL,
	"RESP_PERSON_ID" varchar2(5) NULL,
	"SUPP_INFO_TXT" varchar2(2000) NULL,
	"ACTIVE_SERIES_IND" char(1) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"P_CREATED_DATE" DATE NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_PRM_SERIES" PRIMARY KEY 
(
	"PRM_SERIES_ID"
)
);





CREATE TABLE "RCRA_PRM_SUBM"(
	"PRM_SUBM_ID" varchar2(40) NOT NULL,
 CONSTRAINT "PK_PRM_SUBM" PRIMARY KEY 
(
	"PRM_SUBM_ID"
)
);





CREATE TABLE "RCRA_PRM_UNIT"(
	"PRM_UNIT_ID" varchar2(40) NOT NULL,
	"PRM_FAC_SUBM_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"PERMIT_UNIT_SEQ_NUM" number NULL,
	"PERMIT_UNIT_NAME" varchar2(40) NULL,
	"SUPP_INFO_TXT" varchar2(2000) NULL,
	"ACTIVE_UNIT_IND" char(1) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"P_CREATED_DATE" DATE NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_PRM_UNIT" PRIMARY KEY 
(
	"PRM_UNIT_ID"
)
);





CREATE TABLE "RCRA_PRM_UNIT_DETAIL"(
	"PRM_UNIT_DETAIL_ID" varchar2(40) NOT NULL,
	"PRM_UNIT_ID" varchar2(40) NOT NULL,
	"TRANS_CODE" char(1) NULL,
	"PERMIT_UNIT_DETAIL_SEQ_NUM" number NOT NULL,
	"PROC_UNIT_DATA_OWNER_CODE" char(2) NULL,
	"PROC_UNIT_CODE" varchar2(3) NULL,
	"PERMIT_STAT_EFFC_DATE" DATE NULL,
	"PERMIT_UNIT_CAP_QNTY" number(14, 3) NULL,
	"CAP_TYPE_CODE" char(1) NULL,
	"COMMER_STAT_CODE" char(1) NULL,
	"LEGAL_OPER_STAT_DATA_OWNER_CDE" char(2) NULL,
	"LEGAL_OPER_STAT_CODE" varchar2(4) NULL,
	"MEASUREMENT_UNIT_DATA_OWNR_CDE" char(2) NULL,
	"MEASUREMENT_UNIT_CODE" char(1) NULL,
	"NUM_OF_UNITS_COUNT" number NULL,
	"STANDARD_PERMIT_IND" char(1) NULL,
	"SUPP_INFO_TXT" varchar2(2000) NULL,
	"CURRENT_UNIT_DETAIL_IND" char(1) NULL,
	"CREATED_BY_USERID" varchar2(255) NULL,
	"P_CREATED_DATE" DATE NULL,
	"LAST_UPDT_BY" varchar2(255) NULL,
	"LAST_UPDT_DATE" DATE NULL,
 CONSTRAINT "PK_PRM_UNIT_DETAIL" PRIMARY KEY 
(
	"PRM_UNIT_DETAIL_ID"
)
);





CREATE TABLE "RCRA_PRM_WASTE_CODE"(
	"PRM_WASTE_CODE_ID" varchar2(40) NOT NULL,
	"PRM_UNIT_DETAIL_ID" varchar2(40) NOT NULL,
	"TRANSACTION_CODE" char(1) NULL,
	"WASTE_CODE_OWNER" char(2) NULL,
	"WASTE_CODE_TYPE" varchar2(6) NULL,
 CONSTRAINT "PK_PRM_WASTE_CODE" PRIMARY KEY 
(
	"PRM_WASTE_CODE_ID"
)
);





CREATE TABLE "RCRA_RU_REPORT_UNIV"(
	"RU_REPORT_UNIV_ID" varchar2(40) NOT NULL,
	"RU_REPORT_UNIV_SUBM_ID" varchar2(40) NOT NULL,
	"HANDLER_ID" varchar2(12) NOT NULL,
	"ACTIVITY_LOCATION" char(2) NOT NULL,
	"SOURCE_TYPE" char(1) NULL,
	"SEQ_NUMBER" number NULL,
	"RECEIVE_DATE" DATE NULL,
	"HANDLER_NAME" varchar2(80) NULL,
	"NON_NOTIFIER_IND" char(1) NULL,
	"ACCESSIBILITY" char(1) NULL,
	"REPORT_CYCLE" number NULL,
	"REGION" char(2) NULL,
	"STATE" char(2) NULL,
	"EXTRACT_FLAG" char(1) NULL,
	"ACTIVE_SITE" varchar2(5) NULL,
	"COUNTY_CODE" varchar2(5) NULL,
	"COUNTY_NAME" varchar2(80) NULL,
	"CONTACT_NAME" varchar2(80) NULL,
	"CONTACT_PHONE" varchar2(22) NULL,
	"CONTACT_FAX" varchar2(15) NULL,
	"CONTACT_EMAIL" varchar2(80) NULL,
	"CONTACT_TITLE" varchar2(45) NULL,
	"CONTACT_LANG_CODE" char(2) NULL,
	"CONTACT_LANG_DESC" varchar2(50) NULL,
	"OWNER_NAME" varchar2(80) NULL,
	"OWNER_TYPE" char(1) NULL,
	"OWNER_SEQ_NUM" number NULL,
	"OPER_NAME" varchar2(80) NULL,
	"OPER_TYPE" char(1) NULL,
	"OPER_SEQ_NUM" number NULL,
	"NAIC1_CODE" varchar2(6) NULL,
	"NAIC2_CODE" varchar2(6) NULL,
	"NAIC3_CODE" varchar2(6) NULL,
	"NAIC4_CODE" varchar2(6) NULL,
	"IN_HANDLER_UNIVERSE" char(1) NULL,
	"IN_A_UNIVERSE" char(1) NULL,
	"FED_WASTE_GENERATOR_OWNER" char(2) NULL,
	"FED_WASTE_GENERATOR" char(1) NULL,
	"STATE_WASTE_GENERATOR_OWNER" char(2) NULL,
	"STATE_WASTE_GENERATOR" char(1) NULL,
	"GEN_STATUS" varchar2(3) NULL,
	"UNIV_WASTE" char(1) NULL,
	"LAND_TYPE" char(1) NULL,
	"STATE_DISTRICT_OWNER" char(2) NULL,
	"STATE_DISTRICT" varchar2(10) NULL,
	"SHORT_TERM_GEN_IND" char(1) NULL,
	"IMPORTER_ACTIVITY" char(1) NULL,
	"MIXED_WASTE_GENERATOR" char(1) NULL,
	"TRANSPORTER_ACTIVITY" char(1) NULL,
	"TRANSFER_FACILITY_IND" char(1) NULL,
	"RECYCLER_ACTIVITY" char(1) NULL,
	"ONSITE_BURNER_EXEMPTION" char(1) NULL,
	"FURNACE_EXEMPTION" char(1) NULL,
	"UNDERGROUND_INJECTION_ACTIVITY" char(1) NULL,
	"UNIVERSAL_WASTE_DEST_FACILITY" char(1) NULL,
	"OFFSITE_WASTE_RECEIPT" char(1) NULL,
	"USED_OIL" varchar2(7) NULL,
	"FEDERAL_UNIVERSAL_WASTE" char(1) NULL,
	"AS_FEDERAL_REGULATED_TSDF" varchar2(6) NULL,
	"AS_CONVERTED_TSDF" varchar2(6) NULL,
	"AS_STATE_REGULATED_TSDF" varchar2(9) NULL,
	"FEDERAL_IND" varchar2(3) NULL,
	"HSM" char(2) NULL,
	"SUBPART_K" varchar2(4) NULL,
	"COMMERCIAL_TSD" char(1) NULL,
	"TSD" varchar2(5) NULL,
	"GPRA_PERMIT" char(1) NULL,
	"GPRA_RENEWAL" char(1) NULL,
	"PERMIT_RENEWAL_WRKLD" varchar2(6) NULL,
	"PERM_WRKLD" varchar2(6) NULL,
	"PERM_PROG" varchar2(6) NULL,
	"PC_WRKLD" varchar2(6) NULL,
	"CLOS_WRKLD" varchar2(6) NULL,
	"GPRACA" char(1) NULL,
	"CA_WRKLD" char(1) NULL,
	"SUBJ_CA" char(1) NULL,
	"SUBJ_CA_NON_TSD" char(1) NULL,
	"SUBJ_CA_TSD_3004" char(1) NULL,
	"SUBJ_CA_DISCRETION" char(1) NULL,
	"NCAPS" char(1) NULL,
	"EC_IND" char(1) NULL,
	"IC_IND" char(1) NULL,
	"CA_725_IND" char(1) NULL,
	"CA_750_IND" char(1) NULL,
	"OPERATING_TSDF" varchar2(6) NULL,
	"FULL_ENFORCEMENT" varchar2(6) NULL,
	"SNC" char(1) NULL,
	"BOY_SNC" char(1) NULL,
	"BOY_STATE_UNADDRESSED_SNC" char(1) NULL,
	"STATE_UNADDRESSED" char(1) NULL,
	"STATE_ADDRESSED" char(1) NULL,
	"BOY_STATE_ADDRESSED" char(1) NULL,
	"STATE_SNC_WITH_COMP_SCHED" char(1) NULL,
	"BOY_STATE_SNC_WITH_COMP_SCHED" char(1) NULL,
	"EPA_UNADDRESSED" char(1) NULL,
	"BOY_EPA_UNADDRESSED" char(1) NULL,
	"EPA_ADDRESSED" char(1) NULL,
	"BOY_EPA_ADDRESSED" char(1) NULL,
	"EPA_SNC_WITH_COMP_SCHED" char(1) NULL,
	"BOY_EPA_SNC_WITH_COMP_SCHED" char(1) NULL,
	"FA_REQUIRED" varchar2(5) NULL,
	"HHANDLER_LAST_CHANGE_DATE" DATE NULL,
	"PUBLIC_NOTES" varchar2(4000) NULL,
	"NOTES" varchar2(4000) NULL,
	"RECOGNIZED_TRADER_IMPORTER_IND" char(1) NULL,
	"RECOGNIZED_TRADER_EXPORTER_IND" char(1) NULL,
	"SLAB_IMPORTER_IND" char(1) NULL,
	"SLAB_EXPORTER_IND" char(1) NULL,
	"RECYCLER_NON_STORAGE_IND" char(1) NULL,
	"MANIFEST_BROKER_IND" char(1) NULL,
	"SUBPART_P_IND" char(1) NULL,
	"LOCATION_LATITUDE" number(19, 14) NULL,
	"LOCATION_LONGITUDE" number(19, 14) NULL,
	"LOCATION_GIS_PRIM" char(1) NULL,
	"LOCATION_GIS_ORIG" char(2) NULL,
	"LOCATION_STREET_NUMBER" varchar2(12) NULL,
	"LOCATION_STREET1" varchar2(50) NULL,
	"LOCATION_STREET2" varchar2(50) NULL,
	"LOCATION_CITY" varchar2(25) NULL,
	"LOCATION_STATE" char(2) NULL,
	"LOCATION_COUNTRY" char(2) NULL,
	"LOCATION_ZIP" varchar2(14) NULL,
	"MAIL_STREET_NUMBER" varchar2(12) NULL,
	"MAIL_STREET1" varchar2(50) NULL,
	"MAIL_STREET2" varchar2(50) NULL,
	"MAIL_CITY" varchar2(25) NULL,
	"MAIL_STATE" char(2) NULL,
	"MAIL_COUNTRY" char(2) NULL,
	"MAIL_ZIP" varchar2(14) NULL,
	"CONTACT_STREET_NUMBER" varchar2(12) NULL,
	"CONTACT_STREET1" varchar2(50) NULL,
	"CONTACT_STREET2" varchar2(50) NULL,
	"CONTACT_CITY" varchar2(25) NULL,
	"CONTACT_STATE" char(2) NULL,
	"CONTACT_COUNTRY" char(2) NULL,
	"CONTACT_ZIP" varchar2(14) NULL,
 CONSTRAINT "PK_RU_REPORT_UNIV" PRIMARY KEY 
(
	"RU_REPORT_UNIV_ID"
)
);





CREATE TABLE "RCRA_RU_REPORT_UNIV_SUBM"(
	"RU_REPORT_UNIV_SUBM_ID" varchar2(40) NOT NULL,
	"RU_SUBM_ID" varchar2(40) NOT NULL,
 CONSTRAINT "PK_RU_REPORT_UNIV_SUBM" PRIMARY KEY 
(
	"RU_REPORT_UNIV_SUBM_ID"
)
);





CREATE TABLE "RCRA_RU_SUBM"(
	"RU_SUBM_ID" varchar2(40) NOT NULL,
	"DATA_ACCESS" varchar2(10) NULL,
 CONSTRAINT "PK_RU_SUBM" PRIMARY KEY 
(
	"RU_SUBM_ID"
)
);






CREATE TABLE "RCRA_SUBMISSIONHISTORY"(
	"SUBMISSIONHISTORY_ID" varchar2(40) NOT NULL,
	"SUBMISSIONTYPE" varchar2(50) NOT NULL,
	"SCHEDULERUNDATE" DATE NOT NULL,
	"TRANSACTIONID" varchar2(50) NOT NULL,
	"PROCESSINGSTATUS" varchar2(50) NOT NULL,
 CONSTRAINT "PK_SUBMISSIONHISTORY" PRIMARY KEY 
(
	"SUBMISSIONHISTORY_ID"
)
);







CREATE INDEX "IX_CA_AREA_CA_FAC_SUBM_ID" ON "RCRA_CA_AREA"
(
	"CA_FAC_SUBM_ID"
);



CREATE INDEX "IX_CA_AREA_REL_EVENT_CA_ARA_ID" ON "RCRA_CA_AREA_REL_EVENT"
(
	"CA_AREA_ID"
);



CREATE INDEX "IX_CA_ATH_RL_EVNT_CA_ATHRTY_ID" ON "RCRA_CA_AUTH_REL_EVENT"
(
	"CA_AUTHORITY_ID"
);



CREATE INDEX "IX_CA_AUTHORITY_CA_FAC_SUBM_ID" ON "RCRA_CA_AUTHORITY"
(
	"CA_FAC_SUBM_ID"
);



CREATE INDEX "IX_CA_EVENT_CA_FAC_SUBM_ID" ON "RCRA_CA_EVENT"
(
	"CA_FAC_SUBM_ID"
);



CREATE INDEX "IX_CA_EVNT_COMMTMNT_CA_EVNT_ID" ON "RCRA_CA_EVENT_COMMITMENT"
(
	"CA_EVENT_ID"
);



CREATE INDEX "IX_CA_FAC_SUBM_CA_SUBM_ID" ON "RCRA_CA_FAC_SUBM"
(
	"CA_SUBM_ID"
);



CREATE INDEX "IX_CA_REL_PERMIT_UNT_CA_ARA_ID" ON "RCRA_CA_REL_PERMIT_UNIT"
(
	"CA_AREA_ID"
);



CREATE INDEX "IX_CA_STTTRY_CTTN_CA_ATHRTY_ID" ON "RCRA_CA_STATUTORY_CITATION"
(
	"CA_AUTHORITY_ID"
);



CREATE INDEX "IX_CME_CITATION_CME_VIOL_ID" ON "RCRA_CME_CITATION"
(
	"CME_VIOL_ID"
);



CREATE INDEX "IX_CME_CSNY_DTE_CME_ENF_ACT_ID" ON "RCRA_CME_CSNY_DATE"
(
	"CME_ENFRC_ACT_ID"
);



CREATE INDEX "IX_CME_ENFRC_ACT_CME_FC_SBM_ID" ON "RCRA_CME_ENFRC_ACT"
(
	"CME_FAC_SUBM_ID"
);



CREATE INDEX "IX_CME_EVAL_CME_FAC_SUBM_ID" ON "RCRA_CME_EVAL"
(
	"CME_FAC_SUBM_ID"
);



CREATE INDEX "IX_CME_EVAL_COMMIT_CME_EVAL_ID" ON "RCRA_CME_EVAL_COMMIT"
(
	"CME_EVAL_ID"
);



CREATE INDEX "IX_CME_EVAL_VIOL_CME_EVAL_ID" ON "RCRA_CME_EVAL_VIOL"
(
	"CME_EVAL_ID"
);



CREATE INDEX "IX_CME_FAC_SUBM_CME_SUBM_ID" ON "RCRA_CME_FAC_SUBM"
(
	"CME_SUBM_ID"
);



CREATE INDEX "IX_CME_MEDIA_CME_ENFRC_ACT_ID" ON "RCRA_CME_MEDIA"
(
	"CME_ENFRC_ACT_ID"
);



CREATE INDEX "IX_CME_MLSTNE_CME_ENFRC_ACT_ID" ON "RCRA_CME_MILESTONE"
(
	"CME_ENFRC_ACT_ID"
);



CREATE INDEX "IX_CME_PNLTY_CME_ENFRC_ACT_ID" ON "RCRA_CME_PNLTY"
(
	"CME_ENFRC_ACT_ID"
);



CREATE INDEX "IX_CME_PYMT_CME_PNLTY_ID" ON "RCRA_CME_PYMT"
(
	"CME_PNLTY_ID"
);



CREATE INDEX "IX_CME_RQST_CME_EVAL_ID" ON "RCRA_CME_RQST"
(
	"CME_EVAL_ID"
);



CREATE INDEX "IX_CME_SPP_ENV_PRJ_CM_EN_AC_ID" ON "RCRA_CME_SUPP_ENVR_PRJT"
(
	"CME_ENFRC_ACT_ID"
);



CREATE INDEX "IX_CME_VIOL_CME_FAC_SUBM_ID" ON "RCRA_CME_VIOL"
(
	"CME_FAC_SUBM_ID"
);



CREATE INDEX "IX_CME_VL_ENFR_CME_ENFR_ACT_ID" ON "RCRA_CME_VIOL_ENFRC"
(
	"CME_ENFRC_ACT_ID"
);



CREATE INDEX "IX_EM_EMANIFEST_EM_SUBM_ID" ON "RCRA_EM_EMANIFEST"
(
	"EM_SUBM_ID"
);



CREATE INDEX "IX_EM_EMNFST_CMMNT_EM_EMNFS_ID" ON "RCRA_EM_EMANIFEST_COMMENT"
(
	"EM_EMANIFEST_ID"
);



CREATE INDEX "IX_EM_FD_WST_CDE_DSC_EM_WST_ID" ON "RCRA_EM_FED_WASTE_CODE_DESC"
(
	"EM_WASTE_ID"
);



CREATE INDEX "IX_EM_STT_WST_CDE_DSC_EM_WS_ID" ON "RCRA_EM_STATE_WASTE_CODE_DESC"
(
	"EM_WASTE_ID"
);



CREATE INDEX "IX_EM_TRNSPORTER_EM_EMNIFST_ID" ON "RCRA_EM_TRANSPORTER"
(
	"EM_EMANIFEST_ID"
);



CREATE INDEX "IX_EM_WASTE_EM_EMANIFEST_ID" ON "RCRA_EM_WASTE"
(
	"EM_EMANIFEST_ID"
);



CREATE INDEX "IX_EM_WASTE_CD_TRNS_EM_WSTE_ID" ON "RCRA_EM_WASTE_CD_TRANS"
(
	"EM_WASTE_ID"
);



CREATE INDEX "IX_EM_WASTE_COMMENT_EM_WSTE_ID" ON "RCRA_EM_WASTE_COMMENT"
(
	"EM_WASTE_ID"
);



CREATE INDEX "IX_EM_WASTE_PCB_EM_WASTE_ID" ON "RCRA_EM_WASTE_PCB"
(
	"EM_WASTE_ID"
);



CREATE INDEX "IX_FA_COST_EST_FA_FAC_SUBM_ID" ON "RCRA_FA_COST_EST"
(
	"FA_FAC_SUBM_ID"
);



CREATE INDEX "IX_FA_CST_ES_RL_MC_FA_CS_ES_ID" ON "RCRA_FA_COST_EST_REL_MECHANISM"
(
	"FA_COST_EST_ID"
);



CREATE INDEX "IX_FA_FAC_SUBM_FA_SUBM_ID" ON "RCRA_FA_FAC_SUBM"
(
	"FA_SUBM_ID"
);



CREATE INDEX "IX_FA_MECHANISM_FA_FAC_SUBM_ID" ON "RCRA_FA_MECHANISM"
(
	"FA_FAC_SUBM_ID"
);



CREATE INDEX "IX_FA_MCHNISM_DTL_FA_MCHNSM_ID" ON "RCRA_FA_MECHANISM_DETAIL"
(
	"FA_MECHANISM_ID"
);



CREATE INDEX "IX_GIS_FAC_SUBM_GIS_SUBM_ID" ON "RCRA_GIS_FAC_SUBM"
(
	"GIS_SUBM_ID"
);



CREATE INDEX "IX_GS__INFORMTN_GS_FC_SBM_ID" ON "RCRA_GIS_GEO_INFORMATION"
(
	"GIS_FAC_SUBM_ID"
);



CREATE INDEX "IX_HD_ADD_CONTACT_HD_HANDLE_ID" ON "RCRA_HD_ADD_CONTACT"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_HD_CERTIFICATIO_HD_HANDL_ID" ON "RCRA_HD_CERTIFICATION"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_HD_ENV_PERMIT_HD_HANDLER_ID" ON "RCRA_HD_ENV_PERMIT"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_HD_EPISOD_EVENT_HD_HANDL_ID" ON "RCRA_HD_EPISODIC_EVENT"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_HD_EPIS_PRJT_HD_EPIS_EVE_ID" ON "RCRA_HD_EPISODIC_PRJT"
(
	"HD_EPISODIC_EVENT_ID"
);



CREATE INDEX "IX_HD_EPIS_WAST_HD_EPIS_EVE_ID" ON "RCRA_HD_EPISODIC_WASTE"
(
	"HD_EPISODIC_EVENT_ID"
);



CREATE INDEX "IX_HD_EPI_WAS_COD_HD_EPI_WA_ID" ON "RCRA_HD_EPISODIC_WASTE_CODE"
(
	"HD_EPISODIC_WASTE_ID"
);



CREATE INDEX "IX_HD_HANDLER_HD_HBASIC_ID" ON "RCRA_HD_HANDLER"
(
	"HD_HBASIC_ID"
);



CREATE INDEX "IX_HD_HBASIC_HD_SUBM_ID" ON "RCRA_HD_HBASIC"
(
	"HD_SUBM_ID"
);



CREATE INDEX "IX_HD_LQG_CLOSURE_HD_HANDLE_ID" ON "RCRA_HD_LQG_CLOSURE"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_HD_LQG_CONSOLID_HD_HANDL_ID" ON "RCRA_HD_LQG_CONSOLIDATION"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_HD_NAICS_HD_HANDLER_ID" ON "RCRA_HD_NAICS"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_HD_OTHER_ID_HD_HBASIC_ID" ON "RCRA_HD_OTHER_ID"
(
	"HD_HBASIC_ID"
);



CREATE INDEX "IX_HD_OWNEROP_HD_HANDLER_ID" ON "RCRA_HD_OWNEROP"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_HD_SEC_MATE_ACTI_HD_HAND_ID" ON "RCRA_HD_SEC_MATERIAL_ACTIVITY"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_HD_SEC_WA_CO_HD_SE_MA_AC_ID" ON "RCRA_HD_SEC_WASTE_CODE"
(
	"HD_SEC_MATERIAL_ACTIVITY_ID"
);



CREATE INDEX "IX_HD_STATE_ACTIVI_HD_HANDL_ID" ON "RCRA_HD_STATE_ACTIVITY"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_HD_UNIVER_WASTE_HD_HANDL_ID" ON "RCRA_HD_UNIVERSAL_WASTE"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_HD_WASTE_CODE_HD_HANDLER_ID" ON "RCRA_HD_WASTE_CODE"
(
	"HD_HANDLER_ID"
);



CREATE INDEX "IX_PRM_EVENT_PRM_SERIES_ID" ON "RCRA_PRM_EVENT"
(
	"PRM_SERIES_ID"
);



CREATE INDEX "IX_PRM_EVNT_CMMTMN_PRM_EVNT_ID" ON "RCRA_PRM_EVENT_COMMITMENT"
(
	"PRM_EVENT_ID"
);



CREATE INDEX "IX_PRM_FAC_SUBM_PRM_SUBM_ID" ON "RCRA_PRM_FAC_SUBM"
(
	"PRM_SUBM_ID"
);



CREATE INDEX "IX_PRM_MOD_EVENT_PRM_EVENT_ID" ON "RCRA_PRM_MOD_EVENT"
(
	"PRM_EVENT_ID"
);



CREATE INDEX "IX_PRM_RLTD_EVN_PRM_UNT_DTL_ID" ON "RCRA_PRM_RELATED_EVENT"
(
	"PRM_UNIT_DETAIL_ID"
);



CREATE INDEX "IX_PRM_SERIES_PRM_FAC_SUBM_ID" ON "RCRA_PRM_SERIES"
(
	"PRM_FAC_SUBM_ID"
);



CREATE INDEX "IX_PRM_UNIT_PRM_FAC_SUBM_ID" ON "RCRA_PRM_UNIT"
(
	"PRM_FAC_SUBM_ID"
);



CREATE INDEX "IX_PRM_UNIT_DETAIL_PRM_UNIT_ID" ON "RCRA_PRM_UNIT_DETAIL"
(
	"PRM_UNIT_ID"
);



CREATE INDEX "IX_PRM_WSTE_CDE_PRM_UNT_DTL_ID" ON "RCRA_PRM_WASTE_CODE"
(
	"PRM_UNIT_DETAIL_ID"
);



CREATE INDEX "IX_RU_RPR_UNV_RU_RPR_UNV_SB_ID" ON "RCRA_RU_REPORT_UNIV"
(
	"RU_REPORT_UNIV_SUBM_ID"
);



CREATE INDEX "IX_RU_REPORT_UNV_SBM_RU_SBM_ID" ON "RCRA_RU_REPORT_UNIV_SUBM"
(
	"RU_SUBM_ID"
);

ALTER TABLE "RCRA_CA_AREA"  ADD  CONSTRAINT "FK_CA_AREA_CA_FAC_SUBM" FOREIGN KEY("CA_FAC_SUBM_ID")
REFERENCES "RCRA_CA_FAC_SUBM" ("CA_FAC_SUBM_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_CA_AREA_REL_EVENT"  ADD  CONSTRAINT "FK_CA_AREA_REL_EVENT_CA_AREA" FOREIGN KEY("CA_AREA_ID")
REFERENCES "RCRA_CA_AREA" ("CA_AREA_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_CA_AUTH_REL_EVENT"  ADD  CONSTRAINT "FK_CA_AUTH_RL_EVNT_CA_AUTHORTY" FOREIGN KEY("CA_AUTHORITY_ID")
REFERENCES "RCRA_CA_AUTHORITY" ("CA_AUTHORITY_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_CA_AUTHORITY"  ADD  CONSTRAINT "FK_CA_AUTHORITY_CA_FAC_SUBM" FOREIGN KEY("CA_FAC_SUBM_ID")
REFERENCES "RCRA_CA_FAC_SUBM" ("CA_FAC_SUBM_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_CA_EVENT"  ADD  CONSTRAINT "FK_CA_EVENT_CA_FAC_SUBM" FOREIGN KEY("CA_FAC_SUBM_ID")
REFERENCES "RCRA_CA_FAC_SUBM" ("CA_FAC_SUBM_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_CA_EVENT_COMMITMENT"  ADD  CONSTRAINT "FK_CA_EVENT_COMMITMENT_CA_EVNT" FOREIGN KEY("CA_EVENT_ID")
REFERENCES "RCRA_CA_EVENT" ("CA_EVENT_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_CA_FAC_SUBM"  ADD  CONSTRAINT "FK_CA_FAC_SUBM_CA_SUBM" FOREIGN KEY("CA_SUBM_ID")
REFERENCES "RCRA_CA_SUBM" ("CA_SUBM_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_CA_REL_PERMIT_UNIT"  ADD  CONSTRAINT "FK_CA_REL_PERMIT_UNIT_CA_AREA" FOREIGN KEY("CA_AREA_ID")
REFERENCES "RCRA_CA_AREA" ("CA_AREA_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CA_STATUTORY_CITATION"  ADD  CONSTRAINT "FK_CA_STTUTRY_CITTON_CA_ATHRTY" FOREIGN KEY("CA_AUTHORITY_ID")
REFERENCES "RCRA_CA_AUTHORITY" ("CA_AUTHORITY_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_CITATION"  ADD  CONSTRAINT "FK_CME_CITATION_CME_VIOL" FOREIGN KEY("CME_VIOL_ID")
REFERENCES "RCRA_CME_VIOL" ("CME_VIOL_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_CSNY_DATE"  ADD  CONSTRAINT "FK_CME_CSNY_DATE_CME_ENFRC_ACT" FOREIGN KEY("CME_ENFRC_ACT_ID")
REFERENCES "RCRA_CME_ENFRC_ACT" ("CME_ENFRC_ACT_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_ENFRC_ACT"  ADD  CONSTRAINT "FK_CME_ENFRC_ACT_CME_FAC_SUBM" FOREIGN KEY("CME_FAC_SUBM_ID")
REFERENCES "RCRA_CME_FAC_SUBM" ("CME_FAC_SUBM_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_EVAL"  ADD  CONSTRAINT "FK_CME_EVAL_CME_FAC_SUBM" FOREIGN KEY("CME_FAC_SUBM_ID")
REFERENCES "RCRA_CME_FAC_SUBM" ("CME_FAC_SUBM_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_CME_EVAL_COMMIT"  ADD  CONSTRAINT "FK_CME_EVAL_COMMIT_CME_EVAL" FOREIGN KEY("CME_EVAL_ID")
REFERENCES "RCRA_CME_EVAL" ("CME_EVAL_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_EVAL_VIOL"  ADD  CONSTRAINT "FK_CME_EVAL_VIOL_CME_EVAL" FOREIGN KEY("CME_EVAL_ID")
REFERENCES "RCRA_CME_EVAL" ("CME_EVAL_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_FAC_SUBM"  ADD  CONSTRAINT "FK_CME_FAC_SUBM_CME_SUBM" FOREIGN KEY("CME_SUBM_ID")
REFERENCES "RCRA_CME_SUBM" ("CME_SUBM_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_MEDIA"  ADD  CONSTRAINT "FK_CME_MEDIA_CME_ENFRC_ACT" FOREIGN KEY("CME_ENFRC_ACT_ID")
REFERENCES "RCRA_CME_ENFRC_ACT" ("CME_ENFRC_ACT_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_MILESTONE"  ADD  CONSTRAINT "FK_CME_MILESTONE_CME_ENFRC_ACT" FOREIGN KEY("CME_ENFRC_ACT_ID")
REFERENCES "RCRA_CME_ENFRC_ACT" ("CME_ENFRC_ACT_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_PNLTY"  ADD  CONSTRAINT "FK_CME_PNLTY_CME_ENFRC_ACT" FOREIGN KEY("CME_ENFRC_ACT_ID")
REFERENCES "RCRA_CME_ENFRC_ACT" ("CME_ENFRC_ACT_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_PYMT"  ADD  CONSTRAINT "FK_CME_PYMT_CME_PNLTY" FOREIGN KEY("CME_PNLTY_ID")
REFERENCES "RCRA_CME_PNLTY" ("CME_PNLTY_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_RQST"  ADD  CONSTRAINT "FK_CME_RQST_CME_EVAL" FOREIGN KEY("CME_EVAL_ID")
REFERENCES "RCRA_CME_EVAL" ("CME_EVAL_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_SUPP_ENVR_PRJT"  ADD  CONSTRAINT "FK_CME_SPP_ENV_PRJ_CME_ENF_ACT" FOREIGN KEY("CME_ENFRC_ACT_ID")
REFERENCES "RCRA_CME_ENFRC_ACT" ("CME_ENFRC_ACT_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_VIOL"  ADD  CONSTRAINT "FK_CME_VIOL_CME_FAC_SUBM" FOREIGN KEY("CME_FAC_SUBM_ID")
REFERENCES "RCRA_CME_FAC_SUBM" ("CME_FAC_SUBM_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_CME_VIOL_ENFRC"  ADD  CONSTRAINT "FK_CME_VL_ENFRC_CME_ENFRC_ACT" FOREIGN KEY("CME_ENFRC_ACT_ID")
REFERENCES "RCRA_CME_ENFRC_ACT" ("CME_ENFRC_ACT_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_EM_EMANIFEST"  ADD  CONSTRAINT "FK_EM_EMANIFEST_EM_SUBM" FOREIGN KEY("EM_SUBM_ID")
REFERENCES "RCRA_EM_SUBM" ("EM_SUBM_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_EM_EMANIFEST_COMMENT"  ADD  CONSTRAINT "FK_EM_EMNIFST_CMMNT_EM_EMNIFST" FOREIGN KEY("EM_EMANIFEST_ID")
REFERENCES "RCRA_EM_EMANIFEST" ("EM_EMANIFEST_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_EM_FED_WASTE_CODE_DESC"  ADD  CONSTRAINT "FK_EM_FED_WSTE_CDE_DSC_EM_WSTE" FOREIGN KEY("EM_WASTE_ID")
REFERENCES "RCRA_EM_WASTE" ("EM_WASTE_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_EM_STATE_WASTE_CODE_DESC"  ADD  CONSTRAINT "FK_EM_STTE_WSTE_CDE_DSC_EM_WST" FOREIGN KEY("EM_WASTE_ID")
REFERENCES "RCRA_EM_WASTE" ("EM_WASTE_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_EM_TRANSPORTER"  ADD  CONSTRAINT "FK_EM_TRANSPORTER_EM_EMANIFEST" FOREIGN KEY("EM_EMANIFEST_ID")
REFERENCES "RCRA_EM_EMANIFEST" ("EM_EMANIFEST_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_EM_WASTE"  ADD  CONSTRAINT "FK_EM_WASTE_EM_EMANIFEST" FOREIGN KEY("EM_EMANIFEST_ID")
REFERENCES "RCRA_EM_EMANIFEST" ("EM_EMANIFEST_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_EM_WASTE_CD_TRANS"  ADD  CONSTRAINT "FK_EM_WASTE_CD_TRANS_EM_WASTE" FOREIGN KEY("EM_WASTE_ID")
REFERENCES "RCRA_EM_WASTE" ("EM_WASTE_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_EM_WASTE_COMMENT"  ADD  CONSTRAINT "FK_EM_WASTE_COMMENT_EM_WASTE" FOREIGN KEY("EM_WASTE_ID")
REFERENCES "RCRA_EM_WASTE" ("EM_WASTE_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_EM_WASTE_PCB"  ADD  CONSTRAINT "FK_EM_WASTE_PCB_EM_WASTE" FOREIGN KEY("EM_WASTE_ID")
REFERENCES "RCRA_EM_WASTE" ("EM_WASTE_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_FA_COST_EST"  ADD  CONSTRAINT "FK_FA_COST_EST_FA_FAC_SUBM" FOREIGN KEY("FA_FAC_SUBM_ID")
REFERENCES "RCRA_FA_FAC_SUBM" ("FA_FAC_SUBM_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_FA_COST_EST_REL_MECHANISM"  ADD  CONSTRAINT "FK_FA_CST_EST_RL_MCH_FA_CST_ES" FOREIGN KEY("FA_COST_EST_ID")
REFERENCES "RCRA_FA_COST_EST" ("FA_COST_EST_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_FA_FAC_SUBM"  ADD  CONSTRAINT "FK_FA_FAC_SUBM_FA_SUBM" FOREIGN KEY("FA_SUBM_ID")
REFERENCES "RCRA_FA_SUBM" ("FA_SUBM_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_FA_MECHANISM"  ADD  CONSTRAINT "FK_FA_MECHANISM_FA_FAC_SUBM" FOREIGN KEY("FA_FAC_SUBM_ID")
REFERENCES "RCRA_FA_FAC_SUBM" ("FA_FAC_SUBM_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_FA_MECHANISM_DETAIL"  ADD  CONSTRAINT "FK_FA_MECHNISM_DTIL_FA_MCHNISM" FOREIGN KEY("FA_MECHANISM_ID")
REFERENCES "RCRA_FA_MECHANISM" ("FA_MECHANISM_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_GIS_FAC_SUBM"  ADD  CONSTRAINT "FK_GIS_FAC_SUBM_GIS_SUBM" FOREIGN KEY("GIS_SUBM_ID")
REFERENCES "RCRA_GIS_SUBM" ("GIS_SUBM_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_GIS_GEO_INFORMATION"  ADD  CONSTRAINT "FK_GIS__INFORMTION_GS_FC_SBM" FOREIGN KEY("GIS_FAC_SUBM_ID")
REFERENCES "RCRA_GIS_FAC_SUBM" ("GIS_FAC_SUBM_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_HD_ADD_CONTACT"  ADD  CONSTRAINT "FK_HD_ADD_CONTACT_HD_HANDLER" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_CERTIFICATION"  ADD  CONSTRAINT "FK_HD_CERTIFICATION_HD_HANDLER" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;

ALTER TABLE "RCRA_HD_ENV_PERMIT"  ADD  CONSTRAINT "FK_HD_ENV_PERMIT_HD_HANDLER" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_EPISODIC_EVENT"  ADD  CONSTRAINT "FK_HD_EPISODIC_EVENT_HD_HANDLE" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_EPISODIC_PRJT"  ADD  CONSTRAINT "FK_HD_EPISO_PRJT_HD_EPISO_EVEN" FOREIGN KEY("HD_EPISODIC_EVENT_ID")
REFERENCES "RCRA_HD_EPISODIC_EVENT" ("HD_EPISODIC_EVENT_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_EPISODIC_WASTE"  ADD  CONSTRAINT "FK_HD_EPISO_WASTE_HD_EPIS_EVEN" FOREIGN KEY("HD_EPISODIC_EVENT_ID")
REFERENCES "RCRA_HD_EPISODIC_EVENT" ("HD_EPISODIC_EVENT_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_EPISODIC_WASTE_CODE"  ADD  CONSTRAINT "FK_HD_EPIS_WAST_COD_HD_EPI_WAS" FOREIGN KEY("HD_EPISODIC_WASTE_ID")
REFERENCES "RCRA_HD_EPISODIC_WASTE" ("HD_EPISODIC_WASTE_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_HANDLER"  ADD  CONSTRAINT "FK_HD_HANDLER_HD_HBASIC" FOREIGN KEY("HD_HBASIC_ID")
REFERENCES "RCRA_HD_HBASIC" ("HD_HBASIC_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_HBASIC"  ADD  CONSTRAINT "FK_HD_HBASIC_HD_SUBM" FOREIGN KEY("HD_SUBM_ID")
REFERENCES "RCRA_HD_SUBM" ("HD_SUBM_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_LQG_CLOSURE"  ADD  CONSTRAINT "FK_HD_LQG_CLOSURE_HD_HANDLER" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_LQG_CONSOLIDATION"  ADD  CONSTRAINT "FK_HD_LQG_CONSOLIDATI_HD_HANDL" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_NAICS"  ADD  CONSTRAINT "FK_HD_NAICS_HD_HANDLER" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;



ALTER TABLE "RCRA_HD_OTHER_ID"  ADD  CONSTRAINT "FK_HD_OTHER_ID_HD_HBASIC" FOREIGN KEY("HD_HBASIC_ID")
REFERENCES "RCRA_HD_HBASIC" ("HD_HBASIC_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_OWNEROP"  ADD  CONSTRAINT "FK_HD_OWNEROP_HD_HANDLER" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_SEC_MATERIAL_ACTIVITY"  ADD  CONSTRAINT "FK_HD_SEC_MATER_ACTIV_HD_HANDL" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_SEC_WASTE_CODE"  ADD  CONSTRAINT "FK_HD_SEC_WAS_COD_HD_SEC_MA_AC" FOREIGN KEY("HD_SEC_MATERIAL_ACTIVITY_ID")
REFERENCES "RCRA_HD_SEC_MATERIAL_ACTIVITY" ("HD_SEC_MATERIAL_ACTIVITY_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_STATE_ACTIVITY"  ADD  CONSTRAINT "FK_HD_STATE_ACTIVITY_HD_HANDLE" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_UNIVERSAL_WASTE"  ADD  CONSTRAINT "FK_HD_UNIVERSA_WASTE_HD_HANDLE" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_HD_WASTE_CODE"  ADD  CONSTRAINT "FK_HD_WASTE_CODE_HD_HANDLER" FOREIGN KEY("HD_HANDLER_ID")
REFERENCES "RCRA_HD_HANDLER" ("HD_HANDLER_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_PRM_EVENT"  ADD  CONSTRAINT "FK_PRM_EVENT_PRM_SERIES" FOREIGN KEY("PRM_SERIES_ID")
REFERENCES "RCRA_PRM_SERIES" ("PRM_SERIES_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_PRM_EVENT_COMMITMENT"  ADD  CONSTRAINT "FK_PRM_EVNT_COMMITMNT_PRM_EVNT" FOREIGN KEY("PRM_EVENT_ID")
REFERENCES "RCRA_PRM_EVENT" ("PRM_EVENT_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_PRM_FAC_SUBM"  ADD  CONSTRAINT "FK_PRM_FAC_SUBM_PRM_SUBM" FOREIGN KEY("PRM_SUBM_ID")
REFERENCES "RCRA_PRM_SUBM" ("PRM_SUBM_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_PRM_MOD_EVENT"  ADD  CONSTRAINT "FK_PRM_MOD_EVENT_PRM_EVENT" FOREIGN KEY("PRM_EVENT_ID")
REFERENCES "RCRA_PRM_EVENT" ("PRM_EVENT_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_PRM_RELATED_EVENT"  ADD  CONSTRAINT "FK_PRM_RELTD_EVNT_PRM_UNT_DTIL" FOREIGN KEY("PRM_UNIT_DETAIL_ID")
REFERENCES "RCRA_PRM_UNIT_DETAIL" ("PRM_UNIT_DETAIL_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_PRM_SERIES"  ADD  CONSTRAINT "FK_PRM_SERIES_PRM_FAC_SUBM" FOREIGN KEY("PRM_FAC_SUBM_ID")
REFERENCES "RCRA_PRM_FAC_SUBM" ("PRM_FAC_SUBM_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_PRM_UNIT"  ADD  CONSTRAINT "FK_PRM_UNIT_PRM_FAC_SUBM" FOREIGN KEY("PRM_FAC_SUBM_ID")
REFERENCES "RCRA_PRM_FAC_SUBM" ("PRM_FAC_SUBM_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_PRM_UNIT_DETAIL"  ADD  CONSTRAINT "FK_PRM_UNIT_DETAIL_PRM_UNIT" FOREIGN KEY("PRM_UNIT_ID")
REFERENCES "RCRA_PRM_UNIT" ("PRM_UNIT_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_PRM_WASTE_CODE"  ADD  CONSTRAINT "FK_PRM_WASTE_CDE_PRM_UNT_DETIL" FOREIGN KEY("PRM_UNIT_DETAIL_ID")
REFERENCES "RCRA_PRM_UNIT_DETAIL" ("PRM_UNIT_DETAIL_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_RU_REPORT_UNIV"  ADD  CONSTRAINT "FK_RU_RPRT_UNV_RU_RPRT_UNV_SBM" FOREIGN KEY("RU_REPORT_UNIV_SUBM_ID")
REFERENCES "RCRA_RU_REPORT_UNIV_SUBM" ("RU_REPORT_UNIV_SUBM_ID")
ON DELETE CASCADE;


ALTER TABLE "RCRA_RU_REPORT_UNIV_SUBM"  ADD  CONSTRAINT "FK_RU_REPORT_UNIV_SUBM_RU_SUBM" FOREIGN KEY("RU_SUBM_ID")
REFERENCES "RCRA_RU_SUBM" ("RU_SUBM_ID")
ON DELETE CASCADE;