/*
Copyright (c) 2016, The Environmental Council of the States (ECOS)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/

/*****************************************************************************************************************************
 *
 *  Script Name:  RCRA_5.12_to_5.13-upgrade_SQL-DDL.sql
 *
 *  Company:  Windsor Solutions, Inc.
 *
 *  Purpose:  This DDL script will alter the SQL Server database objects supporting the RCRA v5.12 data flow to conform with
 *            the RCRA v5.13 schema.
 *
 *  Maintenance:
 *
 *    Analyst         Date            Comment
 *    ----------      ----------      ------------------------------------------------------------------------------
 *    Windsor         03/20/2024      Created
 *
 ****************************************************************************************************************************
 */

---$ Alter table dbo.RCRA_HD_EPISODIC_EVENT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_EPISODIC_EVENT') AND NAME = 'CONTACT_LANG_CODE')
BEGIN
    ALTER TABLE dbo.RCRA_HD_EPISODIC_EVENT
        ADD CONTACT_LANG_CODE CHAR(2) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_EPISODIC_EVENT') AND NAME = 'CONTACT_LANG_DESC')
BEGIN
    ALTER TABLE dbo.RCRA_HD_EPISODIC_EVENT
        ADD CONTACT_LANG_DESC VARCHAR(50) NULL
END
GO


---$ Alter table dbo.RCRA_HD_HANDLER
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'CONTACT_LANG_CODE')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD CONTACT_LANG_CODE CHAR(2) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'CONTACT_LANG_DESC')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD CONTACT_LANG_DESC VARCHAR(50) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'PCONTACT_LANG_CODE')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD PCONTACT_LANG_CODE CHAR(2) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'PCONTACT_LANG_DESC')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD PCONTACT_LANG_DESC VARCHAR(50) NULL
END
GO


---$ Alter table dbo.RCRA_HD_LQG_CONSOLIDATION
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_LQG_CONSOLIDATION') AND NAME = 'CONTACT_LANG_CODE')
BEGIN
    ALTER TABLE dbo.RCRA_HD_LQG_CONSOLIDATION
        ADD CONTACT_LANG_CODE CHAR(2) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_LQG_CONSOLIDATION') AND NAME = 'CONTACT_LANG_DESC')
BEGIN
    ALTER TABLE dbo.RCRA_HD_LQG_CONSOLIDATION
        ADD CONTACT_LANG_DESC VARCHAR(50) NULL
END
GO


---$ Alter table dbo.RCRA_HD_OWNEROP
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_OWNEROP') AND NAME = 'LANG_CODE')
BEGIN
    ALTER TABLE dbo.RCRA_HD_OWNEROP
        ADD LANG_CODE CHAR(2) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_OWNEROP') AND NAME = 'LANG_DESC')
BEGIN
    ALTER TABLE dbo.RCRA_HD_OWNEROP
        ADD LANG_DESC VARCHAR(50) NULL
END
GO


---$ Alter table dbo.RCRA_RU_REPORT_UNIV
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_RU_REPORT_UNIV') AND NAME = 'CONTACT_LANG_CODE')
BEGIN
    ALTER TABLE dbo.RCRA_RU_REPORT_UNIV
        ADD CONTACT_LANG_CODE CHAR(2) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_RU_REPORT_UNIV') AND NAME = 'CONTACT_LANG_DESC')
BEGIN
    ALTER TABLE dbo.RCRA_RU_REPORT_UNIV
        ADD CONTACT_LANG_DESC VARCHAR(50) NULL
END
GO


---$ Create table dbo.RCRA_HD_ADD_CONTACT
IF OBJECT_ID(N'dbo.RCRA_HD_ADD_CONTACT') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_HD_ADD_CONTACT
    (
        HD_ADD_CONTACT_ID VARCHAR(40) NOT NULL,
        HD_HANDLER_ID VARCHAR(40) NOT NULL,
        TRANSACTION_CODE CHAR(1) NULL,
        ADD_CONTACT_SEQ INT NOT NULL,
        CONTACT_TYPE CHAR(2) NULL,
        CONTACT_TYPE_OWNER CHAR(2) NULL,
        CONTACT_FIRST_NAME VARCHAR(38) NULL,
        CONTACT_MIDDLE_INITIAL CHAR(1) NULL,
        CONTACT_LAST_NAME VARCHAR(38) NULL,
        CONTACT_STREET_NUMBER VARCHAR(12) NULL,
        CONTACT_STREET_1 VARCHAR(50) NULL,
        CONTACT_STREET_2 VARCHAR(50) NULL,
        CONTACT_CITY VARCHAR(25) NULL,
        CONTACT_STATE CHAR(2) NULL,
        CONTACT_ZIP VARCHAR(14) NULL,
        CONTACT_COUNTRY CHAR(2) NULL,
        CONTACT_PHONE VARCHAR(15) NULL,
        CONTACT_PHONE_EXT VARCHAR(6) NULL,
        CONTACT_FAX VARCHAR(15) NULL,
        CONTACT_EMAIL VARCHAR(80) NULL,
        CONTACT_TITLE VARCHAR(45) NULL,
        CONTACT_LANG_CODE CHAR(2) NULL,
        CONTACT_LANG_DESC VARCHAR(50) NULL
    )
    END
GO


---$ Create Index/PK: IX_HD_ADD_CONTACT_HD_HANDLE_ID, Table : dbo.RCRA_HD_ADD_CONTACT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_ADD_CONTACT') AND NAME = 'IX_HD_ADD_CONTACT_HD_HANDLE_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_ADD_CONTACT_HD_HANDLE_ID
        ON dbo.RCRA_HD_ADD_CONTACT(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_HD_ADD_CONTACT, Table : dbo.RCRA_HD_ADD_CONTACT
IF OBJECT_ID(N'dbo.PK_HD_ADD_CONTACT') IS NULL
    ALTER TABLE dbo.RCRA_HD_ADD_CONTACT
        ADD CONSTRAINT PK_HD_ADD_CONTACT PRIMARY KEY CLUSTERED(HD_ADD_CONTACT_ID)
GO

---$ Create FK : FK_HD_ADD_CONTACT_HD_HANDLER
IF OBJECT_ID(N'dbo.FK_HD_ADD_CONTACT_HD_HANDLER') IS NULL
BEGIN
    ALTER TABLE dbo.RCRA_HD_ADD_CONTACT
        ADD CONSTRAINT FK_HD_ADD_CONTACT_HD_HANDLER
            FOREIGN KEY(HD_HANDLER_ID)
                REFERENCES dbo.RCRA_HD_HANDLER(HD_HANDLER_ID)
                    ON DELETE CASCADE
                    ON UPDATE NO ACTION
END
GO

