/******************************************************************************************************************************
 ** ObjectName: WQX_2.0-MySQL-DDL.sql
 **
 ** Author: Windsor Solutions, Inc.
 **
 ** Company Name: Windsor Solutions, Inc
 **
 ** Description:  Creates the WQX staging tables and views needed to support the OpenNode2 WQX plugin.
 **
 ** Notes:  Run drops statements only if schema already exists, Otherwise, just run the create statements.
 **
 **
 ** Revision History:      
 ** ----------------------------------------------------------------------------------------------------------------------------
 **  Date         Name        Description
 ** ----------------------------------------------------------------------------------------------------------------------------
 ** 01/01/2010  Windsor       Original   
 ** 11/05/2010  KJames        Added ORG_ID to the WQX_SUBMISSIONHISTORY table.   
 ** 11/05/2010  KJames        Removed the constraint between WQX_SUBMISSIONHISTORY and WQX_ORGANIZATION.  This will allow the
 **                           deletion of WQX data without purging historical submission records.                  
 ** 09/08/2011  JenGo         Converted to MySQL
 ** 10/01/2012  KJames        Modified FK constraint between ACTIVITYGROUP and ORGANIZATION
 **                           to be CASCADE DELETE.
 ** 12/18/2012  AGeery        Added three views to support Java plugin
 ******************************************************************************************************************************/
/*
 ALTER TABLE WQX_TELEPHONIC
	DROP CONSTRAINT FK_ORG_TELEPHONIC;

ALTER TABLE WQX_TAXONOMICDETAILS
	DROP CONSTRAINT FK_ACTIVITY_TAXDETAIL;

ALTER TABLE WQX_RESULTDETECTQUANTLIMIT
	DROP CONSTRAINT FK_RESULT_RESULTDETQUANTLIMIT;

ALTER TABLE WQX_RESULTATTACHEDBINARYOBJECT
	DROP CONSTRAINT FK_RESULT_RESULTATTBINOBJ;

ALTER TABLE WQX_RESULT
	DROP CONSTRAINT FK_ACTIVITY_RESULT;

ALTER TABLE WQX_PROJECTMONLOC
	DROP CONSTRAINT FK_PROJECT_PROJECTMONLOC;

ALTER TABLE WQX_PROJECTACTIVITY
	DROP CONSTRAINT FK_PROJECT_PROJECTACTIVITY;

ALTER TABLE WQX_PROJECTACTIVITY
	DROP CONSTRAINT FK_ACTIVITY_PROJECTACTIVITY;

ALTER TABLE WQX_PROJECT
	DROP CONSTRAINT FK_ORG_PROJECT;

ALTER TABLE WQX_PROJATTACHEDBINARYOBJECT
	DROP CONSTRAINT FK_PROJECT_PROJATTBINOBJ;

ALTER TABLE WQX_ORGADDRESS
	DROP CONSTRAINT FK_ORG_ORGADDRESS;

ALTER TABLE WQX_MONLOCATTACHEDBINARYOBJECT
	DROP CONSTRAINT FK_MONLOC_MONLOCATTBINOBJ;

ALTER TABLE WQX_MONITORINGLOCATION
	DROP CONSTRAINT FK_ORG_MONITORINGLOCATION;

ALTER TABLE WQX_LABSAMPLEPREP
	DROP CONSTRAINT FK_RESULT_LABSAMPLEPREP;

ALTER TABLE WQX_ELECTRONICADDRESS
	DROP CONSTRAINT FK_ORG_ELECTRONICADDRESS;

ALTER TABLE WQX_DELETES
	DROP CONSTRAINT FK_WQX_DELETES_WQX_ORG;

ALTER TABLE WQX_BIOLOGICALHABITATINDEX
	DROP CONSTRAINT FK_ORG_BIOLOGICALHABITATINDEX;

ALTER TABLE WQX_ALTMONLOC
	DROP CONSTRAINT FK_MONLOC_ALTMONLOC;

ALTER TABLE WQX_ACTIVITYMETRIC
	DROP CONSTRAINT FK_ACTIVITY_ACTIVITYMETRIC;

ALTER TABLE WQX_ACTIVITYGROUP
	DROP CONSTRAINT FK_ORG_ACTIVITYGROUP;

ALTER TABLE WQX_ACTIVITYCONDUCTINGORG
	DROP CONSTRAINT FK_ACTIVITY_ACTCONDUCTINGORG;

ALTER TABLE WQX_ACTIVITYACTIVITYGROUP
	DROP CONSTRAINT FK_ACTIVITY_ACTACTGROUP;

ALTER TABLE WQX_ACTIVITYACTIVITYGROUP
	DROP CONSTRAINT FK_ACTIVITYGROUP_ACTACTGROUP;

ALTER TABLE WQX_ACTIVITY
	DROP CONSTRAINT FK_ORG_ACTIVITY;

ALTER TABLE WQX_ACTATTACHEDBINARYOBJECT
	DROP CONSTRAINT FK_ACTIVITY_ACTATTBINOBJ;

ALTER TABLE WQX_TELEPHONIC
	DROP CONSTRAINT PK_WQX_TELEPHONIC;

ALTER TABLE WQX_TAXONOMICDETAILS
	DROP CONSTRAINT PK_WQX_TAXONOMICDETAILS;

ALTER TABLE WQX_SUBMISSIONHISTORY
	DROP CONSTRAINT PK_WQX_SUBMISSIONHISTORY;

ALTER TABLE WQX_RESULTDETECTQUANTLIMIT
	DROP CONSTRAINT PK_WQX_RESULTDETECTQUANTLIMIT;

ALTER TABLE WQX_RESULTATTACHEDBINARYOBJECT
	DROP CONSTRAINT PK_WQX_RESULTATTBINARYOBJECT;

ALTER TABLE WQX_RESULT
	DROP CONSTRAINT PK_WQX_RESULT;

ALTER TABLE WQX_PROJECTMONLOC
	DROP CONSTRAINT PK_WQX_PROJECTMONLOC;

ALTER TABLE WQX_PROJECTACTIVITY
	DROP CONSTRAINT PK_WQX_PROJECTACTIVITY;

ALTER TABLE WQX_PROJECT
	DROP CONSTRAINT PK_WQX_PROJECT;

ALTER TABLE WQX_PROJATTACHEDBINARYOBJECT
	DROP CONSTRAINT PK_WQX_PROJATTBINARYOBJECT;

ALTER TABLE WQX_ORGANIZATION
	DROP CONSTRAINT PK_WQX_ORGANIZATION;

ALTER TABLE WQX_ORGADDRESS
	DROP CONSTRAINT PK_WQX_ORGADDRESS;

ALTER TABLE WQX_MONLOCATTACHEDBINARYOBJECT
	DROP CONSTRAINT PK_WQX_MONLOCATTBINARYOBJECT;

ALTER TABLE WQX_MONITORINGLOCATION
	DROP CONSTRAINT PK_WQX_MONITORINGLOCATION;

ALTER TABLE WQX_LABSAMPLEPREP
	DROP CONSTRAINT PK_WQX_LABSAMPLEPREP;

ALTER TABLE WQX_ELECTRONICADDRESS
	DROP CONSTRAINT PK_WQX_ELECTRONICADDRESS;

ALTER TABLE WQX_DELETES
	DROP CONSTRAINT PK_WQX_DELETES;

ALTER TABLE WQX_BIOLOGICALHABITATINDEX
	DROP CONSTRAINT PK_WQX_BIOLOGICALHABITATINDEX;

ALTER TABLE WQX_ALTMONLOC
	DROP CONSTRAINT PK_WQX_ALTMONLOC;

ALTER TABLE WQX_ACTIVITYMETRIC
	DROP CONSTRAINT PK_WQX_ACTIVITYMETRIC;

ALTER TABLE WQX_ACTIVITYGROUP
	DROP CONSTRAINT PK_WQX_ACTIVITYGROUP;

ALTER TABLE WQX_ACTIVITYCONDUCTINGORG
	DROP CONSTRAINT PK_WQX_ACTIVITYCONDUCTINGORG;

ALTER TABLE WQX_ACTIVITYACTIVITYGROUP
	DROP CONSTRAINT PK_WQX_ACTIVITYACTIVITYGROUP;

ALTER TABLE WQX_ACTIVITY
	DROP CONSTRAINT PK_WQX_ACTIVITY;

ALTER TABLE WQX_ACTATTACHEDBINARYOBJECT
	DROP CONSTRAINT PK_WQX_ACTATTBINARYOBJECT;

DROP VIEW WQX_V_ACTIVITYGROUPID_HIB;	
DROP VIEW WQX_V_ATTACHEDBINARYOBJECT_HIB;	
DROP VIEW WQX_V_PROJECTACTIVITYID_HIB;	
	
DROP TABLE WQX_TELEPHONIC;
DROP TABLE WQX_TAXONOMICDETAILS;
DROP TABLE WQX_SUBMISSIONHISTORY;
DROP TABLE WQX_RESULTDETECTQUANTLIMIT;
DROP TABLE WQX_RESULTATTACHEDBINARYOBJECT;
DROP TABLE WQX_RESULT;
DROP TABLE WQX_PROJECTMONLOC;
DROP TABLE WQX_PROJECTACTIVITY;
DROP TABLE WQX_PROJECT;
DROP TABLE WQX_PROJATTACHEDBINARYOBJECT;
DROP TABLE WQX_ORGANIZATION;
DROP TABLE WQX_ORGADDRESS;
DROP TABLE WQX_MONLOCATTACHEDBINARYOBJECT;
DROP TABLE WQX_MONITORINGLOCATION;
DROP TABLE WQX_LABSAMPLEPREP;
DROP TABLE WQX_ELECTRONICADDRESS;
DROP TABLE WQX_DELETES;
DROP TABLE WQX_BIOLOGICALHABITATINDEX;
DROP TABLE WQX_ALTMONLOC;
DROP TABLE WQX_ACTIVITYMETRIC;
DROP TABLE WQX_ACTIVITYGROUP;
DROP TABLE WQX_ACTIVITYCONDUCTINGORG;
DROP TABLE WQX_ACTIVITYACTIVITYGROUP;
DROP TABLE WQX_ACTIVITY;
DROP TABLE WQX_ACTATTACHEDBINARYOBJECT;
*/ 


SET storage_engine=InnoDB;
SET CHARACTER SET utf8;
USE ga_wqx;

 CREATE TABLE WQX_ACTATTACHEDBINARYOBJECT ( 
	RECORDID                	VARCHAR(50) NOT NULL,
	PARENTID                	VARCHAR(50) NOT NULL,
	BINARYOBJECTFILE        	VARCHAR(255) NOT NULL,
	BINARYOBJECTFILETYPECODE	VARCHAR(6) NOT NULL,
	BINARYOBJECTCONTENT     	BLOB NULL 
	)
;

CREATE TABLE WQX_ACTIVITY ( 
	RECORDID                      	VARCHAR(50) NOT NULL,
	PARENTID                      	VARCHAR(50) NOT NULL,
	ACTIVITYID                    	VARCHAR(35) NOT NULL,
	ACTIVITYTYPECODE              	VARCHAR(70) NOT NULL,
	ACTIVITYMEDIA                 	VARCHAR(20) NOT NULL,
	ACTIVITYMEDIASUBDIVISION      	VARCHAR(45) NULL,
	ACTIVITYSTARTDATE             	DATETIME NOT NULL,
	STARTTIME                     	VARCHAR(20) NULL,
	STARTTIMEZONE                 	VARCHAR(4) NULL,
	ACTIVITYENDDATE               	DATETIME NULL,
	ENDTIME                       	VARCHAR(20) NULL,
	ENDTIMEZONE                   	VARCHAR(4) NULL,
	RELATIVEDEPTH                 	VARCHAR(15) NULL,
	DEPTHHEIGHTMEASURE            	VARCHAR(12) NULL,
	DEPTHHEIGHTMEASUREUNIT        	VARCHAR(12) NULL,
	TOPDEPTHHEIGHTMEASURE         	VARCHAR(12) NULL,
	TOPDEPTHHEIGHTMEASUREUNIT     	VARCHAR(12) NULL,
	BOTTOMDEPTHHEIGHTMEASURE      	VARCHAR(12) NULL,
	BOTTOMDEPTHHEIGHTMEASUREUNIT  	VARCHAR(12) NULL,
	DEPTHALTITUDEREFPOINT         	VARCHAR(125) NULL,
	MONLOCID                      	VARCHAR(35) NULL,
	ACTIVITYCOMMENT               	VARCHAR(4000) NULL,
	LATITUDEMEASURE               	VARCHAR(30) NULL,
	LONGITUDEMEASURE              	VARCHAR(30) NULL,
	SOURCEMAPSCALE                	VARCHAR(12) NULL,
	HORIZACCURACYMEASURE          	VARCHAR(12) NULL,
	HORIZACCURACYMEASUREUNIT      	VARCHAR(12) NULL,
	HORIZCOLLMETHOD               	VARCHAR(150) NULL,
	HORIZCOORDREFSYSDATUM         	VARCHAR(6) NULL,
	BIOACTIVITYASSEMBLAGESAMPD    	VARCHAR(50) NULL,
	BIOHABCOLLDURATIONMEASURE     	VARCHAR(12) NULL,
	BIOHABCOLLDURATIONMEASUREUNIT 	VARCHAR(12) NULL,
	BIOHABSAMPCOMP                	VARCHAR(15) NULL,
	BIOHABSAMPCOMPPLACEINSERIES   	VARCHAR(12) NULL,
	BIOHABREACHLENGTHMEASURE      	VARCHAR(12) NULL,
	BIOHABREACHLENGTHMEASUREUNIT  	VARCHAR(12) NULL,
	BIOHABREACHWIDTHMEASURE       	VARCHAR(12) NULL,
	BIOHABREACHWIDTHMEASUREUNIT   	VARCHAR(12) NULL,
	BIOHABPASSCOUNT               	VARCHAR(12) NULL,
	BIOHABNETTYPE                 	VARCHAR(30) NULL,
	BIOHABNETSURFACEAREAMEASURE   	VARCHAR(12) NULL,
	BIOHABNETSURFACEMEASUREUNIT   	VARCHAR(12) NULL,
	BIOHABNETMESHSIZEMEASURE      	VARCHAR(12) NULL,
	BIOHABNETMESHMEASUREUNIT      	VARCHAR(12) NULL,
	BIOHABNETBOATSPEEDMEASURE     	VARCHAR(12) NULL,
	BIOHABNETBOATSPEEDMEASUREUNIT 	VARCHAR(12) NULL,
	BIOHABNETCURRSPEEDMEASURE     	VARCHAR(12) NULL,
	BIOHABNETCURRSPEEDMEASUREUNIT 	VARCHAR(12) NULL,
	BIOACTIVITYTOXICITYTESTTYPE   	VARCHAR(7) NULL,
	SAMPCOLLMETHODID              	VARCHAR(20) NULL,
	SAMPCOLLMETHODIDCONTEXT       	VARCHAR(120) NULL,
	SAMPCOLLMETHOD                	VARCHAR(120) NULL,
	SAMPCOLLMETHODQUALIFIER       	VARCHAR(25) NULL,
	SAMPCOLLMETHODDESC            	VARCHAR(500) NULL,
	SAMPCOLLEQUIPMENT             	VARCHAR(40) NULL,
	SAMPCOLLEQUIPMENTCOMMENT      	VARCHAR(4000) NULL,
	SAMPPREPID                    	VARCHAR(20) NULL,
	SAMPPREPIDCONTEXT             	VARCHAR(120) NULL,
	SAMPPREP                      	VARCHAR(120) NULL,
	SAMPPREPQUALIFIERTYPE         	VARCHAR(25) NULL,
	SAMPPREPDESC                  	VARCHAR(500) NULL,
	SAMPPREPCONTTYPE              	VARCHAR(35) NULL,
	SAMPPREPCONTCOLOR             	VARCHAR(15) NULL,
	SAMPPREPCONTCHEMPRESERVUSED   	VARCHAR(250) NULL,
	SAMPPREPCONTTHERMALPRESERVUSED	VARCHAR(25) NULL,
	SAMPPREPCONTSAMPTRANSSTORDESC 	VARCHAR(250) NULL,
	RESULTCOUNT                   	VARCHAR(255) NULL,
	WQXUPDATEDATE                 	DATETIME NOT NULL,
	TMPPROJECTID			VARCHAR(50) NULL
	)
;

CREATE TABLE WQX_ACTIVITYACTIVITYGROUP ( 
	RECORDID             	VARCHAR(50) NOT NULL,
	ACTIVITYPARENTID     	VARCHAR(50) NOT NULL,
	ACTIVITYGROUPPARENTID	VARCHAR(50) NOT NULL 
	)
;

CREATE TABLE WQX_ACTIVITYCONDUCTINGORG ( 
	RECORDID             	VARCHAR(50) NOT NULL,
	PARENTID             	VARCHAR(50) NOT NULL,
	ACTIVITYID           	VARCHAR(35) NOT NULL,
	ACTIVITYCONDUCTINGORG	VARCHAR(120) NOT NULL 
	)
;

CREATE TABLE WQX_ACTIVITYGROUP ( 
	RECORDID             	VARCHAR(50) NOT NULL,
	PARENTID             	VARCHAR(50) NOT NULL,
	ACTIVITYGROUPID      	VARCHAR(35) NOT NULL,
	ACTIVITYGROUPNAME    	VARCHAR(50) NOT NULL,
	ACTIVITYGROUPTYPECODE	VARCHAR(50) NOT NULL,
	WQXUPDATEDATE        	DATETIME NOT NULL 
	)
;

CREATE TABLE WQX_ACTIVITYMETRIC ( 
	RECORDID                 	VARCHAR(50) NOT NULL,
	PARENTID                 	VARCHAR(50) NOT NULL,
	METRICTYPEID             	VARCHAR(35) NOT NULL,
	METRICTYPEIDCONTEXT      	VARCHAR(50) NOT NULL,
	METRICTYPENAME           	VARCHAR(50) NULL,
	CITATIONRESOURCETITLE    	VARCHAR(120) NULL,
	CITATIONRESOURCECREATOR  	VARCHAR(120) NULL,
	CITATIONRESOURCESUBJECT  	VARCHAR(500) NULL,
	CITATIONRESOURCEPUBLISHER	VARCHAR(60) NULL,
	CITATIONRESOURCEDATE     	DATETIME NULL,
	CITATIONRESOURCEID       	VARCHAR(255) NULL,
	METRICTYPESCALE          	VARCHAR(50) NULL,
	METRICTYPEFORMULADESC    	VARCHAR(50) NULL,
	METRICVALUEMEASURE       	VARCHAR(12) NULL,
	METRICVALUEMEASUREUNIT   	VARCHAR(12) NULL,
	METRICSCORE              	VARCHAR(10) NOT NULL,
	METRICCOMMENT            	VARCHAR(4000) NULL,
	METRICINDEXID            	VARCHAR(35) NULL 
	)
;

CREATE TABLE WQX_ALTMONLOC ( 
	RECORDID       	VARCHAR(50) NOT NULL,
	PARENTID       	VARCHAR(50) NOT NULL,
	MONLOCID       	VARCHAR(35) NOT NULL,
	MONLOCIDCONTEXT	VARCHAR(120) NOT NULL 
	)
;

CREATE TABLE WQX_BIOLOGICALHABITATINDEX ( 
	RECORDID           	VARCHAR(50) NOT NULL,
	PARENTID           	VARCHAR(50) NOT NULL,
	INDEXID            	VARCHAR(35) NOT NULL,
	INDEXTYPEID        	VARCHAR(35) NOT NULL,
	INDEXTYPEIDCONTEXT 	VARCHAR(50) NOT NULL,
	INDEXTYPENAME      	VARCHAR(50) NOT NULL,
	RESOURCETITLE      	VARCHAR(120) NULL,
	RESOURCECREATOR    	VARCHAR(120) NULL,
	RESOURCESUBJECT    	VARCHAR(500) NULL,
	RESOURCEPUBLISHER  	VARCHAR(60) NULL,
	RESOURCEDATE       	VARCHAR(10) NULL,
	RESOURCEID         	VARCHAR(255) NULL,
	INDEXTYPESCALE     	VARCHAR(50) NULL,
	INDEXSCORE         	VARCHAR(10) NOT NULL,
	INDEXQUALIFIERCODE 	VARCHAR(5) NULL,
	INDEXCOMMENT       	VARCHAR(4000) NULL,
	INDEXCALCULATEDDATE	VARCHAR(10) NULL,
	MONLOCID           	VARCHAR(35) NOT NULL,
	WQXUPDATEDATE      	DATETIME NOT NULL 
	)
;

CREATE TABLE WQX_DELETES ( 
	RECORDID     	VARCHAR(50) NOT NULL,
	PARENTID     	VARCHAR(50) NOT NULL,
	COMPONENT    	VARCHAR(50) NOT NULL,
	IDENTIFIER   	VARCHAR(50) NOT NULL,
	WQXUPDATEDATE	DATETIME NOT NULL 
	)
;

CREATE TABLE WQX_ELECTRONICADDRESS ( 
	RECORDID             	VARCHAR(50) NOT NULL,
	PARENTID             	VARCHAR(50) NOT NULL,
	ELECTRONICADDRESS    	VARCHAR(120) NOT NULL,
	ELECTRONICADDRESSTYPE	VARCHAR(8) NULL 
	)
;

CREATE TABLE WQX_LABSAMPLEPREP ( 
	RECORDID               	VARCHAR(50) NOT NULL,
	PARENTID               	VARCHAR(50) NOT NULL,
	METHODID               	VARCHAR(20) NOT NULL,
	METHODIDCONTEXT        	VARCHAR(120) NOT NULL,
	METHODNAME             	VARCHAR(120) NOT NULL,
	METHODQUALIFIERTYPE    	VARCHAR(25) NULL,
	METHODDESC             	VARCHAR(500) NULL,
	PREPSTARTDATE          	DATETIME NULL,
	PREPSTARTTIME          	VARCHAR(20) NULL,
	PREPSTARTTIMEZONECODE  	VARCHAR(4) NULL,
	PREPENDDATE            	DATETIME NULL,
	PREPENDTIME            	VARCHAR(20) NULL,
	PREPENDTIMEZONECODE    	VARCHAR(4) NULL,
	SUBSTANCEDILUTIONFACTOR	VARCHAR(10) NULL 
	)
;

CREATE TABLE WQX_MONITORINGLOCATION ( 
	RECORDID                	VARCHAR(50) NOT NULL,
	PARENTID                	VARCHAR(50) NOT NULL,
	MONITORINGLOCATIONID    	VARCHAR(35) NOT NULL,
	MONLOCNAME              	VARCHAR(255) NOT NULL,
	MONLOCTYPE              	VARCHAR(45) NOT NULL,
	MONLOCDESC              	VARCHAR(1999) NULL,
	HUCEIGHTDIGITCODE       	VARCHAR(8) NULL,
	HUCTWELVEDIGITCODE      	VARCHAR(12) NULL,
	TRIBALLANDIND           	CHAR(1) NULL,
	TRIBALLANDNAME          	VARCHAR(200) NULL,
	LATITUDEMEASURE         	VARCHAR(30) NOT NULL,
	LONGITUDEMEASURE        	VARCHAR(30) NOT NULL,
	SOURCEMAPSCALE          	INT NULL,
	HORIZACCURACYMEASURE    	VARCHAR(12) NULL,
	HORIZACCURACYMEASUREUNIT	VARCHAR(12) NULL,
	HORIZCOLLMETHOD         	VARCHAR(150) NOT NULL,
	HORIZCOORDREFSYSDATUM   	VARCHAR(6) NOT NULL,
	VERTICALMEASURE         	VARCHAR(12) NULL,
	VERTICALMEASUREUNIT     	VARCHAR(12) NULL,
	VERTICALCOLLMETHOD      	VARCHAR(50) NULL,
	VERTICALCOORDREFSYSDATUM	VARCHAR(10) NULL,
	COUNTRYCODE             	VARCHAR(2) NULL,
	STATECODE               	VARCHAR(2) NULL,
	COUNTYCODE              	VARCHAR(3) NULL,
	WELLTYPE                	VARCHAR(255) NULL,
	AQUIFERNAME             	VARCHAR(120) NULL,
	FORMATIONTYPE           	VARCHAR(50) NULL,
	WELLHOLEDEPTHMEASURE    	VARCHAR(12) NULL,
	WELLHOLEDEPTHMEASUREUNIT	VARCHAR(12) NULL,
	WQXUPDATEDATE           	DATETIME NOT NULL 
	)
;

CREATE TABLE WQX_MONLOCATTACHEDBINARYOBJECT ( 
	RECORDID                	VARCHAR(50) NOT NULL,
	PARENTID                	VARCHAR(50) NOT NULL,
	BINARYOBJECTFILE        	VARCHAR(255) NOT NULL,
	BINARYOBJECTFILETYPECODE	VARCHAR(6) NOT NULL,
	BINARYOBJECTCONTENT     	BLOB NULL 
	)
;

CREATE TABLE WQX_ORGADDRESS ( 
	RECORDID           	VARCHAR(50) NOT NULL,
	PARENTID           	VARCHAR(50) NOT NULL,
	ADDRESSTYPE        	VARCHAR(8) NULL,
	ADDRESS            	VARCHAR(50) NOT NULL,
	SUPPLEMENTALADDRESS	VARCHAR(120) NULL,
	LOCALITY           	VARCHAR(30) NULL,
	STATECODE          	VARCHAR(2) NULL,
	POSTALCODE         	VARCHAR(10) NULL,
	COUNTRYCODE        	VARCHAR(2) NULL,
	COUNTYCODE         	VARCHAR(3) NULL 
	)
;

CREATE TABLE WQX_ORGANIZATION ( 
	RECORDID     	VARCHAR(50) NOT NULL,
	ORGID        	VARCHAR(30) NOT NULL,
	ORGFORMALNAME	VARCHAR(120) NOT NULL,
	ORGDESC      	VARCHAR(500) NULL,
	TRIBALCODE   	VARCHAR(3) NULL 
	)
;

CREATE TABLE WQX_PROJATTACHEDBINARYOBJECT ( 
	RECORDID                	VARCHAR(50) NOT NULL,
	PARENTID                	VARCHAR(50) NOT NULL,
	BINARYOBJECTFILE        	VARCHAR(255) NOT NULL,
	BINARYOBJECTFILETYPECODE	VARCHAR(6) NOT NULL,
	BINARYOBJECTCONTENT     	BLOB NULL 
	)
;

CREATE TABLE WQX_PROJECT ( 
	RECORDID              	VARCHAR(50) NOT NULL,
	PARENTID              	VARCHAR(50) NOT NULL,
	PROJECTID             	VARCHAR(35) NOT NULL,
	PROJECTNAME           	VARCHAR(120) NOT NULL,
	PROJECTDESC           	VARCHAR(1999) NULL,
	SAMPLINGDESIGNTYPECODE	VARCHAR(20) NULL,
	QAPPAPPROVEDIND       	CHAR(1) NULL,
	QAPPAPPROVALAGENCYNAME	VARCHAR(50) NULL,
	WQXUPDATEDATE         	DATETIME NOT NULL 
	)
;

CREATE TABLE WQX_PROJECTACTIVITY ( 
	RECORDID        	VARCHAR(50) NOT NULL,
	PROJECTPARENTID 	VARCHAR(50) NOT NULL,
	ACTIVITYPARENTID	VARCHAR(50) NOT NULL 
	)
;

CREATE TABLE WQX_PROJECTMONLOC ( 
	RECORDID                  	VARCHAR(50) NOT NULL,
	PARENTID                  	VARCHAR(50) NOT NULL,
	MONLOCID                  	VARCHAR(35) NOT NULL,
	LOCWEIGHTINGFACMEASURE    	VARCHAR(12) NOT NULL,
	LOCWEIGHTINGFACMEASUREUNIT	VARCHAR(12) NOT NULL,
	STATISTICALSTRATUM        	VARCHAR(15) NULL,
	LOCATIONCATERY            	VARCHAR(50) NULL,
	LOCATIONSTATUS            	VARCHAR(15) NULL,
	REFLOCATIONTYPECODE       	VARCHAR(20) NULL,
	REFLOCATIONSTARTDATE      	DATETIME NULL,
	REFLOCATIONENDDATE        	DATETIME NULL,
	RESOURCETITLE             	VARCHAR(120) NULL,
	RESOURCECREATOR           	VARCHAR(120) NULL,
	RESOURCESUBJECT           	VARCHAR(500) NULL,
	RESOURCEPUBLISHER         	VARCHAR(60) NULL,
	RESOURCEDATE              	DATETIME NULL,
	RESOURCEID                	VARCHAR(255) NULL,
	PROJMONLOCCOMMENT         	VARCHAR(4000) NULL 
	)
;

CREATE TABLE WQX_RESULT ( 
	RECORDID                      	VARCHAR(50) NOT NULL,
	PARENTID                      	VARCHAR(50) NOT NULL,
	DATALOGGERLINENAME            	VARCHAR(15) NULL,
	RESULTDETECTIONCONDITION      	VARCHAR(35) NULL,
	CHARACTERISTICNAME            	VARCHAR(120) NULL,
	METHODSPECIATIONNAME          	VARCHAR(20) NULL,
	RESULTSAMPFRACTION            	VARCHAR(25) NULL,
	RESULTMEASURE                 	VARCHAR(60) NULL,
	RESULTMEASUREUNIT             	VARCHAR(12) NULL,
	RESULTMEASUREQUALIFIERCODE    	VARCHAR(5) NULL,
	STATUSID                      	VARCHAR(12) NULL,
	STATISTICALBASECODE           	VARCHAR(25) NULL,
	VALUETYPE                     	VARCHAR(20) NULL,
	WEIGHTBASIS                   	VARCHAR(15) NULL,
	TIMEBASIS                     	VARCHAR(12) NULL,
	TEMPERATUREBASIS              	VARCHAR(12) NULL,
	PARTICLESIZEBASIS             	VARCHAR(15) NULL,
	PRECISIONVALUE                	VARCHAR(60) NULL,
	BIASVALUE                     	VARCHAR(60) NULL,
	CONFIDENCEINTERVALVALUE       	VARCHAR(15) NULL,
	UPPERCONFIDENCELIMITVALUE     	VARCHAR(15) NULL,
	LOWERCONFIDENCELIMITVALUE     	VARCHAR(15) NULL,
	RESULTCOMMENT                 	VARCHAR(4000) NULL,
	DEPTHHEIGHTMEASURE            	VARCHAR(12) NULL,
	DEPTHHEIGHTMEASUREUNIT        	VARCHAR(12) NULL,
	DEPTHALTITUDEREFPOINT         	VARCHAR(125) NULL,
	RESULTSAMPPOINT               	VARCHAR(12) NULL,
	BIORESULTINTENT               	VARCHAR(35) NULL,
	BIORESULTINDIVIDUALID         	VARCHAR(4) NULL,
	BIORESULTSUBJECTTAXONOMIC     	VARCHAR(120) NULL,
	BIORESULTUNIDENTIFIEDSPECIESID	VARCHAR(120) NULL,
	BIORESULTSAMPTISSUEANATOMY    	VARCHAR(30) NULL,
	GRPSUMMCOUNTWEIGHTMEASURE     	VARCHAR(12) NULL,
	GRPSUMMCOUNTWEIGHTMEASUREUNIT 	VARCHAR(12) NULL,
	TAXDETAILSCELLFORM            	VARCHAR(11) NULL,
	TAXDETAILSCELLSHAPE           	VARCHAR(18) NULL,
	TAXDETAILSHABITNAME           	VARCHAR(50) NULL,
	TAXDETAILSVOLTINISM           	VARCHAR(25) NULL,
	TAXDETAILSPOLLTOLERANCE       	VARCHAR(4) NULL,
	TAXDETAILSPOLLTOLERANCESCALE  	VARCHAR(50) NULL,
	TAXDETAILSTROPHICLEVEL        	VARCHAR(4) NULL,
	TAXDETAILSFUNCFEEDINGGROUP    	VARCHAR(125) NULL,
	CITATIONRESOURCETITLE         	VARCHAR(120) NULL,
	CITATIONRESOURCECREATOR       	VARCHAR(120) NULL,
	CITATIONRESOURCESUBJECT       	VARCHAR(500) NULL,
	CITATIONRESOURCEPUBLISHER     	VARCHAR(60) NULL,
	CITATIONRESOURCEDATE          	DATETIME NULL,
	CITATIONRESOURCEID            	VARCHAR(255) NULL,
	FREQCLASSDESCCODE             	VARCHAR(50) NULL,
	FREQCLASSDESCUNITCODE         	VARCHAR(12) NULL,
	FREQCLASSLOWERBOUNDVALUE      	VARCHAR(8) NULL,
	FREQCLASSUPPERBOUNDVALUE      	VARCHAR(8) NULL,
	ANALYTICALMETHODID            	VARCHAR(20) NULL,
	ANALYTICALMETHODIDCONTEXT     	VARCHAR(120) NULL,
	ANALYTICALMETHODNAME          	VARCHAR(120) NULL,
	ANALYTICALMETHODQUALIFIERTYPE 	VARCHAR(25) NULL,
	ANALYTICALMETHODDESC          	VARCHAR(500) NULL,
	LABNAME                       	VARCHAR(60) NULL,
	LABANALYSISSTARTDATE          	DATETIME NULL,
	LABANALYSISSTARTTIME          	VARCHAR(20) NULL,
	LABANALYSISSTARTTIMEZONECODE  	VARCHAR(4) NULL,
	LABANALYSISENDDATE            	DATETIME NULL,
	LABANALYSISENDTIME            	VARCHAR(20) NULL,
	LABANALYSISENDTIMEZONECODE    	VARCHAR(4) NULL,
	RESULTLABCOMMENTCODE          	VARCHAR(3) NULL,
	LABACCIND                     	CHAR(1) NULL,
	LABACCAUTHORITYNAME           	VARCHAR(20) NULL,
	LABTAXACCIND                  	CHAR(1) NULL,
	LABTAXACCAUTHORITYNAME        	VARCHAR(20) NULL,
	TMPACTIVITYID			VARCHAR(35) NULL
	)
;

CREATE TABLE WQX_RESULTATTACHEDBINARYOBJECT ( 
	RECORDID                	VARCHAR(50) NOT NULL,
	PARENTID                	VARCHAR(50) NOT NULL,
	BINARYOBJECTFILE        	VARCHAR(255) NOT NULL,
	BINARYOBJECTFILETYPECODE	VARCHAR(6) NOT NULL,
	BINARYOBJECTCONTENT     	BLOB NULL 
	)
;

CREATE TABLE WQX_RESULTDETECTQUANTLIMIT ( 
	RECORDID                    	VARCHAR(50) NOT NULL,
	PARENTID                    	VARCHAR(50) NOT NULL,
	DETECTQUANTLIMITTYPE        	VARCHAR(35) NOT NULL,
	DETECTQUANTLIMITMEASURE     	VARCHAR(12) NULL,
	DETECTQUANTLIMITMEASUNITCODE	VARCHAR(12) NULL 
	)
;

CREATE TABLE WQX_SUBMISSIONHISTORY ( 
	RECORDID           	VARCHAR(50) NOT NULL,
	PARENTID           	VARCHAR(50) NOT NULL,
	SCHEDULERUNDATE    	DATETIME NOT NULL,
	WQXUPDATEDATE      	DATETIME NOT NULL,
	SUBMISSIONTYPE     	VARCHAR(13) NOT NULL,
	LOCALTRANSACTIONID 	VARCHAR(50) NOT NULL,
	CDXPROCESSINGSTATUS	VARCHAR(50) NOT NULL,
 	ORGID               	VARCHAR(30) NOT NULL
 
	)
;

CREATE TABLE WQX_TELEPHONIC ( 
	RECORDID           	VARCHAR(50) NOT NULL,
	PARENTID           	VARCHAR(50) NOT NULL,
	TELEPHONENUMBER    	VARCHAR(15) NOT NULL,
	TELEPHONENUMBERTYPE	VARCHAR(6) NULL,
	TELEPHONEEXT       	VARCHAR(6) NULL 
	)
;

CREATE VIEW WQX_V_ACTIVITYGROUPID_HIB AS
SELECT WQX_ACTIVITYACTIVITYGROUP.ACTIVITYGROUPPARENTID
     , WQX_ACTIVITY.ACTIVITYID 
  FROM WQX_ACTIVITYACTIVITYGROUP 
  JOIN WQX_ACTIVITY 
    ON WQX_ACTIVITYACTIVITYGROUP.ACTIVITYPARENTID = WQX_ACTIVITY.RECORDID
;

CREATE VIEW WQX_V_ATTACHEDBINARYOBJECT_HIB AS
SELECT RECORDID
     , PARENTID
     , BINARYOBJECTFILE
     , BINARYOBJECTFILETYPECODE
     , BINARYOBJECTCONTENT
  FROM WQX_ACTATTACHEDBINARYOBJECT
UNION ALL
SELECT RECORDID
     , PARENTID
     , BINARYOBJECTFILE
     , BINARYOBJECTFILETYPECODE
     , BINARYOBJECTCONTENT
  FROM WQX_MONLOCATTACHEDBINARYOBJECT
UNION ALL
SELECT RECORDID
     , PARENTID
     , BINARYOBJECTFILE
     , BINARYOBJECTFILETYPECODE
     , BINARYOBJECTCONTENT
FROM WQX_PROJATTACHEDBINARYOBJECT
UNION ALL
SELECT RECORDID
     , PARENTID
     , BINARYOBJECTFILE
     , BINARYOBJECTFILETYPECODE
     , BINARYOBJECTCONTENT
FROM WQX_RESULTATTACHEDBINARYOBJECT
;

CREATE VIEW WQX_V_PROJECTACTIVITYID_HIB AS
SELECT WQX_PROJECTACTIVITY.ACTIVITYPARENTID
     , WQX_PROJECT.PROJECTID 
  FROM WQX_PROJECTACTIVITY 
  JOIN WQX_ACTIVITY 
    ON WQX_PROJECTACTIVITY.ACTIVITYPARENTID = WQX_ACTIVITY.RECORDID
  JOIN WQX_PROJECT 
    ON WQX_PROJECTACTIVITY.PROJECTPARENTID = WQX_PROJECT.RECORDID
;

CREATE UNIQUE INDEX PK_WQX_ACTATTBINARYOBJECT
	ON WQX_ACTATTACHEDBINARYOBJECT(RECORDID)
;

CREATE UNIQUE INDEX PK_WQX_ACTIVITY
	ON WQX_ACTIVITY(RECORDID)
;

CREATE INDEX FK_ORG_ACTIVITY
	ON WQX_ACTIVITY(PARENTID)
;

CREATE INDEX FK_ACTIVITY_ACTACTGROUP
	ON WQX_ACTIVITYACTIVITYGROUP(ACTIVITYPARENTID)
;

CREATE INDEX FK_ACTIVITYGROUP_ACTACTGROUP
	ON WQX_ACTIVITYACTIVITYGROUP(ACTIVITYGROUPPARENTID)
;

CREATE UNIQUE INDEX PK_WQX_ACTIVITYACTIVITYGROUP
	ON WQX_ACTIVITYACTIVITYGROUP(RECORDID)
;

CREATE UNIQUE INDEX PK_WQX_ACTIVITYCONDUCTINGORG
	ON WQX_ACTIVITYCONDUCTINGORG(RECORDID)
;


CREATE INDEX FK_ACTIVITY_ACTATTBINOBJ
	ON WQX_ACTATTACHEDBINARYOBJECT(PARENTID)
;

CREATE INDEX FK_ACTIVITY_ACTCONDUCTINGORG
	ON WQX_ACTIVITYCONDUCTINGORG(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_ACTIVITYGROUP
	ON WQX_ACTIVITYGROUP(RECORDID)
;

CREATE INDEX FK_ORG_ACTIVITYGROUP
	ON WQX_ACTIVITYGROUP(PARENTID)
;

CREATE INDEX FK_ACTIVITY_ACTIVITYMETRIC
	ON WQX_ACTIVITYMETRIC(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_ACTIVITYMETRIC
	ON WQX_ACTIVITYMETRIC(RECORDID)
;

CREATE UNIQUE INDEX PK_WQX_ALTMONLOC
	ON WQX_ALTMONLOC(RECORDID)
;

CREATE INDEX FK_MONLOC_ALTMONLOC
	ON WQX_ALTMONLOC(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_BIOLOGICALHABITATINDEX
	ON WQX_BIOLOGICALHABITATINDEX(RECORDID)
;

CREATE INDEX FK_ORG_BIOLOGICALHABITATINDEX
	ON WQX_BIOLOGICALHABITATINDEX(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_DELETES
	ON WQX_DELETES(RECORDID)
;

CREATE UNIQUE INDEX PK_WQX_ELECTRONICADDRESS
	ON WQX_ELECTRONICADDRESS(RECORDID)
;

CREATE INDEX FK_ORG_ELECTRONICADDRESS
	ON WQX_ELECTRONICADDRESS(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_LABSAMPLEPREP
	ON WQX_LABSAMPLEPREP(RECORDID)
;

CREATE INDEX FK_RESULT_LABSAMPLEPREP
	ON WQX_LABSAMPLEPREP(PARENTID)
;

CREATE INDEX FK_ORG_MONITORINGLOCATION
	ON WQX_MONITORINGLOCATION(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_MONITORINGLOCATION
	ON WQX_MONITORINGLOCATION(RECORDID)
;

CREATE UNIQUE INDEX PK_WQX_MONLOCATTBINARYOBJECT
	ON WQX_MONLOCATTACHEDBINARYOBJECT(RECORDID)
;

CREATE INDEX FK_MONLOC_MONLOCATTBINOBJ
	ON WQX_MONLOCATTACHEDBINARYOBJECT(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_ORGADDRESS
	ON WQX_ORGADDRESS(RECORDID)
;

CREATE INDEX FK_ORG_ORGADDRESS
	ON WQX_ORGADDRESS(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_ORGANIZATION
	ON WQX_ORGANIZATION(RECORDID)
;

CREATE UNIQUE INDEX PK_WQX_PROJATTBINARYOBJECT
	ON WQX_PROJATTACHEDBINARYOBJECT(RECORDID)
;

CREATE INDEX FK_PROJECT_PROJATTBINOBJ
	ON WQX_PROJATTACHEDBINARYOBJECT(PARENTID)
;

CREATE INDEX FK_ORG_PROJECT
	ON WQX_PROJECT(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_PROJECT
	ON WQX_PROJECT(RECORDID)
;

CREATE INDEX FK_PROJECT_PROJECTACTIVITY
	ON WQX_PROJECTACTIVITY(PROJECTPARENTID)
;

CREATE UNIQUE INDEX PK_WQX_PROJECTACTIVITY
	ON WQX_PROJECTACTIVITY(RECORDID)
;

CREATE INDEX FK_ACTIVITY_PROJECTACTIVITY
	ON WQX_PROJECTACTIVITY(ACTIVITYPARENTID)
;

CREATE INDEX FK_PROJECT_PROJECTMONLOC
	ON WQX_PROJECTMONLOC(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_PROJECTMONLOC
	ON WQX_PROJECTMONLOC(RECORDID)
;

CREATE UNIQUE INDEX PK_WQX_RESULT
	ON WQX_RESULT(RECORDID)
;

CREATE INDEX FK_ACTIVITY_RESULT
	ON WQX_RESULT(PARENTID)
;

CREATE INDEX FK_RESULT_RESULTATTBINOBJ
	ON WQX_RESULTATTACHEDBINARYOBJECT(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_RESULTATTBINARYOBJECT
	ON WQX_RESULTATTACHEDBINARYOBJECT(RECORDID)
;

CREATE UNIQUE INDEX PK_WQX_RESULTDETECTQUANTLIMIT
	ON WQX_RESULTDETECTQUANTLIMIT(RECORDID)
;

CREATE INDEX FK_RESULT_RESULTDETQUANTLIMIT
	ON WQX_RESULTDETECTQUANTLIMIT(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_SUBMISSIONHISTORY
	ON WQX_SUBMISSIONHISTORY(RECORDID)
;

CREATE INDEX FK_WQX_SUBMISSIONHIST_WQX_ORG
	ON WQX_SUBMISSIONHISTORY(PARENTID)
;

CREATE UNIQUE INDEX PK_WQX_TELEPHONIC
	ON WQX_TELEPHONIC(RECORDID)
;

CREATE INDEX FK_ORG_TELEPHONIC
	ON WQX_TELEPHONIC(PARENTID)
;

ALTER TABLE WQX_ACTATTACHEDBINARYOBJECT
	ADD ( CONSTRAINT PK_WQX_ACTATTBINARYOBJECT
	PRIMARY KEY (RECORDID) )
;

ALTER TABLE WQX_ACTIVITY
	ADD ( CONSTRAINT PK_WQX_ACTIVITY
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_ACTIVITYACTIVITYGROUP
	ADD ( CONSTRAINT PK_WQX_ACTIVITYACTIVITYGROUP
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_ACTIVITYCONDUCTINGORG
	ADD ( CONSTRAINT PK_WQX_ACTIVITYCONDUCTINGORG
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_ACTIVITYGROUP
	ADD ( CONSTRAINT PK_WQX_ACTIVITYGROUP
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_ACTIVITYMETRIC
	ADD ( CONSTRAINT PK_WQX_ACTIVITYMETRIC
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_ALTMONLOC
	ADD ( CONSTRAINT PK_WQX_ALTMONLOC
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_BIOLOGICALHABITATINDEX
	ADD ( CONSTRAINT PK_WQX_BIOLOGICALHABITATINDEX
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_DELETES
	ADD ( CONSTRAINT PK_WQX_DELETES
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_ELECTRONICADDRESS
	ADD ( CONSTRAINT PK_WQX_ELECTRONICADDRESS
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_LABSAMPLEPREP
	ADD ( CONSTRAINT PK_WQX_LABSAMPLEPREP
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_MONITORINGLOCATION
	ADD ( CONSTRAINT PK_WQX_MONITORINGLOCATION
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_MONLOCATTACHEDBINARYOBJECT
	ADD ( CONSTRAINT PK_WQX_MONLOCATTBINARYOBJECT
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_ORGADDRESS
	ADD ( CONSTRAINT PK_WQX_ORGADDRESS
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_ORGANIZATION
	ADD ( CONSTRAINT PK_WQX_ORGANIZATION
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_PROJATTACHEDBINARYOBJECT
	ADD ( CONSTRAINT PK_WQX_PROJATTBINARYOBJECT
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_PROJECT
	ADD ( CONSTRAINT PK_WQX_PROJECT
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_PROJECTACTIVITY
	ADD ( CONSTRAINT PK_WQX_PROJECTACTIVITY
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_PROJECTMONLOC
	ADD ( CONSTRAINT PK_WQX_PROJECTMONLOC
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_RESULT
	ADD ( CONSTRAINT PK_WQX_RESULT
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_RESULTATTACHEDBINARYOBJECT
	ADD ( CONSTRAINT PK_WQX_RESULTATTBINARYOBJECT
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_RESULTDETECTQUANTLIMIT
	ADD ( CONSTRAINT PK_WQX_RESULTDETECTQUANTLIMIT
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_SUBMISSIONHISTORY
	ADD ( CONSTRAINT PK_WQX_SUBMISSIONHISTORY
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_TELEPHONIC
	ADD ( CONSTRAINT PK_WQX_TELEPHONIC
	PRIMARY KEY (RECORDID)
	 )
;

ALTER TABLE WQX_ACTATTACHEDBINARYOBJECT
	ADD ( CONSTRAINT FK_ACTIVITY_ACTATTBINOBJ
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ACTIVITY(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_ACTIVITY
	ADD ( CONSTRAINT FK_ORG_ACTIVITY
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ORGANIZATION(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_ACTIVITYACTIVITYGROUP
	ADD ( CONSTRAINT FK_ACTIVITY_ACTACTGROUP
	FOREIGN KEY(ACTIVITYPARENTID)
	REFERENCES WQX_ACTIVITY(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_ACTIVITYACTIVITYGROUP
	ADD ( CONSTRAINT FK_ACTIVITYGROUP_ACTACTGROUP
	FOREIGN KEY(ACTIVITYGROUPPARENTID)
	REFERENCES WQX_ACTIVITYGROUP(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_ACTIVITYCONDUCTINGORG
	ADD ( CONSTRAINT FK_ACTIVITY_ACTCONDUCTINGORG
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ACTIVITY(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_ACTIVITYGROUP
	ADD ( CONSTRAINT FK_ORG_ACTIVITYGROUP
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ORGANIZATION(RECORDID)
	ON DELETE CASCADE )
;

ALTER TABLE WQX_ACTIVITYMETRIC
	ADD ( CONSTRAINT FK_ACTIVITY_ACTIVITYMETRIC
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ACTIVITY(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_ALTMONLOC
	ADD ( CONSTRAINT FK_MONLOC_ALTMONLOC
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_MONITORINGLOCATION(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_BIOLOGICALHABITATINDEX
	ADD ( CONSTRAINT FK_ORG_BIOLOGICALHABITATINDEX
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ORGANIZATION(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_DELETES
	ADD ( CONSTRAINT FK_WQX_DELETES_WQX_ORG
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ORGANIZATION(RECORDID)
	ON DELETE NO ACTION  )
;

ALTER TABLE WQX_ELECTRONICADDRESS
	ADD ( CONSTRAINT FK_ORG_ELECTRONICADDRESS
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ORGANIZATION(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_LABSAMPLEPREP
	ADD ( CONSTRAINT FK_RESULT_LABSAMPLEPREP
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_RESULT(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_MONITORINGLOCATION
	ADD ( CONSTRAINT FK_ORG_MONITORINGLOCATION
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ORGANIZATION(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_MONLOCATTACHEDBINARYOBJECT
	ADD ( CONSTRAINT FK_MONLOC_MONLOCATTBINOBJ
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_MONITORINGLOCATION(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_ORGADDRESS
	ADD ( CONSTRAINT FK_ORG_ORGADDRESS
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ORGANIZATION(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_PROJATTACHEDBINARYOBJECT
	ADD ( CONSTRAINT FK_PROJECT_PROJATTBINOBJ
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_PROJECT(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_PROJECT
	ADD ( CONSTRAINT FK_ORG_PROJECT
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ORGANIZATION(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_PROJECTACTIVITY
	ADD ( CONSTRAINT FK_PROJECT_PROJECTACTIVITY
	FOREIGN KEY(PROJECTPARENTID)
	REFERENCES WQX_PROJECT(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_PROJECTACTIVITY
	ADD ( CONSTRAINT FK_ACTIVITY_PROJECTACTIVITY
	FOREIGN KEY(ACTIVITYPARENTID)
	REFERENCES WQX_ACTIVITY(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_PROJECTMONLOC
	ADD ( CONSTRAINT FK_PROJECT_PROJECTMONLOC
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_PROJECT(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_RESULT
	ADD ( CONSTRAINT FK_ACTIVITY_RESULT
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ACTIVITY(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_RESULTATTACHEDBINARYOBJECT
	ADD ( CONSTRAINT FK_RESULT_RESULTATTBINOBJ
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_RESULT(RECORDID)
	ON DELETE CASCADE  )
;

ALTER TABLE WQX_RESULTDETECTQUANTLIMIT
	ADD ( CONSTRAINT FK_RESULT_RESULTDETQUANTLIMIT
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_RESULT(RECORDID)
	ON DELETE CASCADE  )
;

-- ALTER TABLE WQX_SUBMISSIONHISTORY
-- ADD ( CONSTRAINT FK_WQX_SUBMISSIONHIST_WQX_ORG
-- FOREIGN KEY(PARENTID)
-- REFERENCES WQX_ORGANIZATION(RECORDID)
-- ON DELETE CASCADE  )
-- ;

ALTER TABLE WQX_TELEPHONIC
	ADD ( CONSTRAINT FK_ORG_TELEPHONIC
	FOREIGN KEY(PARENTID)
	REFERENCES WQX_ORGANIZATION(RECORDID)
	ON DELETE CASCADE  )
;

