INSERT INTO WQX_ORGANIZATION (RECORDID,ORGID,ORGFORMALNAME,ORGDESC,TRIBALCODE) VALUES ('32559EDA-8FEF-45FD-B126-C921CCEF796B','XYZ_Watershed','State of XYZ Department of Environmental Quality', 'Org Desc', 'ABC')
/

