-- =============================================  
--  
-- ATTAINS v1.0 OpenNode2 Plugin Staging table creation script
--  
-- MODIFICATION HISTORY    
-- Author      Date       Comments  
-- ---------   --------   -----------------------------------------------------  
-- Windsor     20170814   Created  
-- Windsor     20170814   Cloned SQL Server and modified to support Oracle.
-- 
-- =============================================   

/*

ALTER TABLE "ATT_WTR_TYPE"
    DROP CONSTRAINT "FK_WTR_TYPE_ASSESSMNT_UNIT";

ALTER TABLE "ATT_USE_ATTAINMENT"
    DROP CONSTRAINT "FK_USE_ATTAINMENT_ASSESSMNT";

ALTER TABLE "ATT_TMDLNPDES_DETAIL"
    DROP CONSTRAINT "FK_TMDLNPDES_DETAIL_NPDS_DETIL";

ALTER TABLE "ATT_ST_WIDE_WTR_TYPE"
    DROP CONSTRAINT "FK_ST_WIDE_WTR_TYPE_ST_WID_ASS";

ALTER TABLE "ATT_ST_WIDE_USE_ATTAINMENT"
    DROP CONSTRAINT "FK_ST_WIDE_USE_ATTN_ST_WID_ASS";

ALTER TABLE "ATT_ST_WIDE_SRC"
    DROP CONSTRAINT "FK_ST_WIDE_SRC_ST_WIDE_ACTN";

ALTER TABLE "ATT_ST_WIDE_PROBABLE_SRC"
    DROP CONSTRAINT "FK_ST_WIDE_PRBB_SRC_ST_WID_ASS";

ALTER TABLE "ATT_ST_WIDE_CAUSE"
    DROP CONSTRAINT "FK_ST_WIDE_CUSE_ST_WIDE_ASSSSM";

ALTER TABLE "ATT_ST_WIDE_CAUSE"
    DROP CONSTRAINT "FK_ST_WIDE_CAUSE_ST_WIDE_ACTN";

ALTER TABLE "ATT_ST_WIDE_ASSESSMNT"
    DROP CONSTRAINT "FK_ST_WIDE_ASSESSMNT_REP_CYCLE";

ALTER TABLE "ATT_ST_WIDE_ACTN"
    DROP CONSTRAINT "FK_ST_WIDE_ACTN_ACTN";

ALTER TABLE "ATT_ST_INTEGRATED_REP_CATG"
    DROP CONSTRAINT "FK_ST_INTGR_REP_CATG_USE_ATTNM";

ALTER TABLE "ATT_ST_INTEGRATED_REP_CATG"
    DROP CONSTRAINT "FK_ST_INTGRTD_REP_CATG_ASSSSMN";

ALTER TABLE "ATT_ST_INTEGRATED_REP_CATG"
    DROP CONSTRAINT "FK_ST_INTEGRATED_REP_CATG_PARM";

ALTER TABLE "ATT_SRC"
    DROP CONSTRAINT "FK_SRC_SPECIFIC_WTR";

ALTER TABLE "ATT_SPECIFIC_WTR"
    DROP CONSTRAINT "FK_SPECIFIC_WTR_ACTN";

ALTER TABLE "ATT_SEASON"
    DROP CONSTRAINT "FK_SEASON_ASSC_USE";

ALTER TABLE "ATT_REVIEW_CMNT"
    DROP CONSTRAINT "FK_REVIW_CMNT_ST_WIDE_ASSSSMNT";

ALTER TABLE "ATT_REVIEW_CMNT"
    DROP CONSTRAINT "FK_REVIEW_CMNT_ASSESSMNT";

ALTER TABLE "ATT_REVIEW_CMNT"
    DROP CONSTRAINT "FK_REVIEW_CMNT_ACTN";

ALTER TABLE "ATT_REP_CYCLE"
    DROP CONSTRAINT "FK_REP_CYCLE_ORG";

ALTER TABLE "ATT_RELATED_TMD_LS"
    DROP CONSTRAINT "FK_RELATED_TMD_LS_ACTN";

ALTER TABLE "ATT_PROBABLE_SRC"
    DROP CONSTRAINT "FK_PROBABLE_SRC_ASSESSMNT";

ALTER TABLE "ATT_PRIOR_CAUSE"
    DROP CONSTRAINT "FK_PRIOR_CAUSE_PARAM";

ALTER TABLE "ATT_PRIO"
    DROP CONSTRAINT "FK_PRIO_ORG";

ALTER TABLE "ATT_PRIO_USE"
    DROP CONSTRAINT "FK_PRIO_USE_PRIO";

ALTER TABLE "ATT_PRIO_PARAM"
    DROP CONSTRAINT "FK_PRIO_PARAM_PRIO";

ALTER TABLE "ATT_PRIO_ASSESSMNT_UNIT"
    DROP CONSTRAINT "FK_PRIO_ASSESSMNT_UNIT_PRIO";

ALTER TABLE "ATT_PREVIOUS_ASSESSMNT_UNIT"
    DROP CONSTRAINT "FK_PRVS_ASSSSMNT_UNIT_MODFCTNS";

ALTER TABLE "ATT_PARAM"
    DROP CONSTRAINT "FK_PARAM_ASSESSMNT";

ALTER TABLE "ATT_ORG_CONTACT"
    DROP CONSTRAINT "FK_ORG_CONTACT_ORG";

ALTER TABLE "ATT_NPDES_DETAIL"
    DROP CONSTRAINT "FK_NPDES_DETAIL_ASSC_POLUT";

ALTER TABLE "ATT_MON_STATION"
    DROP CONSTRAINT "FK_MON_STATION_ASSESSMNT_UNIT";

ALTER TABLE "ATT_MODIFICATIONS"
    DROP CONSTRAINT "FK_MODIFICATIONS_ASSSSMNT_UNIT";

ALTER TABLE "ATT_LOC"
    DROP CONSTRAINT "FK_LOC_PRIO";

ALTER TABLE "ATT_LOC"
    DROP CONSTRAINT "FK_LOC_ASSESSMNT_UNIT";

ALTER TABLE "ATT_LOAD_ALLOCATION_DETAIL"
    DROP CONSTRAINT "FK_LOAD_ALLOCTN_DTIL_ASSC_PLUT";

ALTER TABLE "ATT_DOCUMENT"
    DROP CONSTRAINT "FK_DOCUMENT_REP_CYCLE";

ALTER TABLE "ATT_DOCUMENT"
    DROP CONSTRAINT "FK_DOCUMENT_ASSESSMNT_UNIT";

ALTER TABLE "ATT_DOCUMENT"
    DROP CONSTRAINT "FK_DOCUMENT_ASSESSMNT";

ALTER TABLE "ATT_DOCUMENT"
    DROP CONSTRAINT "FK_DOCUMENT_ACTN";

ALTER TABLE "ATT_DOCUMENT_TYPE"
    DROP CONSTRAINT "FK_DOCUMENT_TYPE_DOCUMENT";

ALTER TABLE "ATT_DELISTED_WTR"
    DROP CONSTRAINT "FK_DELISTED_WTR_REP_CYCLE";

ALTER TABLE "ATT_DELISTED_WTR_CAUSE"
    DROP CONSTRAINT "FK_DELISTD_WTR_CUSE_DLISTD_WTR";

ALTER TABLE "ATT_COMBINED_CYCLE"
    DROP CONSTRAINT "FK_COMBINED_CYCLE_REP_CYCLE";

ALTER TABLE "ATT_ASSESSMNT"
    DROP CONSTRAINT "FK_ASSESSMNT_REP_CYCLE";

ALTER TABLE "ATT_ASSESSMNT_UNIT"
    DROP CONSTRAINT "FK_ASSESSMNT_UNIT_ORG";

ALTER TABLE "ATT_ASSESSMNT_TYPE"
    DROP CONSTRAINT "FK_ASSSSMNT_TYPE_USE_ATTINMENT";

ALTER TABLE "ATT_ASSESSMNT_METHOD_TYPE"
    DROP CONSTRAINT "FK_ASSSSMN_MTHD_TYPE_USE_ATTNM";

ALTER TABLE "ATT_ASSC_USE"
    DROP CONSTRAINT "FK_ASSC_USE_PARAM";

ALTER TABLE "ATT_ASSC_POLUT"
    DROP CONSTRAINT "FK_ASSC_POLUT_SPECIFIC_WTR";

ALTER TABLE "ATT_ASSC_POLUT_NAME"
    DROP CONSTRAINT "FK_ASSC_PLUT_NAME_ADDRSSD_PARM";

ALTER TABLE "ATT_ASSC_CAUSE_NAME"
    DROP CONSTRAINT "FK_ASSC_CAUSE_NAME_PROBBLE_SRC";

ALTER TABLE "ATT_ASSC_ACTN"
    DROP CONSTRAINT "FK_ASSC_ACTN_PARAM";

ALTER TABLE "ATT_ADDRESSED_PARAM"
    DROP CONSTRAINT "FK_ADDRESSED_PARAM_SPCIFIC_WTR";

ALTER TABLE "ATT_ACTN"
    DROP CONSTRAINT "FK_ACTN_ORG";

ALTER TABLE "ATT_WTR_TYPE"
    DROP CONSTRAINT "PK_WTR_TYPE";

ALTER TABLE "ATT_USE_ATTAINMENT"
    DROP CONSTRAINT "PK_USE_ATTAINMENT";

ALTER TABLE "ATT_TMDLNPDES_DETAIL"
    DROP CONSTRAINT "PK_TMDLNPDES_DETAIL";

ALTER TABLE "ATT_ST_WIDE_WTR_TYPE"
    DROP CONSTRAINT "PK_ST_WIDE_WTR_TYPE";

ALTER TABLE "ATT_ST_WIDE_USE_ATTAINMENT"
    DROP CONSTRAINT "PK_ST_WIDE_USE_ATTAINMENT";

ALTER TABLE "ATT_ST_WIDE_SRC"
    DROP CONSTRAINT "PK_ST_WIDE_SRC";

ALTER TABLE "ATT_ST_WIDE_PROBABLE_SRC"
    DROP CONSTRAINT "PK_ST_WIDE_PROBABLE_SRC";

ALTER TABLE "ATT_ST_WIDE_CAUSE"
    DROP CONSTRAINT "PK_ST_WIDE_CAUSE";

ALTER TABLE "ATT_ST_WIDE_ASSESSMNT"
    DROP CONSTRAINT "PK_ST_WIDE_ASSESSMNT";

ALTER TABLE "ATT_ST_WIDE_ACTN"
    DROP CONSTRAINT "PK_ST_WIDE_ACTN";

ALTER TABLE "ATT_ST_INTEGRATED_REP_CATG"
    DROP CONSTRAINT "PK_ST_INTEGRATED_REP_CATG";

ALTER TABLE "ATT_SRC"
    DROP CONSTRAINT "PK_SRC";

ALTER TABLE "ATT_SPECIFIC_WTR"
    DROP CONSTRAINT "PK_SPECIFIC_WTR";

ALTER TABLE "ATT_SEASON"
    DROP CONSTRAINT "PK_SEASON";

ALTER TABLE "ATT_REVIEW_CMNT"
    DROP CONSTRAINT "PK_REVIEW_CMNT";

ALTER TABLE "ATT_REP_CYCLE"
    DROP CONSTRAINT "PK_REP_CYCLE";

ALTER TABLE "ATT_RELATED_TMD_LS"
    DROP CONSTRAINT "PK_RELATED_TMD_LS";

ALTER TABLE "ATT_PROBABLE_SRC"
    DROP CONSTRAINT "PK_PROBABLE_SRC";

ALTER TABLE "ATT_PRIOR_CAUSE"
    DROP CONSTRAINT "PK_PRIOR_CAUSE";

ALTER TABLE "ATT_PRIO"
    DROP CONSTRAINT "PK_PRIO";

ALTER TABLE "ATT_PRIO_USE"
    DROP CONSTRAINT "PK_PRIO_USE";

ALTER TABLE "ATT_PRIO_PARAM"
    DROP CONSTRAINT "PK_PRIO_PARAM";

ALTER TABLE "ATT_PRIO_ASSESSMNT_UNIT"
    DROP CONSTRAINT "PK_PRIO_ASSESSMNT_UNIT";

ALTER TABLE "ATT_PREVIOUS_ASSESSMNT_UNIT"
    DROP CONSTRAINT "PK_PREVIOUS_ASSESSMNT_UNIT";

ALTER TABLE "ATT_PARAM"
    DROP CONSTRAINT "PK_PARAM";

ALTER TABLE "ATT_ORG"
    DROP CONSTRAINT "PK_ORG";

ALTER TABLE "ATT_ORG_CONTACT"
    DROP CONSTRAINT "PK_ORG_CONTACT";

ALTER TABLE "ATT_NPDES_DETAIL"
    DROP CONSTRAINT "PK_NPDES_DETAIL";

ALTER TABLE "ATT_MON_STATION"
    DROP CONSTRAINT "PK_MON_STATION";

ALTER TABLE "ATT_MODIFICATIONS"
    DROP CONSTRAINT "PK_MODIFICATIONS";

ALTER TABLE "ATT_LOC"
    DROP CONSTRAINT "PK_LOC";

ALTER TABLE "ATT_LOAD_ALLOCATION_DETAIL"
    DROP CONSTRAINT "PK_LOAD_ALLOCATION_DETAIL";

ALTER TABLE "ATT_DOCUMENT"
    DROP CONSTRAINT "PK_DOCUMENT";

ALTER TABLE "ATT_DOCUMENT_TYPE"
    DROP CONSTRAINT "PK_DOCUMENT_TYPE";

ALTER TABLE "ATT_DELISTED_WTR"
    DROP CONSTRAINT "PK_DELISTED_WTR";

ALTER TABLE "ATT_DELISTED_WTR_CAUSE"
    DROP CONSTRAINT "PK_DELISTED_WTR_CAUSE";

ALTER TABLE "ATT_COMBINED_CYCLE"
    DROP CONSTRAINT "PK_COMBINED_CYCLE";

ALTER TABLE "ATT_ASSESSMNT"
    DROP CONSTRAINT "PK_ASSESSMNT";

ALTER TABLE "ATT_ASSESSMNT_UNIT"
    DROP CONSTRAINT "PK_ASSESSMNT_UNIT";

ALTER TABLE "ATT_ASSESSMNT_TYPE"
    DROP CONSTRAINT "PK_ASSESSMNT_TYPE";

ALTER TABLE "ATT_ASSESSMNT_METHOD_TYPE"
    DROP CONSTRAINT "PK_ASSESSMNT_METHOD_TYPE";

ALTER TABLE "ATT_ASSC_USE"
    DROP CONSTRAINT "PK_ASSC_USE";

ALTER TABLE "ATT_ASSC_POLUT"
    DROP CONSTRAINT "PK_ASSC_POLUT";

ALTER TABLE "ATT_ASSC_POLUT_NAME"
    DROP CONSTRAINT "PK_ASSC_POLUT_NAME";

ALTER TABLE "ATT_ASSC_CAUSE_NAME"
    DROP CONSTRAINT "PK_ASSC_CAUSE_NAME";

ALTER TABLE "ATT_ASSC_ACTN"
    DROP CONSTRAINT "PK_ASSC_ACTN";

ALTER TABLE "ATT_ADDRESSED_PARAM"
    DROP CONSTRAINT "PK_ADDRESSED_PARAM";

ALTER TABLE "ATT_ACTN"
    DROP CONSTRAINT "PK_ACTN";

DROP INDEX "IX_WTR_TYPE_ATT_ASSSSM_UNIT_ID";

DROP INDEX "IX_USE_ATTNMNT_ATT_ASSSSMNT_ID";

DROP INDEX "IX_TMDLN_DTIL_ATT_NPDS_DTIL_ID";

DROP INDEX "IX_ST_WID_WT_TY_AT_ST_WI_AS_ID";

DROP INDEX "IX_ST_WID_US_AT_AT_ST_WI_AS_ID";

DROP INDEX "IX_ST_WID_SRC_ATT_ST_WID_AC_ID";

DROP INDEX "IX_ST_WID_PR_SR_AT_ST_WI_AS_ID";

DROP INDEX "IX_ST_WID_CUS_ATT_ST_WID_AC_ID";

DROP INDEX "IX_ST_WID_CUS_ATT_ST_WID_AS_ID";

DROP INDEX "IX_ST_WIDE_ASSS_ATT_REP_CYC_ID";

DROP INDEX "IX_ST_WIDE_ACTN_ATT_ACTN_ID";

DROP INDEX "IX_ST_INT_REP_CAT_ATT_US_AT_ID";

DROP INDEX "IX_ST_INTG_REP_CATG_ATT_ASS_ID";

DROP INDEX "IX_ST_INTG_REP_CATG_ATT_PAR_ID";

DROP INDEX "IX_SRC_ATT_SPECIFIC_WTR_ID";

DROP INDEX "IX_SPECIFIC_WTR_ATT_ACTN_ID";

DROP INDEX "IX_SEASON_ATT_ASSC_USE_ID";

DROP INDEX "IX_REVIEW_CMNT_ATT_ACTN_ID";

DROP INDEX "IX_REVIEW_CMNT_ATT_ASSSSMNT_ID";

DROP INDEX "IX_RVIW_CMNT_ATT_ST_WID_ASS_ID";

DROP INDEX "IX_REP_CYCLE_ATT_ORG_ID";

DROP INDEX "IX_RELATED_TMD_LS_ATT_ACTN_ID";

DROP INDEX "IX_PROBBLE_SRC_ATT_ASSSSMNT_ID";

DROP INDEX "IX_PRIOR_CAUSE_ATT_PARAM_ID";

DROP INDEX "IX_PRIO_ATT_ORG_ID";

DROP INDEX "IX_PRIO_USE_ATT_PRIO_ID";

DROP INDEX "IX_PRIO_PARAM_ATT_PRIO_ID";

DROP INDEX "IX_PRIO_ASSSS_UNIT_ATT_PRIO_ID";

DROP INDEX "IX_PRVS_ASSSS_UNIT_ATT_MDFC_ID";

DROP INDEX "IX_PARAM_ATT_ASSESSMNT_ID";

DROP INDEX "IX_ORG_CONTACT_ATT_ORG_ID";

DROP INDEX "IX_NPDS_DETIL_ATT_ASSC_PLUT_ID";

DROP INDEX "IX_MON_STTN_ATT_ASSSSM_UNIT_ID";

DROP INDEX "IX_MDFCTNS_ATT_ASSSSMN_UNIT_ID";

DROP INDEX "IX_LOC_ATT_ASSESSMNT_UNIT_ID";

DROP INDEX "IX_LOC_ATT_PRIO_ID";

DROP INDEX "IX_LOAD_ALL_DTI_ATT_ASS_PLU_ID";

DROP INDEX "IX_DOCUMENT_ATT_ASSESSMNT_ID";

DROP INDEX "IX_DOCUMENT_ATT_REP_CYCLE_ID";

DROP INDEX "IX_DCUMNT_ATT_ASSSSMNT_UNIT_ID";

DROP INDEX "IX_DOCUMENT_ATT_ACTN_ID";

DROP INDEX "IX_DOCUMNT_TYPE_ATT_DOCUMNT_ID";

DROP INDEX "IX_DLISTD_WTR_ATT_REP_CYCLE_ID";

DROP INDEX "IX_DLST_WTR_CUS_ATT_DLS_WTR_ID";

DROP INDEX "IX_CMBND_CYCLE_ATT_REP_CYCL_ID";

DROP INDEX "IX_ASSESSMNT_ATT_REP_CYCLE_ID";

DROP INDEX "IX_ASSESSMNT_UNIT_ATT_ORG_ID";

DROP INDEX "IX_ASSSS_TYPE_ATT_USE_ATTNM_ID";

DROP INDEX "IX_ASSS_MTH_TYP_ATT_USE_ATT_ID";

DROP INDEX "IX_ASSC_USE_ATT_PARAM_ID";

DROP INDEX "IX_ASSC_PLUT_ATT_SPCIFC_WTR_ID";

DROP INDEX "IX_ASSC_PLU_NAM_ATT_ADD_PAR_ID";

DROP INDEX "IX_ASSC_CUS_NAM_ATT_PRB_SRC_ID";

DROP INDEX "IX_ASSC_ACTN_ATT_PARAM_ID";

DROP INDEX "IX_ADDRS_PARM_ATT_SPCFC_WTR_ID";

DROP INDEX "IX_ACTN_ATT_ORG_ID";

DROP TABLE "ATT_WTR_TYPE";

DROP TABLE "ATT_USE_ATTAINMENT";

DROP TABLE "ATT_TMDLNPDES_DETAIL";

DROP TABLE "ATT_ST_WIDE_WTR_TYPE";

DROP TABLE "ATT_ST_WIDE_USE_ATTAINMENT";

DROP TABLE "ATT_ST_WIDE_SRC";

DROP TABLE "ATT_ST_WIDE_PROBABLE_SRC";

DROP TABLE "ATT_ST_WIDE_CAUSE";

DROP TABLE "ATT_ST_WIDE_ASSESSMNT";

DROP TABLE "ATT_ST_WIDE_ACTN";

DROP TABLE "ATT_ST_INTEGRATED_REP_CATG";

DROP TABLE "ATT_SRC";

DROP TABLE "ATT_SPECIFIC_WTR";

DROP TABLE "ATT_SEASON";

DROP TABLE "ATT_REVIEW_CMNT";

DROP TABLE "ATT_REP_CYCLE";

DROP TABLE "ATT_RELATED_TMD_LS";

DROP TABLE "ATT_PROBABLE_SRC";

DROP TABLE "ATT_PRIOR_CAUSE";

DROP TABLE "ATT_PRIO";

DROP TABLE "ATT_PRIO_USE";

DROP TABLE "ATT_PRIO_PARAM";

DROP TABLE "ATT_PRIO_ASSESSMNT_UNIT";

DROP TABLE "ATT_PREVIOUS_ASSESSMNT_UNIT";

DROP TABLE "ATT_PARAM";

DROP TABLE "ATT_ORG";

DROP TABLE "ATT_ORG_CONTACT";

DROP TABLE "ATT_NPDES_DETAIL";

DROP TABLE "ATT_MON_STATION";

DROP TABLE "ATT_MODIFICATIONS";

DROP TABLE "ATT_LOC";

DROP TABLE "ATT_LOAD_ALLOCATION_DETAIL";

DROP TABLE "ATT_DOCUMENT";

DROP TABLE "ATT_DOCUMENT_TYPE";

DROP TABLE "ATT_DELISTED_WTR";

DROP TABLE "ATT_DELISTED_WTR_CAUSE";

DROP TABLE "ATT_COMBINED_CYCLE";

DROP TABLE "ATT_ASSESSMNT";

DROP TABLE "ATT_ASSESSMNT_UNIT";

DROP TABLE "ATT_ASSESSMNT_TYPE";

DROP TABLE "ATT_ASSESSMNT_METHOD_TYPE";

DROP TABLE "ATT_ASSC_USE";

DROP TABLE "ATT_ASSC_POLUT";

DROP TABLE "ATT_ASSC_POLUT_NAME";

DROP TABLE "ATT_ASSC_CAUSE_NAME";

DROP TABLE "ATT_ASSC_ACTN";

DROP TABLE "ATT_ADDRESSED_PARAM";

DROP TABLE "ATT_ACTN";

*/


CREATE TABLE "ATT_ACTN" ( 
    "ATT_ACTN_ID"           varchar2(36) NOT NULL,
    "ATT_ORG_ID"            varchar2(36) NOT NULL,
    "ACTN_IDENT"            varchar2(45) NULL,
    "ACTN_NAME"             varchar2(255) NOT NULL,
    "AGNCY_CODE"            char(1) NOT NULL,
    "ACTN_TYPE_CODE"        varchar2(50) NOT NULL,
    "ACTN_STAT_CODE"        varchar2(30) NOT NULL,
    "CMPL_DATE"             date NOT NULL,
    "ACTN_CMNT_TXT"         varchar2(4000) NULL,
    "TMDL_OTHR_IDENT"       varchar2(45) NULL,
    "TMDL_DATE"             date NULL,
    "INDIAN_COUNTRY_IND"    char(1) NULL 
    );

CREATE TABLE "ATT_ADDRESSED_PARAM" ( 
    "ATT_ADDRESSED_PARAM_ID"    varchar2(36) NOT NULL,
    "ATT_SPECIFIC_WTR_ID"       varchar2(36) NOT NULL,
    "PARAM_NAME"                varchar2(240) NULL 
    );

CREATE TABLE "ATT_ASSC_ACTN" ( 
    "ATT_ASSC_ACTN_ID"    varchar2(36) NOT NULL,
    "ATT_PARAM_ID"        varchar2(36) NOT NULL,
    "ASSC_ACTN_IDENT"     varchar2(45) NULL 
    );

CREATE TABLE "ATT_ASSC_CAUSE_NAME" ( 
    "ATT_ASSC_CAUSE_NAME_ID"    varchar2(36) NOT NULL,
    "ATT_PROBABLE_SRC_ID"       varchar2(36) NOT NULL,
    "CAUSE_NAME"                varchar2(240) NOT NULL 
    );

CREATE TABLE "ATT_ASSC_POLUT_NAME" ( 
    "ATT_ASSC_POLUT_NAME_ID"    varchar2(36) NOT NULL,
    "ATT_ADDRESSED_PARAM_ID"    varchar2(36) NOT NULL,
    "POLUT_NAME"                varchar2(240) NOT NULL 
    );

CREATE TABLE "ATT_ASSC_POLUT" ( 
    "ATT_ASSC_POLUT_ID"               varchar2(36) NOT NULL,
    "ATT_SPECIFIC_WTR_ID"             varchar2(36) NOT NULL,
    "POLUT_NAME"                      varchar2(240) NOT NULL,
    "POLUT_SRC_TYPE_CODE"             varchar2(40) NOT NULL,
    "EXPLICIT_MARGINOF_SAFETY_TXT"    varchar2(255) NULL,
    "IMPLICIT_MARGINOF_SAFETY_TXT"    varchar2(255) NULL,
    "TMDL_END_POINT_TXT"              varchar2(4000) NULL 
    );

CREATE TABLE "ATT_ASSC_USE" ( 
    "ATT_ASSC_USE_ID"          varchar2(36) NOT NULL,
    "ATT_PARAM_ID"             varchar2(36) NOT NULL,
    "ASSC_USE_NAME"            varchar2(255) NOT NULL,
    "PARAM_ATTAINMENT_CODE"    varchar2(30) NULL,
    "TREND_CODE"               varchar2(25) NULL 
    );

CREATE TABLE "ATT_ASSESSMNT_METHOD_TYPE" ( 
    "ATT_ASSESSMNT_METHOD_TYPE_ID"    varchar2(36) NOT NULL,
    "ATT_USE_ATTAINMENT_ID"           varchar2(36) NOT NULL,
    "METHOD_TYPE_CNTXT"               varchar2(30) NOT NULL,
    "METHOD_TYPE_CODE"                varchar2(20) NOT NULL,
    "METHOD_TYPE_NAME"                varchar2(150) NULL 
    );

CREATE TABLE "ATT_ASSESSMNT_TYPE" ( 
    "ATT_ASSESSMNT_TYPE_ID"        varchar2(36) NOT NULL,
    "ATT_USE_ATTAINMENT_ID"        varchar2(36) NOT NULL,
    "ASSESSMNT_TYPE_CODE"          varchar2(30) NOT NULL,
    "ASSESSMNT_CONFIDENCE_CODE"    varchar2(30) NOT NULL 
    );

CREATE TABLE "ATT_ASSESSMNT_UNIT" ( 
    "ATT_ASSESSMNT_UNIT_ID"      varchar2(36) NOT NULL,
    "ATT_ORG_ID"                 varchar2(36) NOT NULL,
    "ASSESSMNT_UNIT_IDENT"       varchar2(50) NULL,
    "ASSESSMNT_UNIT_NAME"        varchar2(255) NOT NULL,
    "LOC_DESC_TXT"               varchar2(2000) NOT NULL,
    "AGNCY_CODE"                 char(1) NOT NULL,
    "ST_CODE"                    varchar2(2) NOT NULL,
    "STAT_IND"                   char(1) NOT NULL,
    "ASSESSMNT_UNIT_CMNT_TXT"    varchar2(4000) NULL,
    "USE_CLASS_CODE"             varchar2(15) NULL,
    "USE_CLASS_NAME"             varchar2(50) NULL 
    );

CREATE TABLE "ATT_ASSESSMNT" ( 
    "ATT_ASSESSMNT_ID"           varchar2(36) NOT NULL,
    "ATT_REP_CYCLE_ID"           varchar2(36) NOT NULL,
    "ASSESSMNT_UNIT_IDENT"       varchar2(50) NULL,
    "AGNCY_CODE"                 char(1) NOT NULL,
    "CYCLE_LAST_ASSESSED_TXT"    varchar2(4) NOT NULL,
    "YEAR_LAST_MONITORED_TXT"    varchar2(4) NULL,
    "TROPHIC_STAT_CODE"          varchar2(30) NULL,
    "EPAIR_CATG"                 varchar2(5) NULL,
    "ASSESSMNT_CMNTS_TXT"        varchar2(4000) NULL,
    "RATIONALE_TXT"              varchar2(4000) NULL 
    );

CREATE TABLE "ATT_COMBINED_CYCLE" ( 
    "ATT_COMBINED_CYCLE_ID"    varchar2(36) NOT NULL,
    "ATT_REP_CYCLE_ID"         varchar2(36) NOT NULL,
    "COMBINED_CYCLE_TXT"       varchar2(4) NOT NULL 
    );

CREATE TABLE "ATT_DELISTED_WTR_CAUSE" ( 
    "ATT_DELISTED_WTR_CAUSE_ID"    varchar2(36) NOT NULL,
    "ATT_DELISTED_WTR_ID"          varchar2(36) NOT NULL,
    "CAUSE_NAME"                   varchar2(240) NOT NULL,
    "AGNCY_CODE"                   char(1) NOT NULL,
    "DELISTING_REASON_CODE"        varchar2(100) NOT NULL,
    "DELISTING_CMNT_TXT"           varchar2(4000) NULL 
    );

CREATE TABLE "ATT_DELISTED_WTR" ( 
    "ATT_DELISTED_WTR_ID"     varchar2(36) NOT NULL,
    "ATT_REP_CYCLE_ID"        varchar2(36) NOT NULL,
    "ASSESSMNT_UNIT_IDENT"    varchar2(50) NOT NULL 
    );

CREATE TABLE "ATT_DOCUMENT_TYPE" ( 
    "ATT_DOCUMENT_TYPE_ID"    varchar2(36) NOT NULL,
    "ATT_DOCUMENT_ID"         varchar2(36) NOT NULL,
    "DOCUMENT_TYPE_CODE"      varchar2(30) NOT NULL 
    );

CREATE TABLE "ATT_DOCUMENT" ( 
    "ATT_DOCUMENT_ID"          varchar2(36) NOT NULL,
    "ATT_ASSESSMNT_UNIT_ID"    varchar2(36) NULL,
    "ATT_REP_CYCLE_ID"         varchar2(36) NULL,
    "ATT_ASSESSMNT_ID"         varchar2(36) NULL,
    "ATT_ACTN_ID"              varchar2(36) NULL,
    "AGNCY_CODE"               char(1) NOT NULL,
    "DOCUMENT_FILE_TYPE"       varchar2(255) NOT NULL,
    "DOCUMENT_FILE_NAME"       varchar2(255) NULL,
    "DOCUMENT_NAME"            varchar2(255) NOT NULL,
    "DOCUMENT_DESC"            varchar2(255) NULL,
    "DOCUMENT_CMNTS"           varchar2(4000) NULL,
    "DOCUMENT_URL"             varchar2(2000) NULL 
    );

CREATE TABLE "ATT_LOAD_ALLOCATION_DETAIL" ( 
    "ATT_LOAD_ALLOCATION_DETAIL_ID"    varchar2(36) NOT NULL,
    "ATT_ASSC_POLUT_ID"                varchar2(36) NOT NULL,
    "LOAD_ALLOCATION_NUM"              number(24,3) NULL,
    "LOAD_ALLOCATION_UNTS_TXT"         varchar2(20) NULL,
    "SEASON_START_TXT"                 varchar2(5) NULL,
    "SEASON_END_TXT"                   varchar2(5) NULL 
    );

CREATE TABLE "ATT_LOC" ( 
    "ATT_LOC_ID"               varchar2(36) NOT NULL,
    "ATT_ASSESSMNT_UNIT_ID"    varchar2(36) NULL,
    "ATT_PRIO_ID"              varchar2(36) NULL,
    "LOC_TYPE_CODE"            varchar2(22) NULL,
    "LOC_TXT"                  varchar2(255) NULL 
    );

CREATE TABLE "ATT_MODIFICATIONS" ( 
    "ATT_MODIFICATIONS_ID"     varchar2(36) NOT NULL,
    "ATT_ASSESSMNT_UNIT_ID"    varchar2(36) NOT NULL,
    "MOD_TYPE_CODE"            varchar2(25) NOT NULL,
    "CHANGE_DESC_TXT"          varchar2(255) NULL 
    );

CREATE TABLE "ATT_MON_STATION" ( 
    "ATT_MON_STATION_ID"       varchar2(36) NOT NULL,
    "ATT_ASSESSMNT_UNIT_ID"    varchar2(36) NOT NULL,
    "MON_ORG_IDENT"            varchar2(30) NOT NULL,
    "MON_LOC_IDENT"            varchar2(35) NOT NULL,
    "MON_DATA_LINK_TXT"        varchar2(255) NULL 
    );

CREATE TABLE "ATT_NPDES_DETAIL" ( 
    "ATT_NPDES_DETAIL_ID"    varchar2(36) NOT NULL,
    "ATT_ASSC_POLUT_ID"      varchar2(36) NOT NULL,
    "NPDES_IDENT"            varchar2(60) NULL,
    "OTHR_IDENT"             varchar2(4000) NULL 
    );

CREATE TABLE "ATT_ORG_CONTACT" ( 
    "ATT_ORG_CONTACT_ID"           varchar2(36) NOT NULL,
    "ATT_ORG_ID"                   varchar2(36) NOT NULL,
    "CONTACT_TYPE_TXT"             varchar2(35) NOT NULL,
    "WEB_URL_TXT"                  varchar2(255) NOT NULL,
    "SUB_ORG_NAME"                 varchar2(150) NULL,
    "EMAIL_ADDR_TXT"               varchar2(240) NULL,
    "FIRST_NAME"                   varchar2(15) NULL,
    "MIDDLE_INITIAL"               char(1) NULL,
    "LAST_NAME"                    varchar2(15) NULL,
    "INDVL_TITLE_TXT"              varchar2(45) NULL,
    "TELEPH_NUM_TXT"               varchar2(15) NULL,
    "PHONE_EXT_TXT"                varchar2(6) NULL,
    "FAX_NUM_TXT"                  varchar2(15) NULL,
    "MAILING_ADDR_TXT"             varchar2(30) NULL,
    "SUPPL_ADDR_TXT"               varchar2(30) NULL,
    "MAILING_ADDR_CITY_NAME"       varchar2(25) NULL,
    "MAILING_ADDR_ST_USPS_CODE"    varchar2(2) NULL,
    "MAILING_ADDR_COUNTRY_CODE"    varchar2(2) NULL,
    "MAILING_ADDR_ZIP_CODE"        varchar2(14) NULL 
    );

CREATE TABLE "ATT_ORG" ( 
    "ATT_ORG_ID"      varchar2(36) NOT NULL,
    "ORG_IDENT"       varchar2(30) NOT NULL,
    "ORG_NAME"        varchar2(150) NULL,
    "ORG_TYPE_TXT"    varchar2(30) NULL 
    );

CREATE TABLE "ATT_PARAM" ( 
    "ATT_PARAM_ID"                    varchar2(36) NOT NULL,
    "ATT_ASSESSMNT_ID"                varchar2(36) NOT NULL,
    "PARAM_STAT_NAME"                 varchar2(30) NOT NULL,
    "PARAM_NAME"                      varchar2(240) NULL,
    "PARAM_CMNT_TXT"                  varchar2(4000) NULL,
    "POLUT_IND"                       char(1) NULL,
    "ST_QUALIFIER_TXT"                varchar2(15) NULL,
    "AGNCY_CODE"                      char(1) NULL,
    "CYCLE_FIRST_LISTED_TXT"          varchar2(4) NULL,
    "CYCLE_SCHD_FOR_TMDL_TXT"         varchar2(4) NULL,
    "CWA_303D_PRIO_RANKING_TXT"       varchar2(25) NULL,
    "CONSENT_DECREE_CYCLE_TXT"        varchar2(4) NULL,
    "ALTERNATE_LISTING_IDENT"         varchar2(50) NULL,
    "CYCLE_EXPECTED_TO_ATTAIN_TXT"    varchar2(4) NULL 
    );

CREATE TABLE "ATT_PREVIOUS_ASSESSMNT_UNIT" ( 
    "ATT_PREVIOUS_ASSESSMNT_UNIT_ID"    varchar2(36) NOT NULL,
    "ATT_MODIFICATIONS_ID"              varchar2(36) NOT NULL,
    "ASSESSMNT_UNIT_IDENT"              varchar2(50) NULL 
    );

CREATE TABLE "ATT_PRIO_ASSESSMNT_UNIT" ( 
    "ATT_PRIO_ASSESSMNT_UNIT_ID"    varchar2(36) NOT NULL,
    "ATT_PRIO_ID"                   varchar2(36) NOT NULL,
    "ASSESSMNT_UNIT_IDENT"          varchar2(50) NULL 
    );

CREATE TABLE "ATT_PRIO_PARAM" ( 
    "ATT_PRIO_PARAM_ID"    varchar2(36) NOT NULL,
    "ATT_PRIO_ID"          varchar2(36) NOT NULL,
    "PARAM_NAME"           varchar2(240) NULL 
    );

CREATE TABLE "ATT_PRIO_USE" ( 
    "ATT_PRIO_USE_ID"    varchar2(36) NOT NULL,
    "ATT_PRIO_ID"        varchar2(36) NOT NULL,
    "USE_NAME"           varchar2(255) NULL 
    );

CREATE TABLE "ATT_PRIO" ( 
    "ATT_PRIO_ID"            varchar2(36) NOT NULL,
    "ATT_ORG_ID"             varchar2(36) NOT NULL,
    "PRIO_STAT_CODE"         varchar2(255) NULL,
    "PRIO_STAT_DATE"         date NULL,
    "PRIO_IDENT"             varchar2(50) NULL,
    "PRIO_NAME"              varchar2(240) NULL,
    "CYCLE_BASE_LINE_TXT"    varchar2(4) NULL,
    "CYCLE_GOAL_TXT"         varchar2(4) NULL,
    "PRIO_TYPE_CODE"         varchar2(25) NULL,
    "PRIO_DESC_TXT"          varchar2(2000) NULL,
    "PRIO_CMNT_TXT"          varchar2(4000) NULL 
    );

CREATE TABLE "ATT_PRIOR_CAUSE" ( 
    "ATT_PRIOR_CAUSE_ID"       varchar2(36) NOT NULL,
    "ATT_PARAM_ID"             varchar2(36) NOT NULL,
    "PRIOR_CAUSE_NAME"         varchar2(240) NOT NULL,
    "PRIOR_CAUSE_CYCLE_TXT"    varchar2(4) NOT NULL 
    );

CREATE TABLE "ATT_PROBABLE_SRC" ( 
    "ATT_PROBABLE_SRC_ID"    varchar2(36) NOT NULL,
    "ATT_ASSESSMNT_ID"       varchar2(36) NOT NULL,
    "SRC_NAME"               varchar2(240) NOT NULL,
    "SRC_CONFIRMED_IND"      char(1) NOT NULL,
    "SRC_CMNT_TXT"           varchar2(4000) NULL 
    );

CREATE TABLE "ATT_RELATED_TMD_LS" ( 
    "ATT_RELATED_TMD_LS_ID"    varchar2(36) NOT NULL,
    "ATT_ACTN_ID"              varchar2(36) NOT NULL,
    "ACTN_IDENT"               varchar2(45) NULL,
    "CHANGE_TYPE_TXT"          varchar2(255) NOT NULL 
    );

CREATE TABLE "ATT_REP_CYCLE" ( 
    "ATT_REP_CYCLE_ID"    varchar2(36) NOT NULL,
    "ATT_ORG_ID"          varchar2(36) NOT NULL,
    "REP_CYCLE_TXT"       varchar2(4) NOT NULL,
    "REP_STAT_CODE"       varchar2(38) NOT NULL 
    );

CREATE TABLE "ATT_REVIEW_CMNT" ( 
    "ATT_REVIEW_CMNT_ID"          varchar2(36) NOT NULL,
    "ATT_ASSESSMNT_ID"            varchar2(36) NULL,
    "ATT_ST_WIDE_ASSESSMNT_ID"    varchar2(36) NULL,
    "ATT_ACTN_ID"                 varchar2(36) NULL,
    "REVIEW_CMNT_TXT"             varchar2(4000) NOT NULL,
    "REVIEW_CMNT_DATE"            date NOT NULL,
    "REVIEW_CMNT_USR_NAME"        varchar2(30) NOT NULL,
    "ORG_IDENT"                   varchar2(30) NOT NULL 
    );

CREATE TABLE "ATT_SEASON" ( 
    "ATT_SEASON_ID"       varchar2(36) NOT NULL,
    "ATT_ASSC_USE_ID"     varchar2(36) NOT NULL,
    "SEASON_START_TXT"    varchar2(5) NULL,
    "SEASON_END_TXT"      varchar2(5) NULL 
    );

CREATE TABLE "ATT_SPECIFIC_WTR" ( 
    "ATT_SPECIFIC_WTR_ID"     varchar2(36) NOT NULL,
    "ATT_ACTN_ID"             varchar2(36) NOT NULL,
    "ASSESSMNT_UNIT_IDENT"    varchar2(50) NOT NULL 
    );

CREATE TABLE "ATT_SRC" ( 
    "ATT_SRC_ID"             varchar2(36) NOT NULL,
    "ATT_SPECIFIC_WTR_ID"    varchar2(36) NOT NULL,
    "SRC_NAME"               varchar2(240) NOT NULL,
    "SRC_CMNT_TXT"           varchar2(4000) NULL 
    );

CREATE TABLE "ATT_ST_INTEGRATED_REP_CATG" ( 
    "ATT_ST_INTEGRATED_REP_CATG_ID"    varchar2(36) NOT NULL,
    "ATT_ASSESSMNT_ID"                 varchar2(36) NULL,
    "ATT_USE_ATTAINMENT_ID"            varchar2(36) NULL,
    "ATT_PARAM_ID"                     varchar2(36) NULL,
    "ST_IR_CATG_CODE"                  varchar2(5) NOT NULL,
    "ST_CATG_DESC_TXT"                 varchar2(255) NULL 
    );

CREATE TABLE "ATT_ST_WIDE_ACTN" ( 
    "ATT_ST_WIDE_ACTN_ID"        varchar2(36) NOT NULL,
    "ATT_ACTN_ID"                varchar2(36) NOT NULL,
    "ST_WIDE_ASSESSMNT_IDENT"    varchar2(45) NOT NULL,
    "ST_WIDE_CYCLE_TXT"          varchar2(4) NOT NULL,
    "ST_WIDE_CMNT_TXT"           varchar2(4000) NULL 
    );

CREATE TABLE "ATT_ST_WIDE_ASSESSMNT" ( 
    "ATT_ST_WIDE_ASSESSMNT_ID"    varchar2(36) NOT NULL,
    "ATT_REP_CYCLE_ID"            varchar2(36) NOT NULL,
    "ST_WIDE_ASSESSMNT_NAME"      varchar2(255) NULL,
    "ST_WIDE_ASSESSMNT_IDENT"     varchar2(45) NOT NULL,
    "ST_WIDE_CMNT_TXT"            varchar2(4000) NULL 
    );

CREATE TABLE "ATT_ST_WIDE_CAUSE" ( 
    "ATT_ST_WIDE_CAUSE_ID"        varchar2(36) NOT NULL,
    "ATT_ST_WIDE_ASSESSMNT_ID"    varchar2(36) NULL,
    "ATT_ST_WIDE_ACTN_ID"         varchar2(36) NULL,
    "ST_WIDE_CAUSE_NAME"          varchar2(240) NOT NULL 
    );

CREATE TABLE "ATT_ST_WIDE_PROBABLE_SRC" ( 
    "ATT_ST_WIDE_PROBABLE_SRC_ID"    varchar2(36) NOT NULL,
    "ATT_ST_WIDE_ASSESSMNT_ID"       varchar2(36) NOT NULL,
    "ST_WIDE_PROBABLE_SRC_NAME"      varchar2(240) NOT NULL 
    );

CREATE TABLE "ATT_ST_WIDE_SRC" ( 
    "ATT_ST_WIDE_SRC_ID"     varchar2(36) NOT NULL,
    "ATT_ST_WIDE_ACTN_ID"    varchar2(36) NOT NULL,
    "ST_WIDE_SRC_NAME"       varchar2(240) NOT NULL 
    );

CREATE TABLE "ATT_ST_WIDE_USE_ATTAINMENT" ( 
    "ATT_ST_WIDE_USE_ATTAINMENT_ID"    varchar2(36) NOT NULL,
    "ATT_ST_WIDE_ASSESSMNT_ID"         varchar2(36) NOT NULL,
    "ST_WIDE_USE_NAME"                 varchar2(255) NOT NULL,
    "USE_ATTAINMENT_CODE"              char(1) NOT NULL,
    "THREATENED_IND"                   char(1) NULL,
    "TREND_CODE"                       varchar2(25) NULL,
    "AGNCY_CODE"                       char(1) NOT NULL 
    );

CREATE TABLE "ATT_ST_WIDE_WTR_TYPE" ( 
    "ATT_ST_WIDE_WTR_TYPE_ID"     varchar2(36) NOT NULL,
    "ATT_ST_WIDE_ASSESSMNT_ID"    varchar2(36) NOT NULL,
    "ST_WIDE_WTR_TYPE_CODE"       varchar2(40) NOT NULL 
    );

CREATE TABLE "ATT_TMDLNPDES_DETAIL" ( 
    "ATT_TMDLNPDES_DETAIL_ID"           varchar2(36) NOT NULL,
    "ATT_NPDES_DETAIL_ID"               varchar2(36) NOT NULL,
    "WASTE_LOAD_ALLOCATION_NUM"         number(24,3) NOT NULL,
    "WASTE_LOAD_ALLOCATION_UNTS_TXT"    varchar2(20) NOT NULL,
    "SEASON_START_TXT"                  varchar2(5) NULL,
    "SEASON_END_TXT"                    varchar2(5) NULL 
    );

CREATE TABLE "ATT_USE_ATTAINMENT" ( 
    "ATT_USE_ATTAINMENT_ID"    varchar2(36) NOT NULL,
    "ATT_ASSESSMNT_ID"         varchar2(36) NOT NULL,
    "USE_NAME"                 varchar2(255) NULL,
    "USE_ATTAINMENT_CODE"      char(1) NOT NULL,
    "THREATENED_IND"           char(1) NULL,
    "TREND_CODE"               varchar2(25) NULL,
    "AGNCY_CODE"               char(1) NOT NULL,
    "ST_QUALIFIER_TXT"         varchar2(15) NULL,
    "USE_CMNT_TXT"             varchar2(4000) NULL,
    "ASSESSMNT_BASIS_CODE"     varchar2(30) NULL,
    "MON_START_DATE"           date NULL,
    "MON_END_DATE"             date NULL,
    "ASSESSMNT_DATE"           date NULL,
    "ASSESSOR_NAME"            varchar2(80) NULL 
    );

CREATE TABLE "ATT_WTR_TYPE" ( 
    "ATT_WTR_TYPE_ID"                varchar2(36) NOT NULL,
    "ATT_ASSESSMNT_UNIT_ID"          varchar2(36) NOT NULL,
    "WTR_TYPE_CODE"                  varchar2(40) NOT NULL,
    "WTR_SIZE_NUM"                   number(18,4) NOT NULL,
    "UNTS_CODE"                      varchar2(15) NOT NULL,
    "SIZE_ESTIMATION_METHOD_CODE"    varchar2(45) NULL,
    "SIZE_SRC_TXT"                   varchar2(100) NULL,
    "SIZE_SRC_SCALE_TXT"             varchar2(30) NULL 
    );


CREATE INDEX "IX_ACTN_ATT_ORG_ID"
    ON "ATT_ACTN"("ATT_ORG_ID");

CREATE INDEX "IX_ADDRS_PARM_ATT_SPCFC_WTR_ID"
    ON "ATT_ADDRESSED_PARAM"("ATT_SPECIFIC_WTR_ID");

CREATE INDEX "IX_ASSC_ACTN_ATT_PARAM_ID"
    ON "ATT_ASSC_ACTN"("ATT_PARAM_ID");

CREATE INDEX "IX_ASSC_CUS_NAM_ATT_PRB_SRC_ID"
    ON "ATT_ASSC_CAUSE_NAME"("ATT_PROBABLE_SRC_ID");

CREATE INDEX "IX_ASSC_PLU_NAM_ATT_ADD_PAR_ID"
    ON "ATT_ASSC_POLUT_NAME"("ATT_ADDRESSED_PARAM_ID");

CREATE INDEX "IX_ASSC_PLUT_ATT_SPCIFC_WTR_ID"
    ON "ATT_ASSC_POLUT"("ATT_SPECIFIC_WTR_ID");

CREATE INDEX "IX_ASSC_USE_ATT_PARAM_ID"
    ON "ATT_ASSC_USE"("ATT_PARAM_ID");

CREATE INDEX "IX_ASSS_MTH_TYP_ATT_USE_ATT_ID"
    ON "ATT_ASSESSMNT_METHOD_TYPE"("ATT_USE_ATTAINMENT_ID");

CREATE INDEX "IX_ASSSS_TYPE_ATT_USE_ATTNM_ID"
    ON "ATT_ASSESSMNT_TYPE"("ATT_USE_ATTAINMENT_ID");

CREATE INDEX "IX_ASSESSMNT_UNIT_ATT_ORG_ID"
    ON "ATT_ASSESSMNT_UNIT"("ATT_ORG_ID");

CREATE INDEX "IX_ASSESSMNT_ATT_REP_CYCLE_ID"
    ON "ATT_ASSESSMNT"("ATT_REP_CYCLE_ID");

CREATE INDEX "IX_CMBND_CYCLE_ATT_REP_CYCL_ID"
    ON "ATT_COMBINED_CYCLE"("ATT_REP_CYCLE_ID");

CREATE INDEX "IX_DLST_WTR_CUS_ATT_DLS_WTR_ID"
    ON "ATT_DELISTED_WTR_CAUSE"("ATT_DELISTED_WTR_ID");

CREATE INDEX "IX_DLISTD_WTR_ATT_REP_CYCLE_ID"
    ON "ATT_DELISTED_WTR"("ATT_REP_CYCLE_ID");

CREATE INDEX "IX_DOCUMNT_TYPE_ATT_DOCUMNT_ID"
    ON "ATT_DOCUMENT_TYPE"("ATT_DOCUMENT_ID");

CREATE INDEX "IX_DOCUMENT_ATT_ASSESSMNT_ID"
    ON "ATT_DOCUMENT"("ATT_ASSESSMNT_ID");

CREATE INDEX "IX_DOCUMENT_ATT_REP_CYCLE_ID"
    ON "ATT_DOCUMENT"("ATT_REP_CYCLE_ID");

CREATE INDEX "IX_DCUMNT_ATT_ASSSSMNT_UNIT_ID"
    ON "ATT_DOCUMENT"("ATT_ASSESSMNT_UNIT_ID");

CREATE INDEX "IX_DOCUMENT_ATT_ACTN_ID"
    ON "ATT_DOCUMENT"("ATT_ACTN_ID");

CREATE INDEX "IX_LOAD_ALL_DTI_ATT_ASS_PLU_ID"
    ON "ATT_LOAD_ALLOCATION_DETAIL"("ATT_ASSC_POLUT_ID");

CREATE INDEX "IX_LOC_ATT_ASSESSMNT_UNIT_ID"
    ON "ATT_LOC"("ATT_ASSESSMNT_UNIT_ID");

CREATE INDEX "IX_LOC_ATT_PRIO_ID"
    ON "ATT_LOC"("ATT_PRIO_ID");

CREATE INDEX "IX_MDFCTNS_ATT_ASSSSMN_UNIT_ID"
    ON "ATT_MODIFICATIONS"("ATT_ASSESSMNT_UNIT_ID");

CREATE INDEX "IX_MON_STTN_ATT_ASSSSM_UNIT_ID"
    ON "ATT_MON_STATION"("ATT_ASSESSMNT_UNIT_ID");

CREATE INDEX "IX_NPDS_DETIL_ATT_ASSC_PLUT_ID"
    ON "ATT_NPDES_DETAIL"("ATT_ASSC_POLUT_ID");

CREATE INDEX "IX_ORG_CONTACT_ATT_ORG_ID"
    ON "ATT_ORG_CONTACT"("ATT_ORG_ID");

CREATE INDEX "IX_PARAM_ATT_ASSESSMNT_ID"
    ON "ATT_PARAM"("ATT_ASSESSMNT_ID");

CREATE INDEX "IX_PRVS_ASSSS_UNIT_ATT_MDFC_ID"
    ON "ATT_PREVIOUS_ASSESSMNT_UNIT"("ATT_MODIFICATIONS_ID");

CREATE INDEX "IX_PRIO_ASSSS_UNIT_ATT_PRIO_ID"
    ON "ATT_PRIO_ASSESSMNT_UNIT"("ATT_PRIO_ID");

CREATE INDEX "IX_PRIO_PARAM_ATT_PRIO_ID"
    ON "ATT_PRIO_PARAM"("ATT_PRIO_ID");

CREATE INDEX "IX_PRIO_USE_ATT_PRIO_ID"
    ON "ATT_PRIO_USE"("ATT_PRIO_ID");

CREATE INDEX "IX_PRIO_ATT_ORG_ID"
    ON "ATT_PRIO"("ATT_ORG_ID");

CREATE INDEX "IX_PRIOR_CAUSE_ATT_PARAM_ID"
    ON "ATT_PRIOR_CAUSE"("ATT_PARAM_ID");

CREATE INDEX "IX_PROBBLE_SRC_ATT_ASSSSMNT_ID"
    ON "ATT_PROBABLE_SRC"("ATT_ASSESSMNT_ID");

CREATE INDEX "IX_RELATED_TMD_LS_ATT_ACTN_ID"
    ON "ATT_RELATED_TMD_LS"("ATT_ACTN_ID");

CREATE INDEX "IX_REP_CYCLE_ATT_ORG_ID"
    ON "ATT_REP_CYCLE"("ATT_ORG_ID");

CREATE INDEX "IX_REVIEW_CMNT_ATT_ACTN_ID"
    ON "ATT_REVIEW_CMNT"("ATT_ACTN_ID");

CREATE INDEX "IX_REVIEW_CMNT_ATT_ASSSSMNT_ID"
    ON "ATT_REVIEW_CMNT"("ATT_ASSESSMNT_ID");

CREATE INDEX "IX_RVIW_CMNT_ATT_ST_WID_ASS_ID"
    ON "ATT_REVIEW_CMNT"("ATT_ST_WIDE_ASSESSMNT_ID");

CREATE INDEX "IX_SEASON_ATT_ASSC_USE_ID"
    ON "ATT_SEASON"("ATT_ASSC_USE_ID");

CREATE INDEX "IX_SPECIFIC_WTR_ATT_ACTN_ID"
    ON "ATT_SPECIFIC_WTR"("ATT_ACTN_ID");

CREATE INDEX "IX_SRC_ATT_SPECIFIC_WTR_ID"
    ON "ATT_SRC"("ATT_SPECIFIC_WTR_ID");

CREATE INDEX "IX_ST_INT_REP_CAT_ATT_US_AT_ID"
    ON "ATT_ST_INTEGRATED_REP_CATG"("ATT_USE_ATTAINMENT_ID");

CREATE INDEX "IX_ST_INTG_REP_CATG_ATT_ASS_ID"
    ON "ATT_ST_INTEGRATED_REP_CATG"("ATT_ASSESSMNT_ID");

CREATE INDEX "IX_ST_INTG_REP_CATG_ATT_PAR_ID"
    ON "ATT_ST_INTEGRATED_REP_CATG"("ATT_PARAM_ID");

CREATE INDEX "IX_ST_WIDE_ACTN_ATT_ACTN_ID"
    ON "ATT_ST_WIDE_ACTN"("ATT_ACTN_ID");

CREATE INDEX "IX_ST_WIDE_ASSS_ATT_REP_CYC_ID"
    ON "ATT_ST_WIDE_ASSESSMNT"("ATT_REP_CYCLE_ID");

CREATE INDEX "IX_ST_WID_CUS_ATT_ST_WID_AC_ID"
    ON "ATT_ST_WIDE_CAUSE"("ATT_ST_WIDE_ACTN_ID");

CREATE INDEX "IX_ST_WID_CUS_ATT_ST_WID_AS_ID"
    ON "ATT_ST_WIDE_CAUSE"("ATT_ST_WIDE_ASSESSMNT_ID");

CREATE INDEX "IX_ST_WID_PR_SR_AT_ST_WI_AS_ID"
    ON "ATT_ST_WIDE_PROBABLE_SRC"("ATT_ST_WIDE_ASSESSMNT_ID");

CREATE INDEX "IX_ST_WID_SRC_ATT_ST_WID_AC_ID"
    ON "ATT_ST_WIDE_SRC"("ATT_ST_WIDE_ACTN_ID");

CREATE INDEX "IX_ST_WID_US_AT_AT_ST_WI_AS_ID"
    ON "ATT_ST_WIDE_USE_ATTAINMENT"("ATT_ST_WIDE_ASSESSMNT_ID");

CREATE INDEX "IX_ST_WID_WT_TY_AT_ST_WI_AS_ID"
    ON "ATT_ST_WIDE_WTR_TYPE"("ATT_ST_WIDE_ASSESSMNT_ID");

CREATE INDEX "IX_TMDLN_DTIL_ATT_NPDS_DTIL_ID"
    ON "ATT_TMDLNPDES_DETAIL"("ATT_NPDES_DETAIL_ID");

CREATE INDEX "IX_USE_ATTNMNT_ATT_ASSSSMNT_ID"
    ON "ATT_USE_ATTAINMENT"("ATT_ASSESSMNT_ID");

CREATE INDEX "IX_WTR_TYPE_ATT_ASSSSM_UNIT_ID"
    ON "ATT_WTR_TYPE"("ATT_ASSESSMNT_UNIT_ID");

ALTER TABLE "ATT_ACTN"
    ADD CONSTRAINT "PK_ACTN"
    PRIMARY KEY ("ATT_ACTN_ID");

ALTER TABLE "ATT_ADDRESSED_PARAM"
    ADD CONSTRAINT "PK_ADDRESSED_PARAM"
    PRIMARY KEY ("ATT_ADDRESSED_PARAM_ID");

ALTER TABLE "ATT_ASSC_ACTN"
    ADD CONSTRAINT "PK_ASSC_ACTN"
    PRIMARY KEY ("ATT_ASSC_ACTN_ID");

ALTER TABLE "ATT_ASSC_CAUSE_NAME"
    ADD CONSTRAINT "PK_ASSC_CAUSE_NAME"
    PRIMARY KEY ("ATT_ASSC_CAUSE_NAME_ID");

ALTER TABLE "ATT_ASSC_POLUT_NAME"
    ADD CONSTRAINT "PK_ASSC_POLUT_NAME"
    PRIMARY KEY ("ATT_ASSC_POLUT_NAME_ID");

ALTER TABLE "ATT_ASSC_POLUT"
    ADD CONSTRAINT "PK_ASSC_POLUT"
    PRIMARY KEY ("ATT_ASSC_POLUT_ID");

ALTER TABLE "ATT_ASSC_USE"
    ADD CONSTRAINT "PK_ASSC_USE"
    PRIMARY KEY ("ATT_ASSC_USE_ID");

ALTER TABLE "ATT_ASSESSMNT_METHOD_TYPE"
    ADD CONSTRAINT "PK_ASSESSMNT_METHOD_TYPE"
    PRIMARY KEY ("ATT_ASSESSMNT_METHOD_TYPE_ID");

ALTER TABLE "ATT_ASSESSMNT_TYPE"
    ADD CONSTRAINT "PK_ASSESSMNT_TYPE"
    PRIMARY KEY ("ATT_ASSESSMNT_TYPE_ID");

ALTER TABLE "ATT_ASSESSMNT_UNIT"
    ADD CONSTRAINT "PK_ASSESSMNT_UNIT"
    PRIMARY KEY ("ATT_ASSESSMNT_UNIT_ID");

ALTER TABLE "ATT_ASSESSMNT"
    ADD CONSTRAINT "PK_ASSESSMNT"
    PRIMARY KEY ("ATT_ASSESSMNT_ID");

ALTER TABLE "ATT_COMBINED_CYCLE"
    ADD CONSTRAINT "PK_COMBINED_CYCLE"
    PRIMARY KEY ("ATT_COMBINED_CYCLE_ID");

ALTER TABLE "ATT_DELISTED_WTR_CAUSE"
    ADD CONSTRAINT "PK_DELISTED_WTR_CAUSE"
    PRIMARY KEY ("ATT_DELISTED_WTR_CAUSE_ID");

ALTER TABLE "ATT_DELISTED_WTR"
    ADD CONSTRAINT "PK_DELISTED_WTR"
    PRIMARY KEY ("ATT_DELISTED_WTR_ID");

ALTER TABLE "ATT_DOCUMENT_TYPE"
    ADD CONSTRAINT "PK_DOCUMENT_TYPE"
    PRIMARY KEY ("ATT_DOCUMENT_TYPE_ID");

ALTER TABLE "ATT_DOCUMENT"
    ADD CONSTRAINT "PK_DOCUMENT"
    PRIMARY KEY ("ATT_DOCUMENT_ID");

ALTER TABLE "ATT_LOAD_ALLOCATION_DETAIL"
    ADD CONSTRAINT "PK_LOAD_ALLOCATION_DETAIL"
    PRIMARY KEY ("ATT_LOAD_ALLOCATION_DETAIL_ID");

ALTER TABLE "ATT_LOC"
    ADD CONSTRAINT "PK_LOC"
    PRIMARY KEY ("ATT_LOC_ID");

ALTER TABLE "ATT_MODIFICATIONS"
    ADD CONSTRAINT "PK_MODIFICATIONS"
    PRIMARY KEY ("ATT_MODIFICATIONS_ID");

ALTER TABLE "ATT_MON_STATION"
    ADD CONSTRAINT "PK_MON_STATION"
    PRIMARY KEY ("ATT_MON_STATION_ID");

ALTER TABLE "ATT_NPDES_DETAIL"
    ADD CONSTRAINT "PK_NPDES_DETAIL"
    PRIMARY KEY ("ATT_NPDES_DETAIL_ID");

ALTER TABLE "ATT_ORG_CONTACT"
    ADD CONSTRAINT "PK_ORG_CONTACT"
    PRIMARY KEY ("ATT_ORG_CONTACT_ID");

ALTER TABLE "ATT_ORG"
    ADD CONSTRAINT "PK_ORG"
    PRIMARY KEY ("ATT_ORG_ID");

ALTER TABLE "ATT_PARAM"
    ADD CONSTRAINT "PK_PARAM"
    PRIMARY KEY ("ATT_PARAM_ID");

ALTER TABLE "ATT_PREVIOUS_ASSESSMNT_UNIT"
    ADD CONSTRAINT "PK_PREVIOUS_ASSESSMNT_UNIT"
    PRIMARY KEY ("ATT_PREVIOUS_ASSESSMNT_UNIT_ID");

ALTER TABLE "ATT_PRIO_ASSESSMNT_UNIT"
    ADD CONSTRAINT "PK_PRIO_ASSESSMNT_UNIT"
    PRIMARY KEY ("ATT_PRIO_ASSESSMNT_UNIT_ID");

ALTER TABLE "ATT_PRIO_PARAM"
    ADD CONSTRAINT "PK_PRIO_PARAM"
    PRIMARY KEY ("ATT_PRIO_PARAM_ID");

ALTER TABLE "ATT_PRIO_USE"
    ADD CONSTRAINT "PK_PRIO_USE"
    PRIMARY KEY ("ATT_PRIO_USE_ID");

ALTER TABLE "ATT_PRIO"
    ADD CONSTRAINT "PK_PRIO"
    PRIMARY KEY ("ATT_PRIO_ID");

ALTER TABLE "ATT_PRIOR_CAUSE"
    ADD CONSTRAINT "PK_PRIOR_CAUSE"
    PRIMARY KEY ("ATT_PRIOR_CAUSE_ID");

ALTER TABLE "ATT_PROBABLE_SRC"
    ADD CONSTRAINT "PK_PROBABLE_SRC"
    PRIMARY KEY ("ATT_PROBABLE_SRC_ID");

ALTER TABLE "ATT_RELATED_TMD_LS"
    ADD CONSTRAINT "PK_RELATED_TMD_LS"
    PRIMARY KEY ("ATT_RELATED_TMD_LS_ID");

ALTER TABLE "ATT_REP_CYCLE"
    ADD CONSTRAINT "PK_REP_CYCLE"
    PRIMARY KEY ("ATT_REP_CYCLE_ID");

ALTER TABLE "ATT_REVIEW_CMNT"
    ADD CONSTRAINT "PK_REVIEW_CMNT"
    PRIMARY KEY ("ATT_REVIEW_CMNT_ID");

ALTER TABLE "ATT_SEASON"
    ADD CONSTRAINT "PK_SEASON"
    PRIMARY KEY ("ATT_SEASON_ID");

ALTER TABLE "ATT_SPECIFIC_WTR"
    ADD CONSTRAINT "PK_SPECIFIC_WTR"
    PRIMARY KEY ("ATT_SPECIFIC_WTR_ID");

ALTER TABLE "ATT_SRC"
    ADD CONSTRAINT "PK_SRC"
    PRIMARY KEY ("ATT_SRC_ID");

ALTER TABLE "ATT_ST_INTEGRATED_REP_CATG"
    ADD CONSTRAINT "PK_ST_INTEGRATED_REP_CATG"
    PRIMARY KEY ("ATT_ST_INTEGRATED_REP_CATG_ID");

ALTER TABLE "ATT_ST_WIDE_ACTN"
    ADD CONSTRAINT "PK_ST_WIDE_ACTN"
    PRIMARY KEY ("ATT_ST_WIDE_ACTN_ID");

ALTER TABLE "ATT_ST_WIDE_ASSESSMNT"
    ADD CONSTRAINT "PK_ST_WIDE_ASSESSMNT"
    PRIMARY KEY ("ATT_ST_WIDE_ASSESSMNT_ID");

ALTER TABLE "ATT_ST_WIDE_CAUSE"
    ADD CONSTRAINT "PK_ST_WIDE_CAUSE"
    PRIMARY KEY ("ATT_ST_WIDE_CAUSE_ID");

ALTER TABLE "ATT_ST_WIDE_PROBABLE_SRC"
    ADD CONSTRAINT "PK_ST_WIDE_PROBABLE_SRC"
    PRIMARY KEY ("ATT_ST_WIDE_PROBABLE_SRC_ID");

ALTER TABLE "ATT_ST_WIDE_SRC"
    ADD CONSTRAINT "PK_ST_WIDE_SRC"
    PRIMARY KEY ("ATT_ST_WIDE_SRC_ID");

ALTER TABLE "ATT_ST_WIDE_USE_ATTAINMENT"
    ADD CONSTRAINT "PK_ST_WIDE_USE_ATTAINMENT"
    PRIMARY KEY ("ATT_ST_WIDE_USE_ATTAINMENT_ID");

ALTER TABLE "ATT_ST_WIDE_WTR_TYPE"
    ADD CONSTRAINT "PK_ST_WIDE_WTR_TYPE"
    PRIMARY KEY ("ATT_ST_WIDE_WTR_TYPE_ID");

ALTER TABLE "ATT_TMDLNPDES_DETAIL"
    ADD CONSTRAINT "PK_TMDLNPDES_DETAIL"
    PRIMARY KEY ("ATT_TMDLNPDES_DETAIL_ID");

ALTER TABLE "ATT_USE_ATTAINMENT"
    ADD CONSTRAINT "PK_USE_ATTAINMENT"
    PRIMARY KEY ("ATT_USE_ATTAINMENT_ID");

ALTER TABLE "ATT_WTR_TYPE"
    ADD CONSTRAINT "PK_WTR_TYPE"
    PRIMARY KEY ("ATT_WTR_TYPE_ID");

ALTER TABLE "ATT_ACTN"
    ADD CONSTRAINT "FK_ACTN_ORG"
    FOREIGN KEY("ATT_ORG_ID")
    REFERENCES "ATT_ORG"("ATT_ORG_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ADDRESSED_PARAM"
    ADD CONSTRAINT "FK_ADDRESSED_PARAM_SPCIFIC_WTR"
    FOREIGN KEY("ATT_SPECIFIC_WTR_ID")
    REFERENCES "ATT_SPECIFIC_WTR"("ATT_SPECIFIC_WTR_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ASSC_ACTN"
    ADD CONSTRAINT "FK_ASSC_ACTN_PARAM"
    FOREIGN KEY("ATT_PARAM_ID")
    REFERENCES "ATT_PARAM"("ATT_PARAM_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ASSC_CAUSE_NAME"
    ADD CONSTRAINT "FK_ASSC_CAUSE_NAME_PROBBLE_SRC"
    FOREIGN KEY("ATT_PROBABLE_SRC_ID")
    REFERENCES "ATT_PROBABLE_SRC"("ATT_PROBABLE_SRC_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ASSC_POLUT_NAME"
    ADD CONSTRAINT "FK_ASSC_PLUT_NAME_ADDRSSD_PARM"
    FOREIGN KEY("ATT_ADDRESSED_PARAM_ID")
    REFERENCES "ATT_ADDRESSED_PARAM"("ATT_ADDRESSED_PARAM_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ASSC_POLUT"
    ADD CONSTRAINT "FK_ASSC_POLUT_SPECIFIC_WTR"
    FOREIGN KEY("ATT_SPECIFIC_WTR_ID")
    REFERENCES "ATT_SPECIFIC_WTR"("ATT_SPECIFIC_WTR_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ASSC_USE"
    ADD CONSTRAINT "FK_ASSC_USE_PARAM"
    FOREIGN KEY("ATT_PARAM_ID")
    REFERENCES "ATT_PARAM"("ATT_PARAM_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ASSESSMNT_METHOD_TYPE"
    ADD CONSTRAINT "FK_ASSSSMN_MTHD_TYPE_USE_ATTNM"
    FOREIGN KEY("ATT_USE_ATTAINMENT_ID")
    REFERENCES "ATT_USE_ATTAINMENT"("ATT_USE_ATTAINMENT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ASSESSMNT_TYPE"
    ADD CONSTRAINT "FK_ASSSSMNT_TYPE_USE_ATTINMENT"
    FOREIGN KEY("ATT_USE_ATTAINMENT_ID")
    REFERENCES "ATT_USE_ATTAINMENT"("ATT_USE_ATTAINMENT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ASSESSMNT_UNIT"
    ADD CONSTRAINT "FK_ASSESSMNT_UNIT_ORG"
    FOREIGN KEY("ATT_ORG_ID")
    REFERENCES "ATT_ORG"("ATT_ORG_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ASSESSMNT"
    ADD CONSTRAINT "FK_ASSESSMNT_REP_CYCLE"
    FOREIGN KEY("ATT_REP_CYCLE_ID")
    REFERENCES "ATT_REP_CYCLE"("ATT_REP_CYCLE_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_COMBINED_CYCLE"
    ADD CONSTRAINT "FK_COMBINED_CYCLE_REP_CYCLE"
    FOREIGN KEY("ATT_REP_CYCLE_ID")
    REFERENCES "ATT_REP_CYCLE"("ATT_REP_CYCLE_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_DELISTED_WTR_CAUSE"
    ADD CONSTRAINT "FK_DELISTD_WTR_CUSE_DLISTD_WTR"
    FOREIGN KEY("ATT_DELISTED_WTR_ID")
    REFERENCES "ATT_DELISTED_WTR"("ATT_DELISTED_WTR_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_DELISTED_WTR"
    ADD CONSTRAINT "FK_DELISTED_WTR_REP_CYCLE"
    FOREIGN KEY("ATT_REP_CYCLE_ID")
    REFERENCES "ATT_REP_CYCLE"("ATT_REP_CYCLE_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_DOCUMENT_TYPE"
    ADD CONSTRAINT "FK_DOCUMENT_TYPE_DOCUMENT"
    FOREIGN KEY("ATT_DOCUMENT_ID")
    REFERENCES "ATT_DOCUMENT"("ATT_DOCUMENT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_DOCUMENT"
    ADD CONSTRAINT "FK_DOCUMENT_REP_CYCLE"
    FOREIGN KEY("ATT_REP_CYCLE_ID")
    REFERENCES "ATT_REP_CYCLE"("ATT_REP_CYCLE_ID");

ALTER TABLE "ATT_DOCUMENT"
    ADD CONSTRAINT "FK_DOCUMENT_ASSESSMNT_UNIT"
    FOREIGN KEY("ATT_ASSESSMNT_UNIT_ID")
    REFERENCES "ATT_ASSESSMNT_UNIT"("ATT_ASSESSMNT_UNIT_ID");

ALTER TABLE "ATT_DOCUMENT"
    ADD CONSTRAINT "FK_DOCUMENT_ASSESSMNT"
    FOREIGN KEY("ATT_ASSESSMNT_ID")
    REFERENCES "ATT_ASSESSMNT"("ATT_ASSESSMNT_ID");

ALTER TABLE "ATT_DOCUMENT"
    ADD CONSTRAINT "FK_DOCUMENT_ACTN"
    FOREIGN KEY("ATT_ACTN_ID")
    REFERENCES "ATT_ACTN"("ATT_ACTN_ID");

ALTER TABLE "ATT_LOAD_ALLOCATION_DETAIL"
    ADD CONSTRAINT "FK_LOAD_ALLOCTN_DTIL_ASSC_PLUT"
    FOREIGN KEY("ATT_ASSC_POLUT_ID")
    REFERENCES "ATT_ASSC_POLUT"("ATT_ASSC_POLUT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_LOC"
    ADD CONSTRAINT "FK_LOC_PRIO"
    FOREIGN KEY("ATT_PRIO_ID")
    REFERENCES "ATT_PRIO"("ATT_PRIO_ID");

ALTER TABLE "ATT_LOC"
    ADD CONSTRAINT "FK_LOC_ASSESSMNT_UNIT"
    FOREIGN KEY("ATT_ASSESSMNT_UNIT_ID")
    REFERENCES "ATT_ASSESSMNT_UNIT"("ATT_ASSESSMNT_UNIT_ID");

ALTER TABLE "ATT_MODIFICATIONS"
    ADD CONSTRAINT "FK_MODIFICATIONS_ASSSSMNT_UNIT"
    FOREIGN KEY("ATT_ASSESSMNT_UNIT_ID")
    REFERENCES "ATT_ASSESSMNT_UNIT"("ATT_ASSESSMNT_UNIT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_MON_STATION"
    ADD CONSTRAINT "FK_MON_STATION_ASSESSMNT_UNIT"
    FOREIGN KEY("ATT_ASSESSMNT_UNIT_ID")
    REFERENCES "ATT_ASSESSMNT_UNIT"("ATT_ASSESSMNT_UNIT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_NPDES_DETAIL"
    ADD CONSTRAINT "FK_NPDES_DETAIL_ASSC_POLUT"
    FOREIGN KEY("ATT_ASSC_POLUT_ID")
    REFERENCES "ATT_ASSC_POLUT"("ATT_ASSC_POLUT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ORG_CONTACT"
    ADD CONSTRAINT "FK_ORG_CONTACT_ORG"
    FOREIGN KEY("ATT_ORG_ID")
    REFERENCES "ATT_ORG"("ATT_ORG_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_PARAM"
    ADD CONSTRAINT "FK_PARAM_ASSESSMNT"
    FOREIGN KEY("ATT_ASSESSMNT_ID")
    REFERENCES "ATT_ASSESSMNT"("ATT_ASSESSMNT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_PREVIOUS_ASSESSMNT_UNIT"
    ADD CONSTRAINT "FK_PRVS_ASSSSMNT_UNIT_MODFCTNS"
    FOREIGN KEY("ATT_MODIFICATIONS_ID")
    REFERENCES "ATT_MODIFICATIONS"("ATT_MODIFICATIONS_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_PRIO_ASSESSMNT_UNIT"
    ADD CONSTRAINT "FK_PRIO_ASSESSMNT_UNIT_PRIO"
    FOREIGN KEY("ATT_PRIO_ID")
    REFERENCES "ATT_PRIO"("ATT_PRIO_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_PRIO_PARAM"
    ADD CONSTRAINT "FK_PRIO_PARAM_PRIO"
    FOREIGN KEY("ATT_PRIO_ID")
    REFERENCES "ATT_PRIO"("ATT_PRIO_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_PRIO_USE"
    ADD CONSTRAINT "FK_PRIO_USE_PRIO"
    FOREIGN KEY("ATT_PRIO_ID")
    REFERENCES "ATT_PRIO"("ATT_PRIO_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_PRIO"
    ADD CONSTRAINT "FK_PRIO_ORG"
    FOREIGN KEY("ATT_ORG_ID")
    REFERENCES "ATT_ORG"("ATT_ORG_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_PRIOR_CAUSE"
    ADD CONSTRAINT "FK_PRIOR_CAUSE_PARAM"
    FOREIGN KEY("ATT_PARAM_ID")
    REFERENCES "ATT_PARAM"("ATT_PARAM_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_PROBABLE_SRC"
    ADD CONSTRAINT "FK_PROBABLE_SRC_ASSESSMNT"
    FOREIGN KEY("ATT_ASSESSMNT_ID")
    REFERENCES "ATT_ASSESSMNT"("ATT_ASSESSMNT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_RELATED_TMD_LS"
    ADD CONSTRAINT "FK_RELATED_TMD_LS_ACTN"
    FOREIGN KEY("ATT_ACTN_ID")
    REFERENCES "ATT_ACTN"("ATT_ACTN_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_REP_CYCLE"
    ADD CONSTRAINT "FK_REP_CYCLE_ORG"
    FOREIGN KEY("ATT_ORG_ID")
    REFERENCES "ATT_ORG"("ATT_ORG_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_REVIEW_CMNT"
    ADD CONSTRAINT "FK_REVIW_CMNT_ST_WIDE_ASSSSMNT"
    FOREIGN KEY("ATT_ST_WIDE_ASSESSMNT_ID")
    REFERENCES "ATT_ST_WIDE_ASSESSMNT"("ATT_ST_WIDE_ASSESSMNT_ID");

ALTER TABLE "ATT_REVIEW_CMNT"
    ADD CONSTRAINT "FK_REVIEW_CMNT_ASSESSMNT"
    FOREIGN KEY("ATT_ASSESSMNT_ID")
    REFERENCES "ATT_ASSESSMNT"("ATT_ASSESSMNT_ID");

ALTER TABLE "ATT_REVIEW_CMNT"
    ADD CONSTRAINT "FK_REVIEW_CMNT_ACTN"
    FOREIGN KEY("ATT_ACTN_ID")
    REFERENCES "ATT_ACTN"("ATT_ACTN_ID");

ALTER TABLE "ATT_SEASON"
    ADD CONSTRAINT "FK_SEASON_ASSC_USE"
    FOREIGN KEY("ATT_ASSC_USE_ID")
    REFERENCES "ATT_ASSC_USE"("ATT_ASSC_USE_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_SPECIFIC_WTR"
    ADD CONSTRAINT "FK_SPECIFIC_WTR_ACTN"
    FOREIGN KEY("ATT_ACTN_ID")
    REFERENCES "ATT_ACTN"("ATT_ACTN_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_SRC"
    ADD CONSTRAINT "FK_SRC_SPECIFIC_WTR"
    FOREIGN KEY("ATT_SPECIFIC_WTR_ID")
    REFERENCES "ATT_SPECIFIC_WTR"("ATT_SPECIFIC_WTR_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ST_INTEGRATED_REP_CATG"
    ADD CONSTRAINT "FK_ST_INTGR_REP_CATG_USE_ATTNM"
    FOREIGN KEY("ATT_USE_ATTAINMENT_ID")
    REFERENCES "ATT_USE_ATTAINMENT"("ATT_USE_ATTAINMENT_ID");

ALTER TABLE "ATT_ST_INTEGRATED_REP_CATG"
    ADD CONSTRAINT "FK_ST_INTGRTD_REP_CATG_ASSSSMN"
    FOREIGN KEY("ATT_ASSESSMNT_ID")
    REFERENCES "ATT_ASSESSMNT"("ATT_ASSESSMNT_ID");

ALTER TABLE "ATT_ST_INTEGRATED_REP_CATG"
    ADD CONSTRAINT "FK_ST_INTEGRATED_REP_CATG_PARM"
    FOREIGN KEY("ATT_PARAM_ID")
    REFERENCES "ATT_PARAM"("ATT_PARAM_ID");

ALTER TABLE "ATT_ST_WIDE_ACTN"
    ADD CONSTRAINT "FK_ST_WIDE_ACTN_ACTN"
    FOREIGN KEY("ATT_ACTN_ID")
    REFERENCES "ATT_ACTN"("ATT_ACTN_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ST_WIDE_ASSESSMNT"
    ADD CONSTRAINT "FK_ST_WIDE_ASSESSMNT_REP_CYCLE"
    FOREIGN KEY("ATT_REP_CYCLE_ID")
    REFERENCES "ATT_REP_CYCLE"("ATT_REP_CYCLE_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ST_WIDE_CAUSE"
    ADD CONSTRAINT "FK_ST_WIDE_CUSE_ST_WIDE_ASSSSM"
    FOREIGN KEY("ATT_ST_WIDE_ASSESSMNT_ID")
    REFERENCES "ATT_ST_WIDE_ASSESSMNT"("ATT_ST_WIDE_ASSESSMNT_ID");

ALTER TABLE "ATT_ST_WIDE_CAUSE"
    ADD CONSTRAINT "FK_ST_WIDE_CAUSE_ST_WIDE_ACTN"
    FOREIGN KEY("ATT_ST_WIDE_ACTN_ID")
    REFERENCES "ATT_ST_WIDE_ACTN"("ATT_ST_WIDE_ACTN_ID");

ALTER TABLE "ATT_ST_WIDE_PROBABLE_SRC"
    ADD CONSTRAINT "FK_ST_WIDE_PRBB_SRC_ST_WID_ASS"
    FOREIGN KEY("ATT_ST_WIDE_ASSESSMNT_ID")
    REFERENCES "ATT_ST_WIDE_ASSESSMNT"("ATT_ST_WIDE_ASSESSMNT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ST_WIDE_SRC"
    ADD CONSTRAINT "FK_ST_WIDE_SRC_ST_WIDE_ACTN"
    FOREIGN KEY("ATT_ST_WIDE_ACTN_ID")
    REFERENCES "ATT_ST_WIDE_ACTN"("ATT_ST_WIDE_ACTN_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ST_WIDE_USE_ATTAINMENT"
    ADD CONSTRAINT "FK_ST_WIDE_USE_ATTN_ST_WID_ASS"
    FOREIGN KEY("ATT_ST_WIDE_ASSESSMNT_ID")
    REFERENCES "ATT_ST_WIDE_ASSESSMNT"("ATT_ST_WIDE_ASSESSMNT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_ST_WIDE_WTR_TYPE"
    ADD CONSTRAINT "FK_ST_WIDE_WTR_TYPE_ST_WID_ASS"
    FOREIGN KEY("ATT_ST_WIDE_ASSESSMNT_ID")
    REFERENCES "ATT_ST_WIDE_ASSESSMNT"("ATT_ST_WIDE_ASSESSMNT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_TMDLNPDES_DETAIL"
    ADD CONSTRAINT "FK_TMDLNPDES_DETAIL_NPDS_DETIL"
    FOREIGN KEY("ATT_NPDES_DETAIL_ID")
    REFERENCES "ATT_NPDES_DETAIL"("ATT_NPDES_DETAIL_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_USE_ATTAINMENT"
    ADD CONSTRAINT "FK_USE_ATTAINMENT_ASSESSMNT"
    FOREIGN KEY("ATT_ASSESSMNT_ID")
    REFERENCES "ATT_ASSESSMNT"("ATT_ASSESSMNT_ID")
    ON DELETE CASCADE;

ALTER TABLE "ATT_WTR_TYPE"
    ADD CONSTRAINT "FK_WTR_TYPE_ASSESSMNT_UNIT"
    FOREIGN KEY("ATT_ASSESSMNT_UNIT_ID")
    REFERENCES "ATT_ASSESSMNT_UNIT"("ATT_ASSESSMNT_UNIT_ID")
    ON DELETE CASCADE;
    
comment on column ATT_ACTN.ACTN_CMNT_TXT is 'Free text providing additional comments on the action (ActionCommentText)';
comment on column ATT_ACTN.ACTN_IDENT is 'Unique code identifying the action (ActionIdentifier)';
comment on column ATT_ACTN.ACTN_NAME is 'Name of the action (ActionName)';
comment on column ATT_ACTN.ACTN_STAT_CODE is 'Status of the Action (i.e. Final, Draft, Public Comment, etc.) (ActionStatusCode)';
comment on column ATT_ACTN.ACTN_TYPE_CODE is 'Code identifying the type of action being taken (ActionTypeCode)';
comment on column ATT_ACTN.AGNCY_CODE is 'Code identifying the agency responsible for the action (S=State, E=EPA, T=Tribal) (AgencyCode)';
comment on column ATT_ACTN.CMPL_DATE is 'Date the action is planned to be completed (CompletionDate)';
comment on column ATT_ACTN.INDIAN_COUNTRY_IND is 'Indicates if the water is either wholly or partially in Indian country. (IndianCountryIndicator)';
comment on column ATT_ACTN.TMDL_DATE is 'Date TMDL was established (TMDLDate)';
comment on column ATT_ACTN.TMDL_OTHR_IDENT is 'Alternative code identifying the TMDL Report (an example could be a state assigned identifier that is different from the ID in ActionIdentifier) (TMDLOtherIdentifier)';
comment on column ATT_ADDRESSED_PARAM.PARAM_NAME is 'Name of the parameter (ParameterName)';
comment on column ATT_ASSC_ACTN.ASSC_ACTN_IDENT is 'Unique code identifying the Action that corresponds to this cause. (AssociatedActionIdentifier)';
comment on column ATT_ASSC_CAUSE_NAME.CAUSE_NAME is 'Name of the cause (CauseName)';
comment on column ATT_ASSC_POLUT.EXPLICIT_MARGINOF_SAFETY_TXT is 'Explicit margin of safety for the AssociatedPollutant (ExplicitMarginofSafetyText)';
comment on column ATT_ASSC_POLUT.IMPLICIT_MARGINOF_SAFETY_TXT is 'Implicit margin of safety for the AssociatedPollutant (ImplicitMarginofSafetyText)';
comment on column ATT_ASSC_POLUT.POLUT_NAME is 'Name of the pollutant (PollutantName)';
comment on column ATT_ASSC_POLUT.POLUT_SRC_TYPE_CODE is 'Are the sources of the pollutant point source, nonpoint source or both. (PollutantSourceTypeCode)';
comment on column ATT_ASSC_POLUT.TMDL_END_POINT_TXT is 'Free text describing the TMDL End Point (TMDLEndPointText)';
comment on column ATT_ASSC_POLUT_NAME.POLUT_NAME is 'Name of the pollutant (PollutantName)';
comment on column ATT_ASSC_USE.ASSC_USE_NAME is 'Name of the designated use. (AssociatedUseName)';
comment on column ATT_ASSC_USE.PARAM_ATTAINMENT_CODE is 'Code indicating the attainment status for this parameter for this specific use. (ParameterAttainmentCode)';
comment on column ATT_ASSC_USE.TREND_CODE is 'Code representing the water quality trend for this use or parameter. (TrendCode)';
comment on column ATT_ASSESSMNT.AGNCY_CODE is 'Code identifying the agency responsible for the action (S=State, E=EPA, T=Tribal) (AgencyCode)';
comment on column ATT_ASSESSMNT.ASSESSMNT_CMNTS_TXT is 'Free text for providing additional comments on the assessment. (AssessmentCommentsText)';
comment on column ATT_ASSESSMNT.ASSESSMNT_UNIT_IDENT is 'A unique identifier assigned to the Assessment Unit by the reporting organization (AssessmentUnitIdentifier)';
comment on column ATT_ASSESSMNT.CYCLE_LAST_ASSESSED_TXT is 'Cycle this Assessment Unit was last assessed, which can include any conclusions related to this Assessment Unit and can include delisting decisions. (CycleLastAssessedText)';
comment on column ATT_ASSESSMNT.EPAIR_CATG is 'EPA Defined Reporting Category (EPAIRCategory)';
comment on column ATT_ASSESSMNT.RATIONALE_TXT is 'Rationale for the assessment conclusion. This text will be available for the public. (RationaleText)';
comment on column ATT_ASSESSMNT.TROPHIC_STAT_CODE is 'Code representing the trophic status for the Assessment Unit (TrophicStatusCode)';
comment on column ATT_ASSESSMNT.YEAR_LAST_MONITORED_TXT is 'Cycle this Assessment Unit was last monitored (YearLastMonitoredText)';
comment on column ATT_ASSESSMNT_METHOD_TYPE.METHOD_TYPE_CNTXT is 'Context for the MethodTypeName (MethodTypeContext)';
comment on column ATT_ASSESSMNT_METHOD_TYPE.METHOD_TYPE_CODE is 'Code for the Assessment Method (MethodTypeCode)';
comment on column ATT_ASSESSMNT_METHOD_TYPE.METHOD_TYPE_NAME is 'Name of the method used (MethodTypeName)';
comment on column ATT_ASSESSMNT_TYPE.ASSESSMNT_CONFIDENCE_CODE is 'Code indicating the confidence in the AssessmentType (AssessmentConfidenceCode)';
comment on column ATT_ASSESSMNT_TYPE.ASSESSMNT_TYPE_CODE is 'Code representing the type of assessment that was performed. (AssessmentTypeCode)';
comment on column ATT_ASSESSMNT_UNIT.AGNCY_CODE is 'Code identifying the agency responsible for the action (S=State, E=EPA, T=Tribal) (AgencyCode)';
comment on column ATT_ASSESSMNT_UNIT.ASSESSMNT_UNIT_CMNT_TXT is 'Text to provide a comment on a specific Assessment Unit (AssessmentUnitCommentText)';
comment on column ATT_ASSESSMNT_UNIT.ASSESSMNT_UNIT_IDENT is 'A unique identifier assigned to the Assessment Unit by the reporting organization (AssessmentUnitIdentifier)';
comment on column ATT_ASSESSMNT_UNIT.ASSESSMNT_UNIT_NAME is 'Name of Assessment Unit (i.e. GNIS Name) (AssessmentUnitName)';
comment on column ATT_ASSESSMNT_UNIT.LOC_DESC_TXT is 'Text description of the Assessment Unit location (describes the extent of the Assessment Unit) (LocationDescriptionText)';
comment on column ATT_ASSESSMNT_UNIT.ST_CODE is 'Geographic state within which the Assessment Unit is contained (StateCode)';
comment on column ATT_ASSESSMNT_UNIT.STAT_IND is 'Indicator of whether the Assessment Unit is currently active, or if the identifier has been retired and is being kept for historical tracking purposes and is part of an Assessment Unit History of another Assessment Unit. (StatusIndicator)';
comment on column ATT_ASSESSMNT_UNIT.USE_CLASS_CODE is 'Unique code identifying the use class for this water (UseClassCode)';
comment on column ATT_ASSESSMNT_UNIT.USE_CLASS_NAME is 'name of the use class for this water (UseClassName)';
comment on column ATT_COMBINED_CYCLE.COMBINED_CYCLE_TXT is 'Additional reporting cycle for the Assessments (CombinedCycleText)';
comment on column ATT_DELISTED_WTR.ASSESSMNT_UNIT_IDENT is 'A unique identifier assigned to the Assessment Unit by the reporting organization (AssessmentUnitIdentifier)';
comment on column ATT_DELISTED_WTR_CAUSE.AGNCY_CODE is 'Code identifying the agency responsible for the action (S=State, E=EPA, T=Tribal) (AgencyCode)';
comment on column ATT_DELISTED_WTR_CAUSE.CAUSE_NAME is 'Name of the cause (CauseName)';
comment on column ATT_DELISTED_WTR_CAUSE.DELISTING_CMNT_TXT is 'Free text for providing additional comments on the delisting (DelistingCommentText)';
comment on column ATT_DELISTED_WTR_CAUSE.DELISTING_REASON_CODE is 'Reason the waterbody/cause is being delisted (DelistingReasonCode)';
comment on column ATT_DOCUMENT.AGNCY_CODE is 'Code identifying the agency responsible for the action (S=State, E=EPA, T=Tribal) (AgencyCode)';
comment on column ATT_DOCUMENT.DOCUMENT_CMNTS is 'Free text for providing additional comments on the document. (DocumentComments)';
comment on column ATT_DOCUMENT.DOCUMENT_DESC is 'Description of the document (DocumentDescription)';
comment on column ATT_DOCUMENT.DOCUMENT_FILE_NAME is 'File of the document. Should be the file name of the document, including the extension (.doc, .pdf, etc.). The document must be included in a .zip file with this name and included in the submission along with the XML file. (DocumentFileName)';
comment on column ATT_DOCUMENT.DOCUMENT_FILE_TYPE is 'The file extension of the document (DocumentFileType)';
comment on column ATT_DOCUMENT.DOCUMENT_NAME is 'Name of the document (DocumentName)';
comment on column ATT_DOCUMENT.DOCUMENT_URL is 'URL where the document can be accessed online (DocumentURL)';
comment on column ATT_DOCUMENT_TYPE.DOCUMENT_TYPE_CODE is 'Type of document being provided (DocumentTypeCode)';
comment on column ATT_LOAD_ALLOCATION_DETAIL.LOAD_ALLOCATION_NUM is 'Load allocation assigned to this AssociatedPollutant (LoadAllocationNumeric)';
comment on column ATT_LOAD_ALLOCATION_DETAIL.LOAD_ALLOCATION_UNTS_TXT is 'Unit of measure for load allocation (LoadAllocationUnitsText)';
comment on column ATT_LOAD_ALLOCATION_DETAIL.SEASON_END_TXT is 'The month and day for the start of when this element was evaluated or when the Action applies (MM/DD) (SeasonEndText)';
comment on column ATT_LOAD_ALLOCATION_DETAIL.SEASON_START_TXT is 'The month and day for the start of when this element was evaluated or when the Action applies (MM/DD) (SeasonStartText)';
comment on column ATT_LOC.LOC_TXT is 'Value for the location (LocationText)';
comment on column ATT_LOC.LOC_TYPE_CODE is 'Description of the type of location (i.e. 8-digit HUC, County, etc.) (LocationTypeCode)';
comment on column ATT_MODIFICATIONS.CHANGE_DESC_TXT is 'Text describing the change made to the Assessment Unit (ChangeDescriptionText)';
comment on column ATT_MODIFICATIONS.MOD_TYPE_CODE is 'Code representing the type of modification that was made. (ModificationTypeCode)';
comment on column ATT_MON_STATION.MON_DATA_LINK_TXT is 'URL providing the link to the monitoring data for this station. For Water Quality Portal data, this link should be the Restful URL that would provide access to the data. (MonitoringDataLinkText)';
comment on column ATT_MON_STATION.MON_LOC_IDENT is 'Unique identifier for the monitoring location (MonitoringLocationIdentifier)';
comment on column ATT_MON_STATION.MON_ORG_IDENT is 'Organization that conducted the monitoring. For data that is available via STORET/WQX or the Water Quality portal, this Organization ID is a unique ID assigned by EPA, or other agency responsible for assigning organizations. (MonitoringOrganizationIdentif';
comment on column ATT_NPDES_DETAIL.NPDES_IDENT is 'Unique identifier for a permit as assigned by the NPDES program (NPDESIdentifier)';
comment on column ATT_NPDES_DETAIL.OTHR_IDENT is 'Other state identifier for a permit (OtherIdentifier)';
comment on column ATT_ORG.ORG_IDENT is 'A unique identifier assigned to the organization. Identifiers would be managed centrally by EPA (OrganizationIdentifier)';
comment on column ATT_ORG.ORG_NAME is 'Name corresponding to unique organization ID (i.e. Utah Division of Water Quality); org name will be ignored on submission, for outbound services only (OrganizationName)';
comment on column ATT_ORG.ORG_TYPE_TXT is 'State/tribe/territory; org name will be ignored on submission, for outbound services only (OrganizationTypeText)';
comment on column ATT_ORG_CONTACT.CONTACT_TYPE_TXT is 'Area of responsibility for this contact (TMDL Program, 303(d) Program, Monitoring, Assessment, NPS) (ContactTypeText)';
comment on column ATT_ORG_CONTACT.EMAIL_ADDR_TXT is 'Email address for requesting additional information (EmailAddressText)';
comment on column ATT_ORG_CONTACT.FAX_NUM_TXT is 'Fax Number (FaxNumberText)';
comment on column ATT_ORG_CONTACT.FIRST_NAME is 'First name of a person. (FirstName)';
comment on column ATT_ORG_CONTACT.INDVL_TITLE_TXT is 'Title of the contact person. (IndividualTitleText)';
comment on column ATT_ORG_CONTACT.LAST_NAME is 'Last name of a person. (LastName)';
comment on column ATT_ORG_CONTACT.MAILING_ADDR_CITY_NAME is 'City or Locality Name (MailingAddressCityName)';
comment on column ATT_ORG_CONTACT.MAILING_ADDR_COUNTRY_CODE is 'Country Name (MailingAddressCountryCode)';
comment on column ATT_ORG_CONTACT.MAILING_ADDR_ST_USPS_CODE is 'State USPS Code (i.e. KS) (MailingAddressStateUSPSCode)';
comment on column ATT_ORG_CONTACT.MAILING_ADDR_TXT is 'Mailing Address (MailingAddressText)';
comment on column ATT_ORG_CONTACT.MAILING_ADDR_ZIP_CODE is 'Zip Code (MailingAddressZIPCode)';
comment on column ATT_ORG_CONTACT.MIDDLE_INITIAL is 'Middle Initial of a person. (MiddleInitial)';
comment on column ATT_ORG_CONTACT.PHONE_EXT_TXT is 'Telephone number extension (PhoneExtensionText)';
comment on column ATT_ORG_CONTACT.SUB_ORG_NAME is 'Name of the suborganization who has responsibility for this area (SubOrganizationName)';
comment on column ATT_ORG_CONTACT.SUPPL_ADDR_TXT is 'Additional Address Information (SupplementalAddressText)';
comment on column ATT_ORG_CONTACT.TELEPH_NUM_TXT is 'Telephone Number data (TelephoneNumberText)';
comment on column ATT_ORG_CONTACT.WEB_URL_TXT is 'Organization web link for more information (WebURLText)';
comment on column ATT_PARAM.AGNCY_CODE is 'Code identifying the agency responsible for the action (S=State, E=EPA, T=Tribal) (AgencyCode)';
comment on column ATT_PARAM.ALTERNATE_LISTING_IDENT is 'Unique identifier for the listed water. Use this identifier ONLY if the listing identifier is different from the Assessment Unit Identifier (AlternateListingIdentifier)';
comment on column ATT_PARAM.CONSENT_DECREE_CYCLE_TXT is 'Cycle for which Consent Decree actions are due (ConsentDecreeCycleText)';
comment on column ATT_PARAM.CWA_303D_PRIO_RANKING_TXT is 'CWA 303(d) priority for developing a TMDL (i.e. High, Medium, Low) (CWA303dPriorityRankingText)';
comment on column ATT_PARAM.CYCLE_EXPECTED_TO_ATTAIN_TXT is 'Cycle by which the Assessment Unit is expected to attain its standards (used to indicate whether or not this cause should be considered towards category 4B) (CycleExpectedToAttainText)';
comment on column ATT_PARAM.CYCLE_FIRST_LISTED_TXT is 'Cycle the Assessment Unit was first listed for this cause (CycleFirstListedText)';
comment on column ATT_PARAM.CYCLE_SCHD_FOR_TMDL_TXT is 'Cycle when the jurisdiction anticipates submitting the TMDL for EPA approval (CycleScheduledForTMDLText)';
comment on column ATT_PARAM.PARAM_CMNT_TXT is 'Free text providing additional comments for the parameter (ParameterCommentText)';
comment on column ATT_PARAM.PARAM_NAME is 'Name of the parameter (ParameterName)';
comment on column ATT_PARAM.PARAM_STAT_NAME is 'Status for the parameter indicating whether this parameter is a cause, observed effect, or provided for informational purposes as a monitored parameter. (ParameterStatusName)';
comment on column ATT_PARAM.POLUT_IND is 'Flag indicating whether or not the cause is a pollutant (PollutantIndicator)';
comment on column ATT_PARAM.ST_QUALIFIER_TXT is 'Additional information about the parent element (StateQualifierText)';
comment on column ATT_PREVIOUS_ASSESSMNT_UNIT.ASSESSMNT_UNIT_IDENT is 'A unique identifier assigned to the Assessment Unit by the reporting organization (AssessmentUnitIdentifier)';
comment on column ATT_PRIO.CYCLE_BASE_LINE_TXT is 'Cycle that is the baseline for the priority (starting cycle) (CycleBaseLineText)';
comment on column ATT_PRIO.CYCLE_GOAL_TXT is 'Cycle that is the goal for the priority (ending cycle) (CycleGoalText)';
comment on column ATT_PRIO.PRIO_CMNT_TXT is 'Free text providing additional comments on the priority (PriorityCommentText)';
comment on column ATT_PRIO.PRIO_DESC_TXT is 'Description of the priority (PriorityDescriptionText)';
comment on column ATT_PRIO.PRIO_IDENT is 'Unique identifier for a priority (PriorityIdentifier)';
comment on column ATT_PRIO.PRIO_NAME is 'Name for the priority (PriorityName)';
comment on column ATT_PRIO.PRIO_STAT_CODE is 'Status of the Priority (PriorityStatusCode)';
comment on column ATT_PRIO.PRIO_STAT_DATE is 'Date the status was changed (PriorityStatusDate)';
comment on column ATT_PRIO.PRIO_TYPE_CODE is 'Code identifying the type of priority that is being set (PriorityTypeCode)';
comment on column ATT_PRIO_ASSESSMNT_UNIT.ASSESSMNT_UNIT_IDENT is 'A unique identifier assigned to the Assessment Unit by the reporting organization (AssessmentUnitIdentifier)';
comment on column ATT_PRIO_PARAM.PARAM_NAME is 'Name of the parameter (ParameterName)';
comment on column ATT_PRIO_USE.USE_NAME is 'Name of the designated use. (UseName)';
comment on column ATT_PRIOR_CAUSE.PRIOR_CAUSE_CYCLE_TXT is 'Cycle for the prior cause that is being replaced with or related to the cause. (PriorCauseCycleText)';
comment on column ATT_PRIOR_CAUSE.PRIOR_CAUSE_NAME is 'Prior name for the cause for this Assessment Unit (PriorCauseName)';
comment on column ATT_PROBABLE_SRC.SRC_CMNT_TXT is 'Free text for providing additional comments on the source (SourceCommentText)';
comment on column ATT_PROBABLE_SRC.SRC_CONFIRMED_IND is 'Indicator of whether the source has been confirmed (SourceConfirmedIndicator)';
comment on column ATT_PROBABLE_SRC.SRC_NAME is 'Name of the source (SourceName)';
comment on column ATT_RELATED_TMD_LS.ACTN_IDENT is 'Unique code identifying the action (ActionIdentifier)';
comment on column ATT_RELATED_TMD_LS.CHANGE_TYPE_TXT is 'Free text describing the relationship between the TMDLs (ChangeTypeText)';
comment on column ATT_REP_CYCLE.REP_CYCLE_TXT is 'Reporting cycle for the Assessments (ReportingCycleText)';
comment on column ATT_REP_CYCLE.REP_STAT_CODE is 'Status of the report or 303(d) list (i.e. Final, Draft, Public Comment, etc.) (ReportStatusCode)';
comment on column ATT_REVIEW_CMNT.ORG_IDENT is 'A unique identifier assigned to the organization. Identifiers would be managed centrally by EPA (OrganizationIdentifier)';
comment on column ATT_REVIEW_CMNT.REVIEW_CMNT_DATE is 'The date the comment was made (ReviewCommentDate)';
comment on column ATT_REVIEW_CMNT.REVIEW_CMNT_TXT is 'The actual comment (ReviewCommentText)';
comment on column ATT_REVIEW_CMNT.REVIEW_CMNT_USR_NAME is 'The username of the commenter (ReviewCommentUserName)';
comment on column ATT_SEASON.SEASON_END_TXT is 'The month and day for the start of when this element was evaluated or when the Action applies (MM/DD) (SeasonEndText)';
comment on column ATT_SEASON.SEASON_START_TXT is 'The month and day for the start of when this element was evaluated or when the Action applies (MM/DD) (SeasonStartText)';
comment on column ATT_SPECIFIC_WTR.ASSESSMNT_UNIT_IDENT is 'A unique identifier assigned to the Assessment Unit by the reporting organization (AssessmentUnitIdentifier)';
comment on column ATT_SRC.SRC_CMNT_TXT is 'Free text for providing additional comments on the source (SourceCommentText)';
comment on column ATT_SRC.SRC_NAME is 'Name of the source (SourceName)';
comment on column ATT_ST_INTEGRATED_REP_CATG.ST_CATG_DESC_TXT is 'Description of the State IR Category (StateCategoryDescriptionText)';
comment on column ATT_ST_INTEGRATED_REP_CATG.ST_IR_CATG_CODE is 'State Integrated Reporting Category (StateIRCategoryCode)';
comment on column ATT_ST_WIDE_ACTN.ST_WIDE_ASSESSMNT_IDENT is 'Unique code identifying the statewide assessment (StateWideAssessmentIdentifier)';
comment on column ATT_ST_WIDE_ACTN.ST_WIDE_CMNT_TXT is 'Free text for providing additional comments on the statewide assessment or action (StateWideCommentText)';
comment on column ATT_ST_WIDE_ACTN.ST_WIDE_CYCLE_TXT is 'Cycle when the statewide assessment was made (StateWideCycleText)';
comment on column ATT_ST_WIDE_ASSESSMNT.ST_WIDE_ASSESSMNT_IDENT is 'Unique code identifying the statewide assessment (StateWideAssessmentIdentifier)';
comment on column ATT_ST_WIDE_ASSESSMNT.ST_WIDE_ASSESSMNT_NAME is 'Common name that this statewide assessment is referred by. (StateWideAssessmentName)';
comment on column ATT_ST_WIDE_ASSESSMNT.ST_WIDE_CMNT_TXT is 'Free text for providing additional comments on the statewide assessment or action (StateWideCommentText)';
comment on column ATT_ST_WIDE_CAUSE.ST_WIDE_CAUSE_NAME is 'Name of cause (StateWideCauseName)';
comment on column ATT_ST_WIDE_PROBABLE_SRC.ST_WIDE_PROBABLE_SRC_NAME is 'Name of probable source (StateWideProbableSourceName)';
comment on column ATT_ST_WIDE_SRC.ST_WIDE_SRC_NAME is 'Name of source (StateWideSourceName)';
comment on column ATT_ST_WIDE_USE_ATTAINMENT.AGNCY_CODE is 'Code identifying the agency responsible for the action (S=State, E=EPA, T=Tribal) (AgencyCode)';
comment on column ATT_ST_WIDE_USE_ATTAINMENT.ST_WIDE_USE_NAME is 'Name of the designated use. (StateWideUseName)';
comment on column ATT_ST_WIDE_USE_ATTAINMENT.THREATENED_IND is 'Indicator identifying whether or not the use is threatened. If this code is set to Y AttainmentCode should typically be Fully Supporting. Not reporting this data element is equivalent to saying ThreatenedIndicator=N. (ThreatenedIndicator)';
comment on column ATT_ST_WIDE_USE_ATTAINMENT.TREND_CODE is 'Code representing the water quality trend for this use or parameter. (TrendCode)';
comment on column ATT_ST_WIDE_USE_ATTAINMENT.USE_ATTAINMENT_CODE is 'Code identifying the use attainment for this use (UseAttainmentCode)';
comment on column ATT_ST_WIDE_WTR_TYPE.ST_WIDE_WTR_TYPE_CODE is 'Code representing the water type (StateWideWaterTypeCode)';
comment on column ATT_TMDLNPDES_DETAIL.SEASON_END_TXT is 'The month and day for the start of when this element was evaluated or when the Action applies (MM/DD) (SeasonEndText)';
comment on column ATT_TMDLNPDES_DETAIL.SEASON_START_TXT is 'The month and day for the start of when this element was evaluated or when the Action applies (MM/DD) (SeasonStartText)';
comment on column ATT_TMDLNPDES_DETAIL.WASTE_LOAD_ALLOCATION_NUM is 'Waste load allocation assigned to this Permittee (WasteLoadAllocationNumeric)';
comment on column ATT_TMDLNPDES_DETAIL.WASTE_LOAD_ALLOCATION_UNTS_TXT is 'Unit of measure for waste load allocation (WasteLoadAllocationUnitsText)';
comment on column ATT_USE_ATTAINMENT.AGNCY_CODE is 'Code identifying the agency responsible for the action (S=State, E=EPA, T=Tribal) (AgencyCode)';
comment on column ATT_USE_ATTAINMENT.ASSESSMNT_BASIS_CODE is 'Code representing the basis for the assessment; is it based on monitored data, extrapolated data, or both. (AssessmentBasisCode)';
comment on column ATT_USE_ATTAINMENT.ASSESSMNT_DATE is 'Day on which the assessment was completed (AssessmentDate)';
comment on column ATT_USE_ATTAINMENT.ASSESSOR_NAME is 'Name of the individual performing the assessment (AssessorName)';
comment on column ATT_USE_ATTAINMENT.MON_END_DATE is 'Date on which monitoring ended (MonitoringEndDate)';
comment on column ATT_USE_ATTAINMENT.MON_START_DATE is 'Date on which monitoring began (MonitoringStartDate)';
comment on column ATT_USE_ATTAINMENT.ST_QUALIFIER_TXT is 'Additional information about the parent element (StateQualifierText)';
comment on column ATT_USE_ATTAINMENT.THREATENED_IND is 'Indicator identifying whether or not the use is threatened. If this code is set to Y AttainmentCode should typically be Fully Supporting. Not reporting this data element is equivalent to saying ThreatenedIndicator=N. (ThreatenedIndicator)';comment on column ATT_USE_ATTAINMENT.TREND_CODE is 'Code representing the water quality trend for this use or parameter. (TrendCode)';
comment on column ATT_USE_ATTAINMENT.USE_ATTAINMENT_CODE is 'Code identifying the use attainment for this use (UseAttainmentCode)';
comment on column ATT_USE_ATTAINMENT.USE_CMNT_TXT is 'Free text for providing additional comments on the use assessment (UseCommentText)';
comment on column ATT_USE_ATTAINMENT.USE_NAME is 'Name of the designated use. (UseName)';
comment on column ATT_WTR_TYPE.SIZE_ESTIMATION_METHOD_CODE is 'Code representing the method used for determining the water size (SizeEstimationMethodCode)';
comment on column ATT_WTR_TYPE.SIZE_SRC_SCALE_TXT is 'Text describing the scale of the source material used for estimating the water size (i.e. 1:24000) (SizeSourceScaleText)';
comment on column ATT_WTR_TYPE.SIZE_SRC_TXT is 'Text describing the source used for estimating the water size. (SizeSourceText)';
comment on column ATT_WTR_TYPE.UNTS_CODE is 'Code representing the unit of measure (UnitsCode)';
comment on column ATT_WTR_TYPE.WTR_SIZE_NUM is 'Size for this particular water type (WaterSizeNumber)';
comment on column ATT_WTR_TYPE.WTR_TYPE_CODE is 'Code representing the water type (WaterTypeCode)';