//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.24 at 11:33:47 AM PST 
//


package com.windsor.node.plugin.facid3.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DataSourceDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataSourceDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}OriginatingPartnerName"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}InformationSystemAcronymName"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}LastUpdatedDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataSourceDataType", propOrder = {
    "originatingPartnerName",
    "informationSystemAcronymName",
    "lastUpdatedDate"
})
public class DataSourceDataType {

    @XmlElement(name = "OriginatingPartnerName", required = true)
    protected String originatingPartnerName;
    @XmlElement(name = "InformationSystemAcronymName", required = true)
    protected String informationSystemAcronymName;
    @XmlElement(name = "LastUpdatedDate")
    protected XMLGregorianCalendar lastUpdatedDate;

    /**
     * Gets the value of the originatingPartnerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatingPartnerName() {
        return originatingPartnerName;
    }

    /**
     * Sets the value of the originatingPartnerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatingPartnerName(String value) {
        this.originatingPartnerName = value;
    }

    /**
     * Gets the value of the informationSystemAcronymName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformationSystemAcronymName() {
        return informationSystemAcronymName;
    }

    /**
     * Sets the value of the informationSystemAcronymName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformationSystemAcronymName(String value) {
        this.informationSystemAcronymName = value;
    }

    /**
     * Gets the value of the lastUpdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * Sets the value of the lastUpdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdatedDate(XMLGregorianCalendar value) {
        this.lastUpdatedDate = value;
    }

}
