//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.24 at 11:33:47 AM PST 
//


package com.windsor.node.plugin.facid3.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TelephonicDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TelephonicDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}TelephoneNumberText" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}TelephoneNumberTypeName" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}TelephoneExtensionNumberText" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TelephonicDataType", propOrder = {
    "telephoneNumberText",
    "telephoneNumberTypeName",
    "telephoneExtensionNumberText"
})
public class TelephonicDataType {

    @XmlElement(name = "TelephoneNumberText")
    protected String telephoneNumberText;
    @XmlElement(name = "TelephoneNumberTypeName")
    protected String telephoneNumberTypeName;
    @XmlElement(name = "TelephoneExtensionNumberText")
    protected String telephoneExtensionNumberText;

    /**
     * Gets the value of the telephoneNumberText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneNumberText() {
        return telephoneNumberText;
    }

    /**
     * Sets the value of the telephoneNumberText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneNumberText(String value) {
        this.telephoneNumberText = value;
    }

    /**
     * Gets the value of the telephoneNumberTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneNumberTypeName() {
        return telephoneNumberTypeName;
    }

    /**
     * Sets the value of the telephoneNumberTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneNumberTypeName(String value) {
        this.telephoneNumberTypeName = value;
    }

    /**
     * Gets the value of the telephoneExtensionNumberText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneExtensionNumberText() {
        return telephoneExtensionNumberText;
    }

    /**
     * Sets the value of the telephoneExtensionNumberText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneExtensionNumberText(String value) {
        this.telephoneExtensionNumberText = value;
    }

}
