--This script creates the two Oracle tables needed to run the OpenNode2 MapForce Plugin Tutorial

CREATE TABLE BEACH(
	EPA_BEACH_ID VARCHAR2(25) NOT NULL,
	BEACH_NAME VARCHAR2(50) NOT NULL,
	BEACH_DESCRIPTION VARCHAR2(100) NULL,
	STATE_CD char(2) NOT NULL,
	FIPS_CD char(5) NOT NULL,
	WATERBODY_NAME_CD VARCHAR2(25) NOT NULL,
	ACCESSIBILITY_TYPE_CD VARCHAR2(25) NOT NULL);

ALTER TABLE BEACH 
ADD CONSTRAINT PK_BEACH PRIMARY KEY ( EPA_BEACH_ID );

CREATE TABLE BEACH_ACTIVITY(
	ACTIVITY_ID VARCHAR2(40) NOT NULL,
	EPA_BEACH_ID VARCHAR2(25) NOT NULL,
	ACTIVITY_TYPE VARCHAR2(25) NOT NULL,
	ACTIVITY_NAME VARCHAR2(50) NOT NULL,
	START_DATE DATE NOT NULL,
	REOPEN_DATE DATE NOT NULL,
	REASON_TYPE_CD VARCHAR2(25) NOT NULL,
	POLLUTION_SOURCE_CD VARCHAR2(25) NOT NULL,
	INDICATOR_TYPE_CD VARCHAR2(25) NOT NULL);

ALTER TABLE BEACH_ACTIVITY 
ADD CONSTRAINT PK_BEACH_ACTIVITY PRIMARY KEY ( ACTIVITY_ID );

ALTER TABLE BEACH_ACTIVITY  ADD CONSTRAINT FK_BEACH_ACTIVITY_BEACH FOREIGN KEY(EPA_BEACH_ID)
REFERENCES BEACH (EPA_BEACH_ID);
