CREATE TABLE RCRA_HD_CERTIFICATION ( 
	PK_GUID            	VARCHAR(40) NOT NULL,
	FK_GUID            	VARCHAR(40) NOT NULL,
	TRANSACTION_CODE   	CHARACTER(1),
	CERT_SEQ           	INTEGER NOT NULL,
	CERT_SIGNED_DATE   	VARCHAR(10),
	CERT_TITLE         	VARCHAR(45),
	CERT_FIRST_NAME    	VARCHAR(15),
	CERT_MIDDLE_INITIAL	CHARACTER(1),
	CERT_LAST_NAME     	VARCHAR(15),
	NOTES              	VARCHAR(245) 
	)
/

CREATE TABLE RCRA_HD_ENV_PERMIT ( 
	PK_GUID          	VARCHAR(40) NOT NULL,
	FK_GUID          	VARCHAR(40) NOT NULL,
	TRANSACTION_CODE 	CHARACTER(1),
	ENV_PERMIT_NUMBER	VARCHAR(13) NOT NULL,
	ENV_PERMIT_OWNER 	CHARACTER(2),
	ENV_PERMIT_TYPE  	CHARACTER(1),
	ENV_PERMIT_DESC  	VARCHAR(20) NOT NULL,
	NOTES            	VARCHAR(240) 
	)
/

CREATE TABLE RCRA_HD_HANDLER ( 
	PK_GUID                       	VARCHAR(40) NOT NULL,
	FK_GUID                       	VARCHAR(40) NOT NULL,
	TRANSACTION_CODE              	CHARACTER(1),
	ACTIVITY_LOCATION             	CHARACTER(2) NOT NULL,
	SOURCE_TYPE                   	CHARACTER(1) NOT NULL,
	SEQ_NUMBER                    	INTEGER NOT NULL,
	RECEIVE_DATE                  	VARCHAR(10),
	NON_NOTIFIER                  	CHARACTER(1),
	NUMBER_OF_EMPLOYEES           	INTEGER,
	LOCATION_STREET1              	VARCHAR(30),
	LOCATION_STREET2              	VARCHAR(30),
	LOCATION_CITY                 	VARCHAR(25),
	LOCATION_STATE                	CHARACTER(2),
	LOCATION_ZIP                  	VARCHAR(14),
	LOCATION_COUNTRY              	CHARACTER(2),
	MAIL_STREET1                  	VARCHAR(30),
	MAIL_STREET2                  	VARCHAR(30),
	MAIL_CITY                     	VARCHAR(25),
	MAIL_STATE                    	CHARACTER(2),
	MAIL_ZIP                      	VARCHAR(14),
	MAIL_COUNTRY                  	CHARACTER(2),
	CONTACT_FIRST_NAME            	VARCHAR(15),
	CONTACT_MIDDLE_INITIAL        	CHARACTER(1),
	CONTACT_LAST_NAME             	VARCHAR(15),
	CONTACT_ORG_NAME              	VARCHAR(80),
	CONTACT_STREET1               	VARCHAR(30),
	CONTACT_STREET2               	VARCHAR(30),
	CONTACT_CITY                  	VARCHAR(25),
	CONTACT_STATE                 	CHARACTER(2),
	CONTACT_ZIP                   	VARCHAR(14),
	CONTACT_COUNTRY               	CHARACTER(2),
	CONTACT_PHONE                 	VARCHAR(15),
	CONTACT_PHONE_EXT             	VARCHAR(6),
	CONTACT_EMAIL_ADDRESS         	VARCHAR(240),
	PCONTACT_FIRST_NAME           	VARCHAR(15),
	PCONTACT_MIDDLE_NAME          	CHARACTER(1),
	PCONTACT_LAST_NAME            	VARCHAR(15),
	PCONTACT_ORG_NAME             	VARCHAR(80),
	PCONTACT_STREET1              	VARCHAR(30),
	PCONTACT_STREET2              	VARCHAR(30),
	PCONTACT_CITY                 	VARCHAR(25),
	PCONTACT_STATE                	CHARACTER(2),
	PCONTACT_ZIP                  	VARCHAR(14),
	PCONTACT_COUNTRY              	CHARACTER(2),
	PCONTACT_PHONE                	VARCHAR(15),
	PCONTACT_PHONE_EXT            	VARCHAR(6),
	PCONTACT_EMAIL_ADDRESS        	VARCHAR(240),
	ACKNOWLEDGE_DATE              	VARCHAR(10),
	ACKNOWLEDGE_FLAG              	CHARACTER(1),
	SITE_NAME                     	VARCHAR(80),
	IMPORTER_ACTIVITY             	CHARACTER(1),
	MIXED_WASTE_GENERATOR         	CHARACTER(1),
	RECYCLER_ACTIVITY             	CHARACTER(1),
	TRANSPORTER_ACTIVITY          	CHARACTER(1),
	TSD_ACTIVITY                  	CHARACTER(1),
	UNDERGROUND_INJECTION_ACTIVITY	CHARACTER(1),
	UNIVERSAL_WASTE_DEST_FACILITY 	CHARACTER(1),
	ONSITE_BURNER_EXEMPTION       	CHARACTER(1),
	FURNACE_EXEMPTION             	CHARACTER(1),
	LAND_TYPE                     	CHARACTER(1),
	STATE_DISTRICT                	VARCHAR(10),
	USED_OIL_BURNER               	CHARACTER(1),
	USED_OIL_PROCESSOR            	CHARACTER(1),
	USED_OIL_REFINER              	CHARACTER(1),
	USED_OIL_MARKET_BURNER        	CHARACTER(1),
	USED_OIL_SPEC_MARKETER        	CHARACTER(1),
	USED_OIL_TRANSFER_FACILITY    	CHARACTER(1),
	USED_OIL_TRANSPORTER          	CHARACTER(1),
	TSD_DATE                      	VARCHAR(10),
	OFF_SITE_RECEIPT              	CHARACTER(1),
	ACCESSIBILITY                 	CHARACTER(1),
	COUNTY_CODE                   	VARCHAR(5),
	COUNTY_CODE_OWNER             	CHARACTER(2),
	FED_WASTE_GENERATOR_OWNER     	CHARACTER(2),
	FED_WASTE_GENERATOR           	CHARACTER(1),
	STATE_WASTE_GENERATOR_OWNER   	CHARACTER(2),
	STATE_WASTE_GENERATOR         	CHARACTER(1),
	NOTES                         	VARCHAR(2000) 
	)
/

CREATE TABLE RCRA_HD_HBASIC ( 
	PK_GUID            	VARCHAR(40) NOT NULL,
	TRANSACTION_CODE   	CHARACTER(1),
	HANDLER_ID         	VARCHAR(12) NOT NULL,
	EXTRACT_FLAG       	CHARACTER(1),
	FACILITY_IDENTIFIER	VARCHAR(12),
	NOTES              	VARCHAR(240),
	LAST_UPDATE_DATE   	TIMESTAMP NOT NULL 
	)
/

CREATE TABLE RCRA_HD_NAICS ( 
	PK_GUID         	VARCHAR(40)  NOT NULL,
	FK_GUID         	VARCHAR(40) NOT NULL,
	TRANSACTION_CODE	CHARACTER(1),
	NAICS_SEQ       	INTEGER NOT NULL,
	NAICS_OWNER     	CHARACTER(2),
	NAICS_CODE      	VARCHAR(6),
	NOTES           	VARCHAR(240) 
	)
/

CREATE TABLE RCRA_HD_OTHER_ID ( 
	PK_GUID           	VARCHAR(40) NOT NULL,
	FK_GUID           	VARCHAR(40) NOT NULL,
	TRANSACTION_CODE	CHARACTER(1),
	OTHER_ID          	VARCHAR(12) NOT NULL,
	RELATIONSHIP_OWNER	CHARACTER(2),
	RELATIONSHIP_TYPE 	CHARACTER(1),
	SAME_FACILITY     	CHARACTER(1),
	NOTES             	VARCHAR(2000) 
	)
/

CREATE TABLE RCRA_HD_OWNEROP ( 
	PK_GUID            	VARCHAR(40)  NOT NULL,
	FK_GUID            	VARCHAR(40) NOT NULL,
	TRANSACTION_CODE   	CHARACTER(1),
	OWNER_OP_SEQ       	INTEGER NOT NULL,
	OWNER_OP_IND       	CHARACTER(2),
	FIRST_NAME         	VARCHAR(15),
	MIDDLE_INITIAL     	CHARACTER(1),
	LAST_NAME          	VARCHAR(15),
	ORG_NAME           	VARCHAR(80),
	OWNER_OP_TYPE      	CHARACTER(1),
	DATE_BECAME_CURRENT	VARCHAR(10),
	DATE_ENDED_CURRENT 	VARCHAR(10),
	STREET1            	VARCHAR(30),
	STREET2            	VARCHAR(30),
	CITY               	VARCHAR(25),
	STATE              	CHARACTER(2),
	COUNTRY            	CHARACTER(2),
	ZIP                	VARCHAR(14),
	PHONE              	VARCHAR(15),
	PHONE_EXT          	VARCHAR(6),
	EMAIL_ADDRESS      	VARCHAR(240),
	DUNN_BRADSTREET_NUM	VARCHAR(10),
	NOTES              	VARCHAR(240) 
	)
/

CREATE TABLE RCRA_HD_STATE_ACTIVITY ( 
	PK_GUID             	VARCHAR(40) NOT NULL,
	FK_GUID             	VARCHAR(40) NOT NULL,
	TRANSACTION_CODE    	CHARACTER(1),
	STATE_ACTIVITY_OWNER	CHARACTER(2) NOT NULL,
	STATE_ACTIVITY_TYPE 	VARCHAR(5) NOT NULL,
	NOTES               	VARCHAR(2000) 
	)
/

CREATE TABLE RCRA_HD_UNIVERSAL_WASTE ( 
	PK_GUID              	VARCHAR(40)  NOT NULL,
	FK_GUID              	VARCHAR(40) NOT NULL,
	TRANSACTION_CODE     	CHARACTER(1),
	UNIVERSAL_WASTE_OWNER	CHARACTER(2),
	UNIVERSAL_WASTE_TYPE 	CHARACTER(1),
	ACCUMULATED          	CHARACTER(1),
	GENERATED            	CHARACTER(1),
	NOTES                	VARCHAR(240) 
	)
/

CREATE TABLE RCRA_HD_WASTE_CODE ( 
	PK_GUID         	VARCHAR(40) NOT NULL,
	FK_GUID         	VARCHAR(40) NOT NULL,
	TRANSACTION_CODE	CHARACTER(1),
	WASTE_CODE_OWNER	CHARACTER(2),
	WASTE_CODE_TYPE 	VARCHAR(6) 
	)
/

CREATE INDEX IDX_CERT
	ON RCRA_HD_CERTIFICATION(FK_GUID)
/

CREATE INDEX IDX_ENVPERMIT
	ON RCRA_HD_ENV_PERMIT(FK_GUID)
/

CREATE INDEX IDX_HANDLER
	ON RCRA_HD_HANDLER(FK_GUID)
/

CREATE INDEX IDX_HANDLER_ID
	ON RCRA_HD_HBASIC(HANDLER_ID)
/

CREATE INDEX IDX_NAICS
	ON RCRA_HD_NAICS(FK_GUID)
/

CREATE INDEX IDX_OTHERID
	ON RCRA_HD_OTHER_ID(FK_GUID)
/

CREATE INDEX IDX_OWNEROP
	ON RCRA_HD_OWNEROP(FK_GUID)
/

CREATE INDEX IDX_STATEACT
	ON RCRA_HD_STATE_ACTIVITY(FK_GUID)
/

CREATE INDEX IDX_UNIV
	ON RCRA_HD_UNIVERSAL_WASTE(FK_GUID)
/

CREATE INDEX IDX_WASTE
	ON RCRA_HD_WASTE_CODE(FK_GUID)
/

ALTER TABLE RCRA_HD_CERTIFICATION
	ADD CONSTRAINT SQL080522162120440
	PRIMARY KEY (PK_GUID)
/

ALTER TABLE RCRA_HD_ENV_PERMIT
	ADD CONSTRAINT SQL090420141704110
	PRIMARY KEY (PK_GUID)
/

ALTER TABLE RCRA_HD_HANDLER
	ADD CONSTRAINT SQL090422120358410
	PRIMARY KEY (PK_GUID)
/

ALTER TABLE RCRA_HD_HBASIC
	ADD CONSTRAINT SQL090420143700820
	PRIMARY KEY (PK_GUID)
/

ALTER TABLE RCRA_HD_NAICS
	ADD CONSTRAINT SQL080522161304650
	PRIMARY KEY (PK_GUID)
/

ALTER TABLE RCRA_HD_OTHER_ID
	ADD CONSTRAINT SQL090420153601240
	PRIMARY KEY (PK_GUID)
/

ALTER TABLE RCRA_HD_OWNEROP
	ADD CONSTRAINT SQL090420140542950
	PRIMARY KEY (PK_GUID)
/

ALTER TABLE RCRA_HD_STATE_ACTIVITY
	ADD CONSTRAINT SQL090420141726010
	PRIMARY KEY (PK_GUID)
/

ALTER TABLE RCRA_HD_UNIVERSAL_WASTE
	ADD CONSTRAINT SQL080522161229230
	PRIMARY KEY (PK_GUID)
/

ALTER TABLE RCRA_HD_WASTE_CODE
	ADD CONSTRAINT SQL080522161249810
	PRIMARY KEY (PK_GUID)
/

ALTER TABLE RCRA_HD_HANDLER
	ADD CONSTRAINT FK_HBASIC_HANDLER
	FOREIGN KEY(FK_GUID)
	REFERENCES RCRA_HD_HBASIC(PK_GUID)
/

ALTER TABLE RCRA_HD_OTHER_ID
	ADD CONSTRAINT FK_HBASIC_OTHERID
	FOREIGN KEY(FK_GUID)
	REFERENCES RCRA_HD_HBASIC(PK_GUID)
/

CREATE TABLE RCRA_CME_CITATION ( 
	CITATION_ID          	VARCHAR2(40) NOT NULL,
	VIOL_ID              	VARCHAR2(40) NOT NULL,
	TRANS_CODE           	VARCHAR2(50) NULL,
	CITATION_NAME_SEQ_NUM	NUMBER NOT NULL,
	CITATION_NAME        	VARCHAR2(128) NULL,
	CITATION_NAME_OWNER  	VARCHAR2(255) NULL,
	CITATION_NAME_TYPE   	VARCHAR2(255) NULL,
	NOTES                	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_CSNY_DATE ( 
	CSNY_DATE_ID	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID	VARCHAR2(40) NOT NULL,
	TRANS_CODE  	VARCHAR2(50) NULL,
	SNY_DATE    	DATE NOT NULL 
	)
/

CREATE TABLE RCRA_CME_ENFRC_ACT ( 
	ENFRC_ACT_ID                 	VARCHAR2(40) NOT NULL,
	CME_FAC_SUBM_ID              	VARCHAR2(40) NOT NULL,
	TRANS_CODE                   	VARCHAR2(50) NULL,
	ENFRC_AGN_LOC_NAME           	VARCHAR2(128) NOT NULL,
	ENFRC_ACT_IDEN               	VARCHAR2(50) NOT NULL,
	ENFRC_ACT_DATE               	DATE NOT NULL,
	ENFRC_AGN_NAME               	VARCHAR2(128) NOT NULL,
	ENFRC_DOCKET_NUM             	VARCHAR2(20) NULL,
	ENFRC_ATTRY                  	VARCHAR2(255) NULL,
	CORCT_ACT_COMPT              	VARCHAR2(255) NULL,
	CNST_AGMT_FINAL_ORDER_SEQ_NUM	NUMBER NULL,
	APPEAL_INIT_DATE             	DATE NULL,
	APPEAL_RSLN_DATE             	DATE NULL,
	DISP_STAT_DATE               	DATE NULL,
	DISP_STAT_OWNER              	VARCHAR2(255) NULL,
	DISP_STAT                    	VARCHAR2(255) NULL,
	ENFRC_OWNER                  	VARCHAR2(255) NULL,
	ENFRC_TYPE                   	VARCHAR2(255) NULL,
	ENFRC_RESP_PERSON_OWNER      	VARCHAR2(255) NULL,
	ENFRC_RESP_PERSON_IDEN       	VARCHAR2(50) NULL,
	ENFRC_RESP_SUBORG_OWNER      	VARCHAR2(255) NULL,
	ENFRC_RESP_SUBORG            	VARCHAR2(255) NULL,
	NOTES                        	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_EVAL ( 
	EVAL_ID                    	VARCHAR2(40) NOT NULL,
	CME_FAC_SUBM_ID            	VARCHAR2(40) NOT NULL,
	TRANS_CODE                 	VARCHAR2(50) NULL,
	EVAL_ACT_LOC               	VARCHAR2(255) NOT NULL,
	EVAL_IDEN                  	VARCHAR2(50) NOT NULL,
	EVAL_START_DATE            	DATE NOT NULL,
	EVAL_RESP_AGN              	VARCHAR2(255) NOT NULL,
	DAY_ZERO                   	DATE NULL,
	FOUND_VIOL                 	VARCHAR2(255) NULL,
	CTZN_CPLT_IND              	VARCHAR2(50) NULL,
	MULTIMEDIA_IND             	VARCHAR2(50) NULL,
	SAMPL_IND                  	VARCHAR2(50) NULL,
	NOT_SUBTL_C_IND            	VARCHAR2(50) NULL,
	EVAL_TYPE_OWNER            	VARCHAR2(255) NULL,
	EVAL_TYPE                  	VARCHAR2(255) NULL,
	FOCUS_AREA_OWNER           	VARCHAR2(255) NULL,
	FOCUS_AREA                 	VARCHAR2(255) NULL,
	EVAL_RESP_PERSON_IDEN_OWNER	VARCHAR2(255) NULL,
	EVAL_RESP_PERSON_IDEN      	VARCHAR2(50) NULL,
	EVAL_RESP_SUBORG_OWNER     	VARCHAR2(255) NULL,
	EVAL_RESP_SUBORG           	VARCHAR2(255) NULL,
	NOTES                      	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_EVAL_COMMIT ( 
	EVAL_COMMIT_ID	VARCHAR2(40) NOT NULL,
	EVAL_ID       	VARCHAR2(40) NOT NULL,
	TRANS_CODE    	VARCHAR2(50) NULL,
	COMMIT_LEAD   	VARCHAR2(255) NOT NULL,
	COMMIT_SEQ_NUM	NUMBER NOT NULL 
	)
/

CREATE TABLE RCRA_CME_EVAL_VIOL ( 
	EVAL_VIOL_ID       	VARCHAR2(40) NOT NULL,
	EVAL_ID            	VARCHAR2(40) NOT NULL,
	TRANS_CODE         	VARCHAR2(50) NULL,
	VIOL_ACT_LOC       	VARCHAR2(255) NOT NULL,
	VIOL_SEQ_NUM       	NUMBER NOT NULL,
	AGN_WHICH_DTRM_VIOL	VARCHAR2(255) NOT NULL 
	)
/

CREATE TABLE RCRA_CME_FAC_SUBM ( 
	CME_FAC_SUBM_ID        	VARCHAR2(40) NOT NULL,
	HAZRD_WASTE_CME_SUBM_ID	VARCHAR2(40) NOT NULL,
	EPA_HDLR_ID            	VARCHAR2(255) NOT NULL 
	)
/

CREATE TABLE RCRA_CME_HAZRD_WASTE_CME_SUBM ( 
	HAZRD_WASTE_CME_SUBM_ID	VARCHAR2(40) NOT NULL 
	)
/

CREATE TABLE RCRA_CME_MEDIA ( 
	MEDIA_ID             	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID         	VARCHAR2(40) NOT NULL,
	TRANS_CODE           	VARCHAR2(50) NULL,
	MULTIMEDIA_CODE_OWNER	VARCHAR2(255) NOT NULL,
	MULTIMEDIA_CODE      	VARCHAR2(50) NOT NULL,
	NOTES                	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_MILESTONE ( 
	MILESTONE_ID            	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID            	VARCHAR2(40) NOT NULL,
	TRANS_CODE              	VARCHAR2(50) NULL,
	MILESTONE_SEQ_NUM       	NUMBER NOT NULL,
	TECH_RQMT_IDEN          	VARCHAR2(50) NULL,
	TECH_RQMT_DESC          	VARCHAR2(255) NULL,
	MILESTONE_SCHD_COMP_DATE	DATE NULL,
	MILESTONE_ACTL_COMP_DATE	DATE NULL,
	MILESTONE_DFLT_DATE     	DATE NULL,
	NOTES                   	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_PNLTY ( 
	PNLTY_ID                      	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID                  	VARCHAR2(40) NOT NULL,
	TRANS_CODE                    	VARCHAR2(50) NULL,
	PNLTY_TYPE_OWNER              	VARCHAR2(255) NOT NULL,
	PNLTY_TYPE                    	VARCHAR2(255) NOT NULL,
	CASH_CIVIL_PNLTY_SOUGHT_AMOUNT	NUMBER(14,6) NULL,
	NOTES                         	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_PYMT ( 
	PYMT_ID         	VARCHAR2(40) NOT NULL,
	PNLTY_ID        	VARCHAR2(40) NOT NULL,
	TRANS_CODE      	VARCHAR2(50) NULL,
	PYMT_SEQ_NUM    	NUMBER NOT NULL,
	PYMT_DFLT_DATE  	DATE NULL,
	SCHD_PYMT_DATE  	DATE NULL,
	SCHD_PYMT_AMOUNT	NUMBER(14,6) NULL,
	ACTL_PYMT_DATE  	DATE NULL,
	ACTL_PAID_AMOUNT	NUMBER(14,6) NULL,
	NOTES           	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_RQST ( 
	RQST_ID       	VARCHAR2(40) NOT NULL,
	EVAL_ID       	VARCHAR2(40) NOT NULL,
	TRANS_CODE    	VARCHAR2(50) NULL,
	RQST_SEQ_NUM  	NUMBER NOT NULL,
	DATE_OF_RQST  	DATE NULL,
	DATE_RESP_RCVD	DATE NULL,
	RQST_AGN      	VARCHAR2(255) NULL,
	NOTES         	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_SUPP_ENVR_PRJT ( 
	SUPP_ENVR_PRJT_ID 	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID      	VARCHAR2(40) NOT NULL,
	TRANS_CODE        	VARCHAR2(50) NULL,
	SEP_SEQ_NUM       	NUMBER NOT NULL,
	SEP_EXPND_AMOUNT  	NUMBER(14,6) NULL,
	SEP_SCHD_COMP_DATE	DATE NULL,
	SEP_ACTL_DATE     	DATE NULL,
	SEP_DFLT_DATE     	DATE NULL,
	SEP_CODE_OWNER    	VARCHAR2(255) NULL,
	SEP_DESC_TXT      	VARCHAR2(255) NULL,
	NOTES             	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_VIOL ( 
	VIOL_ID             	VARCHAR2(40) NOT NULL,
	CME_FAC_SUBM_ID     	VARCHAR2(40) NOT NULL,
	TRANS_CODE          	VARCHAR2(50) NULL,
	VIOL_ACT_LOC        	VARCHAR2(255) NOT NULL,
	VIOL_SEQ_NUM        	NUMBER NOT NULL,
	AGN_WHICH_DTRM_VIOL 	VARCHAR2(255) NOT NULL,
	VIOL_TYPE_OWNER     	VARCHAR2(255) NULL,
	VIOL_TYPE           	VARCHAR2(255) NULL,
	FORMER_CITATION_NAME	VARCHAR2(128) NULL,
	VIOL_DTRM_DATE      	DATE NULL,
	RTN_COMPL_ACTL_DATE 	DATE NULL,
	RTN_TO_COMPL_QUAL   	VARCHAR2(255) NULL,
	VIOL_RESP_AGN       	VARCHAR2(255) NULL,
	NOTES               	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_VIOL_ENFRC ( 
	VIOL_ENFRC_ID      	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID       	VARCHAR2(40) NOT NULL,
	TRANS_CODE         	VARCHAR2(50) NULL,
	VIOL_SEQ_NUM       	NUMBER NOT NULL,
	AGN_WHICH_DTRM_VIOL	VARCHAR2(255) NOT NULL,
	RTN_COMPL_SCHD_DATE	DATE NULL 
	)
/


CREATE UNIQUE INDEX PK_CITATION
	ON RCRA_CME_CITATION(CITATION_ID)
/

CREATE INDEX IX_CTTN_VL_ID
	ON RCRA_CME_CITATION(VIOL_ID)
/

CREATE UNIQUE INDEX PK_CSNY_DATE
	ON RCRA_CME_CSNY_DATE(CSNY_DATE_ID)
/

CREATE INDEX IX_CSN_DT_EN_AC_ID
	ON RCRA_CME_CSNY_DATE(ENFRC_ACT_ID)
/

CREATE UNIQUE INDEX PK_ENFRC_ACT
	ON RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
/

CREATE INDEX IX_EN_AC_CM_FC_SB
	ON RCRA_CME_ENFRC_ACT(CME_FAC_SUBM_ID)
/

CREATE INDEX IX_EVL_CM_FC_SB_ID
	ON RCRA_CME_EVAL(CME_FAC_SUBM_ID)
/

CREATE UNIQUE INDEX PK_EVAL
	ON RCRA_CME_EVAL(EVAL_ID)
/

CREATE INDEX IX_EVL_CMMT_EVL_ID
	ON RCRA_CME_EVAL_COMMIT(EVAL_ID)
/

CREATE UNIQUE INDEX PK_EVAL_COMMIT
	ON RCRA_CME_EVAL_COMMIT(EVAL_COMMIT_ID)
/

CREATE INDEX IX_EVL_VL_EVL_ID
	ON RCRA_CME_EVAL_VIOL(EVAL_ID)
/

CREATE UNIQUE INDEX PK_EVAL_VIOL
	ON RCRA_CME_EVAL_VIOL(EVAL_VIOL_ID)
/

CREATE UNIQUE INDEX PK_CME_FAC_SUBM
	ON RCRA_CME_FAC_SUBM(CME_FAC_SUBM_ID)
/

CREATE INDEX IX_CM_FC_SB_HZ_WS
	ON RCRA_CME_FAC_SUBM(HAZRD_WASTE_CME_SUBM_ID)
/

CREATE UNIQUE INDEX PK_HZR_WST_CME_SBM
	ON RCRA_CME_HAZRD_WASTE_CME_SUBM(HAZRD_WASTE_CME_SUBM_ID)
/

CREATE INDEX IX_MDA_ENFR_ACT_ID
	ON RCRA_CME_MEDIA(ENFRC_ACT_ID)
/

CREATE UNIQUE INDEX PK_MEDIA
	ON RCRA_CME_MEDIA(MEDIA_ID)
/

CREATE UNIQUE INDEX PK_MILESTONE
	ON RCRA_CME_MILESTONE(MILESTONE_ID)
/

CREATE INDEX IX_MLST_ENF_ACT_ID
	ON RCRA_CME_MILESTONE(ENFRC_ACT_ID)
/

CREATE UNIQUE INDEX PK_PNLTY
	ON RCRA_CME_PNLTY(PNLTY_ID)
/

CREATE INDEX IX_PNLT_ENF_ACT_ID
	ON RCRA_CME_PNLTY(ENFRC_ACT_ID)
/

CREATE INDEX IX_PYMT_PNLTY_ID
	ON RCRA_CME_PYMT(PNLTY_ID)
/

CREATE UNIQUE INDEX PK_PYMT
	ON RCRA_CME_PYMT(PYMT_ID)
/

CREATE INDEX IX_RQST_EVAL_ID
	ON RCRA_CME_RQST(EVAL_ID)
/

CREATE UNIQUE INDEX PK_RQST
	ON RCRA_CME_RQST(RQST_ID)
/

CREATE INDEX IX_SP_EN_PR_EN_AC
	ON RCRA_CME_SUPP_ENVR_PRJT(ENFRC_ACT_ID)
/

CREATE UNIQUE INDEX PK_SUPP_ENVR_PRJT
	ON RCRA_CME_SUPP_ENVR_PRJT(SUPP_ENVR_PRJT_ID)
/

CREATE UNIQUE INDEX PK_VIOL
	ON RCRA_CME_VIOL(VIOL_ID)
/

CREATE INDEX IX_VL_CME_FC_SB_ID
	ON RCRA_CME_VIOL(CME_FAC_SUBM_ID)
/

CREATE UNIQUE INDEX PK_VIOL_ENFRC
	ON RCRA_CME_VIOL_ENFRC(VIOL_ENFRC_ID)
/

CREATE INDEX IX_VL_ENF_EN_AC_ID
	ON RCRA_CME_VIOL_ENFRC(ENFRC_ACT_ID)
/

ALTER TABLE RCRA_CME_CITATION
	ADD ( CONSTRAINT PK_CITATION
	PRIMARY KEY (CITATION_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_CSNY_DATE
	ADD ( CONSTRAINT PK_CSNY_DATE
	PRIMARY KEY (CSNY_DATE_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_ENFRC_ACT
	ADD ( CONSTRAINT PK_ENFRC_ACT
	PRIMARY KEY (ENFRC_ACT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_EVAL
	ADD ( CONSTRAINT PK_EVAL
	PRIMARY KEY (EVAL_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_EVAL_COMMIT
	ADD ( CONSTRAINT PK_EVAL_COMMIT
	PRIMARY KEY (EVAL_COMMIT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_EVAL_VIOL
	ADD ( CONSTRAINT PK_EVAL_VIOL
	PRIMARY KEY (EVAL_VIOL_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_FAC_SUBM
	ADD ( CONSTRAINT PK_CME_FAC_SUBM
	PRIMARY KEY (CME_FAC_SUBM_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_HAZRD_WASTE_CME_SUBM
	ADD ( CONSTRAINT PK_HZR_WST_CME_SBM
	PRIMARY KEY (HAZRD_WASTE_CME_SUBM_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_MEDIA
	ADD ( CONSTRAINT PK_MEDIA
	PRIMARY KEY (MEDIA_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_MILESTONE
	ADD ( CONSTRAINT PK_MILESTONE
	PRIMARY KEY (MILESTONE_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_PNLTY
	ADD ( CONSTRAINT PK_PNLTY
	PRIMARY KEY (PNLTY_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_PYMT
	ADD ( CONSTRAINT PK_PYMT
	PRIMARY KEY (PYMT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_RQST
	ADD ( CONSTRAINT PK_RQST
	PRIMARY KEY (RQST_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_SUPP_ENVR_PRJT
	ADD ( CONSTRAINT PK_SUPP_ENVR_PRJT
	PRIMARY KEY (SUPP_ENVR_PRJT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_VIOL
	ADD ( CONSTRAINT PK_VIOL
	PRIMARY KEY (VIOL_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_VIOL_ENFRC
	ADD ( CONSTRAINT PK_VIOL_ENFRC
	PRIMARY KEY (VIOL_ENFRC_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_CITATION
	ADD ( CONSTRAINT FK_CITATION_VIOL
	FOREIGN KEY(VIOL_ID)
	REFERENCES RCRA_CME_VIOL(VIOL_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_CSNY_DATE
	ADD ( CONSTRAINT FK_CSN_DTE_ENF_ACT
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_ENFRC_ACT
	ADD ( CONSTRAINT FK_ENF_AC_CM_FC_SB
	FOREIGN KEY(CME_FAC_SUBM_ID)
	REFERENCES RCRA_CME_FAC_SUBM(CME_FAC_SUBM_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_EVAL
	ADD ( CONSTRAINT FK_EVL_CME_FC_SBM
	FOREIGN KEY(CME_FAC_SUBM_ID)
	REFERENCES RCRA_CME_FAC_SUBM(CME_FAC_SUBM_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_EVAL_COMMIT
	ADD ( CONSTRAINT FK_EVL_CMMT_EVL
	FOREIGN KEY(EVAL_ID)
	REFERENCES RCRA_CME_EVAL(EVAL_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_EVAL_VIOL
	ADD ( CONSTRAINT FK_EVAL_VIOL_EVAL
	FOREIGN KEY(EVAL_ID)
	REFERENCES RCRA_CME_EVAL(EVAL_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_FAC_SUBM
	ADD ( CONSTRAINT FK_CM_FC_SB_HZ_WS
	FOREIGN KEY(HAZRD_WASTE_CME_SUBM_ID)
	REFERENCES RCRA_CME_HAZRD_WASTE_CME_SUBM(HAZRD_WASTE_CME_SUBM_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_MEDIA
	ADD ( CONSTRAINT FK_MEDIA_ENFRC_ACT
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_MILESTONE
	ADD ( CONSTRAINT FK_MLSTN_ENFRC_ACT
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_PNLTY
	ADD ( CONSTRAINT FK_PNLTY_ENFRC_ACT
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_PYMT
	ADD ( CONSTRAINT FK_PYMT_PNLTY
	FOREIGN KEY(PNLTY_ID)
	REFERENCES RCRA_CME_PNLTY(PNLTY_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_RQST
	ADD ( CONSTRAINT FK_RQST_EVAL
	FOREIGN KEY(EVAL_ID)
	REFERENCES RCRA_CME_EVAL(EVAL_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_SUPP_ENVR_PRJT
	ADD ( CONSTRAINT FK_SPP_EN_PR_EN_AC
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_VIOL
	ADD ( CONSTRAINT FK_VL_CME_FC_SBM
	FOREIGN KEY(CME_FAC_SUBM_ID)
	REFERENCES RCRA_CME_FAC_SUBM(CME_FAC_SUBM_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_VIOL_ENFRC
	ADD ( CONSTRAINT FK_VL_ENFR_ENF_ACT
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

