/*
Copyright (c) 2016, The Environmental Council of the States (ECOS)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE goODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/

/*****************************************************************************************************************************
 *
 *  Script Name:  RCRA_5.7_to_5.9-upgrade_ORA-DDL.sql
 *
 *  Company:  Windsor Solutions, Inc.
 *
 *  Purpose:  This script will upgrade RCRA 5.7 schema to support RCRA 5.9.
 *
 *  Maintenance:
 *
 *    Analyst         Date            Comment
 *    ----------      ----------      ------------------------------------------------------------------------------
 *    Windsor         10/06/2020      Created
 *
 ****************************************************************************************************************************
 */

---------------------------
--Changed TABLE
--RCRA_SUBMISSIONHISTORY
---------------------------
ALTER TABLE "RCRA_SUBMISSIONHISTORY" MODIFY ("SCHEDULERUNDATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_RU_REPORT_UNIV
---------------------------
ALTER TABLE "RCRA_RU_REPORT_UNIV" ADD ("SUBPART_P_IND" CHAR(1));
ALTER TABLE "RCRA_RU_REPORT_UNIV" MODIFY ("HHANDLER_LAST_CHANGE_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_PRM_UNIT_DETAIL
---------------------------
ALTER TABLE "RCRA_PRM_UNIT_DETAIL" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_PRM_UNIT_DETAIL" ADD ("CURRENT_UNIT_DETAIL_IND" CHAR(1));
ALTER TABLE "RCRA_PRM_UNIT_DETAIL" ADD ("P_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_PRM_UNIT_DETAIL" MODIFY ("PERMIT_STAT_EFFC_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_PRM_UNIT
---------------------------
ALTER TABLE "RCRA_PRM_UNIT" ADD ("ACTIVE_UNIT_IND" CHAR(1));
ALTER TABLE "RCRA_PRM_UNIT" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_PRM_UNIT" ADD ("P_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_PRM_UNIT" MODIFY ("PERMIT_UNIT_SEQ_NUM" NULL);

---------------------------
--Changed TABLE
--RCRA_PRM_SERIES
---------------------------
ALTER TABLE "RCRA_PRM_SERIES" ADD ("ACTIVE_SERIES_IND" CHAR(1));
ALTER TABLE "RCRA_PRM_SERIES" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_PRM_SERIES" ADD ("P_CREATED_DATE" TIMESTAMP(6));

---------------------------
--New TABLE
--RCRA_PRM_MOD_EVENT
---------------------------
  CREATE TABLE "RCRA_PRM_MOD_EVENT" 
   ( "PRM_MOD_EVENT_ID" VARCHAR2(40) NOT NULL ENABLE,
 "PRM_EVENT_ID" VARCHAR2(40) NOT NULL ENABLE,
 "TRANS_CODE" CHAR(1),
 "MOD_HANDLER_ID" VARCHAR2(12) NOT NULL ENABLE,
 "MOD_ACT_LOC_CODE" VARCHAR2(50) NOT NULL ENABLE,
 "MOD_SERIES_SEQ_NUM" NUMBER(10,0) NOT NULL ENABLE,
 "MOD_EVENT_SEQ_NUM" NUMBER(10,0) NOT NULL ENABLE,
 "MOD_EVENT_AGN_CODE" CHAR(1) NOT NULL ENABLE,
 "MOD_EVENT_DATA_OWNER_CODE" CHAR(2) NOT NULL ENABLE,
 "MOD_EVENT_CODE" VARCHAR2(7) NOT NULL ENABLE,
 CONSTRAINT "PK_PRM_MOD_EVENT" PRIMARY KEY ("PRM_MOD_EVENT_ID") ENABLE,
 CONSTRAINT "FK_PRM_MOD_EVENT_PRM_EVENT" FOREIGN KEY ("PRM_EVENT_ID")
  REFERENCES "RCRA_PRM_EVENT" ("PRM_EVENT_ID") ON DELETE CASCADE ENABLE
   );
---------------------------
--Changed TABLE
--RCRA_PRM_EVENT
---------------------------
ALTER TABLE "RCRA_PRM_EVENT" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_PRM_EVENT" ADD ("P_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_PRM_EVENT" MODIFY ("ACTL_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_PRM_EVENT" MODIFY ("NEW_SCHEDULE_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_PRM_EVENT" MODIFY ("ORIGINAL_SCHEDULE_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_HD_LQG_CLOSURE
---------------------------
ALTER TABLE "RCRA_HD_LQG_CLOSURE" MODIFY ("DATE_CLOSED" TIMESTAMP(6));
ALTER TABLE "RCRA_HD_LQG_CLOSURE" MODIFY ("EXPECTED_CLOSURE_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_HD_LQG_CLOSURE" MODIFY ("NEW_CLOSURE_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_HD_HANDLER
---------------------------
ALTER TABLE "RCRA_HD_HANDLER" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_HD_HANDLER" ADD ("CURRENT_RECORD" CHAR(1));
ALTER TABLE "RCRA_HD_HANDLER" ADD ("DATA_ORIG" CHAR(2));
ALTER TABLE "RCRA_HD_HANDLER" ADD ("H_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_HD_HANDLER" MODIFY ("EFFC_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_HD_EPISODIC_EVENT
---------------------------
ALTER TABLE "RCRA_HD_EPISODIC_EVENT" MODIFY ("END_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_HD_EPISODIC_EVENT" MODIFY ("START_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_GIS_GEO_INFORMATION
---------------------------
ALTER TABLE "RCRA_GIS_GEO_INFORMATION" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_GIS_GEO_INFORMATION" ADD ("DATA_ORIG" CHAR(2));
ALTER TABLE "RCRA_GIS_GEO_INFORMATION" ADD ("G_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_GIS_GEO_INFORMATION" MODIFY ("AREA_MEAS_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_GIS_GEO_INFORMATION" MODIFY ("DATA_COLL_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_FA_MECHANISM_DETAIL
---------------------------
ALTER TABLE "RCRA_FA_MECHANISM_DETAIL" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_FA_MECHANISM_DETAIL" ADD ("CURRENT_MECHANISM_DETAIL_IND" CHAR(1));
ALTER TABLE "RCRA_FA_MECHANISM_DETAIL" ADD ("DATA_ORIG" CHAR(2));
ALTER TABLE "RCRA_FA_MECHANISM_DETAIL" ADD ("F_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_FA_MECHANISM_DETAIL" MODIFY ("EFFC_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_FA_MECHANISM_DETAIL" MODIFY ("EXPIRATION_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_FA_MECHANISM
---------------------------
ALTER TABLE "RCRA_FA_MECHANISM" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_FA_MECHANISM" ADD ("DATA_ORIG" CHAR(2));
ALTER TABLE "RCRA_FA_MECHANISM" ADD ("F_CREATED_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_FA_COST_EST
---------------------------
ALTER TABLE "RCRA_FA_COST_EST" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_FA_COST_EST" ADD ("DATA_ORIG" CHAR(2));
ALTER TABLE "RCRA_FA_COST_EST" ADD ("F_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_FA_COST_EST" MODIFY ("COST_ESTIMATE_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_EM_WASTE_CD_TRANS
---------------------------
DROP TABLE "RCRA_EM_WASTE_CD_TRANS";
  CREATE TABLE "RCRA_EM_WASTE_CD_TRANS" 
   ( "EM_WASTE_CD_TRANS_ID" VARCHAR2(40) NOT NULL ENABLE,
 "EM_WASTE_ID" VARCHAR2(40) NOT NULL ENABLE,
 "WASTE_CODE" VARCHAR2(12) NOT NULL ENABLE,
 CONSTRAINT "PK_EM_WASTE_CD_TRANS" PRIMARY KEY ("EM_WASTE_CD_TRANS_ID") ENABLE,
 CONSTRAINT "FK_EM_WASTE_CD_TRANS_EM_WASTE" FOREIGN KEY ("EM_WASTE_ID")
  REFERENCES "RCRA_EM_WASTE" ("EM_WASTE_ID") ON DELETE CASCADE ENABLE
   );
---------------------------
--Changed TABLE
--RCRA_EM_TR_NUM_WASTE
---------------------------
DROP TABLE "RCRA_EM_TR_NUM_WASTE";
  CREATE TABLE "RCRA_EM_TR_NUM_WASTE" 
   ( "EM_TR_NUM_WASTE_ID" VARCHAR2(40) NOT NULL ENABLE,
 "EM_WASTE_ID" VARCHAR2(40) NOT NULL ENABLE,
 "MANIFEST_TRACKING_NUM" VARCHAR2(12) NOT NULL ENABLE,
 CONSTRAINT "PK_EM_TR_NUM_WASTE" PRIMARY KEY ("EM_TR_NUM_WASTE_ID") ENABLE,
 CONSTRAINT "FK_EM_TR_NUM_WASTE_EM_WASTE" FOREIGN KEY ("EM_WASTE_ID")
  REFERENCES "RCRA_EM_WASTE" ("EM_WASTE_ID") ON DELETE CASCADE ENABLE
   );
---------------------------
--Changed TABLE
--RCRA_EM_TR_NUM_RESIDUE_NEW
---------------------------
DROP TABLE "RCRA_EM_TR_NUM_RESIDUE_NEW";
  CREATE TABLE "RCRA_EM_TR_NUM_RESIDUE_NEW" 
   ( "EM_TR_NUM_RESIDUE_NEW_ID" VARCHAR2(40) NOT NULL ENABLE,
 "EM_EMANIFEST_ID" VARCHAR2(40) NOT NULL ENABLE,
 "MANIFEST_TRACKING_NUM" VARCHAR2(12) NOT NULL ENABLE,
 CONSTRAINT "PK_EM_TR_NUM_RESIDUE_NEW" PRIMARY KEY ("EM_TR_NUM_RESIDUE_NEW_ID") ENABLE,
 CONSTRAINT "FK_EM_TR_NM_RSDUE_NW_EM_EMNFST" FOREIGN KEY ("EM_EMANIFEST_ID")
  REFERENCES "RCRA_EM_EMANIFEST" ("EM_EMANIFEST_ID") ON DELETE CASCADE ENABLE
   );
---------------------------
--Changed TABLE
--RCRA_EM_TR_NUM_REJ
---------------------------
DROP TABLE "RCRA_EM_TR_NUM_REJ";
  CREATE TABLE "RCRA_EM_TR_NUM_REJ" 
   ( "EM_TR_NUM_REJ_ID" VARCHAR2(40) NOT NULL ENABLE,
 "EM_EMANIFEST_ID" VARCHAR2(40) NOT NULL ENABLE,
 "MANIFEST_TRACKING_NUM" VARCHAR2(12) NOT NULL ENABLE,
 CONSTRAINT "PK_EM_TR_NUM_REJ" PRIMARY KEY ("EM_TR_NUM_REJ_ID") ENABLE,
 CONSTRAINT "FK_EM_TR_NUM_REJ_EM_EMANIFEST" FOREIGN KEY ("EM_EMANIFEST_ID")
  REFERENCES "RCRA_EM_EMANIFEST" ("EM_EMANIFEST_ID") ON DELETE CASCADE ENABLE
   );
---------------------------
--Changed TABLE
--RCRA_EM_TR_NUM_ORIG
---------------------------
DROP TABLE "RCRA_EM_TR_NUM_ORIG";
  CREATE TABLE "RCRA_EM_TR_NUM_ORIG" 
   ( "EM_TR_NUM_ORIG_ID" VARCHAR2(40) NOT NULL ENABLE,
 "EM_EMANIFEST_ID" VARCHAR2(40) NOT NULL ENABLE,
 "MANIFEST_TRACKING_NUM" VARCHAR2(12) NOT NULL ENABLE,
 CONSTRAINT "PK_EM_TR_NUM_ORIG" PRIMARY KEY ("EM_TR_NUM_ORIG_ID") ENABLE,
 CONSTRAINT "FK_EM_TR_NUM_ORIG_EM_EMANIFEST" FOREIGN KEY ("EM_EMANIFEST_ID")
  REFERENCES "RCRA_EM_EMANIFEST" ("EM_EMANIFEST_ID") ON DELETE CASCADE ENABLE
   );
---------------------------
--Changed TABLE
--RCRA_EM_EMANIFEST
---------------------------
ALTER TABLE "RCRA_EM_EMANIFEST" MODIFY ("IMP_GEN_CITY" VARCHAR2(100));
ALTER TABLE "RCRA_EM_EMANIFEST" MODIFY ("IMP_PORT_CITY" VARCHAR2(100));
ALTER TABLE "RCRA_EM_EMANIFEST" MODIFY ("RESIDUE_IND" NULL);

---------------------------
--Changed TABLE
--RCRA_CME_VIOL_ENFRC
---------------------------
ALTER TABLE "RCRA_CME_VIOL_ENFRC" MODIFY ("RTN_COMPL_SCHD_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_CME_VIOL
---------------------------
ALTER TABLE "RCRA_CME_VIOL" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_CME_VIOL" ADD ("C_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_VIOL" MODIFY ("RTN_COMPL_ACTL_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_VIOL" MODIFY ("VIOL_DTRM_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_CME_SUPP_ENVR_PRJT
---------------------------
ALTER TABLE "RCRA_CME_SUPP_ENVR_PRJT" MODIFY ("SEP_ACTL_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_SUPP_ENVR_PRJT" MODIFY ("SEP_DFLT_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_SUPP_ENVR_PRJT" MODIFY ("SEP_SCHD_COMP_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_CME_RQST
---------------------------
ALTER TABLE "RCRA_CME_RQST" MODIFY ("DATE_OF_RQST" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_RQST" MODIFY ("DATE_RESP_RCVD" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_CME_PYMT
---------------------------
ALTER TABLE "RCRA_CME_PYMT" MODIFY ("ACTL_PYMT_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_PYMT" MODIFY ("PYMT_DFLT_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_PYMT" MODIFY ("SCHD_PYMT_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_CME_MILESTONE
---------------------------
ALTER TABLE "RCRA_CME_MILESTONE" MODIFY ("MILESTONE_ACTL_COMP_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_MILESTONE" MODIFY ("MILESTONE_DFLT_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_MILESTONE" MODIFY ("MILESTONE_SCHD_COMP_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_CME_EVAL
---------------------------
ALTER TABLE "RCRA_CME_EVAL" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_CME_EVAL" ADD ("C_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_EVAL" ADD ("DATA_ORIG" CHAR(2));
ALTER TABLE "RCRA_CME_EVAL" MODIFY ("DAY_ZERO" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_EVAL" MODIFY ("EVAL_START_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_EVAL" MODIFY ("NOC_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_CME_ENFRC_ACT
---------------------------
ALTER TABLE "RCRA_CME_ENFRC_ACT" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_CME_ENFRC_ACT" ADD ("C_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_ENFRC_ACT" ADD ("DATA_ORIG" CHAR(2));
ALTER TABLE "RCRA_CME_ENFRC_ACT" MODIFY ("APPEAL_INIT_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_ENFRC_ACT" MODIFY ("APPEAL_RSLN_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_ENFRC_ACT" MODIFY ("DISP_STAT_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CME_ENFRC_ACT" MODIFY ("ENFRC_ACT_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_CME_CSNY_DATE
---------------------------
ALTER TABLE "RCRA_CME_CSNY_DATE" MODIFY ("SNY_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_CA_REL_PERMIT_UNIT
---------------------------
ALTER TABLE "RCRA_CA_REL_PERMIT_UNIT" MODIFY ("PERMIT_UNIT_SEQ_NUM" NULL);

---------------------------
--Changed TABLE
--RCRA_CA_EVENT
---------------------------
ALTER TABLE "RCRA_CA_EVENT" ADD ("A_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CA_EVENT" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_CA_EVENT" ADD ("DATA_ORIG" CHAR(2));
ALTER TABLE "RCRA_CA_EVENT" ADD ("PUBLIC_SUPP_INFO_TXT" VARCHAR2(2000));
ALTER TABLE "RCRA_CA_EVENT" MODIFY ("ACTL_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CA_EVENT" MODIFY ("NEW_SCHEDULE_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CA_EVENT" MODIFY ("ORIGINAL_SCHEDULE_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_CA_AUTHORITY
---------------------------
ALTER TABLE "RCRA_CA_AUTHORITY" ADD ("A_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CA_AUTHORITY" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_CA_AUTHORITY" ADD ("DATA_ORIG" CHAR(2));
ALTER TABLE "RCRA_CA_AUTHORITY" MODIFY ("AUTHORITY_EFFC_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CA_AUTHORITY" MODIFY ("END_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CA_AUTHORITY" MODIFY ("ISSUE_DATE" TIMESTAMP(6));

---------------------------
--Changed TABLE
--RCRA_CA_AREA
---------------------------
ALTER TABLE "RCRA_CA_AREA" ADD ("A_CREATED_DATE" TIMESTAMP(6));
ALTER TABLE "RCRA_CA_AREA" ADD ("CREATED_BY_USERID" VARCHAR2(255));
ALTER TABLE "RCRA_CA_AREA" ADD ("DATA_ORIG" CHAR(2));
ALTER TABLE "RCRA_CA_AREA" MODIFY ("AREA_SEQ_NUM" NULL);

---------------------------
--New INDEX
--PK_PRM_MOD_EVENT
---------------------------
 -- CREATE UNIQUE INDEX "PK_PRM_MOD_EVENT" ON "RCRA_PRM_MOD_EVENT" ("PRM_MOD_EVENT_ID");
---------------------------
--New INDEX
--IX_PRM_MOD_EVENT_PRM_EVENT_ID
---------------------------
  CREATE INDEX "IX_PRM_MOD_EVENT_PRM_EVENT_ID" ON "RCRA_PRM_MOD_EVENT" ("PRM_EVENT_ID");