/*
Copyright (c) 2016, The Environmental Council of the States (ECOS)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE goODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/

/*****************************************************************************************************************************
 *
 *  Script Name:  RCRA_5.7_to_5.9-upgrade_SQL-DDL.sql
 *
 *  Company:  Windsor Solutions, Inc.
 *
 *  Purpose:  This script will upgrade RCRA 5.7 schema to support RCRA 5.9.
 *
 *  Maintenance:
 *
 *    Analyst         Date            Comment
 *    ----------      ----------      ------------------------------------------------------------------------------
 *    Windsor         10/06/2020      Created
 *
 ****************************************************************************************************************************
 */
 ---$ Alter table dbo.RCRA_CA_AREA
ALTER TABLE dbo.RCRA_CA_AREA
    ALTER COLUMN AREA_SEQ_NUM INT NULL
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AREA') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AREA
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AREA') AND NAME = 'A_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AREA
        ADD A_CREATED_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AREA') AND NAME = 'DATA_ORIG')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AREA
        ADD DATA_ORIG CHAR(2) NULL
END
GO


---$ Alter table dbo.RCRA_CA_AUTHORITY
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AUTHORITY') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AUTHORITY
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AUTHORITY') AND NAME = 'A_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AUTHORITY
        ADD A_CREATED_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AUTHORITY') AND NAME = 'DATA_ORIG')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AUTHORITY
        ADD DATA_ORIG CHAR(2) NULL
END
GO


---$ Alter table dbo.RCRA_CA_EVENT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT') AND NAME = 'PUBLIC_SUPP_INFO_TXT')
BEGIN
    ALTER TABLE dbo.RCRA_CA_EVENT
        ADD PUBLIC_SUPP_INFO_TXT VARCHAR(2000) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_CA_EVENT
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT') AND NAME = 'A_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CA_EVENT
        ADD A_CREATED_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT') AND NAME = 'DATA_ORIG')
BEGIN
    ALTER TABLE dbo.RCRA_CA_EVENT
        ADD DATA_ORIG CHAR(2) NULL
END
GO


---$ Alter table dbo.RCRA_CA_REL_PERMIT_UNIT
ALTER TABLE dbo.RCRA_CA_REL_PERMIT_UNIT
    ALTER COLUMN PERMIT_UNIT_SEQ_NUM INT NULL
GO


---$ Alter table dbo.RCRA_CME_ENFRC_ACT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_ENFRC_ACT') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_ENFRC_ACT') AND NAME = 'C_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
        ADD C_CREATED_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_ENFRC_ACT') AND NAME = 'DATA_ORIG')
BEGIN
    ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
        ADD DATA_ORIG CHAR(2) NULL
END
GO


---$ Alter table dbo.RCRA_CME_EVAL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_CME_EVAL
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL') AND NAME = 'C_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CME_EVAL
        ADD C_CREATED_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL') AND NAME = 'DATA_ORIG')
BEGIN
    ALTER TABLE dbo.RCRA_CME_EVAL
        ADD DATA_ORIG CHAR(2) NULL
END
GO


---$ Alter table dbo.RCRA_CME_VIOL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_VIOL') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_CME_VIOL
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_VIOL') AND NAME = 'C_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CME_VIOL
        ADD C_CREATED_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_EM_EMANIFEST
ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN RESIDUE_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN IMP_GEN_CITY VARCHAR(100) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN IMP_PORT_CITY VARCHAR(100) NULL
GO


---$ Alter table dbo.RCRA_EM_TR_NUM_ORIG
IF OBJECT_ID(N'dbo.DF_EM_TR_NUM_ORIG_ID') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_EM_TR_NUM_ORIG DROP CONSTRAINT DF_EM_TR_NUM_ORIG_ID
END
GO


---$ Alter table dbo.RCRA_EM_TR_NUM_REJ
IF OBJECT_ID(N'dbo.DF_EM_TR_NUM_REJ_ID') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_EM_TR_NUM_REJ DROP CONSTRAINT DF_EM_TR_NUM_REJ_ID
END
GO


---$ Alter table dbo.RCRA_EM_TR_NUM_RESIDUE_NEW
IF OBJECT_ID(N'dbo.DF_EM_TR_NUM_RESIDUE_NEW_ID') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_EM_TR_NUM_RESIDUE_NEW DROP CONSTRAINT DF_EM_TR_NUM_RESIDUE_NEW_ID
END
GO


---$ Alter table dbo.RCRA_EM_TR_NUM_WASTE
IF OBJECT_ID(N'dbo.DF_EM_TR_NUM_WASTE_ID') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_EM_TR_NUM_WASTE DROP CONSTRAINT DF_EM_TR_NUM_WASTE_ID
END
GO


---$ Alter table dbo.RCRA_EM_WASTE_CD_TRANS
IF OBJECT_ID(N'dbo.DF_EM_WASTE_CD_TRANS_ID') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_EM_WASTE_CD_TRANS DROP CONSTRAINT DF_EM_WASTE_CD_TRANS_ID
END
GO


---$ Alter table dbo.RCRA_FA_COST_EST
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'F_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST
        ADD F_CREATED_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'DATA_ORIG')
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST
        ADD DATA_ORIG CHAR(2) NULL
END
GO


---$ Alter table dbo.RCRA_FA_MECHANISM
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'F_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM
        ADD F_CREATED_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'DATA_ORIG')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM
        ADD DATA_ORIG CHAR(2) NULL
END
GO


---$ Alter table dbo.RCRA_FA_MECHANISM_DETAIL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'CURRENT_MECHANISM_DETAIL_IND')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD CURRENT_MECHANISM_DETAIL_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'F_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD F_CREATED_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'DATA_ORIG')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD DATA_ORIG CHAR(2) NULL
END
GO


---$ Alter table dbo.RCRA_GIS_GEO_INFORMATION
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_GIS_GEO_INFORMATION') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_GIS_GEO_INFORMATION
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_GIS_GEO_INFORMATION') AND NAME = 'G_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_GIS_GEO_INFORMATION
        ADD G_CREATED_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_GIS_GEO_INFORMATION') AND NAME = 'DATA_ORIG')
BEGIN
    ALTER TABLE dbo.RCRA_GIS_GEO_INFORMATION
        ADD DATA_ORIG CHAR(2) NULL
END
GO


---$ Alter table dbo.RCRA_HD_HANDLER
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'CURRENT_RECORD')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD CURRENT_RECORD CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'H_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD H_CREATED_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'DATA_ORIG')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD DATA_ORIG CHAR(2) NULL
END
GO


---$ Alter table dbo.RCRA_PRM_EVENT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_EVENT') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_EVENT
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_EVENT') AND NAME = 'P_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_EVENT
        ADD P_CREATED_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_PRM_SERIES
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_SERIES') AND NAME = 'ACTIVE_SERIES_IND')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_SERIES
        ADD ACTIVE_SERIES_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_SERIES') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_SERIES
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_SERIES') AND NAME = 'P_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_SERIES
        ADD P_CREATED_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_PRM_UNIT
ALTER TABLE dbo.RCRA_PRM_UNIT
    ALTER COLUMN PERMIT_UNIT_SEQ_NUM INT NULL
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT') AND NAME = 'ACTIVE_UNIT_IND')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT
        ADD ACTIVE_UNIT_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT') AND NAME = 'P_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT
        ADD P_CREATED_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_PRM_UNIT_DETAIL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT_DETAIL') AND NAME = 'CURRENT_UNIT_DETAIL_IND')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT_DETAIL
        ADD CURRENT_UNIT_DETAIL_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT_DETAIL') AND NAME = 'CREATED_BY_USERID')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT_DETAIL
        ADD CREATED_BY_USERID VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT_DETAIL') AND NAME = 'P_CREATED_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT_DETAIL
        ADD P_CREATED_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_RU_REPORT_UNIV
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_RU_REPORT_UNIV') AND NAME = 'SUBPART_P_IND')
BEGIN
    ALTER TABLE dbo.RCRA_RU_REPORT_UNIV
        ADD SUBPART_P_IND CHAR(1) NULL
END
GO


---$ Create table dbo.RCRA_PRM_MOD_EVENT
IF OBJECT_ID(N'dbo.RCRA_PRM_MOD_EVENT') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_PRM_MOD_EVENT
    (
        PRM_MOD_EVENT_ID VARCHAR(40) NOT NULL,
        PRM_EVENT_ID VARCHAR(40) NOT NULL,
        TRANS_CODE CHAR(1) NULL,
        MOD_HANDLER_ID VARCHAR(12) NOT NULL,
        MOD_ACT_LOC_CODE VARCHAR(50) NOT NULL,
        MOD_SERIES_SEQ_NUM INT NOT NULL,
        MOD_EVENT_SEQ_NUM INT NOT NULL,
        MOD_EVENT_AGN_CODE CHAR(1) NOT NULL,
        MOD_EVENT_DATA_OWNER_CODE CHAR(2) NOT NULL,
        MOD_EVENT_CODE VARCHAR(7) NOT NULL
    )
    END
GO


