/****** Object:  Table [dbo].[OWIR_ASMT_METH_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_ASMT_METH_DTLS](
	[ASMT_METH_DTLS_ID] [varchar](40) NOT NULL,
	[WQS_ATTAIN_DTLS_ID] [varchar](40) NOT NULL,
	[ASMT_METH_IDEN_CODE] [int] NOT NULL,
 CONSTRAINT [PK_ASMT_METH_DTLS] PRIMARY KEY CLUSTERED 
(
	[ASMT_METH_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_ASMT_TYPE_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_ASMT_TYPE_DTLS](
	[ASMT_TYPE_DTLS_ID] [varchar](40) NOT NULL,
	[WQS_ATTAIN_DTLS_ID] [varchar](40) NOT NULL,
	[ASMT_TYPE_TYPE] [varchar](30) NOT NULL,
	[ASMT_CONFIDENCE] [varchar](9) NULL,
 CONSTRAINT [PK_ASMT_TYPE_DTLS] PRIMARY KEY CLUSTERED 
(
	[ASMT_TYPE_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_ASMT_UNIT_CAUSE_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_ASMT_UNIT_CAUSE_DTLS](
	[ASMT_UNIT_CAUSE_DTLS_ID] [varchar](40) NOT NULL,
	[ASMT_UNIT_DTLS_ID] [varchar](40) NOT NULL,
	[CAUSE_NAME] [varchar](240) NOT NULL,
	[CYCLE_FIRST_LISTED] [int] NULL,
	[EXPECTED_TO_ATTAIN_DATE] [datetime] NULL,
	[TMDL_SCHEDULE] [int] NULL,
	[TMDL_PRI] [varchar](6) NULL,
	[TMDL_COMP_DATE] [datetime] NULL,
	[TMDL_PRJT_STAT] [varchar](255) NULL,
	[TMDL_PRJT_COMMENT] [varchar](4000) NULL,
	[CNST_DECREE_CYCLE] [int] NULL,
	[POLLUTION_SRC_TYPE] [varchar](16) NULL,
	[JUSTIFICATION_URL] [varchar](250) NULL,
	[OTHER_PT_SRC_ID] [varchar](4000) NULL,
 CONSTRAINT [PK_ASMT_UNIT_CAUSE_DTLS] PRIMARY KEY CLUSTERED 
(
	[ASMT_UNIT_CAUSE_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_ASMT_UNIT_DELIST_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_ASMT_UNIT_DELIST_DTLS](
	[ASMT_UNIT_DELIST_DTLS_ID] [varchar](40) NOT NULL,
	[ASMT_UNIT_DTLS_ID] [varchar](40) NOT NULL,
	[CAUSE_NAME] [varchar](240) NOT NULL,
	[DELISTING_DATE] [datetime] NULL,
	[DELISTING_REASON] [varchar](120) NOT NULL,
	[DELISTING_COMMENT] [varchar](4000) NULL,
 CONSTRAINT [PK_ASMT_UNIT_DELIST_DTLS] PRIMARY KEY CLUSTERED 
(
	[ASMT_UNIT_DELIST_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_ASMT_UNIT_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_ASMT_UNIT_DTLS](
	[ASMT_UNIT_DTLS_ID] [varchar](40) NOT NULL,
	[STATE_ASMT_DTLS_ID] [varchar](40) NOT NULL,
	[ID_305B] [varchar](50) NOT NULL,
	[WATER_NAME] [varchar](60) NOT NULL,
	[LOC] [varchar](255) NOT NULL,
	[TROPHIC_STAT] [varchar](14) NULL,
	[PUBLIC_LAKE] [varchar](3) NULL,
	[MONTR_SCHD_YEAR] [int] NULL,
	[CLASS_NAME] [varchar](100) NULL,
	[CLASS_DESC] [varchar](4000) NULL,
	[ASSESSOR] [varchar](40) NULL,
	[CATG_ID] [varchar](10) NULL,
	[EPA_CATG] [varchar](6) NULL,
	[ASMT_UNIT_COMMENT] [varchar](4000) NULL,
	[ASMT_UNIT_OWNER] [varchar](20) NULL,
	[CYCLE_LAST_ASSESSED] [int] NULL,
	[TREND] [varchar](11) NULL,
	[CATG_REPORT_FLAG] [varchar](15) NULL,
	[EPA_ADDED_ASMT_UNIT] [char](1) NULL,
	[ASSESSED] [char](1) NULL,
 CONSTRAINT [PK_ASMT_UNIT_DTLS] PRIMARY KEY CLUSTERED 
(
	[ASMT_UNIT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_ASMT_WATER_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_ASMT_WATER_DTLS](
	[ASMT_WATER_DTLS_ID] [varchar](40) NOT NULL,
	[ASMT_UNIT_DTLS_ID] [varchar](40) NOT NULL,
	[WATER_TYPE] [varchar](23) NOT NULL,
	[WATER_SIZE] [decimal](14, 6) NOT NULL,
 CONSTRAINT [PK_ASMT_WATER_DTLS] PRIMARY KEY CLUSTERED 
(
	[ASMT_WATER_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_ATLAS_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_ATLAS_DTLS](
	[ATLAS_DTLS_ID] [varchar](40) NOT NULL,
	[STATE_ASMT_DTLS_ID] [varchar](40) NOT NULL,
	[TOPIC_ID] [int] NOT NULL,
	[TOPIC_OWNER] [varchar](255) NOT NULL,
	[TOPIC_SIZE] [decimal](14, 6) NULL,
	[TOPIC_SCALE] [int] NULL,
	[TOPIC_SRC] [varchar](40) NULL,
	[TOPIC_COUNT] [int] NULL,
	[TOPIC_NAME] [varchar](50) NULL,
	[TOPIC_GROUP] [varchar](50) NULL,
	[TOPIC_SIZE_UNIT] [varchar](15) NULL,
	[TOPIC_MAJOR_FLAG] [int] NULL,
 CONSTRAINT [PK_ATLAS_DTLS] PRIMARY KEY CLUSTERED 
(
	[ATLAS_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_CAUSE_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_CAUSE_DTLS](
	[CAUSE_DTLS_ID] [varchar](40) NOT NULL,
	[WQS_ATTAIN_DTLS_ID] [varchar](40) NOT NULL,
	[CAUSE_NAME] [varchar](240) NOT NULL,
	[POLT_FLAG] [varchar](3) NULL,
	[CAUSE_COMMENT] [varchar](4000) NULL,
	[USER_FLAG] [varchar](15) NULL,
	[EPA_CAUSE_CATG] [varchar](6) NULL,
	[CONFIDENCE] [varchar](6) NULL,
	[STATE_CAUSE_CATG] [varchar](10) NULL,
	[EPA_ADDED_CAUSE] [char](1) NULL,
 CONSTRAINT [PK_CAUSE_DTLS] PRIMARY KEY CLUSTERED 
(
	[CAUSE_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_CYCLE_TRACK_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_CYCLE_TRACK_DTLS](
	[CYCLE_TRACK_DTLS_ID] [varchar](40) NOT NULL,
	[ASMT_UNIT_DTLS_ID] [varchar](40) NOT NULL,
	[PRE_ID_305B] [varchar](50) NOT NULL,
	[PRE_CYCLE] [int] NOT NULL,
	[PURPOSE] [varchar](6) NOT NULL,
 CONSTRAINT [PK_CYCLE_TRACK_DTLS] PRIMARY KEY CLUSTERED 
(
	[CYCLE_TRACK_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_IMPL_ACT_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_IMPL_ACT_DTLS](
	[IMPL_ACT_DTLS_ID] [varchar](40) NOT NULL,
	[ASMT_UNIT_CAUSE_DTLS_ID] [varchar](40) NOT NULL,
	[ACT_DATE] [datetime] NOT NULL,
	[IMPL_ACT_TXT] [varchar](255) NULL,
 CONSTRAINT [PK_IMPL_ACT_DTLS] PRIMARY KEY CLUSTERED 
(
	[IMPL_ACT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_NPDES_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_NPDES_DTLS](
	[NPDES_DTLS_ID] [varchar](40) NOT NULL,
	[ASMT_UNIT_CAUSE_DTLS_ID] [varchar](40) NOT NULL,
	[NPDESID] [varchar](9) NULL,
 CONSTRAINT [PK_NPDES_DTLS] PRIMARY KEY CLUSTERED 
(
	[NPDES_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_OBSERVED_EFFECT_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_OBSERVED_EFFECT_DTLS](
	[OBSERVED_EFFECT_DTLS_ID] [varchar](40) NOT NULL,
	[WQS_ATTAIN_DTLS_ID] [varchar](40) NOT NULL,
	[CAUSE_NAME] [varchar](240) NOT NULL,
 CONSTRAINT [PK_OBSERVED_EFFECT_DTLS] PRIMARY KEY CLUSTERED 
(
	[OBSERVED_EFFECT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_SRC_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_SRC_DTLS](
	[SRC_DTLS_ID] [varchar](40) NOT NULL,
	[CAUSE_DTLS_ID] [varchar](40) NOT NULL,
	[SRC_NAME] [varchar](250) NOT NULL,
	[SRC_COMMENT] [varchar](4000) NULL,
	[CONFIRMED] [char](1) NULL,
 CONSTRAINT [PK_SRC_DTLS] PRIMARY KEY CLUSTERED 
(
	[SRC_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_STATE_ASMT_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_STATE_ASMT_DTLS](
	[STATE_ASMT_DTLS_ID] [varchar](40) NOT NULL,
	[CYCLE] [int] NOT NULL,
	[MERCURY_COMMENT] [varchar](4000) NULL,
	[MERCURY_URL] [varchar](250) NULL,
	[STATE_CODE] [varchar](50) NULL,
	[STATE_NAME] [varchar](128) NULL,
	[CODE_LIST_VERS_IDEN] [varchar](50) NULL,
	[CODE_LIST_VERS_AGN_IDEN] [varchar](50) NULL,
	[VAL] [varchar](50) NULL,
 CONSTRAINT [PK_STATE_ASMT_DTLS] PRIMARY KEY CLUSTERED 
(
	[STATE_ASMT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_STATE_LOC_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_STATE_LOC_DTLS](
	[STATE_LOC_DTLS_ID] [varchar](40) NOT NULL,
	[STATE_ASMT_DTLS_ID] [varchar](40) NOT NULL,
	[LOC_ID] [int] NOT NULL,
	[LOC_TYPE] [varchar](20) NOT NULL,
	[LOC_NAME] [varchar](100) NOT NULL,
 CONSTRAINT [PK_STATE_LOC_DTLS] PRIMARY KEY CLUSTERED 
(
	[STATE_LOC_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_STATE_METH_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_STATE_METH_DTLS](
	[STATE_METH_DTLS_ID] [varchar](40) NOT NULL,
	[STATE_ASMT_DTLS_ID] [varchar](40) NOT NULL,
	[ASMT_METH_IDEN_CODE] [int] NOT NULL,
	[ASMT_METH_NAME] [varchar](90) NOT NULL,
 CONSTRAINT [PK_STATE_METH_DTLS] PRIMARY KEY CLUSTERED 
(
	[STATE_METH_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_TMD_LS_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_TMD_LS_DTLS](
	[TMD_LS_DTLS_ID] [varchar](40) NOT NULL,
	[ASMT_UNIT_CAUSE_DTLS_ID] [varchar](40) NOT NULL,
	[TMDLID] [int] NOT NULL,
 CONSTRAINT [PK_TMD_LS_DTLS] PRIMARY KEY CLUSTERED 
(
	[TMD_LS_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_USER_CATG_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_USER_CATG_DTLS](
	[USER_CATG_DTLS_ID] [varchar](40) NOT NULL,
	[STATE_ASMT_DTLS_ID] [varchar](40) NOT NULL,
	[CATG_ID] [varchar](10) NULL,
	[CATG_DESC] [varchar](4000) NOT NULL,
 CONSTRAINT [PK_USER_CATG_DTLS] PRIMARY KEY CLUSTERED 
(
	[USER_CATG_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[OWIR_WQS_ATTAIN_DTLS]    Script Date: 9/15/2011 12:47:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OWIR_WQS_ATTAIN_DTLS](
	[WQS_ATTAIN_DTLS_ID] [varchar](40) NOT NULL,
	[ASMT_UNIT_DTLS_ID] [varchar](40) NOT NULL,
	[USE_DESC] [varchar](4000) NOT NULL,
	[ATTAIN_DESC] [varchar](24) NOT NULL,
	[THREATENED_FLAG] [varchar](3) NULL,
	[USE_COMMENT] [varchar](4000) NULL,
	[ASMT_DATE] [datetime] NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[KEY_DATE] [datetime] NULL,
	[ASSESSOR] [varchar](40) NULL,
	[EPA_ADDED_ATTAIN] [char](1) NULL,
	[STATE_USE_CATG] [varchar](10) NULL,
	[EPA_USE_CATG] [varchar](6) NULL,
 CONSTRAINT [PK_WQS_ATTAIN_DTLS] PRIMARY KEY CLUSTERED 
(
	[WQS_ATTAIN_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_ASMT_MTH_DTL_WQS_ATT_DTL_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_ASMT_MTH_DTL_WQS_ATT_DTL_ID] ON [dbo].[OWIR_ASMT_METH_DTLS]
(
	[WQS_ATTAIN_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_ASMT_TYP_DTL_WQS_ATT_DTL_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_ASMT_TYP_DTL_WQS_ATT_DTL_ID] ON [dbo].[OWIR_ASMT_TYPE_DTLS]
(
	[WQS_ATTAIN_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_ASM_UNT_CSE_DTL_AS_UN_DT_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_ASM_UNT_CSE_DTL_AS_UN_DT_ID] ON [dbo].[OWIR_ASMT_UNIT_CAUSE_DTLS]
(
	[ASMT_UNIT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_ASM_UNT_DLS_DTL_AS_UN_DT_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_ASM_UNT_DLS_DTL_AS_UN_DT_ID] ON [dbo].[OWIR_ASMT_UNIT_DELIST_DTLS]
(
	[ASMT_UNIT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_ASMT_UNT_DTL_STT_ASM_DTL_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_ASMT_UNT_DTL_STT_ASM_DTL_ID] ON [dbo].[OWIR_ASMT_UNIT_DTLS]
(
	[STATE_ASMT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_ASMT_WTR_DTL_ASM_UNT_DTL_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_ASMT_WTR_DTL_ASM_UNT_DTL_ID] ON [dbo].[OWIR_ASMT_WATER_DTLS]
(
	[ASMT_UNIT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_ATLS_DTLS_STTE_ASMT_DTLS_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_ATLS_DTLS_STTE_ASMT_DTLS_ID] ON [dbo].[OWIR_ATLAS_DTLS]
(
	[STATE_ASMT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_CUSE_DTLS_WQS_ATTIN_DTLS_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_CUSE_DTLS_WQS_ATTIN_DTLS_ID] ON [dbo].[OWIR_CAUSE_DTLS]
(
	[WQS_ATTAIN_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_CYCL_TRC_DTL_ASM_UNT_DTL_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_CYCL_TRC_DTL_ASM_UNT_DTL_ID] ON [dbo].[OWIR_CYCLE_TRACK_DTLS]
(
	[ASMT_UNIT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_IMP_ACT_DTL_ASM_UN_CS_DT_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_IMP_ACT_DTL_ASM_UN_CS_DT_ID] ON [dbo].[OWIR_IMPL_ACT_DTLS]
(
	[ASMT_UNIT_CAUSE_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_NPDS_DTL_ASM_UNT_CSE_DTL_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_NPDS_DTL_ASM_UNT_CSE_DTL_ID] ON [dbo].[OWIR_NPDES_DTLS]
(
	[ASMT_UNIT_CAUSE_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_OBSR_EFF_DTL_WQS_ATT_DTL_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_OBSR_EFF_DTL_WQS_ATT_DTL_ID] ON [dbo].[OWIR_OBSERVED_EFFECT_DTLS]
(
	[WQS_ATTAIN_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_SRC_DTLS_CAUSE_DTLS_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_SRC_DTLS_CAUSE_DTLS_ID] ON [dbo].[OWIR_SRC_DTLS]
(
	[CAUSE_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_STTE_LC_DTLS_STT_ASM_DTL_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_STTE_LC_DTLS_STT_ASM_DTL_ID] ON [dbo].[OWIR_STATE_LOC_DTLS]
(
	[STATE_ASMT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_STTE_MTH_DTL_STT_ASM_DTL_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_STTE_MTH_DTL_STT_ASM_DTL_ID] ON [dbo].[OWIR_STATE_METH_DTLS]
(
	[STATE_ASMT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_TMD_LS_DTL_ASM_UNT_CS_DT_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_TMD_LS_DTL_ASM_UNT_CS_DT_ID] ON [dbo].[OWIR_TMD_LS_DTLS]
(
	[ASMT_UNIT_CAUSE_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_USR_CTG_DTLS_STT_ASM_DTL_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_USR_CTG_DTLS_STT_ASM_DTL_ID] ON [dbo].[OWIR_USER_CATG_DTLS]
(
	[STATE_ASMT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_WQS_ATTN_DTL_ASM_UNT_DTL_ID]    Script Date: 9/15/2011 12:47:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_WQS_ATTN_DTL_ASM_UNT_DTL_ID] ON [dbo].[OWIR_WQS_ATTAIN_DTLS]
(
	[ASMT_UNIT_DTLS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OWIR_ASMT_METH_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_ASMT_MTH_DTLS_WQS_ATTN_DTLS] FOREIGN KEY([WQS_ATTAIN_DTLS_ID])
REFERENCES [dbo].[OWIR_WQS_ATTAIN_DTLS] ([WQS_ATTAIN_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_ASMT_METH_DTLS] CHECK CONSTRAINT [FK_ASMT_MTH_DTLS_WQS_ATTN_DTLS]
GO
ALTER TABLE [dbo].[OWIR_ASMT_TYPE_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_ASMT_TYPE_DTLS_WQS_ATTN_DTL] FOREIGN KEY([WQS_ATTAIN_DTLS_ID])
REFERENCES [dbo].[OWIR_WQS_ATTAIN_DTLS] ([WQS_ATTAIN_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_ASMT_TYPE_DTLS] CHECK CONSTRAINT [FK_ASMT_TYPE_DTLS_WQS_ATTN_DTL]
GO
ALTER TABLE [dbo].[OWIR_ASMT_UNIT_CAUSE_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_ASM_UNT_CSE_DTL_ASM_UNT_DTL] FOREIGN KEY([ASMT_UNIT_DTLS_ID])
REFERENCES [dbo].[OWIR_ASMT_UNIT_DTLS] ([ASMT_UNIT_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_ASMT_UNIT_CAUSE_DTLS] CHECK CONSTRAINT [FK_ASM_UNT_CSE_DTL_ASM_UNT_DTL]
GO
ALTER TABLE [dbo].[OWIR_ASMT_UNIT_DELIST_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_ASM_UNT_DLS_DTL_ASM_UNT_DTL] FOREIGN KEY([ASMT_UNIT_DTLS_ID])
REFERENCES [dbo].[OWIR_ASMT_UNIT_DTLS] ([ASMT_UNIT_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_ASMT_UNIT_DELIST_DTLS] CHECK CONSTRAINT [FK_ASM_UNT_DLS_DTL_ASM_UNT_DTL]
GO
ALTER TABLE [dbo].[OWIR_ASMT_UNIT_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_ASMT_UNT_DTLS_STTE_ASMT_DTL] FOREIGN KEY([STATE_ASMT_DTLS_ID])
REFERENCES [dbo].[OWIR_STATE_ASMT_DTLS] ([STATE_ASMT_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_ASMT_UNIT_DTLS] CHECK CONSTRAINT [FK_ASMT_UNT_DTLS_STTE_ASMT_DTL]
GO
ALTER TABLE [dbo].[OWIR_ASMT_WATER_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_ASMT_WTR_DTLS_ASMT_UNT_DTLS] FOREIGN KEY([ASMT_UNIT_DTLS_ID])
REFERENCES [dbo].[OWIR_ASMT_UNIT_DTLS] ([ASMT_UNIT_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_ASMT_WATER_DTLS] CHECK CONSTRAINT [FK_ASMT_WTR_DTLS_ASMT_UNT_DTLS]
GO
ALTER TABLE [dbo].[OWIR_ATLAS_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_ATLAS_DTLS_STATE_ASMT_DTLS] FOREIGN KEY([STATE_ASMT_DTLS_ID])
REFERENCES [dbo].[OWIR_STATE_ASMT_DTLS] ([STATE_ASMT_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_ATLAS_DTLS] CHECK CONSTRAINT [FK_ATLAS_DTLS_STATE_ASMT_DTLS]
GO
ALTER TABLE [dbo].[OWIR_CAUSE_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_CAUSE_DTLS_WQS_ATTAIN_DTLS] FOREIGN KEY([WQS_ATTAIN_DTLS_ID])
REFERENCES [dbo].[OWIR_WQS_ATTAIN_DTLS] ([WQS_ATTAIN_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_CAUSE_DTLS] CHECK CONSTRAINT [FK_CAUSE_DTLS_WQS_ATTAIN_DTLS]
GO
ALTER TABLE [dbo].[OWIR_CYCLE_TRACK_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_CYCL_TRCK_DTLS_ASMT_UNT_DTL] FOREIGN KEY([ASMT_UNIT_DTLS_ID])
REFERENCES [dbo].[OWIR_ASMT_UNIT_DTLS] ([ASMT_UNIT_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_CYCLE_TRACK_DTLS] CHECK CONSTRAINT [FK_CYCL_TRCK_DTLS_ASMT_UNT_DTL]
GO
ALTER TABLE [dbo].[OWIR_IMPL_ACT_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_IMP_ACT_DTL_ASM_UNT_CSE_DTL] FOREIGN KEY([ASMT_UNIT_CAUSE_DTLS_ID])
REFERENCES [dbo].[OWIR_ASMT_UNIT_CAUSE_DTLS] ([ASMT_UNIT_CAUSE_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_IMPL_ACT_DTLS] CHECK CONSTRAINT [FK_IMP_ACT_DTL_ASM_UNT_CSE_DTL]
GO
ALTER TABLE [dbo].[OWIR_NPDES_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_NPDS_DTLS_ASMT_UNT_CSE_DTLS] FOREIGN KEY([ASMT_UNIT_CAUSE_DTLS_ID])
REFERENCES [dbo].[OWIR_ASMT_UNIT_CAUSE_DTLS] ([ASMT_UNIT_CAUSE_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_NPDES_DTLS] CHECK CONSTRAINT [FK_NPDS_DTLS_ASMT_UNT_CSE_DTLS]
GO
ALTER TABLE [dbo].[OWIR_OBSERVED_EFFECT_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_OBSR_EFFC_DTLS_WQS_ATTN_DTL] FOREIGN KEY([WQS_ATTAIN_DTLS_ID])
REFERENCES [dbo].[OWIR_WQS_ATTAIN_DTLS] ([WQS_ATTAIN_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_OBSERVED_EFFECT_DTLS] CHECK CONSTRAINT [FK_OBSR_EFFC_DTLS_WQS_ATTN_DTL]
GO
ALTER TABLE [dbo].[OWIR_SRC_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_SRC_DTLS_CAUSE_DTLS] FOREIGN KEY([CAUSE_DTLS_ID])
REFERENCES [dbo].[OWIR_CAUSE_DTLS] ([CAUSE_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_SRC_DTLS] CHECK CONSTRAINT [FK_SRC_DTLS_CAUSE_DTLS]
GO
ALTER TABLE [dbo].[OWIR_STATE_LOC_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_STTE_LC_DTLS_STTE_ASMT_DTLS] FOREIGN KEY([STATE_ASMT_DTLS_ID])
REFERENCES [dbo].[OWIR_STATE_ASMT_DTLS] ([STATE_ASMT_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_STATE_LOC_DTLS] CHECK CONSTRAINT [FK_STTE_LC_DTLS_STTE_ASMT_DTLS]
GO
ALTER TABLE [dbo].[OWIR_STATE_METH_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_STTE_MTH_DTLS_STTE_ASMT_DTL] FOREIGN KEY([STATE_ASMT_DTLS_ID])
REFERENCES [dbo].[OWIR_STATE_ASMT_DTLS] ([STATE_ASMT_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_STATE_METH_DTLS] CHECK CONSTRAINT [FK_STTE_MTH_DTLS_STTE_ASMT_DTL]
GO
ALTER TABLE [dbo].[OWIR_TMD_LS_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_TMD_LS_DTLS_ASM_UNT_CSE_DTL] FOREIGN KEY([ASMT_UNIT_CAUSE_DTLS_ID])
REFERENCES [dbo].[OWIR_ASMT_UNIT_CAUSE_DTLS] ([ASMT_UNIT_CAUSE_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_TMD_LS_DTLS] CHECK CONSTRAINT [FK_TMD_LS_DTLS_ASM_UNT_CSE_DTL]
GO
ALTER TABLE [dbo].[OWIR_USER_CATG_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_USR_CTG_DTLS_STTE_ASMT_DTLS] FOREIGN KEY([STATE_ASMT_DTLS_ID])
REFERENCES [dbo].[OWIR_STATE_ASMT_DTLS] ([STATE_ASMT_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_USER_CATG_DTLS] CHECK CONSTRAINT [FK_USR_CTG_DTLS_STTE_ASMT_DTLS]
GO
ALTER TABLE [dbo].[OWIR_WQS_ATTAIN_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_WQS_ATTN_DTLS_ASMT_UNT_DTLS] FOREIGN KEY([ASMT_UNIT_DTLS_ID])
REFERENCES [dbo].[OWIR_ASMT_UNIT_DTLS] ([ASMT_UNIT_DTLS_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OWIR_WQS_ATTAIN_DTLS] CHECK CONSTRAINT [FK_WQS_ATTN_DTLS_ASMT_UNT_DTLS]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The identification number or code assigned by the method publisher. (AssessmentMethodIdentifierCode)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_ASMT_METH_DTLS', @level2type=N'COLUMN',@level2name=N'ASMT_METH_IDEN_CODE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: AssessmentMethodDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_ASMT_METH_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: AssessmentTypeDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_ASMT_TYPE_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: AssessmentUnitCauseDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_ASMT_UNIT_CAUSE_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: AssessmentUnitDelistDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_ASMT_UNIT_DELIST_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: AssessmentUnitDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_ASMT_UNIT_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: AssessmentWaterDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_ASMT_WATER_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: ATLASDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_ATLAS_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: CauseDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_CAUSE_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: CycleTrackDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_CYCLE_TRACK_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: ImplementationActionDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_IMPL_ACT_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: NPDESDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_NPDES_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: ObservedEffectDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_OBSERVED_EFFECT_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: SourceDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_SRC_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'A code designator used to identify a principal administrative subdivision of the United States, Canada, or Mexico. (StateCode)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_STATE_ASMT_DTLS', @level2type=N'COLUMN',@level2name=N'STATE_CODE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'A name used to identify a principal administrative subdivision of the United States, Canada, or Mexico. (StateName)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_STATE_ASMT_DTLS', @level2type=N'COLUMN',@level2name=N'STATE_NAME'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Parent: A designator specifying the code set used to provide a state code. Can be used to identify the URL of a source that defines the set of currently approved permitted values. (CodeListVersionIdentifier)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_STATE_ASMT_DTLS', @level2type=N'COLUMN',@level2name=N'CODE_LIST_VERS_IDEN'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Parent: A designator specifying the code set used to provide a state code. Can be used to identify the URL of a source that defines the set of currently approved permitted values. (CodeListVersionAgencyIdentifier)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_STATE_ASMT_DTLS', @level2type=N'COLUMN',@level2name=N'CODE_LIST_VERS_AGN_IDEN'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Parent: A designator specifying the code set used to provide a state code. Can be used to identify the URL of a source that defines the set of currently approved permitted values. (Value)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_STATE_ASMT_DTLS', @level2type=N'COLUMN',@level2name=N'VAL'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: StateAssessmentDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_STATE_ASMT_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: StateLocationDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_STATE_LOC_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The identification number or code assigned by the method publisher. (AssessmentMethodIdentifierCode)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_STATE_METH_DTLS', @level2type=N'COLUMN',@level2name=N'ASMT_METH_IDEN_CODE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The title of the method that appears on the method from the organization that published it. (AssessmentMethodName)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_STATE_METH_DTLS', @level2type=N'COLUMN',@level2name=N'ASMT_METH_NAME'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: StateMethodDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_STATE_METH_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: TMDLsDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_TMD_LS_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: UserCategoryDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_USER_CATG_DTLS'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema element: WQSAttainmentDetailsDataType' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'OWIR_WQS_ATTAIN_DTLS'
GO
