//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.24 at 11:33:47 AM PST 
//


package com.windsor.node.plugin.facid3.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasureDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasureDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}MeasureValue" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}MeasureUnit" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}MeasurePrecisionText" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}ResultQualifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasureDataType", propOrder = {
    "measureValue",
    "measureUnit",
    "measurePrecisionText",
    "resultQualifier"
})
public class MeasureDataType {

    @XmlElement(name = "MeasureValue")
    protected String measureValue;
    @XmlElement(name = "MeasureUnit")
    protected MeasureUnitDataType measureUnit;
    @XmlElement(name = "MeasurePrecisionText")
    protected String measurePrecisionText;
    @XmlElement(name = "ResultQualifier")
    protected ResultQualifierDataType resultQualifier;

    /**
     * Gets the value of the measureValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureValue() {
        return measureValue;
    }

    /**
     * Sets the value of the measureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureValue(String value) {
        this.measureValue = value;
    }

    /**
     * Gets the value of the measureUnit property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureUnitDataType }
     *     
     */
    public MeasureUnitDataType getMeasureUnit() {
        return measureUnit;
    }

    /**
     * Sets the value of the measureUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureUnitDataType }
     *     
     */
    public void setMeasureUnit(MeasureUnitDataType value) {
        this.measureUnit = value;
    }

    /**
     * Gets the value of the measurePrecisionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurePrecisionText() {
        return measurePrecisionText;
    }

    /**
     * Sets the value of the measurePrecisionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurePrecisionText(String value) {
        this.measurePrecisionText = value;
    }

    /**
     * Gets the value of the resultQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link ResultQualifierDataType }
     *     
     */
    public ResultQualifierDataType getResultQualifier() {
        return resultQualifier;
    }

    /**
     * Sets the value of the resultQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultQualifierDataType }
     *     
     */
    public void setResultQualifier(ResultQualifierDataType value) {
        this.resultQualifier = value;
    }

}
