//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.26 at 02:36:56 PM PDT 
//


package com.windsor.node.plugin.ic.fixeddomain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AffiliationTypeCodeDataType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AffiliationTypeCodeDataType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Obligee"/>
 *     &lt;enumeration value="Owner"/>
 *     &lt;enumeration value="Occupant"/>
 *     &lt;enumeration value="Agency"/>
 *     &lt;enumeration value="Compliance"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AffiliationTypeCodeDataType")
@XmlEnum
public enum AffiliationTypeCodeDataType {

    @XmlEnumValue("Obligee")
    OBLIGEE("Obligee"),
    @XmlEnumValue("Owner")
    OWNER("Owner"),
    @XmlEnumValue("Occupant")
    OCCUPANT("Occupant"),
    @XmlEnumValue("Agency")
    AGENCY("Agency"),
    @XmlEnumValue("Compliance")
    COMPLIANCE("Compliance"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    AffiliationTypeCodeDataType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AffiliationTypeCodeDataType fromValue(String v) {
        for (AffiliationTypeCodeDataType c: AffiliationTypeCodeDataType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
