------------------------------------------------------------------------------
--
-- This script will create an new instance of the OpenNode2 BEACHES v2.4
--
-- Date     Description
-- -------- --------------------------------
-- 20190925 Created
--
------------------------------------------------------------------------------

SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL Serializable
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_BEACHACTIVITY]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITY]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_BEACHACTIVITY]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BEACH_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTIVITYTYPECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTIVITYNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTUALSTARTDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTUALSTOPDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTIVITYDESCRIPTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVITYCOMMENT] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTENTSTARTMEASURE] [decimal] (16, 6) NULL,
[EXTENTLENGTHMEASURE] [decimal] (16, 6) NULL,
[EXTENTUNITOFMEASURE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SENTTOEPA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTIFUPDATEDATE] [datetime] NULL,
[ACTIVITYPARTIALDAYAMOUNT] [decimal] (16, 6) NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_BEACHACTIVITY] on [dbo].[NOTIF_BEACHACTIVITY]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_BEACHACTIVITY]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITY]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHACTIVITY] ADD CONSTRAINT [PK_NOTIF_BEACHACTIVITY] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_BEACHACTIVITY] on [dbo].[NOTIF_BEACHACTIVITY]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_BEACHACTIVITY' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITY]'))
CREATE NONCLUSTERED INDEX [NOTIF_BEACHACTIVITY] ON [dbo].[NOTIF_BEACHACTIVITY] ([BEACH_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_SENTTOEPA] on [dbo].[NOTIF_BEACHACTIVITY]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_SENTTOEPA' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITY]'))
CREATE NONCLUSTERED INDEX [NOTIF_SENTTOEPA] ON [dbo].[NOTIF_BEACHACTIVITY] ([SENTTOEPA])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_ACTIVITYINDICATOR]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYINDICATOR]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_ACTIVITYINDICATOR]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTIVITY_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INDICATORTYPE] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INDICATORDESCRIPTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_ACTIVITYINDICATOR] on [dbo].[NOTIF_ACTIVITYINDICATOR]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_ACTIVITYINDICATOR]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYINDICATOR]', 'U'))
ALTER TABLE [dbo].[NOTIF_ACTIVITYINDICATOR] ADD CONSTRAINT [PK_NOTIF_ACTIVITYINDICATOR] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_ACTIVITYINDICATOR] on [dbo].[NOTIF_ACTIVITYINDICATOR]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_ACTIVITYINDICATOR' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYINDICATOR]'))
CREATE NONCLUSTERED INDEX [NOTIF_ACTIVITYINDICATOR] ON [dbo].[NOTIF_ACTIVITYINDICATOR] ([ACTIVITY_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_ACTIVITYREASON]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYREASON]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_ACTIVITYREASON]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTIVITY_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REASONTYPE] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REASONDESCRIPTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_ACTIVITYREASON] on [dbo].[NOTIF_ACTIVITYREASON]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_ACTIVITYREASON]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYREASON]', 'U'))
ALTER TABLE [dbo].[NOTIF_ACTIVITYREASON] ADD CONSTRAINT [PK_NOTIF_ACTIVITYREASON] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_ACTIVITYREASON] on [dbo].[NOTIF_ACTIVITYREASON]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_ACTIVITYREASON' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYREASON]'))
CREATE NONCLUSTERED INDEX [NOTIF_ACTIVITYREASON] ON [dbo].[NOTIF_ACTIVITYREASON] ([ACTIVITY_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_ACTIVITYSOURCE]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYSOURCE]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_ACTIVITYSOURCE]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTIVITY_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SOURCETYPE] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SOURCEDESCRIPTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_ACTIVITYSOURCE] on [dbo].[NOTIF_ACTIVITYSOURCE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_ACTIVITYSOURCE]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYSOURCE]', 'U'))
ALTER TABLE [dbo].[NOTIF_ACTIVITYSOURCE] ADD CONSTRAINT [PK_NOTIF_ACTIVITYSOURCE] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_ACTIVITYSOURCE] on [dbo].[NOTIF_ACTIVITYSOURCE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_ACTIVITYSOURCE' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYSOURCE]'))
CREATE NONCLUSTERED INDEX [NOTIF_ACTIVITYSOURCE] ON [dbo].[NOTIF_ACTIVITYSOURCE] ([ACTIVITY_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_BEACH]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_BEACH]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_BEACH]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BEACHIDENTIFIER] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BEACHNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEACHDESCRIPTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEACHCOMMENT] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEACHSTATECODE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEACHFIPSCOUNTYCODE] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEACHACCESSTYPE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEACHACCESSCOMMENT] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFECTIVEYEAR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTENTLENGTHMEASURE] [decimal] (16, 6) NULL,
[EXTENTUNITOFMEASURE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SWIMSEASONSTARTDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SWIMSEASONENDDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SWIMSEASONLENGTH] [decimal] (16, 6) NULL,
[SWIMSEASONUNITOFMEASURE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SWIMSEASONFREQUENCYMEASURE] [decimal] (16, 6) NULL,
[OFFSEASONFREQUENCYMEASURE] [decimal] (16, 6) NULL,
[MONITORINGFREQUNITOFMEASURE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONITOREDIRREGULARLY] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONITOREDIRREGULARLYCOMMENT] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEACHTIERRANKING] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEACHACTBEACHINDICATOR] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOPOLLUTIONSOURCES] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POLLUTIONSOURCESUNINVESTIGATED] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WATERBODYNAMECODE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WATERBODYTYPECODE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STARTLATMEASURE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STARTLONGMEASURE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENDLATMEASURE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENDLONGMEASURE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCEMAPSCALE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HORIZCOLLMETHOD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HORIZCOLLDATUM] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEACHDORMANTINDICATOR] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEACHWEBSITE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REPORTINGFREQUENCYMEASURE] [decimal] (16, 6) NULL,
[REPORTINGFREQUNITOFMEASURE] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SWIMSEASONDAYMEASURE] [decimal] (16, 6) NULL,
[ADVREPORTINGFREQUENCYMEASURE] [decimal] (16, 6) NULL,
[ADVREPORTINGFREQUNITOFMEASURE] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_BEACH] on [dbo].[NOTIF_BEACH]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_BEACH]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACH]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACH] ADD CONSTRAINT [PK_NOTIF_BEACH] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_BEACHPOLLUTION]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_BEACHPOLLUTION]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_BEACHPOLLUTION]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BEACH_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[POLLUTIONSOURCECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[POLLUTIONSOURCEDESCRIPTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_BEACHPOLLUTION] on [dbo].[NOTIF_BEACHPOLLUTION]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_BEACHPOLLUTION]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHPOLLUTION]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHPOLLUTION] ADD CONSTRAINT [PK_NOTIF_BEACHPOLLUTION] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_BEACHPOLLUTION] on [dbo].[NOTIF_BEACHPOLLUTION]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_BEACHPOLLUTION' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHPOLLUTION]'))
CREATE NONCLUSTERED INDEX [NOTIF_BEACHPOLLUTION] ON [dbo].[NOTIF_BEACHPOLLUTION] ([BEACH_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_BEACHPROCEDURE]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_BEACHPROCEDURE]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_BEACHPROCEDURE]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BEACH_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROCEDURE_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_BEACHPROCEDURE] on [dbo].[NOTIF_BEACHPROCEDURE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_BEACHPROCEDURE]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHPROCEDURE]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHPROCEDURE] ADD CONSTRAINT [PK_NOTIF_BEACHPROCEDURE] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_BEACHPROCEDURE_IDX] on [dbo].[NOTIF_BEACHPROCEDURE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_BEACHPROCEDURE_IDX' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHPROCEDURE]'))
CREATE NONCLUSTERED INDEX [NOTIF_BEACHPROCEDURE_IDX] ON [dbo].[NOTIF_BEACHPROCEDURE] ([BEACH_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_PROCEDURE_IDX] on [dbo].[NOTIF_BEACHPROCEDURE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_PROCEDURE_IDX' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHPROCEDURE]'))
CREATE NONCLUSTERED INDEX [NOTIF_PROCEDURE_IDX] ON [dbo].[NOTIF_BEACHPROCEDURE] ([PROCEDURE_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_PROCEDURE]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_PROCEDURE]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_PROCEDURE]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROCEDUREIDENTIFIER] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROCEDURETYPECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROCEDUREDESCRIPTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_PROCEDURE] on [dbo].[NOTIF_PROCEDURE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_PROCEDURE]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PROCEDURE]', 'U'))
ALTER TABLE [dbo].[NOTIF_PROCEDURE] ADD CONSTRAINT [PK_NOTIF_PROCEDURE] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_BEACHACTIVITYMONSTATION]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITYMONSTATION]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_BEACHACTIVITYMONSTATION]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTIVITY_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MONITORINGSTATIONIDENTIFIER] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_BEACHACTMONITOR] on [dbo].[NOTIF_BEACHACTIVITYMONSTATION]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_BEACHACTMONITOR]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITYMONSTATION]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHACTIVITYMONSTATION] ADD CONSTRAINT [PK_NOTIF_BEACHACTMONITOR] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_BEACHACTMONITOR_IDX] on [dbo].[NOTIF_BEACHACTIVITYMONSTATION]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_BEACHACTMONITOR_IDX' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITYMONSTATION]'))
CREATE NONCLUSTERED INDEX [NOTIF_BEACHACTMONITOR_IDX] ON [dbo].[NOTIF_BEACHACTIVITYMONSTATION] ([ACTIVITY_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_BEACHCRITERION]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_BEACHCRITERION]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_BEACHCRITERION]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BEACH_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INDICATORNAME] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WATERTYPENAME] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CRITERIONCOMMENT] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEASURETYPENAME] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MEASUREVALUE] [decimal] (16, 6) NOT NULL,
[MEASUREUNITCODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOT_BCH_CRI] on [dbo].[NOTIF_BEACHCRITERION]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOT_BCH_CRI]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHCRITERION]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHCRITERION] ADD CONSTRAINT [PK_NOT_BCH_CRI] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_ORGANIZATION]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATION]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_ORGANIZATION]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORGANIZATIONIDENTIFIER] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORGANIZATIONTYPECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORGANIZATIONNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORGANIZATIONDESCRIPTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORGANIZATIONABBREVIATION] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_ORGANIZATION] on [dbo].[NOTIF_ORGANIZATION]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_ORGANIZATION]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATION]', 'U'))
ALTER TABLE [dbo].[NOTIF_ORGANIZATION] ADD CONSTRAINT [PK_NOTIF_ORGANIZATION] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_STATECONTACT]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_STATECONTACT]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_STATECONTACT]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORGANIZATION_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AGENCYNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TELEPHONENUMBER] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELECTRONICADDR] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FIRSTNAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LASTNAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOT_STCNTCT] on [dbo].[NOTIF_STATECONTACT]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOT_STCNTCT]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_STATECONTACT]', 'U'))
ALTER TABLE [dbo].[NOTIF_STATECONTACT] ADD CONSTRAINT [PK_NOT_STCNTCT] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_ORGANIZATIONMAILINGADDR]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONMAILINGADDR]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_ORGANIZATIONMAILINGADDR]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORGANIZATION_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MAILINGADDRTYPECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MAILINGADDRLINE1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MAILINGADDRLINE2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGADDRLINE3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGADDRCITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STATECODE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ZIPCODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MAILINGADDREFFECTIVEDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MAILINGADDRSTATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_ORGMAILINGADDR] on [dbo].[NOTIF_ORGANIZATIONMAILINGADDR]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_ORGMAILINGADDR]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONMAILINGADDR]', 'U'))
ALTER TABLE [dbo].[NOTIF_ORGANIZATIONMAILINGADDR] ADD CONSTRAINT [PK_NOTIF_ORGMAILINGADDR] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_ORGANIZATIONMAILINGADDR] on [dbo].[NOTIF_ORGANIZATIONMAILINGADDR]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_ORGANIZATIONMAILINGADDR' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONMAILINGADDR]'))
CREATE NONCLUSTERED INDEX [NOTIF_ORGANIZATIONMAILINGADDR] ON [dbo].[NOTIF_ORGANIZATIONMAILINGADDR] ([ORGANIZATION_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_ORGANIZATIONBEACHROLE]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONBEACHROLE]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_ORGANIZATIONBEACHROLE]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BEACH_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORGANIZATION_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ROLETYPECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ROLEEFFECTIVEDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ROLESTATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_ORGANIZATIONBEACHROLE] on [dbo].[NOTIF_ORGANIZATIONBEACHROLE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_ORGANIZATIONBEACHROLE]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONBEACHROLE]', 'U'))
ALTER TABLE [dbo].[NOTIF_ORGANIZATIONBEACHROLE] ADD CONSTRAINT [PK_NOTIF_ORGANIZATIONBEACHROLE] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_ORGANIZATIONBEACHROLE] on [dbo].[NOTIF_ORGANIZATIONBEACHROLE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_ORGANIZATIONBEACHROLE' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONBEACHROLE]'))
CREATE NONCLUSTERED INDEX [NOTIF_ORGANIZATIONBEACHROLE] ON [dbo].[NOTIF_ORGANIZATIONBEACHROLE] ([ORGANIZATION_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_ORGANIZATIONTELEPHONE]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONTELEPHONE]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_ORGANIZATIONTELEPHONE]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORGANIZATION_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TELEPHONETYPECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TELEPHONENUMBER] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TELEPHONEEFFECTIVEDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TELEPHONESTATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_ORGANIZATIONTELEPHONE] on [dbo].[NOTIF_ORGANIZATIONTELEPHONE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_ORGANIZATIONTELEPHONE]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONTELEPHONE]', 'U'))
ALTER TABLE [dbo].[NOTIF_ORGANIZATIONTELEPHONE] ADD CONSTRAINT [PK_NOTIF_ORGANIZATIONTELEPHONE] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_ORGANIZATIONTELEPHONE] on [dbo].[NOTIF_ORGANIZATIONTELEPHONE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_ORGANIZATIONTELEPHONE' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONTELEPHONE]'))
CREATE NONCLUSTERED INDEX [NOTIF_ORGANIZATIONTELEPHONE] ON [dbo].[NOTIF_ORGANIZATIONTELEPHONE] ([ORGANIZATION_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_ORGELECTRONICADDR]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_ORGELECTRONICADDR]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_ORGELECTRONICADDR]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORGANIZATION_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELECTRONICADDRTYPECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELECTRONICADDR] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELECTRONICADDREFFDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELECTRONICADDRSTATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_ORGELECTRONICADDR] on [dbo].[NOTIF_ORGELECTRONICADDR]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_ORGELECTRONICADDR]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGELECTRONICADDR]', 'U'))
ALTER TABLE [dbo].[NOTIF_ORGELECTRONICADDR] ADD CONSTRAINT [PK_NOTIF_ORGELECTRONICADDR] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_ORGELECTRONICADDR] on [dbo].[NOTIF_ORGELECTRONICADDR]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_ORGELECTRONICADDR' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGELECTRONICADDR]'))
CREATE NONCLUSTERED INDEX [NOTIF_ORGELECTRONICADDR] ON [dbo].[NOTIF_ORGELECTRONICADDR] ([ORGANIZATION_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_PERSON]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_PERSON]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_PERSON]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORGANIZATION_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PERSONIDENTIFIER] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PERSONSTATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTNAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MIDDLEINITIAL] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUFFIX] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TITLE] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_PERSON] on [dbo].[NOTIF_PERSON]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_PERSON]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSON]', 'U'))
ALTER TABLE [dbo].[NOTIF_PERSON] ADD CONSTRAINT [PK_NOTIF_PERSON] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_PERSON] on [dbo].[NOTIF_PERSON]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_PERSON' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSON]'))
CREATE NONCLUSTERED INDEX [NOTIF_PERSON] ON [dbo].[NOTIF_PERSON] ([ORGANIZATION_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_PERSONBEACHROLE]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_PERSONBEACHROLE]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_PERSONBEACHROLE]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BEACH_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PERSON_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ROLETYPECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ROLEEFFECTIVEDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ROLESTATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_PERSONBEACHROLE] on [dbo].[NOTIF_PERSONBEACHROLE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_PERSONBEACHROLE]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONBEACHROLE]', 'U'))
ALTER TABLE [dbo].[NOTIF_PERSONBEACHROLE] ADD CONSTRAINT [PK_NOTIF_PERSONBEACHROLE] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_PERSONBEACHROLE] on [dbo].[NOTIF_PERSONBEACHROLE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_PERSONBEACHROLE' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONBEACHROLE]'))
CREATE NONCLUSTERED INDEX [NOTIF_PERSONBEACHROLE] ON [dbo].[NOTIF_PERSONBEACHROLE] ([BEACH_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_PERSONELECTRONICADDRESS]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_PERSONELECTRONICADDRESS]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_PERSONELECTRONICADDRESS]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PERSON_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELECTRONICADDRESSTYPECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELECTRONICADDRESS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELECTRONICADDRESSEFFECTIVEDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ELECTRONICADDRESSSTATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_PERSONELECTRONICADDR] on [dbo].[NOTIF_PERSONELECTRONICADDRESS]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_PERSONELECTRONICADDR]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONELECTRONICADDRESS]', 'U'))
ALTER TABLE [dbo].[NOTIF_PERSONELECTRONICADDRESS] ADD CONSTRAINT [PK_NOTIF_PERSONELECTRONICADDR] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_PERSONELECTRONICADDRESS] on [dbo].[NOTIF_PERSONELECTRONICADDRESS]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_PERSONELECTRONICADDRESS' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONELECTRONICADDRESS]'))
CREATE NONCLUSTERED INDEX [NOTIF_PERSONELECTRONICADDRESS] ON [dbo].[NOTIF_PERSONELECTRONICADDRESS] ([PERSON_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_PERSONMAILINGADDRESS]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_PERSONMAILINGADDRESS]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_PERSONMAILINGADDRESS]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PERSON_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MAILINGADDRTYPECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MAILINGADDRLINE1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MAILINGADDRLINE2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGADDRLINE3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGADDRCITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STATECODE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ZIPCODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MAILINGADDREFFECTIVEDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MAILINGADDRSTATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_PERSONMAILINGADDRESS] on [dbo].[NOTIF_PERSONMAILINGADDRESS]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_PERSONMAILINGADDRESS]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONMAILINGADDRESS]', 'U'))
ALTER TABLE [dbo].[NOTIF_PERSONMAILINGADDRESS] ADD CONSTRAINT [PK_NOTIF_PERSONMAILINGADDRESS] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_PERSONMAILINGADDRESS] on [dbo].[NOTIF_PERSONMAILINGADDRESS]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_PERSONMAILINGADDRESS' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONMAILINGADDRESS]'))
CREATE NONCLUSTERED INDEX [NOTIF_PERSONMAILINGADDRESS] ON [dbo].[NOTIF_PERSONMAILINGADDRESS] ([PERSON_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_PERSONTELEPHONE]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_PERSONTELEPHONE]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_PERSONTELEPHONE]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PERSON_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TELEPHONETYPECODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TELEPHONENUMBER] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TELEPHONEEFFECTIVEDATE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TELEPHONESTATUS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_PERSONTELEPHONE] on [dbo].[NOTIF_PERSONTELEPHONE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_PERSONTELEPHONE]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONTELEPHONE]', 'U'))
ALTER TABLE [dbo].[NOTIF_PERSONTELEPHONE] ADD CONSTRAINT [PK_NOTIF_PERSONTELEPHONE] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [NOTIF_PERSONTELEPHONE] on [dbo].[NOTIF_PERSONTELEPHONE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'NOTIF_PERSONTELEPHONE' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONTELEPHONE]'))
CREATE NONCLUSTERED INDEX [NOTIF_PERSONTELEPHONE] ON [dbo].[NOTIF_PERSONTELEPHONE] ([PERSON_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_BEACHACTIVITYDELETE]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITYDELETE]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_BEACHACTIVITYDELETE]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BEACH_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACTIVITYCODENUMBER] [decimal] (16, 6) NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOT_BCHACTDEL] on [dbo].[NOTIF_BEACHACTIVITYDELETE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOT_BCHACTDEL]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITYDELETE]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHACTIVITYDELETE] ADD CONSTRAINT [PK_NOT_BCHACTDEL] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating index [FK_NOT_BCHACT002] on [dbo].[NOTIF_BEACHACTIVITYDELETE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'FK_NOT_BCHACT002' AND object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITYDELETE]'))
CREATE NONCLUSTERED INDEX [FK_NOT_BCHACT002] ON [dbo].[NOTIF_BEACHACTIVITYDELETE] ([BEACH_ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_SUBMISSIONHISTORY]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_SUBMISSIONHISTORY]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_SUBMISSIONHISTORY]
(
[RECORDID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SCHEDULERUNDATE] [datetime] NOT NULL,
[TRANSACTIONID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROCESSINGSTATUS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating [dbo].[NOTIF_YEARCOMPLETION]'
GO
IF OBJECT_ID(N'[dbo].[NOTIF_YEARCOMPLETION]', 'U') IS NULL
CREATE TABLE [dbo].[NOTIF_YEARCOMPLETION]
(
[ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMPLETIONYEAR] [int] NOT NULL,
[NOTIFICATIONDATACOMPLETIONIND] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONITORINGDATACOMPLETIONIND] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATIONDATACOMPLETIONIND] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Creating primary key [PK_NOTIF_YEARCOMPLETION] on [dbo].[NOTIF_YEARCOMPLETION]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PK_NOTIF_YEARCOMPLETION]', 'PK') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_YEARCOMPLETION]', 'U'))
ALTER TABLE [dbo].[NOTIF_YEARCOMPLETION] ADD CONSTRAINT [PK_NOTIF_YEARCOMPLETION] PRIMARY KEY CLUSTERED  ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_ACTIVITYINDICATOR]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ACTIVITYINDICATOR_BEACHACT]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYINDICATOR]', 'U'))
ALTER TABLE [dbo].[NOTIF_ACTIVITYINDICATOR] ADD CONSTRAINT [FK_ACTIVITYINDICATOR_BEACHACT] FOREIGN KEY ([ACTIVITY_ID]) REFERENCES [dbo].[NOTIF_BEACHACTIVITY] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_ACTIVITYREASON]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ACTIVITYREASON_BEACHACT]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYREASON]', 'U'))
ALTER TABLE [dbo].[NOTIF_ACTIVITYREASON] ADD CONSTRAINT [FK_ACTIVITYREASON_BEACHACT] FOREIGN KEY ([ACTIVITY_ID]) REFERENCES [dbo].[NOTIF_BEACHACTIVITY] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_ACTIVITYSOURCE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ACTIVITYSOURCE_BEACHACT]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ACTIVITYSOURCE]', 'U'))
ALTER TABLE [dbo].[NOTIF_ACTIVITYSOURCE] ADD CONSTRAINT [FK_ACTIVITYSOURCE_BEACHACT] FOREIGN KEY ([ACTIVITY_ID]) REFERENCES [dbo].[NOTIF_BEACHACTIVITY] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_BEACHACTIVITYMONSTATION]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_NOT_ACT_MON]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITYMONSTATION]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHACTIVITYMONSTATION] ADD CONSTRAINT [FK_NOT_ACT_MON] FOREIGN KEY ([ACTIVITY_ID]) REFERENCES [dbo].[NOTIF_BEACHACTIVITY] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_BEACHACTIVITY]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BEACHACTIVITY_BEACH]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHACTIVITY]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHACTIVITY] ADD CONSTRAINT [FK_BEACHACTIVITY_BEACH] FOREIGN KEY ([BEACH_ID]) REFERENCES [dbo].[NOTIF_BEACH] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_BEACHCRITERION]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_NOT_BCH_CRI]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHCRITERION]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHCRITERION] ADD CONSTRAINT [FK_NOT_BCH_CRI] FOREIGN KEY ([BEACH_ID]) REFERENCES [dbo].[NOTIF_BEACH] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_BEACHPOLLUTION]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BEACHPOLLUTION_BEACH]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHPOLLUTION]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHPOLLUTION] ADD CONSTRAINT [FK_BEACHPOLLUTION_BEACH] FOREIGN KEY ([BEACH_ID]) REFERENCES [dbo].[NOTIF_BEACH] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_BEACHPROCEDURE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BEACHPROCEDURE_BEACH]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHPROCEDURE]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHPROCEDURE] ADD CONSTRAINT [FK_BEACHPROCEDURE_BEACH] FOREIGN KEY ([BEACH_ID]) REFERENCES [dbo].[NOTIF_BEACH] ([ID]) ON DELETE CASCADE
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BEACHPROCEDURE_PROCEDURE]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_BEACHPROCEDURE]', 'U'))
ALTER TABLE [dbo].[NOTIF_BEACHPROCEDURE] ADD CONSTRAINT [FK_BEACHPROCEDURE_PROCEDURE] FOREIGN KEY ([PROCEDURE_ID]) REFERENCES [dbo].[NOTIF_PROCEDURE] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_ORGANIZATIONBEACHROLE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ORGANIZATIONBEACHROLE_BEACH]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONBEACHROLE]', 'U'))
ALTER TABLE [dbo].[NOTIF_ORGANIZATIONBEACHROLE] ADD CONSTRAINT [FK_ORGANIZATIONBEACHROLE_BEACH] FOREIGN KEY ([BEACH_ID]) REFERENCES [dbo].[NOTIF_BEACH] ([ID]) ON DELETE CASCADE
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ORGANIZATIONBEACHROLE_ORG]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONBEACHROLE]', 'U'))
ALTER TABLE [dbo].[NOTIF_ORGANIZATIONBEACHROLE] ADD CONSTRAINT [FK_ORGANIZATIONBEACHROLE_ORG] FOREIGN KEY ([ORGANIZATION_ID]) REFERENCES [dbo].[NOTIF_ORGANIZATION] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_PERSONBEACHROLE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PERSONBEACHROLE_BEACH]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONBEACHROLE]', 'U'))
ALTER TABLE [dbo].[NOTIF_PERSONBEACHROLE] ADD CONSTRAINT [FK_PERSONBEACHROLE_BEACH] FOREIGN KEY ([BEACH_ID]) REFERENCES [dbo].[NOTIF_BEACH] ([ID]) ON DELETE CASCADE
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PERSONBEACHROLE_PERSON]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONBEACHROLE]', 'U'))
ALTER TABLE [dbo].[NOTIF_PERSONBEACHROLE] ADD CONSTRAINT [FK_PERSONBEACHROLE_PERSON] FOREIGN KEY ([PERSON_ID]) REFERENCES [dbo].[NOTIF_PERSON] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_ORGANIZATIONMAILINGADDR]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ORGANIZATION_ORGMAILINGADDR]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONMAILINGADDR]', 'U'))
ALTER TABLE [dbo].[NOTIF_ORGANIZATIONMAILINGADDR] ADD CONSTRAINT [FK_ORGANIZATION_ORGMAILINGADDR] FOREIGN KEY ([ORGANIZATION_ID]) REFERENCES [dbo].[NOTIF_ORGANIZATION] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_ORGANIZATIONTELEPHONE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ORGANIZATIONTELEPHONE_ORG]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGANIZATIONTELEPHONE]', 'U'))
ALTER TABLE [dbo].[NOTIF_ORGANIZATIONTELEPHONE] ADD CONSTRAINT [FK_ORGANIZATIONTELEPHONE_ORG] FOREIGN KEY ([ORGANIZATION_ID]) REFERENCES [dbo].[NOTIF_ORGANIZATION] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_STATECONTACT]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_NOT_STCNTCT]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_STATECONTACT]', 'U'))
ALTER TABLE [dbo].[NOTIF_STATECONTACT] ADD CONSTRAINT [FK_NOT_STCNTCT] FOREIGN KEY ([ORGANIZATION_ID]) REFERENCES [dbo].[NOTIF_ORGANIZATION] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_ORGELECTRONICADDR]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ORGELECTRONICADDR_ORG]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_ORGELECTRONICADDR]', 'U'))
ALTER TABLE [dbo].[NOTIF_ORGELECTRONICADDR] ADD CONSTRAINT [FK_ORGELECTRONICADDR_ORG] FOREIGN KEY ([ORGANIZATION_ID]) REFERENCES [dbo].[NOTIF_ORGANIZATION] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_PERSON]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PERSON_ORGANIZATION]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSON]', 'U'))
ALTER TABLE [dbo].[NOTIF_PERSON] ADD CONSTRAINT [FK_PERSON_ORGANIZATION] FOREIGN KEY ([ORGANIZATION_ID]) REFERENCES [dbo].[NOTIF_ORGANIZATION] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_PERSONELECTRONICADDRESS]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PERSONELECTRONICADD_PERSON]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONELECTRONICADDRESS]', 'U'))
ALTER TABLE [dbo].[NOTIF_PERSONELECTRONICADDRESS] ADD CONSTRAINT [FK_PERSONELECTRONICADD_PERSON] FOREIGN KEY ([PERSON_ID]) REFERENCES [dbo].[NOTIF_PERSON] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_PERSONMAILINGADDRESS]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PERSONMAILINGADDRESS_PERSON]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONMAILINGADDRESS]', 'U'))
ALTER TABLE [dbo].[NOTIF_PERSONMAILINGADDRESS] ADD CONSTRAINT [FK_PERSONMAILINGADDRESS_PERSON] FOREIGN KEY ([PERSON_ID]) REFERENCES [dbo].[NOTIF_PERSON] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Adding foreign keys to [dbo].[NOTIF_PERSONTELEPHONE]'
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PERSONTELEPHONE_PERSON]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NOTIF_PERSONTELEPHONE]', 'U'))
ALTER TABLE [dbo].[NOTIF_PERSONTELEPHONE] ADD CONSTRAINT [FK_PERSONTELEPHONE_PERSON] FOREIGN KEY ([PERSON_ID]) REFERENCES [dbo].[NOTIF_PERSON] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
-- This statement writes to the SQL Server Log so SQL Monitor can show this deployment.
IF HAS_PERMS_BY_NAME(N'sys.xp_logevent', N'OBJECT', N'EXECUTE') = 1
BEGIN
    DECLARE @databaseName AS nvarchar(2048), @eventMessage AS nvarchar(2048)
    SET @databaseName = REPLACE(REPLACE(DB_NAME(), N'\', N'\\'), N'"', N'\"')
    SET @eventMessage = N'Redgate SQL Compare: { "deployment": { "description": "Redgate SQL Compare deployed to ' + @databaseName + N'", "database": "' + @databaseName + N'" }}'
    EXECUTE sys.xp_logevent 55000, @eventMessage
END
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	PRINT 'The database update failed'
END
GO
