DROP TABLE NODE.WQX_TELEPHONIC
/
DROP TABLE NODE.WQX_SUBMISSIONHISTORY
/
DROP TABLE NODE.WQX_RESULTDETECTQUANTLIMIT
/
DROP TABLE NODE.WQX_RESULTATTACHEDBINARYOBJECT
/
DROP TABLE NODE.WQX_RESULT
/
DROP TABLE NODE.WQX_PROJECTMONLOC
/
DROP TABLE NODE.WQX_PROJECTACTIVITY
/
DROP TABLE NODE.WQX_PROJECT
/
DROP TABLE NODE.WQX_PROJATTACHEDBINARYOBJECT
/
DROP TABLE NODE.WQX_ORGANIZATION
/
DROP TABLE NODE.WQX_ORGADDRESS
/
DROP TABLE NODE.WQX_MONLOCATTACHEDBINARYOBJECT
/
DROP TABLE NODE.WQX_MONITORINGLOCATION
/
DROP TABLE NODE.WQX_LABSAMPLEPREP
/
DROP TABLE NODE.WQX_ELECTRONICADDRESS
/
DROP TABLE NODE.WQX_DELETES
/
DROP TABLE NODE.WQX_BIOLOGICALHABITATINDEX
/
DROP TABLE NODE.WQX_ALTMONLOC
/
DROP TABLE NODE.WQX_ACTIVITYMETRIC
/
DROP TABLE NODE.WQX_ACTIVITYGROUP
/
DROP TABLE NODE.WQX_ACTIVITYCONDUCTINGORG
/
DROP TABLE NODE.WQX_ACTIVITYACTIVITYGROUP
/
DROP TABLE NODE.WQX_ACTIVITY
/
DROP TABLE NODE.WQX_ACTATTACHEDBINARYOBJECT
/





CREATE TABLE NODE.WQX_ORGANIZATION(
    RECORDID varchar(50) NOT NULL,
    ORGID varchar(30) NOT NULL,
    ORGFORMALNAME varchar(120) NOT NULL,
    ORGDESC varchar(500) ,
    TRIBALCODE varchar(3) ,
    CONSTRAINT PK_WQX_ORG PRIMARY KEY  (RECORDID))
/





CREATE TABLE NODE.WQX_PROJECTACTIVITY(
    RECORDID varchar(50) NOT NULL,
    PROJECTPARENTID varchar(50) NOT NULL,
    ACTIVITYPARENTID varchar(50) NOT NULL,
 CONSTRAINT PK_WQX_PROJECTACT PRIMARY KEY  
(
    RECORDID 
))
/





CREATE TABLE NODE.WQX_PROJECTMONLOC(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    MONLOCID varchar(35) NOT NULL,
    LOCWEIGHTINGFACMEASURE varchar(12) NOT NULL,
    LOCWEIGHTINGFACMEASUREUNIT varchar(12) NOT NULL,
    STATISTICALSTRATUM varchar(15) ,
    LOCATIONCATERY varchar(50) ,
    LOCATIONSTATUS varchar(15) ,
    REFLOCATIONTYPECODE varchar(20) ,
    REFLOCATIONSTARTDATE date ,
    REFLOCATIONENDDATE date ,
    RESOURCETITLE varchar(120) ,
    RESOURCECREATOR varchar(120) ,
    RESOURCESUBJECT varchar(500) ,
    RESOURCEPUBLISHER varchar(60) ,
    RESOURCEDATE date ,
    RESOURCEID varchar(255) ,
    PROJMONLOCCOMMENT varchar(4000) ,
 CONSTRAINT PK_WQX_PROJMONLOC PRIMARY KEY  
(
    RECORDID ) )

/




CREATE TABLE NODE.WQX_PROJATTACHEDBINARYOBJECT(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    BINARYOBJECTFILE varchar(255) NOT NULL,
    BINARYOBJECTFILETYPECODE varchar(6) NOT NULL,
 CONSTRAINT PK_WQX_PRJATBINOBJ PRIMARY KEY  
(
    RECORDID 
)) 

/




CREATE TABLE NODE.WQX_ACTIVITYACTIVITYGROUP(
    RECORDID varchar(50) NOT NULL,
    ACTIVITYPARENTID varchar(50) NOT NULL,
    ACTIVITYGROUPPARENTID varchar(50) NOT NULL,
    ACTIVITYID varchar(35) NOT NULL,
 CONSTRAINT PK_WQX_ACTACTGROUP PRIMARY KEY  
(
    RECORDID 
))
/





CREATE TABLE NODE.WQX_RESULT(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    DATALOGGERLINENAME varchar(15) ,
    RESULTDETECTIONCONDITION varchar(35) ,
    CHARACTERISTICNAME varchar(120) ,
    METHODSPECIATIONNAME varchar(20) ,
    RESULTSAMPFRACTION varchar(25) ,
    RESULTMEASURE varchar(60) ,
    RESULTMEASUREUNIT varchar(12) ,
    RESULTMEASUREQUALIFIERCODE varchar(5) ,
    STATUSID varchar(12) ,
    STATISTICALBASECODE varchar(25) ,
    VALUETYPE varchar(20) ,
    WEIGHTBASIS varchar(15) ,
    TIMEBASIS varchar(12) ,
    TEMPERATUREBASIS varchar(12) ,
    PARTICLESIZEBASIS varchar(15) ,
    PRECISIONVALUE varchar(60) ,
    BIASVALUE varchar(60) ,
    CONFIDENCEINTERVALVALUE varchar(15) ,
    UPPERCONFIDENCELIMITVALUE varchar(15) ,
    LOWERCONFIDENCELIMITVALUE varchar(15) ,
    RESULTCOMMENT varchar(4000) ,
    DEPTHHEIGHTMEASURE varchar(12) ,
    DEPTHHEIGHTMEASUREUNIT varchar(12) ,
    DEPTHALTITUDEREFPOINT varchar(125) ,
    RESULTSAMPPOINT varchar(12) ,
    BIORESULTINTENT varchar(35) ,
    BIORESULTINDIVIDUALID varchar(4) ,
    BIORESULTSUBJECTTAXONOMIC varchar(120) ,
    BIORESULTUNIDENTIFIEDSPECIESID varchar(120) ,
    BIORESULTSAMPTISSUEANATOMY varchar(30) ,
    GRPSUMMCOUNTWEIGHTMEASURE varchar(12) ,
    GRPSUMMCOUNTWEIGHTMEASUREUNIT varchar(12) ,
    TAXDETAILSCELLFORM varchar(11) ,
    TAXDETAILSCELLSHAPE varchar(18) ,
    TAXDETAILSHABITNAME varchar(15) ,
    TAXDETAILSVOLTINISM varchar(25) ,
    TAXDETAILSPOLLTOLERANCE varchar(4) ,
    TAXDETAILSPOLLTOLERANCESCALE varchar(50) ,
    TAXDETAILSTROPHICLEVEL varchar(4) ,
    TAXDETAILSFUNCFEEDINGGROUP varchar(6) ,
    CITATIONRESOURCETITLE varchar(120) ,
    CITATIONRESOURCECREATOR varchar(120) ,
    CITATIONRESOURCESUBJECT varchar(500) ,
    CITATIONRESOURCEPUBLISHER varchar(60) ,
    CITATIONRESOURCEDATE date ,
    CITATIONRESOURCEID varchar(255) ,
    FREQCLASSDESCCODE varchar(50) ,
    FREQCLASSDESCUNITCODE varchar(12) ,
    FREQCLASSLOWERBOUNDVALUE varchar(8) ,
    FREQCLASSUPPERBOUNDVALUE varchar(8) ,
    ANALYTICALMETHODID varchar(20) ,
    ANALYTICALMETHODIDCONTEXT varchar(120) ,
    ANALYTICALMETHODNAME varchar(120) ,
    ANALYTICALMETHODQUALIFIERTYPE varchar(25) ,
    ANALYTICALMETHODDESC varchar(500) ,
    LABNAME varchar(60) ,
    LABANALYSISSTARTDATE date ,
    LABANALYSISSTARTTIME varchar(20) ,
    LABANALYSISSTARTTIMEZONECODE varchar(4) ,
    LABANALYSISENDDATE date ,
    LABANALYSISENDTIME varchar(20) ,
    LABANALYSISENDTIMEZONECODE varchar(4) ,
    RESULTLABCOMMENTCODE varchar(3) ,
    LABACCIND char(1) ,
    LABACCAUTHORITYNAME varchar(20) ,
    LABTAXACCIND char(1) ,
    LABTAXACCAUTHORITYNAME varchar(20) ,
    TMPACTIVITYID varchar(35)
 CONSTRAINT PK_WQX_RESULT PRIMARY KEY  
(
    RECORDID 
)) 
/





CREATE TABLE NODE.WQX_ACTATTACHEDBINARYOBJECT(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    BINARYOBJECTFILE varchar(255) NOT NULL,
    BINARYOBJECTFILETYPECODE varchar(6) NOT NULL,
 CONSTRAINT PK_WQX_ACTATBINOBJ PRIMARY KEY  
(
    RECORDID 
)) 
/





CREATE TABLE NODE.WQX_ACTIVITYCONDUCTINGORG(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    ACTIVITYID varchar(35) NOT NULL,
    ACTIVITYCONDUCTINGORG varchar(120) NOT NULL,
 CONSTRAINT PK_WQX_ACTCONDGORG PRIMARY KEY  
(
    RECORDID 
)) 
/





CREATE TABLE NODE.WQX_ACTIVITYMETRIC(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    METRICTYPEID varchar(35) NOT NULL,
    METRICTYPEIDCONTEXT varchar(50) NOT NULL,
    METRICTYPENAME varchar(50) ,
    CITATIONRESOURCETITLE varchar(120) ,
    CITATIONRESOURCECREATOR varchar(120) ,
    CITATIONRESOURCESUBJECT varchar(500) ,
    CITATIONRESOURCEPUBLISHER varchar(60) ,
    CITATIONRESOURCEDATE date ,
    CITATIONRESOURCEID varchar(255) ,
    METRICTYPESCALE varchar(50) ,
    METRICTYPEFORMULADESC varchar(50) ,
    METRICVALUEMEASURE varchar(12) ,
    METRICVALUEMEASUREUNIT varchar(12) ,
    METRICSCORE varchar(10) ,
    METRICCOMMENT varchar(4000) ,
    METRICINDEXID varchar(35) ,
 CONSTRAINT PK_WQX_ACTIVITYMET PRIMARY KEY  
(
    RECORDID 
)) 
/





CREATE TABLE NODE.WQX_RESULTATTACHEDBINARYOBJECT(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    BINARYOBJECTFILE varchar(255) NOT NULL,
    BINARYOBJECTFILETYPECODE varchar(6) NOT NULL,
 CONSTRAINT PK_WQX_RSLTATBINOB PRIMARY KEY  
(
    RECORDID 
)) 
/





CREATE TABLE NODE.WQX_RESULTDETECTQUANTLIMIT(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    DETECTQUANTLIMITTYPE varchar(35) NOT NULL,
    DETECTQUANTLIMITMEASURE varchar(12) ,
    DETECTQUANTLIMITMEASUNITCODE varchar(12) ,
 CONSTRAINT PK_WQX_RSLTDTQNTLT PRIMARY KEY  
(
    RECORDID 
)) 
/





CREATE TABLE NODE.WQX_LABSAMPLEPREP(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    METHODID varchar(20) NOT NULL,
    METHODIDCONTEXT varchar(120) NOT NULL,
    METHODNAME varchar(120) NOT NULL,
    METHODQUALIFIERTYPE varchar(25) ,
    METHODDESC varchar(500) ,
    PREPSTARTDATE date ,
    PREPSTARTTIME varchar(20) ,
    PREPSTARTTIMEZONECODE varchar(4) ,
    PREPENDDATE date ,
    PREPENDTIME varchar(20) ,
    PREPENDTIMEZONECODE varchar(4) ,
    SUBSTANCEDILUTIONFACTOR varchar(10) ,
 CONSTRAINT PK_WQX_LABSAMPPREP PRIMARY KEY  
(
    RECORDID 
))
/





CREATE TABLE NODE.WQX_ACTIVITY(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    ACTIVITYID varchar(35) NOT NULL,
    ACTIVITYTYPECODE varchar(70) NOT NULL,
    ACTIVITYMEDIA varchar(20) NOT NULL,
    ACTIVITYMEDIASUBDIVISION varchar(45) ,
    ACTIVITYSTARTDATE date NOT NULL,
    STARTTIME varchar(20) ,
    STARTTIMEZONE varchar(4) ,
    ACTIVITYENDDATE date ,
    ENDTIME varchar(20) ,
    ENDTIMEZONE varchar(4) ,
    RELATIVEDEPTH varchar(15) ,
    DEPTHHEIGHTMEASURE varchar(12) ,
    DEPTHHEIGHTMEASUREUNIT varchar(12) ,
    TOPDEPTHHEIGHTMEASURE varchar(12) ,
    TOPDEPTHHEIGHTMEASUREUNIT varchar(12) ,
    BOTTOMDEPTHHEIGHTMEASURE varchar(12) ,
    BOTTOMDEPTHHEIGHTMEASUREUNIT varchar(12) ,
    DEPTHALTITUDEREFPOINT varchar(125) ,
    MONLOCID varchar(35) ,
    ACTIVITYCOMMENT varchar(4000) ,
    LATITUDEMEASURE varchar(30) ,
    LONGITUDEMEASURE varchar(30) ,
    SOURCEMAPSCALE varchar(12) ,
    HORIZACCURACYMEASURE varchar(12) ,
    HORIZACCURACYMEASUREUNIT varchar(12) ,
    HORIZCOLLMETHOD varchar(150) ,
    HORIZCOORDREFSYSDATUM varchar(6) ,
    BIOACTIVITYASSEMBLAGESAMPD varchar(50) ,
    BIOHABCOLLDURATIONMEASURE varchar(12) ,
    BIOHABCOLLDURATIONMEASUREUNIT varchar(12) ,
    BIOHABSAMPCOMP varchar(15) ,
    BIOHABSAMPCOMPPLACEINSERIES varchar(12) ,
    BIOHABREACHLENGTHMEASURE varchar(12) ,
    BIOHABREACHLENGTHMEASUREUNIT varchar(12) ,
    BIOHABREACHWIDTHMEASURE varchar(12) ,
    BIOHABREACHWIDTHMEASUREUNIT varchar(12) ,
    BIOHABPASSCOUNT varchar(12) ,
    BIOHABNETTYPE varchar(30) ,
    BIOHABNETSURFACEAREAMEASURE varchar(12) ,
    BIOHABNETSURFACEMEASUREUNIT varchar(12) ,
    BIOHABNETMESHSIZEMEASURE varchar(12) ,
    BIOHABNETMESHMEASUREUNIT varchar(12) ,
    BIOHABNETBOATSPEEDMEASURE varchar(12) ,
    BIOHABNETBOATSPEEDMEASUREUNIT varchar(12) ,
    BIOHABNETCURRSPEEDMEASURE varchar(12) ,
    BIOHABNETCURRSPEEDMEASUREUNIT varchar(12) ,
    BIOACTIVITYTOXICITYTESTTYPE varchar(7) ,
    SAMPCOLLMETHODID varchar(20) ,
    SAMPCOLLMETHODIDCONTEXT varchar(120) ,
    SAMPCOLLMETHOD varchar(120) ,
    SAMPCOLLMETHODQUALIFIER varchar(25) ,
    SAMPCOLLMETHODDESC varchar(500) ,
    SAMPCOLLEQUIPMENT varchar(40) ,
    SAMPCOLLEQUIPMENTCOMMENT varchar(4000) ,
    SAMPPREPID varchar(20) ,
    SAMPPREPIDCONTEXT varchar(120) ,
    SAMPPREP varchar(120) ,
    SAMPPREPQUALIFIERTYPE varchar(25) ,
    SAMPPREPDESC varchar(500) ,
    SAMPPREPCONTTYPE varchar(35) ,
    SAMPPREPCONTCOLOR varchar(15) ,
    SAMPPREPCONTCHEMPRESERVUSED varchar(250) ,
    SAMPPREPCONTTHERMALPRESERVUSED varchar(25) ,
    SAMPPREPCONTSAMPTRANSSTORDESC varchar(250) ,
    RESULTCOUNT varchar(255) ,
    WQXUPDATEDATE date NOT NULL,
    TMPACTIVITYTYPE varchar(50) ,
    TMPPROJECTID varchar(50) ,
 CONSTRAINT PK_WQX_ACTIVITY PRIMARY KEY  
(
    RECORDID 
)) 
/





CREATE TABLE NODE.WQX_MONITORINGLOCATION(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    MONITORINGLOCATIONID varchar(35) NOT NULL,
    MONLOCNAME varchar(255) NOT NULL,
    MONLOCTYPE varchar(45) NOT NULL,
    MONLOCDESC varchar(1999) ,
    HUCEIGHTDIGITCODE varchar(8) ,
    HUCTWELVEDIGITCODE varchar(12) ,
    TRIBALLANDIND char(1) NOT NULL,
    TRIBALLANDNAME varchar(200) ,
    LATITUDEMEASURE varchar(30) NOT NULL,
    LONGITUDEMEASURE varchar(30) NOT NULL,
    SOURCEMAPSCALE int ,
    HORIZACCURACYMEASURE varchar(12) ,
    HORIZACCURACYMEASUREUNIT varchar(12) ,
    HORIZCOLLMETHOD varchar(150) NOT NULL,
    HORIZCOORDREFSYSDATUM varchar(6) NOT NULL,
    VERTICALMEASURE varchar(12) ,
    VERTICALMEASUREUNIT varchar(12) ,
    VERTICALCOLLMETHOD varchar(50) ,
    VERTICALCOORDREFSYSDATUM varchar(10) ,
    COUNTRYCODE varchar(2) ,
    STATECODE varchar(2) ,
    COUNTYCODE varchar(3) ,
    WELLTYPE varchar(255) ,
    AQUIFERNAME varchar(120) ,
    FORMATIONTYPE varchar(50) ,
    WELLHOLEDEPTHMEASURE varchar(12) ,
    WELLHOLEDEPTHMEASUREUNIT varchar(12) ,
    WQXUPDATEDATE date NOT NULL,
 CONSTRAINT PK_WQX_MONLOC PRIMARY KEY  
(
    RECORDID 
)) 
/





CREATE TABLE NODE.WQX_ORGADDRESS(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    ADDRESSTYPE varchar(8) ,
    ADDRESS varchar(50) NOT NULL,
    SUPPLEMENTALADDRESS varchar(120) ,
    LOCALITY varchar(30) ,
    STATECODE varchar(2) ,
    POSTALCODE varchar(10) ,
    COUNTRYCODE varchar(2) ,
    COUNTYCODE varchar(3) ,
 CONSTRAINT PK_WQX_ORGADDRESS PRIMARY KEY  
(
    RECORDID 
)) 
/





CREATE TABLE NODE.WQX_DELETES(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    COMPONENT varchar(50) NOT NULL,
    IDENTIFIER varchar(50) NOT NULL,
    WQXUPDATEDATE date NOT NULL,
 CONSTRAINT PK_WQX_DELETES PRIMARY KEY  
(
    RECORDID 
)) 

/




CREATE TABLE NODE.WQX_SUBMISSIONHISTORY(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    SCHEDULERUNDATE date NOT NULL,
    WQXUPDATEDATE date NOT NULL,
    SUBMISSIONTYPE varchar(13) NOT NULL,
    LOCALTRANSACTIONID varchar(50) NOT NULL,
    CDXPROCESSINGSTATUS varchar(50) NOT NULL,
 CONSTRAINT PK_WQX_SUBHIST PRIMARY KEY  
(
    RECORDID 
)) 
/

CREATE TABLE NODE.WQX_TELEPHONIC(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    TELEPHONENUMBER varchar(15) NOT NULL,
    TELEPHONENUMBERTYPE varchar(6) ,
    TELEPHONEEXT varchar(6) ,
 CONSTRAINT PK_WQX_TELEPHONIC PRIMARY KEY  
(
    RECORDID)) 
/

CREATE TABLE NODE.WQX_BIOLOGICALHABITATINDEX(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    INDEXID varchar(35) NOT NULL,
    INDEXTYPEID varchar(35) NOT NULL,
    INDEXTYPEIDCONTEXT varchar(50) NOT NULL,
    INDEXTYPENAME varchar(50) NOT NULL,
    RESOURCETITLE varchar(120) ,
    RESOURCECREATOR varchar(120) ,
    RESOURCESUBJECT varchar(500) ,
    RESOURCEPUBLISHER varchar(60) ,
    RESOURCEDATE varchar(10) ,
    RESOURCEID varchar(255) ,
    INDEXTYPESCALE varchar(50) ,
    INDEXSCORE varchar(10) NOT NULL,
    INDEXQUALIFIERCODE varchar(5) ,
    INDEXCOMMENT varchar(4000) ,
    INDEXCALCULATEDDATE varchar(10) ,
    MONLOCID varchar(35) NOT NULL,
    WQXUPDATEDATE date NOT NULL,
 CONSTRAINT PK_WQX_BIOHAINDEX PRIMARY KEY  
(
    RECORDID 
)) 
/

CREATE TABLE NODE.WQX_ELECTRONICADDRESS(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    ELECTRONICADDRESS varchar(120) NOT NULL,
    ELECTRONICADDRESSTYPE varchar(8) ,
 CONSTRAINT PK_WQX_ELECTICAD PRIMARY KEY  
(
    RECORDID)) 
/

CREATE TABLE NODE.WQX_ACTIVITYGROUP(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    ACTIVITYGROUPID varchar(35) NOT NULL,
    ACTIVITYGROUPNAME varchar(50) NOT NULL,
    ACTIVITYGROUPTYPECODE varchar(50) NOT NULL,
    ACTIVITYID varchar(35) NOT NULL,
    WQXUPDATEDATE date NOT NULL,
 CONSTRAINT PK_WQX_ACTGROUP PRIMARY KEY  
(
    RECORDID)) 
/

CREATE TABLE NODE.WQX_PROJECT(
    RECORDID varchar(50) NOT NULL ,
    PARENTID varchar(50) NOT NULL,
    PROJECTID varchar(35) NOT NULL,
    PROJECTNAME varchar(120) NOT NULL,
    PROJECTDESC varchar(1999) ,
    SAMPLINGDESIGNTYPECODE varchar(20) ,
    QAPPAPPROVEDIND char(1) ,
    QAPPAPPROVALAGENCYNAME varchar(50) ,
    WQXUPDATEDATE date NOT NULL,
 CONSTRAINT PK_WQX_PROJECT PRIMARY KEY  
(
    RECORDID)) 
/

CREATE TABLE NODE.WQX_MONLOCATTACHEDBINARYOBJECT(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    BINARYOBJECTFILE varchar(255) NOT NULL,
    BINARYOBJECTFILETYPECODE varchar(6) NOT NULL,
 CONSTRAINT PK_WQX_MNLCTBNBJ PRIMARY KEY  
(
    RECORDID)) 
/

CREATE TABLE NODE.WQX_ALTMONLOC(
    RECORDID varchar(50) NOT NULL,
    PARENTID varchar(50) NOT NULL,
    MONLOCID varchar(35) NOT NULL,
    MONLOCIDCONTEXT varchar(120) NOT NULL,
 CONSTRAINT PK_WQX_ALTMONLOC PRIMARY KEY  
(
    RECORDID)) 
/

ALTER TABLE NODE.WQX_PROJECTACTIVITY   ADD  CONSTRAINT FK_ACT_PACTIVITY FOREIGN KEY(ACTIVITYPARENTID)
REFERENCES NODE.WQX_ACTIVITY (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_PROJECTACTIVITY  ADD  CONSTRAINT FK_PROJ_ACTIVITY FOREIGN KEY(PROJECTPARENTID)
REFERENCES NODE.WQX_PROJECT (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_PROJECTMONLOC   ADD  CONSTRAINT FK_PROJ_PRJCTMNLC FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_PROJECT (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_PROJATTACHEDBINARYOBJECT  ADD  CONSTRAINT FK_PRJECT_PRJTBNBJ FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_PROJECT (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_ACTIVITYACTIVITYGROUP   ADD  CONSTRAINT FK_ACT_ACTCTGRP FOREIGN KEY(ACTIVITYPARENTID)
REFERENCES NODE.WQX_ACTIVITY (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_ACTIVITYACTIVITYGROUP   ADD  CONSTRAINT FK_AG_ACTACTGROUP FOREIGN KEY(ACTIVITYGROUPPARENTID)
REFERENCES NODE.WQX_ACTIVITYGROUP (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_RESULT   ADD  CONSTRAINT FK_ACT_RESULT FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ACTIVITY (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_ACTATTACHEDBINARYOBJECT  ADD  CONSTRAINT FK_ACT_CTTTBNBJ FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ACTIVITY (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_ACTIVITYCONDUCTINGORG   ADD  CONSTRAINT FK_ACT_CTCNDCTNGRG FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ACTIVITY (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_ACTIVITYMETRIC   ADD  CONSTRAINT FK_ACT_ACTMETRIC FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ACTIVITY (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_RESULTATTACHEDBINARYOBJECT  ADD  CONSTRAINT FK_RSLT_RSLTATBNBJ FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_RESULT (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_RESULTDETECTQUANTLIMIT  ADD  CONSTRAINT FK_RSLT_RSLTQNTLMT FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_RESULT (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_LABSAMPLEPREP  ADD  CONSTRAINT FK_RESULT_LABSAMP FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_RESULT (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_ACTIVITY  ADD  CONSTRAINT FK_ORG_ACTIVITY FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ORGANIZATION (RECORDID)
ON DELETE CASCADE
/
ALTER TABLE NODE.WQX_MONITORINGLOCATION  ADD  CONSTRAINT FK_ORG_MONLOC FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ORGANIZATION (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_ORGADDRESS  ADD  CONSTRAINT FK_ORG_ORGAD FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ORGANIZATION (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_DELETES   ADD  CONSTRAINT FK_WQX_DEL_WQX_ORG FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ORGANIZATION (RECORDID)
/

ALTER TABLE NODE.WQX_SUBMISSIONHISTORY   ADD  CONSTRAINT FK_SBMSSNHST_ORG FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ORGANIZATION (RECORDID)
/

ALTER TABLE NODE.WQX_TELEPHONIC   ADD  CONSTRAINT FK_ORG_TELEPHONIC FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ORGANIZATION (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_BIOLOGICALHABITATINDEX   ADD  CONSTRAINT FK_ORG_BIOHABTAT FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ORGANIZATION (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_ELECTRONICADDRESS  ADD  CONSTRAINT FK_ORG_ELECADD FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ORGANIZATION (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_ACTIVITYGROUP  ADD  CONSTRAINT FK_ORG_ACTGRP FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ORGANIZATION (RECORDID)
/

ALTER TABLE NODE.WQX_PROJECT   ADD  CONSTRAINT FK_ORG_PROJECT FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_ORGANIZATION (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_MONLOCATTACHEDBINARYOBJECT  ADD  CONSTRAINT FK_MON_MNLCTTBNBJ FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_MONITORINGLOCATION (RECORDID)
ON DELETE CASCADE
/

ALTER TABLE NODE.WQX_ALTMONLOC   ADD  CONSTRAINT FK_MONLOC_ALTNLC FOREIGN KEY(PARENTID)
REFERENCES NODE.WQX_MONITORINGLOCATION (RECORDID)
ON DELETE CASCADE
/
