
DELETE FROM BEACH_ACTIVITY
GO
DELETE FROM BEACH
GO

--Insert 2 Beaches
INSERT INTO [BEACH]
           ([EPA_BEACH_ID],[BEACH_NAME],[BEACH_DESCRIPTION],[STATE_CD],[FIPS_CD],[WATERBODY_NAME_CD],[ACCESSIBILITY_TYPE_CD])
     VALUES('MI000286', 'Thompson Park', 'Thunder Bay' ,'MI' ,'32001', 'LAKE_HURON', 'PUB_PUB_ACC')
GO

INSERT INTO [BEACH]
           ([EPA_BEACH_ID],[BEACH_NAME],[BEACH_DESCRIPTION],[STATE_CD],[FIPS_CD],[WATERBODY_NAME_CD],[ACCESSIBILITY_TYPE_CD])
     VALUES('MI000309','Traverse City Park Beach','Traverse City','MI', '32002', 'LAKE_MCHGN', 'PUB_PUB_ACC')
GO

--Insert 2 Closures for Thompson Park
INSERT INTO [BEACH_ACTIVITY]
           ([ACTIVITY_ID], [EPA_BEACH_ID],[ACTIVITY_TYPE],[ACTIVITY_NAME],[START_DATE],[REOPEN_DATE],[REASON_TYPE_CD],[POLLUTION_SOURCE_CD],[INDICATOR_TYPE_CD])
     VALUES
           ('1111', 'MI000286','CLOSURE','Beach Closure','6/1/2009','6/3/2009','ELEV_BACT','RUNOFF','ECOLI')
GO

INSERT INTO [BEACH_ACTIVITY]
           ([ACTIVITY_ID], [EPA_BEACH_ID],[ACTIVITY_TYPE],[ACTIVITY_NAME],[START_DATE],[REOPEN_DATE],[REASON_TYPE_CD],[POLLUTION_SOURCE_CD],[INDICATOR_TYPE_CD])
     VALUES
           ('2222', 'MI000286','CLOSURE','Beach Closure','6/6/2009','6/7/2009','ELEV_BACT','RUNOFF','ECOLI')
GO