#region License
/*
Copyright (c) 2009, The Environmental Council of the States (ECOS)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/
#endregion

﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Windsor.Node2008.WNOS.Service.GetServices {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="NetworkNodeListType", Namespace="http://www.exchangenetwork.net/schema/ends/2")]
    [System.Xml.Serialization.XmlRootAttribute("NetworkNodes", Namespace="http://www.exchangenetwork.net/schema/ends/2", IsNullable=false)]
    public partial class NetworkNodeListType1 {
        
        private NetworkNodeType[] networkNodeDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NetworkNodeDetails")]
        public NetworkNodeType[] NetworkNodeDetails {
            get {
                return this.networkNodeDetailsField;
            }
            set {
                this.networkNodeDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/ends/2")]
    public partial class NetworkNodeType {
        
        private string nodeIdentifierField;
        
        private string nodeNameField;
        
        private string nodeAddressField;
        
        private string organizationIdentifierField;
        
        private string nodeContactField;
        
        private NodeVersionCode nodeVersionIdentifierField;
        
        private NodeStageCode nodeDeploymentTypeCodeField;
        
        private NodeStatusCode nodeStatusField;
        
        private ObjectPropertyType[] nodePropertyField;
        
        private NodeBoundingBoxType boundingBoxDetailsField;
        
        private ServiceDescriptionListTypeService[] nodeServiceListField;
        
        /// <remarks/>
        public string NodeIdentifier {
            get {
                return this.nodeIdentifierField;
            }
            set {
                this.nodeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string NodeName {
            get {
                return this.nodeNameField;
            }
            set {
                this.nodeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string NodeAddress {
            get {
                return this.nodeAddressField;
            }
            set {
                this.nodeAddressField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationIdentifier {
            get {
                return this.organizationIdentifierField;
            }
            set {
                this.organizationIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string NodeContact {
            get {
                return this.nodeContactField;
            }
            set {
                this.nodeContactField = value;
            }
        }
        
        /// <remarks/>
        public NodeVersionCode NodeVersionIdentifier {
            get {
                return this.nodeVersionIdentifierField;
            }
            set {
                this.nodeVersionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public NodeStageCode NodeDeploymentTypeCode {
            get {
                return this.nodeDeploymentTypeCodeField;
            }
            set {
                this.nodeDeploymentTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public NodeStatusCode NodeStatus {
            get {
                return this.nodeStatusField;
            }
            set {
                this.nodeStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NodeProperty")]
        public ObjectPropertyType[] NodeProperty {
            get {
                return this.nodePropertyField;
            }
            set {
                this.nodePropertyField = value;
            }
        }
        
        /// <remarks/>
        public NodeBoundingBoxType BoundingBoxDetails {
            get {
                return this.boundingBoxDetailsField;
            }
            set {
                this.boundingBoxDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Service", IsNullable=false)]
        public ServiceDescriptionListTypeService[] NodeServiceList {
            get {
                return this.nodeServiceListField;
            }
            set {
                this.nodeServiceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/ends/2")]
    public enum NodeVersionCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.1")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.0")]
        Item20,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/ends/2")]
    public enum NodeStageCode {
        
        /// <remarks/>
        Development,
        
        /// <remarks/>
        Test,
        
        /// <remarks/>
        Production,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/ends/2")]
    public enum NodeStatusCode {
        
        /// <remarks/>
        Operational,
        
        /// <remarks/>
        Busy,
        
        /// <remarks/>
        Offline,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/ends/2")]
    public partial class ObjectPropertyType {
        
        private string propertyNameField;
        
        private object propertyValueField;
        
        /// <remarks/>
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
        
        /// <remarks/>
        public object PropertyValue {
            get {
                return this.propertyValueField;
            }
            set {
                this.propertyValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/ends/2")]
    public partial class RequestParameterType {
        
        private string parameterNameField;
        
        private string parameterTypeField;
        
        private string parameterTypeDescriptorField;
        
        private bool parameterRequiredIndicatorField;
        
        private EncodingType parameterEncodingField;
        
        private string parameterSortIndexField;
        
        private string parameterOccurrenceNumberField;
        
        private string valueField;
        
        public RequestParameterType() {
            this.parameterRequiredIndicatorField = true;
            this.parameterEncodingField = EncodingType.None;
            this.parameterOccurrenceNumberField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParameterName {
            get {
                return this.parameterNameField;
            }
            set {
                this.parameterNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParameterType {
            get {
                return this.parameterTypeField;
            }
            set {
                this.parameterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParameterTypeDescriptor {
            get {
                return this.parameterTypeDescriptorField;
            }
            set {
                this.parameterTypeDescriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ParameterRequiredIndicator {
            get {
                return this.parameterRequiredIndicatorField;
            }
            set {
                this.parameterRequiredIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(EncodingType.None)]
        public EncodingType ParameterEncoding {
            get {
                return this.parameterEncodingField;
            }
            set {
                this.parameterEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string ParameterSortIndex {
            get {
                return this.parameterSortIndexField;
            }
            set {
                this.parameterSortIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string ParameterOccurrenceNumber {
            get {
                return this.parameterOccurrenceNumberField;
            }
            set {
                this.parameterOccurrenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/ends/2")]
    public enum EncodingType {
        
        /// <remarks/>
        Base64,
        
        /// <remarks/>
        ZIP,
        
        /// <remarks/>
        Encrypt,
        
        /// <remarks/>
        Digest,
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/ends/2")]
    public partial class NodeBoundingBoxType {
        
        private decimal boundingCoordinateEastField;
        
        private decimal boundingCoordinateNorthField;
        
        private decimal boundingCoordinateSouthField;
        
        private decimal boundingCoordinateWestField;
        
        /// <remarks/>
        public decimal BoundingCoordinateEast {
            get {
                return this.boundingCoordinateEastField;
            }
            set {
                this.boundingCoordinateEastField = value;
            }
        }
        
        /// <remarks/>
        public decimal BoundingCoordinateNorth {
            get {
                return this.boundingCoordinateNorthField;
            }
            set {
                this.boundingCoordinateNorthField = value;
            }
        }
        
        /// <remarks/>
        public decimal BoundingCoordinateSouth {
            get {
                return this.boundingCoordinateSouthField;
            }
            set {
                this.boundingCoordinateSouthField = value;
            }
        }
        
        /// <remarks/>
        public decimal BoundingCoordinateWest {
            get {
                return this.boundingCoordinateWestField;
            }
            set {
                this.boundingCoordinateWestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.exchangenetwork.net/schema/ends/2")]
    public partial class ServiceDescriptionListTypeService {
        
        private NodeMethodTypeCode methodNameField;
        
        private string dataflowField;
        
        private string serviceIdentifierField;
        
        private string serviceDescriptionField;
        
        private string serviceDocumentURLField;
        
        private ObjectPropertyType[] servicePropertyField;
        
        private string[] styleSheetURLField;
        
        private RequestParameterType[] parameterField;
        
        /// <remarks/>
        public NodeMethodTypeCode MethodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
        
        /// <remarks/>
        public string Dataflow {
            get {
                return this.dataflowField;
            }
            set {
                this.dataflowField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceIdentifier {
            get {
                return this.serviceIdentifierField;
            }
            set {
                this.serviceIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceDescription {
            get {
                return this.serviceDescriptionField;
            }
            set {
                this.serviceDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string ServiceDocumentURL {
            get {
                return this.serviceDocumentURLField;
            }
            set {
                this.serviceDocumentURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceProperty")]
        public ObjectPropertyType[] ServiceProperty {
            get {
                return this.servicePropertyField;
            }
            set {
                this.servicePropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StyleSheetURL", DataType="anyURI")]
        public string[] StyleSheetURL {
            get {
                return this.styleSheetURLField;
            }
            set {
                this.styleSheetURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public RequestParameterType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exchangenetwork.net/schema/ends/2")]
    public enum NodeMethodTypeCode {
        
        /// <remarks/>
        Query,
        
        /// <remarks/>
        Solicit,
        
        /// <remarks/>
        Submit,
        
        /// <remarks/>
        Execute,
    }
}
