select * from WQX_ORGANIZATION
select * from WQX_ELECTRONICADDRESS
select * from WQX_TELEPHONIC
select * from WQX_ORGADDRESS
select * from WQX_PROJECT
select * from WQX_PROJATTACHEDBINARYOBJECT -- empty
select * from WQX_PROJECTMONLOC -- empty
select * from WQX_MONITORINGLOCATION where parentid='1'
select * from WQX_ALTMONLOC -- empty
select * from WQX_MONLOCATTACHEDBINARYOBJECT -- empty
select * from WQX_BIOLOGICALHABITATINDEX -- empty
select * from WQX_ACTIVITY
select * from WQX_ACTIVITYGROUP
select * from WQX_PROJECTACTIVITY
select * from WQX_ACTIVITYCONDUCTINGORG
select * from WQX_ACTIVITYMETRIC
select * from WQX_ACTATTACHEDBINARYOBJECT
select * from WQX_RESULT
select * from WQX_RESULTATTACHEDBINARYOBJECT
select * from WQX_RESULTDETECTQUANTLIMIT
select * from WQX_LABSAMPLEPREP

select * from WQX_SUBMISSIONHISTORY

select * from WQX_ACTIVITYGROUP

delete from WQX_SUBMISSIONHISTORY

select MAX(WQXUPDATEDATE) from WQX_SUBMISSIONHISTORY where CDXPROCESSINGSTATUS = 'Pending' 


SELECT projectid FROM WQX_PROJECT WHERE WQX_PROJECT.RECORDID IN (SELECT projectparentid FROM WQX_PROJECTACTIVITY WHERE WQX_PROJECTACTIVITY.ACTIVITYPARENTID = ?)

SELECT activityconductingorg FROM WQX_ACTIVITYCONDUCTINGORG WHERE PARENTID = ? AND ACTIVITYID = ?


SELECT * FROM WQX_PROJECT WHERE PARENTID = '1' AND WQXUPDATEDATE >= '1900-01-01 01:00:0'

SELECT * FROM WQX_BIOLOGICALHABITATINDEX WHERE PARENTID = '1' AND WQXUPDATEDATE >= '1900-01-01 01:00:0'