--------------------------------------------------------
--  File created - Monday-April-20-2009   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table NACCOUNT
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NACCOUNT" 
   (	"ID" VARCHAR2(50 BYTE), 
	"NAASACCOUNT" VARCHAR2(500 BYTE), 
	"ISACTIVE" CHAR(1 BYTE), 
	"SYSTEMROLE" VARCHAR2(50 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE, 
	"ISDELETED" CHAR(1 BYTE), 
	"ISDEMOUSER" CHAR(1 BYTE), 
	"PASSWORDHASH" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NACCOUNTPOLICY
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NACCOUNTPOLICY" 
   (	"ID" VARCHAR2(50 BYTE), 
	"ACCOUNTID" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"QUALIFIER" VARCHAR2(500 BYTE), 
	"ISALLOWED" CHAR(1 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NACTIVITY
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NACTIVITY" 
   (	"ID" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(128 BYTE), 
	"TRANSACTIONID" VARCHAR2(50 BYTE), 
	"IP" VARCHAR2(64 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE, 
	"WEBMETHOD" VARCHAR2(50 BYTE), 
	"FLOWNAME" VARCHAR2(255 BYTE), 
	"OPERATION" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NACTIVITYDETAIL
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NACTIVITYDETAIL" 
   (	"ID" VARCHAR2(50 BYTE), 
	"ACTIVITYID" VARCHAR2(50 BYTE), 
	"DETAIL" VARCHAR2(4000 BYTE), 
	"MODIFIEDON" DATE, 
	"ORDERINDEX" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NCONFIG
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NCONFIG" 
   (	"ID" VARCHAR2(255 BYTE), 
	"VALUE" VARCHAR2(4000 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE, 
	"ISEDITABLE" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NCONNECTION
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NCONNECTION" 
   (	"ID" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(255 BYTE), 
	"PROVIDER" VARCHAR2(500 BYTE), 
	"CONNECTIONSTRING" VARCHAR2(500 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NDOCUMENT
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NDOCUMENT" 
   (	"ID" VARCHAR2(50 BYTE), 
	"TRANSACTIONID" VARCHAR2(50 BYTE), 
	"DOCUMENTNAME" VARCHAR2(255 BYTE), 
	"TYPE" VARCHAR2(255 BYTE), 
	"DOCUMENTID" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"STATUSDETAIL" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NDOCUMENTCONTENT
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NDOCUMENTCONTENT" 
   (	"DOCUMENTID" VARCHAR2(50 BYTE), 
	"DATA" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" 
 LOB ("DATA") STORE AS (
  TABLESPACE "OPENNODE2_NET" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 
--------------------------------------------------------
--  DDL for Table NFLOW
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NFLOW" 
   (	"ID" VARCHAR2(50 BYTE), 
	"INFOURL" VARCHAR2(500 BYTE), 
	"CONTACT" VARCHAR2(255 BYTE), 
	"ISPROTECTED" CHAR(1 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE, 
	"CODE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NNODENOTIFICATION
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NNODENOTIFICATION" 
   (	"ID" VARCHAR2(50 BYTE), 
	"TRANSACTIONID" VARCHAR2(50 BYTE), 
	"NOTIFYDATA" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NNOTIFICATION
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NNOTIFICATION" 
   (	"ID" VARCHAR2(50 BYTE), 
	"FLOWID" VARCHAR2(50 BYTE), 
	"ACCOUNTID" VARCHAR2(50 BYTE), 
	"ONSOLICIT" CHAR(1 BYTE), 
	"ONQUERY" CHAR(1 BYTE), 
	"ONSUBMIT" CHAR(1 BYTE), 
	"ONNOTIFY" CHAR(1 BYTE), 
	"ONSCHEDULE" CHAR(1 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE, 
	"ONDOWNLOAD" CHAR(1 BYTE), 
	"ONEXECUTE" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NOBJECTCACHE
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NOBJECTCACHE" 
   (	"NAME" VARCHAR2(255 BYTE), 
	"MODIFIEDON" DATE, 
	"EXPIRATION" DATE, 
	"DATA" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" 
 LOB ("DATA") STORE AS (
  TABLESPACE "OPENNODE2_NET" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 
--------------------------------------------------------
--  DDL for Table NPARTNER
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NPARTNER" 
   (	"ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"URL" VARCHAR2(500 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE, 
	"VERSION" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NPLUGIN
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NPLUGIN" 
   (	"ID" VARCHAR2(50 BYTE), 
	"FLOWID" VARCHAR2(50 BYTE), 
	"BINARYVERSION" VARCHAR2(40 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE, 
	"ZIPPEDBINARY" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" 
 LOB ("ZIPPEDBINARY") STORE AS (
  TABLESPACE "OPENNODE2_NET" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 
--------------------------------------------------------
--  DDL for Table NREQUEST
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NREQUEST" 
   (	"ID" VARCHAR2(50 BYTE), 
	"TRANSACTIONID" VARCHAR2(50 BYTE), 
	"SERVICEID" VARCHAR2(50 BYTE), 
	"ROWINDEX" NUMBER, 
	"MAXROWCOUNT" NUMBER, 
	"REQUESTTYPE" VARCHAR2(50 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE, 
	"PARAMSBYNAME" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NREQUESTARG
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NREQUESTARG" 
   (	"ID" VARCHAR2(50 BYTE), 
	"REQUESTID" VARCHAR2(50 BYTE), 
	"ARGNAME" VARCHAR2(255 BYTE), 
	"ARGVALUE" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NSCHEDULE
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NSCHEDULE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"FLOWID" VARCHAR2(50 BYTE), 
	"STARTON" DATE, 
	"ENDON" DATE, 
	"SOURCETYPE" VARCHAR2(50 BYTE), 
	"SOURCEID" VARCHAR2(255 BYTE), 
	"SOURCEOPERATION" VARCHAR2(255 BYTE), 
	"TARGETTYPE" VARCHAR2(50 BYTE), 
	"TARGETID" VARCHAR2(255 BYTE), 
	"LASTEXECUTEDON" DATE, 
	"NEXTRUN" DATE, 
	"FREQUENCYTYPE" VARCHAR2(50 BYTE), 
	"FREQUENCY" NUMBER, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE, 
	"ISACTIVE" VARCHAR2(1 BYTE), 
	"ISRUNNOW" VARCHAR2(1 BYTE), 
	"EXECUTESTATUS" VARCHAR2(50 BYTE), 
	"TARGETOPERATION" VARCHAR2(255 BYTE), 
	"TARGETFLOW" VARCHAR2(255 BYTE), 
	"SOURCEFLOW" VARCHAR2(255 BYTE), 
	"LASTEXECUTEACTIVITYID" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NSCHEDULESOURCEARG
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NSCHEDULESOURCEARG" 
   (	"ID" VARCHAR2(50 BYTE), 
	"SCHEDULEID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"VALUE" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NSERVICE
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NSERVICE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"FLOWID" VARCHAR2(50 BYTE), 
	"ISACTIVE" CHAR(1 BYTE), 
	"SERVICETYPE" VARCHAR2(128 BYTE), 
	"IMPLEMENTOR" VARCHAR2(500 BYTE), 
	"AUTHLEVEL" VARCHAR2(50 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE,
	"PUBLISHFLAGS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NSERVICEARG
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NSERVICEARG" 
   (	"ID" VARCHAR2(50 BYTE), 
	"SERVICEID" VARCHAR2(50 BYTE), 
	"ARGCODE" VARCHAR2(255 BYTE), 
	"VALUE" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NSERVICECONN
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NSERVICECONN" 
   (	"ID" VARCHAR2(50 BYTE), 
	"SERVICEID" VARCHAR2(50 BYTE), 
	"CONNECTIONID" VARCHAR2(50 BYTE), 
	"KEYNAME" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NTRANSACTION
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NTRANSACTION" 
   (	"ID" VARCHAR2(50 BYTE), 
	"FLOWID" VARCHAR2(50 BYTE), 
	"NETWORKID" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE, 
	"STATUSDETAIL" VARCHAR2(4000 BYTE), 
	"OPERATION" VARCHAR2(255 BYTE), 
	"WEBMETHOD" VARCHAR2(50 BYTE), 
	"ENDPOINTVERSION" VARCHAR2(50 BYTE), 
	"NETWORKENDPOINTVERSION" VARCHAR2(50 BYTE), 
	"NETWORKENDPOINTURL" VARCHAR2(500 BYTE), 
	"NETWORKENDPOINTSTATUS" VARCHAR2(50 BYTE), 
	"NETWORKENDPOINTSTATUSDETAIL" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NTRANSACTIONNOTIFICATION
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NTRANSACTIONNOTIFICATION" 
   (	"ID" VARCHAR2(50 BYTE), 
	"TRANSACTIONID" VARCHAR2(50 BYTE), 
	"URI" VARCHAR2(500 BYTE), 
	"TYPE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NTRANSACTIONREALTIMEDETAILS
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NTRANSACTIONREALTIMEDETAILS" 
   (	"ID" VARCHAR2(50 BYTE), 
	"STATUSTYPE" VARCHAR2(50 BYTE), 
	"TRANSACTIONID" VARCHAR2(50 BYTE), 
	"MODIFIEDON" DATE, 
	"ORDERINDEX" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  DDL for Table NTRANSACTIONRECIPIENT
--------------------------------------------------------

  CREATE TABLE "OPENNODE2_NET"."NTRANSACTIONRECIPIENT" 
   (	"ID" VARCHAR2(50 BYTE), 
	"TRANSACTIONID" VARCHAR2(50 BYTE), 
	"URI" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "OPENNODE2_NET" ;
 
--------------------------------------------------------
--  Constraints for Table NACCOUNTPOLICY
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NACCOUNTPOLICY" ADD CONSTRAINT "PK_NACCOUNTPOLICY" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNTPOLICY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNTPOLICY" MODIFY ("ACCOUNTID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNTPOLICY" MODIFY ("TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNTPOLICY" MODIFY ("QUALIFIER" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNTPOLICY" MODIFY ("ISALLOWED" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNTPOLICY" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNTPOLICY" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NACTIVITY
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NACTIVITY" ADD CONSTRAINT "PK_ACTIVITY" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NACTIVITY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACTIVITY" MODIFY ("TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACTIVITY" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACTIVITY" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NACTIVITYDETAIL
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NACTIVITYDETAIL" ADD CONSTRAINT "PK_ACTIVITYDETAIL" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NACTIVITYDETAIL" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACTIVITYDETAIL" MODIFY ("ACTIVITYID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACTIVITYDETAIL" MODIFY ("DETAIL" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACTIVITYDETAIL" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NACCOUNT
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NACCOUNT" ADD CONSTRAINT "PK_ACCOUNT" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNT" MODIFY ("NAASACCOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNT" MODIFY ("ISACTIVE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNT" MODIFY ("SYSTEMROLE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNT" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNT" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNT" ADD CONSTRAINT "UNQ_ACCOUNT_NAASACCOUNT" UNIQUE ("NAASACCOUNT") ENABLE;
 
--------------------------------------------------------
--  Constraints for Table NCONFIG
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NCONFIG" ADD CONSTRAINT "PK_CONFIG" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NCONFIG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NCONFIG" MODIFY ("VALUE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NCONFIG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NCONFIG" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NCONFIG" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NCONFIG" MODIFY ("ISEDITABLE" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NCONNECTION
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NCONNECTION" ADD CONSTRAINT "PK_CONNECTION" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NCONNECTION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NCONNECTION" MODIFY ("CODE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NCONNECTION" MODIFY ("PROVIDER" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NCONNECTION" MODIFY ("CONNECTIONSTRING" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NCONNECTION" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NCONNECTION" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NCONNECTION" ADD CONSTRAINT "UNQ_CONNECTION_CODE" UNIQUE ("CODE") ENABLE;
 
--------------------------------------------------------
--  Constraints for Table NDOCUMENT
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NDOCUMENT" ADD CONSTRAINT "PK_DOCUMENT" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NDOCUMENT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NDOCUMENT" MODIFY ("TRANSACTIONID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NDOCUMENT" MODIFY ("DOCUMENTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NDOCUMENT" MODIFY ("TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NDOCUMENT" MODIFY ("DOCUMENTID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NDOCUMENT" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NDOCUMENT" ADD CONSTRAINT "UNQ_DOC_TRANSIDDOCNAME" UNIQUE ("DOCUMENTNAME", "TRANSACTIONID") ENABLE;
 
--------------------------------------------------------
--  Constraints for Table NDOCUMENTCONTENT
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NDOCUMENTCONTENT" ADD CONSTRAINT "PK_NDOCUMENTCONTENT" PRIMARY KEY ("DOCUMENTID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NDOCUMENTCONTENT" MODIFY ("DOCUMENTID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NDOCUMENTCONTENT" MODIFY ("DATA" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NFLOW
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NFLOW" ADD CONSTRAINT "PK_FLOW" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NFLOW" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NFLOW" MODIFY ("INFOURL" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NFLOW" MODIFY ("CONTACT" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NFLOW" MODIFY ("ISPROTECTED" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NFLOW" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NFLOW" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NFLOW" MODIFY ("CODE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NFLOW" ADD CONSTRAINT "UNQ_FLOW_CODE" UNIQUE ("CODE") ENABLE;
 
--------------------------------------------------------
--  Constraints for Table NNODENOTIFICATION
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NNODENOTIFICATION" ADD CONSTRAINT "PK_NNODENOTIFICATION" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NNODENOTIFICATION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNODENOTIFICATION" MODIFY ("TRANSACTIONID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNODENOTIFICATION" MODIFY ("NOTIFYDATA" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NNOTIFICATION
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("FLOWID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("ACCOUNTID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("ONSOLICIT" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("ONQUERY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("ONSUBMIT" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("ONNOTIFY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("ONSCHEDULE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("ONDOWNLOAD" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" MODIFY ("ONEXECUTE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" ADD CONSTRAINT "UNQ_NOTIF_FLOWIDACCTID" UNIQUE ("ACCOUNTID", "FLOWID") ENABLE;
 
--------------------------------------------------------
--  Constraints for Table NOBJECTCACHE
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NOBJECTCACHE" ADD CONSTRAINT "PK_NOBJECTCACHE" PRIMARY KEY ("NAME") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NOBJECTCACHE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NOBJECTCACHE" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NOBJECTCACHE" MODIFY ("EXPIRATION" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NOBJECTCACHE" MODIFY ("DATA" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NPARTNER
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NPARTNER" ADD CONSTRAINT "PK_PARTNER" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NPARTNER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NPARTNER" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NPARTNER" MODIFY ("URL" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NPARTNER" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NPARTNER" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NPARTNER" MODIFY ("VERSION" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NPARTNER" ADD CONSTRAINT "UNQ_PARTNER_NAME" UNIQUE ("NAME") ENABLE;
 
--------------------------------------------------------
--  Constraints for Table NREQUEST
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NREQUEST" ADD CONSTRAINT "PK_REQUEST" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NREQUEST" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NREQUEST" MODIFY ("SERVICEID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NREQUEST" MODIFY ("ROWINDEX" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NREQUEST" MODIFY ("MAXROWCOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NREQUEST" MODIFY ("REQUESTTYPE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NREQUEST" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NREQUEST" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NREQUEST" MODIFY ("PARAMSBYNAME" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NREQUESTARG
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NREQUESTARG" ADD CONSTRAINT "PK_REQUESTARG" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NREQUESTARG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NREQUESTARG" MODIFY ("REQUESTID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NREQUESTARG" MODIFY ("ARGNAME" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NSCHEDULE
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" ADD CONSTRAINT "PK_SCHEDULE" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("STARTON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("ENDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("SOURCETYPE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("SOURCEID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("NEXTRUN" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("FREQUENCYTYPE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("FREQUENCY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("ISACTIVE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("ISRUNNOW" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" MODIFY ("EXECUTESTATUS" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" ADD CONSTRAINT "UNQ_SCHEDULE_NAME" UNIQUE ("NAME") ENABLE;
 
--------------------------------------------------------
--  Constraints for Table NSCHEDULESOURCEARG
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NSCHEDULESOURCEARG" ADD CONSTRAINT "PK_NSCHEDULESOURCEARG" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULESOURCEARG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULESOURCEARG" MODIFY ("SCHEDULEID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULESOURCEARG" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULESOURCEARG" ADD CONSTRAINT "UNQ_SCHEDSRCARG_SCHEDIDNAME" UNIQUE ("NAME", "SCHEDULEID") ENABLE;
 
--------------------------------------------------------
--  Constraints for Table NSERVICE
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NSERVICE" ADD CONSTRAINT "PK_SERVICE" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICE" MODIFY ("FLOWID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICE" MODIFY ("ISACTIVE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICE" MODIFY ("SERVICETYPE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICE" MODIFY ("IMPLEMENTOR" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICE" MODIFY ("AUTHLEVEL" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICE" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICE" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICE" ADD CONSTRAINT "UNQ_SERVICE_NAMEFLOWID" UNIQUE ("FLOWID", "NAME") ENABLE;
 
--------------------------------------------------------
--  Constraints for Table NSERVICEARG
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NSERVICEARG" ADD CONSTRAINT "PK_SERVICEARG" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICEARG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICEARG" MODIFY ("SERVICEID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICEARG" MODIFY ("ARGCODE" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NSERVICECONN
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NSERVICECONN" ADD CONSTRAINT "PK_NSERVICECONN" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICECONN" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICECONN" MODIFY ("SERVICEID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICECONN" MODIFY ("CONNECTIONID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICECONN" MODIFY ("KEYNAME" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICECONN" ADD CONSTRAINT "UNQ_SVC_SERVICEIDKEYNAME" UNIQUE ("KEYNAME", "SERVICEID") ENABLE;
 
--------------------------------------------------------
--  Constraints for Table NTRANSACTION
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NTRANSACTION" ADD CONSTRAINT "PK_TRANSACTION" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTION" MODIFY ("FLOWID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTION" MODIFY ("NETWORKID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTION" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTION" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTION" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTION" MODIFY ("WEBMETHOD" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NTRANSACTIONNOTIFICATION
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONNOTIFICATION" ADD CONSTRAINT "PK_NTRANSNOTIF" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONNOTIFICATION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONNOTIFICATION" MODIFY ("TRANSACTIONID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONNOTIFICATION" MODIFY ("URI" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONNOTIFICATION" MODIFY ("TYPE" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NTRANSACTIONRECIPIENT
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONRECIPIENT" ADD CONSTRAINT "PK_NTRANSRECIPT" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONRECIPIENT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONRECIPIENT" MODIFY ("TRANSACTIONID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONRECIPIENT" MODIFY ("URI" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NPLUGIN
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NPLUGIN" ADD CONSTRAINT "NPLUGIN_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NPLUGIN" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NPLUGIN" MODIFY ("FLOWID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NPLUGIN" MODIFY ("BINARYVERSION" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NPLUGIN" MODIFY ("MODIFIEDBY" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NPLUGIN" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NPLUGIN" MODIFY ("ZIPPEDBINARY" NOT NULL ENABLE);
 
--------------------------------------------------------
--  Constraints for Table NTRANSACTIONREALTIMEDETAILS
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONREALTIMEDETAILS" ADD CONSTRAINT "NTRANSACTIONREALTIMEDETAI_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONREALTIMEDETAILS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONREALTIMEDETAILS" MODIFY ("STATUSTYPE" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONREALTIMEDETAILS" MODIFY ("TRANSACTIONID" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONREALTIMEDETAILS" MODIFY ("MODIFIEDON" NOT NULL ENABLE);
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONREALTIMEDETAILS" MODIFY ("ORDERINDEX" NOT NULL ENABLE);
 
--------------------------------------------------------
--  DDL for Index PK_ACCOUNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_ACCOUNT" ON "OPENNODE2_NET"."NACCOUNT" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_NACCOUNTPOLICY
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_NACCOUNTPOLICY" ON "OPENNODE2_NET"."NACCOUNTPOLICY" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_ACTIVITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_ACTIVITY" ON "OPENNODE2_NET"."NACTIVITY" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_ACTIVITYDETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_ACTIVITYDETAIL" ON "OPENNODE2_NET"."NACTIVITYDETAIL" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_CONFIG
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_CONFIG" ON "OPENNODE2_NET"."NCONFIG" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_CONNECTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_CONNECTION" ON "OPENNODE2_NET"."NCONNECTION" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_DOCUMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_DOCUMENT" ON "OPENNODE2_NET"."NDOCUMENT" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_NDOCUMENTCONTENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_NDOCUMENTCONTENT" ON "OPENNODE2_NET"."NDOCUMENTCONTENT" ("DOCUMENTID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_FLOW
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_FLOW" ON "OPENNODE2_NET"."NFLOW" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_NNODENOTIFICATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_NNODENOTIFICATION" ON "OPENNODE2_NET"."NNODENOTIFICATION" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_NOTIFICATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_NOTIFICATION" ON "OPENNODE2_NET"."NNOTIFICATION" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_NOBJECTCACHE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_NOBJECTCACHE" ON "OPENNODE2_NET"."NOBJECTCACHE" ("NAME") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_PARTNER
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_PARTNER" ON "OPENNODE2_NET"."NPARTNER" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_REQUEST
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_REQUEST" ON "OPENNODE2_NET"."NREQUEST" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_REQUESTARG
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_REQUESTARG" ON "OPENNODE2_NET"."NREQUESTARG" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_SCHEDULE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_SCHEDULE" ON "OPENNODE2_NET"."NSCHEDULE" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_NSCHEDULESOURCEARG
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_NSCHEDULESOURCEARG" ON "OPENNODE2_NET"."NSCHEDULESOURCEARG" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_SERVICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_SERVICE" ON "OPENNODE2_NET"."NSERVICE" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_SERVICEARG
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_SERVICEARG" ON "OPENNODE2_NET"."NSERVICEARG" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_NSERVICECONN
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_NSERVICECONN" ON "OPENNODE2_NET"."NSERVICECONN" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_TRANSACTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_TRANSACTION" ON "OPENNODE2_NET"."NTRANSACTION" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_NTRANSNOTIF
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_NTRANSNOTIF" ON "OPENNODE2_NET"."NTRANSACTIONNOTIFICATION" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index PK_NTRANSRECIPT
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."PK_NTRANSRECIPT" ON "OPENNODE2_NET"."NTRANSACTIONRECIPIENT" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index UNQ_ACCOUNT_NAASACCOUNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."UNQ_ACCOUNT_NAASACCOUNT" ON "OPENNODE2_NET"."NACCOUNT" ("NAASACCOUNT") 
  ;
 
--------------------------------------------------------
--  DDL for Index UNQ_CONNECTION_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."UNQ_CONNECTION_CODE" ON "OPENNODE2_NET"."NCONNECTION" ("CODE") 
  ;
 
--------------------------------------------------------
--  DDL for Index UNQ_DOC_TRANSIDDOCNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."UNQ_DOC_TRANSIDDOCNAME" ON "OPENNODE2_NET"."NDOCUMENT" ("DOCUMENTNAME", "TRANSACTIONID") 
  ;
 
--------------------------------------------------------
--  DDL for Index UNQ_FLOW_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."UNQ_FLOW_CODE" ON "OPENNODE2_NET"."NFLOW" ("CODE") 
  ;
 
--------------------------------------------------------
--  DDL for Index UNQ_NOTIF_FLOWIDACCTID
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."UNQ_NOTIF_FLOWIDACCTID" ON "OPENNODE2_NET"."NNOTIFICATION" ("ACCOUNTID", "FLOWID") 
  ;
 
--------------------------------------------------------
--  DDL for Index UNQ_PARTNER_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."UNQ_PARTNER_NAME" ON "OPENNODE2_NET"."NPARTNER" ("NAME") 
  ;
 
--------------------------------------------------------
--  DDL for Index UNQ_SCHEDULE_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."UNQ_SCHEDULE_NAME" ON "OPENNODE2_NET"."NSCHEDULE" ("NAME") 
  ;
 
--------------------------------------------------------
--  DDL for Index UNQ_SCHEDSRCARG_SCHEDIDNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."UNQ_SCHEDSRCARG_SCHEDIDNAME" ON "OPENNODE2_NET"."NSCHEDULESOURCEARG" ("NAME", "SCHEDULEID") 
  ;
 
--------------------------------------------------------
--  DDL for Index UNQ_SERVICE_NAMEFLOWID
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."UNQ_SERVICE_NAMEFLOWID" ON "OPENNODE2_NET"."NSERVICE" ("FLOWID", "NAME") 
  ;
 
--------------------------------------------------------
--  DDL for Index UNQ_SVC_SERVICEIDKEYNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."UNQ_SVC_SERVICEIDKEYNAME" ON "OPENNODE2_NET"."NSERVICECONN" ("KEYNAME", "SERVICEID") 
  ;
 
--------------------------------------------------------
--  DDL for Index NPLUGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."NPLUGIN_PK" ON "OPENNODE2_NET"."NPLUGIN" ("ID") 
  ;
 
--------------------------------------------------------
--  DDL for Index NTRANSACTIONREALTIMEDETAI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPENNODE2_NET"."NTRANSACTIONREALTIMEDETAI_PK" ON "OPENNODE2_NET"."NTRANSACTIONREALTIMEDETAILS" ("ID") 
  ;
 
--------------------------------------------------------
--  Ref Constraints for Table NACCOUNTPOLICY
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NACCOUNTPOLICY" ADD CONSTRAINT "FK_ACCOUNTIDPOLICY_ACCOUNT" FOREIGN KEY ("ACCOUNTID")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NACCOUNTPOLICY" ADD CONSTRAINT "FK_ACCOUNTPOLICY_ACCOUNT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NACTIVITY
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NACTIVITY" ADD CONSTRAINT "FK_ACTIVITY_ACCOUNT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NACTIVITY" ADD CONSTRAINT "FK_ACTIVITY_TRANSACTION" FOREIGN KEY ("TRANSACTIONID")
	  REFERENCES "OPENNODE2_NET"."NTRANSACTION" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NACTIVITYDETAIL
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NACTIVITYDETAIL" ADD CONSTRAINT "FK_ACTIVITYDETAIL_ACTIVITY" FOREIGN KEY ("ACTIVITYID")
	  REFERENCES "OPENNODE2_NET"."NACTIVITY" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NACCOUNT
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NACCOUNT" ADD CONSTRAINT "FK_ACCOUNT_ACCOUNT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NCONFIG
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NCONFIG" ADD CONSTRAINT "FK_CONFIG_ACCOUNT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NCONNECTION
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NCONNECTION" ADD CONSTRAINT "FK_CONNECTION_ACCOUNT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NDOCUMENT
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NDOCUMENT" ADD CONSTRAINT "FK_DOCUMENT_TRANSACTION" FOREIGN KEY ("TRANSACTIONID")
	  REFERENCES "OPENNODE2_NET"."NTRANSACTION" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NDOCUMENTCONTENT
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NDOCUMENTCONTENT" ADD CONSTRAINT "FK_DOCCONTENT_DOC" FOREIGN KEY ("DOCUMENTID")
	  REFERENCES "OPENNODE2_NET"."NDOCUMENT" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NFLOW
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NFLOW" ADD CONSTRAINT "FK_FLOW_ACCOUNT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NNODENOTIFICATION
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NNODENOTIFICATION" ADD CONSTRAINT "FK_NODENOTIF_TRANS" FOREIGN KEY ("TRANSACTIONID")
	  REFERENCES "OPENNODE2_NET"."NTRANSACTION" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NNOTIFICATION
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" ADD CONSTRAINT "FK_MODBY_NOTIF_ACCT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" ADD CONSTRAINT "FK_NOTIF_ACCOUNT" FOREIGN KEY ("ACCOUNTID")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NNOTIFICATION" ADD CONSTRAINT "FK_NOTIF_FLOW" FOREIGN KEY ("FLOWID")
	  REFERENCES "OPENNODE2_NET"."NFLOW" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NPARTNER
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NPARTNER" ADD CONSTRAINT "FK_PARTNER_ACCOUNT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NREQUEST
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NREQUEST" ADD CONSTRAINT "FK_MODBY_REQUEST_ACCT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NREQUEST" ADD CONSTRAINT "FK_REQUEST_SERVICE" FOREIGN KEY ("SERVICEID")
	  REFERENCES "OPENNODE2_NET"."NSERVICE" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NREQUEST" ADD CONSTRAINT "FK_REQUEST_TRANSACTION" FOREIGN KEY ("TRANSACTIONID")
	  REFERENCES "OPENNODE2_NET"."NTRANSACTION" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NREQUESTARG
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NREQUESTARG" ADD CONSTRAINT "FK_REQUESTARG_REQUEST" FOREIGN KEY ("REQUESTID")
	  REFERENCES "OPENNODE2_NET"."NREQUEST" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NSCHEDULE
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_ACCOUNT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_ACTIVITY" FOREIGN KEY ("LASTEXECUTEACTIVITYID")
	  REFERENCES "OPENNODE2_NET"."NACTIVITY" ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NSCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_FLOW" FOREIGN KEY ("FLOWID")
	  REFERENCES "OPENNODE2_NET"."NFLOW" ("ID") ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NSCHEDULESOURCEARG
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NSCHEDULESOURCEARG" ADD CONSTRAINT "FK_SCHEDULESOURCEARG_SCHEDULE" FOREIGN KEY ("SCHEDULEID")
	  REFERENCES "OPENNODE2_NET"."NSCHEDULE" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NSERVICE
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NSERVICE" ADD CONSTRAINT "FK_SERVICE_ACCOUNT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICE" ADD CONSTRAINT "FK_SERVICE_FLOW" FOREIGN KEY ("FLOWID")
	  REFERENCES "OPENNODE2_NET"."NFLOW" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NSERVICEARG
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NSERVICEARG" ADD CONSTRAINT "FK_SERVICEARG_SERVICE" FOREIGN KEY ("SERVICEID")
	  REFERENCES "OPENNODE2_NET"."NSERVICE" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NSERVICECONN
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NSERVICECONN" ADD CONSTRAINT "FK_SERVICECONN_CONNECTION" FOREIGN KEY ("CONNECTIONID")
	  REFERENCES "OPENNODE2_NET"."NCONNECTION" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NSERVICECONN" ADD CONSTRAINT "FK_SERVICECONN_SERVICE" FOREIGN KEY ("SERVICEID")
	  REFERENCES "OPENNODE2_NET"."NSERVICE" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NTRANSACTION
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NTRANSACTION" ADD CONSTRAINT "FK_MODIFIEDBY_TRANS_ACCT" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NTRANSACTION" ADD CONSTRAINT "FK_TRANSACTION_FLOW" FOREIGN KEY ("FLOWID")
	  REFERENCES "OPENNODE2_NET"."NFLOW" ("ID") ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NTRANSACTIONNOTIFICATION
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONNOTIFICATION" ADD CONSTRAINT "FK_TRANSNOTIF_TRANS" FOREIGN KEY ("TRANSACTIONID")
	  REFERENCES "OPENNODE2_NET"."NTRANSACTION" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NTRANSACTIONRECIPIENT
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONRECIPIENT" ADD CONSTRAINT "FK_TRANSRECIPIENT_TRANS" FOREIGN KEY ("TRANSACTIONID")
	  REFERENCES "OPENNODE2_NET"."NTRANSACTION" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NPLUGIN
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NPLUGIN" ADD CONSTRAINT "NPLUGIN_NACCOUNT_FK" FOREIGN KEY ("MODIFIEDBY")
	  REFERENCES "OPENNODE2_NET"."NACCOUNT" ("ID") ENABLE;
 
  ALTER TABLE "OPENNODE2_NET"."NPLUGIN" ADD CONSTRAINT "NPLUGIN_NFLOW_FK" FOREIGN KEY ("FLOWID")
	  REFERENCES "OPENNODE2_NET"."NFLOW" ("ID") ON DELETE CASCADE ENABLE;
 
--------------------------------------------------------
--  Ref Constraints for Table NTRANSACTIONREALTIMEDETAILS
--------------------------------------------------------

  ALTER TABLE "OPENNODE2_NET"."NTRANSACTIONREALTIMEDETAILS" ADD CONSTRAINT "NTRANSACTIONREALTIMEDETAI_FK1" FOREIGN KEY ("TRANSACTIONID")
	  REFERENCES "OPENNODE2_NET"."NTRANSACTION" ("ID") ENABLE;
 