#region License
/*
Copyright (c) 2009, The Environmental Council of the States (ECOS)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/
#endregion

﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


namespace Windsor.Node2008.NAASUserMgr
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "UserMgrBinding3", Namespace = "http://www.exchangenetwork.net/wsdl/usermgr/3")]
    public partial class UserMgr3 : System.Web.Services.Protocols.SoapHttpClientProtocol, Windsor.Node2008.NAASClient.IUserMgr
    {

        private System.Threading.SendOrPostCallback AddUserOperationCompleted;

        private System.Threading.SendOrPostCallback DeleteUserOperationCompleted;

        private System.Threading.SendOrPostCallback UpdateUserOperationCompleted;

        private System.Threading.SendOrPostCallback SetUserPropertiesOperationCompleted;

        private System.Threading.SendOrPostCallback SetUserPropertyOperationCompleted;

        private System.Threading.SendOrPostCallback DeleteUserPropertyOperationCompleted;

        private System.Threading.SendOrPostCallback GetUserPropertyOperationCompleted;

        private System.Threading.SendOrPostCallback GetUserListOperationCompleted;

        private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;

        private System.Threading.SendOrPostCallback CopyUserAccountOperationCompleted;

        /// <remarks/>
        public UserMgr3() : this("https://naas.epacdxnode.net/xml/usermgr_v30.wsdl")
        {
        }
        public UserMgr3(string endpointUrl)
        {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = endpointUrl;
        }

        /// <remarks/>
        public event AddUserCompletedEventHandler AddUserCompleted;

        /// <remarks/>
        public event DeleteUserCompletedEventHandler DeleteUserCompleted;

        /// <remarks/>
        public event UpdateUserCompletedEventHandler UpdateUserCompleted;

        /// <remarks/>
        public event SetUserPropertiesCompletedEventHandler SetUserPropertiesCompleted;

        /// <remarks/>
        public event SetUserPropertyCompletedEventHandler SetUserPropertyCompleted;

        /// <remarks/>
        public event DeleteUserPropertyCompletedEventHandler DeleteUserPropertyCompleted;

        /// <remarks/>
        public event GetUserPropertyCompletedEventHandler GetUserPropertyCompleted;

        /// <remarks/>
        public event GetUserListCompletedEventHandler GetUserListCompleted;

        /// <remarks/>
        public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;

        /// <remarks/>
        public event CopyUserAccountCompletedEventHandler CopyUserAccountCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddUserResponse", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
        public AddUserResponse AddUser([System.Xml.Serialization.XmlElementAttribute("AddUser", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")] AddUser AddUser1)
        {
            object[] results = this.Invoke("AddUser", new object[] {
                    AddUser1});
            return ((AddUserResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginAddUser(AddUser AddUser1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("AddUser", new object[] {
                    AddUser1}, callback, asyncState);
        }

        /// <remarks/>
        public AddUserResponse EndAddUser(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((AddUserResponse)(results[0]));
        }

        /// <remarks/>
        public void AddUserAsync(AddUser AddUser1)
        {
            this.AddUserAsync(AddUser1, null);
        }

        /// <remarks/>
        public void AddUserAsync(AddUser AddUser1, object userState)
        {
            if ((this.AddUserOperationCompleted == null))
            {
                this.AddUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserOperationCompleted);
            }
            this.InvokeAsync("AddUser", new object[] {
                    AddUser1}, this.AddUserOperationCompleted, userState);
        }

        private void OnAddUserOperationCompleted(object arg)
        {
            if ((this.AddUserCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUserCompleted(this, new AddUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteUserResponse", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
        public DeleteUserResponse DeleteUser([System.Xml.Serialization.XmlElementAttribute("DeleteUser", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")] DeleteUser DeleteUser1)
        {
            object[] results = this.Invoke("DeleteUser", new object[] {
                    DeleteUser1});
            return ((DeleteUserResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDeleteUser(DeleteUser DeleteUser1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DeleteUser", new object[] {
                    DeleteUser1}, callback, asyncState);
        }

        /// <remarks/>
        public DeleteUserResponse EndDeleteUser(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((DeleteUserResponse)(results[0]));
        }

        /// <remarks/>
        public void DeleteUserAsync(DeleteUser DeleteUser1)
        {
            this.DeleteUserAsync(DeleteUser1, null);
        }

        /// <remarks/>
        public void DeleteUserAsync(DeleteUser DeleteUser1, object userState)
        {
            if ((this.DeleteUserOperationCompleted == null))
            {
                this.DeleteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserOperationCompleted);
            }
            this.InvokeAsync("DeleteUser", new object[] {
                    DeleteUser1}, this.DeleteUserOperationCompleted, userState);
        }

        private void OnDeleteUserOperationCompleted(object arg)
        {
            if ((this.DeleteUserCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserCompleted(this, new DeleteUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateUserResponse", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
        public UpdateUserResponse UpdateUser([System.Xml.Serialization.XmlElementAttribute("UpdateUser", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")] UpdateUser UpdateUser1)
        {
            object[] results = this.Invoke("UpdateUser", new object[] {
                    UpdateUser1});
            return ((UpdateUserResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUpdateUser(UpdateUser UpdateUser1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateUser", new object[] {
                    UpdateUser1}, callback, asyncState);
        }

        /// <remarks/>
        public UpdateUserResponse EndUpdateUser(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((UpdateUserResponse)(results[0]));
        }

        /// <remarks/>
        public void UpdateUserAsync(UpdateUser UpdateUser1)
        {
            this.UpdateUserAsync(UpdateUser1, null);
        }

        /// <remarks/>
        public void UpdateUserAsync(UpdateUser UpdateUser1, object userState)
        {
            if ((this.UpdateUserOperationCompleted == null))
            {
                this.UpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserOperationCompleted);
            }
            this.InvokeAsync("UpdateUser", new object[] {
                    UpdateUser1}, this.UpdateUserOperationCompleted, userState);
        }

        private void OnUpdateUserOperationCompleted(object arg)
        {
            if ((this.UpdateUserCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserCompleted(this, new UpdateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SetUserPropertiesResponse", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
        public SetUserPropertiesResponse SetUserProperties([System.Xml.Serialization.XmlElementAttribute("SetUserProperties", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")] SetUserProperties SetUserProperties1)
        {
            object[] results = this.Invoke("SetUserProperties", new object[] {
                    SetUserProperties1});
            return ((SetUserPropertiesResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSetUserProperties(SetUserProperties SetUserProperties1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SetUserProperties", new object[] {
                    SetUserProperties1}, callback, asyncState);
        }

        /// <remarks/>
        public SetUserPropertiesResponse EndSetUserProperties(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((SetUserPropertiesResponse)(results[0]));
        }

        /// <remarks/>
        public void SetUserPropertiesAsync(SetUserProperties SetUserProperties1)
        {
            this.SetUserPropertiesAsync(SetUserProperties1, null);
        }

        /// <remarks/>
        public void SetUserPropertiesAsync(SetUserProperties SetUserProperties1, object userState)
        {
            if ((this.SetUserPropertiesOperationCompleted == null))
            {
                this.SetUserPropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserPropertiesOperationCompleted);
            }
            this.InvokeAsync("SetUserProperties", new object[] {
                    SetUserProperties1}, this.SetUserPropertiesOperationCompleted, userState);
        }

        private void OnSetUserPropertiesOperationCompleted(object arg)
        {
            if ((this.SetUserPropertiesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserPropertiesCompleted(this, new SetUserPropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SetUserPropertyResponse", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
        public SetUserPropertyResponse SetUserProperty([System.Xml.Serialization.XmlElementAttribute("SetUserProperty", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")] SetUserProperty SetUserProperty1)
        {
            object[] results = this.Invoke("SetUserProperty", new object[] {
                    SetUserProperty1});
            return ((SetUserPropertyResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSetUserProperty(SetUserProperty SetUserProperty1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SetUserProperty", new object[] {
                    SetUserProperty1}, callback, asyncState);
        }

        /// <remarks/>
        public SetUserPropertyResponse EndSetUserProperty(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((SetUserPropertyResponse)(results[0]));
        }

        /// <remarks/>
        public void SetUserPropertyAsync(SetUserProperty SetUserProperty1)
        {
            this.SetUserPropertyAsync(SetUserProperty1, null);
        }

        /// <remarks/>
        public void SetUserPropertyAsync(SetUserProperty SetUserProperty1, object userState)
        {
            if ((this.SetUserPropertyOperationCompleted == null))
            {
                this.SetUserPropertyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserPropertyOperationCompleted);
            }
            this.InvokeAsync("SetUserProperty", new object[] {
                    SetUserProperty1}, this.SetUserPropertyOperationCompleted, userState);
        }

        private void OnSetUserPropertyOperationCompleted(object arg)
        {
            if ((this.SetUserPropertyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserPropertyCompleted(this, new SetUserPropertyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteUserPropertyResponse", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
        public DeleteUserPropertyResponse DeleteUserProperty([System.Xml.Serialization.XmlElementAttribute("DeleteUserProperty", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")] DeleteUserProperty DeleteUserProperty1)
        {
            object[] results = this.Invoke("DeleteUserProperty", new object[] {
                    DeleteUserProperty1});
            return ((DeleteUserPropertyResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDeleteUserProperty(DeleteUserProperty DeleteUserProperty1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DeleteUserProperty", new object[] {
                    DeleteUserProperty1}, callback, asyncState);
        }

        /// <remarks/>
        public DeleteUserPropertyResponse EndDeleteUserProperty(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((DeleteUserPropertyResponse)(results[0]));
        }

        /// <remarks/>
        public void DeleteUserPropertyAsync(DeleteUserProperty DeleteUserProperty1)
        {
            this.DeleteUserPropertyAsync(DeleteUserProperty1, null);
        }

        /// <remarks/>
        public void DeleteUserPropertyAsync(DeleteUserProperty DeleteUserProperty1, object userState)
        {
            if ((this.DeleteUserPropertyOperationCompleted == null))
            {
                this.DeleteUserPropertyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserPropertyOperationCompleted);
            }
            this.InvokeAsync("DeleteUserProperty", new object[] {
                    DeleteUserProperty1}, this.DeleteUserPropertyOperationCompleted, userState);
        }

        private void OnDeleteUserPropertyOperationCompleted(object arg)
        {
            if ((this.DeleteUserPropertyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserPropertyCompleted(this, new DeleteUserPropertyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUserPropertyResponse", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
        public GetUserPropertyResponse GetUserProperty([System.Xml.Serialization.XmlElementAttribute("GetUserProperty", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")] GetUserProperty GetUserProperty1)
        {
            object[] results = this.Invoke("GetUserProperty", new object[] {
                    GetUserProperty1});
            return ((GetUserPropertyResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetUserProperty(GetUserProperty GetUserProperty1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetUserProperty", new object[] {
                    GetUserProperty1}, callback, asyncState);
        }

        /// <remarks/>
        public GetUserPropertyResponse EndGetUserProperty(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetUserPropertyResponse)(results[0]));
        }

        /// <remarks/>
        public void GetUserPropertyAsync(GetUserProperty GetUserProperty1)
        {
            this.GetUserPropertyAsync(GetUserProperty1, null);
        }

        /// <remarks/>
        public void GetUserPropertyAsync(GetUserProperty GetUserProperty1, object userState)
        {
            if ((this.GetUserPropertyOperationCompleted == null))
            {
                this.GetUserPropertyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserPropertyOperationCompleted);
            }
            this.InvokeAsync("GetUserProperty", new object[] {
                    GetUserProperty1}, this.GetUserPropertyOperationCompleted, userState);
        }

        private void OnGetUserPropertyOperationCompleted(object arg)
        {
            if ((this.GetUserPropertyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserPropertyCompleted(this, new GetUserPropertyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUserListResponse", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
        public GetUserListResponse GetUserList([System.Xml.Serialization.XmlElementAttribute("GetUserList", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")] GetUserList GetUserList1)
        {
            object[] results = this.Invoke("GetUserList", new object[] {
                    GetUserList1});
            return ((GetUserListResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetUserList(GetUserList GetUserList1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetUserList", new object[] {
                    GetUserList1}, callback, asyncState);
        }

        /// <remarks/>
        public GetUserListResponse EndGetUserList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetUserListResponse)(results[0]));
        }

        /// <remarks/>
        public void GetUserListAsync(GetUserList GetUserList1)
        {
            this.GetUserListAsync(GetUserList1, null);
        }

        /// <remarks/>
        public void GetUserListAsync(GetUserList GetUserList1, object userState)
        {
            if ((this.GetUserListOperationCompleted == null))
            {
                this.GetUserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserListOperationCompleted);
            }
            this.InvokeAsync("GetUserList", new object[] {
                    GetUserList1}, this.GetUserListOperationCompleted, userState);
        }

        private void OnGetUserListOperationCompleted(object arg)
        {
            if ((this.GetUserListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserListCompleted(this, new GetUserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ChangePasswordResponse", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
        public ChangePasswordResponse ChangePassword([System.Xml.Serialization.XmlElementAttribute("ChangePassword", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")] ChangePassword ChangePassword1)
        {
            object[] results = this.Invoke("ChangePassword", new object[] {
                    ChangePassword1});
            return ((ChangePasswordResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginChangePassword(ChangePassword ChangePassword1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ChangePassword", new object[] {
                    ChangePassword1}, callback, asyncState);
        }

        /// <remarks/>
        public ChangePasswordResponse EndChangePassword(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChangePasswordResponse)(results[0]));
        }

        /// <remarks/>
        public void ChangePasswordAsync(ChangePassword ChangePassword1)
        {
            this.ChangePasswordAsync(ChangePassword1, null);
        }

        /// <remarks/>
        public void ChangePasswordAsync(ChangePassword ChangePassword1, object userState)
        {
            if ((this.ChangePasswordOperationCompleted == null))
            {
                this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("ChangePassword", new object[] {
                    ChangePassword1}, this.ChangePasswordOperationCompleted, userState);
        }

        private void OnChangePasswordOperationCompleted(object arg)
        {
            if ((this.ChangePasswordCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CopyUserAccountResponse", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
        public CopyUserAccountResponse CopyUserAccount([System.Xml.Serialization.XmlElementAttribute("CopyUserAccount", Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")] CopyUserAccount CopyUserAccount1)
        {
            object[] results = this.Invoke("CopyUserAccount", new object[] {
                    CopyUserAccount1});
            return ((CopyUserAccountResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCopyUserAccount(CopyUserAccount CopyUserAccount1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CopyUserAccount", new object[] {
                    CopyUserAccount1}, callback, asyncState);
        }

        /// <remarks/>
        public CopyUserAccountResponse EndCopyUserAccount(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CopyUserAccountResponse)(results[0]));
        }

        /// <remarks/>
        public void CopyUserAccountAsync(CopyUserAccount CopyUserAccount1)
        {
            this.CopyUserAccountAsync(CopyUserAccount1, null);
        }

        /// <remarks/>
        public void CopyUserAccountAsync(CopyUserAccount CopyUserAccount1, object userState)
        {
            if ((this.CopyUserAccountOperationCompleted == null))
            {
                this.CopyUserAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCopyUserAccountOperationCompleted);
            }
            this.InvokeAsync("CopyUserAccount", new object[] {
                    CopyUserAccount1}, this.CopyUserAccountOperationCompleted, userState);
        }

        private void OnCopyUserAccountOperationCompleted(object arg)
        {
            if ((this.CopyUserAccountCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CopyUserAccountCompleted(this, new CopyUserAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class AddUser
    {

        private string adminNameField;

        private string credentialField;

        private DomainTypeCode domainField;

        private string userIdField;

        private UserTypeCode userTypeField;

        private string userPasswordField;

        private string passwordConfirmationField;

        private string affiliateField;

        private AccountStatusCode statusField;

        /// <remarks/>
        public string adminName
        {
            get
            {
                return this.adminNameField;
            }
            set
            {
                this.adminNameField = value;
            }
        }

        /// <remarks/>
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }

        /// <remarks/>
        public DomainTypeCode domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public UserTypeCode userType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }

        /// <remarks/>
        public string userPassword
        {
            get
            {
                return this.userPasswordField;
            }
            set
            {
                this.userPasswordField = value;
            }
        }

        /// <remarks/>
        public string passwordConfirmation
        {
            get
            {
                return this.passwordConfirmationField;
            }
            set
            {
                this.passwordConfirmationField = value;
            }
        }

        /// <remarks/>
        public string affiliate
        {
            get
            {
                return this.affiliateField;
            }
            set
            {
                this.affiliateField = value;
            }
        }

        /// <remarks/>
        public AccountStatusCode status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public enum DomainTypeCode
    {

        /// <remarks/>
        @default,

        /// <remarks/>
        iamads,

        /// <remarks/>
        iamldap,

        /// <remarks/>
        devldap,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public enum UserTypeCode
    {

        /// <remarks/>
        user,

        /// <remarks/>
        @operator,

        /// <remarks/>
        approver,

        /// <remarks/>
        admin,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public enum AccountStatusCode
    {

        /// <remarks/>
        valid,

        /// <remarks/>
        pending,

        /// <remarks/>
        invalid,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class UserAccountType
    {

        private string userIdField;

        private string userGroupField;

        private string ownerField;

        private string nodeField;

        private string affiliateField;

        private string statusField;

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string userGroup
        {
            get
            {
                return this.userGroupField;
            }
            set
            {
                this.userGroupField = value;
            }
        }

        /// <remarks/>
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }

        /// <remarks/>
        public string node
        {
            get
            {
                return this.nodeField;
            }
            set
            {
                this.nodeField = value;
            }
        }

        /// <remarks/>
        public string affiliate
        {
            get
            {
                return this.affiliateField;
            }
            set
            {
                this.affiliateField = value;
            }
        }

        /// <remarks/>
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class UserPropertyPairType
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class AddUserResponse
    {

        private string returnField;

        /// <remarks/>
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class DeleteUser
    {

        private string adminNameField;

        private string credentialField;

        private DomainTypeCode domainField;

        private string userIdField;

        /// <remarks/>
        public string adminName
        {
            get
            {
                return this.adminNameField;
            }
            set
            {
                this.adminNameField = value;
            }
        }

        /// <remarks/>
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }

        /// <remarks/>
        public DomainTypeCode domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class DeleteUserResponse
    {

        private string returnField;

        /// <remarks/>
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class UpdateUser
    {

        private string adminNameField;

        private string credentialField;

        private DomainTypeCode domainField;

        private string userIdField;

        private UserTypeCode userTypeField;

        private string userPasswordField;

        private string ownerField;

        private string affiliateField;

        private AccountStatusCode statusField;

        /// <remarks/>
        public string adminName
        {
            get
            {
                return this.adminNameField;
            }
            set
            {
                this.adminNameField = value;
            }
        }

        /// <remarks/>
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }

        /// <remarks/>
        public DomainTypeCode domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public UserTypeCode userType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }

        /// <remarks/>
        public string userPassword
        {
            get
            {
                return this.userPasswordField;
            }
            set
            {
                this.userPasswordField = value;
            }
        }

        /// <remarks/>
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }

        /// <remarks/>
        public string affiliate
        {
            get
            {
                return this.affiliateField;
            }
            set
            {
                this.affiliateField = value;
            }
        }

        /// <remarks/>
        public AccountStatusCode status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class UpdateUserResponse
    {

        private string returnField;

        /// <remarks/>
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class SetUserProperties
    {

        private string adminNameField;

        private string credentialField;

        private DomainTypeCode domainField;

        private string userIdField;

        private string commonNameField;

        private string organizationField;

        private string organizationUnitField;

        private string addressField;

        private string cityField;

        private StateId stateField;

        private string zipCodeField;

        private string phoneField;

        private string emailField;

        private string secretQuestionField;

        private string secretAnswerField;

        private string supervisorField;

        private string supervisorPhoneField;

        private string userDataField;

        private string securityLevelField;

        /// <remarks/>
        public string adminName
        {
            get
            {
                return this.adminNameField;
            }
            set
            {
                this.adminNameField = value;
            }
        }

        /// <remarks/>
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }

        /// <remarks/>
        public DomainTypeCode domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string commonName
        {
            get
            {
                return this.commonNameField;
            }
            set
            {
                this.commonNameField = value;
            }
        }

        /// <remarks/>
        public string organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }

        /// <remarks/>
        public string organizationUnit
        {
            get
            {
                return this.organizationUnitField;
            }
            set
            {
                this.organizationUnitField = value;
            }
        }

        /// <remarks/>
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public StateId state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public string zipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }

        /// <remarks/>
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        public string secretQuestion
        {
            get
            {
                return this.secretQuestionField;
            }
            set
            {
                this.secretQuestionField = value;
            }
        }

        /// <remarks/>
        public string secretAnswer
        {
            get
            {
                return this.secretAnswerField;
            }
            set
            {
                this.secretAnswerField = value;
            }
        }

        /// <remarks/>
        public string supervisor
        {
            get
            {
                return this.supervisorField;
            }
            set
            {
                this.supervisorField = value;
            }
        }

        /// <remarks/>
        public string supervisorPhone
        {
            get
            {
                return this.supervisorPhoneField;
            }
            set
            {
                this.supervisorPhoneField = value;
            }
        }

        /// <remarks/>
        public string userData
        {
            get
            {
                return this.userDataField;
            }
            set
            {
                this.userDataField = value;
            }
        }

        /// <remarks/>
        public string securityLevel
        {
            get
            {
                return this.securityLevelField;
            }
            set
            {
                this.securityLevelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public enum StateId
    {

        /// <remarks/>
        ACE,

        /// <remarks/>
        AQS,

        /// <remarks/>
        AQS_DM,

        /// <remarks/>
        AL,

        /// <remarks/>
        AK,

        /// <remarks/>
        AK_TC,

        /// <remarks/>
        AZ,

        /// <remarks/>
        AZ_HT,

        /// <remarks/>
        AZ_NN,

        /// <remarks/>
        AZ_SRPMIC,

        /// <remarks/>
        AR,

        /// <remarks/>
        BPEL,

        /// <remarks/>
        CA,

        /// <remarks/>
        CA_DHS,

        /// <remarks/>
        CA_Water,

        /// <remarks/>
        CA_WB,

        /// <remarks/>
        CA_ST,

        /// <remarks/>
        CDX,

        /// <remarks/>
        CDX_RMP,

        /// <remarks/>
        CDXWeb,

        /// <remarks/>
        CDXWebTemp,

        /// <remarks/>
        CNMI,

        /// <remarks/>
        REF,

        /// <remarks/>
        CO,

        /// <remarks/>
        CSC,

        /// <remarks/>
        CT,

        /// <remarks/>
        DE,

        /// <remarks/>
        DE_DT,

        /// <remarks/>
        DC,

        /// <remarks/>
        ENFO,

        /// <remarks/>
        EPA_R9,

        /// <remarks/>
        EPA_R10,

        /// <remarks/>
        ERG1,

        /// <remarks/>
        ERG2,

        /// <remarks/>
        FL,

        /// <remarks/>
        GA,

        /// <remarks/>
        GLNPO,

        /// <remarks/>
        HI,

        /// <remarks/>
        HERE,

        /// <remarks/>
        ICIS,

        /// <remarks/>
        ID,

        /// <remarks/>
        ID_KT,

        /// <remarks/>
        ID_SB,

        /// <remarks/>
        ID_WR,

        /// <remarks/>
        IL,

        /// <remarks/>
        IN,

        /// <remarks/>
        IA,

        /// <remarks/>
        KS,

        /// <remarks/>
        KS_DA,

        /// <remarks/>
        KY,

        /// <remarks/>
        KY_DOGI,

        /// <remarks/>
        LA,

        /// <remarks/>
        LA_DEQ,

        /// <remarks/>
        ME,

        /// <remarks/>
        MD,

        /// <remarks/>
        MA,

        /// <remarks/>
        MI,

        /// <remarks/>
        MN,

        /// <remarks/>
        MN_NRRI,

        /// <remarks/>
        MS,

        /// <remarks/>
        MO,

        /// <remarks/>
        MT,

        /// <remarks/>
        NatureServe,

        /// <remarks/>
        NE,

        /// <remarks/>
        NE_OMAHA,

        /// <remarks/>
        NE_HHSS,

        /// <remarks/>
        NEI,

        /// <remarks/>
        NH,

        /// <remarks/>
        NV,

        /// <remarks/>
        NJ,

        /// <remarks/>
        NM,

        /// <remarks/>
        NY,

        /// <remarks/>
        NY_HEALTH,

        /// <remarks/>
        NY_MHK,

        /// <remarks/>
        NC,

        /// <remarks/>
        ND,

        /// <remarks/>
        OH,

        /// <remarks/>
        OK,

        /// <remarks/>
        OK_CN,

        /// <remarks/>
        OK_ODA,

        /// <remarks/>
        OR,

        /// <remarks/>
        OR_CTUIR,

        /// <remarks/>
        OregonRPC,

        /// <remarks/>
        PA,

        /// <remarks/>
        PR,

        /// <remarks/>
        RI,

        /// <remarks/>
        SAIC,

        /// <remarks/>
        SC,

        /// <remarks/>
        SD,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ID_SB")]
        ID_SB1,

        /// <remarks/>
        SD_MSIWRC,

        /// <remarks/>
        TN,

        /// <remarks/>
        TWX,

        /// <remarks/>
        TX,

        /// <remarks/>
        TrustService,

        /// <remarks/>
        UIC,

        /// <remarks/>
        UT,

        /// <remarks/>
        VT,

        /// <remarks/>
        VA,

        /// <remarks/>
        WA,

        /// <remarks/>
        WA_SIT,

        /// <remarks/>
        WV,

        /// <remarks/>
        WV_HRS,

        /// <remarks/>
        WI,

        /// <remarks/>
        WQX,

        /// <remarks/>
        WY,

        /// <remarks/>
        WA_SIN,

        /// <remarks/>
        WA_DNR,

        /// <remarks/>
        CA_YT,

        /// <remarks/>
        WY_WRIR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class SetUserPropertiesResponse
    {

        private string returnField;

        /// <remarks/>
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class SetUserProperty
    {

        private string adminNameField;

        private string credentialField;

        private DomainTypeCode domainField;

        private string userIdField;

        private UserPropertyPairType[] propertyField;

        /// <remarks/>
        public string adminName
        {
            get
            {
                return this.adminNameField;
            }
            set
            {
                this.adminNameField = value;
            }
        }

        /// <remarks/>
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }

        /// <remarks/>
        public DomainTypeCode domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public UserPropertyPairType[] property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class SetUserPropertyResponse
    {

        private string returnField;

        /// <remarks/>
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class DeleteUserProperty
    {

        private string adminNameField;

        private string credentialField;

        private DomainTypeCode domainField;

        private string userIdField;

        private string propertyNameField;

        /// <remarks/>
        public string adminName
        {
            get
            {
                return this.adminNameField;
            }
            set
            {
                this.adminNameField = value;
            }
        }

        /// <remarks/>
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }

        /// <remarks/>
        public DomainTypeCode domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string propertyName
        {
            get
            {
                return this.propertyNameField;
            }
            set
            {
                this.propertyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class DeleteUserPropertyResponse
    {

        private string returnField;

        /// <remarks/>
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class GetUserProperty
    {

        private string adminNameField;

        private string credentialField;

        private DomainTypeCode domainField;

        private string userIdField;

        private string propertyNameField;

        /// <remarks/>
        public string adminName
        {
            get
            {
                return this.adminNameField;
            }
            set
            {
                this.adminNameField = value;
            }
        }

        /// <remarks/>
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }

        /// <remarks/>
        public DomainTypeCode domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string propertyName
        {
            get
            {
                return this.propertyNameField;
            }
            set
            {
                this.propertyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class GetUserPropertyResponse
    {

        private UserPropertyPairType[] returnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
        public UserPropertyPairType[] @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class GetUserList
    {

        private string adminNameField;

        private string credentialField;

        private DomainTypeCode domainField;

        private string rowIdField;

        private string maxRowsField;

        private string userIdField;

        private string affiliateField;

        private string statusField;

        public GetUserList()
        {
            this.rowIdField = "0";
            this.maxRowsField = "200";
        }

        /// <remarks/>
        public string adminName
        {
            get
            {
                return this.adminNameField;
            }
            set
            {
                this.adminNameField = value;
            }
        }

        /// <remarks/>
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }

        /// <remarks/>
        public DomainTypeCode domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string rowId
        {
            get
            {
                return this.rowIdField;
            }
            set
            {
                this.rowIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string maxRows
        {
            get
            {
                return this.maxRowsField;
            }
            set
            {
                this.maxRowsField = value;
            }
        }

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string affiliate
        {
            get
            {
                return this.affiliateField;
            }
            set
            {
                this.affiliateField = value;
            }
        }

        /// <remarks/>
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class GetUserListResponse
    {

        private UserAccountType[] returnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("account", IsNullable = false)]
        public UserAccountType[] @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class ChangePassword
    {

        private string userIdField;

        private string credentialField;

        private DomainTypeCode domainField;

        private string newPasswordField;

        private string passwordConfirmationField;

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }

        /// <remarks/>
        public DomainTypeCode domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        /// <remarks/>
        public string newPassword
        {
            get
            {
                return this.newPasswordField;
            }
            set
            {
                this.newPasswordField = value;
            }
        }

        /// <remarks/>
        public string passwordConfirmation
        {
            get
            {
                return this.passwordConfirmationField;
            }
            set
            {
                this.passwordConfirmationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class ChangePasswordResponse
    {

        private string returnField;

        /// <remarks/>
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class CopyUserAccount
    {

        private string adminNameField;

        private string credentialField;

        private DomainTypeCode fromDomainField;

        private StateId fromNodeField;

        private string userIdField;

        private AccountStatusCode accountStatusField;

        private DomainTypeCode toDomainField;

        private AccountStatusCode newStatusField;

        private CopyAccountMethod methodField;

        /// <remarks/>
        public string adminName
        {
            get
            {
                return this.adminNameField;
            }
            set
            {
                this.adminNameField = value;
            }
        }

        /// <remarks/>
        public string credential
        {
            get
            {
                return this.credentialField;
            }
            set
            {
                this.credentialField = value;
            }
        }

        /// <remarks/>
        public DomainTypeCode fromDomain
        {
            get
            {
                return this.fromDomainField;
            }
            set
            {
                this.fromDomainField = value;
            }
        }

        /// <remarks/>
        public StateId fromNode
        {
            get
            {
                return this.fromNodeField;
            }
            set
            {
                this.fromNodeField = value;
            }
        }

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public AccountStatusCode accountStatus
        {
            get
            {
                return this.accountStatusField;
            }
            set
            {
                this.accountStatusField = value;
            }
        }

        /// <remarks/>
        public DomainTypeCode toDomain
        {
            get
            {
                return this.toDomainField;
            }
            set
            {
                this.toDomainField = value;
            }
        }

        /// <remarks/>
        public AccountStatusCode newStatus
        {
            get
            {
                return this.newStatusField;
            }
            set
            {
                this.newStatusField = value;
            }
        }

        /// <remarks/>
        public CopyAccountMethod method
        {
            get
            {
                return this.methodField;
            }
            set
            {
                this.methodField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public enum CopyAccountMethod
    {

        /// <remarks/>
        add,

        /// <remarks/>
        update,

        /// <remarks/>
        set,

        /// <remarks/>
        setprops,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.exchangenetwork.net/schema/usermgr/3")]
    public partial class CopyUserAccountResponse
    {

        private string returnField;

        /// <remarks/>
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void AddUserCompletedEventHandler(object sender, AddUserCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal AddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public AddUserResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((AddUserResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void DeleteUserCompletedEventHandler(object sender, DeleteUserCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DeleteUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public DeleteUserResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DeleteUserResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void UpdateUserCompletedEventHandler(object sender, UpdateUserCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UpdateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public UpdateUserResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((UpdateUserResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void SetUserPropertiesCompletedEventHandler(object sender, SetUserPropertiesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetUserPropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SetUserPropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SetUserPropertiesResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SetUserPropertiesResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void SetUserPropertyCompletedEventHandler(object sender, SetUserPropertyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetUserPropertyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SetUserPropertyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SetUserPropertyResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SetUserPropertyResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void DeleteUserPropertyCompletedEventHandler(object sender, DeleteUserPropertyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserPropertyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DeleteUserPropertyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public DeleteUserPropertyResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DeleteUserPropertyResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetUserPropertyCompletedEventHandler(object sender, GetUserPropertyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserPropertyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetUserPropertyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public GetUserPropertyResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((GetUserPropertyResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetUserListCompletedEventHandler(object sender, GetUserListCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetUserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public GetUserListResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((GetUserListResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ChangePasswordResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ChangePasswordResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CopyUserAccountCompletedEventHandler(object sender, CopyUserAccountCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CopyUserAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CopyUserAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CopyUserAccountResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CopyUserAccountResponse)(this.results[0]));
            }
        }
    }
}
