--------------------------------------------------------
--  File created - Tuesday-October-07-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMTS_BUY_PUB_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_BUY_PUB_SUPRT_DOC_DETAIL" 
   (	"BUY_PUB_SUPRT_DOC_DETAIL_ID" VARCHAR2(40 BYTE), 
	"BUY_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"SUPRT_DOC_TXT" VARCHAR2(100 BYTE), 
	"SUPRT_DOC_NUM_TXT" VARCHAR2(100 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_BUY_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_BUY_SUPRT_DOC_DETAIL" 
   (	"BUY_SUPRT_DOC_DETAIL_ID" VARCHAR2(40 BYTE), 
	"BUY_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"SUPRT_DOC_TXT" VARCHAR2(100 BYTE), 
	"SUPRT_DOC_NUM_TXT" VARCHAR2(100 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_BUY_TRANS_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_BUY_TRANS_DETAIL" 
   (	"BUY_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"EMTS_ID" VARCHAR2(40 BYTE), 
	"TRANS_PART_ORG_IDEN" VARCHAR2(12 BYTE), 
	"TRANS_PART_ORG_NAME" VARCHAR2(125 BYTE), 
	"RIN_QNTY" NUMBER(10,0), 
	"BATCH_VOL" NUMBER(10,0), 
	"FUEL_CODE" VARCHAR2(4 BYTE), 
	"ASSIGN_CODE" NUMBER(10,0), 
	"RIN_YEAR" NUMBER(10,0), 
	"QAP_SERVICE_TYPE_CODE" VARCHAR2(4 BYTE), 
	"BUY_RSN_CODE" VARCHAR2(4 BYTE), 
	"RIN_PRICE_AMT" NUMBER(5,2), 
	"GALLON_PRICE_AMT" NUMBER(5,2), 
	"TRANSFER_DATE" TIMESTAMP (6), 
	"PTD_NUM" VARCHAR2(100 BYTE), 
	"MATCHING_TRANS_IDEN" VARCHAR2(100 BYTE), 
	"TRANS_DETAIL_CMNT_TXT" VARCHAR2(400 BYTE), 
	"GENR_ORG_IDEN" VARCHAR2(12 BYTE), 
	"GENR_FAC_IDEN" VARCHAR2(12 BYTE), 
	"BATCH_NUM_TXT" VARCHAR2(20 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_CO_PROD_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_CO_PROD_DETAIL" 
   (	"CO_PROD_DETAIL_ID" VARCHAR2(40 BYTE), 
	"GENR_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"CO_PROD_CODE" VARCHAR2(4 BYTE), 
	"CO_PROD_DETAIL_CMNT_TXT" VARCHAR2(400 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_EMTS
--------------------------------------------------------

  CREATE TABLE "EMTS_EMTS" 
   (	"EMTS_ID" VARCHAR2(40 BYTE), 
	"USER_LOGIN_TXT" VARCHAR2(100 BYTE), 
	"SUBM_CRTN_DATE" TIMESTAMP (6), 
	"ORG_IDEN" VARCHAR2(12 BYTE), 
	"SUBM_CMNT_TXT" VARCHAR2(400 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_FDSTK_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_FDSTK_DETAIL" 
   (	"FDSTK_DETAIL_ID" VARCHAR2(40 BYTE), 
	"GENR_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"FDSTK_CODE" VARCHAR2(4 BYTE), 
	"RENEW_BIOMASS_IND" VARCHAR2(1 BYTE), 
	"FDSTK_QNTY" NUMBER(10,1), 
	"FDSTK_MEAS_CODE" VARCHAR2(3 BYTE), 
	"FDSTK_DETAIL_CMNT_TXT" VARCHAR2(400 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_GENR_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_GENR_SUPRT_DOC_DETAIL" 
   (	"GENR_SUPRT_DOC_DETAIL_ID" VARCHAR2(40 BYTE), 
	"GENR_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"SUPRT_DOC_TXT" VARCHAR2(100 BYTE), 
	"SUPRT_DOC_NUM_TXT" VARCHAR2(100 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_GENR_TRANS_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_GENR_TRANS_DETAIL" 
   (	"GENR_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"EMTS_ID" VARCHAR2(40 BYTE), 
	"RIN_QNTY" NUMBER(10,0), 
	"BATCH_VOL" NUMBER(10,0), 
	"FUEL_CODE" VARCHAR2(4 BYTE), 
	"FUEL_CATG_CODE" VARCHAR2(4 BYTE), 
	"PROD_DATE" TIMESTAMP (6), 
	"PROC_CODE" VARCHAR2(4 BYTE), 
	"QAP_SERVICE_TYPE_CODE" VARCHAR2(4 BYTE), 
	"DENATURANT_VOL" NUMBER(10,0), 
	"EQUIVALENCE_VAL" NUMBER(2,1), 
	"IMPORT_FAC_IDEN" VARCHAR2(12 BYTE), 
	"TRANS_DETAIL_CMNT_TXT" VARCHAR2(400 BYTE), 
	"GENR_ORG_IDEN" VARCHAR2(12 BYTE), 
	"GENR_FAC_IDEN" VARCHAR2(12 BYTE), 
	"BATCH_NUM_TXT" VARCHAR2(20 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_LOCK_TRANS_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_LOCK_TRANS_DETAIL" 
   (	"LOCK_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"EMTS_ID" VARCHAR2(40 BYTE), 
	"FUEL_CODE" VARCHAR2(4 BYTE), 
	"ASSIGN_CODE" NUMBER(10,0), 
	"RIN_YEAR" NUMBER(10,0), 
	"QAP_SERVICE_TYPE_CODE" VARCHAR2(4 BYTE), 
	"QAP_PROVIDER_ORG_IDEN" VARCHAR2(12 BYTE), 
	"TRANS_DETAIL_CMNT_TXT" VARCHAR2(400 BYTE), 
	"GENR_ORG_IDEN" VARCHAR2(12 BYTE), 
	"GENR_FAC_IDEN" VARCHAR2(12 BYTE), 
	"BATCH_NUM_TXT" VARCHAR2(20 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_RETIRE_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_RETIRE_SUPRT_DOC_DETAIL" 
   (	"RETIRE_SUPRT_DOC_DETAIL_ID" VARCHAR2(40 BYTE), 
	"RETIRE_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"SUPRT_DOC_TXT" VARCHAR2(100 BYTE), 
	"SUPRT_DOC_NUM_TXT" VARCHAR2(100 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_RETIRE_TRANS_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_RETIRE_TRANS_DETAIL" 
   (	"RETIRE_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"EMTS_ID" VARCHAR2(40 BYTE), 
	"RIN_QNTY" NUMBER(10,0), 
	"BATCH_VOL" NUMBER(10,0), 
	"FUEL_CODE" VARCHAR2(4 BYTE), 
	"ASSIGN_CODE" NUMBER(10,0), 
	"RIN_YEAR" NUMBER(10,0), 
	"QAP_SERVICE_TYPE_CODE" VARCHAR2(4 BYTE), 
	"RETIRE_RSN_CODE" VARCHAR2(4 BYTE), 
	"TRANS_DATE" TIMESTAMP (6), 
	"COMPL_YEAR" NUMBER(10,0), 
	"COMPL_LEVEL_CODE" VARCHAR2(3 BYTE), 
	"COMPL_FAC_IDEN" VARCHAR2(12 BYTE), 
	"TRANS_DETAIL_CMNT_TXT" VARCHAR2(400 BYTE), 
	"GENR_ORG_IDEN" VARCHAR2(12 BYTE), 
	"GENR_FAC_IDEN" VARCHAR2(12 BYTE), 
	"BATCH_NUM_TXT" VARCHAR2(20 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_SELL_PUB_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_SELL_PUB_SUPRT_DOC_DETAIL" 
   (	"SELL_PUB_SUPRT_DOC_DETAIL_ID" VARCHAR2(40 BYTE), 
	"SELL_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"SUPRT_DOC_TXT" VARCHAR2(100 BYTE), 
	"SUPRT_DOC_NUM_TXT" VARCHAR2(100 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_SELL_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_SELL_SUPRT_DOC_DETAIL" 
   (	"SELL_SUPRT_DOC_DETAIL_ID" VARCHAR2(40 BYTE), 
	"SELL_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"SUPRT_DOC_TXT" VARCHAR2(100 BYTE), 
	"SUPRT_DOC_NUM_TXT" VARCHAR2(100 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_SELL_TRANS_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_SELL_TRANS_DETAIL" 
   (	"SELL_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"EMTS_ID" VARCHAR2(40 BYTE), 
	"TRANS_PART_ORG_IDEN" VARCHAR2(12 BYTE), 
	"TRANS_PART_ORG_NAME" VARCHAR2(125 BYTE), 
	"RIN_QNTY" NUMBER(10,0), 
	"BATCH_VOL" NUMBER(10,0), 
	"FUEL_CODE" VARCHAR2(4 BYTE), 
	"ASSIGN_CODE" NUMBER(10,0), 
	"RIN_YEAR" NUMBER(10,0), 
	"QAP_SERVICE_TYPE_CODE" VARCHAR2(4 BYTE), 
	"SELL_RSN_CODE" VARCHAR2(4 BYTE), 
	"RIN_PRICE_AMT" NUMBER(5,2), 
	"GALLON_PRICE_AMT" NUMBER(5,2), 
	"TRANSFER_DATE" TIMESTAMP (6), 
	"PTD_NUM" VARCHAR2(100 BYTE), 
	"MATCHING_TRANS_IDEN" VARCHAR2(100 BYTE), 
	"TRANS_DETAIL_CMNT_TXT" VARCHAR2(400 BYTE), 
	"GENR_ORG_IDEN" VARCHAR2(12 BYTE), 
	"GENR_FAC_IDEN" VARCHAR2(12 BYTE), 
	"BATCH_NUM_TXT" VARCHAR2(20 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_SEPR_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_SEPR_SUPRT_DOC_DETAIL" 
   (	"SEPR_SUPRT_DOC_DETAIL_ID" VARCHAR2(40 BYTE), 
	"SEPR_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"SUPRT_DOC_TXT" VARCHAR2(100 BYTE), 
	"SUPRT_DOC_NUM_TXT" VARCHAR2(100 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_SEPR_TRANS_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_SEPR_TRANS_DETAIL" 
   (	"SEPR_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"EMTS_ID" VARCHAR2(40 BYTE), 
	"RIN_QNTY" NUMBER(10,0), 
	"BATCH_VOL" NUMBER(10,0), 
	"FUEL_CODE" VARCHAR2(4 BYTE), 
	"RIN_YEAR" NUMBER(10,0), 
	"QAP_SERVICE_TYPE_CODE" VARCHAR2(4 BYTE), 
	"SEPR_RSN_CODE" VARCHAR2(4 BYTE), 
	"TRANS_DATE" TIMESTAMP (6), 
	"BLENDER_ORG_IDEN" VARCHAR2(12 BYTE), 
	"BLENDER_ORG_NAME" VARCHAR2(125 BYTE), 
	"TRANS_DETAIL_CMNT_TXT" VARCHAR2(400 BYTE), 
	"GENR_ORG_IDEN" VARCHAR2(12 BYTE), 
	"GENR_FAC_IDEN" VARCHAR2(12 BYTE), 
	"BATCH_NUM_TXT" VARCHAR2(20 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Table EMTS_UNLOCK_TRANS_DETAIL
--------------------------------------------------------

  CREATE TABLE "EMTS_UNLOCK_TRANS_DETAIL" 
   (	"UNLOCK_TRANS_DETAIL_ID" VARCHAR2(40 BYTE), 
	"EMTS_ID" VARCHAR2(40 BYTE), 
	"FUEL_CODE" VARCHAR2(4 BYTE), 
	"ASSIGN_CODE" NUMBER(10,0), 
	"RIN_YEAR" NUMBER(10,0), 
	"QAP_SERVICE_TYPE_CODE" VARCHAR2(4 BYTE), 
	"QAP_PROVIDER_ORG_IDEN" VARCHAR2(12 BYTE), 
	"TRANS_DETAIL_CMNT_TXT" VARCHAR2(400 BYTE), 
	"GENR_ORG_IDEN" VARCHAR2(12 BYTE), 
	"GENR_FAC_IDEN" VARCHAR2(12 BYTE), 
	"BATCH_NUM_TXT" VARCHAR2(20 BYTE)
   ) ;
/
--------------------------------------------------------
--  DDL for Index PK_GENR_TRANS_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_GENR_TRANS_DETAIL" ON "EMTS_GENR_TRANS_DETAIL" ("GENR_TRANS_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_GENR_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_GENR_SUPRT_DOC_DETAIL" ON "EMTS_GENR_SUPRT_DOC_DETAIL" ("GENR_SUPRT_DOC_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_RETIRE_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RETIRE_SUPRT_DOC_DETAIL" ON "EMTS_RETIRE_SUPRT_DOC_DETAIL" ("RETIRE_SUPRT_DOC_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_SELL_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SELL_SUPRT_DOC_DETAIL" ON "EMTS_SELL_SUPRT_DOC_DETAIL" ("SELL_SUPRT_DOC_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_SELL_TRANS_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SELL_TRANS_DETAIL" ON "EMTS_SELL_TRANS_DETAIL" ("SELL_TRANS_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_BUY_PUB_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_BUY_PUB_SUPRT_DOC_DETAIL" ON "EMTS_BUY_PUB_SUPRT_DOC_DETAIL" ("BUY_PUB_SUPRT_DOC_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_FDSTK_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_FDSTK_DETAIL" ON "EMTS_FDSTK_DETAIL" ("FDSTK_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_RETIRE_TRANS_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RETIRE_TRANS_DETAIL" ON "EMTS_RETIRE_TRANS_DETAIL" ("RETIRE_TRANS_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_LOCK_TRANS_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_LOCK_TRANS_DETAIL" ON "EMTS_LOCK_TRANS_DETAIL" ("LOCK_TRANS_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_BUY_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_BUY_SUPRT_DOC_DETAIL" ON "EMTS_BUY_SUPRT_DOC_DETAIL" ("BUY_SUPRT_DOC_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_SEPR_TRANS_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SEPR_TRANS_DETAIL" ON "EMTS_SEPR_TRANS_DETAIL" ("SEPR_TRANS_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_SELL_PUB_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SELL_PUB_SUPRT_DOC_DETAIL" ON "EMTS_SELL_PUB_SUPRT_DOC_DETAIL" ("SELL_PUB_SUPRT_DOC_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_SEPR_SUPRT_DOC_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SEPR_SUPRT_DOC_DETAIL" ON "EMTS_SEPR_SUPRT_DOC_DETAIL" ("SEPR_SUPRT_DOC_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_EMTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_EMTS" ON "EMTS_EMTS" ("EMTS_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_BUY_TRANS_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_BUY_TRANS_DETAIL" ON "EMTS_BUY_TRANS_DETAIL" ("BUY_TRANS_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index PK_CO_PROD_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CO_PROD_DETAIL" ON "EMTS_CO_PROD_DETAIL" ("CO_PROD_DETAIL_ID") 
  ;
/
--------------------------------------------------------
--  Constraints for Table EMTS_FDSTK_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_FDSTK_DETAIL" ADD CONSTRAINT "PK_FDSTK_DETAIL" PRIMARY KEY ("FDSTK_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_FDSTK_DETAIL" MODIFY ("FDSTK_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_FDSTK_DETAIL" MODIFY ("GENR_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_FDSTK_DETAIL" MODIFY ("FDSTK_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_FDSTK_DETAIL" MODIFY ("RENEW_BIOMASS_IND" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_FDSTK_DETAIL" MODIFY ("FDSTK_QNTY" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_FDSTK_DETAIL" MODIFY ("FDSTK_MEAS_CODE" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_SELL_SUPRT_DOC_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_SELL_SUPRT_DOC_DETAIL" ADD CONSTRAINT "PK_SELL_SUPRT_DOC_DETAIL" PRIMARY KEY ("SELL_SUPRT_DOC_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_SELL_SUPRT_DOC_DETAIL" MODIFY ("SELL_SUPRT_DOC_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_SUPRT_DOC_DETAIL" MODIFY ("SELL_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_TXT" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_NUM_TXT" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_RETIRE_SUPRT_DOC_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_RETIRE_SUPRT_DOC_DETAIL" ADD CONSTRAINT "PK_RETIRE_SUPRT_DOC_DETAIL" PRIMARY KEY ("RETIRE_SUPRT_DOC_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_RETIRE_SUPRT_DOC_DETAIL" MODIFY ("RETIRE_SUPRT_DOC_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_RETIRE_SUPRT_DOC_DETAIL" MODIFY ("RETIRE_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_RETIRE_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_TXT" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_RETIRE_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_NUM_TXT" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_CO_PROD_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_CO_PROD_DETAIL" ADD CONSTRAINT "PK_CO_PROD_DETAIL" PRIMARY KEY ("CO_PROD_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_CO_PROD_DETAIL" MODIFY ("CO_PROD_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_CO_PROD_DETAIL" MODIFY ("GENR_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_CO_PROD_DETAIL" MODIFY ("CO_PROD_CODE" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_SELL_TRANS_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_SELL_TRANS_DETAIL" ADD CONSTRAINT "PK_SELL_TRANS_DETAIL" PRIMARY KEY ("SELL_TRANS_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_SELL_TRANS_DETAIL" MODIFY ("SELL_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_TRANS_DETAIL" MODIFY ("EMTS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_TRANS_DETAIL" MODIFY ("TRANS_PART_ORG_IDEN" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_TRANS_DETAIL" MODIFY ("TRANS_PART_ORG_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_TRANS_DETAIL" MODIFY ("RIN_QNTY" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_TRANS_DETAIL" MODIFY ("FUEL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_TRANS_DETAIL" MODIFY ("ASSIGN_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_TRANS_DETAIL" MODIFY ("RIN_YEAR" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_TRANS_DETAIL" MODIFY ("SELL_RSN_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_TRANS_DETAIL" MODIFY ("TRANSFER_DATE" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_RETIRE_TRANS_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_RETIRE_TRANS_DETAIL" ADD CONSTRAINT "PK_RETIRE_TRANS_DETAIL" PRIMARY KEY ("RETIRE_TRANS_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_RETIRE_TRANS_DETAIL" MODIFY ("RETIRE_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_RETIRE_TRANS_DETAIL" MODIFY ("EMTS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_RETIRE_TRANS_DETAIL" MODIFY ("RIN_QNTY" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_RETIRE_TRANS_DETAIL" MODIFY ("FUEL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_RETIRE_TRANS_DETAIL" MODIFY ("ASSIGN_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_RETIRE_TRANS_DETAIL" MODIFY ("RIN_YEAR" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_RETIRE_TRANS_DETAIL" MODIFY ("RETIRE_RSN_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_RETIRE_TRANS_DETAIL" MODIFY ("TRANS_DATE" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_EMTS
--------------------------------------------------------

  ALTER TABLE "EMTS_EMTS" ADD CONSTRAINT "PK_EMTS" PRIMARY KEY ("EMTS_ID") ENABLE;
 
  ALTER TABLE "EMTS_EMTS" MODIFY ("EMTS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_EMTS" MODIFY ("USER_LOGIN_TXT" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_EMTS" MODIFY ("SUBM_CRTN_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_EMTS" MODIFY ("ORG_IDEN" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_BUY_TRANS_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_BUY_TRANS_DETAIL" ADD CONSTRAINT "PK_BUY_TRANS_DETAIL" PRIMARY KEY ("BUY_TRANS_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_BUY_TRANS_DETAIL" MODIFY ("BUY_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_TRANS_DETAIL" MODIFY ("EMTS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_TRANS_DETAIL" MODIFY ("TRANS_PART_ORG_IDEN" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_TRANS_DETAIL" MODIFY ("TRANS_PART_ORG_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_TRANS_DETAIL" MODIFY ("RIN_QNTY" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_TRANS_DETAIL" MODIFY ("FUEL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_TRANS_DETAIL" MODIFY ("ASSIGN_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_TRANS_DETAIL" MODIFY ("RIN_YEAR" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_TRANS_DETAIL" MODIFY ("BUY_RSN_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_TRANS_DETAIL" MODIFY ("TRANSFER_DATE" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_LOCK_TRANS_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_LOCK_TRANS_DETAIL" ADD CONSTRAINT "PK_LOCK_TRANS_DETAIL" PRIMARY KEY ("LOCK_TRANS_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_LOCK_TRANS_DETAIL" MODIFY ("LOCK_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_LOCK_TRANS_DETAIL" MODIFY ("EMTS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_LOCK_TRANS_DETAIL" MODIFY ("FUEL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_LOCK_TRANS_DETAIL" MODIFY ("ASSIGN_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_LOCK_TRANS_DETAIL" MODIFY ("RIN_YEAR" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_GENR_TRANS_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_GENR_TRANS_DETAIL" ADD CONSTRAINT "PK_GENR_TRANS_DETAIL" PRIMARY KEY ("GENR_TRANS_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_GENR_TRANS_DETAIL" MODIFY ("GENR_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_GENR_TRANS_DETAIL" MODIFY ("EMTS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_GENR_TRANS_DETAIL" MODIFY ("RIN_QNTY" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_GENR_TRANS_DETAIL" MODIFY ("FUEL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_GENR_TRANS_DETAIL" MODIFY ("FUEL_CATG_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_GENR_TRANS_DETAIL" MODIFY ("PROD_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_GENR_TRANS_DETAIL" MODIFY ("PROC_CODE" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_SELL_PUB_SUPRT_DOC_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_SELL_PUB_SUPRT_DOC_DETAIL" ADD CONSTRAINT "PK_SELL_PUB_SUPRT_DOC_DETAIL" PRIMARY KEY ("SELL_PUB_SUPRT_DOC_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_SELL_PUB_SUPRT_DOC_DETAIL" MODIFY ("SELL_PUB_SUPRT_DOC_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_PUB_SUPRT_DOC_DETAIL" MODIFY ("SELL_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_PUB_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_TXT" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SELL_PUB_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_NUM_TXT" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_BUY_SUPRT_DOC_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_BUY_SUPRT_DOC_DETAIL" ADD CONSTRAINT "PK_BUY_SUPRT_DOC_DETAIL" PRIMARY KEY ("BUY_SUPRT_DOC_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_BUY_SUPRT_DOC_DETAIL" MODIFY ("BUY_SUPRT_DOC_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_SUPRT_DOC_DETAIL" MODIFY ("BUY_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_TXT" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_NUM_TXT" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_UNLOCK_TRANS_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_UNLOCK_TRANS_DETAIL" MODIFY ("UNLOCK_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_UNLOCK_TRANS_DETAIL" MODIFY ("EMTS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_UNLOCK_TRANS_DETAIL" MODIFY ("FUEL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_UNLOCK_TRANS_DETAIL" MODIFY ("ASSIGN_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_UNLOCK_TRANS_DETAIL" MODIFY ("RIN_YEAR" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_SEPR_SUPRT_DOC_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_SEPR_SUPRT_DOC_DETAIL" ADD CONSTRAINT "PK_SEPR_SUPRT_DOC_DETAIL" PRIMARY KEY ("SEPR_SUPRT_DOC_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_SEPR_SUPRT_DOC_DETAIL" MODIFY ("SEPR_SUPRT_DOC_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SEPR_SUPRT_DOC_DETAIL" MODIFY ("SEPR_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SEPR_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_TXT" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SEPR_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_NUM_TXT" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_BUY_PUB_SUPRT_DOC_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_BUY_PUB_SUPRT_DOC_DETAIL" ADD CONSTRAINT "PK_BUY_PUB_SUPRT_DOC_DETAIL" PRIMARY KEY ("BUY_PUB_SUPRT_DOC_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_BUY_PUB_SUPRT_DOC_DETAIL" MODIFY ("BUY_PUB_SUPRT_DOC_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_PUB_SUPRT_DOC_DETAIL" MODIFY ("BUY_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_PUB_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_TXT" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_BUY_PUB_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_NUM_TXT" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_GENR_SUPRT_DOC_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_GENR_SUPRT_DOC_DETAIL" ADD CONSTRAINT "PK_GENR_SUPRT_DOC_DETAIL" PRIMARY KEY ("GENR_SUPRT_DOC_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_GENR_SUPRT_DOC_DETAIL" MODIFY ("GENR_SUPRT_DOC_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_GENR_SUPRT_DOC_DETAIL" MODIFY ("GENR_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_GENR_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_TXT" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_GENR_SUPRT_DOC_DETAIL" MODIFY ("SUPRT_DOC_NUM_TXT" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table EMTS_SEPR_TRANS_DETAIL
--------------------------------------------------------

  ALTER TABLE "EMTS_SEPR_TRANS_DETAIL" ADD CONSTRAINT "PK_SEPR_TRANS_DETAIL" PRIMARY KEY ("SEPR_TRANS_DETAIL_ID") ENABLE;
 
  ALTER TABLE "EMTS_SEPR_TRANS_DETAIL" MODIFY ("SEPR_TRANS_DETAIL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SEPR_TRANS_DETAIL" MODIFY ("EMTS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SEPR_TRANS_DETAIL" MODIFY ("RIN_QNTY" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SEPR_TRANS_DETAIL" MODIFY ("FUEL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SEPR_TRANS_DETAIL" MODIFY ("RIN_YEAR" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SEPR_TRANS_DETAIL" MODIFY ("SEPR_RSN_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "EMTS_SEPR_TRANS_DETAIL" MODIFY ("TRANS_DATE" NOT NULL ENABLE);
/
