---$ Alter table dbo.RCRA_CA_AREA
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AREA') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AREA
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AREA') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AREA
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_CA_AUTHORITY
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AUTHORITY') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AUTHORITY
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AUTHORITY') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AUTHORITY
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_CA_EVENT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CA_EVENT
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CA_EVENT
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_CME_ENFRC_ACT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_ENFRC_ACT') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_ENFRC_ACT') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_CME_EVAL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CME_EVAL
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CME_EVAL
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_CME_VIOL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_VIOL') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CME_VIOL
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_VIOL') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CME_VIOL
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_EM_EMANIFEST
ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN CREATED_DATE datetime NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN MAN_TRACKING_NUM VARCHAR(12) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN [STATUS] VARCHAR(17) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN ORIGIN_TYPE VARCHAR(7) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN REJ_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN DISCREPANCY_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN IMP_IND CHAR(1) NULL
GO


---$ Alter table dbo.RCRA_EM_HANDLER
ALTER TABLE dbo.RCRA_EM_HANDLER
    ALTER COLUMN SITE_TYPE VARCHAR(11) NULL
GO

ALTER TABLE dbo.RCRA_EM_HANDLER
    ALTER COLUMN MANIFEST_NAME VARCHAR(80) NULL
GO


---$ Alter table dbo.RCRA_EM_WASTE
ALTER TABLE dbo.RCRA_EM_WASTE
    ALTER COLUMN DOT_HAZ_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_EM_WASTE
    ALTER COLUMN PCB_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_EM_WASTE
    ALTER COLUMN LINE_NUM INT NULL
GO


---$ Alter table dbo.RCRA_FA_COST_EST
ALTER TABLE dbo.RCRA_FA_COST_EST
    ALTER COLUMN COST_ESTIMATE_DATE datetime NOT NULL
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'UPDATE_DUE_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST
        ADD UPDATE_DUE_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'CURRENT_COST_ESTIMATE_IND')
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST
        ADD CURRENT_COST_ESTIMATE_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_FA_MECHANISM
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'PROVIDER_CONTACT_EMAIL')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM
        ADD PROVIDER_CONTACT_EMAIL VARCHAR(80) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'ACTIVE_MECHANISM_IND')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM
        ADD ACTIVE_MECHANISM_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_FA_MECHANISM_DETAIL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'FAC_FACE_VAL_AMOUNT')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD FAC_FACE_VAL_AMOUNT DECIMAL(14,6) NOT NULL CONSTRAINT FAC_FACE_VAL_AMOUNT_Default_ForNotNullCol DEFAULT (0)

    -- drop generated default constraint
    IF OBJECT_ID(N'FAC_FACE_VAL_AMOUNT_Default_ForNotNullCol') IS NOT NULL 
        ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL 
            DROP CONSTRAINT FAC_FACE_VAL_AMOUNT_Default_ForNotNullCol
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'ALT_IND')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD ALT_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_GIS_GEO_INFORMATION
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_GIS_GEO_INFORMATION') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_GIS_GEO_INFORMATION
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_GIS_GEO_INFORMATION') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_GIS_GEO_INFORMATION
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_HD_HANDLER
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD LAST_UPDT_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'BR_EXEMPT_IND')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD BR_EXEMPT_IND CHAR(1) NULL
END
GO


---$ Alter table dbo.RCRA_PRM_EVENT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_EVENT') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_EVENT
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_EVENT') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_EVENT
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_PRM_SERIES
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_SERIES') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_SERIES
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_SERIES') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_SERIES
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_PRM_UNIT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_PRM_UNIT_DETAIL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT_DETAIL') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT_DETAIL
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT_DETAIL') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT_DETAIL
        ADD LAST_UPDT_DATE datetime NULL
END
GO


