/*
Copyright (c) 2016, The Environmental Council of the States (ECOS)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE ;ODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/

/*****************************************************************************************************************************
 *
 *  Script Name:  RCRA_5.10_to_5.11-upgrade_SQL-DDL.sql
 *
 *  Company:  Windsor Solutions, Inc.
 *
 *  Purpose:  This DDL script will update the SQL Server RCRA v5.10 database objects to support the RCRA v5.11 data flow.
 *
 *  Maintenance:
 *
 *    Analyst         Date            Comment
 *    ----------      ----------      ------------------------------------------------------------------------------
 *    Windsor         12/02/2021      Created
 *
 ****************************************************************************************************************************
 */

---$ Alter table dbo.RCRA_CA_AREA
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AREA') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AREA
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AREA') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AREA
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_CA_AUTHORITY
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AUTHORITY') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AUTHORITY
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AUTHORITY') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CA_AUTHORITY
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_CA_EVENT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CA_EVENT
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CA_EVENT
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_CME_ENFRC_ACT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_ENFRC_ACT') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_ENFRC_ACT') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_CME_EVAL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CME_EVAL
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CME_EVAL
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_CME_VIOL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_VIOL') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_CME_VIOL
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_VIOL') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_CME_VIOL
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_EM_EMANIFEST
ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN CREATED_DATE datetime NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN MAN_TRACKING_NUM VARCHAR(12) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN [STATUS] VARCHAR(17) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN ORIGIN_TYPE VARCHAR(7) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN REJ_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN DISCREPANCY_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ALTER COLUMN IMP_IND CHAR(1) NULL
GO


---$ Alter table dbo.RCRA_EM_HANDLER
ALTER TABLE dbo.RCRA_EM_HANDLER
    ALTER COLUMN SITE_TYPE VARCHAR(11) NULL
GO

ALTER TABLE dbo.RCRA_EM_HANDLER
    ALTER COLUMN MANIFEST_NAME VARCHAR(80) NULL
GO


---$ Alter table dbo.RCRA_EM_WASTE
ALTER TABLE dbo.RCRA_EM_WASTE
    ALTER COLUMN DOT_HAZ_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_EM_WASTE
    ALTER COLUMN PCB_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_EM_WASTE
    ALTER COLUMN LINE_NUM INT NULL
GO


---$ Alter table dbo.RCRA_FA_COST_EST
ALTER TABLE dbo.RCRA_FA_COST_EST
    ALTER COLUMN COST_ESTIMATE_DATE datetime NULL
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'UPDATE_DUE_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST
        ADD UPDATE_DUE_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'CURRENT_COST_ESTIMATE_IND')
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST
        ADD CURRENT_COST_ESTIMATE_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_FA_MECHANISM
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'PROVIDER_CONTACT_EMAIL')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM
        ADD PROVIDER_CONTACT_EMAIL VARCHAR(80) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'ACTIVE_MECHANISM_IND')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM
        ADD ACTIVE_MECHANISM_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_FA_MECHANISM_DETAIL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'FAC_FACE_VAL_AMOUNT')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD FAC_FACE_VAL_AMOUNT DECIMAL(14,6) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'ALT_IND')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD ALT_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_GIS_GEO_INFORMATION
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_GIS_GEO_INFORMATION') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_GIS_GEO_INFORMATION
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_GIS_GEO_INFORMATION') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_GIS_GEO_INFORMATION
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_HD_HANDLER
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD LAST_UPDT_DATE datetime NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'BR_EXEMPT_IND')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD BR_EXEMPT_IND CHAR(1) NULL
END
GO


---$ Alter table dbo.RCRA_PRM_EVENT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_EVENT') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_EVENT
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_EVENT') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_EVENT
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_PRM_SERIES
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_SERIES') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_SERIES
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_SERIES') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_SERIES
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_PRM_UNIT
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT
        ADD LAST_UPDT_DATE datetime NULL
END
GO


---$ Alter table dbo.RCRA_PRM_UNIT_DETAIL
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT_DETAIL') AND NAME = 'LAST_UPDT_BY')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT_DETAIL
        ADD LAST_UPDT_BY VARCHAR(255) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT_DETAIL') AND NAME = 'LAST_UPDT_DATE')
BEGIN
    ALTER TABLE dbo.RCRA_PRM_UNIT_DETAIL
        ADD LAST_UPDT_DATE datetime NULL
END
GO


