/*
Copyright (c) 2016, The Environmental Council of the States (ECOS)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE ;ODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/

/*****************************************************************************************************************************
 *
 *  Script Name:  RCRA_5.10_to_5.11-upgrade_ORA-DDL.sql
 *
 *  Company:  Windsor Solutions, Inc.
 *
 *  Purpose:  This DDL script will update the Oracle RCRA v5.10 database objects to support the RCRA v5.11 data flow.
 *
 *  Maintenance:
 *
 *    Analyst         Date            Comment
 *    ----------      ----------      ------------------------------------------------------------------------------
 *    Windsor         12/02/2021      Created
 *
 ****************************************************************************************************************************
 */

ALTER TABLE RCRA_CA_AREA
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_CA_AREA
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_CA_AUTHORITY
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_CA_AUTHORITY
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_CA_EVENT
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_CA_EVENT
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_CME_ENFRC_ACT
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_CME_ENFRC_ACT
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_CME_EVAL
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_CME_EVAL
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_CME_VIOL
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_CME_VIOL
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_EM_EMANIFEST
    MODIFY CREATED_DATE DATE NULL;
    
ALTER TABLE RCRA_EM_EMANIFEST
    MODIFY MAN_TRACKING_NUM VARCHAR2(12) NULL;

ALTER TABLE RCRA_EM_EMANIFEST
    MODIFY "STATUS" VARCHAR2(17) NULL;

ALTER TABLE RCRA_EM_EMANIFEST
    MODIFY ORIGIN_TYPE VARCHAR2(7) NULL;

ALTER TABLE RCRA_EM_EMANIFEST
    MODIFY REJ_IND CHAR(1) NULL;

ALTER TABLE RCRA_EM_EMANIFEST
    MODIFY DISCREPANCY_IND CHAR(1) NULL;

ALTER TABLE RCRA_EM_EMANIFEST
    MODIFY IMP_IND CHAR(1) NULL;

ALTER TABLE RCRA_EM_HANDLER
    MODIFY SITE_TYPE VARCHAR2(11) NULL;

ALTER TABLE RCRA_EM_HANDLER
    MODIFY MANIFEST_NAME VARCHAR2(80) NULL;

ALTER TABLE RCRA_EM_WASTE
    MODIFY DOT_HAZ_IND CHAR(1) NULL;

ALTER TABLE RCRA_EM_WASTE
    MODIFY PCB_IND CHAR(1) NULL;

ALTER TABLE RCRA_EM_WASTE
    MODIFY LINE_NUM INT NULL;

ALTER TABLE RCRA_FA_COST_EST
        ADD UPDATE_DUE_DATE DATE NULL;

ALTER TABLE RCRA_FA_COST_EST
        ADD CURRENT_COST_ESTIMATE_IND CHAR(1) NULL;

ALTER TABLE RCRA_FA_COST_EST
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_FA_COST_EST
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_FA_MECHANISM
        ADD PROVIDER_CONTACT_EMAIL VARCHAR2(80) NULL;

ALTER TABLE RCRA_FA_MECHANISM
        ADD ACTIVE_MECHANISM_IND CHAR(1) NULL;

ALTER TABLE RCRA_FA_MECHANISM
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_FA_MECHANISM
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_FA_MECHANISM_DETAIL
        ADD FAC_FACE_VAL_AMOUNT DECIMAL(14,6) NULL;

ALTER TABLE RCRA_FA_MECHANISM_DETAIL
        ADD ALT_IND CHAR(1) NULL;

ALTER TABLE RCRA_FA_MECHANISM_DETAIL
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_FA_MECHANISM_DETAIL
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_GIS_GEO_INFORMATION
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_GIS_GEO_INFORMATION
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_HD_HANDLER
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_HD_HANDLER
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_HD_HANDLER
        ADD BR_EXEMPT_IND CHAR(1) NULL;

ALTER TABLE RCRA_PRM_EVENT
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_PRM_EVENT
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_PRM_SERIES
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_PRM_SERIES
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_PRM_UNIT
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_PRM_UNIT
        ADD LAST_UPDT_DATE DATE NULL;

ALTER TABLE RCRA_PRM_UNIT_DETAIL
        ADD LAST_UPDT_BY VARCHAR2(255) NULL;

ALTER TABLE RCRA_PRM_UNIT_DETAIL
        ADD LAST_UPDT_DATE DATE NULL;



