//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.24 at 11:33:47 AM PST 
//


package com.windsor.node.plugin.facid3.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FacilityAffiliationDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FacilityAffiliationDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}AffiliateIdentifier"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}Affiliation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FacilityAffiliationDataType", propOrder = {
    "affiliateIdentifier",
    "affiliation"
})
public class FacilityAffiliationDataType {

    @XmlElement(name = "AffiliateIdentifier", required = true)
    protected String affiliateIdentifier;
    @XmlElement(name = "Affiliation")
    protected AffiliationDataType affiliation;

    /**
     * Gets the value of the affiliateIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliateIdentifier() {
        return affiliateIdentifier;
    }

    /**
     * Sets the value of the affiliateIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliateIdentifier(String value) {
        this.affiliateIdentifier = value;
    }

    /**
     * Gets the value of the affiliation property.
     * 
     * @return
     *     possible object is
     *     {@link AffiliationDataType }
     *     
     */
    public AffiliationDataType getAffiliation() {
        return affiliation;
    }

    /**
     * Sets the value of the affiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AffiliationDataType }
     *     
     */
    public void setAffiliation(AffiliationDataType value) {
        this.affiliation = value;
    }

}
