//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.24 at 11:33:47 AM PST 
//


package com.windsor.node.plugin.facid3.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferenceMethodDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenceMethodDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}MethodIdentifierCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}MethodIdentifierCodeListIdentifier" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}MethodName" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}MethodDescriptionText" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/facilityid/3}MethodDeviationsText" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceMethodDataType", propOrder = {
    "methodIdentifierCode",
    "methodIdentifierCodeListIdentifier",
    "methodName",
    "methodDescriptionText",
    "methodDeviationsText"
})
public class ReferenceMethodDataType {

    @XmlElement(name = "MethodIdentifierCode")
    protected String methodIdentifierCode;
    @XmlElement(name = "MethodIdentifierCodeListIdentifier")
    protected MethodIdentifierCodeListIdentifierDataType methodIdentifierCodeListIdentifier;
    @XmlElement(name = "MethodName")
    protected String methodName;
    @XmlElement(name = "MethodDescriptionText")
    protected String methodDescriptionText;
    @XmlElement(name = "MethodDeviationsText")
    protected String methodDeviationsText;

    /**
     * Gets the value of the methodIdentifierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodIdentifierCode() {
        return methodIdentifierCode;
    }

    /**
     * Sets the value of the methodIdentifierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodIdentifierCode(String value) {
        this.methodIdentifierCode = value;
    }

    /**
     * Gets the value of the methodIdentifierCodeListIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MethodIdentifierCodeListIdentifierDataType }
     *     
     */
    public MethodIdentifierCodeListIdentifierDataType getMethodIdentifierCodeListIdentifier() {
        return methodIdentifierCodeListIdentifier;
    }

    /**
     * Sets the value of the methodIdentifierCodeListIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodIdentifierCodeListIdentifierDataType }
     *     
     */
    public void setMethodIdentifierCodeListIdentifier(MethodIdentifierCodeListIdentifierDataType value) {
        this.methodIdentifierCodeListIdentifier = value;
    }

    /**
     * Gets the value of the methodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * Sets the value of the methodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodName(String value) {
        this.methodName = value;
    }

    /**
     * Gets the value of the methodDescriptionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodDescriptionText() {
        return methodDescriptionText;
    }

    /**
     * Sets the value of the methodDescriptionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodDescriptionText(String value) {
        this.methodDescriptionText = value;
    }

    /**
     * Gets the value of the methodDeviationsText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodDeviationsText() {
        return methodDeviationsText;
    }

    /**
     * Sets the value of the methodDeviationsText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodDeviationsText(String value) {
        this.methodDeviationsText = value;
    }

}
