CREATE OR REPLACE VIEW RCRA_CA_REL_EVENT_VW AS
(
   SELECT
    CA_AREA_REL_EVENT_ID CA_REL_EVENT_ID,
    CA_AREA_ID,
    NULL CA_AUTHORITY_ID,
    TRANS_CODE,
    ACT_LOC_CODE,
    CORCT_ACT_EVENT_DATA_OWNER_CDE,
    CORCT_ACT_EVENT_CODE,
    EVENT_AGN_CODE,
    EVENT_SEQ_NUM
   FROM 
    RCRA_CA_AREA_REL_EVENT
   UNION ALL
   SELECT
    CA_AUTH_REL_EVENT_ID,
    NULL,
    CA_AUTHORITY_ID,
    TRANS_CODE,
    ACT_LOC_CODE,
    CORCT_ACT_EVENT_DATA_OWNER_CDE,
    CORCT_ACT_EVENT_CODE,
    EVENT_AGN_CODE,
    EVENT_SEQ_NUM
   FROM 
    RCRA_CA_AUTH_REL_EVENT
);

CREATE OR REPLACE VIEW RCRA_EVENT_COMMITMENT_VW AS
(
   SELECT
    CA_EVENT_COMMITMENT_ID EVENT_COMMITMENT_ID,
    CA_EVENT_ID, 
    NULL PRM_EVENT_ID,
    TRANS_CODE,
    COMMIT_LEAD,
    COMMIT_SEQ_NUM
   FROM 
    RCRA_CA_EVENT_COMMITMENT
   UNION ALL
   SELECT
    PRM_EVENT_COMMITMENT_ID,
    NULL,
    PRM_EVENT_ID,
    TRANS_CODE,
    COMMIT_LEAD,
    COMMIT_SEQ_NUM
   FROM 
    RCRA_PRM_EVENT_COMMITMENT
);

CREATE OR REPLACE VIEW RCRA_WASTE_CODE_VW AS
(
   SELECT
    HD_SEC_WASTE_CODE_ID WASTE_CODE_ID,
    HD_SEC_MATERIAL_ACTIVITY_ID,
    NULL HD_HANDLER_ID,
    NULL PRM_UNIT_DETAIL_ID,
    TRANSACTION_CODE TRANS_CODE,
    WASTE_CODE_OWNER,
    WASTE_CODE_TYPE
   FROM 
    RCRA_HD_SEC_WASTE_CODE
   UNION ALL
   SELECT
    HD_WASTE_CODE_ID,
    NULL,
    HD_HANDLER_ID,
    NULL PRM_UNIT_DETAIL_ID,
    TRANSACTION_CODE,
    WASTE_CODE_OWNER,
    WASTE_CODE_TYPE
   FROM 
    RCRA_HD_WASTE_CODE
   UNION ALL
   SELECT
    PRM_WASTE_CODE_ID,
    NULL,
    NULL,
    PRM_UNIT_DETAIL_ID,
    TRANSACTION_CODE,
    WASTE_CODE_OWNER,
    WASTE_CODE_TYPE
   FROM 
    RCRA_PRM_WASTE_CODE
);
