#region License
/*
Copyright (c) 2009, The Environmental Council of the States (ECOS)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/
#endregion

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;


//namespace PNWWQX_DataCatalog
namespace pnwwqx.rp
{

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:net:exchangenetwork")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:us:net:exchangenetwork", IsNullable=false)]
    public class PNWWQXDataCatalog 
    {
        public PNWWQXDataCatalog()
        {
            XmlDocument d = new XmlDocument();
            XmlAttribute xsi = d.CreateAttribute("xsi", "noNamespaceSchemaLocation", XmlSchema.InstanceNamespace);
            xsi.Value = "http://www.exchangenetwork.net/Registry/PNWWQX_DataCatalog_v.1.3.xsd";
            this.XAttributes = new XmlAttribute[] {xsi};
        }

        [XmlAnyAttribute]
        public XmlAttribute[] XAttributes;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PNWWQXDataCatalogList")]
        public PNWWQXDataCatalogList[] PNWWQXDataCatalogList;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:net:exchangenetwork")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:us:net:exchangenetwork", IsNullable=false)]
    public class PNWWQXDataCatalogList 
    {
    
        /// <remarks/>
        public ProvidingOrganizationDetailsType ProvidingOrganizationDetails;
    
        /// <remarks/>
        public DataAccessType DataAccess;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectSummary")]
        public ProjectSummaryType[] ProjectSummary;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StationSummary")]
        public StationSummaryType[] StationSummary;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FieldEventSummary")]
        public FieldEventSummaryType[] FieldEventSummary;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:net:exchangenetwork")]
    [System.Xml.Serialization.XmlRootAttribute("FieldEventSummary", Namespace="urn:us:net:exchangenetwork", IsNullable=false)]
    public class FieldEventSummaryType 
    {
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime MinFieldEventStartDate;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime MaxFieldEventEndDate;
    
        /// <remarks/>
        public string MediaText;
    
        /// <remarks/>
        public string BiologicalSystematicName;
    
        /// <remarks/>
        public string AnalyteName;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string NumberResults;
    
        /// <remarks/>
        public string FieldEventProjectIdentifier;
    
        /// <remarks/>
        public string FieldEventStationIdentifier;
    
        /// <remarks/>
        public string FieldEventContactOrganizationName;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:net:exchangenetwork")]
    [System.Xml.Serialization.XmlRootAttribute("LocationDescriptor", Namespace="urn:us:net:exchangenetwork", IsNullable=false)]
    public class StationLocationDescriptorType 
    {
    
        /// <remarks/>
        public string LocationDescriptorName;
    
        /// <remarks/>
        public string LocationDescriptorContext;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:net:exchangenetwork")]
    [System.Xml.Serialization.XmlRootAttribute("StationSummary", Namespace="urn:us:net:exchangenetwork", IsNullable=false)]
    public class StationSummaryType 
    {
    
        /// <remarks/>
        public string StationIdentifier;
    
        /// <remarks/>
        public string StationName;
    
        /// <remarks/>
        public string StationType;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LocationDescriptor")]
        public StationLocationDescriptorType[] LocationDescriptor;
    
        /// <remarks/>
        public System.Decimal LatitudeMeasure;
    
        /// <remarks/>
        public System.Decimal LongitudeMeasure;
    
        /// <remarks/>
        public string StationContactOrganizationName;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:net:exchangenetwork")]
    [System.Xml.Serialization.XmlRootAttribute("ProjectSummary", Namespace="urn:us:net:exchangenetwork", IsNullable=false)]
    public class ProjectSummaryType 
    {
    
        /// <remarks/>
        public string ProjectIdentifier;
    
        /// <remarks/>
        public string ProjectName;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ProjectStartDate;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ProjectEndDate;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProjectEndDateSpecified;
    
        /// <remarks/>
        public string ProjectContactOrganizationName;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:net:exchangenetwork")]
    [System.Xml.Serialization.XmlRootAttribute("DataAccess", Namespace="urn:us:net:exchangenetwork", IsNullable=false)]
    public class DataAccessType 
    {
    
        /// <remarks/>
        public string DataSourceName;
    
        /// <remarks/>
        public string DataSourceAccessMethod;
    
        /// <remarks/>
        public string DataSourceLocation;
    
        /// <remarks/>
        public string AvailabilityDescription;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime RefreshDate;
    }

}