--------------------------------------------------------
--  File created - Friday-November-20-2009   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRI_CHEM
--------------------------------------------------------

  CREATE TABLE "TRI_CHEM" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"CAS_CLBER" VARCHAR2(100), 
	"CHEM_TXT" VARCHAR2(100), 
	"CHEM_MIXTURE_TXT" VARCHAR2(100), 
	"CHEM_ID" VARCHAR2(100), 
	"CHEM_REGISTRY" VARCHAR2(100), 
	"CHEM_REGISTRY_CTX" VARCHAR2(100), 
	"DIOXIN_DIST1" VARCHAR2(100), 
	"DIOXIN_DIST2" VARCHAR2(100), 
	"DIOXIN_DIST3" VARCHAR2(100), 
	"DIOXIN_DIST4" VARCHAR2(100), 
	"DIOXIN_DIST5" VARCHAR2(100), 
	"DIOXIN_DIST6" VARCHAR2(100), 
	"DIOXIN_DIST7" VARCHAR2(100), 
	"DIOXIN_DIST8" VARCHAR2(100), 
	"DIOXIN_DIST9" VARCHAR2(100), 
	"DIOXIN_DIST10" VARCHAR2(100), 
	"DIOXIN_DIST11" VARCHAR2(100), 
	"DIOXIN_DIST12" VARCHAR2(100), 
	"DIOXIN_DIST13" VARCHAR2(100), 
	"DIOXIN_DIST14" VARCHAR2(100), 
	"DIOXIN_DIST15" VARCHAR2(100), 
	"DIOXIN_DIST16" VARCHAR2(100), 
	"DIOXIN_DIST17" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_FAC
--------------------------------------------------------

  CREATE TABLE "TRI_FAC" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"FAC_ID" VARCHAR2(100), 
	"FAC_SITE" VARCHAR2(100), 
	"LOC_ADD_TXT" VARCHAR2(100), 
	"SUPP_LOC_TXT" VARCHAR2(100), 
	"LOCALITY" VARCHAR2(100), 
	"STATE_CL_ID" VARCHAR2(100), 
	"STATE_CODE" VARCHAR2(10), 
	"STATE" VARCHAR2(50), 
	"ADD_POSTAL_CODE" VARCHAR2(50), 
	"COUNTRY_CL_ID" VARCHAR2(100), 
	"COUNTRY_CODE" VARCHAR2(10), 
	"COUNTRY" VARCHAR2(50), 
	"COUNTY_CL_ID" VARCHAR2(100), 
	"COUNTY_CODE" VARCHAR2(100), 
	"COUNTY" VARCHAR2(100), 
	"TRIBAL_CL_ID" VARCHAR2(100), 
	"TRIBAL_CODE" VARCHAR2(100), 
	"TRIBAL" VARCHAR2(100), 
	"TRIBAL_LAND" VARCHAR2(100), 
	"TRIBAL_LAND_IND" VARCHAR2(100), 
	"LOC_DESCN_TXT" VARCHAR2(100), 
	"MAIL_FAC_SITE" VARCHAR2(100), 
	"MAIL_ADD_TXT" VARCHAR2(100), 
	"SUPP_MAIL_ADD" VARCHAR2(100), 
	"MAIL_ADD_CITY" VARCHAR2(100), 
	"MAIL_ADD_POSTAL_CODE" VARCHAR2(100), 
	"PROVINCE_TXT" VARCHAR2(100), 
	"MAIL_ADD_STATE_CDLST" VARCHAR2(100), 
	"MAIL_ADD_STATE_CODE" VARCHAR2(10), 
	"MAIL_ADD_STATE" VARCHAR2(100), 
	"MAIL_ADD_COUNTRY_CDLST" VARCHAR2(100), 
	"MAIL_ADD_COUNTRY_CODE" VARCHAR2(10), 
	"MAIL_ADD_COUNTRY" VARCHAR2(100), 
	"LAT_ME" VARCHAR2(20), 
	"LON_ME" VARCHAR2(20), 
	"SRC_MAP_SCALE_CLBER" VARCHAR2(100), 
	"HOR_ME_VALUE" VARCHAR2(100), 
	"HOR_ME_UNIT_CODE" VARCHAR2(100), 
	"HOR_ME_UNIT" VARCHAR2(100), 
	"HOR_ME_PREC_TXT" VARCHAR2(100), 
	"HOR_RESULT_QFR_CODE" VARCHAR2(100), 
	"HOR_RESULT_QFR" VARCHAR2(100), 
	"HOR_METH_ID_CODE" VARCHAR2(100), 
	"HOR_METH" VARCHAR2(100), 
	"HOR_METH_DESCN_TXT" VARCHAR2(100), 
	"HOR_METH_DEV_TXT" VARCHAR2(100), 
	"GEO_REF_POINT_CD" VARCHAR2(100), 
	"GEO_REF_POINT_NM" VARCHAR2(100), 
	"HOR_REF_DATUM_CD" VARCHAR2(100), 
	"HOR_REF_DATUM_NM" VARCHAR2(100), 
	"DATA_COLLECTION_DATE" VARCHAR2(100), 
	"LOC_COMS_TXT" VARCHAR2(100), 
	"VER_ME_VALUE" VARCHAR2(100), 
	"VER_ME_UNIT_CODE" VARCHAR2(100), 
	"VER_ME_UNIT" VARCHAR2(100), 
	"VER_ME_PREC_TXT" VARCHAR2(100), 
	"VER_RESULT_QFR_CODE" VARCHAR2(100), 
	"VER_RESULT_QFR" VARCHAR2(100), 
	"VER_METH_ID_CODE" VARCHAR2(100), 
	"VER_METH" VARCHAR2(100), 
	"VER_METH_DESCN_TXT" VARCHAR2(100), 
	"VER_METH_DEV_TXT" VARCHAR2(100), 
	"GEO_REF_DATUM_CD" VARCHAR2(100), 
	"GEO_REF_DATUM_NM" VARCHAR2(100), 
	"VERIF_METH_ID" VARCHAR2(100), 
	"VERIF_METH" VARCHAR2(100), 
	"VERIF_METH_DESC" VARCHAR2(100), 
	"VERIF_METH_DEV" VARCHAR2(100), 
	"COORD_DATA_SRC_CODE" VARCHAR2(100), 
	"COORD_DATA_SRC" VARCHAR2(100), 
	"GEOMETRIC_TYPE_CODE" VARCHAR2(100), 
	"GEOMETRIC_TYPE" VARCHAR2(100), 
	"LAT_DEGREE_ME" VARCHAR2(100), 
	"LAT_MINUTE_ME" VARCHAR2(100), 
	"LAT_SECOND_ME" VARCHAR2(100), 
	"LON_DEGREE_ME" VARCHAR2(100), 
	"LON_MINUTE_ME" VARCHAR2(100), 
	"LON_SECOND_ME" VARCHAR2(100), 
	"PARENT_COMPANY_TXT" VARCHAR2(100), 
	"PARENT_DUN_CODE" VARCHAR2(100), 
	"FACILITY_ACCESS_CODE" VARCHAR2(100), 
	"PRI_YR_TECH_CONTACT_NAME" VARCHAR2(100), 
	"PRI_YR_TECH_CONTACT_PHONE" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_FAC_DUN
--------------------------------------------------------

  CREATE TABLE "TRI_FAC_DUN" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"FAC_DUN_CODE" VARCHAR2(9)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_FAC_NAICS
--------------------------------------------------------

  CREATE TABLE "TRI_FAC_NAICS" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"FAC_NAICS" VARCHAR2(100), 
	"NAICS_PRIMARY_IND" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_FAC_SIC
--------------------------------------------------------

  CREATE TABLE "TRI_FAC_SIC" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"FAC_SIC" VARCHAR2(100), 
	"SIC_PRIMARY_IND" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_NPDES_ID
--------------------------------------------------------

  CREATE TABLE "TRI_NPDES_ID" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"NPDES_ID_CLBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_OFFSITE_DISP_QTY
--------------------------------------------------------

  CREATE TABLE "TRI_OFFSITE_DISP_QTY" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"YEAR_OFFSET_ME" VARCHAR2(100), 
	"TOTAL_Q" VARCHAR2(100), 
	"TOTAL_Q_NA_IND" CHAR(1), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_OFFSITE_ENERGY_REC_QTY
--------------------------------------------------------

  CREATE TABLE "TRI_OFFSITE_ENERGY_REC_QTY" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"YEAR_OFFSET_ME" VARCHAR2(100), 
	"TOTAL_Q" VARCHAR2(100), 
	"TOTAL_Q_NA_IND" CHAR(1), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_OFFSITE_RECYCLED_Q
--------------------------------------------------------

  CREATE TABLE "TRI_OFFSITE_RECYCLED_Q" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"YEAR_OFFSET_ME" VARCHAR2(100), 
	"TOTAL_Q" VARCHAR2(100), 
	"TOTAL_Q_NA_IND" CHAR(1), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_OFFSITE_TREATED_Q
--------------------------------------------------------

  CREATE TABLE "TRI_OFFSITE_TREATED_Q" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"YEAR_OFFSET_ME" VARCHAR2(100), 
	"TOTAL_Q" VARCHAR2(100), 
	"TOTAL_Q_NA_IND" CHAR(1), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_OFFSITE_UIC_DISP_QTY
--------------------------------------------------------

  CREATE TABLE "TRI_OFFSITE_UIC_DISP_QTY" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"YEAR_OFFSET_ME" VARCHAR2(100), 
	"TOTAL_Q" VARCHAR2(100), 
	"TOTAL_Q_NA_IND" CHAR(1), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_ONSITE_DISP_QTY
--------------------------------------------------------

  CREATE TABLE "TRI_ONSITE_DISP_QTY" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"YEAR_OFFSET_ME" VARCHAR2(100), 
	"TOTAL_Q" VARCHAR2(100), 
	"TOTAL_Q_NA_IND" CHAR(1), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_ONSITE_ENERGY_RCV_QTY
--------------------------------------------------------

  CREATE TABLE "TRI_ONSITE_ENERGY_RCV_QTY" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"YEAR_OFFSET_ME" VARCHAR2(100), 
	"TOTAL_Q" VARCHAR2(100), 
	"TOTAL_Q_NA_IND" CHAR(1), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_ONSITE_RCV_PROC
--------------------------------------------------------

  CREATE TABLE "TRI_ONSITE_RCV_PROC" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"ENERGY_RCV_METH_CODE" VARCHAR2(100), 
	"ENERGY_RCV_NA_IND" CHAR(1)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_ONSITE_RECYCG_PROC
--------------------------------------------------------

  CREATE TABLE "TRI_ONSITE_RECYCG_PROC" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"ONSITE_RECYCG_METH_CODE" VARCHAR2(100), 
	"ONSITE_RECYCG_NA_IND" CHAR(1)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_ONSITE_RECYCLED_Q
--------------------------------------------------------

  CREATE TABLE "TRI_ONSITE_RECYCLED_Q" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"YEAR_OFFSET_ME" VARCHAR2(100), 
	"TOTAL_Q" VARCHAR2(100), 
	"TOTAL_Q_NA_IND" CHAR(1), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_ONSITE_RELEASE_Q
--------------------------------------------------------

  CREATE TABLE "TRI_ONSITE_RELEASE_Q" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"EI_MEDIUM_CODE" VARCHAR2(100), 
	"WASTE_Q_ME" VARCHAR2(100), 
	"WASTE_Q_NA_IND" CHAR(1), 
	"WASTE_Q_RANGE_CODE" VARCHAR2(100), 
	"Q_BASIS_EST_CD" VARCHAR2(100), 
	"Q_BASIS_NA_IND" CHAR(1), 
	"WATER_SEQ_CLBER" VARCHAR2(100), 
	"STREAM" VARCHAR2(100), 
	"RELEASE_STORM_WATER" VARCHAR2(100), 
	"RELEASE_STORM_NA_IND" CHAR(1), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"WASTE_Q_CATASTROPHIC_MEASURE" VARCHAR2(100), 
	"WASTE_Q_RANGE_NUM_BASIS_VALUE" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_ONSITE_TREATED_Q
--------------------------------------------------------

  CREATE TABLE "TRI_ONSITE_TREATED_Q" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"YEAR_OFFSET_ME" VARCHAR2(100), 
	"TOTAL_Q" VARCHAR2(100), 
	"TOTAL_Q_NA_IND" CHAR(1), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_ONSITE_UIC_DISP_QTY
--------------------------------------------------------

  CREATE TABLE "TRI_ONSITE_UIC_DISP_QTY" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"YEAR_OFFSET_ME" VARCHAR2(100), 
	"TOTAL_Q" VARCHAR2(100), 
	"TOTAL_Q_NA_IND" CHAR(1), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_RCRA_ID
--------------------------------------------------------

  CREATE TABLE "TRI_RCRA_ID" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"RCRA_ID_CLBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_REPLACED_REPORT_ID
--------------------------------------------------------

  CREATE TABLE "TRI_REPLACED_REPORT_ID" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"REPLACED_REPORT_ID" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_REPORT
--------------------------------------------------------

  CREATE TABLE "TRI_REPORT" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"REPORT_ID" VARCHAR2(100), 
	"REPORT_POST_DATE" VARCHAR2(50), 
	"REPORT_REC_DATE" VARCHAR2(50), 
	"REPORT_ORIG_POST_DATE" VARCHAR2(50), 
	"REPORT_ORIG_REC_DATE" VARCHAR2(50), 
	"REPORT_SUB_METH_CODE" VARCHAR2(100), 
	"REPORT_EPA_PASSED_VALID_IND" CHAR(1), 
	"REPORT_EPA_PROCESSING_STATUS_C" VARCHAR2(100), 
	"UNALTERED_REPORT_IND" VARCHAR2(100), 
	"REPORT_TYPE_CODE" VARCHAR2(100), 
	"SUB_REP_YEAR" VARCHAR2(100), 
	"REPORT_DUE_DATE" VARCHAR2(50), 
	"REVISION_IND" VARCHAR2(100), 
	"CHEM_TRADE_SECRET_IND" VARCHAR2(100), 
	"SUB_SANITIZED_IND" VARCHAR2(100), 
	"CERTIFIER" VARCHAR2(100), 
	"CERTIFIER_TIT_TXT" VARCHAR2(100), 
	"CERT_SIGNED_DATE" VARCHAR2(100), 
	"SUB_ENTIRE_FAC_IND" VARCHAR2(100), 
	"SUB_PARTIAL_FAC_ID" VARCHAR2(100), 
	"SUB_FEDERAL_FAC_ID" VARCHAR2(100), 
	"SUB_CO_FAC_INDIC" VARCHAR2(100), 
	"TECH_CONT" VARCHAR2(100), 
	"TECH_CONT_PHONE_TXT" VARCHAR2(100), 
	"TECH_CONT_EMAIL_ADDRES" VARCHAR2(100), 
	"PUB_CONT_ID" VARCHAR2(100), 
	"PUB_CONT_TIT_TXT" VARCHAR2(100), 
	"PUB_CONT" VARCHAR2(100), 
	"PUB_CONT_PHONE_TXT" VARCHAR2(50), 
	"CHEM_ANC_USAGE_IND" VARCHAR2(100), 
	"CHEM_ARTICLE_COMP_ID" VARCHAR2(100), 
	"CHEM_BYPRODUCT_IND" VARCHAR2(100), 
	"CHEM_FORMULATION_COMP" VARCHAR2(100), 
	"CHEM_IMPORTED_IND" VARCHAR2(100), 
	"CHEM_MANUFACTURE_AID_ID" VARCHAR2(100), 
	"CHEM_MANUFACTURE_IMPURITY" VARCHAR2(100), 
	"CHEM_PROC_IMPURITY_ID" VARCHAR2(100), 
	"CHEM_PROCING_AID_ID" VARCHAR2(100), 
	"CHEM_PRODUCED_IND" VARCHAR2(100), 
	"CHEM_REACTANT_IND" VARCHAR2(100), 
	"CHEM_REP_IND" VARCHAR2(100), 
	"CHEM_SALES_DIST_ID" VARCHAR2(100), 
	"CHEM_USED_PROCED_ID" VARCHAR2(100), 
	"MAX_CHEM_AMOUNT_CODE" VARCHAR2(100), 
	"WASTE_Q_ME" VARCHAR2(100), 
	"WASTE_Q_ME_NA_IND" CHAR(1), 
	"WASTE_Q_RANGE_CODE" VARCHAR2(100), 
	"Q_BASIS_EST_CODE" VARCHAR2(100), 
	"Q_BASIS_EST_NA_IND" CHAR(1), 
	"ONE_TIME_RELEASE_Q" VARCHAR2(100), 
	"ONE_TIME_NA_IND" CHAR(1), 
	"PRODUCTION_RATIO_ME" VARCHAR2(100), 
	"PRODUCTION_RATIO_NA_IND" CHAR(1), 
	"SUB_ADDITIONAL_DATA_ID" VARCHAR2(100), 
	"OPT_INF_TXT" VARCHAR2(4000), 
	"PUB_CONT_EMAIL_ADDRES" VARCHAR2(100), 
	"CHEM_RPT_REV_CD_1" VARCHAR2(100), 
	"CHEM_RPT_REV_CD_2" VARCHAR2(100), 
	"CHEM_RPT_WD_CD_1" VARCHAR2(100), 
	"CHEM_RPT_WD_CD_2" VARCHAR2(100), 
	"TOX_EQ_VAL1_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL2_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL3_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL4_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL5_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL6_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL7_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL8_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL9_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL10_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL11_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL12_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL13_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL14_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL15_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL16_POTW" VARCHAR2(100), 
	"TOX_EQ_VAL17_POTW" VARCHAR2(100), 
	"TOX_EQ_NA_IND_POTW" VARCHAR2(100), 
	"WASTE_Q_CATASTROPHIC_MEASURE" VARCHAR2(100), 
	"WASTE_Q_RANGE_NUM_BASIS_VALUE" VARCHAR2(100), 
	"Q_DISP_LANDFILL_PERCENT_VALUE" VARCHAR2(100), 
	"Q_DISP_OTHER_PERCENT_VALUE" VARCHAR2(100), 
	"Q_TREATED_PERCENT_VALUE" VARCHAR2(100), 
	"TOX_EQ_VAL1_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL2_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL3_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL4_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL5_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL6_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL7_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL8_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL9_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL10_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL11_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL12_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL13_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL14_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL15_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL16_ONETIME" VARCHAR2(100), 
	"TOX_EQ_VAL17_ONETIME" VARCHAR2(100), 
	"TOX_EQ_NA_IND_ONETIME" VARCHAR2(100), 
	"CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_REPORT_VALIDATION
--------------------------------------------------------

  CREATE TABLE "TRI_REPORT_VALIDATION" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"VALIDATION_ENTITY_NAME_TEXT" VARCHAR2(100), 
	"VALIDATION_MESSAGE_CODE" VARCHAR2(100), 
	"VALIDATION_MESSAGE_TEXT" VARCHAR2(100), 
	"EPA_ERROR_SEVERITY_CODE" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_SRC_RED_ACT
--------------------------------------------------------

  CREATE TABLE "TRI_SRC_RED_ACT" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"SRC_RED_SEQ_CL" VARCHAR2(100), 
	"SRC_RED_ACT_CODE" VARCHAR2(100), 
	"SRC_RED_NA_IND" CHAR(1)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_SRC_RED_METH_CD
--------------------------------------------------------

  CREATE TABLE "TRI_SRC_RED_METH_CD" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"SRC_RED_METH_CODE" VARCHAR2(100), 
	"SRC_RED_NA_IND" CHAR(1)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_SUB
--------------------------------------------------------

  CREATE TABLE "TRI_SUB" 
   (	"PK_GUID" VARCHAR2(36), 
	"TRI_SUB_ID" VARCHAR2(255), 
	"INSERTED_DATE" DATE DEFAULT SYSDATE, 
	"TRANSACTION_ID" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_TRANSFER_LOC
--------------------------------------------------------

  CREATE TABLE "TRI_TRANSFER_LOC" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"TRANSFER_LOC_SEQ_CL" VARCHAR2(100), 
	"POTW_IND" VARCHAR2(100), 
	"FAC_SITE" VARCHAR2(100), 
	"LOC_ADD_TXT" VARCHAR2(100), 
	"SUPP_LOC_TXT" VARCHAR2(100), 
	"LOCALITY" VARCHAR2(100), 
	"STATE" VARCHAR2(100), 
	"ADD_POSTAL_CODE" VARCHAR2(100), 
	"COUNTY" VARCHAR2(100), 
	"CONTROLLED_LOC_IND" VARCHAR2(100), 
	"RCRA_ID_CLBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_TRANSFER_Q
--------------------------------------------------------

  CREATE TABLE "TRI_TRANSFER_Q" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"TRANSFER_SEQ_CLBER" VARCHAR2(100), 
	"WASTE_Q_ME" VARCHAR2(100), 
	"WASTE_Q_RANGE_CODE" VARCHAR2(100), 
	"WASTE_Q_NA_IND" CHAR(1), 
	"Q_BASIS_EST_CODE" VARCHAR2(100), 
	"Q_BASIS_EST_NA_IND" CHAR(1), 
	"WASTE_MANAGEMENT_CODE" VARCHAR2(100), 
	"TOX_EQ_VAL1" VARCHAR2(100), 
	"TOX_EQ_VAL2" VARCHAR2(100), 
	"TOX_EQ_VAL3" VARCHAR2(100), 
	"TOX_EQ_VAL4" VARCHAR2(100), 
	"TOX_EQ_VAL5" VARCHAR2(100), 
	"TOX_EQ_VAL6" VARCHAR2(100), 
	"TOX_EQ_VAL7" VARCHAR2(100), 
	"TOX_EQ_VAL8" VARCHAR2(100), 
	"TOX_EQ_VAL9" VARCHAR2(100), 
	"TOX_EQ_VAL10" VARCHAR2(100), 
	"TOX_EQ_VAL11" VARCHAR2(100), 
	"TOX_EQ_VAL12" VARCHAR2(100), 
	"TOX_EQ_VAL13" VARCHAR2(100), 
	"TOX_EQ_VAL14" VARCHAR2(100), 
	"TOX_EQ_VAL15" VARCHAR2(100), 
	"TOX_EQ_VAL16" VARCHAR2(100), 
	"TOX_EQ_VAL17" VARCHAR2(100), 
	"TOX_EQ_NA_IND" VARCHAR2(100), 
	"WASTE_Q_CATASTROPHIC_MEASURE" VARCHAR2(100), 
	"WASTE_Q_RANGE_NUM_BASIS_VALUE" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_UIC_ID
--------------------------------------------------------

  CREATE TABLE "TRI_UIC_ID" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"UIC_ID_CLBER" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_WASTE_TREAT_DTL
--------------------------------------------------------

  CREATE TABLE "TRI_WASTE_TREAT_DTL" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"WASTE_STREAM_SEQ_CLBER" VARCHAR2(100), 
	"WASTE_STREAM_TYPE_CODE" VARCHAR2(100), 
	"INFLUENT_CONC_RANGE_C" VARCHAR2(100), 
	"TREAT_EFF_EST_PCT" VARCHAR2(100), 
	"TREAT_EFF_RANGE_CD" VARCHAR2(100), 
	"TREAT_EFF_NA_IND" CHAR(1), 
	"OPERATING_DATA_IND" VARCHAR2(100), 
	"WASTE_TREAT_NA_IND" CHAR(1)
   ) ;
--------------------------------------------------------
--  DDL for Table TRI_WASTE_TREAT_METH
--------------------------------------------------------

  CREATE TABLE "TRI_WASTE_TREAT_METH" 
   (	"PK_GUID" VARCHAR2(36), 
	"FK_GUID" VARCHAR2(36), 
	"WASTE_TREAT_SEQ_CL" VARCHAR2(100), 
	"WASTE_TREAT_METH_CODE" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  Constraints for Table TRI_CHEM
--------------------------------------------------------

  ALTER TABLE "TRI_CHEM" ADD CONSTRAINT "PK_TRI_CHEM" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_CHEM" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_CHEM" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_FAC
--------------------------------------------------------

  ALTER TABLE "TRI_FAC" ADD CONSTRAINT "PK_TRI_FAC" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_FAC" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_FAC" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_FAC_DUN
--------------------------------------------------------

  ALTER TABLE "TRI_FAC_DUN" ADD CONSTRAINT "PK_TRI_FAC_DUN" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_FAC_DUN" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_FAC_DUN" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_FAC_NAICS
--------------------------------------------------------

  ALTER TABLE "TRI_FAC_NAICS" ADD CONSTRAINT "PK_TRI_FAC_NAICS" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_FAC_NAICS" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_FAC_NAICS" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_FAC_SIC
--------------------------------------------------------

  ALTER TABLE "TRI_FAC_SIC" ADD CONSTRAINT "PK_TRI_FAC_SIC" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_FAC_SIC" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_FAC_SIC" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_NPDES_ID
--------------------------------------------------------

  ALTER TABLE "TRI_NPDES_ID" ADD CONSTRAINT "PK_TRI_NPDES_ID" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_NPDES_ID" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_NPDES_ID" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_OFFSITE_DISP_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_OFFSITE_DISP_QTY" ADD CONSTRAINT "PK_TRI_OFFSITE_DISP_QTY" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_OFFSITE_DISP_QTY" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_OFFSITE_DISP_QTY" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_OFFSITE_ENERGY_REC_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_OFFSITE_ENERGY_REC_QTY" ADD CONSTRAINT "PK_TRI_OFFSITE_ENERGY_REC_QTY" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_OFFSITE_ENERGY_REC_QTY" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_OFFSITE_ENERGY_REC_QTY" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_OFFSITE_RECYCLED_Q
--------------------------------------------------------

  ALTER TABLE "TRI_OFFSITE_RECYCLED_Q" ADD CONSTRAINT "PK_TRI_OFFSITE_RECYCLED_Q" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_OFFSITE_RECYCLED_Q" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_OFFSITE_RECYCLED_Q" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_OFFSITE_TREATED_Q
--------------------------------------------------------

  ALTER TABLE "TRI_OFFSITE_TREATED_Q" ADD CONSTRAINT "PK_TRI_OFFSITE_TREATED_Q" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_OFFSITE_TREATED_Q" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_OFFSITE_TREATED_Q" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_OFFSITE_UIC_DISP_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_OFFSITE_UIC_DISP_QTY" ADD CONSTRAINT "PK_TRI_OFFSITE_UIC_DISP_QTY" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_OFFSITE_UIC_DISP_QTY" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_OFFSITE_UIC_DISP_QTY" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_ONSITE_DISP_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_DISP_QTY" ADD CONSTRAINT "PK_TRI_ONSITE_DISP_QTY" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_ONSITE_DISP_QTY" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_ONSITE_DISP_QTY" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_ONSITE_ENERGY_RCV_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_ENERGY_RCV_QTY" ADD CONSTRAINT "PK_TRI_ONSITE_ENERGY_RCV_QTY" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_ONSITE_ENERGY_RCV_QTY" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_ONSITE_ENERGY_RCV_QTY" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_ONSITE_RCV_PROC
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_RCV_PROC" ADD CONSTRAINT "PK_TRI_ONSITE_RCV_PROC" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_ONSITE_RCV_PROC" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_ONSITE_RCV_PROC" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_ONSITE_RECYCG_PROC
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_RECYCG_PROC" ADD CONSTRAINT "PK_TRI_ONSITE_RECYCG_PROC" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_ONSITE_RECYCG_PROC" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_ONSITE_RECYCG_PROC" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_ONSITE_RECYCLED_Q
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_RECYCLED_Q" ADD CONSTRAINT "PK_TRI_ONSITE_RECYCLED_Q" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_ONSITE_RECYCLED_Q" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_ONSITE_RECYCLED_Q" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_ONSITE_RELEASE_Q
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_RELEASE_Q" ADD CONSTRAINT "PK_TRI_ONSITE_RELEASE_Q" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_ONSITE_RELEASE_Q" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_ONSITE_RELEASE_Q" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_ONSITE_TREATED_Q
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_TREATED_Q" ADD CONSTRAINT "PK_TRI_ONSITE_TREATED_Q" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_ONSITE_TREATED_Q" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_ONSITE_TREATED_Q" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_ONSITE_UIC_DISP_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_UIC_DISP_QTY" ADD CONSTRAINT "PK_TRI_ONSITE_UIC_DISP_QTY" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_ONSITE_UIC_DISP_QTY" MODIFY ("PK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_RCRA_ID
--------------------------------------------------------

  ALTER TABLE "TRI_RCRA_ID" ADD CONSTRAINT "PK_TRI_RCRA_ID" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_RCRA_ID" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_RCRA_ID" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_REPLACED_REPORT_ID
--------------------------------------------------------

  ALTER TABLE "TRI_REPLACED_REPORT_ID" ADD CONSTRAINT "PK_TRI_REPLACED_REPORT_ID" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_REPLACED_REPORT_ID" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_REPLACED_REPORT_ID" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_REPORT
--------------------------------------------------------

  ALTER TABLE "TRI_REPORT" ADD CONSTRAINT "PK_TRI_REPORT" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_REPORT" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_REPORT" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_REPORT_VALIDATION
--------------------------------------------------------

  ALTER TABLE "TRI_REPORT_VALIDATION" ADD CONSTRAINT "PK_TRI_REPORT_VALIDATION" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_REPORT_VALIDATION" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_REPORT_VALIDATION" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_SRC_RED_ACT
--------------------------------------------------------

  ALTER TABLE "TRI_SRC_RED_ACT" ADD CONSTRAINT "PK_TRI_SRC_RED_ACT" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_SRC_RED_ACT" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_SRC_RED_ACT" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_SRC_RED_METH_CD
--------------------------------------------------------

  ALTER TABLE "TRI_SRC_RED_METH_CD" ADD CONSTRAINT "PK_TRI_SRC_RED_METH_CD" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_SRC_RED_METH_CD" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_SRC_RED_METH_CD" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_SUB
--------------------------------------------------------

  ALTER TABLE "TRI_SUB" ADD CONSTRAINT "PK_TRI_SUB" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_SUB" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_SUB" MODIFY ("TRI_SUB_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_SUB" MODIFY ("INSERTED_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_SUB" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_TRANSFER_LOC
--------------------------------------------------------

  ALTER TABLE "TRI_TRANSFER_LOC" ADD CONSTRAINT "PK_TRI_TRANSFER_LOC" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_TRANSFER_LOC" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_TRANSFER_LOC" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_TRANSFER_Q
--------------------------------------------------------

  ALTER TABLE "TRI_TRANSFER_Q" ADD CONSTRAINT "PK_TRI_TRANSFER_Q" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_TRANSFER_Q" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_TRANSFER_Q" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_UIC_ID
--------------------------------------------------------

  ALTER TABLE "TRI_UIC_ID" ADD CONSTRAINT "PK_TRI_UIC_ID" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_UIC_ID" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_UIC_ID" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_WASTE_TREAT_DTL
--------------------------------------------------------

  ALTER TABLE "TRI_WASTE_TREAT_DTL" ADD CONSTRAINT "PK_TRI_WASTE_TREAT_DTL" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_WASTE_TREAT_DTL" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_WASTE_TREAT_DTL" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRI_WASTE_TREAT_METH
--------------------------------------------------------

  ALTER TABLE "TRI_WASTE_TREAT_METH" ADD CONSTRAINT "PK_TRI_WASTE_TREAT_METH" PRIMARY KEY ("PK_GUID") ENABLE;
 
  ALTER TABLE "TRI_WASTE_TREAT_METH" MODIFY ("PK_GUID" NOT NULL ENABLE);
 
  ALTER TABLE "TRI_WASTE_TREAT_METH" MODIFY ("FK_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Index IX_TRI_CHEM
--------------------------------------------------------

  CREATE INDEX "IX_TRI_CHEM" ON "TRI_CHEM" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_FAC
--------------------------------------------------------

  CREATE INDEX "IX_TRI_FAC" ON "TRI_FAC" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_FAC_DUN
--------------------------------------------------------

  CREATE INDEX "IX_TRI_FAC_DUN" ON "TRI_FAC_DUN" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_FAC_NAICS
--------------------------------------------------------

  CREATE INDEX "IX_TRI_FAC_NAICS" ON "TRI_FAC_NAICS" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_FAC_SIC
--------------------------------------------------------

  CREATE INDEX "IX_TRI_FAC_SIC" ON "TRI_FAC_SIC" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_NPDES_ID
--------------------------------------------------------

  CREATE INDEX "IX_TRI_NPDES_ID" ON "TRI_NPDES_ID" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_OFFSITE_DISP_QTY
--------------------------------------------------------

  CREATE INDEX "IX_TRI_OFFSITE_DISP_QTY" ON "TRI_OFFSITE_DISP_QTY" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_OFFSITE_ENERGY_REC_QTY
--------------------------------------------------------

  CREATE INDEX "IX_TRI_OFFSITE_ENERGY_REC_QTY" ON "TRI_OFFSITE_ENERGY_REC_QTY" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_OFFSITE_RECYCLED_Q
--------------------------------------------------------

  CREATE INDEX "IX_TRI_OFFSITE_RECYCLED_Q" ON "TRI_OFFSITE_RECYCLED_Q" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_OFFSITE_TREATED_Q
--------------------------------------------------------

  CREATE INDEX "IX_TRI_OFFSITE_TREATED_Q" ON "TRI_OFFSITE_TREATED_Q" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_OFFSITE_UIC_DISP_QTY
--------------------------------------------------------

  CREATE INDEX "IX_TRI_OFFSITE_UIC_DISP_QTY" ON "TRI_OFFSITE_UIC_DISP_QTY" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_ONSITE_DISP_QTY
--------------------------------------------------------

  CREATE INDEX "IX_TRI_ONSITE_DISP_QTY" ON "TRI_ONSITE_DISP_QTY" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_ONSITE_ENERGY_RCV_QTY
--------------------------------------------------------

  CREATE INDEX "IX_TRI_ONSITE_ENERGY_RCV_QTY" ON "TRI_ONSITE_ENERGY_RCV_QTY" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_ONSITE_RCV_PROC
--------------------------------------------------------

  CREATE INDEX "IX_TRI_ONSITE_RCV_PROC" ON "TRI_ONSITE_RCV_PROC" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_ONSITE_RECYCG_PROC
--------------------------------------------------------

  CREATE INDEX "IX_TRI_ONSITE_RECYCG_PROC" ON "TRI_ONSITE_RECYCG_PROC" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_ONSITE_RECYCLED_Q
--------------------------------------------------------

  CREATE INDEX "IX_TRI_ONSITE_RECYCLED_Q" ON "TRI_ONSITE_RECYCLED_Q" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_ONSITE_RELEASE_Q
--------------------------------------------------------

  CREATE INDEX "IX_TRI_ONSITE_RELEASE_Q" ON "TRI_ONSITE_RELEASE_Q" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_ONSITE_TREATED_Q
--------------------------------------------------------

  CREATE INDEX "IX_TRI_ONSITE_TREATED_Q" ON "TRI_ONSITE_TREATED_Q" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_ONSITE_UIC_DISP_QTY
--------------------------------------------------------

  CREATE INDEX "IX_TRI_ONSITE_UIC_DISP_QTY" ON "TRI_ONSITE_UIC_DISP_QTY" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_RCRA_ID
--------------------------------------------------------

  CREATE INDEX "IX_TRI_RCRA_ID" ON "TRI_RCRA_ID" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_REPLACED_REPORT_ID
--------------------------------------------------------

  CREATE INDEX "IX_TRI_REPLACED_REPORT_ID" ON "TRI_REPLACED_REPORT_ID" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_REPORT
--------------------------------------------------------

  CREATE INDEX "IX_TRI_REPORT" ON "TRI_REPORT" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_REPORT_VALIDATION
--------------------------------------------------------

  CREATE INDEX "IX_TRI_REPORT_VALIDATION" ON "TRI_REPORT_VALIDATION" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_SRC_RED_ACT
--------------------------------------------------------

  CREATE INDEX "IX_TRI_SRC_RED_ACT" ON "TRI_SRC_RED_ACT" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_SRC_RED_METH_CD
--------------------------------------------------------

  CREATE INDEX "IX_TRI_SRC_RED_METH_CD" ON "TRI_SRC_RED_METH_CD" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_TRANSFER_LOC
--------------------------------------------------------

  CREATE INDEX "IX_TRI_TRANSFER_LOC" ON "TRI_TRANSFER_LOC" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_TRANSFER_Q
--------------------------------------------------------

  CREATE INDEX "IX_TRI_TRANSFER_Q" ON "TRI_TRANSFER_Q" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_UIC_ID
--------------------------------------------------------

  CREATE INDEX "IX_TRI_UIC_ID" ON "TRI_UIC_ID" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_WASTE_TREAT_DTL
--------------------------------------------------------

  CREATE INDEX "IX_TRI_WASTE_TREAT_DTL" ON "TRI_WASTE_TREAT_DTL" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index IX_TRI_WASTE_TREAT_METH
--------------------------------------------------------

  CREATE INDEX "IX_TRI_WASTE_TREAT_METH" ON "TRI_WASTE_TREAT_METH" ("FK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_CHEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_CHEM" ON "TRI_CHEM" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_FAC
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_FAC" ON "TRI_FAC" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_FAC_DUN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_FAC_DUN" ON "TRI_FAC_DUN" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_FAC_NAICS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_FAC_NAICS" ON "TRI_FAC_NAICS" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_FAC_SIC
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_FAC_SIC" ON "TRI_FAC_SIC" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_NPDES_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_NPDES_ID" ON "TRI_NPDES_ID" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_OFFSITE_DISP_QTY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_OFFSITE_DISP_QTY" ON "TRI_OFFSITE_DISP_QTY" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_OFFSITE_ENERGY_REC_QTY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_OFFSITE_ENERGY_REC_QTY" ON "TRI_OFFSITE_ENERGY_REC_QTY" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_OFFSITE_RECYCLED_Q
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_OFFSITE_RECYCLED_Q" ON "TRI_OFFSITE_RECYCLED_Q" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_OFFSITE_TREATED_Q
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_OFFSITE_TREATED_Q" ON "TRI_OFFSITE_TREATED_Q" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_OFFSITE_UIC_DISP_QTY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_OFFSITE_UIC_DISP_QTY" ON "TRI_OFFSITE_UIC_DISP_QTY" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_ONSITE_DISP_QTY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_ONSITE_DISP_QTY" ON "TRI_ONSITE_DISP_QTY" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_ONSITE_ENERGY_RCV_QTY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_ONSITE_ENERGY_RCV_QTY" ON "TRI_ONSITE_ENERGY_RCV_QTY" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_ONSITE_RCV_PROC
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_ONSITE_RCV_PROC" ON "TRI_ONSITE_RCV_PROC" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_ONSITE_RECYCG_PROC
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_ONSITE_RECYCG_PROC" ON "TRI_ONSITE_RECYCG_PROC" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_ONSITE_RECYCLED_Q
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_ONSITE_RECYCLED_Q" ON "TRI_ONSITE_RECYCLED_Q" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_ONSITE_RELEASE_Q
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_ONSITE_RELEASE_Q" ON "TRI_ONSITE_RELEASE_Q" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_ONSITE_TREATED_Q
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_ONSITE_TREATED_Q" ON "TRI_ONSITE_TREATED_Q" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_ONSITE_UIC_DISP_QTY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_ONSITE_UIC_DISP_QTY" ON "TRI_ONSITE_UIC_DISP_QTY" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_RCRA_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_RCRA_ID" ON "TRI_RCRA_ID" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_REPLACED_REPORT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_REPLACED_REPORT_ID" ON "TRI_REPLACED_REPORT_ID" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_REPORT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_REPORT" ON "TRI_REPORT" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_REPORT_VALIDATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_REPORT_VALIDATION" ON "TRI_REPORT_VALIDATION" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_SRC_RED_ACT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_SRC_RED_ACT" ON "TRI_SRC_RED_ACT" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_SRC_RED_METH_CD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_SRC_RED_METH_CD" ON "TRI_SRC_RED_METH_CD" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_SUB
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_SUB" ON "TRI_SUB" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_TRANSFER_LOC
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_TRANSFER_LOC" ON "TRI_TRANSFER_LOC" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_TRANSFER_Q
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_TRANSFER_Q" ON "TRI_TRANSFER_Q" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_UIC_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_UIC_ID" ON "TRI_UIC_ID" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_WASTE_TREAT_DTL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_WASTE_TREAT_DTL" ON "TRI_WASTE_TREAT_DTL" ("PK_GUID") 
  ;
--------------------------------------------------------
--  DDL for Index PK_TRI_WASTE_TREAT_METH
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRI_WASTE_TREAT_METH" ON "TRI_WASTE_TREAT_METH" ("PK_GUID") 
  ;
--------------------------------------------------------
--  Ref Constraints for Table TRI_CHEM
--------------------------------------------------------

  ALTER TABLE "TRI_CHEM" ADD CONSTRAINT "fk_chem_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_FAC
--------------------------------------------------------

  ALTER TABLE "TRI_FAC" ADD CONSTRAINT "fk_fac_sub" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_SUB" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_FAC_DUN
--------------------------------------------------------

  ALTER TABLE "TRI_FAC_DUN" ADD CONSTRAINT "fk_facdun_fac" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_FAC" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_FAC_NAICS
--------------------------------------------------------

  ALTER TABLE "TRI_FAC_NAICS" ADD CONSTRAINT "fk_facnaics_fac" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_FAC" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_FAC_SIC
--------------------------------------------------------

  ALTER TABLE "TRI_FAC_SIC" ADD CONSTRAINT "fk_facsic_fac" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_FAC" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_NPDES_ID
--------------------------------------------------------

  ALTER TABLE "TRI_NPDES_ID" ADD CONSTRAINT "fk_npdesid_fac" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_FAC" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_OFFSITE_DISP_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_OFFSITE_DISP_QTY" ADD CONSTRAINT "fk_offsitedispqty_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_OFFSITE_ENERGY_REC_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_OFFSITE_ENERGY_REC_QTY" ADD CONSTRAINT "fk_offsiteenergyrecqty_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_OFFSITE_RECYCLED_Q
--------------------------------------------------------

  ALTER TABLE "TRI_OFFSITE_RECYCLED_Q" ADD CONSTRAINT "fk_offsiterecycledq_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_OFFSITE_TREATED_Q
--------------------------------------------------------

  ALTER TABLE "TRI_OFFSITE_TREATED_Q" ADD CONSTRAINT "fk_offsitetreatedq_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_OFFSITE_UIC_DISP_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_OFFSITE_UIC_DISP_QTY" ADD CONSTRAINT "fk_offsiteuicdispqty_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_ONSITE_DISP_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_DISP_QTY" ADD CONSTRAINT "fk_onsitedispqty_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_ONSITE_ENERGY_RCV_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_ENERGY_RCV_QTY" ADD CONSTRAINT "fk_onsiteenergyrcvqty_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_ONSITE_RCV_PROC
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_RCV_PROC" ADD CONSTRAINT "fk_onsitercvproc_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_ONSITE_RECYCG_PROC
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_RECYCG_PROC" ADD CONSTRAINT "fk_onsiterecycgproc_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_ONSITE_RECYCLED_Q
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_RECYCLED_Q" ADD CONSTRAINT "fk_onsiterecycledq_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_ONSITE_RELEASE_Q
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_RELEASE_Q" ADD CONSTRAINT "fk_onsitereleaseq_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_ONSITE_TREATED_Q
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_TREATED_Q" ADD CONSTRAINT "fk_onsitetreatedq_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_ONSITE_UIC_DISP_QTY
--------------------------------------------------------

  ALTER TABLE "TRI_ONSITE_UIC_DISP_QTY" ADD CONSTRAINT "fk_onsiteuicdispqty_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_RCRA_ID
--------------------------------------------------------

  ALTER TABLE "TRI_RCRA_ID" ADD CONSTRAINT "fk_rcraid_fac" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_FAC" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_REPLACED_REPORT_ID
--------------------------------------------------------

  ALTER TABLE "TRI_REPLACED_REPORT_ID" ADD CONSTRAINT "fk_replacedreportid_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_REPORT
--------------------------------------------------------

  ALTER TABLE "TRI_REPORT" ADD CONSTRAINT "fk_report_sub" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_SUB" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_REPORT_VALIDATION
--------------------------------------------------------

  ALTER TABLE "TRI_REPORT_VALIDATION" ADD CONSTRAINT "fk_tri_report_validation_tri_r" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_SRC_RED_ACT
--------------------------------------------------------

  ALTER TABLE "TRI_SRC_RED_ACT" ADD CONSTRAINT "fk_srcredact_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_SRC_RED_METH_CD
--------------------------------------------------------

  ALTER TABLE "TRI_SRC_RED_METH_CD" ADD CONSTRAINT "fk_srcredmethcd_srcredact" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_SRC_RED_ACT" ("PK_GUID") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table TRI_TRANSFER_LOC
--------------------------------------------------------

  ALTER TABLE "TRI_TRANSFER_LOC" ADD CONSTRAINT "fk_transferloc_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_TRANSFER_Q
--------------------------------------------------------

  ALTER TABLE "TRI_TRANSFER_Q" ADD CONSTRAINT "fk_transferq_transferloc" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_TRANSFER_LOC" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_UIC_ID
--------------------------------------------------------

  ALTER TABLE "TRI_UIC_ID" ADD CONSTRAINT "fk_uicid_fac" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_FAC" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_WASTE_TREAT_DTL
--------------------------------------------------------

  ALTER TABLE "TRI_WASTE_TREAT_DTL" ADD CONSTRAINT "fk_wastetreatdtl_report" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_REPORT" ("PK_GUID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRI_WASTE_TREAT_METH
--------------------------------------------------------

  ALTER TABLE "TRI_WASTE_TREAT_METH" ADD CONSTRAINT "fk_wastetreatmeth_wtdtl" FOREIGN KEY ("FK_GUID")
	  REFERENCES "TRI_WASTE_TREAT_DTL" ("PK_GUID") ON DELETE CASCADE ENABLE;
