/****** Object:  Table [dbo].[TRI_SUB]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_SUB](
	[PK_GUID] [varchar](36) NOT NULL,
	[TRI_SUB_ID] [varchar](255) NOT NULL,
	[INSERTED_DATE] [datetime] NOT NULL,
	[TRANSACTION_ID] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TRI_SUB] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_TRI_SUB] UNIQUE NONCLUSTERED 
(
	[TRI_SUB_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TRI_FAC]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_FAC](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[FAC_ID] [varchar](100) NULL,
	[FAC_SITE] [varchar](100) NULL,
	[LOC_ADD_TXT] [varchar](100) NULL,
	[SUPP_LOC_TXT] [varchar](100) NULL,
	[LOCALITY] [varchar](100) NULL,
	[STATE_CL_ID] [varchar](100) NULL,
	[STATE_CODE] [varchar](10) NULL,
	[STATE] [varchar](50) NULL,
	[ADD_POSTAL_CODE] [varchar](50) NULL,
	[COUNTRY_CL_ID] [varchar](100) NULL,
	[COUNTRY_CODE] [varchar](10) NULL,
	[COUNTRY] [varchar](50) NULL,
	[COUNTY_CL_ID] [varchar](100) NULL,
	[COUNTY_CODE] [varchar](100) NULL,
	[COUNTY] [varchar](100) NULL,
	[TRIBAL_CL_ID] [varchar](100) NULL,
	[TRIBAL_CODE] [varchar](100) NULL,
	[TRIBAL] [varchar](100) NULL,
	[TRIBAL_LAND] [varchar](100) NULL,
	[TRIBAL_LAND_IND] [varchar](100) NULL,
	[LOC_DESCN_TXT] [varchar](100) NULL,
	[MAIL_FAC_SITE] [varchar](100) NULL,
	[MAIL_ADD_TXT] [varchar](100) NULL,
	[SUPP_MAIL_ADD] [varchar](100) NULL,
	[MAIL_ADD_CITY] [varchar](100) NULL,
	[MAIL_ADD_POSTAL_CODE] [varchar](100) NULL,
	[PROVINCE_TXT] [varchar](100) NULL,
	[MAIL_ADD_STATE_CDLST] [varchar](100) NULL,
	[MAIL_ADD_STATE_CODE] [varchar](10) NULL,
	[MAIL_ADD_STATE] [varchar](100) NULL,
	[MAIL_ADD_COUNTRY_CDLST] [varchar](100) NULL,
	[MAIL_ADD_COUNTRY_CODE] [varchar](10) NULL,
	[MAIL_ADD_COUNTRY] [varchar](100) NULL,
	[LAT_ME] [varchar](20) NULL,
	[LON_ME] [varchar](20) NULL,
	[SRC_MAP_SCALE_CLBER] [varchar](100) NULL,
	[HOR_ME_VALUE] [varchar](100) NULL,
	[HOR_ME_UNIT_CODE] [varchar](100) NULL,
	[HOR_ME_UNIT] [varchar](100) NULL,
	[HOR_ME_PREC_TXT] [varchar](100) NULL,
	[HOR_RESULT_QFR_CODE] [varchar](100) NULL,
	[HOR_RESULT_QFR] [varchar](100) NULL,
	[HOR_METH_ID_CODE] [varchar](100) NULL,
	[HOR_METH] [varchar](100) NULL,
	[HOR_METH_DESCN_TXT] [varchar](100) NULL,
	[HOR_METH_DEV_TXT] [varchar](100) NULL,
	[GEO_REF_POINT_CD] [varchar](100) NULL,
	[GEO_REF_POINT_NM] [varchar](100) NULL,
	[HOR_REF_DATUM_CD] [varchar](100) NULL,
	[HOR_REF_DATUM_NM] [varchar](100) NULL,
	[DATA_COLLECTION_DATE] [varchar](100) NULL,
	[LOC_COMS_TXT] [varchar](100) NULL,
	[VER_ME_VALUE] [varchar](100) NULL,
	[VER_ME_UNIT_CODE] [varchar](100) NULL,
	[VER_ME_UNIT] [varchar](100) NULL,
	[VER_ME_PREC_TXT] [varchar](100) NULL,
	[VER_RESULT_QFR_CODE] [varchar](100) NULL,
	[VER_RESULT_QFR] [varchar](100) NULL,
	[VER_METH_ID_CODE] [varchar](100) NULL,
	[VER_METH] [varchar](100) NULL,
	[VER_METH_DESCN_TXT] [varchar](100) NULL,
	[VER_METH_DEV_TXT] [varchar](100) NULL,
	[GEO_REF_DATUM_CD] [varchar](100) NULL,
	[GEO_REF_DATUM_NM] [varchar](100) NULL,
	[VERIF_METH_ID] [varchar](100) NULL,
	[VERIF_METH] [varchar](100) NULL,
	[VERIF_METH_DESC] [varchar](100) NULL,
	[VERIF_METH_DEV] [varchar](100) NULL,
	[COORD_DATA_SRC_CODE] [varchar](100) NULL,
	[COORD_DATA_SRC] [varchar](100) NULL,
	[GEOMETRIC_TYPE_CODE] [varchar](100) NULL,
	[GEOMETRIC_TYPE] [varchar](100) NULL,
	[LAT_DEGREE_ME] [varchar](100) NULL,
	[LAT_MINUTE_ME] [varchar](100) NULL,
	[LAT_SECOND_ME] [varchar](100) NULL,
	[LON_DEGREE_ME] [varchar](100) NULL,
	[LON_MINUTE_ME] [varchar](100) NULL,
	[LON_SECOND_ME] [varchar](100) NULL,
	[PARENT_COMPANY_TXT] [varchar](100) NULL,
	[PARENT_DUN_CODE] [varchar](100) NULL,
	[FACILITY_ACCESS_CODE] [varchar](100) NULL,
	[PRI_YR_TECH_CONTACT_NAME] [varchar](100) NULL,
	[PRI_YR_TECH_CONTACT_PHONE] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_FAC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_FAC_FAC_ID] ON [dbo].[TRI_FAC] 
(
	[FAC_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_TRI_FAC_FK_GUID] ON [dbo].[TRI_FAC] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_REPORT](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[REPORT_ID] [varchar](100) NULL,
	[REPORT_POST_DATE] [varchar](50) NULL,
	[REPORT_REC_DATE] [varchar](50) NULL,
	[REPORT_ORIG_POST_DATE] [varchar](50) NULL,
	[REPORT_ORIG_REC_DATE] [varchar](50) NULL,
	[REPORT_SUB_METH_CODE] [varchar](100) NULL,
	[REPORT_EPA_PASSED_VALID_IND] [char](1) NULL,
	[REPORT_EPA_PROCESSING_STATUS_C] [varchar](100) NULL,
	[UNALTERED_REPORT_IND] [varchar](100) NULL,
	[REPORT_TYPE_CODE] [varchar](100) NULL,
	[SUB_REP_YEAR] [varchar](100) NULL,
	[REPORT_DUE_DATE] [varchar](50) NULL,
	[REVISION_IND] [varchar](100) NULL,
	[CHEM_TRADE_SECRET_IND] [varchar](100) NULL,
	[SUB_SANITIZED_IND] [varchar](100) NULL,
	[CERTIFIER] [varchar](100) NULL,
	[CERTIFIER_TIT_TXT] [varchar](100) NULL,
	[CERT_SIGNED_DATE] [varchar](100) NULL,
	[SUB_ENTIRE_FAC_IND] [varchar](100) NULL,
	[SUB_PARTIAL_FAC_ID] [varchar](100) NULL,
	[SUB_FEDERAL_FAC_ID] [varchar](100) NULL,
	[SUB_CO_FAC_INDIC] [varchar](100) NULL,
	[TECH_CONT] [varchar](100) NULL,
	[TECH_CONT_PHONE_TXT] [varchar](100) NULL,
	[TECH_CONT_EMAIL_ADDRES] [varchar](100) NULL,
	[PUB_CONT_ID] [varchar](100) NULL,
	[PUB_CONT_TIT_TXT] [varchar](100) NULL,
	[PUB_CONT] [varchar](100) NULL,
	[PUB_CONT_PHONE_TXT] [varchar](50) NULL,
	[CHEM_ANC_USAGE_IND] [varchar](100) NULL,
	[CHEM_ARTICLE_COMP_ID] [varchar](100) NULL,
	[CHEM_BYPRODUCT_IND] [varchar](100) NULL,
	[CHEM_FORMULATION_COMP] [varchar](100) NULL,
	[CHEM_IMPORTED_IND] [varchar](100) NULL,
	[CHEM_MANUFACTURE_AID_ID] [varchar](100) NULL,
	[CHEM_MANUFACTURE_IMPURITY] [varchar](100) NULL,
	[CHEM_PROC_IMPURITY_ID] [varchar](100) NULL,
	[CHEM_PROCING_AID_ID] [varchar](100) NULL,
	[CHEM_PRODUCED_IND] [varchar](100) NULL,
	[CHEM_REACTANT_IND] [varchar](100) NULL,
	[CHEM_REP_IND] [varchar](100) NULL,
	[CHEM_SALES_DIST_ID] [varchar](100) NULL,
	[CHEM_USED_PROCED_ID] [varchar](100) NULL,
	[MAX_CHEM_AMOUNT_CODE] [varchar](100) NULL,
	[WASTE_Q_ME] [varchar](100) NULL,
	[WASTE_Q_ME_NA_IND] [char](1) NULL,
	[WASTE_Q_RANGE_CODE] [varchar](100) NULL,
	[Q_BASIS_EST_CODE] [varchar](100) NULL,
	[Q_BASIS_EST_NA_IND] [char](1) NULL,
	[ONE_TIME_RELEASE_Q] [varchar](100) NULL,
	[ONE_TIME_NA_IND] [char](1) NULL,
	[PRODUCTION_RATIO_ME] [varchar](100) NULL,
	[PRODUCTION_RATIO_NA_IND] [char](1) NULL,
	[SUB_ADDITIONAL_DATA_ID] [varchar](100) NULL,
	[OPT_INF_TXT] [varchar](4000) NULL,
	[PUB_CONT_EMAIL_ADDRES] [varchar](100) NULL,
	[CHEM_RPT_REV_CD_1] [varchar](100) NULL,
	[CHEM_RPT_REV_CD_2] [varchar](100) NULL,
	[CHEM_RPT_WD_CD_1] [varchar](100) NULL,
	[CHEM_RPT_WD_CD_2] [varchar](100) NULL,
	[TOX_EQ_VAL1_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL2_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL3_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL4_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL5_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL6_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL7_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL8_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL9_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL10_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL11_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL12_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL13_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL14_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL15_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL16_POTW] [varchar](100) NULL,
	[TOX_EQ_VAL17_POTW] [varchar](100) NULL,
	[TOX_EQ_NA_IND_POTW] [char](1) NULL,
	[WASTE_Q_CATASTROPHIC_MEASURE] [varchar](100) NULL,
	[WASTE_Q_RANGE_NUM_BASIS_VALUE] [varchar](100) NULL,
	[Q_DISP_LANDFILL_PERCENT_VALUE] [varchar](100) NULL,
	[Q_DISP_OTHER_PERCENT_VALUE] [varchar](100) NULL,
	[Q_TREATED_PERCENT_VALUE] [varchar](100) NULL,
	[TOX_EQ_VAL1_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL2_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL3_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL4_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL5_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL6_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL7_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL8_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL9_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL10_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL11_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL12_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL13_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL14_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL15_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL16_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL17_ONETIME] [varchar](100) NULL,
	[TOX_EQ_NA_IND_ONETIME] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_REPORT] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_REPORT_FK_GUID] ON [dbo].[TRI_REPORT] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_FAC_DUN]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_FAC_DUN](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[FAC_DUN_CODE] [varchar](9) NULL,
 CONSTRAINT [PK_TRI_FAC_DUN] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_FAC_DUN_FK_GUID] ON [dbo].[TRI_FAC_DUN] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_FAC_SIC]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_FAC_SIC](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[FAC_SIC] [varchar](100) NULL,
	[SIC_PRIMARY_IND] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_FAC_SIC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_FAC_SIC_FK_GUID] ON [dbo].[TRI_FAC_SIC] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_RCRA_ID]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_RCRA_ID](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[RCRA_ID_CLBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_RCRA_ID] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_RCRA_ID_FK_GUID] ON [dbo].[TRI_RCRA_ID] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_UIC_ID]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_UIC_ID](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[UIC_ID_CLBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_UIC_ID] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_UIC_ID_FK_GUID] ON [dbo].[TRI_UIC_ID] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_FAC_NAICS]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_FAC_NAICS](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[FAC_NAICS] [varchar](100) NULL,
	[NAICS_PRIMARY_IND] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_NAICS_SIC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_FAC_NAICS_FK_GUID] ON [dbo].[TRI_FAC_NAICS] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_NPDES_ID]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_NPDES_ID](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[NPDES_ID_CLBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_NPDES_ID] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_NPDES_ID_FK_GUID] ON [dbo].[TRI_NPDES_ID] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_OFFSITE_ENERGY_REC_QTY]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_OFFSITE_ENERGY_REC_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_OFFSITE_ENERGY_REC_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_OFFSITE_ENERGY_REC_QTY_FK_GUID] ON [dbo].[TRI_OFFSITE_ENERGY_REC_QTY] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_ONSITE_RECYCLED_Q]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_RECYCLED_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_RECYCLED_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_ONSITE_RECYCLED_Q_FK_GUID] ON [dbo].[TRI_ONSITE_RECYCLED_Q] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_CHEM]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_CHEM](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[CAS_CLBER] [varchar](100) NULL,
	[CHEM_TXT] [varchar](100) NULL,
	[CHEM_MIXTURE_TXT] [varchar](100) NULL,
	[CHEM_ID] [varchar](100) NULL,
	[CHEM_REGISTRY] [varchar](100) NULL,
	[CHEM_REGISTRY_CTX] [varchar](100) NULL,
	[DIOXIN_DIST1] [varchar](100) NULL,
	[DIOXIN_DIST2] [varchar](100) NULL,
	[DIOXIN_DIST3] [varchar](100) NULL,
	[DIOXIN_DIST4] [varchar](100) NULL,
	[DIOXIN_DIST5] [varchar](100) NULL,
	[DIOXIN_DIST6] [varchar](100) NULL,
	[DIOXIN_DIST7] [varchar](100) NULL,
	[DIOXIN_DIST8] [varchar](100) NULL,
	[DIOXIN_DIST9] [varchar](100) NULL,
	[DIOXIN_DIST10] [varchar](100) NULL,
	[DIOXIN_DIST11] [varchar](100) NULL,
	[DIOXIN_DIST12] [varchar](100) NULL,
	[DIOXIN_DIST13] [varchar](100) NULL,
	[DIOXIN_DIST14] [varchar](100) NULL,
	[DIOXIN_DIST15] [varchar](100) NULL,
	[DIOXIN_DIST16] [varchar](100) NULL,
	[DIOXIN_DIST17] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_CHEM] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_CHEM_FK_GUID] ON [dbo].[TRI_CHEM] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_OFFSITE_DISP_QTY]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_OFFSITE_DISP_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_OFFSITE_DISP_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_OFFSITE_DISP_QTY_FK_GUID] ON [dbo].[TRI_OFFSITE_DISP_QTY] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_TRANSFER_LOC]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_TRANSFER_LOC](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[TRANSFER_LOC_SEQ_CL] [varchar](100) NULL,
	[POTW_IND] [varchar](100) NULL,
	[FAC_SITE] [varchar](100) NULL,
	[LOC_ADD_TXT] [varchar](100) NULL,
	[SUPP_LOC_TXT] [varchar](100) NULL,
	[LOCALITY] [varchar](100) NULL,
	[STATE] [varchar](100) NULL,
	[ADD_POSTAL_CODE] [varchar](100) NULL,
	[COUNTY] [varchar](100) NULL,
	[CONTROLLED_LOC_IND] [varchar](100) NULL,
	[RCRA_ID_CLBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_TRANSFER_LOC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_TRANSFER_LOC_FK_GUID] ON [dbo].[TRI_TRANSFER_LOC] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_REPLACED_REPORT_ID]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_REPLACED_REPORT_ID](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[REPLACED_REPORT_ID] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_REPLACED_REPORT_ID] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_REPLACED_REPORT_ID_FK_GUID] ON [dbo].[TRI_REPLACED_REPORT_ID] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_ONSITE_ENERGY_RCV_QTY]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_ENERGY_RCV_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_ENERGY_RCV_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_ONSITE_ENERGY_RCV_QTY_FK_GUID] ON [dbo].[TRI_ONSITE_ENERGY_RCV_QTY] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_ONSITE_RCV_PROC]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_RCV_PROC](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[ENERGY_RCV_METH_CODE] [varchar](100) NULL,
	[ENERGY_RCV_NA_IND] [char](1) NULL,
 CONSTRAINT [PK_TRI_ONSITE_RCV_PROC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_ONSITE_RCV_PROC_FK_GUID] ON [dbo].[TRI_ONSITE_RCV_PROC] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_REPORT_VALIDATION]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_REPORT_VALIDATION](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[VALIDATION_ENTITY_NAME_TEXT] [varchar](100) NULL,
	[VALIDATION_MESSAGE_CODE] [varchar](100) NULL,
	[VALIDATION_MESSAGE_TEXT] [varchar](100) NULL,
	[EPA_ERROR_SEVERITY_CODE] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_REPORT_VALIDATION] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_REPORT_VALIDATION_FK_GUID] ON [dbo].[TRI_REPORT_VALIDATION] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_ONSITE_TREATED_Q]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_TREATED_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_TREATED_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_ONSITE_TREATED_Q_FK_GUID] ON [dbo].[TRI_ONSITE_TREATED_Q] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_ONSITE_UIC_DISP_QTY]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_UIC_DISP_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_UIC_DISP_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_ONSITE_UIC_DISP_QTY_FK_GUID] ON [dbo].[TRI_ONSITE_UIC_DISP_QTY] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_SRC_RED_ACT]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_SRC_RED_ACT](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[SRC_RED_SEQ_CL] [varchar](100) NULL,
	[SRC_RED_ACT_CODE] [varchar](100) NULL,
	[SRC_RED_NA_IND] [char](1) NULL,
 CONSTRAINT [PK_TRI_SRC_RED_ACT] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_SRC_RED_ACT_FK_GUID] ON [dbo].[TRI_SRC_RED_ACT] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_OFFSITE_UIC_DISP_QTY]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_OFFSITE_UIC_DISP_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_OFFSITE_UIC_DISP_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_OFFSITE_UIC_DISP_QTY_FK_GUID] ON [dbo].[TRI_OFFSITE_UIC_DISP_QTY] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_OFFSITE_TREATED_Q]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_OFFSITE_TREATED_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_OFFSITE_TREATED_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_OFFSITE_TREATED_Q_FK_GUID] ON [dbo].[TRI_OFFSITE_TREATED_Q] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_ONSITE_DISP_QTY]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_DISP_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_DISP_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_ONSITE_DISP_QTY_FK_GUID] ON [dbo].[TRI_ONSITE_DISP_QTY] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_WASTE_TREAT_DTL]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_WASTE_TREAT_DTL](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[WASTE_STREAM_SEQ_CLBER] [varchar](100) NULL,
	[WASTE_STREAM_TYPE_CODE] [varchar](100) NULL,
	[INFLUENT_CONC_RANGE_C] [varchar](100) NULL,
	[TREAT_EFF_EST_PCT] [varchar](100) NULL,
	[TREAT_EFF_RANGE_CD] [varchar](100) NULL,
	[TREAT_EFF_NA_IND] [char](1) NULL,
	[OPERATING_DATA_IND] [varchar](100) NULL,
	[WASTE_TREAT_NA_IND] [char](1) NULL,
 CONSTRAINT [PK_TRI_WASTE_TREAT_DTL] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_WASTE_TREAT_DTL_FK_GUID] ON [dbo].[TRI_WASTE_TREAT_DTL] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_OFFSITE_RECYCLED_Q]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_OFFSITE_RECYCLED_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_OFFSITE_RECYCLED_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_OFFSITE_RECYCLED_Q_FK_GUID] ON [dbo].[TRI_OFFSITE_RECYCLED_Q] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_ONSITE_RECYCG_PROC]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_RECYCG_PROC](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[ONSITE_RECYCG_METH_CODE] [varchar](100) NULL,
	[ONSITE_RECYCG_NA_IND] [char](1) NULL,
 CONSTRAINT [PK_TRI_ONSITE_RECYCG_PROC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_ONSITE_RECYCG_PROC_FK_GUID] ON [dbo].[TRI_ONSITE_RECYCG_PROC] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_ONSITE_RELEASE_Q]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_RELEASE_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[EI_MEDIUM_CODE] [varchar](100) NULL,
	[WASTE_Q_ME] [varchar](100) NULL,
	[WASTE_Q_NA_IND] [char](1) NULL,
	[WASTE_Q_RANGE_CODE] [varchar](100) NULL,
	[Q_BASIS_EST_CD] [varchar](100) NULL,
	[Q_BASIS_NA_IND] [char](1) NULL,
	[WATER_SEQ_CLBER] [varchar](100) NULL,
	[STREAM] [varchar](100) NULL,
	[RELEASE_STORM_WATER] [varchar](100) NULL,
	[RELEASE_STORM_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[WASTE_Q_CATASTROPHIC_MEASURE] [varchar](100) NULL,
	[WASTE_Q_RANGE_NUM_BASIS_VALUE] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_RELEASE_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_ONSITE_RELEASE_Q_FK_GUID] ON [dbo].[TRI_ONSITE_RELEASE_Q] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_TRANSFER_Q]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_TRANSFER_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[TRANSFER_SEQ_CLBER] [varchar](100) NULL,
	[WASTE_Q_ME] [varchar](100) NULL,
	[WASTE_Q_RANGE_CODE] [varchar](100) NULL,
	[WASTE_Q_NA_IND] [char](1) NULL,
	[Q_BASIS_EST_CODE] [varchar](100) NULL,
	[Q_BASIS_EST_NA_IND] [char](1) NULL,
	[WASTE_MANAGEMENT_CODE] [varchar](100) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[WASTE_Q_CATASTROPHIC_MEASURE] [varchar](100) NULL,
	[WASTE_Q_RANGE_NUM_BASIS_VALUE] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_TRANSFER_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_TRANSFER_Q_FK_GUID] ON [dbo].[TRI_TRANSFER_Q] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_SRC_RED_METH_CD]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_SRC_RED_METH_CD](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[SRC_RED_METH_CODE] [varchar](100) NULL,
	[SRC_RED_NA_IND] [char](1) NULL,
 CONSTRAINT [PK_TRI_SRC_RED_METH_CD] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_SRC_RED_METH_CD_FK_GUID] ON [dbo].[TRI_SRC_RED_METH_CD] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRI_WASTE_TREAT_METH]    Script Date: 11/10/2009 16:10:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRI_WASTE_TREAT_METH](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[WASTE_TREAT_SEQ_CL] [varchar](100) NULL,
	[WASTE_TREAT_METH_CODE] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_WASTE_TREAT_METH] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_TRI_WASTE_TREAT_METH_FK_GUID] ON [dbo].[TRI_WASTE_TREAT_METH] 
(
	[FK_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Default [DF__TRI_SUB__INSERTE__09DE7BCC]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_SUB] ADD  DEFAULT (getdate()) FOR [INSERTED_DATE]
GO
/****** Object:  ForeignKey [FK_CHEM_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_CHEM]  WITH NOCHECK ADD  CONSTRAINT [FK_CHEM_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_CHEM] CHECK CONSTRAINT [FK_CHEM_REPORT]
GO
/****** Object:  ForeignKey [FK_FAC_SUB]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_FAC]  WITH CHECK ADD  CONSTRAINT [FK_FAC_SUB] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_SUB] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_FAC] CHECK CONSTRAINT [FK_FAC_SUB]
GO
/****** Object:  ForeignKey [FK_FACDUN_FAC]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_FAC_DUN]  WITH CHECK ADD  CONSTRAINT [FK_FACDUN_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_FAC_DUN] CHECK CONSTRAINT [FK_FACDUN_FAC]
GO
/****** Object:  ForeignKey [FK_FACNAICS_FAC]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_FAC_NAICS]  WITH CHECK ADD  CONSTRAINT [FK_FACNAICS_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_FAC_NAICS] CHECK CONSTRAINT [FK_FACNAICS_FAC]
GO
/****** Object:  ForeignKey [FK_FACSIC_FAC]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_FAC_SIC]  WITH CHECK ADD  CONSTRAINT [FK_FACSIC_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_FAC_SIC] CHECK CONSTRAINT [FK_FACSIC_FAC]
GO
/****** Object:  ForeignKey [FK_NPDESID_FAC]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_NPDES_ID]  WITH CHECK ADD  CONSTRAINT [FK_NPDESID_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_NPDES_ID] CHECK CONSTRAINT [FK_NPDESID_FAC]
GO
/****** Object:  ForeignKey [FK_OFFSITEDISPQTY_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_OFFSITE_DISP_QTY]  WITH NOCHECK ADD  CONSTRAINT [FK_OFFSITEDISPQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_OFFSITE_DISP_QTY] CHECK CONSTRAINT [FK_OFFSITEDISPQTY_REPORT]
GO
/****** Object:  ForeignKey [FK_OFFSITEENERGYRECQTY_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_OFFSITE_ENERGY_REC_QTY]  WITH NOCHECK ADD  CONSTRAINT [FK_OFFSITEENERGYRECQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_OFFSITE_ENERGY_REC_QTY] CHECK CONSTRAINT [FK_OFFSITEENERGYRECQTY_REPORT]
GO
/****** Object:  ForeignKey [FK_OFFSITERECYCLEDQ_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_OFFSITE_RECYCLED_Q]  WITH NOCHECK ADD  CONSTRAINT [FK_OFFSITERECYCLEDQ_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_OFFSITE_RECYCLED_Q] CHECK CONSTRAINT [FK_OFFSITERECYCLEDQ_REPORT]
GO
/****** Object:  ForeignKey [FK_OFFSITETREATEDQ_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_OFFSITE_TREATED_Q]  WITH NOCHECK ADD  CONSTRAINT [FK_OFFSITETREATEDQ_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_OFFSITE_TREATED_Q] CHECK CONSTRAINT [FK_OFFSITETREATEDQ_REPORT]
GO
/****** Object:  ForeignKey [FK_OFFSITEUICDISPQTY_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_OFFSITE_UIC_DISP_QTY]  WITH NOCHECK ADD  CONSTRAINT [FK_OFFSITEUICDISPQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_OFFSITE_UIC_DISP_QTY] CHECK CONSTRAINT [FK_OFFSITEUICDISPQTY_REPORT]
GO
/****** Object:  ForeignKey [FK_ONSITEDISPQTY_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_ONSITE_DISP_QTY]  WITH NOCHECK ADD  CONSTRAINT [FK_ONSITEDISPQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_DISP_QTY] CHECK CONSTRAINT [FK_ONSITEDISPQTY_REPORT]
GO
/****** Object:  ForeignKey [FK_ONSITEENERGYRCVQTY_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_ONSITE_ENERGY_RCV_QTY]  WITH NOCHECK ADD  CONSTRAINT [FK_ONSITEENERGYRCVQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_ENERGY_RCV_QTY] CHECK CONSTRAINT [FK_ONSITEENERGYRCVQTY_REPORT]
GO
/****** Object:  ForeignKey [FK_ONSITERCVPROC_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_ONSITE_RCV_PROC]  WITH NOCHECK ADD  CONSTRAINT [FK_ONSITERCVPROC_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_RCV_PROC] CHECK CONSTRAINT [FK_ONSITERCVPROC_REPORT]
GO
/****** Object:  ForeignKey [FK_ONSITERECYCGPROC_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_ONSITE_RECYCG_PROC]  WITH NOCHECK ADD  CONSTRAINT [FK_ONSITERECYCGPROC_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_RECYCG_PROC] CHECK CONSTRAINT [FK_ONSITERECYCGPROC_REPORT]
GO
/****** Object:  ForeignKey [FK_ONSITERECYCLEDQ_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_ONSITE_RECYCLED_Q]  WITH NOCHECK ADD  CONSTRAINT [FK_ONSITERECYCLEDQ_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_RECYCLED_Q] CHECK CONSTRAINT [FK_ONSITERECYCLEDQ_REPORT]
GO
/****** Object:  ForeignKey [FK_ONSITERELEASEQ_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_ONSITE_RELEASE_Q]  WITH NOCHECK ADD  CONSTRAINT [FK_ONSITERELEASEQ_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_RELEASE_Q] CHECK CONSTRAINT [FK_ONSITERELEASEQ_REPORT]
GO
/****** Object:  ForeignKey [FK_ONSITETREATEDQ_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_ONSITE_TREATED_Q]  WITH NOCHECK ADD  CONSTRAINT [FK_ONSITETREATEDQ_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_TREATED_Q] CHECK CONSTRAINT [FK_ONSITETREATEDQ_REPORT]
GO
/****** Object:  ForeignKey [FK_ONSITEUICDISPQTY_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_ONSITE_UIC_DISP_QTY]  WITH NOCHECK ADD  CONSTRAINT [FK_ONSITEUICDISPQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_UIC_DISP_QTY] CHECK CONSTRAINT [FK_ONSITEUICDISPQTY_REPORT]
GO
/****** Object:  ForeignKey [FK_RCRAID_FAC]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_RCRA_ID]  WITH CHECK ADD  CONSTRAINT [FK_RCRAID_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_RCRA_ID] CHECK CONSTRAINT [FK_RCRAID_FAC]
GO
/****** Object:  ForeignKey [FK_REPLACEDREPORTID_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_REPLACED_REPORT_ID]  WITH NOCHECK ADD  CONSTRAINT [FK_REPLACEDREPORTID_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_REPLACED_REPORT_ID] CHECK CONSTRAINT [FK_REPLACEDREPORTID_REPORT]
GO
/****** Object:  ForeignKey [FK_REPORT_SUB]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_REPORT]  WITH NOCHECK ADD  CONSTRAINT [FK_REPORT_SUB] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_SUB] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_REPORT] CHECK CONSTRAINT [FK_REPORT_SUB]
GO
/****** Object:  ForeignKey [FK_TRI_REPORT_VALIDATION_TRI_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_REPORT_VALIDATION]  WITH NOCHECK ADD  CONSTRAINT [FK_TRI_REPORT_VALIDATION_TRI_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_REPORT_VALIDATION] CHECK CONSTRAINT [FK_TRI_REPORT_VALIDATION_TRI_REPORT]
GO
/****** Object:  ForeignKey [FK_SRCREDACT_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_SRC_RED_ACT]  WITH NOCHECK ADD  CONSTRAINT [FK_SRCREDACT_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_SRC_RED_ACT] CHECK CONSTRAINT [FK_SRCREDACT_REPORT]
GO
/****** Object:  ForeignKey [FK_SRCREDMETHCD_SRCREDACT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_SRC_RED_METH_CD]  WITH CHECK ADD  CONSTRAINT [FK_SRCREDMETHCD_SRCREDACT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_SRC_RED_ACT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_SRC_RED_METH_CD] CHECK CONSTRAINT [FK_SRCREDMETHCD_SRCREDACT]
GO
/****** Object:  ForeignKey [FK_TRANSFERLOC_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_TRANSFER_LOC]  WITH NOCHECK ADD  CONSTRAINT [FK_TRANSFERLOC_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_TRANSFER_LOC] CHECK CONSTRAINT [FK_TRANSFERLOC_REPORT]
GO
/****** Object:  ForeignKey [FK_TRANSFERQ_TRANSFERLOC]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_TRANSFER_Q]  WITH NOCHECK ADD  CONSTRAINT [FK_TRANSFERQ_TRANSFERLOC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_TRANSFER_LOC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_TRANSFER_Q] CHECK CONSTRAINT [FK_TRANSFERQ_TRANSFERLOC]
GO
/****** Object:  ForeignKey [FK_UICID_FAC]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_UIC_ID]  WITH CHECK ADD  CONSTRAINT [FK_UICID_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_UIC_ID] CHECK CONSTRAINT [FK_UICID_FAC]
GO
/****** Object:  ForeignKey [FK_WASTETREATDTL_REPORT]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_WASTE_TREAT_DTL]  WITH NOCHECK ADD  CONSTRAINT [FK_WASTETREATDTL_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_WASTE_TREAT_DTL] CHECK CONSTRAINT [FK_WASTETREATDTL_REPORT]
GO
/****** Object:  ForeignKey [FK_WASTETREATMETH_WTDTL]    Script Date: 11/10/2009 16:10:52 ******/
ALTER TABLE [dbo].[TRI_WASTE_TREAT_METH]  WITH NOCHECK ADD  CONSTRAINT [FK_WASTETREATMETH_WTDTL] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_WASTE_TREAT_DTL] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_WASTE_TREAT_METH] CHECK CONSTRAINT [FK_WASTETREATMETH_WTDTL]
GO
