/*************************************************************************************************
** ObjectName: TRI_6.2-SQL-DLL.sql
**
** Author: Windsor Solutions, Inc.
**
** Company Name: Windsor Solutions, Inc.
**
** Description:  This script will build the TRI database objects to support the OpenNode2 TRI
**               plug-in.  Run the script from the top if running for the first time, if running
**               in an existing environment you'll need to run the drop statements first, then 
**               run the create statements.  Please note, dropping then recreating the schema 
**               objects will purge all data.
**
** Revision History:
** ------------------------------------------------------------------------------------------------
** Date          Name        Description
** ------------------------------------------------------------------------------------------------
** 05/29/2024    Windsor     Created 
**
***************************************************************************************************/

/*
ALTER TABLE [dbo].[TRI_WASTE_TREAT_METH] DROP CONSTRAINT [FK_WASTETREATMETH_WTDTL]
GO
ALTER TABLE [dbo].[TRI_WASTE_TREAT_DTL] DROP CONSTRAINT [FK_WASTETREATDTL_REPORT]
GO
ALTER TABLE [dbo].[TRI_UIC_ID] DROP CONSTRAINT [FK_UICID_FAC]
GO
ALTER TABLE [dbo].[TRI_TRANSFER_Q] DROP CONSTRAINT [FK_TRANSFERQ_TRANSFERLOC]
GO
ALTER TABLE [dbo].[TRI_TRANSFER_LOC] DROP CONSTRAINT [FK_TRANSFERLOC_REPORT]
GO
ALTER TABLE [dbo].[TRI_SRC_RED_METH_CD] DROP CONSTRAINT [FK_SRCREDMETHCD_SRCREDACT]
GO
ALTER TABLE [dbo].[TRI_SRC_RED_ACT] DROP CONSTRAINT [FK_SRCREDACT_REPORT]
GO
ALTER TABLE [dbo].[TRI_REPORT_VALIDATION] DROP CONSTRAINT [FK_TRI_REPORT_VALIDATION_TRI_REPORT]
GO
ALTER TABLE [dbo].[TRI_REPORT] DROP CONSTRAINT [FK_REPORT_SUB]
GO
ALTER TABLE [dbo].[TRI_REPLACED_REPORT_ID] DROP CONSTRAINT [FK_REPLACEDREPORTID_REPORT]
GO
ALTER TABLE [dbo].[TRI_RCRA_ID] DROP CONSTRAINT [FK_RCRAID_FAC]
GO
ALTER TABLE [dbo].[TRI_POTW_WASTE_QUANTITY] DROP CONSTRAINT [FK_TRI_RPT_POTW_WQ]
GO
ALTER TABLE [dbo].[TRI_ONSITE_UIC_DISP_QTY] DROP CONSTRAINT [FK_ONSITEUICDISPQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_TREATED_Q] DROP CONSTRAINT [FK_ONSITETREATEDQ_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_RELEASE_Q] DROP CONSTRAINT [FK_ONSITERELEASEQ_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_RECYCLED_Q] DROP CONSTRAINT [FK_ONSITERECYCLEDQ_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_RECYCG_PROC] DROP CONSTRAINT [FK_ONSITERECYCGPROC_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_RCV_PROC] DROP CONSTRAINT [FK_ONSITERCVPROC_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_ENERGY_RCV_QTY] DROP CONSTRAINT [FK_ONSITEENERGYRCVQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_DISP_QTY] DROP CONSTRAINT [FK_ONSITEDISPQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_OFFSITE_UIC_DISP_QTY] DROP CONSTRAINT [FK_OFFSITEUICDISPQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_OFFSITE_TREATED_Q] DROP CONSTRAINT [FK_OFFSITETREATEDQ_REPORT]
GO
ALTER TABLE [dbo].[TRI_OFFSITE_RECYCLED_Q] DROP CONSTRAINT [FK_OFFSITERECYCLEDQ_REPORT]
GO
ALTER TABLE [dbo].[TRI_OFFSITE_ENERGY_REC_QTY] DROP CONSTRAINT [FK_OFFSITEENERGYRECQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_OFFSITE_DISP_QTY] DROP CONSTRAINT [FK_OFFSITEDISPQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_NPDES_ID] DROP CONSTRAINT [FK_NPDESID_FAC]
GO
ALTER TABLE [dbo].[TRI_FAC_SIC] DROP CONSTRAINT [FK_FACSIC_FAC]
GO
ALTER TABLE [dbo].[TRI_FAC_NAICS] DROP CONSTRAINT [FK_FACNAICS_FAC]
GO
ALTER TABLE [dbo].[TRI_FAC_DUN] DROP CONSTRAINT [FK_FACDUN_FAC]
GO
ALTER TABLE [dbo].[TRI_FAC] DROP CONSTRAINT [FK_FAC_SUB]
GO
ALTER TABLE [dbo].[TRI_COMMENT] DROP CONSTRAINT [FK_COMMENT_REP]
GO
ALTER TABLE [dbo].[TRI_CHEM_REACTNT_SUBCATG] DROP CONSTRAINT [FK_CHEM_REACTNT_SUBCATG_CODE_REPORT]
GO
ALTER TABLE [dbo].[TRI_CHEM_PRCSS_AID_SUBCATG] DROP CONSTRAINT [FK_CHEM_PRCSS_AID_SUBCATG_CODE_REPORT]
GO
ALTER TABLE [dbo].[TRI_CHEM_MFG_AID_SUBCATG] DROP CONSTRAINT [FK_CHEM_MFG_AID_SUBCATG_CODE_REPORT]
GO
ALTER TABLE [dbo].[TRI_CHEM_FRMLN_CMPNT_SUBCATG] DROP CONSTRAINT [FK_CHEM_FRMLN_CMPNT_SUBCATG_CODE_REPORT]
GO
ALTER TABLE [dbo].[TRI_CHEM_ANCLRY_USAGE_SUBCATG] DROP CONSTRAINT [FK_CHEM_ANCLRY_USAGE_SUBCATG_CODE_REPORT]
GO
ALTER TABLE [dbo].[TRI_CHEM] DROP CONSTRAINT [FK_CHEM_REPORT]
GO
ALTER TABLE [dbo].[TRI_SUB] DROP CONSTRAINT [DF__TRI_SUB__INSERTE__3B75D760]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_WASTE_TREAT_METH]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_WASTE_TREAT_METH]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_WASTE_TREAT_DTL]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_WASTE_TREAT_DTL]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_UIC_ID]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_UIC_ID]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_TRANSFER_Q]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_TRANSFER_Q]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_TRANSFER_LOC]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_TRANSFER_LOC]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_SUB]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_SUB]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_SRC_RED_METH_CD]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_SRC_RED_METH_CD]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_SRC_RED_ACT]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_SRC_RED_ACT]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_REPORT_VALIDATION]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_REPORT_VALIDATION]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_REPORT]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_REPORT]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_REPLACED_REPORT_ID]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_REPLACED_REPORT_ID]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_RCRA_ID]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_RCRA_ID]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_POTW_WASTE_QUANTITY]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_POTW_WASTE_QUANTITY]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_ONSITE_UIC_DISP_QTY]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_ONSITE_UIC_DISP_QTY]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_ONSITE_TREATED_Q]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_ONSITE_TREATED_Q]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_ONSITE_RELEASE_Q]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_ONSITE_RELEASE_Q]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_ONSITE_RECYCLED_Q]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_ONSITE_RECYCLED_Q]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_ONSITE_RECYCG_PROC]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_ONSITE_RECYCG_PROC]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_ONSITE_RCV_PROC]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_ONSITE_RCV_PROC]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_ONSITE_ENERGY_RCV_QTY]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_ONSITE_ENERGY_RCV_QTY]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_ONSITE_DISP_QTY]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_ONSITE_DISP_QTY]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_OFFSITE_UIC_DISP_QTY]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_OFFSITE_UIC_DISP_QTY]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_OFFSITE_TREATED_Q]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_OFFSITE_TREATED_Q]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_OFFSITE_RECYCLED_Q]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_OFFSITE_RECYCLED_Q]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_OFFSITE_ENERGY_REC_QTY]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_OFFSITE_ENERGY_REC_QTY]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_OFFSITE_DISP_QTY]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_OFFSITE_DISP_QTY]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_NPDES_ID]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_NPDES_ID]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_FAC_SIC]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_FAC_SIC]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_FAC_NAICS]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_FAC_NAICS]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_FAC_DUN]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_FAC_DUN]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_FAC]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_FAC]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_COMMENT]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_COMMENT]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_CHEM_REACTNT_SUBCATG]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_CHEM_REACTNT_SUBCATG]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_CHEM_PRCSS_AID_SUBCATG]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_CHEM_PRCSS_AID_SUBCATG]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_CHEM_MFG_AID_SUBCATG]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_CHEM_MFG_AID_SUBCATG]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_CHEM_FRMLN_CMPNT_SUBCATG]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_CHEM_FRMLN_CMPNT_SUBCATG]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_CHEM_ANCLRY_USAGE_SUBCATG]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_CHEM_ANCLRY_USAGE_SUBCATG]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRI_CHEM]') AND type in (N'U'))
DROP TABLE [dbo].[TRI_CHEM]
GO
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_CHEM](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[CAS_CLBER] [varchar](100) NULL,
	[CHEM_TXT] [varchar](100) NULL,
	[CHEM_MIXTURE_TXT] [varchar](100) NULL,
	[CHEM_ID] [varchar](100) NULL,
	[CHEM_REGISTRY] [varchar](100) NULL,
	[CHEM_REGISTRY_CTX] [varchar](100) NULL,
	[DIOXIN_DIST1] [varchar](100) NULL,
	[DIOXIN_DIST2] [varchar](100) NULL,
	[DIOXIN_DIST3] [varchar](100) NULL,
	[DIOXIN_DIST4] [varchar](100) NULL,
	[DIOXIN_DIST5] [varchar](100) NULL,
	[DIOXIN_DIST6] [varchar](100) NULL,
	[DIOXIN_DIST7] [varchar](100) NULL,
	[DIOXIN_DIST8] [varchar](100) NULL,
	[DIOXIN_DIST9] [varchar](100) NULL,
	[DIOXIN_DIST10] [varchar](100) NULL,
	[DIOXIN_DIST11] [varchar](100) NULL,
	[DIOXIN_DIST12] [varchar](100) NULL,
	[DIOXIN_DIST13] [varchar](100) NULL,
	[DIOXIN_DIST14] [varchar](100) NULL,
	[DIOXIN_DIST15] [varchar](100) NULL,
	[DIOXIN_DIST16] [varchar](100) NULL,
	[DIOXIN_DIST17] [varchar](100) NULL,
	[METAL_CMP_RPT_INC_ELM_MTL_IND] [char](1) NULL,
	[LEAD_EXCD_THRSHLD_IND] [char](1) NULL,
 CONSTRAINT [PK_TRI_CHEM] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_CHEM_ANCLRY_USAGE_SUBCATG](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[CHEM_ANCLRY_USAGE_SUBCATG_CODE] [varchar](32) NOT NULL,
 CONSTRAINT [PK_TRI_CHEM_ANCLRY_USAGE_SUBCATG] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_CHEM_FRMLN_CMPNT_SUBCATG](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[CHEM_FRMLN_CMPNT_SUBCATG_CODE] [varchar](32) NOT NULL,
 CONSTRAINT [PK_TRI_CHEM_FRMLN_CMPNT_SUBCATG] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_CHEM_MFG_AID_SUBCATG](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[CHEM_MFG_AID_SUBCATG_CODE] [varchar](32) NOT NULL,
 CONSTRAINT [PK_TRI_CHEM_MFG_AID_SUBCATG] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_CHEM_PRCSS_AID_SUBCATG](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[CHEM_PRCSS_AID_SUBCATG_CODE] [varchar](32) NOT NULL,
 CONSTRAINT [PK_TRI_CHEM_PRCSS_AID_SUBCATG] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_CHEM_REACTNT_SUBCATG](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[CHEM_REACTNT_SUBCATG_CODE] [varchar](32) NOT NULL,
 CONSTRAINT [PK_TRI_CHEM_REACTNT_SUBCATG] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_COMMENT](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[COMMENT_SEQ] [int] NULL,
	[COMMENT_SECTION] [varchar](50) NULL,
	[COMMENT_TYPE_CODE] [varchar](50) NULL,
	[COMMENT_TYPE_DESC] [varchar](255) NULL,
	[COMMENT_TEXT] [varchar](4000) NULL,
	[COMMENT_P2_CLASS] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_COMMENT] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_FAC](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[FAC_ID] [varchar](100) NULL,
	[FAC_SITE] [varchar](100) NULL,
	[LOC_ADD_TXT] [varchar](100) NULL,
	[SUPP_LOC_TXT] [varchar](100) NULL,
	[LOCALITY] [varchar](100) NULL,
	[STATE_CL_ID] [varchar](100) NULL,
	[STATE_CODE] [varchar](10) NULL,
	[STATE] [varchar](50) NULL,
	[ADD_POSTAL_CODE] [varchar](50) NULL,
	[COUNTRY_CL_ID] [varchar](100) NULL,
	[COUNTRY_CODE] [varchar](10) NULL,
	[COUNTRY] [varchar](50) NULL,
	[COUNTY_CL_ID] [varchar](100) NULL,
	[COUNTY_CODE] [varchar](100) NULL,
	[COUNTY] [varchar](100) NULL,
	[TRIBAL_CL_ID] [varchar](100) NULL,
	[TRIBAL_CODE] [varchar](100) NULL,
	[TRIBAL] [varchar](100) NULL,
	[TRIBAL_LAND] [varchar](100) NULL,
	[TRIBAL_LAND_IND] [varchar](100) NULL,
	[LOC_DESCN_TXT] [varchar](100) NULL,
	[MAIL_FAC_SITE] [varchar](100) NULL,
	[MAIL_ADD_TXT] [varchar](100) NULL,
	[SUPP_MAIL_ADD] [varchar](100) NULL,
	[MAIL_ADD_CITY] [varchar](100) NULL,
	[MAIL_ADD_POSTAL_CODE] [varchar](100) NULL,
	[PROVINCE_TXT] [varchar](100) NULL,
	[MAIL_ADD_STATE_CDLST] [varchar](100) NULL,
	[MAIL_ADD_STATE_CODE] [varchar](10) NULL,
	[MAIL_ADD_STATE] [varchar](100) NULL,
	[MAIL_ADD_COUNTRY_CDLST] [varchar](100) NULL,
	[MAIL_ADD_COUNTRY_CODE] [varchar](10) NULL,
	[MAIL_ADD_COUNTRY] [varchar](100) NULL,
	[LAT_ME] [varchar](20) NULL,
	[LON_ME] [varchar](20) NULL,
	[SRC_MAP_SCALE_CLBER] [varchar](100) NULL,
	[HOR_ME_VALUE] [varchar](100) NULL,
	[HOR_ME_UNIT_CODE] [varchar](100) NULL,
	[HOR_ME_UNIT] [varchar](100) NULL,
	[HOR_ME_PREC_TXT] [varchar](100) NULL,
	[HOR_RESULT_QFR_CODE] [varchar](100) NULL,
	[HOR_RESULT_QFR] [varchar](100) NULL,
	[HOR_METH_ID_CODE] [varchar](100) NULL,
	[HOR_METH] [varchar](100) NULL,
	[HOR_METH_DESCN_TXT] [varchar](100) NULL,
	[HOR_METH_DEV_TXT] [varchar](100) NULL,
	[GEO_REF_POINT_CD] [varchar](100) NULL,
	[GEO_REF_POINT_NM] [varchar](100) NULL,
	[HOR_REF_DATUM_CD] [varchar](100) NULL,
	[HOR_REF_DATUM_NM] [varchar](100) NULL,
	[DATA_COLLECTION_DATE] [varchar](100) NULL,
	[LOC_COMS_TXT] [varchar](100) NULL,
	[VER_ME_VALUE] [varchar](100) NULL,
	[VER_ME_UNIT_CODE] [varchar](100) NULL,
	[VER_ME_UNIT] [varchar](100) NULL,
	[VER_ME_PREC_TXT] [varchar](100) NULL,
	[VER_RESULT_QFR_CODE] [varchar](100) NULL,
	[VER_RESULT_QFR] [varchar](100) NULL,
	[VER_METH_ID_CODE] [varchar](100) NULL,
	[VER_METH] [varchar](100) NULL,
	[VER_METH_DESCN_TXT] [varchar](100) NULL,
	[VER_METH_DEV_TXT] [varchar](100) NULL,
	[GEO_REF_DATUM_CD] [varchar](100) NULL,
	[GEO_REF_DATUM_NM] [varchar](100) NULL,
	[VERIF_METH_ID] [varchar](100) NULL,
	[VERIF_METH] [varchar](100) NULL,
	[VERIF_METH_DESC] [varchar](100) NULL,
	[VERIF_METH_DEV] [varchar](100) NULL,
	[COORD_DATA_SRC_CODE] [varchar](100) NULL,
	[COORD_DATA_SRC] [varchar](100) NULL,
	[GEOMETRIC_TYPE_CODE] [varchar](100) NULL,
	[GEOMETRIC_TYPE] [varchar](100) NULL,
	[LAT_DEGREE_ME] [varchar](100) NULL,
	[LAT_MINUTE_ME] [varchar](100) NULL,
	[LAT_SECOND_ME] [varchar](100) NULL,
	[LON_DEGREE_ME] [varchar](100) NULL,
	[LON_MINUTE_ME] [varchar](100) NULL,
	[LON_SECOND_ME] [varchar](100) NULL,
	[PARENT_COMPANY_TXT] [varchar](100) NULL,
	[PARENT_DUN_CODE] [varchar](100) NULL,
	[FACILITY_ACCESS_CODE] [varchar](100) NULL,
	[PRI_YR_TECH_CONTACT_NAME] [varchar](100) NULL,
	[PRI_YR_TECH_CONTACT_PHONE] [varchar](100) NULL,
	[PARENT_COMPANY_NAME_N_S] [char](1) NULL,
	[FRGN_PARENT_COMPANY_NAME_NA_IND] [char](1) NULL,
	[FRGN_PARENT_COMPANY_TXT] [varchar](100) NULL,
	[FRGN_PARENT_COMPANY_NAME_N_S] [char](1) NULL,
	[FRGN_PARENT_DUN_CODE] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_FAC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_FAC_DUN](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[FAC_DUN_CODE] [varchar](9) NULL,
 CONSTRAINT [PK_TRI_FAC_DUN] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_FAC_NAICS](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[FAC_NAICS] [varchar](100) NULL,
	[NAICS_PRIMARY_IND] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_NAICS_SIC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_FAC_SIC](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[FAC_SIC] [varchar](100) NULL,
	[SIC_PRIMARY_IND] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_FAC_SIC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_NPDES_ID](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[NPDES_ID_CLBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_NPDES_ID] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_OFFSITE_DISP_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_OFFSITE_DISP_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_OFFSITE_ENERGY_REC_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_OFFSITE_ENERGY_REC_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_OFFSITE_RECYCLED_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_OFFSITE_RECYCLED_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_OFFSITE_TREATED_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_OFFSITE_TREATED_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_OFFSITE_UIC_DISP_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_OFFSITE_UIC_DISP_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_DISP_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_DISP_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_ENERGY_RCV_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_ENERGY_RCV_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_RCV_PROC](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[ENERGY_RCV_METH_CODE] [varchar](100) NULL,
	[ENERGY_RCV_NA_IND] [char](1) NULL,
 CONSTRAINT [PK_TRI_ONSITE_RCV_PROC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_RECYCG_PROC](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[ONSITE_RECYCG_METH_CODE] [varchar](100) NULL,
	[ONSITE_RECYCG_NA_IND] [char](1) NULL,
 CONSTRAINT [PK_TRI_ONSITE_RECYCG_PROC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_RECYCLED_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_RECYCLED_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_RELEASE_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[EI_MEDIUM_CODE] [varchar](100) NULL,
	[WASTE_Q_ME] [varchar](100) NULL,
	[WASTE_Q_NA_IND] [char](1) NULL,
	[WASTE_Q_RANGE_CODE] [varchar](100) NULL,
	[Q_BASIS_EST_CD] [varchar](100) NULL,
	[Q_BASIS_NA_IND] [char](1) NULL,
	[WATER_SEQ_CLBER] [varchar](100) NULL,
	[STREAM] [varchar](100) NULL,
	[RELEASE_STORM_WATER] [varchar](100) NULL,
	[RELEASE_STORM_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[WASTE_Q_CATASTROPHIC_MEASURE] [varchar](100) NULL,
	[WASTE_Q_RANGE_NUM_BASIS_VALUE] [varchar](100) NULL,
	[STREAM_REACH_CODE] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_RELEASE_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_TREATED_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_TREATED_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_ONSITE_UIC_DISP_QTY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NULL,
	[YEAR_OFFSET_ME] [varchar](100) NULL,
	[TOTAL_Q] [varchar](100) NULL,
	[TOTAL_Q_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_ONSITE_UIC_DISP_QTY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_POTW_WASTE_QUANTITY](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[POTW_SEQ_NO] [varchar](100) NULL,
	[WASTE_Q_ME] [varchar](100) NULL,
	[WASTE_Q_CATASTROPHIC_MEASURE] [varchar](100) NULL,
	[WASTE_Q_RANGE_CODE] [varchar](100) NULL,
	[WASTE_Q_RANGE_NUM_BASIS_VALUE] [varchar](100) NULL,
	[WASTE_Q_ME_NA_IND] [char](1) NULL,
	[Q_BASIS_EST_CODE] [varchar](100) NULL,
	[Q_BASIS_EST_NA_IND] [char](1) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[Q_DISP_LANDFILL_PERCENT_VALUE] [varchar](100) NULL,
	[Q_DISP_OTHER_PERCENT_VALUE] [varchar](100) NULL,
	[Q_TREATED_PERCENT_VALUE] [varchar](100) NULL,
	[POTW_TRANSFER_TYPE_CODE] [varchar](32) NULL,
	[POTW_TRANSFER_SEQ_NUMBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_POTW_WASTE_QUANTITY] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_RCRA_ID](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[RCRA_ID_CLBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_RCRA_ID] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_REPLACED_REPORT_ID](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[REPLACED_REPORT_ID] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_REPLACED_REPORT_ID] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_REPORT](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[REPORT_ID] [varchar](100) NULL,
	[REPORT_POST_DATE] [varchar](50) NULL,
	[REPORT_REC_DATE] [varchar](50) NULL,
	[REPORT_ORIG_POST_DATE] [varchar](50) NULL,
	[REPORT_ORIG_REC_DATE] [varchar](50) NULL,
	[REPORT_SUB_METH_CODE] [varchar](100) NULL,
	[REPORT_EPA_PASSED_VALID_IND] [char](1) NULL,
	[REPORT_EPA_PROCESSING_STATUS_C] [varchar](100) NULL,
	[UNALTERED_REPORT_IND] [varchar](100) NULL,
	[REPORT_TYPE_CODE] [varchar](100) NULL,
	[SUB_REP_YEAR] [varchar](100) NULL,
	[REPORT_DUE_DATE] [varchar](50) NULL,
	[REVISION_IND] [varchar](100) NULL,
	[CHEM_TRADE_SECRET_IND] [varchar](100) NULL,
	[SUB_SANITIZED_IND] [varchar](100) NULL,
	[CERTIFIER] [varchar](100) NULL,
	[CERTIFIER_TIT_TXT] [varchar](100) NULL,
	[CERT_SIGNED_DATE] [varchar](100) NULL,
	[SUB_ENTIRE_FAC_IND] [varchar](100) NULL,
	[SUB_PARTIAL_FAC_ID] [varchar](100) NULL,
	[SUB_FEDERAL_FAC_ID] [varchar](100) NULL,
	[SUB_CO_FAC_INDIC] [varchar](100) NULL,
	[TECH_CONT] [varchar](100) NULL,
	[TECH_CONT_PHONE_TXT] [varchar](100) NULL,
	[TECH_CONT_EMAIL_ADDRES] [varchar](100) NULL,
	[PUB_CONT_ID] [varchar](100) NULL,
	[PUB_CONT_TIT_TXT] [varchar](100) NULL,
	[PUB_CONT] [varchar](100) NULL,
	[PUB_CONT_PHONE_TXT] [varchar](50) NULL,
	[CHEM_ANC_USAGE_IND] [varchar](100) NULL,
	[CHEM_ARTICLE_COMP_ID] [varchar](100) NULL,
	[CHEM_BYPRODUCT_IND] [varchar](100) NULL,
	[CHEM_FORMULATION_COMP] [varchar](100) NULL,
	[CHEM_IMPORTED_IND] [varchar](100) NULL,
	[CHEM_MANUFACTURE_AID_ID] [varchar](100) NULL,
	[CHEM_MANUFACTURE_IMPURITY] [varchar](100) NULL,
	[CHEM_PROC_IMPURITY_ID] [varchar](100) NULL,
	[CHEM_PROCING_AID_ID] [varchar](100) NULL,
	[CHEM_PRODUCED_IND] [varchar](100) NULL,
	[CHEM_REACTANT_IND] [varchar](100) NULL,
	[CHEM_REP_IND] [varchar](100) NULL,
	[CHEM_SALES_DIST_ID] [varchar](100) NULL,
	[CHEM_USED_PROCED_ID] [varchar](100) NULL,
	[MAX_CHEM_AMOUNT_CODE] [varchar](100) NULL,
	[ONE_TIME_RELEASE_Q] [varchar](100) NULL,
	[ONE_TIME_NA_IND] [char](1) NULL,
	[PRODUCTION_RATIO_ME] [varchar](100) NULL,
	[PRODUCTION_RATIO_NA_IND] [char](1) NULL,
	[SUB_ADDITIONAL_DATA_ID] [varchar](100) NULL,
	[OPT_INF_TXT] [varchar](4000) NULL,
	[PUB_CONT_EMAIL_ADDRES] [varchar](100) NULL,
	[CHEM_RPT_REV_CD_1] [varchar](100) NULL,
	[CHEM_RPT_REV_CD_2] [varchar](100) NULL,
	[CHEM_RPT_WD_CD_1] [varchar](100) NULL,
	[CHEM_RPT_WD_CD_2] [varchar](100) NULL,
	[TOX_EQ_VAL1_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL2_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL3_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL4_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL5_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL6_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL7_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL8_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL9_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL10_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL11_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL12_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL13_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL14_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL15_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL16_ONETIME] [varchar](100) NULL,
	[TOX_EQ_VAL17_ONETIME] [varchar](100) NULL,
	[TOX_EQ_NA_IND_ONETIME] [char](1) NULL,
	[CALC_ROUNDING_HINT_NUMBER] [varchar](100) NULL,
	[MISC_INF_TXT] [varchar](4000) NULL,
	[TECH_CONT_PHONE_EXT_TXT] [varchar](100) NULL,
	[PUB_CONT_PHONE_EXT_TXT] [varchar](100) NULL,
	[OPT_INF_CATG] [varchar](100) NULL,
	[MISC_INF_CATG] [varchar](100) NULL,
	[PRODUCTION_RATIO_TYPE] [varchar](100) NULL,
	[CHEM_PROC_RECYCG_IND] [char](1) NULL,
	[FORM_PREP_METH] [varchar](32) NULL,
	[WASTE_ROCK_MGD_PILE_IND] [char](1) NULL,
	[WASTE_ROCK_QTY] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_REPORT] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_REPORT_VALIDATION](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[VALIDATION_ENTITY_NAME_TEXT] [varchar](100) NULL,
	[VALIDATION_MESSAGE_CODE] [varchar](100) NULL,
	[VALIDATION_MESSAGE_TEXT] [varchar](100) NULL,
	[EPA_ERROR_SEVERITY_CODE] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_REPORT_VALIDATION] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_SRC_RED_ACT](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[SRC_RED_SEQ_CL] [varchar](100) NULL,
	[SRC_RED_ACT_CODE] [varchar](100) NULL,
	[SRC_RED_NA_IND] [char](1) NULL,
	[SRC_RED_EFF_CODE] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_SRC_RED_ACT] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_SRC_RED_METH_CD](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[SRC_RED_METH_CODE] [varchar](100) NULL,
	[SRC_RED_NA_IND] [char](1) NULL,
 CONSTRAINT [PK_TRI_SRC_RED_METH_CD] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_SUB](
	[PK_GUID] [varchar](36) NOT NULL,
	[TRI_SUB_ID] [varchar](255) NOT NULL,
	[INSERTED_DATE] [datetime] NOT NULL,
	[TRANSACTION_ID] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TRI_SUB] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_TRI_SUB] UNIQUE NONCLUSTERED 
(
	[TRI_SUB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_TRANSFER_LOC](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[TRANSFER_LOC_SEQ_CL] [varchar](100) NULL,
	[POTW_IND] [varchar](100) NULL,
	[FAC_SITE] [varchar](100) NULL,
	[LOC_ADD_TXT] [varchar](100) NULL,
	[SUPP_LOC_TXT] [varchar](100) NULL,
	[LOCALITY] [varchar](100) NULL,
	[STATE] [varchar](100) NULL,
	[ADD_POSTAL_CODE] [varchar](100) NULL,
	[COUNTY] [varchar](100) NULL,
	[CONTROLLED_LOC_IND] [varchar](100) NULL,
	[RCRA_ID_CLBER] [varchar](100) NULL,
	[EPA_REGISTRY_ID] [varchar](32) NULL,
 CONSTRAINT [PK_TRI_TRANSFER_LOC] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_TRANSFER_Q](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[TRANSFER_SEQ_CLBER] [varchar](100) NULL,
	[WASTE_Q_ME] [varchar](100) NULL,
	[WASTE_Q_RANGE_CODE] [varchar](100) NULL,
	[WASTE_Q_NA_IND] [char](1) NULL,
	[Q_BASIS_EST_CODE] [varchar](100) NULL,
	[Q_BASIS_EST_NA_IND] [char](1) NULL,
	[WASTE_MANAGEMENT_CODE] [varchar](100) NULL,
	[TOX_EQ_VAL1] [varchar](100) NULL,
	[TOX_EQ_VAL2] [varchar](100) NULL,
	[TOX_EQ_VAL3] [varchar](100) NULL,
	[TOX_EQ_VAL4] [varchar](100) NULL,
	[TOX_EQ_VAL5] [varchar](100) NULL,
	[TOX_EQ_VAL6] [varchar](100) NULL,
	[TOX_EQ_VAL7] [varchar](100) NULL,
	[TOX_EQ_VAL8] [varchar](100) NULL,
	[TOX_EQ_VAL9] [varchar](100) NULL,
	[TOX_EQ_VAL10] [varchar](100) NULL,
	[TOX_EQ_VAL11] [varchar](100) NULL,
	[TOX_EQ_VAL12] [varchar](100) NULL,
	[TOX_EQ_VAL13] [varchar](100) NULL,
	[TOX_EQ_VAL14] [varchar](100) NULL,
	[TOX_EQ_VAL15] [varchar](100) NULL,
	[TOX_EQ_VAL16] [varchar](100) NULL,
	[TOX_EQ_VAL17] [varchar](100) NULL,
	[TOX_EQ_NA_IND] [char](1) NULL,
	[WASTE_Q_CATASTROPHIC_MEASURE] [varchar](100) NULL,
	[WASTE_Q_RANGE_NUM_BASIS_VALUE] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_TRANSFER_Q] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_UIC_ID](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[UIC_ID_CLBER] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_UIC_ID] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_WASTE_TREAT_DTL](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[WASTE_STREAM_SEQ_CLBER] [varchar](100) NULL,
	[WASTE_STREAM_TYPE_CODE] [varchar](100) NULL,
	[INFLUENT_CONC_RANGE_C] [varchar](100) NULL,
	[TREAT_EFF_EST_PCT] [varchar](100) NULL,
	[TREAT_EFF_RANGE_CD] [varchar](100) NULL,
	[TREAT_EFF_NA_IND] [char](1) NULL,
	[OPERATING_DATA_IND] [varchar](100) NULL,
	[WASTE_TREAT_NA_IND] [char](1) NULL,
 CONSTRAINT [PK_TRI_WASTE_TREAT_DTL] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRI_WASTE_TREAT_METH](
	[PK_GUID] [varchar](36) NOT NULL,
	[FK_GUID] [varchar](36) NOT NULL,
	[WASTE_TREAT_SEQ_CL] [varchar](100) NULL,
	[WASTE_TREAT_METH_CODE] [varchar](100) NULL,
 CONSTRAINT [PK_TRI_WASTE_TREAT_METH] PRIMARY KEY CLUSTERED 
(
	[PK_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRI_SUB] ADD  CONSTRAINT [DF__TRI_SUB__INSERTE__3B75D760]  DEFAULT (getdate()) FOR [INSERTED_DATE]
GO
ALTER TABLE [dbo].[TRI_CHEM]  WITH CHECK ADD  CONSTRAINT [FK_CHEM_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_CHEM] CHECK CONSTRAINT [FK_CHEM_REPORT]
GO
ALTER TABLE [dbo].[TRI_CHEM_ANCLRY_USAGE_SUBCATG]  WITH CHECK ADD  CONSTRAINT [FK_CHEM_ANCLRY_USAGE_SUBCATG_CODE_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_CHEM_ANCLRY_USAGE_SUBCATG] CHECK CONSTRAINT [FK_CHEM_ANCLRY_USAGE_SUBCATG_CODE_REPORT]
GO
ALTER TABLE [dbo].[TRI_CHEM_FRMLN_CMPNT_SUBCATG]  WITH CHECK ADD  CONSTRAINT [FK_CHEM_FRMLN_CMPNT_SUBCATG_CODE_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_CHEM_FRMLN_CMPNT_SUBCATG] CHECK CONSTRAINT [FK_CHEM_FRMLN_CMPNT_SUBCATG_CODE_REPORT]
GO
ALTER TABLE [dbo].[TRI_CHEM_MFG_AID_SUBCATG]  WITH CHECK ADD  CONSTRAINT [FK_CHEM_MFG_AID_SUBCATG_CODE_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_CHEM_MFG_AID_SUBCATG] CHECK CONSTRAINT [FK_CHEM_MFG_AID_SUBCATG_CODE_REPORT]
GO
ALTER TABLE [dbo].[TRI_CHEM_PRCSS_AID_SUBCATG]  WITH CHECK ADD  CONSTRAINT [FK_CHEM_PRCSS_AID_SUBCATG_CODE_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_CHEM_PRCSS_AID_SUBCATG] CHECK CONSTRAINT [FK_CHEM_PRCSS_AID_SUBCATG_CODE_REPORT]
GO
ALTER TABLE [dbo].[TRI_CHEM_REACTNT_SUBCATG]  WITH CHECK ADD  CONSTRAINT [FK_CHEM_REACTNT_SUBCATG_CODE_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_CHEM_REACTNT_SUBCATG] CHECK CONSTRAINT [FK_CHEM_REACTNT_SUBCATG_CODE_REPORT]
GO
ALTER TABLE [dbo].[TRI_COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_COMMENT_REP] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_COMMENT] CHECK CONSTRAINT [FK_COMMENT_REP]
GO
ALTER TABLE [dbo].[TRI_FAC]  WITH CHECK ADD  CONSTRAINT [FK_FAC_SUB] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_SUB] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_FAC] CHECK CONSTRAINT [FK_FAC_SUB]
GO
ALTER TABLE [dbo].[TRI_FAC_DUN]  WITH CHECK ADD  CONSTRAINT [FK_FACDUN_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_FAC_DUN] CHECK CONSTRAINT [FK_FACDUN_FAC]
GO
ALTER TABLE [dbo].[TRI_FAC_NAICS]  WITH CHECK ADD  CONSTRAINT [FK_FACNAICS_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_FAC_NAICS] CHECK CONSTRAINT [FK_FACNAICS_FAC]
GO
ALTER TABLE [dbo].[TRI_FAC_SIC]  WITH CHECK ADD  CONSTRAINT [FK_FACSIC_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_FAC_SIC] CHECK CONSTRAINT [FK_FACSIC_FAC]
GO
ALTER TABLE [dbo].[TRI_NPDES_ID]  WITH CHECK ADD  CONSTRAINT [FK_NPDESID_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_NPDES_ID] CHECK CONSTRAINT [FK_NPDESID_FAC]
GO
ALTER TABLE [dbo].[TRI_OFFSITE_DISP_QTY]  WITH CHECK ADD  CONSTRAINT [FK_OFFSITEDISPQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_OFFSITE_DISP_QTY] CHECK CONSTRAINT [FK_OFFSITEDISPQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_OFFSITE_ENERGY_REC_QTY]  WITH CHECK ADD  CONSTRAINT [FK_OFFSITEENERGYRECQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_OFFSITE_ENERGY_REC_QTY] CHECK CONSTRAINT [FK_OFFSITEENERGYRECQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_OFFSITE_RECYCLED_Q]  WITH CHECK ADD  CONSTRAINT [FK_OFFSITERECYCLEDQ_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_OFFSITE_RECYCLED_Q] CHECK CONSTRAINT [FK_OFFSITERECYCLEDQ_REPORT]
GO
ALTER TABLE [dbo].[TRI_OFFSITE_TREATED_Q]  WITH CHECK ADD  CONSTRAINT [FK_OFFSITETREATEDQ_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_OFFSITE_TREATED_Q] CHECK CONSTRAINT [FK_OFFSITETREATEDQ_REPORT]
GO
ALTER TABLE [dbo].[TRI_OFFSITE_UIC_DISP_QTY]  WITH CHECK ADD  CONSTRAINT [FK_OFFSITEUICDISPQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_OFFSITE_UIC_DISP_QTY] CHECK CONSTRAINT [FK_OFFSITEUICDISPQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_DISP_QTY]  WITH CHECK ADD  CONSTRAINT [FK_ONSITEDISPQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_DISP_QTY] CHECK CONSTRAINT [FK_ONSITEDISPQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_ENERGY_RCV_QTY]  WITH CHECK ADD  CONSTRAINT [FK_ONSITEENERGYRCVQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_ENERGY_RCV_QTY] CHECK CONSTRAINT [FK_ONSITEENERGYRCVQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_RCV_PROC]  WITH CHECK ADD  CONSTRAINT [FK_ONSITERCVPROC_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_RCV_PROC] CHECK CONSTRAINT [FK_ONSITERCVPROC_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_RECYCG_PROC]  WITH CHECK ADD  CONSTRAINT [FK_ONSITERECYCGPROC_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_RECYCG_PROC] CHECK CONSTRAINT [FK_ONSITERECYCGPROC_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_RECYCLED_Q]  WITH CHECK ADD  CONSTRAINT [FK_ONSITERECYCLEDQ_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_RECYCLED_Q] CHECK CONSTRAINT [FK_ONSITERECYCLEDQ_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_RELEASE_Q]  WITH CHECK ADD  CONSTRAINT [FK_ONSITERELEASEQ_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_RELEASE_Q] CHECK CONSTRAINT [FK_ONSITERELEASEQ_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_TREATED_Q]  WITH CHECK ADD  CONSTRAINT [FK_ONSITETREATEDQ_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_TREATED_Q] CHECK CONSTRAINT [FK_ONSITETREATEDQ_REPORT]
GO
ALTER TABLE [dbo].[TRI_ONSITE_UIC_DISP_QTY]  WITH CHECK ADD  CONSTRAINT [FK_ONSITEUICDISPQTY_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_ONSITE_UIC_DISP_QTY] CHECK CONSTRAINT [FK_ONSITEUICDISPQTY_REPORT]
GO
ALTER TABLE [dbo].[TRI_POTW_WASTE_QUANTITY]  WITH CHECK ADD  CONSTRAINT [FK_TRI_RPT_POTW_WQ] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_POTW_WASTE_QUANTITY] CHECK CONSTRAINT [FK_TRI_RPT_POTW_WQ]
GO
ALTER TABLE [dbo].[TRI_RCRA_ID]  WITH CHECK ADD  CONSTRAINT [FK_RCRAID_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_RCRA_ID] CHECK CONSTRAINT [FK_RCRAID_FAC]
GO
ALTER TABLE [dbo].[TRI_REPLACED_REPORT_ID]  WITH CHECK ADD  CONSTRAINT [FK_REPLACEDREPORTID_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_REPLACED_REPORT_ID] CHECK CONSTRAINT [FK_REPLACEDREPORTID_REPORT]
GO
ALTER TABLE [dbo].[TRI_REPORT]  WITH CHECK ADD  CONSTRAINT [FK_REPORT_SUB] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_SUB] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_REPORT] CHECK CONSTRAINT [FK_REPORT_SUB]
GO
ALTER TABLE [dbo].[TRI_REPORT_VALIDATION]  WITH CHECK ADD  CONSTRAINT [FK_TRI_REPORT_VALIDATION_TRI_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_REPORT_VALIDATION] CHECK CONSTRAINT [FK_TRI_REPORT_VALIDATION_TRI_REPORT]
GO
ALTER TABLE [dbo].[TRI_SRC_RED_ACT]  WITH CHECK ADD  CONSTRAINT [FK_SRCREDACT_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_SRC_RED_ACT] CHECK CONSTRAINT [FK_SRCREDACT_REPORT]
GO
ALTER TABLE [dbo].[TRI_SRC_RED_METH_CD]  WITH CHECK ADD  CONSTRAINT [FK_SRCREDMETHCD_SRCREDACT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_SRC_RED_ACT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_SRC_RED_METH_CD] CHECK CONSTRAINT [FK_SRCREDMETHCD_SRCREDACT]
GO
ALTER TABLE [dbo].[TRI_TRANSFER_LOC]  WITH CHECK ADD  CONSTRAINT [FK_TRANSFERLOC_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_TRANSFER_LOC] CHECK CONSTRAINT [FK_TRANSFERLOC_REPORT]
GO
ALTER TABLE [dbo].[TRI_TRANSFER_Q]  WITH CHECK ADD  CONSTRAINT [FK_TRANSFERQ_TRANSFERLOC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_TRANSFER_LOC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_TRANSFER_Q] CHECK CONSTRAINT [FK_TRANSFERQ_TRANSFERLOC]
GO
ALTER TABLE [dbo].[TRI_UIC_ID]  WITH CHECK ADD  CONSTRAINT [FK_UICID_FAC] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_FAC] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_UIC_ID] CHECK CONSTRAINT [FK_UICID_FAC]
GO
ALTER TABLE [dbo].[TRI_WASTE_TREAT_DTL]  WITH CHECK ADD  CONSTRAINT [FK_WASTETREATDTL_REPORT] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_REPORT] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_WASTE_TREAT_DTL] CHECK CONSTRAINT [FK_WASTETREATDTL_REPORT]
GO
ALTER TABLE [dbo].[TRI_WASTE_TREAT_METH]  WITH CHECK ADD  CONSTRAINT [FK_WASTETREATMETH_WTDTL] FOREIGN KEY([FK_GUID])
REFERENCES [dbo].[TRI_WASTE_TREAT_DTL] ([PK_GUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TRI_WASTE_TREAT_METH] CHECK CONSTRAINT [FK_WASTETREATMETH_WTDTL]
GO
