/*************************************************************************************************
** ObjectName: TRI_6.0-ORA-DLL.sql
**
** Author: Windsor Solutions, Inc.
**
** Company Name: Windsor Solutions, Inc.
**
** Description:  This script will build the TRI database objects to support the OpenNode2 TRI
**               plug-in.  Run the script from the top if running for the first time, if running
**               in an existing environment you'll need to run the drop statements first, then 
**               run the create statements.  Please note, dropping the recreating the schema 
**               objects will purge all data.
**
** Revision History:
** ------------------------------------------------------------------------------------------------
** Date          Name        Description
** ------------------------------------------------------------------------------------------------
** 06/10/2016    Windsor     Created 
**
***************************************************************************************************/

/*

ALTER TABLE "TRI_WASTE_TREAT_METH"
 DROP CONSTRAINT "FK_WASTETREATMETH_WTDTL";

ALTER TABLE "TRI_WASTE_TREAT_DTL"
 DROP CONSTRAINT "FK_WASTETREATDTL_REPORT";

ALTER TABLE "TRI_UIC_ID"
 DROP CONSTRAINT "FK_UICID_FAC";

ALTER TABLE "TRI_TRANSFER_Q"
 DROP CONSTRAINT "FK_TRANSFERQ_TRANSFERLOC";

ALTER TABLE "TRI_TRANSFER_LOC"
 DROP CONSTRAINT "FK_TRANSFERLOC_REPORT";

ALTER TABLE "TRI_SRC_RED_METH_CD"
 DROP CONSTRAINT "FK_SRCREDMETHCD_SRCREDACT";

ALTER TABLE "TRI_SRC_RED_ACT"
 DROP CONSTRAINT "FK_SRCREDACT_REPORT";

ALTER TABLE "TRI_REPORT"
 DROP CONSTRAINT "FK_REPORT_SUB";

ALTER TABLE "TRI_REPORT_VALIDATION"
 DROP CONSTRAINT "FK_TRI_REPORT_VALIDATION_TRI_R";

ALTER TABLE "TRI_REPLACED_REPORT_ID"
 DROP CONSTRAINT "FK_REPLACEDREPORTID_REPORT";

ALTER TABLE "TRI_RCRA_ID"
 DROP CONSTRAINT "FK_RCRAID_FAC";

ALTER TABLE "TRI_POTW_WASTE_QUANTITY"
 DROP CONSTRAINT "FK_TRI_RPT_POTW_WQ";

ALTER TABLE "TRI_ONSITE_UIC_DISP_QTY"
 DROP CONSTRAINT "FK_ONSITEUICDISPQTY_REPORT";

ALTER TABLE "TRI_ONSITE_TREATED_Q"
 DROP CONSTRAINT "FK_ONSITETREATEDQ_REPORT";

ALTER TABLE "TRI_ONSITE_RELEASE_Q"
 DROP CONSTRAINT "FK_ONSITERELEASEQ_REPORT";

ALTER TABLE "TRI_ONSITE_RECYCLED_Q"
 DROP CONSTRAINT "FK_ONSITERECYCLEDQ_REPORT";

ALTER TABLE "TRI_ONSITE_RECYCG_PROC"
 DROP CONSTRAINT "FK_ONSITERECYCGPROC_REPORT";

ALTER TABLE "TRI_ONSITE_RCV_PROC"
 DROP CONSTRAINT "FK_ONSITERCVPROC_REPORT";

ALTER TABLE "TRI_ONSITE_ENERGY_RCV_QTY"
 DROP CONSTRAINT "FK_ONSITEENERGYRCVQTY_REPORT";

ALTER TABLE "TRI_ONSITE_DISP_QTY"
 DROP CONSTRAINT "FK_ONSITEDISPQTY_REPORT";

ALTER TABLE "TRI_OFFSITE_UIC_DISP_QTY"
 DROP CONSTRAINT "FK_OFFSITEUICDISPQTY_REPORT";

ALTER TABLE "TRI_OFFSITE_TREATED_Q"
 DROP CONSTRAINT "FK_OFFSITETREATEDQ_REPORT";

ALTER TABLE "TRI_OFFSITE_RECYCLED_Q"
 DROP CONSTRAINT "FK_OFFSITERECYCLEDQ_REPORT";

ALTER TABLE "TRI_OFFSITE_ENERGY_REC_QTY"
 DROP CONSTRAINT "FK_OFFSITEENERGYRECQTY_REPORT";

ALTER TABLE "TRI_OFFSITE_DISP_QTY"
 DROP CONSTRAINT "FK_OFFSITEDISPQTY_REPORT";

ALTER TABLE "TRI_NPDES_ID"
 DROP CONSTRAINT "FK_NPDESID_FAC";

ALTER TABLE "TRI_FAC"
 DROP CONSTRAINT "FK_FAC_SUB";

ALTER TABLE "TRI_FAC_SIC"
 DROP CONSTRAINT "FK_FACSIC_FAC";

ALTER TABLE "TRI_FAC_NAICS"
 DROP CONSTRAINT "FK_FACNAICS_FAC";

ALTER TABLE "TRI_FAC_DUN"
 DROP CONSTRAINT "FK_FACDUN_FAC";

ALTER TABLE "TRI_COMMENT"
 DROP CONSTRAINT "FK_COMMENT_REP";

ALTER TABLE "TRI_CHEM"
 DROP CONSTRAINT "FK_CHEM_REPORT";

ALTER TABLE "TRI_SUB"
 DROP CONSTRAINT "UK_TRI_SUB";

ALTER TABLE "TRI_WASTE_TREAT_METH"
 DROP CONSTRAINT "PK_TRI_WASTE_TREAT_METH";

ALTER TABLE "TRI_WASTE_TREAT_DTL"
 DROP CONSTRAINT "PK_TRI_WASTE_TREAT_DTL";

ALTER TABLE "TRI_UIC_ID"
 DROP CONSTRAINT "PK_TRI_UIC_ID";

ALTER TABLE "TRI_TRANSFER_Q"
 DROP CONSTRAINT "PK_TRI_TRANSFER_Q";

ALTER TABLE "TRI_TRANSFER_LOC"
 DROP CONSTRAINT "PK_TRI_TRANSFER_LOC";

ALTER TABLE "TRI_SUB"
 DROP CONSTRAINT "PK_TRI_SUB";

ALTER TABLE "TRI_SRC_RED_METH_CD"
 DROP CONSTRAINT "PK_TRI_SRC_RED_METH_CD";

ALTER TABLE "TRI_SRC_RED_ACT"
 DROP CONSTRAINT "PK_TRI_SRC_RED_ACT";

ALTER TABLE "TRI_REPORT"
 DROP CONSTRAINT "PK_TRI_REPORT";

ALTER TABLE "TRI_REPORT_VALIDATION"
 DROP CONSTRAINT "PK_TRI_REPORT_VALIDATION";

ALTER TABLE "TRI_REPLACED_REPORT_ID"
 DROP CONSTRAINT "PK_TRI_REPLACED_REPORT_ID";

ALTER TABLE "TRI_RCRA_ID"
 DROP CONSTRAINT "PK_TRI_RCRA_ID";

ALTER TABLE "TRI_POTW_WASTE_QUANTITY"
 DROP CONSTRAINT "PK_TRI_POTW_WASTE_QUANTITY";

ALTER TABLE "TRI_ONSITE_UIC_DISP_QTY"
 DROP CONSTRAINT "PK_TRI_ONSITE_UIC_DISP_QTY";

ALTER TABLE "TRI_ONSITE_TREATED_Q"
 DROP CONSTRAINT "PK_TRI_ONSITE_TREATED_Q";

ALTER TABLE "TRI_ONSITE_RELEASE_Q"
 DROP CONSTRAINT "PK_TRI_ONSITE_RELEASE_Q";

ALTER TABLE "TRI_ONSITE_RECYCLED_Q"
 DROP CONSTRAINT "PK_TRI_ONSITE_RECYCLED_Q";

ALTER TABLE "TRI_ONSITE_RECYCG_PROC"
 DROP CONSTRAINT "PK_TRI_ONSITE_RECYCG_PROC";

ALTER TABLE "TRI_ONSITE_RCV_PROC"
 DROP CONSTRAINT "PK_TRI_ONSITE_RCV_PROC";

ALTER TABLE "TRI_ONSITE_ENERGY_RCV_QTY"
 DROP CONSTRAINT "PK_TRI_ONSITE_ENERGY_RCV_QTY";

ALTER TABLE "TRI_ONSITE_DISP_QTY"
 DROP CONSTRAINT "PK_TRI_ONSITE_DISP_QTY";

ALTER TABLE "TRI_OFFSITE_UIC_DISP_QTY"
 DROP CONSTRAINT "PK_TRI_OFFSITE_UIC_DISP_QTY";

ALTER TABLE "TRI_OFFSITE_TREATED_Q"
 DROP CONSTRAINT "PK_TRI_OFFSITE_TREATED_Q";

ALTER TABLE "TRI_OFFSITE_RECYCLED_Q"
 DROP CONSTRAINT "PK_TRI_OFFSITE_RECYCLED_Q";

ALTER TABLE "TRI_OFFSITE_ENERGY_REC_QTY"
 DROP CONSTRAINT "PK_TRI_OFFSITE_ENERGY_REC_QTY";

ALTER TABLE "TRI_OFFSITE_DISP_QTY"
 DROP CONSTRAINT "PK_TRI_OFFSITE_DISP_QTY";

ALTER TABLE "TRI_NPDES_ID"
 DROP CONSTRAINT "PK_TRI_NPDES_ID";

ALTER TABLE "TRI_FAC"
 DROP CONSTRAINT "PK_TRI_FAC";

ALTER TABLE "TRI_FAC_SIC"
 DROP CONSTRAINT "PK_TRI_FAC_SIC";

ALTER TABLE "TRI_FAC_NAICS"
 DROP CONSTRAINT "PK_TRI_FAC_NAICS";

ALTER TABLE "TRI_FAC_DUN"
 DROP CONSTRAINT "PK_TRI_FAC_DUN";

ALTER TABLE "TRI_COMMENT"
 DROP CONSTRAINT "PK_TRI_COMMENT";

ALTER TABLE "TRI_CHEM"
 DROP CONSTRAINT "PK_TRI_CHEM";

DROP TRIGGER "TRI_SUB_BI";

DROP INDEX "IX_TRI_WST_TRT_METH_FK_GUID";

DROP INDEX "PK_TRI_WASTE_TREAT_METH";

DROP INDEX "PK_TRI_WASTE_TREAT_DTL";

DROP INDEX "IX_TRI_WASTE_TREAT_DTL";

DROP INDEX "PK_TRI_UIC_ID";

DROP INDEX "IX_TRI_UIC_ID_FK_GUID";

DROP INDEX "PK_TRI_TRANSFER_Q";

DROP INDEX "IX_TRI_TRANSFER_Q_FK_GUID";

DROP INDEX "IX_TRI_TRANSFER_LOC_FK_GUID";

DROP INDEX "PK_TRI_TRANSFER_LOC";

DROP INDEX "PK_TRI_SUB";

DROP INDEX "UK_TRI_SUB";

DROP INDEX "IX_TRI_SRC_RED_METH_CD_FK_GUID";

DROP INDEX "PK_TRI_SRC_RED_METH_CD";

DROP INDEX "PK_TRI_SRC_RED_ACT";

DROP INDEX "IX_TRI_SRC_RED_ACT";

DROP INDEX "PK_TRI_REPORT";

DROP INDEX "IX_TRI_REPORT";

DROP INDEX "PK_TRI_REPORT_VALIDATION";

DROP INDEX "IX_TRI_REPORT_VALIDATION";

DROP INDEX "PK_TRI_REPLACED_REPORT_ID";

DROP INDEX "IX_TRI_REPLACED_REPORT_ID";

DROP INDEX "IX_TRI_RCRA_ID";

DROP INDEX "PK_TRI_RCRA_ID";

DROP INDEX "PK_TRI_POTW_WASTE_QUANTITY";

DROP INDEX "IX_TRI_ONSITE_UIC_DISP_QTY";

DROP INDEX "PK_TRI_ONSITE_UIC_DISP_QTY";

DROP INDEX "PK_TRI_ONSITE_TREATED_Q";

DROP INDEX "IX_TRI_ON_TREATED_Q_FK_GUID";

DROP INDEX "IX_TRI_ON_RELEASE_Q_FK_GUID";

DROP INDEX "PK_TRI_ONSITE_RELEASE_Q";

DROP INDEX "IX_TRI_ONSITE_RECYCLED_Q";

DROP INDEX "PK_TRI_ONSITE_RECYCLED_Q";

DROP INDEX "PK_TRI_ONSITE_RECYCG_PROC";

DROP INDEX "IX_TRI_ON_RECYCG_PROC_FK_GUID";

DROP INDEX "PK_TRI_ONSITE_RCV_PROC";

DROP INDEX "IX_TRI_ONSITE_RCV_PROC_FK_GUID";

DROP INDEX "PK_TRI_ONSITE_ENERGY_RCV_QTY";

DROP INDEX "IX_TRI_ON_EGY_RCV_QTY_FK_GUID";

DROP INDEX "PK_TRI_ONSITE_DISP_QTY";

DROP INDEX "IX_TRI_ON_DIS_QTY_FK_GUID";

DROP INDEX "PK_TRI_OFFSITE_UIC_DISP_QTY";

DROP INDEX "IX_TRI_OFFSITE_UIC_DISP_QTY";

DROP INDEX "IX_TRI_OFF_TREATED_Q_FK_GUID";

DROP INDEX "PK_TRI_OFFSITE_TREATED_Q";

DROP INDEX "IX_TRI_OFFSITE_RECYCLED_Q";

DROP INDEX "PK_TRI_OFFSITE_RECYCLED_Q";

DROP INDEX "IX_TRI_OFF_EGY_REC_QTY_FK_GUID";

DROP INDEX "PK_TRI_OFFSITE_ENERGY_REC_QTY";

DROP INDEX "IX_TRI_OFF_DISP_QTY_FK_GUID";

DROP INDEX "PK_TRI_OFFSITE_DISP_QTY";

DROP INDEX "IX_TRI_NPDES_ID";

DROP INDEX "PK_TRI_NPDES_ID";

DROP INDEX "IX_TRI_FAC_FK_GUID";

DROP INDEX "PK_TRI_FAC";

DROP INDEX "IX_TRI_FAC_FAC_ID";

DROP INDEX "PK_TRI_FAC_SIC";

DROP INDEX "IX_TRI_FAC_SIC_FK_GUID";

DROP INDEX "PK_TRI_FAC_NAICS";

DROP INDEX "IX_TRI_FAC_NAICS";

DROP INDEX "IX_TRI_FAC_DUN";

DROP INDEX "PK_TRI_FAC_DUN";

DROP INDEX "PK_TRI_COMMENT";

DROP INDEX "IX_TRI_COMMENT_FK_GUID";

DROP INDEX "PK_TRI_CHEM";

DROP INDEX "IX_TRI_CHEM_FK_GUID";

DROP SEQUENCE "ID_SEQ";

DROP TABLE "TRI_WASTE_TREAT_METH";

DROP TABLE "TRI_WASTE_TREAT_DTL";

DROP TABLE "TRI_UIC_ID";

DROP TABLE "TRI_TRANSFER_Q";

DROP TABLE "TRI_TRANSFER_LOC";

DROP TABLE "TRI_SUB";

DROP TABLE "TRI_SRC_RED_METH_CD";

DROP TABLE "TRI_SRC_RED_ACT";

DROP TABLE "TRI_REPORT";

DROP TABLE "TRI_REPORT_VALIDATION";

DROP TABLE "TRI_REPLACED_REPORT_ID";

DROP TABLE "TRI_RCRA_ID";

DROP TABLE "TRI_POTW_WASTE_QUANTITY";

DROP TABLE "TRI_ONSITE_UIC_DISP_QTY";

DROP TABLE "TRI_ONSITE_TREATED_Q";

DROP TABLE "TRI_ONSITE_RELEASE_Q";

DROP TABLE "TRI_ONSITE_RECYCLED_Q";

DROP TABLE "TRI_ONSITE_RECYCG_PROC";

DROP TABLE "TRI_ONSITE_RCV_PROC";

DROP TABLE "TRI_ONSITE_ENERGY_RCV_QTY";

DROP TABLE "TRI_ONSITE_DISP_QTY";

DROP TABLE "TRI_OFFSITE_UIC_DISP_QTY";

DROP TABLE "TRI_OFFSITE_TREATED_Q";

DROP TABLE "TRI_OFFSITE_RECYCLED_Q";

DROP TABLE "TRI_OFFSITE_ENERGY_REC_QTY";

DROP TABLE "TRI_OFFSITE_DISP_QTY";

DROP TABLE "TRI_NPDES_ID";

DROP TABLE "TRI_FAC";

DROP TABLE "TRI_FAC_SIC";

DROP TABLE "TRI_FAC_NAICS";

DROP TABLE "TRI_FAC_DUN";

DROP TABLE "TRI_COMMENT";

DROP TABLE "TRI_CHEM";

*/

CREATE TABLE "TRI_CHEM" ( 
 "PK_GUID"           VARCHAR2(36) NOT NULL,
 "FK_GUID"           VARCHAR2(36) NOT NULL,
 "CAS_CLBER"         VARCHAR2(100) NULL,
 "CHEM_TXT"          VARCHAR2(100) NULL,
 "CHEM_MIXTURE_TXT"  VARCHAR2(100) NULL,
 "CHEM_ID"           VARCHAR2(100) NULL,
 "CHEM_REGISTRY"     VARCHAR2(100) NULL,
 "CHEM_REGISTRY_CTX" VARCHAR2(100) NULL,
 "DIOXIN_DIST1"      VARCHAR2(100) NULL,
 "DIOXIN_DIST2"      VARCHAR2(100) NULL,
 "DIOXIN_DIST3"      VARCHAR2(100) NULL,
 "DIOXIN_DIST4"      VARCHAR2(100) NULL,
 "DIOXIN_DIST5"      VARCHAR2(100) NULL,
 "DIOXIN_DIST6"      VARCHAR2(100) NULL,
 "DIOXIN_DIST7"      VARCHAR2(100) NULL,
 "DIOXIN_DIST8"      VARCHAR2(100) NULL,
 "DIOXIN_DIST9"      VARCHAR2(100) NULL,
 "DIOXIN_DIST10"     VARCHAR2(100) NULL,
 "DIOXIN_DIST11"     VARCHAR2(100) NULL,
 "DIOXIN_DIST12"     VARCHAR2(100) NULL,
 "DIOXIN_DIST13"     VARCHAR2(100) NULL,
 "DIOXIN_DIST14"     VARCHAR2(100) NULL,
 "DIOXIN_DIST15"     VARCHAR2(100) NULL,
 "DIOXIN_DIST16"     VARCHAR2(100) NULL,
 "DIOXIN_DIST17"     VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_COMMENT" ( 
 "PK_GUID"           VARCHAR2(36) NOT NULL,
 "FK_GUID"           VARCHAR2(36) NOT NULL,
 "COMMENT_SEQ"       NUMBER NULL,
 "COMMENT_SECTION"   VARCHAR2(50) NULL,
 "COMMENT_TYPE_CODE" VARCHAR2(50) NULL,
 "COMMENT_TYPE_DESC" VARCHAR2(255) NULL,
 "COMMENT_TEXT"      VARCHAR2(4000) NULL,
 "COMMENT_P2_CLASS"  VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_FAC_DUN" ( 
 "PK_GUID"      VARCHAR2(36) NOT NULL,
 "FK_GUID"      VARCHAR2(36) NOT NULL,
 "FAC_DUN_CODE" VARCHAR2(9) NULL 
 );

CREATE TABLE "TRI_FAC_NAICS" ( 
 "PK_GUID"           VARCHAR2(36) NOT NULL,
 "FK_GUID"           VARCHAR2(36) NOT NULL,
 "FAC_NAICS"         VARCHAR2(100) NULL,
 "NAICS_PRIMARY_IND" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_FAC_SIC" ( 
 "PK_GUID"         VARCHAR2(36) NOT NULL,
 "FK_GUID"         VARCHAR2(36) NOT NULL,
 "FAC_SIC"         VARCHAR2(100) NULL,
 "SIC_PRIMARY_IND" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_FAC" ( 
 "PK_GUID"                   VARCHAR2(36) NOT NULL,
 "FK_GUID"                   VARCHAR2(36) NOT NULL,
 "FAC_ID"                    VARCHAR2(100) NULL,
 "FAC_SITE"                  VARCHAR2(100) NULL,
 "LOC_ADD_TXT"               VARCHAR2(100) NULL,
 "SUPP_LOC_TXT"              VARCHAR2(100) NULL,
 "LOCALITY"                  VARCHAR2(100) NULL,
 "STATE_CL_ID"               VARCHAR2(100) NULL,
 "STATE_CODE"                VARCHAR2(10) NULL,
 "STATE"                     VARCHAR2(50) NULL,
 "ADD_POSTAL_CODE"           VARCHAR2(50) NULL,
 "COUNTRY_CL_ID"             VARCHAR2(100) NULL,
 "COUNTRY_CODE"              VARCHAR2(10) NULL,
 "COUNTRY"                   VARCHAR2(50) NULL,
 "COUNTY_CL_ID"              VARCHAR2(100) NULL,
 "COUNTY_CODE"               VARCHAR2(100) NULL,
 "COUNTY"                    VARCHAR2(100) NULL,
 "TRIBAL_CL_ID"              VARCHAR2(100) NULL,
 "TRIBAL_CODE"               VARCHAR2(100) NULL,
 "TRIBAL"                    VARCHAR2(100) NULL,
 "TRIBAL_LAND"               VARCHAR2(100) NULL,
 "TRIBAL_LAND_IND"           VARCHAR2(100) NULL,
 "LOC_DESCN_TXT"             VARCHAR2(100) NULL,
 "MAIL_FAC_SITE"             VARCHAR2(100) NULL,
 "MAIL_ADD_TXT"              VARCHAR2(100) NULL,
 "SUPP_MAIL_ADD"             VARCHAR2(100) NULL,
 "MAIL_ADD_CITY"             VARCHAR2(100) NULL,
 "MAIL_ADD_POSTAL_CODE"      VARCHAR2(100) NULL,
 "PROVINCE_TXT"              VARCHAR2(100) NULL,
 "MAIL_ADD_STATE_CDLST"      VARCHAR2(100) NULL,
 "MAIL_ADD_STATE_CODE"       VARCHAR2(10) NULL,
 "MAIL_ADD_STATE"            VARCHAR2(100) NULL,
 "MAIL_ADD_COUNTRY_CDLST"    VARCHAR2(100) NULL,
 "MAIL_ADD_COUNTRY_CODE"     VARCHAR2(10) NULL,
 "MAIL_ADD_COUNTRY"          VARCHAR2(100) NULL,
 "LAT_ME"                    VARCHAR2(20) NULL,
 "LON_ME"                    VARCHAR2(20) NULL,
 "SRC_MAP_SCALE_CLBER"       VARCHAR2(100) NULL,
 "HOR_ME_VALUE"              VARCHAR2(100) NULL,
 "HOR_ME_UNIT_CODE"          VARCHAR2(100) NULL,
 "HOR_ME_UNIT"               VARCHAR2(100) NULL,
 "HOR_ME_PREC_TXT"           VARCHAR2(100) NULL,
 "HOR_RESULT_QFR_CODE"       VARCHAR2(100) NULL,
 "HOR_RESULT_QFR"            VARCHAR2(100) NULL,
 "HOR_METH_ID_CODE"          VARCHAR2(100) NULL,
 "HOR_METH"                  VARCHAR2(100) NULL,
 "HOR_METH_DESCN_TXT"        VARCHAR2(100) NULL,
 "HOR_METH_DEV_TXT"          VARCHAR2(100) NULL,
 "GEO_REF_POINT_CD"          VARCHAR2(100) NULL,
 "GEO_REF_POINT_NM"          VARCHAR2(100) NULL,
 "HOR_REF_DATUM_CD"          VARCHAR2(100) NULL,
 "HOR_REF_DATUM_NM"          VARCHAR2(100) NULL,
 "DATA_COLLECTION_DATE"      VARCHAR2(100) NULL,
 "LOC_COMS_TXT"              VARCHAR2(100) NULL,
 "VER_ME_VALUE"              VARCHAR2(100) NULL,
 "VER_ME_UNIT_CODE"          VARCHAR2(100) NULL,
 "VER_ME_UNIT"               VARCHAR2(100) NULL,
 "VER_ME_PREC_TXT"           VARCHAR2(100) NULL,
 "VER_RESULT_QFR_CODE"       VARCHAR2(100) NULL,
 "VER_RESULT_QFR"            VARCHAR2(100) NULL,
 "VER_METH_ID_CODE"          VARCHAR2(100) NULL,
 "VER_METH"                  VARCHAR2(100) NULL,
 "VER_METH_DESCN_TXT"        VARCHAR2(100) NULL,
 "VER_METH_DEV_TXT"          VARCHAR2(100) NULL,
 "GEO_REF_DATUM_CD"          VARCHAR2(100) NULL,
 "GEO_REF_DATUM_NM"          VARCHAR2(100) NULL,
 "VERIF_METH_ID"             VARCHAR2(100) NULL,
 "VERIF_METH"                VARCHAR2(100) NULL,
 "VERIF_METH_DESC"           VARCHAR2(100) NULL,
 "VERIF_METH_DEV"            VARCHAR2(100) NULL,
 "COORD_DATA_SRC_CODE"       VARCHAR2(100) NULL,
 "COORD_DATA_SRC"            VARCHAR2(100) NULL,
 "GEOMETRIC_TYPE_CODE"       VARCHAR2(100) NULL,
 "GEOMETRIC_TYPE"            VARCHAR2(100) NULL,
 "LAT_DEGREE_ME"             VARCHAR2(100) NULL,
 "LAT_MINUTE_ME"             VARCHAR2(100) NULL,
 "LAT_SECOND_ME"             VARCHAR2(100) NULL,
 "LON_DEGREE_ME"             VARCHAR2(100) NULL,
 "LON_MINUTE_ME"             VARCHAR2(100) NULL,
 "LON_SECOND_ME"             VARCHAR2(100) NULL,
 "PARENT_COMPANY_TXT"        VARCHAR2(100) NULL,
 "PARENT_DUN_CODE"           VARCHAR2(100) NULL,
 "FACILITY_ACCESS_CODE"      VARCHAR2(100) NULL,
 "PRI_YR_TECH_CONTACT_NAME"  VARCHAR2(100) NULL,
 "PRI_YR_TECH_CONTACT_PHONE" VARCHAR2(100) NULL,
 "PARENT_COMPANY_NAME_N_S"   CHAR(1) NULL 
 );

CREATE TABLE "TRI_NPDES_ID" ( 
 "PK_GUID"        VARCHAR2(36) NOT NULL,
 "FK_GUID"        VARCHAR2(36) NOT NULL,
 "NPDES_ID_CLBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_OFFSITE_DISP_QTY" ( 
 "PK_GUID"                   VARCHAR2(36) NOT NULL,
 "FK_GUID"                   VARCHAR2(36) NOT NULL,
 "YEAR_OFFSET_ME"            VARCHAR2(100) NULL,
 "TOTAL_Q"                   VARCHAR2(100) NULL,
 "TOTAL_Q_NA_IND"            CHAR(1) NULL,
 "TOX_EQ_VAL1"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"              VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"             CHAR(1) NULL,
 "CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_OFFSITE_ENERGY_REC_QTY" ( 
 "PK_GUID"                   VARCHAR2(36) NOT NULL,
 "FK_GUID"                   VARCHAR2(36) NOT NULL,
 "YEAR_OFFSET_ME"            VARCHAR2(100) NULL,
 "TOTAL_Q"                   VARCHAR2(100) NULL,
 "TOTAL_Q_NA_IND"            CHAR(1) NULL,
 "TOX_EQ_VAL1"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"              VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"             CHAR(1) NULL,
 "CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_OFFSITE_RECYCLED_Q" ( 
 "PK_GUID"                   VARCHAR2(36) NOT NULL,
 "FK_GUID"                   VARCHAR2(36) NOT NULL,
 "YEAR_OFFSET_ME"            VARCHAR2(100) NULL,
 "TOTAL_Q"                   VARCHAR2(100) NULL,
 "TOTAL_Q_NA_IND"            CHAR(1) NULL,
 "TOX_EQ_VAL1"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"              VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"             CHAR(1) NULL,
 "CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_OFFSITE_TREATED_Q" ( 
 "PK_GUID"                   VARCHAR2(36) NOT NULL,
 "FK_GUID"                   VARCHAR2(36) NOT NULL,
 "YEAR_OFFSET_ME"            VARCHAR2(100) NULL,
 "TOTAL_Q"                   VARCHAR2(100) NULL,
 "TOTAL_Q_NA_IND"            CHAR(1) NULL,
 "TOX_EQ_VAL1"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"              VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"             CHAR(1) NULL,
 "CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_OFFSITE_UIC_DISP_QTY" ( 
 "PK_GUID"                   VARCHAR2(36) NOT NULL,
 "FK_GUID"                   VARCHAR2(36) NOT NULL,
 "YEAR_OFFSET_ME"            VARCHAR2(100) NULL,
 "TOTAL_Q"                   VARCHAR2(100) NULL,
 "TOTAL_Q_NA_IND"            CHAR(1) NULL,
 "TOX_EQ_VAL1"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"              VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"             CHAR(1) NULL,
 "CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_ONSITE_DISP_QTY" ( 
 "PK_GUID"                   VARCHAR2(36) NOT NULL,
 "FK_GUID"                   VARCHAR2(36) NOT NULL,
 "YEAR_OFFSET_ME"            VARCHAR2(100) NULL,
 "TOTAL_Q"                   VARCHAR2(100) NULL,
 "TOTAL_Q_NA_IND"            CHAR(1) NULL,
 "TOX_EQ_VAL1"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"              VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"             CHAR(1) NULL,
 "CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_ONSITE_ENERGY_RCV_QTY" ( 
 "PK_GUID"                   VARCHAR2(36) NOT NULL,
 "FK_GUID"                   VARCHAR2(36) NOT NULL,
 "YEAR_OFFSET_ME"            VARCHAR2(100) NULL,
 "TOTAL_Q"                   VARCHAR2(100) NULL,
 "TOTAL_Q_NA_IND"            CHAR(1) NULL,
 "TOX_EQ_VAL1"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"              VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"             CHAR(1) NULL,
 "CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_ONSITE_RCV_PROC" ( 
 "PK_GUID"              VARCHAR2(36) NOT NULL,
 "FK_GUID"              VARCHAR2(36) NOT NULL,
 "ENERGY_RCV_METH_CODE" VARCHAR2(100) NULL,
 "ENERGY_RCV_NA_IND"    CHAR(1) NULL 
 );

CREATE TABLE "TRI_ONSITE_RECYCG_PROC" ( 
 "PK_GUID"                 VARCHAR2(36) NOT NULL,
 "FK_GUID"                 VARCHAR2(36) NOT NULL,
 "ONSITE_RECYCG_METH_CODE" VARCHAR2(100) NULL,
 "ONSITE_RECYCG_NA_IND"    CHAR(1) NULL 
 );

CREATE TABLE "TRI_ONSITE_RECYCLED_Q" ( 
 "PK_GUID"                   VARCHAR2(36) NOT NULL,
 "FK_GUID"                   VARCHAR2(36) NOT NULL,
 "YEAR_OFFSET_ME"            VARCHAR2(100) NULL,
 "TOTAL_Q"                   VARCHAR2(100) NULL,
 "TOTAL_Q_NA_IND"            CHAR(1) NULL,
 "TOX_EQ_VAL1"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"              VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"             CHAR(1) NULL,
 "CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_ONSITE_RELEASE_Q" ( 
 "PK_GUID"                       VARCHAR2(36) NOT NULL,
 "FK_GUID"                       VARCHAR2(36) NOT NULL,
 "EI_MEDIUM_CODE"                VARCHAR2(100) NULL,
 "WASTE_Q_ME"                    VARCHAR2(100) NULL,
 "WASTE_Q_NA_IND"                CHAR(1) NULL,
 "WASTE_Q_RANGE_CODE"            VARCHAR2(100) NULL,
 "Q_BASIS_EST_CD"                VARCHAR2(100) NULL,
 "Q_BASIS_NA_IND"                CHAR(1) NULL,
 "WATER_SEQ_CLBER"               VARCHAR2(100) NULL,
 "STREAM"                        VARCHAR2(100) NULL,
 "RELEASE_STORM_WATER"           VARCHAR2(100) NULL,
 "RELEASE_STORM_NA_IND"          CHAR(1) NULL,
 "TOX_EQ_VAL1"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"                  VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"                 CHAR(1) NULL,
 "WASTE_Q_CATASTROPHIC_MEASURE"  VARCHAR2(100) NULL,
 "WASTE_Q_RANGE_NUM_BASIS_VALUE" VARCHAR2(100) NULL,
 "STREAM_REACH_CODE"             VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_ONSITE_TREATED_Q" ( 
 "PK_GUID"                   VARCHAR2(36) NOT NULL,
 "FK_GUID"                   VARCHAR2(36) NOT NULL,
 "YEAR_OFFSET_ME"            VARCHAR2(100) NULL,
 "TOTAL_Q"                   VARCHAR2(100) NULL,
 "TOTAL_Q_NA_IND"            CHAR(1) NULL,
 "TOX_EQ_VAL1"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"              VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"             CHAR(1) NULL,
 "CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_ONSITE_UIC_DISP_QTY" ( 
 "PK_GUID"                   VARCHAR2(36) NOT NULL,
 "FK_GUID"                   VARCHAR2(36) NULL,
 "YEAR_OFFSET_ME"            VARCHAR2(100) NULL,
 "TOTAL_Q"                   VARCHAR2(100) NULL,
 "TOTAL_Q_NA_IND"            CHAR(1) NULL,
 "TOX_EQ_VAL1"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"              VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"              VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"             CHAR(1) NULL,
 "CALC_ROUNDING_HINT_NUMBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_POTW_WASTE_QUANTITY" ( 
 "PK_GUID"                       VARCHAR2(36) NOT NULL,
 "FK_GUID"                       VARCHAR2(36) NOT NULL,
 "POTW_SEQ_NO"                   VARCHAR2(100) NULL,
 "WASTE_Q_ME"                    VARCHAR2(100) NULL,
 "WASTE_Q_CATASTROPHIC_MEASURE"  VARCHAR2(100) NULL,
 "WASTE_Q_RANGE_CODE"            VARCHAR2(100) NULL,
 "WASTE_Q_RANGE_NUM_BASIS_VALUE" VARCHAR2(100) NULL,
 "WASTE_Q_ME_NA_IND"             CHAR(1) NULL,
 "Q_BASIS_EST_CODE"              VARCHAR2(100) NULL,
 "Q_BASIS_EST_NA_IND"            CHAR(1) NULL,
 "TOX_EQ_VAL1"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"                  VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"                 CHAR(1) NULL,
 "Q_DISP_LANDFILL_PERCENT_VALUE" VARCHAR2(100) NULL,
 "Q_DISP_OTHER_PERCENT_VALUE"    VARCHAR2(100) NULL,
 "Q_TREATED_PERCENT_VALUE"       VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_RCRA_ID" ( 
 "PK_GUID"       VARCHAR2(36) NOT NULL,
 "FK_GUID"       VARCHAR2(36) NOT NULL,
 "RCRA_ID_CLBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_REPLACED_REPORT_ID" ( 
 "PK_GUID"            VARCHAR2(36) NOT NULL,
 "FK_GUID"            VARCHAR2(36) NOT NULL,
 "REPLACED_REPORT_ID" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_REPORT_VALIDATION" ( 
 "PK_GUID"                     VARCHAR2(36) NOT NULL,
 "FK_GUID"                     VARCHAR2(36) NOT NULL,
 "VALIDATION_ENTITY_NAME_TEXT" VARCHAR2(100) NULL,
 "VALIDATION_MESSAGE_CODE"     VARCHAR2(100) NULL,
 "VALIDATION_MESSAGE_TEXT"     VARCHAR2(100) NULL,
 "EPA_ERROR_SEVERITY_CODE"     VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_REPORT" ( 
 "PK_GUID"                        VARCHAR2(36) NOT NULL,
 "FK_GUID"                        VARCHAR2(36) NOT NULL,
 "REPORT_ID"                      VARCHAR2(100) NULL,
 "REPORT_POST_DATE"               VARCHAR2(50) NULL,
 "REPORT_REC_DATE"                VARCHAR2(50) NULL,
 "REPORT_ORIG_POST_DATE"          VARCHAR2(50) NULL,
 "REPORT_ORIG_REC_DATE"           VARCHAR2(50) NULL,
 "REPORT_SUB_METH_CODE"           VARCHAR2(100) NULL,
 "REPORT_EPA_PASSED_VALID_IND"    CHAR(1) NULL,
 "REPORT_EPA_PROCESSING_STATUS_C" VARCHAR2(100) NULL,
 "UNALTERED_REPORT_IND"           VARCHAR2(100) NULL,
 "REPORT_TYPE_CODE"               VARCHAR2(100) NULL,
 "SUB_REP_YEAR"                   VARCHAR2(100) NULL,
 "REPORT_DUE_DATE"                VARCHAR2(50) NULL,
 "REVISION_IND"                   VARCHAR2(100) NULL,
 "CHEM_TRADE_SECRET_IND"          VARCHAR2(100) NULL,
 "SUB_SANITIZED_IND"              VARCHAR2(100) NULL,
 "CERTIFIER"                      VARCHAR2(100) NULL,
 "CERTIFIER_TIT_TXT"              VARCHAR2(100) NULL,
 "CERT_SIGNED_DATE"               VARCHAR2(100) NULL,
 "SUB_ENTIRE_FAC_IND"             VARCHAR2(100) NULL,
 "SUB_PARTIAL_FAC_ID"             VARCHAR2(100) NULL,
 "SUB_FEDERAL_FAC_ID"             VARCHAR2(100) NULL,
 "SUB_CO_FAC_INDIC"               VARCHAR2(100) NULL,
 "TECH_CONT"                      VARCHAR2(100) NULL,
 "TECH_CONT_PHONE_TXT"            VARCHAR2(100) NULL,
 "TECH_CONT_EMAIL_ADDRES"         VARCHAR2(100) NULL,
 "PUB_CONT_ID"                    VARCHAR2(100) NULL,
 "PUB_CONT_TIT_TXT"               VARCHAR2(100) NULL,
 "PUB_CONT"                       VARCHAR2(100) NULL,
 "PUB_CONT_PHONE_TXT"             VARCHAR2(50) NULL,
 "CHEM_ANC_USAGE_IND"             VARCHAR2(100) NULL,
 "CHEM_ARTICLE_COMP_ID"           VARCHAR2(100) NULL,
 "CHEM_BYPRODUCT_IND"             VARCHAR2(100) NULL,
 "CHEM_FORMULATION_COMP"          VARCHAR2(100) NULL,
 "CHEM_IMPORTED_IND"              VARCHAR2(100) NULL,
 "CHEM_MANUFACTURE_AID_ID"        VARCHAR2(100) NULL,
 "CHEM_MANUFACTURE_IMPURITY"      VARCHAR2(100) NULL,
 "CHEM_PROC_IMPURITY_ID"          VARCHAR2(100) NULL,
 "CHEM_PROCING_AID_ID"            VARCHAR2(100) NULL,
 "CHEM_PRODUCED_IND"              VARCHAR2(100) NULL,
 "CHEM_REACTANT_IND"              VARCHAR2(100) NULL,
 "CHEM_REP_IND"                   VARCHAR2(100) NULL,
 "CHEM_SALES_DIST_ID"             VARCHAR2(100) NULL,
 "CHEM_USED_PROCED_ID"            VARCHAR2(100) NULL,
 "MAX_CHEM_AMOUNT_CODE"           VARCHAR2(100) NULL,
 "ONE_TIME_RELEASE_Q"             VARCHAR2(100) NULL,
 "ONE_TIME_NA_IND"                CHAR(1) NULL,
 "PRODUCTION_RATIO_ME"            VARCHAR2(100) NULL,
 "PRODUCTION_RATIO_NA_IND"        CHAR(1) NULL,
 "SUB_ADDITIONAL_DATA_ID"         VARCHAR2(100) NULL,
 "OPT_INF_TXT"                    VARCHAR2(4000) NULL,
 "PUB_CONT_EMAIL_ADDRES"          VARCHAR2(100) NULL,
 "CHEM_RPT_REV_CD_1"              VARCHAR2(100) NULL,
 "CHEM_RPT_REV_CD_2"              VARCHAR2(100) NULL,
 "CHEM_RPT_WD_CD_1"               VARCHAR2(100) NULL,
 "CHEM_RPT_WD_CD_2"               VARCHAR2(100) NULL,
 "TOX_EQ_VAL1_ONETIME"            VARCHAR2(100) NULL,
 "TOX_EQ_VAL2_ONETIME"            VARCHAR2(100) NULL,
 "TOX_EQ_VAL3_ONETIME"            VARCHAR2(100) NULL,
 "TOX_EQ_VAL4_ONETIME"            VARCHAR2(100) NULL,
 "TOX_EQ_VAL5_ONETIME"            VARCHAR2(100) NULL,
 "TOX_EQ_VAL6_ONETIME"            VARCHAR2(100) NULL,
 "TOX_EQ_VAL7_ONETIME"            VARCHAR2(100) NULL,
 "TOX_EQ_VAL8_ONETIME"            VARCHAR2(100) NULL,
 "TOX_EQ_VAL9_ONETIME"            VARCHAR2(100) NULL,
 "TOX_EQ_VAL10_ONETIME"           VARCHAR2(100) NULL,
 "TOX_EQ_VAL11_ONETIME"           VARCHAR2(100) NULL,
 "TOX_EQ_VAL12_ONETIME"           VARCHAR2(100) NULL,
 "TOX_EQ_VAL13_ONETIME"           VARCHAR2(100) NULL,
 "TOX_EQ_VAL14_ONETIME"           VARCHAR2(100) NULL,
 "TOX_EQ_VAL15_ONETIME"           VARCHAR2(100) NULL,
 "TOX_EQ_VAL16_ONETIME"           VARCHAR2(100) NULL,
 "TOX_EQ_VAL17_ONETIME"           VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND_ONETIME"          CHAR(1) NULL,
 "CALC_ROUNDING_HINT_NUMBER"      VARCHAR2(100) NULL,
 "MISC_INF_TXT"                   VARCHAR2(4000) NULL,
 "TECH_CONT_PHONE_EXT_TXT"        VARCHAR2(100) NULL,
 "PUB_CONT_PHONE_EXT_TXT"         VARCHAR2(100) NULL,
 "OPT_INF_CATG"                   VARCHAR2(100) NULL,
 "MISC_INF_CATG"                  VARCHAR2(100) NULL,
 "PRODUCTION_RATIO_TYPE"          VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_SRC_RED_ACT" ( 
 "PK_GUID"          VARCHAR2(36) NOT NULL,
 "FK_GUID"          VARCHAR2(36) NOT NULL,
 "SRC_RED_SEQ_CL"   VARCHAR2(100) NULL,
 "SRC_RED_ACT_CODE" VARCHAR2(100) NULL,
 "SRC_RED_NA_IND"   CHAR(1) NULL,
 "SRC_RED_EFF_CODE" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_SRC_RED_METH_CD" ( 
 "PK_GUID"           VARCHAR2(36) NOT NULL,
 "FK_GUID"           VARCHAR2(36) NOT NULL,
 "SRC_RED_METH_CODE" VARCHAR2(100) NULL,
 "SRC_RED_NA_IND"    CHAR(1) NULL 
 );

CREATE TABLE "TRI_SUB" ( 
 "PK_GUID"        VARCHAR2(36) NOT NULL,
 "TRI_SUB_ID"     VARCHAR2(255) NOT NULL,
 "INSERTED_DATE"  DATE DEFAULT SYSDATE NOT NULL,
 "TRANSACTION_ID" VARCHAR2(50) NOT NULL 
 );

CREATE TABLE "TRI_TRANSFER_LOC" ( 
 "PK_GUID"             VARCHAR2(36) NOT NULL,
 "FK_GUID"             VARCHAR2(36) NOT NULL,
 "TRANSFER_LOC_SEQ_CL" VARCHAR2(100) NULL,
 "POTW_IND"            VARCHAR2(100) NULL,
 "FAC_SITE"            VARCHAR2(100) NULL,
 "LOC_ADD_TXT"         VARCHAR2(100) NULL,
 "SUPP_LOC_TXT"        VARCHAR2(100) NULL,
 "LOCALITY"            VARCHAR2(100) NULL,
 "STATE"               VARCHAR2(100) NULL,
 "ADD_POSTAL_CODE"     VARCHAR2(100) NULL,
 "COUNTY"              VARCHAR2(100) NULL,
 "CONTROLLED_LOC_IND"  VARCHAR2(100) NULL,
 "RCRA_ID_CLBER"       VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_TRANSFER_Q" ( 
 "PK_GUID"                       VARCHAR2(36) NOT NULL,
 "FK_GUID"                       VARCHAR2(36) NOT NULL,
 "TRANSFER_SEQ_CLBER"            VARCHAR2(100) NULL,
 "WASTE_Q_ME"                    VARCHAR2(100) NULL,
 "WASTE_Q_RANGE_CODE"            VARCHAR2(100) NULL,
 "WASTE_Q_NA_IND"                CHAR(1) NULL,
 "Q_BASIS_EST_CODE"              VARCHAR2(100) NULL,
 "Q_BASIS_EST_NA_IND"            CHAR(1) NULL,
 "WASTE_MANAGEMENT_CODE"         VARCHAR2(100) NULL,
 "TOX_EQ_VAL1"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL2"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL3"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL4"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL5"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL6"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL7"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL8"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL9"                   VARCHAR2(100) NULL,
 "TOX_EQ_VAL10"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL11"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL12"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL13"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL14"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL15"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL16"                  VARCHAR2(100) NULL,
 "TOX_EQ_VAL17"                  VARCHAR2(100) NULL,
 "TOX_EQ_NA_IND"                 CHAR(1) NULL,
 "WASTE_Q_CATASTROPHIC_MEASURE"  VARCHAR2(100) NULL,
 "WASTE_Q_RANGE_NUM_BASIS_VALUE" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_UIC_ID" ( 
 "PK_GUID"      VARCHAR2(36) NOT NULL,
 "FK_GUID"      VARCHAR2(36) NOT NULL,
 "UIC_ID_CLBER" VARCHAR2(100) NULL 
 );

CREATE TABLE "TRI_WASTE_TREAT_DTL" ( 
 "PK_GUID"                VARCHAR2(36) NOT NULL,
 "FK_GUID"                VARCHAR2(36) NOT NULL,
 "WASTE_STREAM_SEQ_CLBER" VARCHAR2(100) NULL,
 "WASTE_STREAM_TYPE_CODE" VARCHAR2(100) NULL,
 "INFLUENT_CONC_RANGE_C"  VARCHAR2(100) NULL,
 "TREAT_EFF_EST_PCT"      VARCHAR2(100) NULL,
 "TREAT_EFF_RANGE_CD"     VARCHAR2(100) NULL,
 "TREAT_EFF_NA_IND"       CHAR(1) NULL,
 "OPERATING_DATA_IND"     VARCHAR2(100) NULL,
 "WASTE_TREAT_NA_IND"     CHAR(1) NULL 
 );

CREATE TABLE "TRI_WASTE_TREAT_METH" ( 
 "PK_GUID"               VARCHAR2(36) NOT NULL,
 "FK_GUID"               VARCHAR2(36) NOT NULL,
 "WASTE_TREAT_SEQ_CL"    VARCHAR2(100) NULL,
 "WASTE_TREAT_METH_CODE" VARCHAR2(100) NULL 
 );

CREATE SEQUENCE "ID_SEQ"
 INCREMENT BY 1
 START WITH 1
 MAXVALUE 9999999999999999999999999999
 NOMINVALUE
 NOCYCLE
 CACHE 20
 NOORDER;


CREATE UNIQUE INDEX "PK_TRI_CHEM"
 ON "TRI_CHEM"("PK_GUID");

CREATE INDEX "IX_TRI_CHEM_FK_GUID"
 ON "TRI_CHEM"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_COMMENT"
 ON "TRI_COMMENT"("PK_GUID");

CREATE INDEX "IX_TRI_COMMENT_FK_GUID"
 ON "TRI_COMMENT"("FK_GUID");

CREATE INDEX "IX_TRI_FAC_DUN"
 ON "TRI_FAC_DUN"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_FAC_DUN"
 ON "TRI_FAC_DUN"("PK_GUID");

CREATE UNIQUE INDEX "PK_TRI_FAC_NAICS"
 ON "TRI_FAC_NAICS"("PK_GUID");

CREATE INDEX "IX_TRI_FAC_NAICS"
 ON "TRI_FAC_NAICS"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_FAC_SIC"
 ON "TRI_FAC_SIC"("PK_GUID");

CREATE INDEX "IX_TRI_FAC_SIC_FK_GUID"
 ON "TRI_FAC_SIC"("FK_GUID");

CREATE INDEX "IX_TRI_FAC_FK_GUID"
 ON "TRI_FAC"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_FAC"
 ON "TRI_FAC"("PK_GUID");

CREATE INDEX "IX_TRI_FAC_FAC_ID"
 ON "TRI_FAC"("FAC_ID");

CREATE INDEX "IX_TRI_NPDES_ID"
 ON "TRI_NPDES_ID"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_NPDES_ID"
 ON "TRI_NPDES_ID"("PK_GUID");

CREATE INDEX "IX_TRI_OFF_DISP_QTY_FK_GUID"
 ON "TRI_OFFSITE_DISP_QTY"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_OFFSITE_DISP_QTY"
 ON "TRI_OFFSITE_DISP_QTY"("PK_GUID");

CREATE INDEX "IX_TRI_OFF_EGY_REC_QTY_FK_GUID"
 ON "TRI_OFFSITE_ENERGY_REC_QTY"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_OFFSITE_ENERGY_REC_QTY"
 ON "TRI_OFFSITE_ENERGY_REC_QTY"("PK_GUID");

CREATE INDEX "IX_TRI_OFFSITE_RECYCLED_Q"
 ON "TRI_OFFSITE_RECYCLED_Q"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_OFFSITE_RECYCLED_Q"
 ON "TRI_OFFSITE_RECYCLED_Q"("PK_GUID");

CREATE INDEX "IX_TRI_OFF_TREATED_Q_FK_GUID"
 ON "TRI_OFFSITE_TREATED_Q"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_OFFSITE_TREATED_Q"
 ON "TRI_OFFSITE_TREATED_Q"("PK_GUID");

CREATE UNIQUE INDEX "PK_TRI_OFFSITE_UIC_DISP_QTY"
 ON "TRI_OFFSITE_UIC_DISP_QTY"("PK_GUID");

CREATE INDEX "IX_TRI_OFFSITE_UIC_DISP_QTY"
 ON "TRI_OFFSITE_UIC_DISP_QTY"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_ONSITE_DISP_QTY"
 ON "TRI_ONSITE_DISP_QTY"("PK_GUID");

CREATE INDEX "IX_TRI_ON_DIS_QTY_FK_GUID"
 ON "TRI_ONSITE_DISP_QTY"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_ONSITE_ENERGY_RCV_QTY"
 ON "TRI_ONSITE_ENERGY_RCV_QTY"("PK_GUID");

CREATE INDEX "IX_TRI_ON_EGY_RCV_QTY_FK_GUID"
 ON "TRI_ONSITE_ENERGY_RCV_QTY"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_ONSITE_RCV_PROC"
 ON "TRI_ONSITE_RCV_PROC"("PK_GUID");

CREATE INDEX "IX_TRI_ONSITE_RCV_PROC_FK_GUID"
 ON "TRI_ONSITE_RCV_PROC"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_ONSITE_RECYCG_PROC"
 ON "TRI_ONSITE_RECYCG_PROC"("PK_GUID");

CREATE INDEX "IX_TRI_ON_RECYCG_PROC_FK_GUID"
 ON "TRI_ONSITE_RECYCG_PROC"("FK_GUID");

CREATE INDEX "IX_TRI_ONSITE_RECYCLED_Q"
 ON "TRI_ONSITE_RECYCLED_Q"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_ONSITE_RECYCLED_Q"
 ON "TRI_ONSITE_RECYCLED_Q"("PK_GUID");

CREATE INDEX "IX_TRI_ON_RELEASE_Q_FK_GUID"
 ON "TRI_ONSITE_RELEASE_Q"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_ONSITE_RELEASE_Q"
 ON "TRI_ONSITE_RELEASE_Q"("PK_GUID");

CREATE UNIQUE INDEX "PK_TRI_ONSITE_TREATED_Q"
 ON "TRI_ONSITE_TREATED_Q"("PK_GUID");

CREATE INDEX "IX_TRI_ON_TREATED_Q_FK_GUID"
 ON "TRI_ONSITE_TREATED_Q"("FK_GUID");

CREATE INDEX "IX_TRI_ONSITE_UIC_DISP_QTY"
 ON "TRI_ONSITE_UIC_DISP_QTY"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_ONSITE_UIC_DISP_QTY"
 ON "TRI_ONSITE_UIC_DISP_QTY"("PK_GUID");

CREATE UNIQUE INDEX "PK_TRI_POTW_WASTE_QUANTITY"
 ON "TRI_POTW_WASTE_QUANTITY"("PK_GUID");

CREATE INDEX "IX_TRI_RCRA_ID"
 ON "TRI_RCRA_ID"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_RCRA_ID"
 ON "TRI_RCRA_ID"("PK_GUID");

CREATE UNIQUE INDEX "PK_TRI_REPLACED_REPORT_ID"
 ON "TRI_REPLACED_REPORT_ID"("PK_GUID");

CREATE INDEX "IX_TRI_REPLACED_REPORT_ID"
 ON "TRI_REPLACED_REPORT_ID"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_REPORT_VALIDATION"
 ON "TRI_REPORT_VALIDATION"("PK_GUID");

CREATE INDEX "IX_TRI_REPORT_VALIDATION"
 ON "TRI_REPORT_VALIDATION"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_REPORT"
 ON "TRI_REPORT"("PK_GUID");

CREATE INDEX "IX_TRI_REPORT"
 ON "TRI_REPORT"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_SRC_RED_ACT"
 ON "TRI_SRC_RED_ACT"("PK_GUID");

CREATE INDEX "IX_TRI_SRC_RED_ACT"
 ON "TRI_SRC_RED_ACT"("FK_GUID");

CREATE INDEX "IX_TRI_SRC_RED_METH_CD_FK_GUID"
 ON "TRI_SRC_RED_METH_CD"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_SRC_RED_METH_CD"
 ON "TRI_SRC_RED_METH_CD"("PK_GUID");

CREATE UNIQUE INDEX "PK_TRI_SUB"
 ON "TRI_SUB"("PK_GUID");

CREATE UNIQUE INDEX "UK_TRI_SUB"
 ON "TRI_SUB"("TRI_SUB_ID");

CREATE INDEX "IX_TRI_TRANSFER_LOC_FK_GUID"
 ON "TRI_TRANSFER_LOC"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_TRANSFER_LOC"
 ON "TRI_TRANSFER_LOC"("PK_GUID");

CREATE UNIQUE INDEX "PK_TRI_TRANSFER_Q"
 ON "TRI_TRANSFER_Q"("PK_GUID");

CREATE INDEX "IX_TRI_TRANSFER_Q_FK_GUID"
 ON "TRI_TRANSFER_Q"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_UIC_ID"
 ON "TRI_UIC_ID"("PK_GUID");

CREATE INDEX "IX_TRI_UIC_ID_FK_GUID"
 ON "TRI_UIC_ID"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_WASTE_TREAT_DTL"
 ON "TRI_WASTE_TREAT_DTL"("PK_GUID");

CREATE INDEX "IX_TRI_WASTE_TREAT_DTL"
 ON "TRI_WASTE_TREAT_DTL"("FK_GUID");

CREATE INDEX "IX_TRI_WST_TRT_METH_FK_GUID"
 ON "TRI_WASTE_TREAT_METH"("FK_GUID");

CREATE UNIQUE INDEX "PK_TRI_WASTE_TREAT_METH"
 ON "TRI_WASTE_TREAT_METH"("PK_GUID");

ALTER TABLE "TRI_CHEM"
 ADD ( CONSTRAINT "PK_TRI_CHEM"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_COMMENT"
 ADD ( CONSTRAINT "PK_TRI_COMMENT"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_FAC_DUN"
 ADD ( CONSTRAINT "PK_TRI_FAC_DUN"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_FAC_NAICS"
 ADD ( CONSTRAINT "PK_TRI_FAC_NAICS"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_FAC_SIC"
 ADD ( CONSTRAINT "PK_TRI_FAC_SIC"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_FAC"
 ADD ( CONSTRAINT "PK_TRI_FAC"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_NPDES_ID"
 ADD ( CONSTRAINT "PK_TRI_NPDES_ID"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_OFFSITE_DISP_QTY"
 ADD ( CONSTRAINT "PK_TRI_OFFSITE_DISP_QTY"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_OFFSITE_ENERGY_REC_QTY"
 ADD ( CONSTRAINT "PK_TRI_OFFSITE_ENERGY_REC_QTY"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_OFFSITE_RECYCLED_Q"
 ADD ( CONSTRAINT "PK_TRI_OFFSITE_RECYCLED_Q"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_OFFSITE_TREATED_Q"
 ADD ( CONSTRAINT "PK_TRI_OFFSITE_TREATED_Q"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_OFFSITE_UIC_DISP_QTY"
 ADD ( CONSTRAINT "PK_TRI_OFFSITE_UIC_DISP_QTY"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_ONSITE_DISP_QTY"
 ADD ( CONSTRAINT "PK_TRI_ONSITE_DISP_QTY"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_ONSITE_ENERGY_RCV_QTY"
 ADD ( CONSTRAINT "PK_TRI_ONSITE_ENERGY_RCV_QTY"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_ONSITE_RCV_PROC"
 ADD ( CONSTRAINT "PK_TRI_ONSITE_RCV_PROC"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_ONSITE_RECYCG_PROC"
 ADD ( CONSTRAINT "PK_TRI_ONSITE_RECYCG_PROC"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_ONSITE_RECYCLED_Q"
 ADD ( CONSTRAINT "PK_TRI_ONSITE_RECYCLED_Q"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_ONSITE_RELEASE_Q"
 ADD ( CONSTRAINT "PK_TRI_ONSITE_RELEASE_Q"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_ONSITE_TREATED_Q"
 ADD ( CONSTRAINT "PK_TRI_ONSITE_TREATED_Q"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_ONSITE_UIC_DISP_QTY"
 ADD ( CONSTRAINT "PK_TRI_ONSITE_UIC_DISP_QTY"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_POTW_WASTE_QUANTITY"
 ADD ( CONSTRAINT "PK_TRI_POTW_WASTE_QUANTITY"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_RCRA_ID"
 ADD ( CONSTRAINT "PK_TRI_RCRA_ID"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_REPLACED_REPORT_ID"
 ADD ( CONSTRAINT "PK_TRI_REPLACED_REPORT_ID"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_REPORT_VALIDATION"
 ADD ( CONSTRAINT "PK_TRI_REPORT_VALIDATION"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_REPORT"
 ADD ( CONSTRAINT "PK_TRI_REPORT"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_SRC_RED_ACT"
 ADD ( CONSTRAINT "PK_TRI_SRC_RED_ACT"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_SRC_RED_METH_CD"
 ADD ( CONSTRAINT "PK_TRI_SRC_RED_METH_CD"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_SUB"
 ADD ( CONSTRAINT "PK_TRI_SUB"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_TRANSFER_LOC"
 ADD ( CONSTRAINT "PK_TRI_TRANSFER_LOC"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_TRANSFER_Q"
 ADD ( CONSTRAINT "PK_TRI_TRANSFER_Q"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_UIC_ID"
 ADD ( CONSTRAINT "PK_TRI_UIC_ID"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_WASTE_TREAT_DTL"
 ADD ( CONSTRAINT "PK_TRI_WASTE_TREAT_DTL"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_WASTE_TREAT_METH"
 ADD ( CONSTRAINT "PK_TRI_WASTE_TREAT_METH"
 PRIMARY KEY ("PK_GUID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_SUB"
 ADD ( CONSTRAINT "UK_TRI_SUB"
 UNIQUE ("TRI_SUB_ID")
 NOT DEFERRABLE INITIALLY IMMEDIATE );

ALTER TABLE "TRI_CHEM"
 ADD ( CONSTRAINT "FK_CHEM_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_COMMENT"
 ADD ( CONSTRAINT "FK_COMMENT_REP"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_FAC_DUN"
 ADD ( CONSTRAINT "FK_FACDUN_FAC"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_FAC("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_FAC_NAICS"
 ADD ( CONSTRAINT "FK_FACNAICS_FAC"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_FAC("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_FAC_SIC"
 ADD ( CONSTRAINT "FK_FACSIC_FAC"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_FAC("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_FAC"
 ADD ( CONSTRAINT "FK_FAC_SUB"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_SUB("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_NPDES_ID"
 ADD ( CONSTRAINT "FK_NPDESID_FAC"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_FAC("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_OFFSITE_DISP_QTY"
 ADD ( CONSTRAINT "FK_OFFSITEDISPQTY_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_OFFSITE_ENERGY_REC_QTY"
 ADD ( CONSTRAINT "FK_OFFSITEENERGYRECQTY_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_OFFSITE_RECYCLED_Q"
 ADD ( CONSTRAINT "FK_OFFSITERECYCLEDQ_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_OFFSITE_TREATED_Q"
 ADD ( CONSTRAINT "FK_OFFSITETREATEDQ_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_OFFSITE_UIC_DISP_QTY"
 ADD ( CONSTRAINT "FK_OFFSITEUICDISPQTY_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_ONSITE_DISP_QTY"
 ADD ( CONSTRAINT "FK_ONSITEDISPQTY_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_ONSITE_ENERGY_RCV_QTY"
 ADD ( CONSTRAINT "FK_ONSITEENERGYRCVQTY_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_ONSITE_RCV_PROC"
 ADD ( CONSTRAINT "FK_ONSITERCVPROC_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_ONSITE_RECYCG_PROC"
 ADD ( CONSTRAINT "FK_ONSITERECYCGPROC_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_ONSITE_RECYCLED_Q"
 ADD ( CONSTRAINT "FK_ONSITERECYCLEDQ_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_ONSITE_RELEASE_Q"
 ADD ( CONSTRAINT "FK_ONSITERELEASEQ_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_ONSITE_TREATED_Q"
 ADD ( CONSTRAINT "FK_ONSITETREATEDQ_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_ONSITE_UIC_DISP_QTY"
 ADD ( CONSTRAINT "FK_ONSITEUICDISPQTY_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_POTW_WASTE_QUANTITY"
 ADD ( CONSTRAINT "FK_TRI_RPT_POTW_WQ"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_RCRA_ID"
 ADD ( CONSTRAINT "FK_RCRAID_FAC"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_FAC("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_REPLACED_REPORT_ID"
 ADD ( CONSTRAINT "FK_REPLACEDREPORTID_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_REPORT_VALIDATION"
 ADD ( CONSTRAINT "FK_TRI_REPORT_VALIDATION_TRI_R"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_REPORT"
 ADD ( CONSTRAINT "FK_REPORT_SUB"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_SUB("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_SRC_RED_ACT"
 ADD ( CONSTRAINT "FK_SRCREDACT_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_SRC_RED_METH_CD"
 ADD ( CONSTRAINT "FK_SRCREDMETHCD_SRCREDACT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_SRC_RED_ACT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_TRANSFER_LOC"
 ADD ( CONSTRAINT "FK_TRANSFERLOC_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_TRANSFER_Q"
 ADD ( CONSTRAINT "FK_TRANSFERQ_TRANSFERLOC"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_TRANSFER_LOC("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_UIC_ID"
 ADD ( CONSTRAINT "FK_UICID_FAC"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_FAC("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_WASTE_TREAT_DTL"
 ADD ( CONSTRAINT "FK_WASTETREATDTL_REPORT"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_REPORT("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

ALTER TABLE "TRI_WASTE_TREAT_METH"
 ADD ( CONSTRAINT "FK_WASTETREATMETH_WTDTL"
 FOREIGN KEY("FK_GUID")
 REFERENCES TRI_WASTE_TREAT_DTL("PK_GUID")
 ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );

CREATE TRIGGER "TRI_SUB_BI" 
  BEFORE INSERT ON TRI_SUB 
  FOR EACH ROW
BEGIN 
  IF INSERTING THEN 
    IF :NEW.PK_GUID IS NULL THEN 
      SELECT ID_SEQ.NEXTVAL INTO :NEW.PK_GUID FROM dual; 
    END IF; 
  END IF; 
END;