/*
Copyright (c) 2016, The Environmental Council of the States (ECOS)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE ;ODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/

/*****************************************************************************************************************************
 *
 *  Script Name:  RCRA_5.10_to_5.12-upgrade_ORA-DDL.sql
 *
 *  Company:  Windsor Solutions, Inc.
 *
 *  Purpose:  This DDL script will alter the Oracle database objects supporting the RCRA v5.10 data flow to conform with
 *            the RCRA v5.12 schema.
 *
 *  Maintenance:
 *
 *    Analyst         Date            Comment
 *    ----------      ----------      ------------------------------------------------------------------------------
 *    Windsor         12/19/2022      Created
 *
 ****************************************************************************************************************************
 */
-- ALTER TABLE "RCRA_EM_HANDLER" DROP CONSTRAINT "FK_EM_HANDLER_EM_EMANIFEST";
-- ALTER TABLE "RCRA_EM_TR_NUM_ORIG" DROP CONSTRAINT "FK_EM_TR_NUM_ORIG_EM_EMANIFEST";
-- ALTER TABLE "RCRA_EM_TR_NUM_REJ" DROP CONSTRAINT "FK_EM_TR_NUM_REJ_EM_EMANIFEST";
-- ALTER TABLE "RCRA_EM_TR_NUM_RESIDUE_NEW" DROP CONSTRAINT "FK_EM_TR_NM_RSDUE_NW_EM_EMNFST";
-- ALTER TABLE "RCRA_EM_TR_NUM_WASTE" DROP CONSTRAINT "FK_EM_TR_NUM_WASTE_EM_WASTE";
-- ALTER TABLE "RCRA_EM_WASTE_CD_FED" DROP CONSTRAINT "FK_EM_WASTE_CD_FED_EM_WASTE";
-- ALTER TABLE "RCRA_EM_WASTE_CD_GEN" DROP CONSTRAINT "FK_EM_WASTE_CD_GEN_EM_WASTE";
-- ALTER TABLE "RCRA_EM_WASTE_CD_TSDF" DROP CONSTRAINT "FK_EM_WASTE_CD_TSDF_EM_WASTE";
-- ALTER TABLE "RCRA_EM_HANDLER" DROP CONSTRAINT "PK_EM_HANDLER";
-- ALTER TABLE "RCRA_EM_TR_NUM_ORIG" DROP CONSTRAINT "PK_EM_TR_NUM_ORIG";
-- ALTER TABLE "RCRA_EM_TR_NUM_REJ" DROP CONSTRAINT "PK_EM_TR_NUM_REJ";
-- ALTER TABLE "RCRA_EM_TR_NUM_RESIDUE_NEW" DROP CONSTRAINT "PK_EM_TR_NUM_RESIDUE_NEW";
-- ALTER TABLE "RCRA_EM_TR_NUM_WASTE" DROP CONSTRAINT "PK_EM_TR_NUM_WASTE";
-- ALTER TABLE "RCRA_EM_WASTE_CD_FED" DROP CONSTRAINT "PK_EM_WASTE_CD_FED";
-- ALTER TABLE "RCRA_EM_WASTE_CD_GEN" DROP CONSTRAINT "PK_EM_WASTE_CD_GEN";
-- ALTER TABLE "RCRA_EM_WASTE_CD_TSDF" DROP CONSTRAINT "PK_EM_WASTE_CD_TSDF";

-- DROP INDEX "IX_EM_HANDLER_EM_EMANIFEST_ID";
-- DROP INDEX "IX_EM_TR_NM_ORG_EM_EMNIFEST_ID";
-- DROP INDEX "IX_EM_TR_NUM_RJ_EM_EMNIFEST_ID";
-- DROP INDEX "IX_EM_TR_NM_RSDE_NW_EM_EMNF_ID";
-- DROP INDEX "IX_EM_TR_NUM_WASTE_EM_WASTE_ID";
-- DROP INDEX "IX_EM_WASTE_CD_FED_EM_WASTE_ID";
-- DROP INDEX "IX_EM_WASTE_CD_GEN_EM_WASTE_ID";
-- DROP INDEX "IX_EM_WASTE_CD_TSDF_EM_WSTE_ID";
DROP TABLE "RCRA_EM_WASTE_CD_TSDF";
DROP TABLE "RCRA_EM_WASTE_CD_GEN";
DROP TABLE "RCRA_EM_WASTE_CD_FED";
DROP TABLE "RCRA_EM_TR_NUM_WASTE";
DROP TABLE "RCRA_EM_TR_NUM_REJ";
DROP TABLE "RCRA_EM_TR_NUM_ORIG";
DROP TABLE "RCRA_EM_TR_NUM_RESIDUE_NEW";
DROP TABLE "RCRA_EM_HANDLER";

CREATE TABLE "RCRA_EM_FED_WASTE_CODE_DESC"
(
    "EM_FED_WASTE_CODE_DESC_ID" varchar2(40) NOT NULL,
    "EM_WASTE_ID" varchar2(40) NOT NULL,
    "FED_MANIFEST_WASTE_CODE" varchar2(6) NOT NULL,
    "MANIFEST_WASTE_DESC" varchar2(2000) NULL,
    "COI_IND" char(1) NULL
);
ALTER TABLE "RCRA_EM_FED_WASTE_CODE_DESC" ADD CONSTRAINT "PK_EM_FED_WASTE_CODE_DESC" PRIMARY KEY ("EM_FED_WASTE_CODE_DESC_ID");
CREATE  INDEX "IX_EM_FD_WST_CDE_DSC_EM_WST_ID" ON "RCRA_EM_FED_WASTE_CODE_DESC" ("EM_WASTE_ID");

CREATE TABLE "RCRA_EM_STATE_WASTE_CODE_DESC"
(
    "EM_STATE_WASTE_CODE_DESC_ID" varchar2(40) NOT NULL,
    "EM_WASTE_ID" varchar2(40) NOT NULL,
    "STA_MANIFEST_WASTE_CODE" varchar2(8) NOT NULL,
    "MANIFEST_WASTE_DESC" varchar2(2000) NULL
);
ALTER TABLE "RCRA_EM_STATE_WASTE_CODE_DESC" ADD CONSTRAINT "PK_EM_STATE_WASTE_CODE_DESC" PRIMARY KEY ("EM_STATE_WASTE_CODE_DESC_ID");
CREATE INDEX "IX_EM_STT_WST_CDE_DSC_EM_WS_ID" ON "RCRA_EM_STATE_WASTE_CODE_DESC" ("EM_WASTE_ID");

CREATE TABLE "RCRA_EM_TRANSPORTER"
(
    "EM_TRANSPORTER_ID" varchar2(40) NOT NULL,
    "EM_EMANIFEST_ID" varchar2(40) NOT NULL,
    "TRANSPORTER_ID" varchar2(15) NULL,
    "TRANSPORTER_NAME" varchar2(80) NULL,
    "TRANSPORTER_PRINTED_NAME" varchar2(80) NULL,
    "TRANSPORTER_SIGNATURE_DATE" DATE NULL,
    "TRANSPORTER_ESIG_FIRST_NAME" varchar2(38) NULL,
    "TRANSPORTER_ESIG_LAST_NAME" varchar2(38) NULL,
    "TRANS_ESIG_SIGNATURE_DATE" DATE NULL,
    "TRANSPORTER_LINE_NUM" varchar2(19) NULL,
    "TRANSPORTER_REGISTERED" char(1) NULL
);
ALTER TABLE "RCRA_EM_TRANSPORTER" ADD CONSTRAINT "PK_EM_TRANSPORTER" PRIMARY KEY ("EM_TRANSPORTER_ID");
CREATE INDEX "IX_EM_TRNSPORTER_EM_EMNIFST_ID" ON "RCRA_EM_TRANSPORTER" ("EM_EMANIFEST_ID");

ALTER TABLE "RCRA_EM_WASTE_PCB" ADD "LOAD_TYPE_DESC" varchar2(25) NULL;
ALTER TABLE "RCRA_EM_WASTE_PCB" MODIFY "PCB_LOAD_TYPE_CODE" varchar2(25);
ALTER TABLE "RCRA_EM_WASTE_PCB" MODIFY "PCB_WASTE_TYPE" varchar2(150);

ALTER TABLE "RCRA_EM_FED_WASTE_CODE_DESC" ADD CONSTRAINT "FK_EM_FED_WSTE_CDE_DSC_EM_WSTE" FOREIGN KEY ("EM_WASTE_ID") REFERENCES "RCRA_EM_WASTE" ("EM_WASTE_ID") ON DELETE CASCADE;
ALTER TABLE "RCRA_EM_STATE_WASTE_CODE_DESC" ADD CONSTRAINT "FK_EM_STTE_WSTE_CDE_DSC_EM_WST" FOREIGN KEY ("EM_WASTE_ID") REFERENCES "RCRA_EM_WASTE" ("EM_WASTE_ID") ON DELETE CASCADE;
ALTER TABLE "RCRA_EM_TRANSPORTER" ADD CONSTRAINT "FK_EM_TRANSPORTER_EM_EMANIFEST" FOREIGN KEY ("EM_EMANIFEST_ID") REFERENCES "RCRA_EM_EMANIFEST" ("EM_EMANIFEST_ID") ON DELETE CASCADE;

/*
  RCRA_EM_MANIFEST
*/

ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "GENERATOR_MAIL_STREET_NUM" varchar2(12) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "GENERATOR_MAIL_CITY" varchar2(35) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "GENERATOR_LOC_STREET_NUM" varchar2(12) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "GENERATOR_LOC_CITY" varchar2(35) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "GENERATOR_LOC_STA" char(2) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "GENERATOR_LOC_ZIP" varchar2(25) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "GENERATOR_CONTACT_PHONE_NUM" varchar2(15) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "GENERATOR_CONTACT_PHONE_EXT" varchar2(6) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "GENERATOR_CONTACT_COMPANY_NAME" varchar2(80) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "EMERGENCY_PHONE_NUM" varchar2(15) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "EMERGENCY_PHONE_EXT" varchar2(6) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "GENERATOR_PRINTED_NAME" varchar2(80) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_ID" varchar2(15) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_NAME" varchar2(80) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_MAIL_STREET_NUM" varchar2(12) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_MAIL_CITY" varchar2(35) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_MAIL_CTRY" char(2) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_MAIL_STA" char(2) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_MAIL_ZIP" varchar2(25) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_LOC_STREET_NUM" varchar2(12) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_LOC_CITY" varchar2(35) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_LOC_STA" char(2) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_LOC_ZIP" varchar2(25) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_CONTACT_PHONE_NUM" varchar2(15) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_CONTACT_PHONE_EXT" varchar2(6) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_CONTACT_EMAIL" varchar2(80) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_CONTACT_COMPANY_NAME" varchar2(80) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_PRINTED_NAME" varchar2(80) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_ESIG_FIRST_NAME" varchar2(38) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_ESIG_LAST_NAME" varchar2(38) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "DES_FAC_ESIG_SIGNATURE_DATE" DATE NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ORIG_SUBM_TYPE" varchar2(14) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "COI_ONLY" char(1) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "BROKER_ID" varchar2(15) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "LAST_EM_UPDT_DATE" DATE NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "TRANSPORTER_ON_SITE" char(1) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_PRINTED_NAME" varchar2(80) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_SIGNATURE_DATE" DATE NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_ESIG_FIRST_NAME" varchar2(38) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_ESIG_LAST_NAME" varchar2(38) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_ESIG_SIGNATURE_DATE" DATE NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_ID" varchar2(12) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_NAME" varchar2(80) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_MAIL_STREET_NUM" varchar2(12) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_MAIL_CITY" varchar2(25) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_MAIL_STA" char(2) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_MAIL_ZIP" varchar2(14) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_LOC_STREET_NUM" varchar2(12) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_LOC_STREET_1" varchar2(50) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_LOC_STREET_2" varchar2(50) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_LOC_CITY" varchar2(25) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_LOC_STA" char(2) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_LOC_ZIP" varchar2(14) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_CONTACT_FIRST_NAME" varchar2(38) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_CONTACT_LAST_NAME" varchar2(38) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_CONTACT_PHONE_NO" varchar2(15) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_CONTACT_PHONE_EXT" varchar2(6) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_CONTACT_EMAIL" varchar2(80) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_CONTACT_COMPANY_NAME" varchar2(80) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_REGISTERED" char(1) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "ALT_FAC_MODIFIED" char(1) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "FOREIGN_GENERATOR_NAME" varchar2(80) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "FOREIGN_GENERATOR_STREET" varchar2(50) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "FOREIGN_GENERATOR_CITY" varchar2(25) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "FOREIGN_GENERATOR_CTRY_CODE" char(2) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "FOREIGN_GENERATOR_POST_CODE" varchar2(50) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "FOREIGN_GENERATOR_PROVINCE" varchar2(50) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST" ADD
    "PORT_OF_ENTRY_STA" char(2) NULL;

ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "DISCREPANCY_IND";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "IMP_IND";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "CERT_BY_USER_ID";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "REJ_COMMENTS";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "REJ_GEN_ES_SIGNER_USER_ID";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "REJ_GEN_ES_DOC_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "REJ_GEN_ES_DOC_SIZE";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "IMP_PORT_CITY";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "IMP_PORT_STATE_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "PRINTED_DOC_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "PRINTED_DOC_SIZE";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "FORM_DOC_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "FORM_DOC_SIZE";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "ADD_INFO_NEW_MAN_DEST";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "ADD_INFO_CONSENT_NUM";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "CORR_VERSION_NUM";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "CORR_ES_SIGNER_USER_ID";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "CORR_ES_DOC_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" DROP
    COLUMN "CORR_ES_DOC_SIZE";


ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "CORR_EPA_SITE_ID" TO "GENERATOR_ID";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "REJ_GEN_PS_NAME" TO "GENERATOR_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "PRINTED_DOC_MIME_TYPE" TO "GENERATOR_MAIL_STREET_1";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "FORM_DOC_MIME_TYPE" TO "GENERATOR_MAIL_STREET_2";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "IMP_PORT_STATE_CODE" TO "GENERATOR_MAIL_CTRY";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "IMP_GEN_CNTRY_CODE" TO "GENERATOR_MAIL_STA";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "IMP_GEN_POSTAL_CODE" TO "GENERATOR_MAIL_ZIP";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "CORR_ES_DOC_MIME_TYPE" TO "GENERATOR_LOC_STREET_1";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "REJ_GEN_ES_DOC_MIME_TYPE" TO "GENERATOR_LOC_STREET_2";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "CERT_BY_FIRST_NAME" TO "GENERATOR_CONTACT_FIRST_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "CERT_BY_LAST_NAME" TO "GENERATOR_CONTACT_LAST_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "IMP_GEN_NAME" TO "GENERATOR_CONTACT_EMAIL";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "CORR_ES_SIGN_DATE" TO "GENERATOR_SIGNATURE_DATE";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "CORR_ES_SIGNER_FIRST_NAME" TO "GENERATOR_ESIG_FIRST_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "CORR_ES_SIGNER_LAST_NAME" TO "GENERATOR_ESIG_LAST_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "REJ_GEN_ES_SIGN_DATE" TO "GENERATOR_ESIG_SIGNATURE_DATE";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "REJ_TRANS_ON_SITE_IND" TO "GENERATOR_REGISTERED";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "SIGN_STATUS_IND" TO "GENERATOR_MODIFIED";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "IMP_GEN_ADDRESS" TO "DES_FAC_MAIL_STREET_1";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "IMP_GEN_PROVINCE" TO "DES_FAC_MAIL_STREET_2";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "REJ_GEN_ES_CROMERR_ACT_ID" TO "DES_FAC_LOC_STREET_1";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "CORR_ES_CROMERR_ACT_ID" TO "DES_FAC_LOC_STREET_2";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "REJ_GEN_ES_SIGNER_FIRST_NAME" TO "DES_FAC_CONTACT_FIRST_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "REJ_GEN_ES_SIGNER_LAST_NAME" TO "DES_FAC_CONTACT_LAST_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "REJ_GEN_PS_DATE" TO "DES_FAC_SIGNATURE_DATE";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "RESIDUE_IND" TO "DES_FAC_REGISTERED";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "PUBLIC_IND" TO "DES_FAC_MODIFIED";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "CORR_ACTIVE_IND" TO "RESIDUE";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "CONT_PREV_REJ_RES_IND" TO "IMPORT";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "ADD_INFO_HAND_INSTR" TO "MANIFEST_HANDLING_INSTR";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "REJ_TYPE" TO "REJECTION_TYPE";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "REJ_ALT_DES_FAC_TYPE" TO "ALTERNATE_DESIGNATED_FAC_TYPE";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "CORR_ES_CROMERR_DOC_ID" TO "ALT_FAC_MAIL_STREET_1";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "REJ_GEN_ES_CROMERR_DOC_ID" TO "ALT_FAC_MAIL_STREET_2";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "IMP_GEN_CNTRY_NAME" TO "FOREIGN_GENERATOR_CTRY_NAME";
ALTER TABLE "RCRA_EM_EMANIFEST" RENAME COLUMN "IMP_GEN_CITY" TO "PORT_OF_ENTRY_CITY";

-- ALTER TABLE "RCRA_EM_EMANIFEST" MODIFY "CREATED_DATE" DATE NULL;
-- ALTER TABLE "RCRA_EM_EMANIFEST" MODIFY "MAN_TRACKING_NUM" varchar2(12) NULL;
-- ALTER TABLE "RCRA_EM_EMANIFEST" MODIFY "STATUS" varchar2(17) NULL;
-- ALTER TABLE "RCRA_EM_EMANIFEST" MODIFY "ORIGIN_TYPE" varchar2(7) NULL;
-- ALTER TABLE "RCRA_EM_EMANIFEST" MODIFY "REJ_IND" char(1) NULL;


/*
  RCRA_EM_EMANIFEST_COMMENT
*/
ALTER TABLE "RCRA_EM_EMANIFEST_COMMENT"
    ADD "CMNT_DESC" varchar2(255) NULL;
ALTER TABLE "RCRA_EM_EMANIFEST_COMMENT" DROP
    COLUMN "COMMENT_DESC";
ALTER TABLE "RCRA_EM_EMANIFEST_COMMENT" DROP
    COLUMN "HANDLER_ID";
ALTER TABLE "RCRA_EM_EMANIFEST_COMMENT" RENAME COLUMN "COMMENT_LABEL" TO "CMNT_LABEL";


/*
  RCRA_EM_WASTE
*/
ALTER TABLE "RCRA_EM_WASTE" ADD
    "DOT_ID_NUM_DESC" varchar2(6) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "CONTAINER_TYPE_CODE" char(2) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "CONTAINER_TYPE_DESC" varchar2(50) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "DISCREPANCY_COMM" varchar2(257) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "WASTE_RESIDUE" char(1) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "CNST_NUM" varchar2(12) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "EPA_WASTE" char(1) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "COI_ONLY" char(1) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "QNTY_ACUTE_KG" NUMBER(14, 6) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "QNTY_ACUTE_TONS" NUMBER(14, 6) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "QNTY_KG" NUMBER(14, 6) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "QNTY_NON_ACUTE_KG" NUMBER(14, 6) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "QNTY_NON_ACUTE_TONS" NUMBER(14, 6) NULL;
ALTER TABLE "RCRA_EM_WASTE" ADD
    "QNTY_TONS" NUMBER(14, 6) NULL;



ALTER TABLE "RCRA_EM_WASTE" DROP
    COLUMN "DOT_HAZ_IND";
ALTER TABLE "RCRA_EM_WASTE" DROP
    COLUMN "PCB_IND";
ALTER TABLE "RCRA_EM_WASTE" DROP
    COLUMN "DOT_ID_NUM";
ALTER TABLE "RCRA_EM_WASTE" DROP
    COLUMN "QNT_CONT_TYPE_CODE";
ALTER TABLE "RCRA_EM_WASTE" DROP
    COLUMN "QNT_CONT_TYPE_DESC";
ALTER TABLE "RCRA_EM_WASTE" DROP
    COLUMN "DISC_RESIDUE_COMMENTS";
ALTER TABLE "RCRA_EM_WASTE" DROP
    COLUMN "ADD_INFO_NEW_MAN_DEST";
ALTER TABLE "RCRA_EM_WASTE" DROP
    COLUMN "ADD_INFO_CONSENT_NUM";



ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "BR_IND" TO "DOT_HAZRD";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "WASTES_DESC" TO "NON_HAZ_WASTE_DESC";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "QNT_CONT_NUM" TO "CONTAINER_NUM";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "QNT_VAL" TO "QNTY_VAL";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "QNT_UOM_CODE" TO "QTY_UNIT_OF_MEAS_CODE";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "QNT_UOM_DESC" TO "QTY_UNIT_OF_MEAS_DESC";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "BR_FORM_DESC" TO "BR_FORM_CODE_DESC";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "BR_SRC_DESC" TO "BR_SRC_CODE_DESC";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "BR_WM_CODE" TO "BR_WASTE_MIN_CODE";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "BR_WM_DESC" TO "BR_WASTE_MIN_DESC";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "EPA_WASTE_IND" TO "BR_MIXED_RADIOACTIVE_WASTE";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "DISC_RESIDUE_IND" TO "PCB";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "DISC_WASTE_QTY_IND" TO "QNTY_DISCREPANCY";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "DISC_WASTE_TYPE_IND" TO "WASTE_TYPE_DISCREPANCY";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "DISC_COMMENTS" TO "WASTE_RESIDUE_COMM";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "MGMT_METHOD_CODE" TO "MANAGEMENT_METH_CODE";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "MGMT_METHOD_DESC" TO "MANAGEMENT_METH_DESC";
ALTER TABLE "RCRA_EM_WASTE" RENAME COLUMN "ADD_INFO_HAND_INSTR" TO "HANDLING_INSTRUCTIONS";
-- ALTER TABLE "RCRA_EM_WASTE" MODIFY "LINE_NUM" NUMBER(10,0) NULL;


/*
  RCRA_EM_WASTE_COMMENT
*/
ALTER TABLE "RCRA_EM_WASTE_COMMENT" ADD "CMNT_DESC" varchar2(255) NULL;
ALTER TABLE "RCRA_EM_WASTE_COMMENT" DROP
    COLUMN "COMMENT_DESC";
ALTER TABLE "RCRA_EM_WASTE_COMMENT" DROP
    COLUMN "HANDLER_ID";
ALTER TABLE "RCRA_EM_WASTE_COMMENT" RENAME COLUMN "COMMENT_LABEL" TO "CMNT_LABEL";
ALTER TABLE RCRA_HD_EPISODIC_WASTE_CODE MODIFY WASTE_CODE_TEXT varchar2(4000);
