---$ Drop Index/PK: IX_CA_AR_CA_FC_SB, Table : dbo.RCRA_CA_AREA
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AREA') AND NAME = 'IX_CA_AR_CA_FC_SB')
BEGIN
    DROP INDEX IX_CA_AR_CA_FC_SB ON dbo.RCRA_CA_AREA
END
GO

---$ Drop Index/PK: IX_CA_AR_RL_EV_CA, Table : dbo.RCRA_CA_AREA_REL_EVENT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AREA_REL_EVENT') AND NAME = 'IX_CA_AR_RL_EV_CA')
BEGIN
    DROP INDEX IX_CA_AR_RL_EV_CA ON dbo.RCRA_CA_AREA_REL_EVENT
END
GO

---$ Drop Index/PK: PK_CA_AREA_RL_EVNT, Table : dbo.RCRA_CA_AREA_REL_EVENT
IF OBJECT_ID(N'dbo.PK_CA_AREA_RL_EVNT') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_CA_AREA_REL_EVENT
        DROP CONSTRAINT PK_CA_AREA_RL_EVNT
END
GO

---$ Drop Index/PK: IX_CA_AT_RL_EV_CA, Table : dbo.RCRA_CA_AUTH_REL_EVENT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AUTH_REL_EVENT') AND NAME = 'IX_CA_AT_RL_EV_CA')
BEGIN
    DROP INDEX IX_CA_AT_RL_EV_CA ON dbo.RCRA_CA_AUTH_REL_EVENT
END
GO

---$ Drop Index/PK: PK_CA_AUTH_RL_EVNT, Table : dbo.RCRA_CA_AUTH_REL_EVENT
IF OBJECT_ID(N'dbo.PK_CA_AUTH_RL_EVNT') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_CA_AUTH_REL_EVENT
        DROP CONSTRAINT PK_CA_AUTH_RL_EVNT
END
GO

---$ Drop Index/PK: IX_CA_AT_CA_FC_SB, Table : dbo.RCRA_CA_AUTHORITY
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AUTHORITY') AND NAME = 'IX_CA_AT_CA_FC_SB')
BEGIN
    DROP INDEX IX_CA_AT_CA_FC_SB ON dbo.RCRA_CA_AUTHORITY
END
GO

---$ Drop Index/PK: IX_CA_EV_CA_FC_SB, Table : dbo.RCRA_CA_EVENT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT') AND NAME = 'IX_CA_EV_CA_FC_SB')
BEGIN
    DROP INDEX IX_CA_EV_CA_FC_SB ON dbo.RCRA_CA_EVENT
END
GO

---$ Drop Index/PK: IX_CA_EV_CM_CA_EV, Table : dbo.RCRA_CA_EVENT_COMMITMENT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT_COMMITMENT') AND NAME = 'IX_CA_EV_CM_CA_EV')
BEGIN
    DROP INDEX IX_CA_EV_CM_CA_EV ON dbo.RCRA_CA_EVENT_COMMITMENT
END
GO

---$ Drop Index/PK: PK_CA_EVNT_CMMTMNT, Table : dbo.RCRA_CA_EVENT_COMMITMENT
IF OBJECT_ID(N'dbo.PK_CA_EVNT_CMMTMNT') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_CA_EVENT_COMMITMENT
        DROP CONSTRAINT PK_CA_EVNT_CMMTMNT
END
GO

---$ Drop Index/PK: IX_CA_FC_SB_CA_SB, Table : dbo.RCRA_CA_FAC_SUBM
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_FAC_SUBM') AND NAME = 'IX_CA_FC_SB_CA_SB')
BEGIN
    DROP INDEX IX_CA_FC_SB_CA_SB ON dbo.RCRA_CA_FAC_SUBM
END
GO

---$ Drop Index/PK: IX_CA_RL_PR_UN_CA, Table : dbo.RCRA_CA_REL_PERMIT_UNIT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_REL_PERMIT_UNIT') AND NAME = 'IX_CA_RL_PR_UN_CA')
BEGIN
    DROP INDEX IX_CA_RL_PR_UN_CA ON dbo.RCRA_CA_REL_PERMIT_UNIT
END
GO

---$ Drop Index/PK: PK_CA_RL_PRMIT_UNT, Table : dbo.RCRA_CA_REL_PERMIT_UNIT
IF OBJECT_ID(N'dbo.PK_CA_RL_PRMIT_UNT') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_CA_REL_PERMIT_UNIT
        DROP CONSTRAINT PK_CA_RL_PRMIT_UNT
END
GO

---$ Drop Index/PK: IX_CA_ST_CT_CA_AT, Table : dbo.RCRA_CA_STATUTORY_CITATION
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_STATUTORY_CITATION') AND NAME = 'IX_CA_ST_CT_CA_AT')
BEGIN
    DROP INDEX IX_CA_ST_CT_CA_AT ON dbo.RCRA_CA_STATUTORY_CITATION
END
GO

---$ Drop Index/PK: PK_CA_STTTRY_CTTON, Table : dbo.RCRA_CA_STATUTORY_CITATION
IF OBJECT_ID(N'dbo.PK_CA_STTTRY_CTTON') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_CA_STATUTORY_CITATION
        DROP CONSTRAINT PK_CA_STTTRY_CTTON
END
GO

---$ Drop Index/PK: IX_CME_CT_CM_VL_ID, Table : dbo.RCRA_CME_CITATION
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_CITATION') AND NAME = 'IX_CME_CT_CM_VL_ID')
BEGIN
    DROP INDEX IX_CME_CT_CM_VL_ID ON dbo.RCRA_CME_CITATION
END
GO

---$ Drop Index/PK: IX_CM_CS_DT_CM_EN, Table : dbo.RCRA_CME_CSNY_DATE
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_CSNY_DATE') AND NAME = 'IX_CM_CS_DT_CM_EN')
BEGIN
    DROP INDEX IX_CM_CS_DT_CM_EN ON dbo.RCRA_CME_CSNY_DATE
END
GO

---$ Drop Index/PK: IX_CM_EN_AC_CM_FC, Table : dbo.RCRA_CME_ENFRC_ACT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_ENFRC_ACT') AND NAME = 'IX_CM_EN_AC_CM_FC')
BEGIN
    DROP INDEX IX_CM_EN_AC_CM_FC ON dbo.RCRA_CME_ENFRC_ACT
END
GO

---$ Drop Index/PK: IX_CM_EV_CM_FC_SB, Table : dbo.RCRA_CME_EVAL
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL') AND NAME = 'IX_CM_EV_CM_FC_SB')
BEGIN
    DROP INDEX IX_CM_EV_CM_FC_SB ON dbo.RCRA_CME_EVAL
END
GO

---$ Drop Index/PK: IX_CM_EV_CM_CM_EV, Table : dbo.RCRA_CME_EVAL_COMMIT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL_COMMIT') AND NAME = 'IX_CM_EV_CM_CM_EV')
BEGIN
    DROP INDEX IX_CM_EV_CM_CM_EV ON dbo.RCRA_CME_EVAL_COMMIT
END
GO

---$ Drop Index/PK: IX_CM_EV_VL_CM_EV, Table : dbo.RCRA_CME_EVAL_VIOL
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL_VIOL') AND NAME = 'IX_CM_EV_VL_CM_EV')
BEGIN
    DROP INDEX IX_CM_EV_VL_CM_EV ON dbo.RCRA_CME_EVAL_VIOL
END
GO

---$ Drop Index/PK: IX_CM_FC_SB_CM_SB, Table : dbo.RCRA_CME_FAC_SUBM
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_FAC_SUBM') AND NAME = 'IX_CM_FC_SB_CM_SB')
BEGIN
    DROP INDEX IX_CM_FC_SB_CM_SB ON dbo.RCRA_CME_FAC_SUBM
END
GO

---$ Drop Index/PK: IX_CM_MD_CM_EN_AC, Table : dbo.RCRA_CME_MEDIA
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_MEDIA') AND NAME = 'IX_CM_MD_CM_EN_AC')
BEGIN
    DROP INDEX IX_CM_MD_CM_EN_AC ON dbo.RCRA_CME_MEDIA
END
GO

---$ Drop Index/PK: IX_CM_ML_CM_EN_AC, Table : dbo.RCRA_CME_MILESTONE
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_MILESTONE') AND NAME = 'IX_CM_ML_CM_EN_AC')
BEGIN
    DROP INDEX IX_CM_ML_CM_EN_AC ON dbo.RCRA_CME_MILESTONE
END
GO

---$ Drop Index/PK: IX_CM_PN_CM_EN_AC, Table : dbo.RCRA_CME_PNLTY
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_PNLTY') AND NAME = 'IX_CM_PN_CM_EN_AC')
BEGIN
    DROP INDEX IX_CM_PN_CM_EN_AC ON dbo.RCRA_CME_PNLTY
END
GO

---$ Drop Index/PK: IX_CME_PY_CM_PN_ID, Table : dbo.RCRA_CME_PYMT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_PYMT') AND NAME = 'IX_CME_PY_CM_PN_ID')
BEGIN
    DROP INDEX IX_CME_PY_CM_PN_ID ON dbo.RCRA_CME_PYMT
END
GO

---$ Drop Index/PK: IX_CME_RQ_CM_EV_ID, Table : dbo.RCRA_CME_RQST
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_RQST') AND NAME = 'IX_CME_RQ_CM_EV_ID')
BEGIN
    DROP INDEX IX_CME_RQ_CM_EV_ID ON dbo.RCRA_CME_RQST
END
GO

---$ Drop Index/PK: IX_CM_SP_EN_PR_CM, Table : dbo.RCRA_CME_SUPP_ENVR_PRJT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_SUPP_ENVR_PRJT') AND NAME = 'IX_CM_SP_EN_PR_CM')
BEGIN
    DROP INDEX IX_CM_SP_EN_PR_CM ON dbo.RCRA_CME_SUPP_ENVR_PRJT
END
GO

---$ Drop Index/PK: PK_CME_SPP_ENV_PRJ, Table : dbo.RCRA_CME_SUPP_ENVR_PRJT
IF OBJECT_ID(N'dbo.PK_CME_SPP_ENV_PRJ') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_CME_SUPP_ENVR_PRJT
        DROP CONSTRAINT PK_CME_SPP_ENV_PRJ
END
GO

---$ Drop Index/PK: IX_CM_VL_CM_FC_SB, Table : dbo.RCRA_CME_VIOL
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_VIOL') AND NAME = 'IX_CM_VL_CM_FC_SB')
BEGIN
    DROP INDEX IX_CM_VL_CM_FC_SB ON dbo.RCRA_CME_VIOL
END
GO

---$ Drop Index/PK: IX_CM_VL_EN_CM_EN, Table : dbo.RCRA_CME_VIOL_ENFRC
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_VIOL_ENFRC') AND NAME = 'IX_CM_VL_EN_CM_EN')
BEGIN
    DROP INDEX IX_CM_VL_EN_CM_EN ON dbo.RCRA_CME_VIOL_ENFRC
END
GO

---$ Drop Index/PK: IX_FA_CS_ES_FA_FC, Table : dbo.RCRA_FA_COST_EST
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'IX_FA_CS_ES_FA_FC')
BEGIN
    DROP INDEX IX_FA_CS_ES_FA_FC ON dbo.RCRA_FA_COST_EST
END
GO

---$ Drop Index/PK: IX_FA_CS_ES_RL_MC, Table : dbo.RCRA_FA_COST_EST_REL_MECHANISM
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST_REL_MECHANISM') AND NAME = 'IX_FA_CS_ES_RL_MC')
BEGIN
    DROP INDEX IX_FA_CS_ES_RL_MC ON dbo.RCRA_FA_COST_EST_REL_MECHANISM
END
GO

---$ Drop Index/PK: PK_FA_CST_ES_RL_MC, Table : dbo.RCRA_FA_COST_EST_REL_MECHANISM
IF OBJECT_ID(N'dbo.PK_FA_CST_ES_RL_MC') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_FA_COST_EST_REL_MECHANISM
        DROP CONSTRAINT PK_FA_CST_ES_RL_MC
END
GO

---$ Drop Index/PK: IX_FA_FC_SB_FA_SB, Table : dbo.RCRA_FA_FAC_SUBM
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_FAC_SUBM') AND NAME = 'IX_FA_FC_SB_FA_SB')
BEGIN
    DROP INDEX IX_FA_FC_SB_FA_SB ON dbo.RCRA_FA_FAC_SUBM
END
GO

---$ Drop Index/PK: IX_FA_MC_FA_FC_SB, Table : dbo.RCRA_FA_MECHANISM
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'IX_FA_MC_FA_FC_SB')
BEGIN
    DROP INDEX IX_FA_MC_FA_FC_SB ON dbo.RCRA_FA_MECHANISM
END
GO

---$ Drop Index/PK: IX_FA_MC_DT_FA_MC, Table : dbo.RCRA_FA_MECHANISM_DETAIL
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'IX_FA_MC_DT_FA_MC')
BEGIN
    DROP INDEX IX_FA_MC_DT_FA_MC ON dbo.RCRA_FA_MECHANISM_DETAIL
END
GO

---$ Drop Index/PK: PK_FA_MCHNISM_DTIL, Table : dbo.RCRA_FA_MECHANISM_DETAIL
IF OBJECT_ID(N'dbo.PK_FA_MCHNISM_DTIL') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        DROP CONSTRAINT PK_FA_MCHNISM_DTIL
END
GO

---$ Drop Index/PK: IX_GS_FC_SB_GS_SB, Table : dbo.RCRA_GIS_FAC_SUBM
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_GIS_FAC_SUBM') AND NAME = 'IX_GS_FC_SB_GS_SB')
BEGIN
    DROP INDEX IX_GS_FC_SB_GS_SB ON dbo.RCRA_GIS_FAC_SUBM
END
GO

---$ Drop Index/PK: IX_GS_GO_IN_GS_FC, Table : dbo.RCRA_GIS_GEO_INFORMATION
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_GIS_GEO_INFORMATION') AND NAME = 'IX_GS_GO_IN_GS_FC')
BEGIN
    DROP INDEX IX_GS_GO_IN_GS_FC ON dbo.RCRA_GIS_GEO_INFORMATION
END
GO

---$ Drop Index/PK: PK_GS_GO_INFORMTON, Table : dbo.RCRA_GIS_GEO_INFORMATION
IF OBJECT_ID(N'dbo.PK_GS_GO_INFORMTON') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_GIS_GEO_INFORMATION
        DROP CONSTRAINT PK_GS_GO_INFORMTON
END
GO

---$ Drop Index/PK: IX_HD_CER_HD_HA_ID, Table : dbo.RCRA_HD_CERTIFICATION
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_CERTIFICATION') AND NAME = 'IX_HD_CER_HD_HA_ID')
BEGIN
    DROP INDEX IX_HD_CER_HD_HA_ID ON dbo.RCRA_HD_CERTIFICATION
END
GO

---$ Drop Index/PK: PK_HD_CERTIFICATIO, Table : dbo.RCRA_HD_CERTIFICATION
IF OBJECT_ID(N'dbo.PK_HD_CERTIFICATIO') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_HD_CERTIFICATION
        DROP CONSTRAINT PK_HD_CERTIFICATIO
END
GO

---$ Drop Index/PK: IX_HD_EN_PE_HD_HA, Table : dbo.RCRA_HD_ENV_PERMIT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_ENV_PERMIT') AND NAME = 'IX_HD_EN_PE_HD_HA')
BEGIN
    DROP INDEX IX_HD_EN_PE_HD_HA ON dbo.RCRA_HD_ENV_PERMIT
END
GO

---$ Drop Index/PK: IX_HD_HAN_HD_HB_ID, Table : dbo.RCRA_HD_HANDLER
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'IX_HD_HAN_HD_HB_ID')
BEGIN
    DROP INDEX IX_HD_HAN_HD_HB_ID ON dbo.RCRA_HD_HANDLER
END
GO

---$ Drop Index/PK: IX_HD_HBA_HD_SU_ID, Table : dbo.RCRA_HD_HBASIC
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HBASIC') AND NAME = 'IX_HD_HBA_HD_SU_ID')
BEGIN
    DROP INDEX IX_HD_HBA_HD_SU_ID ON dbo.RCRA_HD_HBASIC
END
GO

---$ Drop Index/PK: IX_HD_NAI_HD_HA_ID, Table : dbo.RCRA_HD_NAICS
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_NAICS') AND NAME = 'IX_HD_NAI_HD_HA_ID')
BEGIN
    DROP INDEX IX_HD_NAI_HD_HA_ID ON dbo.RCRA_HD_NAICS
END
GO

---$ Drop Index/PK: IX_HD_OT_ID_HD_HB, Table : dbo.RCRA_HD_OTHER_ID
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_OTHER_ID') AND NAME = 'IX_HD_OT_ID_HD_HB')
BEGIN
    DROP INDEX IX_HD_OT_ID_HD_HB ON dbo.RCRA_HD_OTHER_ID
END
GO

---$ Drop Index/PK: IX_HD_OWN_HD_HA_ID, Table : dbo.RCRA_HD_OWNEROP
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_OWNEROP') AND NAME = 'IX_HD_OWN_HD_HA_ID')
BEGIN
    DROP INDEX IX_HD_OWN_HD_HA_ID ON dbo.RCRA_HD_OWNEROP
END
GO

---$ Drop Index/PK: IX_HD_SE_MA_AC_HD, Table : dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY') AND NAME = 'IX_HD_SE_MA_AC_HD')
BEGIN
    DROP INDEX IX_HD_SE_MA_AC_HD ON dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY
END
GO

---$ Drop Index/PK: IX_HD_SE_WA_CO_HD, Table : dbo.RCRA_HD_SEC_WASTE_CODE
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_SEC_WASTE_CODE') AND NAME = 'IX_HD_SE_WA_CO_HD')
BEGIN
    DROP INDEX IX_HD_SE_WA_CO_HD ON dbo.RCRA_HD_SEC_WASTE_CODE
END
GO

---$ Drop Index/PK: PK_HD_SEC_WAST_COD, Table : dbo.RCRA_HD_SEC_WASTE_CODE
IF OBJECT_ID(N'dbo.PK_HD_SEC_WAST_COD') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_HD_SEC_WASTE_CODE
        DROP CONSTRAINT PK_HD_SEC_WAST_COD
END
GO

---$ Drop Index/PK: IX_HD_ST_AC_HD_HA, Table : dbo.RCRA_HD_STATE_ACTIVITY
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_STATE_ACTIVITY') AND NAME = 'IX_HD_ST_AC_HD_HA')
BEGIN
    DROP INDEX IX_HD_ST_AC_HD_HA ON dbo.RCRA_HD_STATE_ACTIVITY
END
GO

---$ Drop Index/PK: PK_HD_STATE_ACTIVI, Table : dbo.RCRA_HD_STATE_ACTIVITY
IF OBJECT_ID(N'dbo.PK_HD_STATE_ACTIVI') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_HD_STATE_ACTIVITY
        DROP CONSTRAINT PK_HD_STATE_ACTIVI
END
GO

---$ Drop Index/PK: IX_HD_UN_WA_HD_HA, Table : dbo.RCRA_HD_UNIVERSAL_WASTE
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_UNIVERSAL_WASTE') AND NAME = 'IX_HD_UN_WA_HD_HA')
BEGIN
    DROP INDEX IX_HD_UN_WA_HD_HA ON dbo.RCRA_HD_UNIVERSAL_WASTE
END
GO

---$ Drop Index/PK: PK_HD_UNIVER_WASTE, Table : dbo.RCRA_HD_UNIVERSAL_WASTE
IF OBJECT_ID(N'dbo.PK_HD_UNIVER_WASTE') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_HD_UNIVERSAL_WASTE
        DROP CONSTRAINT PK_HD_UNIVER_WASTE
END
GO

---$ Drop Index/PK: IX_HD_WA_CO_HD_HA, Table : dbo.RCRA_HD_WASTE_CODE
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_WASTE_CODE') AND NAME = 'IX_HD_WA_CO_HD_HA')
BEGIN
    DROP INDEX IX_HD_WA_CO_HD_HA ON dbo.RCRA_HD_WASTE_CODE
END
GO

---$ Drop Index/PK: IX_PRM_EV_PR_SR_ID, Table : dbo.RCRA_PRM_EVENT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_EVENT') AND NAME = 'IX_PRM_EV_PR_SR_ID')
BEGIN
    DROP INDEX IX_PRM_EV_PR_SR_ID ON dbo.RCRA_PRM_EVENT
END
GO

---$ Drop Index/PK: IX_PR_EV_CM_PR_EV, Table : dbo.RCRA_PRM_EVENT_COMMITMENT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_EVENT_COMMITMENT') AND NAME = 'IX_PR_EV_CM_PR_EV')
BEGIN
    DROP INDEX IX_PR_EV_CM_PR_EV ON dbo.RCRA_PRM_EVENT_COMMITMENT
END
GO

---$ Drop Index/PK: PK_PRM_EVNT_CMMTMN, Table : dbo.RCRA_PRM_EVENT_COMMITMENT
IF OBJECT_ID(N'dbo.PK_PRM_EVNT_CMMTMN') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_PRM_EVENT_COMMITMENT
        DROP CONSTRAINT PK_PRM_EVNT_CMMTMN
END
GO

---$ Drop Index/PK: IX_PR_FC_SB_PR_SB, Table : dbo.RCRA_PRM_FAC_SUBM
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_FAC_SUBM') AND NAME = 'IX_PR_FC_SB_PR_SB')
BEGIN
    DROP INDEX IX_PR_FC_SB_PR_SB ON dbo.RCRA_PRM_FAC_SUBM
END
GO

---$ Drop Index/PK: IX_PR_RL_EV_PR_UN, Table : dbo.RCRA_PRM_RELATED_EVENT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_RELATED_EVENT') AND NAME = 'IX_PR_RL_EV_PR_UN')
BEGIN
    DROP INDEX IX_PR_RL_EV_PR_UN ON dbo.RCRA_PRM_RELATED_EVENT
END
GO

---$ Drop Index/PK: PK_PRM_RELTED_EVNT, Table : dbo.RCRA_PRM_RELATED_EVENT
IF OBJECT_ID(N'dbo.PK_PRM_RELTED_EVNT') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_PRM_RELATED_EVENT
        DROP CONSTRAINT PK_PRM_RELTED_EVNT
END
GO

---$ Drop Index/PK: IX_PR_SR_PR_FC_SB, Table : dbo.RCRA_PRM_SERIES
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_SERIES') AND NAME = 'IX_PR_SR_PR_FC_SB')
BEGIN
    DROP INDEX IX_PR_SR_PR_FC_SB ON dbo.RCRA_PRM_SERIES
END
GO

---$ Drop Index/PK: IX_PR_UN_PR_FC_SB, Table : dbo.RCRA_PRM_UNIT
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT') AND NAME = 'IX_PR_UN_PR_FC_SB')
BEGIN
    DROP INDEX IX_PR_UN_PR_FC_SB ON dbo.RCRA_PRM_UNIT
END
GO

---$ Drop Index/PK: IX_PR_UN_DT_PR_UN, Table : dbo.RCRA_PRM_UNIT_DETAIL
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT_DETAIL') AND NAME = 'IX_PR_UN_DT_PR_UN')
BEGIN
    DROP INDEX IX_PR_UN_DT_PR_UN ON dbo.RCRA_PRM_UNIT_DETAIL
END
GO

---$ Drop Index/PK: IX_PR_WS_CD_PR_UN, Table : dbo.RCRA_PRM_WASTE_CODE
IF EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_WASTE_CODE') AND NAME = 'IX_PR_WS_CD_PR_UN')
BEGIN
    DROP INDEX IX_PR_WS_CD_PR_UN ON dbo.RCRA_PRM_WASTE_CODE
END
GO

---$ Drop Index/PK: PK_SUBMISSIONHISTO, Table : dbo.RCRA_SUBMISSIONHISTORY
IF OBJECT_ID(N'dbo.PK_SUBMISSIONHISTO') IS NOT NULL
BEGIN
    ALTER TABLE dbo.RCRA_SUBMISSIONHISTORY
        DROP CONSTRAINT PK_SUBMISSIONHISTO
END
GO

---$ Alter table dbo.RCRA_CME_CITATION
ALTER TABLE dbo.RCRA_CME_CITATION
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_CITATION
    ALTER COLUMN CITATION_NAME VARCHAR(80) NULL
GO

ALTER TABLE dbo.RCRA_CME_CITATION
    ALTER COLUMN CITATION_NAME_OWNER CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_CITATION
    ALTER COLUMN CITATION_NAME_TYPE CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_CITATION
    ALTER COLUMN NOTES VARCHAR(4000) NULL
GO


---$ Alter table dbo.RCRA_CME_CSNY_DATE
ALTER TABLE dbo.RCRA_CME_CSNY_DATE
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO


---$ Alter table dbo.RCRA_CME_ENFRC_ACT
ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN ENFRC_AGN_LOC_NAME CHAR(2) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN ENFRC_ACT_IDEN VARCHAR(3) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN ENFRC_AGN_NAME CHAR(1) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN ENFRC_DOCKET_NUM VARCHAR(15) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN ENFRC_ATTRY VARCHAR(5) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN CORCT_ACT_COMPT CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN DISP_STAT_OWNER CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN DISP_STAT CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN ENFRC_OWNER CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN ENFRC_TYPE CHAR(3) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN ENFRC_RESP_PERSON_OWNER CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN ENFRC_RESP_PERSON_IDEN VARCHAR(5) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN ENFRC_RESP_SUBORG_OWNER CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN ENFRC_RESP_SUBORG VARCHAR(10) NULL
GO

ALTER TABLE dbo.RCRA_CME_ENFRC_ACT
    ALTER COLUMN NOTES VARCHAR(4000) NULL
GO


---$ Alter table dbo.RCRA_CME_EVAL
ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN EVAL_ACT_LOC CHAR(2) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN EVAL_IDEN VARCHAR(3) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN EVAL_RESP_AGN CHAR(1) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN FOUND_VIOL CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN CTZN_CPLT_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN MULTIMEDIA_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN SAMPL_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN NOT_SUBTL_C_IND CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN EVAL_TYPE_OWNER CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN EVAL_TYPE VARCHAR(3) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN FOCUS_AREA_OWNER CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN FOCUS_AREA VARCHAR(3) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN EVAL_RESP_PERSON_IDEN_OWNER CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN EVAL_RESP_PERSON_IDEN VARCHAR(5) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN EVAL_RESP_SUBORG_OWNER CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN EVAL_RESP_SUBORG VARCHAR(10) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL
    ALTER COLUMN NOTES VARCHAR(4000) NULL
GO


---$ Alter table dbo.RCRA_CME_EVAL_COMMIT
ALTER TABLE dbo.RCRA_CME_EVAL_COMMIT
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL_COMMIT
    ALTER COLUMN COMMIT_LEAD CHAR(2) NOT NULL
GO


---$ Alter table dbo.RCRA_CME_EVAL_VIOL
ALTER TABLE dbo.RCRA_CME_EVAL_VIOL
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL_VIOL
    ALTER COLUMN VIOL_ACT_LOC CHAR(2) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_EVAL_VIOL
    ALTER COLUMN AGN_WHICH_DTRM_VIOL CHAR(1) NOT NULL
GO


---$ Alter table dbo.RCRA_CME_FAC_SUBM
ALTER TABLE dbo.RCRA_CME_FAC_SUBM
    ALTER COLUMN EPA_HDLR_ID CHAR(12) NOT NULL
GO


---$ Alter table dbo.RCRA_CME_MEDIA
ALTER TABLE dbo.RCRA_CME_MEDIA
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_MEDIA
    ALTER COLUMN MULTIMEDIA_CODE_OWNER CHAR(2) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_MEDIA
    ALTER COLUMN MULTIMEDIA_CODE VARCHAR(3) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_MEDIA
    ALTER COLUMN NOTES VARCHAR(4000) NULL
GO


---$ Alter table dbo.RCRA_CME_MILESTONE
ALTER TABLE dbo.RCRA_CME_MILESTONE
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_MILESTONE
    ALTER COLUMN TECH_RQMT_DESC VARCHAR(200) NULL
GO

ALTER TABLE dbo.RCRA_CME_MILESTONE
    ALTER COLUMN NOTES VARCHAR(4000) NULL
GO


---$ Alter table dbo.RCRA_CME_PNLTY
ALTER TABLE dbo.RCRA_CME_PNLTY
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_PNLTY
    ALTER COLUMN PNLTY_TYPE_OWNER CHAR(2) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_PNLTY
    ALTER COLUMN PNLTY_TYPE VARCHAR(3) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_PNLTY
    ALTER COLUMN NOTES VARCHAR(4000) NULL
GO


---$ Alter table dbo.RCRA_CME_PYMT
ALTER TABLE dbo.RCRA_CME_PYMT
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_PYMT
    ALTER COLUMN NOTES VARCHAR(4000) NULL
GO


---$ Alter table dbo.RCRA_CME_RQST
ALTER TABLE dbo.RCRA_CME_RQST
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_RQST
    ALTER COLUMN RQST_AGN CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_RQST
    ALTER COLUMN NOTES VARCHAR(4000) NULL
GO


---$ Alter table dbo.RCRA_CME_SUPP_ENVR_PRJT
ALTER TABLE dbo.RCRA_CME_SUPP_ENVR_PRJT
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_SUPP_ENVR_PRJT
    ALTER COLUMN SEP_CODE_OWNER CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_SUPP_ENVR_PRJT
    ALTER COLUMN SEP_DESC_TXT VARCHAR(3) NULL
GO

ALTER TABLE dbo.RCRA_CME_SUPP_ENVR_PRJT
    ALTER COLUMN NOTES VARCHAR(4000) NULL
GO


---$ Alter table dbo.RCRA_CME_VIOL
ALTER TABLE dbo.RCRA_CME_VIOL
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_VIOL
    ALTER COLUMN VIOL_ACT_LOC CHAR(2) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_VIOL
    ALTER COLUMN AGN_WHICH_DTRM_VIOL CHAR(1) NOT NULL
GO

ALTER TABLE dbo.RCRA_CME_VIOL
    ALTER COLUMN VIOL_TYPE_OWNER CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_CME_VIOL
    ALTER COLUMN VIOL_TYPE VARCHAR(10) NULL
GO

ALTER TABLE dbo.RCRA_CME_VIOL
    ALTER COLUMN FORMER_CITATION_NAME VARCHAR(35) NULL
GO

ALTER TABLE dbo.RCRA_CME_VIOL
    ALTER COLUMN RTN_TO_COMPL_QUAL CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_VIOL
    ALTER COLUMN VIOL_RESP_AGN CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_VIOL
    ALTER COLUMN NOTES VARCHAR(4000) NULL
GO


---$ Alter table dbo.RCRA_CME_VIOL_ENFRC
ALTER TABLE dbo.RCRA_CME_VIOL_ENFRC
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_CME_VIOL_ENFRC
    ALTER COLUMN AGN_WHICH_DTRM_VIOL CHAR(1) NOT NULL
GO


---$ Create table dbo.RCRA_EM_EMANIFEST
IF OBJECT_ID(N'dbo.RCRA_EM_EMANIFEST') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_EMANIFEST
    (
        EM_EMANIFEST_ID VARCHAR(40) NOT NULL,
        EM_SUBM_ID VARCHAR(40) NOT NULL,
        CREATED_DATE datetime NOT NULL,
        UPDATED_DATE datetime NULL,
        MAN_TRACKING_NUM VARCHAR(12) NOT NULL,
        [STATUS] VARCHAR(17) NOT NULL,
        PUBLIC_IND CHAR(1) NULL,
        SUBM_TYPE VARCHAR(14) NULL,
        SIGN_STATUS_IND CHAR(1) NULL,
        ORIGIN_TYPE VARCHAR(7) NOT NULL,
        SHIPPED_DATE datetime NULL,
        RECEIVED_DATE datetime NULL,
        CERT_DATE datetime NULL,
        REJ_IND CHAR(1) NOT NULL,
        DISCREPANCY_IND CHAR(1) NOT NULL,
        RESIDUE_IND CHAR(1) NOT NULL,
        IMP_IND CHAR(1) NOT NULL,
        CONT_PREV_REJ_RES_IND CHAR(1) NULL,
        CERT_BY_FIRST_NAME VARCHAR(38) NULL,
        CERT_BY_LAST_NAME VARCHAR(38) NULL,
        CERT_BY_USER_ID VARCHAR(255) NULL,
        REJ_TRANS_ON_SITE_IND CHAR(1) NULL,
        REJ_TYPE VARCHAR(13) NULL,
        REJ_ALT_DES_FAC_TYPE VARCHAR(9) NULL,
        REJ_COMMENTS VARCHAR(255) NULL,
        REJ_GEN_PS_NAME VARCHAR(80) NULL,
        REJ_GEN_PS_DATE datetime NULL,
        REJ_GEN_ES_SIGN_DATE datetime NULL,
        REJ_GEN_ES_CROMERR_ACT_ID VARCHAR(50) NULL,
        REJ_GEN_ES_CROMERR_DOC_ID VARCHAR(50) NULL,
        REJ_GEN_ES_SIGNER_FIRST_NAME VARCHAR(38) NULL,
        REJ_GEN_ES_SIGNER_LAST_NAME VARCHAR(38) NULL,
        REJ_GEN_ES_SIGNER_USER_ID VARCHAR(255) NULL,
        REJ_GEN_ES_DOC_NAME VARCHAR(255) NULL,
        REJ_GEN_ES_DOC_SIZE INT NULL,
        REJ_GEN_ES_DOC_MIME_TYPE VARCHAR(50) NULL,
        IMP_GEN_NAME VARCHAR(80) NULL,
        IMP_GEN_ADDRESS VARCHAR(50) NULL,
        IMP_GEN_CITY VARCHAR(25) NULL,
        IMP_GEN_POSTAL_CODE VARCHAR(25) NULL,
        IMP_GEN_PROVINCE VARCHAR(50) NULL,
        IMP_GEN_CNTRY_CODE CHAR(2) NULL,
        IMP_GEN_CNTRY_NAME VARCHAR(100) NULL,
        IMP_PORT_CITY VARCHAR(25) NULL,
        IMP_PORT_STATE_CODE CHAR(2) NULL,
        IMP_PORT_STATE_NAME VARCHAR(100) NULL,
        PRINTED_DOC_NAME VARCHAR(255) NULL,
        PRINTED_DOC_SIZE INT NULL,
        PRINTED_DOC_MIME_TYPE VARCHAR(50) NULL,
        FORM_DOC_NAME VARCHAR(255) NULL,
        FORM_DOC_SIZE INT NULL,
        FORM_DOC_MIME_TYPE VARCHAR(50) NULL,
        ADD_INFO_NEW_MAN_DEST VARCHAR(255) NULL,
        ADD_INFO_CONSENT_NUM VARCHAR(255) NULL,
        ADD_INFO_HAND_INSTR VARCHAR(4000) NULL,
        CORR_VERSION_NUM INT NULL,
        CORR_ACTIVE_IND CHAR(1) NULL,
        CORR_EPA_SITE_ID VARCHAR(15) NULL,
        CORR_ES_SIGN_DATE datetime NULL,
        CORR_ES_CROMERR_ACT_ID VARCHAR(50) NULL,
        CORR_ES_CROMERR_DOC_ID VARCHAR(50) NULL,
        CORR_ES_SIGNER_FIRST_NAME VARCHAR(38) NULL,
        CORR_ES_SIGNER_LAST_NAME VARCHAR(38) NULL,
        CORR_ES_SIGNER_USER_ID VARCHAR(255) NULL,
        CORR_ES_DOC_NAME VARCHAR(255) NULL,
        CORR_ES_DOC_SIZE INT NULL,
        CORR_ES_DOC_MIME_TYPE VARCHAR(50) NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_EMANIFEST_COMMENT
IF OBJECT_ID(N'dbo.RCRA_EM_EMANIFEST_COMMENT') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_EMANIFEST_COMMENT
    (
        EM_EMANIFEST_COMMENT_ID VARCHAR(40) NOT NULL,
        EM_EMANIFEST_ID VARCHAR(40) NOT NULL,
        COMMENT_DESC VARCHAR(4000) NULL,
        HANDLER_ID VARCHAR(15) NULL,
        COMMENT_LABEL VARCHAR(255) NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_HANDLER
IF OBJECT_ID(N'dbo.RCRA_EM_HANDLER') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_HANDLER
    (
        EM_HANDLER_ID VARCHAR(40) NOT NULL,
        EM_EMANIFEST_ID VARCHAR(40) NOT NULL,
        SITE_TYPE VARCHAR(11) NOT NULL,
        EPA_SITE_ID VARCHAR(15) NULL,
        MANIFEST_NAME VARCHAR(80) NOT NULL,
        ORDER_NUM INT NULL,
        REG_IND CHAR(1) NULL,
        MOD_IND CHAR(1) NULL,
        MANIFEST_HANDLER_TYPE VARCHAR(40) NOT NULL,
        MAIL_STREET_NUM VARCHAR(12) NULL,
        MAIL_STREET1 VARCHAR(50) NULL,
        MAIL_STREET2 VARCHAR(50) NULL,
        MAIL_CITY VARCHAR(25) NULL,
        MAIL_ZIP VARCHAR(14) NULL,
        MAIL_CNTRY_CODE CHAR(2) NULL,
        MAIL_CNTRY_NAME VARCHAR(100) NULL,
        MAIL_STATE_CODE CHAR(2) NULL,
        MAIL_STATE_NAME VARCHAR(100) NULL,
        SITE_STREET_NUM VARCHAR(12) NULL,
        SITE_STREET1 VARCHAR(50) NULL,
        SITE_STREET2 VARCHAR(50) NULL,
        SITE_CITY VARCHAR(25) NULL,
        SITE_ZIP VARCHAR(14) NULL,
        SITE_CNTRY_CODE CHAR(2) NULL,
        SITE_CNTRY_NAME VARCHAR(100) NULL,
        SITE_STATE_CODE CHAR(2) NULL,
        SITE_STATE_NAME VARCHAR(100) NULL,
        CONTACT_FIRST_NAME VARCHAR(38) NULL,
        CONTACT_MIDDLE_INITIAL CHAR(1) NULL,
        CONTACT_LAST_NAME VARCHAR(38) NULL,
        CONTACT_EMAIL VARCHAR(80) NULL,
        CONTACT_COMPANY_NAME VARCHAR(80) NULL,
        CONTACT_PHONE_NUM VARCHAR(15) NULL,
        CONTACT_PHONE_EXT VARCHAR(6) NULL,
        EMERG_PHONE_NUM VARCHAR(15) NULL,
        EMERG_PHONE_EXT VARCHAR(6) NULL,
        PS_NAME VARCHAR(80) NULL,
        PS_DATE datetime NULL,
        ES_SIGN_DATE datetime NULL,
        ES_CROMERR_ACT_ID VARCHAR(50) NULL,
        ES_CROMERR_DOC_ID VARCHAR(50) NULL,
        ES_SIGNER_FIRST_NAME VARCHAR(38) NULL,
        ES_SIGNER_LAST_NAME VARCHAR(38) NULL,
        ES_SIGNER_USER_ID VARCHAR(255) NULL,
        ES_DOC_NAME VARCHAR(255) NULL,
        ES_DOC_SIZE INT NULL,
        ES_DOC_MIME_TYPE VARCHAR(50) NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_SUBM
IF OBJECT_ID(N'dbo.RCRA_EM_SUBM') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_SUBM
    (
        EM_SUBM_ID VARCHAR(40) NOT NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_TR_NUM_ORIG
IF OBJECT_ID(N'dbo.RCRA_EM_TR_NUM_ORIG') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_TR_NUM_ORIG
    (
        EM_TR_NUM_ORIG_ID VARCHAR(40) NOT NULL,
        EM_EMANIFEST_ID VARCHAR(40) NOT NULL,
        MANIFEST_TRACKING_NUM VARCHAR(12) NOT NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_TR_NUM_REJ
IF OBJECT_ID(N'dbo.RCRA_EM_TR_NUM_REJ') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_TR_NUM_REJ
    (
        EM_TR_NUM_REJ_ID VARCHAR(40) NOT NULL,
        EM_EMANIFEST_ID VARCHAR(40) NOT NULL,
        MANIFEST_TRACKING_NUM VARCHAR(12) NOT NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_TR_NUM_RESIDUE_NEW
IF OBJECT_ID(N'dbo.RCRA_EM_TR_NUM_RESIDUE_NEW') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_TR_NUM_RESIDUE_NEW
    (
        EM_TR_NUM_RESIDUE_NEW_ID VARCHAR(40) NOT NULL,
        EM_EMANIFEST_ID VARCHAR(40) NOT NULL,
        MANIFEST_TRACKING_NUM VARCHAR(12) NOT NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_TR_NUM_WASTE
IF OBJECT_ID(N'dbo.RCRA_EM_TR_NUM_WASTE') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_TR_NUM_WASTE
    (
        EM_TR_NUM_WASTE_ID VARCHAR(40) NOT NULL,
        EM_WASTE_ID VARCHAR(40) NOT NULL,
        MANIFEST_TRACKING_NUM VARCHAR(12) NOT NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_WASTE
IF OBJECT_ID(N'dbo.RCRA_EM_WASTE') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_WASTE
    (
        EM_WASTE_ID VARCHAR(40) NOT NULL,
        EM_EMANIFEST_ID VARCHAR(40) NOT NULL,
        DOT_HAZ_IND CHAR(1) NOT NULL,
        WASTES_DESC VARCHAR(500) NULL,
        BR_IND CHAR(1) NULL,
        PCB_IND CHAR(1) NOT NULL,
        LINE_NUM INT NOT NULL,
        EPA_WASTE_IND CHAR(1) NULL,
        DOT_ID_NUM VARCHAR(255) NULL,
        DOT_PRINTED_INFO VARCHAR(500) NULL,
        QNT_CONT_NUM INT NULL,
        QNT_VAL DECIMAL(14,6) NULL,
        QNT_CONT_TYPE_CODE VARCHAR(255) NULL,
        QNT_CONT_TYPE_DESC VARCHAR(255) NULL,
        QNT_UOM_CODE CHAR(1) NULL,
        QNT_UOM_DESC VARCHAR(28) NULL,
        BR_DENSITY DECIMAL(14,6) NULL,
        BR_DENSITY_UOM_CODE CHAR(1) NULL,
        BR_DENSITY_UOM_DESC VARCHAR(240) NULL,
        BR_FORM_CODE VARCHAR(4) NULL,
        BR_FORM_DESC VARCHAR(240) NULL,
        BR_SRC_CODE VARCHAR(3) NULL,
        BR_SRC_DESC VARCHAR(240) NULL,
        BR_WM_CODE CHAR(1) NULL,
        BR_WM_DESC VARCHAR(240) NULL,
        DISC_WASTE_QTY_IND CHAR(1) NULL,
        DISC_WASTE_TYPE_IND CHAR(1) NULL,
        DISC_COMMENTS VARCHAR(255) NULL,
        DISC_RESIDUE_IND CHAR(1) NULL,
        DISC_RESIDUE_COMMENTS VARCHAR(255) NULL,
        MGMT_METHOD_CODE VARCHAR(4) NULL,
        MGMT_METHOD_DESC VARCHAR(240) NULL,
        ADD_INFO_NEW_MAN_DEST VARCHAR(255) NULL,
        ADD_INFO_CONSENT_NUM VARCHAR(255) NULL,
        ADD_INFO_HAND_INSTR VARCHAR(4000) NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_WASTE_CD_FED
IF OBJECT_ID(N'dbo.RCRA_EM_WASTE_CD_FED') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_WASTE_CD_FED
    (
        EM_WASTE_CD_FED_ID VARCHAR(40) NOT NULL,
        EM_WASTE_ID VARCHAR(40) NOT NULL,
        WASTE_CODE VARCHAR(6) NOT NULL,
        WASTE_DESC VARCHAR(2000) NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_WASTE_CD_GEN
IF OBJECT_ID(N'dbo.RCRA_EM_WASTE_CD_GEN') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_WASTE_CD_GEN
    (
        EM_WASTE_CD_GEN_ID VARCHAR(40) NOT NULL,
        EM_WASTE_ID VARCHAR(40) NOT NULL,
        WASTE_CODE VARCHAR(6) NOT NULL,
        WASTE_DESC VARCHAR(2000) NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_WASTE_CD_TRANS
IF OBJECT_ID(N'dbo.RCRA_EM_WASTE_CD_TRANS') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_WASTE_CD_TRANS
    (
        EM_WASTE_CD_TRANS_ID VARCHAR(40) NOT NULL,
        EM_WASTE_ID VARCHAR(40) NOT NULL,
        WASTE_CODE VARCHAR(12) NOT NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_WASTE_CD_TSDF
IF OBJECT_ID(N'dbo.RCRA_EM_WASTE_CD_TSDF') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_WASTE_CD_TSDF
    (
        EM_WASTE_CD_TSDF_ID VARCHAR(40) NOT NULL,
        EM_WASTE_ID VARCHAR(40) NOT NULL,
        WASTE_CODE VARCHAR(6) NOT NULL,
        WASTE_DESC VARCHAR(2000) NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_WASTE_COMMENT
IF OBJECT_ID(N'dbo.RCRA_EM_WASTE_COMMENT') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_WASTE_COMMENT
    (
        EM_WASTE_COMMENT_ID VARCHAR(40) NOT NULL,
        EM_WASTE_ID VARCHAR(40) NOT NULL,
        COMMENT_DESC VARCHAR(4000) NULL,
        HANDLER_ID VARCHAR(15) NULL,
        COMMENT_LABEL VARCHAR(255) NULL
    )
    END
GO


---$ Create table dbo.RCRA_EM_WASTE_PCB
IF OBJECT_ID(N'dbo.RCRA_EM_WASTE_PCB') IS NULL
BEGIN
    CREATE TABLE dbo.RCRA_EM_WASTE_PCB
    (
        EM_WASTE_PCB_ID VARCHAR(40) NOT NULL,
        EM_WASTE_ID VARCHAR(40) NOT NULL,
        PCB_LOAD_TYPE_CODE VARCHAR(255) NULL,
        PCB_ARTICLE_CONT_ID VARCHAR(255) NULL,
        PCB_REMOVAL_DATE datetime NULL,
        PCB_WEIGHT DECIMAL(14,6) NULL,
        PCB_WASTE_TYPE VARCHAR(255) NULL,
        PCB_BULK_IDENTITY VARCHAR(255) NULL
    )
    END
GO


---$ Alter table dbo.RCRA_GIS_GEO_INFORMATION
ALTER TABLE dbo.RCRA_GIS_GEO_INFORMATION
    ALTER COLUMN AREA_MEAS_SRC_CODE VARCHAR(4) NULL
GO


---$ Alter table dbo.RCRA_HD_EPISODIC_WASTE
ALTER TABLE dbo.RCRA_HD_EPISODIC_WASTE
    ALTER COLUMN SEQ_NUMBER INT NOT NULL
GO


---$ Alter table dbo.RCRA_HD_HANDLER
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'ACKNOWLEDGE_FLAG_IND')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD ACKNOWLEDGE_FLAG_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'INCLUDE_IN_NATIONAL_REPORT_IND')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD INCLUDE_IN_NATIONAL_REPORT_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'LQHUW_IND')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD LQHUW_IND CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'HD_REPORT_CYCLE_YEAR')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD HD_REPORT_CYCLE_YEAR INT NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'HEALTHCARE_FAC')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD HEALTHCARE_FAC CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'REVERSE_DISTRIBUTOR')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD REVERSE_DISTRIBUTOR CHAR(1) NULL
END
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'SUBPART_P_WITHDRAWAL')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD SUBPART_P_WITHDRAWAL CHAR(1) NULL
END
GO

ALTER TABLE dbo.RCRA_HD_HANDLER
    ALTER COLUMN CONTACT_STREET1 VARCHAR(50) NULL
GO

ALTER TABLE dbo.RCRA_HD_HANDLER
    ALTER COLUMN CONTACT_STREET2 VARCHAR(50) NULL
GO

ALTER TABLE dbo.RCRA_HD_HANDLER
    ALTER COLUMN PCONTACT_STREET1 VARCHAR(50) NULL
GO

ALTER TABLE dbo.RCRA_HD_HANDLER
    ALTER COLUMN PCONTACT_STREET2 VARCHAR(50) NULL
GO

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'RECYCLER_IND')
BEGIN
    ALTER TABLE dbo.RCRA_HD_HANDLER
        ADD RECYCLER_IND CHAR(1) NULL
END
GO


---$ Alter table dbo.RCRA_HD_HBASIC
ALTER TABLE dbo.RCRA_HD_HBASIC
    ALTER COLUMN HANDLER_ID VARCHAR(12) NULL
GO


---$ Alter table dbo.RCRA_HD_LQG_CONSOLIDATION
ALTER TABLE dbo.RCRA_HD_LQG_CONSOLIDATION
    ALTER COLUMN HANDLER_ID VARCHAR(12) NULL
GO


---$ Alter table dbo.RCRA_HD_NAICS
ALTER TABLE dbo.RCRA_HD_NAICS
    ALTER COLUMN NAICS_SEQ VARCHAR(4) NOT NULL
GO


---$ Alter table dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY
ALTER TABLE dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY
    ALTER COLUMN TRANS_CODE CHAR(1) NULL
GO

ALTER TABLE dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY
    ALTER COLUMN HSM_SEQ_NUM VARCHAR(4) NOT NULL
GO

ALTER TABLE dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY
    ALTER COLUMN FAC_CODE_OWNER_NAME CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY
    ALTER COLUMN FAC_TYPE_CODE CHAR(2) NULL
GO

ALTER TABLE dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY
    ALTER COLUMN LAND_BASED_UNIT_IND CHAR(2) NULL
GO


---$ Alter table dbo.RCRA_RU_REPORT_UNIV
ALTER TABLE dbo.RCRA_RU_REPORT_UNIV
    ALTER COLUMN LOCATION_ZIP VARCHAR(14) NULL
GO


---$ Create Index/PK: IX_CA_AREA_CA_FAC_SUBM_ID, Table : dbo.RCRA_CA_AREA
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AREA') AND NAME = 'IX_CA_AREA_CA_FAC_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_CA_AREA_CA_FAC_SUBM_ID
        ON dbo.RCRA_CA_AREA(CA_FAC_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CA_AREA_REL_EVENT_CA_ARA_ID, Table : dbo.RCRA_CA_AREA_REL_EVENT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AREA_REL_EVENT') AND NAME = 'IX_CA_AREA_REL_EVENT_CA_ARA_ID')
    CREATE  NONCLUSTERED  INDEX IX_CA_AREA_REL_EVENT_CA_ARA_ID
        ON dbo.RCRA_CA_AREA_REL_EVENT(CA_AREA_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_CA_AREA_REL_EVENT, Table : dbo.RCRA_CA_AREA_REL_EVENT
IF OBJECT_ID(N'dbo.PK_CA_AREA_REL_EVENT') IS NULL
    ALTER TABLE dbo.RCRA_CA_AREA_REL_EVENT
        ADD CONSTRAINT PK_CA_AREA_REL_EVENT PRIMARY KEY CLUSTERED(CA_AREA_REL_EVENT_ID)
GO

---$ Create Index/PK: IX_CA_ATH_RL_EVNT_CA_ATHRTY_ID, Table : dbo.RCRA_CA_AUTH_REL_EVENT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AUTH_REL_EVENT') AND NAME = 'IX_CA_ATH_RL_EVNT_CA_ATHRTY_ID')
    CREATE  NONCLUSTERED  INDEX IX_CA_ATH_RL_EVNT_CA_ATHRTY_ID
        ON dbo.RCRA_CA_AUTH_REL_EVENT(CA_AUTHORITY_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_CA_AUTH_REL_EVENT, Table : dbo.RCRA_CA_AUTH_REL_EVENT
IF OBJECT_ID(N'dbo.PK_CA_AUTH_REL_EVENT') IS NULL
    ALTER TABLE dbo.RCRA_CA_AUTH_REL_EVENT
        ADD CONSTRAINT PK_CA_AUTH_REL_EVENT PRIMARY KEY CLUSTERED(CA_AUTH_REL_EVENT_ID)
GO

---$ Create Index/PK: IX_CA_AUTHORITY_CA_FAC_SUBM_ID, Table : dbo.RCRA_CA_AUTHORITY
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_AUTHORITY') AND NAME = 'IX_CA_AUTHORITY_CA_FAC_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_CA_AUTHORITY_CA_FAC_SUBM_ID
        ON dbo.RCRA_CA_AUTHORITY(CA_FAC_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CA_EVENT_CA_FAC_SUBM_ID, Table : dbo.RCRA_CA_EVENT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT') AND NAME = 'IX_CA_EVENT_CA_FAC_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_CA_EVENT_CA_FAC_SUBM_ID
        ON dbo.RCRA_CA_EVENT(CA_FAC_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CA_EVNT_COMMTMNT_CA_EVNT_ID, Table : dbo.RCRA_CA_EVENT_COMMITMENT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_EVENT_COMMITMENT') AND NAME = 'IX_CA_EVNT_COMMTMNT_CA_EVNT_ID')
    CREATE  NONCLUSTERED  INDEX IX_CA_EVNT_COMMTMNT_CA_EVNT_ID
        ON dbo.RCRA_CA_EVENT_COMMITMENT(CA_EVENT_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_CA_EVENT_COMMITMENT, Table : dbo.RCRA_CA_EVENT_COMMITMENT
IF OBJECT_ID(N'dbo.PK_CA_EVENT_COMMITMENT') IS NULL
    ALTER TABLE dbo.RCRA_CA_EVENT_COMMITMENT
        ADD CONSTRAINT PK_CA_EVENT_COMMITMENT PRIMARY KEY CLUSTERED(CA_EVENT_COMMITMENT_ID)
GO

---$ Create Index/PK: IX_CA_FAC_SUBM_CA_SUBM_ID, Table : dbo.RCRA_CA_FAC_SUBM
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_FAC_SUBM') AND NAME = 'IX_CA_FAC_SUBM_CA_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_CA_FAC_SUBM_CA_SUBM_ID
        ON dbo.RCRA_CA_FAC_SUBM(CA_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CA_REL_PERMIT_UNT_CA_ARA_ID, Table : dbo.RCRA_CA_REL_PERMIT_UNIT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_REL_PERMIT_UNIT') AND NAME = 'IX_CA_REL_PERMIT_UNT_CA_ARA_ID')
    CREATE  NONCLUSTERED  INDEX IX_CA_REL_PERMIT_UNT_CA_ARA_ID
        ON dbo.RCRA_CA_REL_PERMIT_UNIT(CA_AREA_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_CA_REL_PERMIT_UNIT, Table : dbo.RCRA_CA_REL_PERMIT_UNIT
IF OBJECT_ID(N'dbo.PK_CA_REL_PERMIT_UNIT') IS NULL
    ALTER TABLE dbo.RCRA_CA_REL_PERMIT_UNIT
        ADD CONSTRAINT PK_CA_REL_PERMIT_UNIT PRIMARY KEY CLUSTERED(CA_REL_PERMIT_UNIT_ID)
GO

---$ Create Index/PK: IX_CA_STTTRY_CTTN_CA_ATHRTY_ID, Table : dbo.RCRA_CA_STATUTORY_CITATION
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CA_STATUTORY_CITATION') AND NAME = 'IX_CA_STTTRY_CTTN_CA_ATHRTY_ID')
    CREATE  NONCLUSTERED  INDEX IX_CA_STTTRY_CTTN_CA_ATHRTY_ID
        ON dbo.RCRA_CA_STATUTORY_CITATION(CA_AUTHORITY_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_CA_STATUTORY_CITATION, Table : dbo.RCRA_CA_STATUTORY_CITATION
IF OBJECT_ID(N'dbo.PK_CA_STATUTORY_CITATION') IS NULL
    ALTER TABLE dbo.RCRA_CA_STATUTORY_CITATION
        ADD CONSTRAINT PK_CA_STATUTORY_CITATION PRIMARY KEY CLUSTERED(CA_STATUTORY_CITATION_ID)
GO

---$ Create Index/PK: IX_CME_CITATION_CME_VIOL_ID, Table : dbo.RCRA_CME_CITATION
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_CITATION') AND NAME = 'IX_CME_CITATION_CME_VIOL_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_CITATION_CME_VIOL_ID
        ON dbo.RCRA_CME_CITATION(CME_VIOL_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_CSNY_DTE_CME_ENF_ACT_ID, Table : dbo.RCRA_CME_CSNY_DATE
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_CSNY_DATE') AND NAME = 'IX_CME_CSNY_DTE_CME_ENF_ACT_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_CSNY_DTE_CME_ENF_ACT_ID
        ON dbo.RCRA_CME_CSNY_DATE(CME_ENFRC_ACT_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_ENFRC_ACT_CME_FC_SBM_ID, Table : dbo.RCRA_CME_ENFRC_ACT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_ENFRC_ACT') AND NAME = 'IX_CME_ENFRC_ACT_CME_FC_SBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_ENFRC_ACT_CME_FC_SBM_ID
        ON dbo.RCRA_CME_ENFRC_ACT(CME_FAC_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_EVAL_CME_FAC_SUBM_ID, Table : dbo.RCRA_CME_EVAL
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL') AND NAME = 'IX_CME_EVAL_CME_FAC_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_EVAL_CME_FAC_SUBM_ID
        ON dbo.RCRA_CME_EVAL(CME_FAC_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_EVAL_COMMIT_CME_EVAL_ID, Table : dbo.RCRA_CME_EVAL_COMMIT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL_COMMIT') AND NAME = 'IX_CME_EVAL_COMMIT_CME_EVAL_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_EVAL_COMMIT_CME_EVAL_ID
        ON dbo.RCRA_CME_EVAL_COMMIT(CME_EVAL_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_EVAL_VIOL_CME_EVAL_ID, Table : dbo.RCRA_CME_EVAL_VIOL
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_EVAL_VIOL') AND NAME = 'IX_CME_EVAL_VIOL_CME_EVAL_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_EVAL_VIOL_CME_EVAL_ID
        ON dbo.RCRA_CME_EVAL_VIOL(CME_EVAL_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_FAC_SUBM_CME_SUBM_ID, Table : dbo.RCRA_CME_FAC_SUBM
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_FAC_SUBM') AND NAME = 'IX_CME_FAC_SUBM_CME_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_FAC_SUBM_CME_SUBM_ID
        ON dbo.RCRA_CME_FAC_SUBM(CME_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_MEDIA_CME_ENFRC_ACT_ID, Table : dbo.RCRA_CME_MEDIA
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_MEDIA') AND NAME = 'IX_CME_MEDIA_CME_ENFRC_ACT_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_MEDIA_CME_ENFRC_ACT_ID
        ON dbo.RCRA_CME_MEDIA(CME_ENFRC_ACT_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_MLSTNE_CME_ENFRC_ACT_ID, Table : dbo.RCRA_CME_MILESTONE
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_MILESTONE') AND NAME = 'IX_CME_MLSTNE_CME_ENFRC_ACT_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_MLSTNE_CME_ENFRC_ACT_ID
        ON dbo.RCRA_CME_MILESTONE(CME_ENFRC_ACT_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_PNLTY_CME_ENFRC_ACT_ID, Table : dbo.RCRA_CME_PNLTY
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_PNLTY') AND NAME = 'IX_CME_PNLTY_CME_ENFRC_ACT_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_PNLTY_CME_ENFRC_ACT_ID
        ON dbo.RCRA_CME_PNLTY(CME_ENFRC_ACT_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_PYMT_CME_PNLTY_ID, Table : dbo.RCRA_CME_PYMT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_PYMT') AND NAME = 'IX_CME_PYMT_CME_PNLTY_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_PYMT_CME_PNLTY_ID
        ON dbo.RCRA_CME_PYMT(CME_PNLTY_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_RQST_CME_EVAL_ID, Table : dbo.RCRA_CME_RQST
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_RQST') AND NAME = 'IX_CME_RQST_CME_EVAL_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_RQST_CME_EVAL_ID
        ON dbo.RCRA_CME_RQST(CME_EVAL_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_SPP_ENV_PRJ_CM_EN_AC_ID, Table : dbo.RCRA_CME_SUPP_ENVR_PRJT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_SUPP_ENVR_PRJT') AND NAME = 'IX_CME_SPP_ENV_PRJ_CM_EN_AC_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_SPP_ENV_PRJ_CM_EN_AC_ID
        ON dbo.RCRA_CME_SUPP_ENVR_PRJT(CME_ENFRC_ACT_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_CME_SUPP_ENVR_PRJT, Table : dbo.RCRA_CME_SUPP_ENVR_PRJT
IF OBJECT_ID(N'dbo.PK_CME_SUPP_ENVR_PRJT') IS NULL
    ALTER TABLE dbo.RCRA_CME_SUPP_ENVR_PRJT
        ADD CONSTRAINT PK_CME_SUPP_ENVR_PRJT PRIMARY KEY CLUSTERED(CME_SUPP_ENVR_PRJT_ID)
GO

---$ Create Index/PK: IX_CME_VIOL_CME_FAC_SUBM_ID, Table : dbo.RCRA_CME_VIOL
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_VIOL') AND NAME = 'IX_CME_VIOL_CME_FAC_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_VIOL_CME_FAC_SUBM_ID
        ON dbo.RCRA_CME_VIOL(CME_FAC_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_CME_VL_ENFR_CME_ENFR_ACT_ID, Table : dbo.RCRA_CME_VIOL_ENFRC
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_CME_VIOL_ENFRC') AND NAME = 'IX_CME_VL_ENFR_CME_ENFR_ACT_ID')
    CREATE  NONCLUSTERED  INDEX IX_CME_VL_ENFR_CME_ENFR_ACT_ID
        ON dbo.RCRA_CME_VIOL_ENFRC(CME_ENFRC_ACT_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_EM_EMANIFEST_EM_SUBM_ID, Table : dbo.RCRA_EM_EMANIFEST
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_EMANIFEST') AND NAME = 'IX_EM_EMANIFEST_EM_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_EMANIFEST_EM_SUBM_ID
        ON dbo.RCRA_EM_EMANIFEST(EM_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_EMANIFEST, Table : dbo.RCRA_EM_EMANIFEST
IF OBJECT_ID(N'dbo.PK_EM_EMANIFEST') IS NULL
    ALTER TABLE dbo.RCRA_EM_EMANIFEST
        ADD CONSTRAINT PK_EM_EMANIFEST PRIMARY KEY CLUSTERED(EM_EMANIFEST_ID)
GO

---$ Create Index/PK: IX_EM_EMNFST_CMMNT_EM_EMNFS_ID, Table : dbo.RCRA_EM_EMANIFEST_COMMENT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_EMANIFEST_COMMENT') AND NAME = 'IX_EM_EMNFST_CMMNT_EM_EMNFS_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_EMNFST_CMMNT_EM_EMNFS_ID
        ON dbo.RCRA_EM_EMANIFEST_COMMENT(EM_EMANIFEST_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_EMANIFEST_COMMENT, Table : dbo.RCRA_EM_EMANIFEST_COMMENT
IF OBJECT_ID(N'dbo.PK_EM_EMANIFEST_COMMENT') IS NULL
    ALTER TABLE dbo.RCRA_EM_EMANIFEST_COMMENT
        ADD CONSTRAINT PK_EM_EMANIFEST_COMMENT PRIMARY KEY CLUSTERED(EM_EMANIFEST_COMMENT_ID)
GO

---$ Create Index/PK: IX_EM_HANDLER_EM_EMANIFEST_ID, Table : dbo.RCRA_EM_HANDLER
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_HANDLER') AND NAME = 'IX_EM_HANDLER_EM_EMANIFEST_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_HANDLER_EM_EMANIFEST_ID
        ON dbo.RCRA_EM_HANDLER(EM_EMANIFEST_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_HANDLER, Table : dbo.RCRA_EM_HANDLER
IF OBJECT_ID(N'dbo.PK_EM_HANDLER') IS NULL
    ALTER TABLE dbo.RCRA_EM_HANDLER
        ADD CONSTRAINT PK_EM_HANDLER PRIMARY KEY CLUSTERED(EM_HANDLER_ID)
GO

---$ Create Index/PK: PK_EM_SUBM, Table : dbo.RCRA_EM_SUBM
IF OBJECT_ID(N'dbo.PK_EM_SUBM') IS NULL
    ALTER TABLE dbo.RCRA_EM_SUBM
        ADD CONSTRAINT PK_EM_SUBM PRIMARY KEY CLUSTERED(EM_SUBM_ID)
GO

---$ Create Index/PK: IX_EM_TR_NM_EMNFST_EM_EMNFS_ID, Table : dbo.RCRA_EM_TR_NUM_ORIG
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_TR_NUM_ORIG') AND NAME = 'IX_EM_TR_NM_EMNFST_EM_EMNFS_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_TR_NM_EMNFST_EM_EMNFS_ID
        ON dbo.RCRA_EM_TR_NUM_ORIG(EM_EMANIFEST_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_TR_NUM_ORIG, Table : dbo.RCRA_EM_TR_NUM_ORIG
IF OBJECT_ID(N'dbo.PK_EM_TR_NUM_ORIG') IS NULL
    ALTER TABLE dbo.RCRA_EM_TR_NUM_ORIG
        ADD CONSTRAINT PK_EM_TR_NUM_ORIG PRIMARY KEY CLUSTERED(EM_TR_NUM_ORIG_ID)
GO

---$ Create Index/PK: IX_EM_TR_NUM_RJ_EM_EMNIFEST_ID, Table : dbo.RCRA_EM_TR_NUM_REJ
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_TR_NUM_REJ') AND NAME = 'IX_EM_TR_NUM_RJ_EM_EMNIFEST_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_TR_NUM_RJ_EM_EMNIFEST_ID
        ON dbo.RCRA_EM_TR_NUM_REJ(EM_EMANIFEST_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_TR_NUM_REJ, Table : dbo.RCRA_EM_TR_NUM_REJ
IF OBJECT_ID(N'dbo.PK_EM_TR_NUM_REJ') IS NULL
    ALTER TABLE dbo.RCRA_EM_TR_NUM_REJ
        ADD CONSTRAINT PK_EM_TR_NUM_REJ PRIMARY KEY CLUSTERED(EM_TR_NUM_REJ_ID)
GO

---$ Create Index/PK: IX_EM_TR_NM_RSDE_NW_EM_EMNF_ID, Table : dbo.RCRA_EM_TR_NUM_RESIDUE_NEW
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_TR_NUM_RESIDUE_NEW') AND NAME = 'IX_EM_TR_NM_RSDE_NW_EM_EMNF_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_TR_NM_RSDE_NW_EM_EMNF_ID
        ON dbo.RCRA_EM_TR_NUM_RESIDUE_NEW(EM_EMANIFEST_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_TR_NUM_RESIDUE_NEW, Table : dbo.RCRA_EM_TR_NUM_RESIDUE_NEW
IF OBJECT_ID(N'dbo.PK_EM_TR_NUM_RESIDUE_NEW') IS NULL
    ALTER TABLE dbo.RCRA_EM_TR_NUM_RESIDUE_NEW
        ADD CONSTRAINT PK_EM_TR_NUM_RESIDUE_NEW PRIMARY KEY CLUSTERED(EM_TR_NUM_RESIDUE_NEW_ID)
GO

---$ Create Index/PK: IX_EM_TR_NUM_WASTE_EM_WASTE_ID, Table : dbo.RCRA_EM_TR_NUM_WASTE
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_TR_NUM_WASTE') AND NAME = 'IX_EM_TR_NUM_WASTE_EM_WASTE_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_TR_NUM_WASTE_EM_WASTE_ID
        ON dbo.RCRA_EM_TR_NUM_WASTE(EM_WASTE_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_TR_NUM_WASTE, Table : dbo.RCRA_EM_TR_NUM_WASTE
IF OBJECT_ID(N'dbo.PK_EM_TR_NUM_WASTE') IS NULL
    ALTER TABLE dbo.RCRA_EM_TR_NUM_WASTE
        ADD CONSTRAINT PK_EM_TR_NUM_WASTE PRIMARY KEY CLUSTERED(EM_TR_NUM_WASTE_ID)
GO

---$ Create Index/PK: IX_EM_WASTE_EM_EMANIFEST_ID, Table : dbo.RCRA_EM_WASTE
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_WASTE') AND NAME = 'IX_EM_WASTE_EM_EMANIFEST_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_WASTE_EM_EMANIFEST_ID
        ON dbo.RCRA_EM_WASTE(EM_EMANIFEST_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_WASTE, Table : dbo.RCRA_EM_WASTE
IF OBJECT_ID(N'dbo.PK_EM_WASTE') IS NULL
    ALTER TABLE dbo.RCRA_EM_WASTE
        ADD CONSTRAINT PK_EM_WASTE PRIMARY KEY CLUSTERED(EM_WASTE_ID)
GO

---$ Create Index/PK: IX_EM_WASTE_CD_FED_EM_WASTE_ID, Table : dbo.RCRA_EM_WASTE_CD_FED
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_WASTE_CD_FED') AND NAME = 'IX_EM_WASTE_CD_FED_EM_WASTE_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_WASTE_CD_FED_EM_WASTE_ID
        ON dbo.RCRA_EM_WASTE_CD_FED(EM_WASTE_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_WASTE_CD_FED, Table : dbo.RCRA_EM_WASTE_CD_FED
IF OBJECT_ID(N'dbo.PK_EM_WASTE_CD_FED') IS NULL
    ALTER TABLE dbo.RCRA_EM_WASTE_CD_FED
        ADD CONSTRAINT PK_EM_WASTE_CD_FED PRIMARY KEY CLUSTERED(EM_WASTE_CD_FED_ID)
GO

---$ Create Index/PK: IX_EM_WASTE_CD_GEN_EM_WASTE_ID, Table : dbo.RCRA_EM_WASTE_CD_GEN
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_WASTE_CD_GEN') AND NAME = 'IX_EM_WASTE_CD_GEN_EM_WASTE_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_WASTE_CD_GEN_EM_WASTE_ID
        ON dbo.RCRA_EM_WASTE_CD_GEN(EM_WASTE_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_WASTE_CD_GEN, Table : dbo.RCRA_EM_WASTE_CD_GEN
IF OBJECT_ID(N'dbo.PK_EM_WASTE_CD_GEN') IS NULL
    ALTER TABLE dbo.RCRA_EM_WASTE_CD_GEN
        ADD CONSTRAINT PK_EM_WASTE_CD_GEN PRIMARY KEY CLUSTERED(EM_WASTE_CD_GEN_ID)
GO

---$ Create Index/PK: IX_EM_WASTE_CD_TRNS_EM_WSTE_ID, Table : dbo.RCRA_EM_WASTE_CD_TRANS
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_WASTE_CD_TRANS') AND NAME = 'IX_EM_WASTE_CD_TRNS_EM_WSTE_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_WASTE_CD_TRNS_EM_WSTE_ID
        ON dbo.RCRA_EM_WASTE_CD_TRANS(EM_WASTE_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_WASTE_CD_TRANS, Table : dbo.RCRA_EM_WASTE_CD_TRANS
IF OBJECT_ID(N'dbo.PK_EM_WASTE_CD_TRANS') IS NULL
    ALTER TABLE dbo.RCRA_EM_WASTE_CD_TRANS
        ADD CONSTRAINT PK_EM_WASTE_CD_TRANS PRIMARY KEY CLUSTERED(EM_WASTE_CD_TRANS_ID)
GO

---$ Create Index/PK: IX_EM_WASTE_CD_TSDF_EM_WSTE_ID, Table : dbo.RCRA_EM_WASTE_CD_TSDF
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_WASTE_CD_TSDF') AND NAME = 'IX_EM_WASTE_CD_TSDF_EM_WSTE_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_WASTE_CD_TSDF_EM_WSTE_ID
        ON dbo.RCRA_EM_WASTE_CD_TSDF(EM_WASTE_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_WASTE_CD_TSDF, Table : dbo.RCRA_EM_WASTE_CD_TSDF
IF OBJECT_ID(N'dbo.PK_EM_WASTE_CD_TSDF') IS NULL
    ALTER TABLE dbo.RCRA_EM_WASTE_CD_TSDF
        ADD CONSTRAINT PK_EM_WASTE_CD_TSDF PRIMARY KEY CLUSTERED(EM_WASTE_CD_TSDF_ID)
GO

---$ Create Index/PK: IX_EM_WASTE_COMMENT_EM_WSTE_ID, Table : dbo.RCRA_EM_WASTE_COMMENT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_WASTE_COMMENT') AND NAME = 'IX_EM_WASTE_COMMENT_EM_WSTE_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_WASTE_COMMENT_EM_WSTE_ID
        ON dbo.RCRA_EM_WASTE_COMMENT(EM_WASTE_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_WASTE_COMMENT, Table : dbo.RCRA_EM_WASTE_COMMENT
IF OBJECT_ID(N'dbo.PK_EM_WASTE_COMMENT') IS NULL
    ALTER TABLE dbo.RCRA_EM_WASTE_COMMENT
        ADD CONSTRAINT PK_EM_WASTE_COMMENT PRIMARY KEY CLUSTERED(EM_WASTE_COMMENT_ID)
GO

---$ Create Index/PK: IX_EM_WASTE_PCB_EM_WASTE_ID, Table : dbo.RCRA_EM_WASTE_PCB
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_EM_WASTE_PCB') AND NAME = 'IX_EM_WASTE_PCB_EM_WASTE_ID')
    CREATE  NONCLUSTERED  INDEX IX_EM_WASTE_PCB_EM_WASTE_ID
        ON dbo.RCRA_EM_WASTE_PCB(EM_WASTE_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_EM_WASTE_PCB, Table : dbo.RCRA_EM_WASTE_PCB
IF OBJECT_ID(N'dbo.PK_EM_WASTE_PCB') IS NULL
    ALTER TABLE dbo.RCRA_EM_WASTE_PCB
        ADD CONSTRAINT PK_EM_WASTE_PCB PRIMARY KEY CLUSTERED(EM_WASTE_PCB_ID)
GO

---$ Create Index/PK: IX_FA_COST_EST_FA_FAC_SUBM_ID, Table : dbo.RCRA_FA_COST_EST
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST') AND NAME = 'IX_FA_COST_EST_FA_FAC_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_FA_COST_EST_FA_FAC_SUBM_ID
        ON dbo.RCRA_FA_COST_EST(FA_FAC_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_FA_CST_ES_RL_MC_FA_CS_ES_ID, Table : dbo.RCRA_FA_COST_EST_REL_MECHANISM
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_COST_EST_REL_MECHANISM') AND NAME = 'IX_FA_CST_ES_RL_MC_FA_CS_ES_ID')
    CREATE  NONCLUSTERED  INDEX IX_FA_CST_ES_RL_MC_FA_CS_ES_ID
        ON dbo.RCRA_FA_COST_EST_REL_MECHANISM(FA_COST_EST_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_FA_COST_EST_REL_MECHANISM, Table : dbo.RCRA_FA_COST_EST_REL_MECHANISM
IF OBJECT_ID(N'dbo.PK_FA_COST_EST_REL_MECHANISM') IS NULL
    ALTER TABLE dbo.RCRA_FA_COST_EST_REL_MECHANISM
        ADD CONSTRAINT PK_FA_COST_EST_REL_MECHANISM PRIMARY KEY CLUSTERED(FA_COST_EST_REL_MECHANISM_ID)
GO

---$ Create Index/PK: IX_FA_FAC_SUBM_FA_SUBM_ID, Table : dbo.RCRA_FA_FAC_SUBM
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_FAC_SUBM') AND NAME = 'IX_FA_FAC_SUBM_FA_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_FA_FAC_SUBM_FA_SUBM_ID
        ON dbo.RCRA_FA_FAC_SUBM(FA_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_FA_MECHANISM_FA_FAC_SUBM_ID, Table : dbo.RCRA_FA_MECHANISM
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM') AND NAME = 'IX_FA_MECHANISM_FA_FAC_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_FA_MECHANISM_FA_FAC_SUBM_ID
        ON dbo.RCRA_FA_MECHANISM(FA_FAC_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_FA_MCHNISM_DTL_FA_MCHNSM_ID, Table : dbo.RCRA_FA_MECHANISM_DETAIL
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_FA_MECHANISM_DETAIL') AND NAME = 'IX_FA_MCHNISM_DTL_FA_MCHNSM_ID')
    CREATE  NONCLUSTERED  INDEX IX_FA_MCHNISM_DTL_FA_MCHNSM_ID
        ON dbo.RCRA_FA_MECHANISM_DETAIL(FA_MECHANISM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_FA_MECHANISM_DETAIL, Table : dbo.RCRA_FA_MECHANISM_DETAIL
IF OBJECT_ID(N'dbo.PK_FA_MECHANISM_DETAIL') IS NULL
    ALTER TABLE dbo.RCRA_FA_MECHANISM_DETAIL
        ADD CONSTRAINT PK_FA_MECHANISM_DETAIL PRIMARY KEY CLUSTERED(FA_MECHANISM_DETAIL_ID)
GO

---$ Create Index/PK: IX_GIS_FAC_SUBM_GIS_SUBM_ID, Table : dbo.RCRA_GIS_FAC_SUBM
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_GIS_FAC_SUBM') AND NAME = 'IX_GIS_FAC_SUBM_GIS_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_GIS_FAC_SUBM_GIS_SUBM_ID
        ON dbo.RCRA_GIS_FAC_SUBM(GIS_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_GS_GO_INFORMTN_GS_FC_SBM_ID, Table : dbo.RCRA_GIS_GEO_INFORMATION
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_GIS_GEO_INFORMATION') AND NAME = 'IX_GS_GO_INFORMTN_GS_FC_SBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_GS_GO_INFORMTN_GS_FC_SBM_ID
        ON dbo.RCRA_GIS_GEO_INFORMATION(GIS_FAC_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_GIS_GEO_INFORMATION, Table : dbo.RCRA_GIS_GEO_INFORMATION
IF OBJECT_ID(N'dbo.PK_GIS_GEO_INFORMATION') IS NULL
    ALTER TABLE dbo.RCRA_GIS_GEO_INFORMATION
        ADD CONSTRAINT PK_GIS_GEO_INFORMATION PRIMARY KEY CLUSTERED(GIS_GEO_INFORMATION_ID)
GO

---$ Create Index/PK: IX_HD_CERTIFICATIO_HD_HANDL_ID, Table : dbo.RCRA_HD_CERTIFICATION
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_CERTIFICATION') AND NAME = 'IX_HD_CERTIFICATIO_HD_HANDL_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_CERTIFICATIO_HD_HANDL_ID
        ON dbo.RCRA_HD_CERTIFICATION(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_HD_CERTIFICATION, Table : dbo.RCRA_HD_CERTIFICATION
IF OBJECT_ID(N'dbo.PK_HD_CERTIFICATION') IS NULL
    ALTER TABLE dbo.RCRA_HD_CERTIFICATION
        ADD CONSTRAINT PK_HD_CERTIFICATION PRIMARY KEY CLUSTERED(HD_CERTIFICATION_ID)
GO

---$ Create Index/PK: IX_HD_ENV_PERMIT_HD_HANDLER_ID, Table : dbo.RCRA_HD_ENV_PERMIT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_ENV_PERMIT') AND NAME = 'IX_HD_ENV_PERMIT_HD_HANDLER_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_ENV_PERMIT_HD_HANDLER_ID
        ON dbo.RCRA_HD_ENV_PERMIT(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_EPISOD_EVENT_HD_HANDL_ID, Table : dbo.RCRA_HD_EPISODIC_EVENT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_EPISODIC_EVENT') AND NAME = 'IX_HD_EPISOD_EVENT_HD_HANDL_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_EPISOD_EVENT_HD_HANDL_ID
        ON dbo.RCRA_HD_EPISODIC_EVENT(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_EPIS_WAST_HD_EPIS_EVE_ID, Table : dbo.RCRA_HD_EPISODIC_WASTE
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_EPISODIC_WASTE') AND NAME = 'IX_HD_EPIS_WAST_HD_EPIS_EVE_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_EPIS_WAST_HD_EPIS_EVE_ID
        ON dbo.RCRA_HD_EPISODIC_WASTE(HD_EPISODIC_EVENT_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_EPI_WAS_COD_HD_EPI_WA_ID, Table : dbo.RCRA_HD_EPISODIC_WASTE_CODE
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_EPISODIC_WASTE_CODE') AND NAME = 'IX_HD_EPI_WAS_COD_HD_EPI_WA_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_EPI_WAS_COD_HD_EPI_WA_ID
        ON dbo.RCRA_HD_EPISODIC_WASTE_CODE(HD_EPISODIC_WASTE_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_HANDLER_HD_HBASIC_ID, Table : dbo.RCRA_HD_HANDLER
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HANDLER') AND NAME = 'IX_HD_HANDLER_HD_HBASIC_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_HANDLER_HD_HBASIC_ID
        ON dbo.RCRA_HD_HANDLER(HD_HBASIC_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_HBASIC_HD_SUBM_ID, Table : dbo.RCRA_HD_HBASIC
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_HBASIC') AND NAME = 'IX_HD_HBASIC_HD_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_HBASIC_HD_SUBM_ID
        ON dbo.RCRA_HD_HBASIC(HD_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_LQG_CLOSURE_HD_HANDLE_ID, Table : dbo.RCRA_HD_LQG_CLOSURE
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_LQG_CLOSURE') AND NAME = 'IX_HD_LQG_CLOSURE_HD_HANDLE_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_LQG_CLOSURE_HD_HANDLE_ID
        ON dbo.RCRA_HD_LQG_CLOSURE(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_LQG_CONSOLID_HD_HANDL_ID, Table : dbo.RCRA_HD_LQG_CONSOLIDATION
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_LQG_CONSOLIDATION') AND NAME = 'IX_HD_LQG_CONSOLID_HD_HANDL_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_LQG_CONSOLID_HD_HANDL_ID
        ON dbo.RCRA_HD_LQG_CONSOLIDATION(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_NAICS_HD_HANDLER_ID, Table : dbo.RCRA_HD_NAICS
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_NAICS') AND NAME = 'IX_HD_NAICS_HD_HANDLER_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_NAICS_HD_HANDLER_ID
        ON dbo.RCRA_HD_NAICS(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_OTHER_ID_HD_HBASIC_ID, Table : dbo.RCRA_HD_OTHER_ID
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_OTHER_ID') AND NAME = 'IX_HD_OTHER_ID_HD_HBASIC_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_OTHER_ID_HD_HBASIC_ID
        ON dbo.RCRA_HD_OTHER_ID(HD_HBASIC_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_OWNEROP_HD_HANDLER_ID, Table : dbo.RCRA_HD_OWNEROP
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_OWNEROP') AND NAME = 'IX_HD_OWNEROP_HD_HANDLER_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_OWNEROP_HD_HANDLER_ID
        ON dbo.RCRA_HD_OWNEROP(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_SEC_MATE_ACTI_HD_HAND_ID, Table : dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY') AND NAME = 'IX_HD_SEC_MATE_ACTI_HD_HAND_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_SEC_MATE_ACTI_HD_HAND_ID
        ON dbo.RCRA_HD_SEC_MATERIAL_ACTIVITY(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_HD_SEC_WA_CO_HD_SE_MA_AC_ID, Table : dbo.RCRA_HD_SEC_WASTE_CODE
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_SEC_WASTE_CODE') AND NAME = 'IX_HD_SEC_WA_CO_HD_SE_MA_AC_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_SEC_WA_CO_HD_SE_MA_AC_ID
        ON dbo.RCRA_HD_SEC_WASTE_CODE(HD_SEC_MATERIAL_ACTIVITY_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_HD_SEC_WASTE_CODE, Table : dbo.RCRA_HD_SEC_WASTE_CODE
IF OBJECT_ID(N'dbo.PK_HD_SEC_WASTE_CODE') IS NULL
    ALTER TABLE dbo.RCRA_HD_SEC_WASTE_CODE
        ADD CONSTRAINT PK_HD_SEC_WASTE_CODE PRIMARY KEY CLUSTERED(HD_SEC_WASTE_CODE_ID)
GO

---$ Create Index/PK: IX_HD_STATE_ACTIVI_HD_HANDL_ID, Table : dbo.RCRA_HD_STATE_ACTIVITY
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_STATE_ACTIVITY') AND NAME = 'IX_HD_STATE_ACTIVI_HD_HANDL_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_STATE_ACTIVI_HD_HANDL_ID
        ON dbo.RCRA_HD_STATE_ACTIVITY(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_HD_STATE_ACTIVITY, Table : dbo.RCRA_HD_STATE_ACTIVITY
IF OBJECT_ID(N'dbo.PK_HD_STATE_ACTIVITY') IS NULL
    ALTER TABLE dbo.RCRA_HD_STATE_ACTIVITY
        ADD CONSTRAINT PK_HD_STATE_ACTIVITY PRIMARY KEY CLUSTERED(HD_STATE_ACTIVITY_ID)
GO

---$ Create Index/PK: IX_HD_UNIVER_WASTE_HD_HANDL_ID, Table : dbo.RCRA_HD_UNIVERSAL_WASTE
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_UNIVERSAL_WASTE') AND NAME = 'IX_HD_UNIVER_WASTE_HD_HANDL_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_UNIVER_WASTE_HD_HANDL_ID
        ON dbo.RCRA_HD_UNIVERSAL_WASTE(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_HD_UNIVERSAL_WASTE, Table : dbo.RCRA_HD_UNIVERSAL_WASTE
IF OBJECT_ID(N'dbo.PK_HD_UNIVERSAL_WASTE') IS NULL
    ALTER TABLE dbo.RCRA_HD_UNIVERSAL_WASTE
        ADD CONSTRAINT PK_HD_UNIVERSAL_WASTE PRIMARY KEY CLUSTERED(HD_UNIVERSAL_WASTE_ID)
GO

---$ Create Index/PK: IX_HD_WASTE_CODE_HD_HANDLER_ID, Table : dbo.RCRA_HD_WASTE_CODE
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_HD_WASTE_CODE') AND NAME = 'IX_HD_WASTE_CODE_HD_HANDLER_ID')
    CREATE  NONCLUSTERED  INDEX IX_HD_WASTE_CODE_HD_HANDLER_ID
        ON dbo.RCRA_HD_WASTE_CODE(HD_HANDLER_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_PRM_EVENT_PRM_SERIES_ID, Table : dbo.RCRA_PRM_EVENT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_EVENT') AND NAME = 'IX_PRM_EVENT_PRM_SERIES_ID')
    CREATE  NONCLUSTERED  INDEX IX_PRM_EVENT_PRM_SERIES_ID
        ON dbo.RCRA_PRM_EVENT(PRM_SERIES_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_PRM_EVNT_CMMTMN_PRM_EVNT_ID, Table : dbo.RCRA_PRM_EVENT_COMMITMENT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_EVENT_COMMITMENT') AND NAME = 'IX_PRM_EVNT_CMMTMN_PRM_EVNT_ID')
    CREATE  NONCLUSTERED  INDEX IX_PRM_EVNT_CMMTMN_PRM_EVNT_ID
        ON dbo.RCRA_PRM_EVENT_COMMITMENT(PRM_EVENT_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_PRM_EVENT_COMMITMENT, Table : dbo.RCRA_PRM_EVENT_COMMITMENT
IF OBJECT_ID(N'dbo.PK_PRM_EVENT_COMMITMENT') IS NULL
    ALTER TABLE dbo.RCRA_PRM_EVENT_COMMITMENT
        ADD CONSTRAINT PK_PRM_EVENT_COMMITMENT PRIMARY KEY CLUSTERED(PRM_EVENT_COMMITMENT_ID)
GO

---$ Create Index/PK: IX_PRM_FAC_SUBM_PRM_SUBM_ID, Table : dbo.RCRA_PRM_FAC_SUBM
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_FAC_SUBM') AND NAME = 'IX_PRM_FAC_SUBM_PRM_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_PRM_FAC_SUBM_PRM_SUBM_ID
        ON dbo.RCRA_PRM_FAC_SUBM(PRM_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_PRM_RLTD_EVN_PRM_UNT_DTL_ID, Table : dbo.RCRA_PRM_RELATED_EVENT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_RELATED_EVENT') AND NAME = 'IX_PRM_RLTD_EVN_PRM_UNT_DTL_ID')
    CREATE  NONCLUSTERED  INDEX IX_PRM_RLTD_EVN_PRM_UNT_DTL_ID
        ON dbo.RCRA_PRM_RELATED_EVENT(PRM_UNIT_DETAIL_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_PRM_RELATED_EVENT, Table : dbo.RCRA_PRM_RELATED_EVENT
IF OBJECT_ID(N'dbo.PK_PRM_RELATED_EVENT') IS NULL
    ALTER TABLE dbo.RCRA_PRM_RELATED_EVENT
        ADD CONSTRAINT PK_PRM_RELATED_EVENT PRIMARY KEY CLUSTERED(PRM_RELATED_EVENT_ID)
GO

---$ Create Index/PK: IX_PRM_SERIES_PRM_FAC_SUBM_ID, Table : dbo.RCRA_PRM_SERIES
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_SERIES') AND NAME = 'IX_PRM_SERIES_PRM_FAC_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_PRM_SERIES_PRM_FAC_SUBM_ID
        ON dbo.RCRA_PRM_SERIES(PRM_FAC_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_PRM_UNIT_PRM_FAC_SUBM_ID, Table : dbo.RCRA_PRM_UNIT
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT') AND NAME = 'IX_PRM_UNIT_PRM_FAC_SUBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_PRM_UNIT_PRM_FAC_SUBM_ID
        ON dbo.RCRA_PRM_UNIT(PRM_FAC_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_PRM_UNIT_DETAIL_PRM_UNIT_ID, Table : dbo.RCRA_PRM_UNIT_DETAIL
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_UNIT_DETAIL') AND NAME = 'IX_PRM_UNIT_DETAIL_PRM_UNIT_ID')
    CREATE  NONCLUSTERED  INDEX IX_PRM_UNIT_DETAIL_PRM_UNIT_ID
        ON dbo.RCRA_PRM_UNIT_DETAIL(PRM_UNIT_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_PRM_WSTE_CDE_PRM_UNT_DTL_ID, Table : dbo.RCRA_PRM_WASTE_CODE
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_PRM_WASTE_CODE') AND NAME = 'IX_PRM_WSTE_CDE_PRM_UNT_DTL_ID')
    CREATE  NONCLUSTERED  INDEX IX_PRM_WSTE_CDE_PRM_UNT_DTL_ID
        ON dbo.RCRA_PRM_WASTE_CODE(PRM_UNIT_DETAIL_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_RU_RPR_UNV_RU_RPR_UNV_SB_ID, Table : dbo.RCRA_RU_REPORT_UNIV
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_RU_REPORT_UNIV') AND NAME = 'IX_RU_RPR_UNV_RU_RPR_UNV_SB_ID')
    CREATE  NONCLUSTERED  INDEX IX_RU_RPR_UNV_RU_RPR_UNV_SB_ID
        ON dbo.RCRA_RU_REPORT_UNIV(RU_REPORT_UNIV_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: IX_RU_REPORT_UNV_SBM_RU_SBM_ID, Table : dbo.RCRA_RU_REPORT_UNIV_SUBM
IF NOT EXISTS(SELECT * FROM SYS.INDEXES WHERE OBJECT_ID = OBJECT_ID(N'dbo.RCRA_RU_REPORT_UNIV_SUBM') AND NAME = 'IX_RU_REPORT_UNV_SBM_RU_SBM_ID')
    CREATE  NONCLUSTERED  INDEX IX_RU_REPORT_UNV_SBM_RU_SBM_ID
        ON dbo.RCRA_RU_REPORT_UNIV_SUBM(RU_SUBM_ID)
        WITH(IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = NONE)
GO

---$ Create Index/PK: PK_SUBMISSIONHISTORY, Table : dbo.RCRA_SUBMISSIONHISTORY
IF OBJECT_ID(N'dbo.PK_SUBMISSIONHISTORY') IS NULL
    ALTER TABLE dbo.RCRA_SUBMISSIONHISTORY
        ADD CONSTRAINT PK_SUBMISSIONHISTORY PRIMARY KEY CLUSTERED(SUBMISSIONHISTORY_ID)
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST
    ADD CONSTRAINT FK_RCRA_EM_EMANIFEST_PARENT FOREIGN KEY (EM_SUBM_ID)
        REFERENCES dbo.RCRA_EM_SUBM (EM_SUBM_ID)
        ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_EMANIFEST_COMMENT
    ADD CONSTRAINT FK_RCRA_EM_EMANIFEST_COMMENT_PARENT FOREIGN KEY (EM_EMANIFEST_ID)
        REFERENCES dbo.RCRA_EM_EMANIFEST (EM_EMANIFEST_ID)
        ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_HANDLER
    ADD CONSTRAINT FK_RCRA_EM_HANDLER_PARENT FOREIGN KEY (EM_EMANIFEST_ID)
        REFERENCES dbo.RCRA_EM_EMANIFEST (EM_EMANIFEST_ID)
        ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_WASTE
    ADD CONSTRAINT FK_RCRA_EM_WASTE_PARENT FOREIGN KEY (EM_EMANIFEST_ID)
        REFERENCES dbo.RCRA_EM_EMANIFEST (EM_EMANIFEST_ID)
        ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_TR_NUM_ORIG
    ADD CONSTRAINT FK_RCRA_EM_TR_NUM_ORIG_PARENT FOREIGN KEY (EM_EMANIFEST_ID)
        REFERENCES dbo.RCRA_EM_EMANIFEST (EM_EMANIFEST_ID)
        ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_TR_NUM_REJ
    ADD CONSTRAINT FK_RCRA_EM_TR_NUM_REJ_PARENT FOREIGN KEY (EM_EMANIFEST_ID)
        REFERENCES dbo.RCRA_EM_EMANIFEST (EM_EMANIFEST_ID)
        ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_TR_NUM_RESIDUE_NEW
    ADD CONSTRAINT FK_RCRA_EM_TR_NUM_RESIDUE_NEW_PARENT FOREIGN KEY (EM_EMANIFEST_ID)
        REFERENCES dbo.RCRA_EM_EMANIFEST (EM_EMANIFEST_ID)
        ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_TR_NUM_WASTE
    ADD CONSTRAINT FK_RCRA_EM_TR_NUM_WASTE_PARENT FOREIGN KEY (EM_WASTE_ID)
        REFERENCES dbo.RCRA_EM_WASTE (EM_WASTE_ID)
        ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_WASTE_CD_FED
    ADD CONSTRAINT FK_RCRA_EM_WASTE_CD_FED_PARENT FOREIGN KEY (EM_WASTE_ID)
        REFERENCES dbo.RCRA_EM_WASTE (EM_WASTE_ID)
        ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_WASTE_CD_GEN
    ADD CONSTRAINT FK_RCRA_EM_WASTE_CD_GEN_PARENT FOREIGN KEY (EM_WASTE_ID)
        REFERENCES dbo.RCRA_EM_WASTE (EM_WASTE_ID)
        ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_WASTE_CD_TRANS
    ADD CONSTRAINT FK_RCRA_EM_WASTE_CD_TRANS_PARENT FOREIGN KEY (EM_WASTE_ID)
        REFERENCES dbo.RCRA_EM_WASTE (EM_WASTE_ID)
        ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_WASTE_CD_TSDF
    ADD CONSTRAINT FK_RCRA_EM_WASTE_CD_TSDF_PARENT FOREIGN KEY (EM_WASTE_ID)
        REFERENCES dbo.RCRA_EM_WASTE (EM_WASTE_ID) ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_WASTE_COMMENT
    ADD CONSTRAINT FK_RCRA_EM_WASTE_COMMENT_PARENT FOREIGN KEY (EM_WASTE_ID)
        REFERENCES dbo.RCRA_EM_WASTE (EM_WASTE_ID) ON DELETE CASCADE
GO

ALTER TABLE dbo.RCRA_EM_WASTE_PCB
    ADD CONSTRAINT FK_RCRA_EM_WASTE_PCB_PARENT FOREIGN KEY (EM_WASTE_ID)
        REFERENCES dbo.RCRA_EM_WASTE (EM_WASTE_ID) ON DELETE CASCADE
GO