/*
Copyright (c) 2019, The Environmental Council of the States (ECOS)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the ECOS nor the names of its contributors may
   be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/
/*****************************************************************************************************************************
 *
 *  Script Name:  RCRA_5.6_to_5.7-upgrade_ORA-DDL.sql
 *
 *  Company:  Windsor Solutions, Inc.
 *
 *  Purpose:  This script will upgrade an Oracle 5.6 version RCRA DB to version 5.7.
 *
 *  Maintenance:
 *
 *    Analyst         Date            Comment
 *    ----------      ----------      ------------------------------------------------------------------------------
 *    Windsor         06/18/2019      Created
 *
  ****************************************************************************************************************************
 */

CREATE TABLE RCRA_EM_SUBM
(
EM_SUBM_ID VARCHAR2(40) 
);
ALTER TABLE RCRA_EM_SUBM ADD CONSTRAINT PK_EM_SUBM PRIMARY KEY   (EM_SUBM_ID);


CREATE TABLE RCRA_EM_EMANIFEST
(
EM_EMANIFEST_ID VARCHAR2(40),
EM_SUBM_ID VARCHAR2(40),
CREATED_DATE DATE NOT NULL,
UPDATED_DATE DATE NULL,
MAN_TRACKING_NUM VARCHAR2(12),
STATUS VARCHAR2(17),
PUBLIC_IND CHAR(1),
SUBM_TYPE VARCHAR2(14),
SIGN_STATUS_IND CHAR(1),
ORIGIN_TYPE VARCHAR2(7),
SHIPPED_DATE DATE NULL,
RECEIVED_DATE DATE NULL,
CERT_DATE DATE NULL,
REJ_IND CHAR(1),
DISCREPANCY_IND CHAR(1),
RESIDUE_IND CHAR(1),
IMP_IND CHAR(1),
CONT_PREV_REJ_RES_IND CHAR(1),
CERT_BY_FIRST_NAME VARCHAR2(38),
CERT_BY_LAST_NAME VARCHAR2(38),
CERT_BY_USER_ID VARCHAR2(255),
REJ_TRANS_ON_SITE_IND CHAR(1),
REJ_TYPE VARCHAR2(13),
REJ_ALT_DES_FAC_TYPE VARCHAR2(9),
REJ_COMMENTS VARCHAR2(255),
REJ_GEN_PS_NAME VARCHAR2(80),
REJ_GEN_PS_DATE DATE NULL,
REJ_GEN_ES_SIGN_DATE DATE NULL,
REJ_GEN_ES_CROMERR_ACT_ID VARCHAR2(50),
REJ_GEN_ES_CROMERR_DOC_ID VARCHAR2(50),
REJ_GEN_ES_SIGNER_FIRST_NAME VARCHAR2(38),
REJ_GEN_ES_SIGNER_LAST_NAME VARCHAR2(38), 
REJ_GEN_ES_SIGNER_USER_ID VARCHAR2(255), 
REJ_GEN_ES_DOC_NAME VARCHAR2(255),
REJ_GEN_ES_DOC_SIZE NUMBER(10) NULL,
REJ_GEN_ES_DOC_MIME_TYPE VARCHAR2(50),
IMP_GEN_NAME VARCHAR2(80),
IMP_GEN_ADDRESS VARCHAR2(50),
IMP_GEN_CITY VARCHAR2(25),
IMP_GEN_POSTAL_CODE VARCHAR2(25),
IMP_GEN_PROVINCE VARCHAR2(50),
IMP_GEN_CNTRY_CODE CHAR(2),
IMP_GEN_CNTRY_NAME VARCHAR2(100),
IMP_PORT_CITY VARCHAR2(25),
IMP_PORT_STATE_CODE CHAR(2),
IMP_PORT_STATE_NAME VARCHAR2(100),
PRINTED_DOC_NAME VARCHAR2(255),
PRINTED_DOC_SIZE NUMBER(10) NULL,
PRINTED_DOC_MIME_TYPE VARCHAR2(50),
FORM_DOC_NAME VARCHAR2(255),
FORM_DOC_SIZE NUMBER(10) NULL,
FORM_DOC_MIME_TYPE VARCHAR2(50),
ADD_INFO_NEW_MAN_DEST VARCHAR2(255),
ADD_INFO_CONSENT_NUM VARCHAR2(255),
ADD_INFO_HAND_INSTR VARCHAR2(4000),
CORR_VERSION_NUM NUMBER(10) NULL,
CORR_ACTIVE_IND CHAR(1),
CORR_EPA_SITE_ID VARCHAR2(15),
CORR_ES_SIGN_DATE DATE NULL,
CORR_ES_CROMERR_ACT_ID VARCHAR2(50),
CORR_ES_CROMERR_DOC_ID VARCHAR2(50),
CORR_ES_SIGNER_FIRST_NAME VARCHAR2(38),
CORR_ES_SIGNER_LAST_NAME VARCHAR2(38),
CORR_ES_SIGNER_USER_ID VARCHAR2(255),
CORR_ES_DOC_NAME VARCHAR2(255),
CORR_ES_DOC_SIZE NUMBER(10) NULL,
CORR_ES_DOC_MIME_TYPE VARCHAR2(50)
);

ALTER TABLE RCRA_EM_EMANIFEST ADD CONSTRAINT PK_EM_EMANIFEST PRIMARY KEY  (EM_EMANIFEST_ID);
CREATE INDEX IX_EM_EMANIFEST_EM_SUBM_ID ON RCRA_EM_EMANIFEST (EM_SUBM_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_EMANIFEST_COMMENT');
CREATE TABLE RCRA_EM_EMANIFEST_COMMENT
(
EM_EMANIFEST_COMMENT_ID VARCHAR2(40),
EM_EMANIFEST_ID VARCHAR2(40),
COMMENT_DESC VARCHAR2(4000) ,
HANDLER_ID VARCHAR2(15) ,
COMMENT_LABEL VARCHAR2(255) 
);
EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_EMANIFEST_COMMENT on RCRA_EM_EMANIFEST_COMMENT');
ALTER TABLE RCRA_EM_EMANIFEST_COMMENT ADD CONSTRAINT PK_EM_EMANIFEST_COMMENT PRIMARY KEY  (EM_EMANIFEST_COMMENT_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_EMNFST_CMMNT_EM_EMNFS_ID on RCRA_EM_EMANIFEST_COMMENT');
CREATE INDEX IX_EM_EMNFST_CMMNT_EM_EMNFS_ID ON RCRA_EM_EMANIFEST_COMMENT (EM_EMANIFEST_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_HANDLER');
CREATE TABLE RCRA_EM_HANDLER
(
EM_HANDLER_ID VARCHAR2(40),
EM_EMANIFEST_ID VARCHAR2(40),
SITE_TYPE VARCHAR2(11),
EPA_SITE_ID VARCHAR2(15) ,
MANIFEST_NAME VARCHAR2(80),
ORDER_NUM NUMBER(10) NULL,
REG_IND CHAR(1) ,
MOD_IND CHAR(1) ,
MANIFEST_HANDLER_TYPE VARCHAR2(40),
MAIL_STREET_NUM VARCHAR2(12) ,
MAIL_STREET1 VARCHAR2(50) ,
MAIL_STREET2 VARCHAR2(50) ,
MAIL_CITY VARCHAR2(25) ,
MAIL_ZIP VARCHAR2(14) ,
MAIL_CNTRY_CODE CHAR(2) ,
MAIL_CNTRY_NAME VARCHAR2(100) ,
MAIL_STATE_CODE CHAR(2) ,
MAIL_STATE_NAME VARCHAR2(100) ,
SITE_STREET_NUM VARCHAR2(12) ,
SITE_STREET1 VARCHAR2(50) ,
SITE_STREET2 VARCHAR2(50) ,
SITE_CITY VARCHAR2(25) ,
SITE_ZIP VARCHAR2(14) ,
SITE_CNTRY_CODE CHAR(2) ,
SITE_CNTRY_NAME VARCHAR2(100) ,
SITE_STATE_CODE CHAR(2) ,
SITE_STATE_NAME VARCHAR2(100) ,
CONTACT_FIRST_NAME VARCHAR2(38) ,
CONTACT_MIDDLE_INITIAL CHAR(1) ,
CONTACT_LAST_NAME VARCHAR2(38) ,
CONTACT_EMAIL VARCHAR2(80) ,
CONTACT_COMPANY_NAME VARCHAR2(80) ,
CONTACT_PHONE_NUM VARCHAR2(15) ,
CONTACT_PHONE_EXT VARCHAR2(6) ,
EMERG_PHONE_NUM VARCHAR2(15) ,
EMERG_PHONE_EXT VARCHAR2(6) ,
PS_NAME VARCHAR2(80) ,
PS_DATE DATE NULL,
ES_SIGN_DATE DATE NULL,
ES_CROMERR_ACT_ID VARCHAR2(50) ,
ES_CROMERR_DOC_ID VARCHAR2(50) ,
ES_SIGNER_FIRST_NAME VARCHAR2(38) ,
ES_SIGNER_LAST_NAME VARCHAR2(38) ,
ES_SIGNER_USER_ID VARCHAR2(255) ,
ES_DOC_NAME VARCHAR2(255) ,
ES_DOC_SIZE NUMBER(10) NULL,
ES_DOC_MIME_TYPE VARCHAR2(50) 
);
EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_HANDLER on RCRA_EM_HANDLER');
ALTER TABLE RCRA_EM_HANDLER ADD CONSTRAINT PK_EM_HANDLER PRIMARY KEY  (EM_HANDLER_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_HANDLER_EM_EMANIFEST_ID on RCRA_EM_HANDLER');
CREATE INDEX IX_EM_HANDLER_EM_EMANIFEST_ID ON RCRA_EM_HANDLER (EM_EMANIFEST_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_TR_NUM_ORIG');
CREATE TABLE RCRA_EM_TR_NUM_ORIG
(
EM_TR_NUM_ORIG_ID VARCHAR2(40)  DEFAULT (SYS_GUID()),
EM_EMANIFEST_ID VARCHAR2(40),
MANIFEST_TRACKING_NUM VARCHAR2(12) 
);
EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_TR_NUM_ORIG on RCRA_EM_TR_NUM_ORIG');
ALTER TABLE RCRA_EM_TR_NUM_ORIG ADD CONSTRAINT PK_EM_TR_NUM_ORIG PRIMARY KEY  (EM_TR_NUM_ORIG_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_TR_NM_EMNFST_EM_EMNFS_ID on RCRA_EM_TR_NUM_ORIG');
CREATE INDEX IX_EM_TR_NM_EMNFST_EM_EMNFS_ID ON RCRA_EM_TR_NUM_ORIG (EM_EMANIFEST_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_TR_NUM_RESIDUE_NEW');
CREATE TABLE RCRA_EM_TR_NUM_RESIDUE_NEW
(
EM_TR_NUM_RESIDUE_NEW_ID VARCHAR2(40) DEFAULT (SYS_GUID()),
EM_EMANIFEST_ID VARCHAR2(40),
MANIFEST_TRACKING_NUM VARCHAR2(12) 
);
EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_TR_NUM_RESIDUE_NEW on RCRA_EM_TR_NUM_RESIDUE_NEW');
ALTER TABLE RCRA_EM_TR_NUM_RESIDUE_NEW ADD CONSTRAINT PK_EM_TR_NUM_RESIDUE_NEW PRIMARY KEY  (EM_TR_NUM_RESIDUE_NEW_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_TR_NM_RSDE_NW_EM_EMNF_ID on RCRA_EM_TR_NUM_RESIDUE_NEW');
CREATE INDEX IX_EM_TR_NM_RSDE_NW_EM_EMNF_ID ON RCRA_EM_TR_NUM_RESIDUE_NEW (EM_EMANIFEST_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_TR_NUM_REJ');
CREATE TABLE RCRA_EM_TR_NUM_REJ
(
EM_TR_NUM_REJ_ID VARCHAR2(40)  DEFAULT (SYS_GUID()),
EM_EMANIFEST_ID VARCHAR2(40),
MANIFEST_TRACKING_NUM VARCHAR2(12) 
);
EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_TR_NUM_REJ on RCRA_EM_TR_NUM_REJ');
ALTER TABLE RCRA_EM_TR_NUM_REJ ADD CONSTRAINT PK_EM_TR_NUM_REJ PRIMARY KEY  (EM_TR_NUM_REJ_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_TR_NUM_RJ_EM_EMNIFEST_ID on RCRA_EM_TR_NUM_REJ');
CREATE INDEX IX_EM_TR_NUM_RJ_EM_EMNIFEST_ID ON RCRA_EM_TR_NUM_REJ (EM_EMANIFEST_ID);


EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_WASTE');
CREATE TABLE RCRA_EM_WASTE
(
EM_WASTE_ID VARCHAR2(40),
EM_EMANIFEST_ID VARCHAR2(40),
DOT_HAZ_IND CHAR(1),
WASTES_DESC VARCHAR2(500) ,
BR_IND CHAR(1) ,
PCB_IND CHAR(1),
LINE_NUM NUMBER(10) NOT NULL,
EPA_WASTE_IND CHAR(1) ,
DOT_ID_NUM VARCHAR2(255) ,
DOT_PRINTED_INFO VARCHAR2(500) ,
QNT_CONT_NUM NUMBER(10) NULL,
QNT_VAL NUMBER(14, 6) NULL,
QNT_CONT_TYPE_CODE VARCHAR2(255) ,
QNT_CONT_TYPE_DESC VARCHAR2(255) ,
QNT_UOM_CODE CHAR(1) ,
QNT_UOM_DESC VARCHAR2(28) ,
BR_DENSITY NUMBER(14, 6) NULL,
BR_DENSITY_UOM_CODE CHAR(1) ,
BR_DENSITY_UOM_DESC VARCHAR2(240) ,
BR_FORM_CODE VARCHAR2(4) ,
BR_FORM_DESC VARCHAR2(240) ,
BR_SRC_CODE VARCHAR2(3) ,
BR_SRC_DESC VARCHAR2(240) ,
BR_WM_CODE CHAR(1) ,
BR_WM_DESC VARCHAR2(240) ,
DISC_WASTE_QTY_IND CHAR(1) ,
DISC_WASTE_TYPE_IND CHAR(1) ,
DISC_COMMENTS VARCHAR2(255) ,
DISC_RESIDUE_IND CHAR(1) ,
DISC_RESIDUE_COMMENTS VARCHAR2(255) ,
MGMT_METHOD_CODE VARCHAR2(4) ,
MGMT_METHOD_DESC VARCHAR2(240) ,
ADD_INFO_NEW_MAN_DEST VARCHAR2(255) ,
ADD_INFO_CONSENT_NUM VARCHAR2(255) ,
ADD_INFO_HAND_INSTR VARCHAR2(4000) 
);

ALTER TABLE RCRA_EM_WASTE ADD CONSTRAINT PK_EM_WASTE PRIMARY KEY  (EM_WASTE_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_WASTE_EM_EMANIFEST_ID on RCRA_EM_WASTE');
CREATE INDEX IX_EM_WASTE_EM_EMANIFEST_ID ON RCRA_EM_WASTE (EM_EMANIFEST_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_TR_NUM_WASTE');
CREATE TABLE RCRA_EM_TR_NUM_WASTE
(
EM_TR_NUM_WASTE_ID VARCHAR2(40)  DEFAULT (SYS_GUID()),
EM_WASTE_ID VARCHAR2(40),
MANIFEST_TRACKING_NUM VARCHAR2(12) 
);
EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_TR_NUM_WASTE on RCRA_EM_TR_NUM_WASTE');
ALTER TABLE RCRA_EM_TR_NUM_WASTE ADD CONSTRAINT PK_EM_TR_NUM_WASTE PRIMARY KEY  (EM_TR_NUM_WASTE_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_TR_NUM_WASTE_EM_WASTE_ID on RCRA_EM_TR_NUM_WASTE');
CREATE INDEX IX_EM_TR_NUM_WASTE_EM_WASTE_ID ON RCRA_EM_TR_NUM_WASTE (EM_WASTE_ID);


EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_WASTE_CD_FED');
CREATE TABLE RCRA_EM_WASTE_CD_FED
(
EM_WASTE_CD_FED_ID VARCHAR2(40),
EM_WASTE_ID VARCHAR2(40),
WASTE_CODE VARCHAR2(6),
WASTE_DESC VARCHAR2(2000) 
);

EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_WASTE_CD_FED on RCRA_EM_WASTE_CD_FED');
ALTER TABLE RCRA_EM_WASTE_CD_FED ADD CONSTRAINT PK_EM_WASTE_CD_FED PRIMARY KEY  (EM_WASTE_CD_FED_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_WASTE_CD_FED_EM_WASTE_ID on RCRA_EM_WASTE_CD_FED');
CREATE INDEX IX_EM_WASTE_CD_FED_EM_WASTE_ID ON RCRA_EM_WASTE_CD_FED (EM_WASTE_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_WASTE_CD_GEN');
CREATE TABLE RCRA_EM_WASTE_CD_GEN
(
EM_WASTE_CD_GEN_ID VARCHAR2(40),
EM_WASTE_ID VARCHAR2(40),
WASTE_CODE VARCHAR2(6),
WASTE_DESC VARCHAR2(2000) 
);
EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_WASTE_CD_GEN on RCRA_EM_WASTE_CD_GEN');
ALTER TABLE RCRA_EM_WASTE_CD_GEN ADD CONSTRAINT PK_EM_WASTE_CD_GEN PRIMARY KEY  (EM_WASTE_CD_GEN_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_WASTE_CD_GEN_EM_WASTE_ID on RCRA_EM_WASTE_CD_GEN');
CREATE INDEX IX_EM_WASTE_CD_GEN_EM_WASTE_ID ON RCRA_EM_WASTE_CD_GEN (EM_WASTE_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_WASTE_CD_TRANS');
CREATE TABLE RCRA_EM_WASTE_CD_TRANS
(
EM_WASTE_CD_TRANS_ID VARCHAR2(40) DEFAULT (SYS_GUID()),
EM_WASTE_ID VARCHAR2(40),
WASTE_CODE VARCHAR2(12) 
);

EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_WASTE_CD_TRANS on RCRA_EM_WASTE_CD_TRANS');
ALTER TABLE RCRA_EM_WASTE_CD_TRANS ADD CONSTRAINT PK_EM_WASTE_CD_TRANS PRIMARY KEY  (EM_WASTE_CD_TRANS_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_WASTE_CD_TRNS_EM_WSTE_ID on RCRA_EM_WASTE_CD_TRANS');
CREATE INDEX IX_EM_WASTE_CD_TRNS_EM_WSTE_ID ON RCRA_EM_WASTE_CD_TRANS (EM_WASTE_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_WASTE_CD_TSDF');
CREATE TABLE RCRA_EM_WASTE_CD_TSDF
(
EM_WASTE_CD_TSDF_ID VARCHAR2(40),
EM_WASTE_ID VARCHAR2(40),
WASTE_CODE VARCHAR2(6),
WASTE_DESC VARCHAR2(2000) 
);
EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_WASTE_CD_TSDF on RCRA_EM_WASTE_CD_TSDF');
ALTER TABLE RCRA_EM_WASTE_CD_TSDF ADD CONSTRAINT PK_EM_WASTE_CD_TSDF PRIMARY KEY  (EM_WASTE_CD_TSDF_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_WASTE_CD_TSDF_EM_WSTE_ID on RCRA_EM_WASTE_CD_TSDF');
CREATE INDEX IX_EM_WASTE_CD_TSDF_EM_WSTE_ID ON RCRA_EM_WASTE_CD_TSDF (EM_WASTE_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_WASTE_COMMENT');
CREATE TABLE RCRA_EM_WASTE_COMMENT
(
EM_WASTE_COMMENT_ID VARCHAR2(40),
EM_WASTE_ID VARCHAR2(40),
COMMENT_DESC VARCHAR2(4000) ,
HANDLER_ID VARCHAR2(15) ,
COMMENT_LABEL VARCHAR2(255) 
);
EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_WASTE_COMMENT on RCRA_EM_WASTE_COMMENT');
ALTER TABLE RCRA_EM_WASTE_COMMENT ADD CONSTRAINT PK_EM_WASTE_COMMENT PRIMARY KEY  (EM_WASTE_COMMENT_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_WASTE_COMMENT_EM_WSTE_ID on RCRA_EM_WASTE_COMMENT');
CREATE INDEX IX_EM_WASTE_COMMENT_EM_WSTE_ID ON RCRA_EM_WASTE_COMMENT (EM_WASTE_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Creating RCRA_EM_WASTE_PCB');
CREATE TABLE RCRA_EM_WASTE_PCB
(
EM_WASTE_PCB_ID VARCHAR2(40),
EM_WASTE_ID VARCHAR2(40),
PCB_LOAD_TYPE_CODE VARCHAR2(255) ,
PCB_ARTICLE_CONT_ID VARCHAR2(255) ,
PCB_REMOVAL_DATE DATE NULL,
PCB_WEIGHT NUMBER (14, 6) NULL,
PCB_WASTE_TYPE VARCHAR2(255) ,
PCB_BULK_IDENTITY VARCHAR2(255) 
);
EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_EM_WASTE_PCB on RCRA_EM_WASTE_PCB');
ALTER TABLE RCRA_EM_WASTE_PCB ADD CONSTRAINT PK_EM_WASTE_PCB PRIMARY KEY  (EM_WASTE_PCB_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_EM_WASTE_PCB_EM_WASTE_ID on RCRA_EM_WASTE_PCB');
CREATE INDEX IX_EM_WASTE_PCB_EM_WASTE_ID ON RCRA_EM_WASTE_PCB (EM_WASTE_ID);
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_EMANIFEST_COMMENT');
ALTER TABLE RCRA_EM_EMANIFEST_COMMENT ADD CONSTRAINT FK_EM_EMNIFST_CMMNT_EM_EMNIFST FOREIGN KEY (EM_EMANIFEST_ID) REFERENCES RCRA_EM_EMANIFEST (EM_EMANIFEST_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_HANDLER');
ALTER TABLE RCRA_EM_HANDLER ADD CONSTRAINT FK_EM_HANDLER_EM_EMANIFEST FOREIGN KEY (EM_EMANIFEST_ID) REFERENCES RCRA_EM_EMANIFEST (EM_EMANIFEST_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_TR_NUM_ORIG');
ALTER TABLE RCRA_EM_TR_NUM_ORIG ADD CONSTRAINT FK_EM_TR_NM_EMNIFST_EM_EMNIFST FOREIGN KEY (EM_EMANIFEST_ID) REFERENCES RCRA_EM_EMANIFEST (EM_EMANIFEST_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_TR_NUM_RESIDUE_NEW');
ALTER TABLE RCRA_EM_TR_NUM_RESIDUE_NEW ADD CONSTRAINT FK_EM_TR_NM_RSDUE_NW_EM_EMNFST FOREIGN KEY (EM_EMANIFEST_ID) REFERENCES RCRA_EM_EMANIFEST (EM_EMANIFEST_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_TR_NUM_REJ');
ALTER TABLE RCRA_EM_TR_NUM_REJ ADD CONSTRAINT FK_EM_TR_NUM_REJ_EM_EMANIFEST FOREIGN KEY (EM_EMANIFEST_ID) REFERENCES RCRA_EM_EMANIFEST (EM_EMANIFEST_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_WASTE');
ALTER TABLE RCRA_EM_WASTE ADD CONSTRAINT FK_EM_WASTE_EM_EMANIFEST FOREIGN KEY (EM_EMANIFEST_ID) REFERENCES RCRA_EM_EMANIFEST (EM_EMANIFEST_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_EMANIFEST');
ALTER TABLE RCRA_EM_EMANIFEST ADD CONSTRAINT FK_EM_EMANIFEST_EM_SUBM FOREIGN KEY (EM_SUBM_ID) REFERENCES RCRA_EM_SUBM (EM_SUBM_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_TR_NUM_WASTE');
ALTER TABLE RCRA_EM_TR_NUM_WASTE ADD CONSTRAINT FK_EM_TR_NUM_WASTE_EM_WASTE FOREIGN KEY (EM_WASTE_ID) REFERENCES RCRA_EM_WASTE (EM_WASTE_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_WASTE_CD_FED');
ALTER TABLE RCRA_EM_WASTE_CD_FED ADD CONSTRAINT FK_EM_WASTE_CD_FED_EM_WASTE FOREIGN KEY (EM_WASTE_ID) REFERENCES RCRA_EM_WASTE (EM_WASTE_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_WASTE_CD_GEN');
ALTER TABLE RCRA_EM_WASTE_CD_GEN ADD CONSTRAINT FK_EM_WASTE_CD_GEN_EM_WASTE FOREIGN KEY (EM_WASTE_ID) REFERENCES RCRA_EM_WASTE (EM_WASTE_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_WASTE_CD_TRANS');
ALTER TABLE RCRA_EM_WASTE_CD_TRANS ADD CONSTRAINT FK_EM_WASTE_CD_TRANS_EM_WASTE FOREIGN KEY (EM_WASTE_ID) REFERENCES RCRA_EM_WASTE (EM_WASTE_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_WASTE_CD_TSDF');
ALTER TABLE RCRA_EM_WASTE_CD_TSDF ADD CONSTRAINT FK_EM_WASTE_CD_TSDF_EM_WASTE FOREIGN KEY (EM_WASTE_ID) REFERENCES RCRA_EM_WASTE (EM_WASTE_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_WASTE_COMMENT');
ALTER TABLE RCRA_EM_WASTE_COMMENT ADD CONSTRAINT FK_EM_WASTE_COMMENT_EM_WASTE FOREIGN KEY (EM_WASTE_ID) REFERENCES RCRA_EM_WASTE (EM_WASTE_ID) ON DELETE CASCADE;
EXEC DBMS_OUTPUT.PUT_LINE('Adding foreign keys to RCRA_EM_WASTE_PCB');
ALTER TABLE RCRA_EM_WASTE_PCB ADD CONSTRAINT FK_EM_WASTE_PCB_EM_WASTE FOREIGN KEY (EM_WASTE_ID) REFERENCES RCRA_EM_WASTE (EM_WASTE_ID) ON DELETE CASCADE;























/*
  

    RCRA 5.7 - Existing Object Modification


*/

/*
Run this script on:

        JAMES-461Q8Y1.RCRA_56    -  This database will be modified

to synchronize it with:

        JAMES-461Q8Y1.RCRA_57

You are recommended to back up your database before running this script

Script created by SQL Compare version 13.6.1.7928 from Red Gate Software Ltd at 6/18/2019 2:43:42 PM

*/



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_VIOL');

ALTER TABLE RCRA_CME_VIOL MODIFY TRANS_CODE char (1) ;
ALTER TABLE RCRA_CME_VIOL MODIFY  VIOL_ACT_LOC char (2) ;
ALTER TABLE RCRA_CME_VIOL MODIFY  AGN_WHICH_DTRM_VIOL char (1) ;
ALTER TABLE RCRA_CME_VIOL MODIFY  VIOL_TYPE_OWNER char (2) ;
ALTER TABLE RCRA_CME_VIOL MODIFY  VIOL_TYPE varchar2(10) ;
ALTER TABLE RCRA_CME_VIOL MODIFY  FORMER_CITATION_NAME varchar2(35) ;
ALTER TABLE RCRA_CME_VIOL MODIFY  RTN_TO_COMPL_QUAL char (1) ;
ALTER TABLE RCRA_CME_VIOL MODIFY  VIOL_RESP_AGN char (1) ;
ALTER TABLE RCRA_CME_VIOL MODIFY  NOTES varchar2(4000) ;



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_CITATION');
ALTER TABLE RCRA_CME_CITATION MODIFY  TRANS_CODE char (1) ;
ALTER TABLE RCRA_CME_CITATION MODIFY  CITATION_NAME varchar2(80) ;
ALTER TABLE RCRA_CME_CITATION MODIFY  CITATION_NAME_OWNER char (2) ;
ALTER TABLE RCRA_CME_CITATION MODIFY  CITATION_NAME_TYPE char (2) ;
ALTER TABLE RCRA_CME_CITATION MODIFY  NOTES varchar2(4000) ;



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_ENFRC_ACT');
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  TRANS_CODE char (1) ;
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  ENFRC_AGN_LOC_NAME char (2);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  ENFRC_ACT_IDEN varchar2(3);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  ENFRC_AGN_NAME char (1);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  ENFRC_DOCKET_NUM varchar2(15);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  ENFRC_ATTRY varchar2(5);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  CORCT_ACT_COMPT char (1);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  DISP_STAT_OWNER char (2);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  DISP_STAT char (2);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  ENFRC_OWNER char (2);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  ENFRC_TYPE char (3);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  ENFRC_RESP_PERSON_OWNER char (2);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  ENFRC_RESP_PERSON_IDEN varchar2(5);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  ENFRC_RESP_SUBORG_OWNER char (2);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  ENFRC_RESP_SUBORG varchar2(10);
ALTER TABLE RCRA_CME_ENFRC_ACT MODIFY  NOTES varchar2(4000);



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_CSNY_DATE');
ALTER TABLE RCRA_CME_CSNY_DATE MODIFY  TRANS_CODE char (1);



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_FAC_SUBM');
ALTER TABLE RCRA_CME_FAC_SUBM MODIFY  EPA_HDLR_ID char (12);



--EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_CME_FAC_SUBM_CME_SUBM_ID on RCRA_CME_FAC_SUBM');
--CREATE INDEX IX_CME_FAC_SUBM_CME_SUBM_ID ON RCRA_CME_FAC_SUBM (CME_SUBM_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_EVAL');
ALTER TABLE RCRA_CME_EVAL MODIFY  TRANS_CODE char (1);
ALTER TABLE RCRA_CME_EVAL MODIFY  EVAL_ACT_LOC char (2);
ALTER TABLE RCRA_CME_EVAL MODIFY  EVAL_IDEN varchar2(3);
ALTER TABLE RCRA_CME_EVAL MODIFY  EVAL_RESP_AGN char (1);
ALTER TABLE RCRA_CME_EVAL MODIFY  FOUND_VIOL char (1);
ALTER TABLE RCRA_CME_EVAL MODIFY  CTZN_CPLT_IND char (1);
ALTER TABLE RCRA_CME_EVAL MODIFY  MULTIMEDIA_IND char (1);
ALTER TABLE RCRA_CME_EVAL MODIFY  SAMPL_IND char (1);
ALTER TABLE RCRA_CME_EVAL MODIFY  NOT_SUBTL_C_IND char (1);
ALTER TABLE RCRA_CME_EVAL MODIFY  EVAL_TYPE_OWNER char (2);
ALTER TABLE RCRA_CME_EVAL MODIFY  EVAL_TYPE varchar2(3);
ALTER TABLE RCRA_CME_EVAL MODIFY  FOCUS_AREA_OWNER char (2);
ALTER TABLE RCRA_CME_EVAL MODIFY  FOCUS_AREA varchar2(3);
ALTER TABLE RCRA_CME_EVAL MODIFY  EVAL_RESP_PERSON_IDEN_OWNER char (2);
ALTER TABLE RCRA_CME_EVAL MODIFY  EVAL_RESP_PERSON_IDEN varchar2(5);
ALTER TABLE RCRA_CME_EVAL MODIFY  EVAL_RESP_SUBORG_OWNER char (2);
ALTER TABLE RCRA_CME_EVAL MODIFY  EVAL_RESP_SUBORG varchar2(10);
ALTER TABLE RCRA_CME_EVAL MODIFY  NOTES varchar2(4000);



--EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_CME_EVAL_CME_FAC_SUBM_ID on RCRA_CME_EVAL');
--CREATE INDEX IX_CME_EVAL_CME_FAC_SUBM_ID ON RCRA_CME_EVAL (CME_FAC_SUBM_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_EVAL_COMMIT');
ALTER TABLE RCRA_CME_EVAL_COMMIT MODIFY  TRANS_CODE char (1);
ALTER TABLE RCRA_CME_EVAL_COMMIT MODIFY  COMMIT_LEAD char (2);



--EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_CME_EVAL_COMMIT_CME_EVAL_ID on RCRA_CME_EVAL_COMMIT');
--CREATE INDEX IX_CME_EVAL_COMMIT_CME_EVAL_ID ON RCRA_CME_EVAL_COMMIT (CME_EVAL_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_EVAL_VIOL');
ALTER TABLE RCRA_CME_EVAL_VIOL MODIFY  TRANS_CODE char (1);
ALTER TABLE RCRA_CME_EVAL_VIOL MODIFY  VIOL_ACT_LOC char (2);
ALTER TABLE RCRA_CME_EVAL_VIOL MODIFY  AGN_WHICH_DTRM_VIOL char (1);



--EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_CME_EVAL_VIOL_CME_EVAL_ID on RCRA_CME_EVAL_VIOL');
--CREATE INDEX IX_CME_EVAL_VIOL_CME_EVAL_ID ON RCRA_CME_EVAL_VIOL (CME_EVAL_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_MEDIA');
ALTER TABLE RCRA_CME_MEDIA MODIFY  TRANS_CODE char (1);
ALTER TABLE RCRA_CME_MEDIA MODIFY  MULTIMEDIA_CODE_OWNER char (2);
ALTER TABLE RCRA_CME_MEDIA MODIFY  MULTIMEDIA_CODE varchar2(3);
ALTER TABLE RCRA_CME_MEDIA MODIFY  NOTES varchar2(4000);

--EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_CME_MEDIA_CME_ENFRC_ACT_ID on RCRA_CME_MEDIA');
--CREATE INDEX IX_CME_MEDIA_CME_ENFRC_ACT_ID ON RCRA_CME_MEDIA (CME_ENFRC_ACT_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_MILESTONE');
ALTER TABLE RCRA_CME_MILESTONE MODIFY  TRANS_CODE char (1);
ALTER TABLE RCRA_CME_MILESTONE MODIFY  TECH_RQMT_DESC varchar2(200);
ALTER TABLE RCRA_CME_MILESTONE MODIFY  NOTES varchar2(4000);

--EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_CME_MLSTNE_CME_ENFRC_ACT_ID on RCRA_CME_MILESTONE');
--CREATE INDEX IX_CME_MLSTNE_CME_ENFRC_ACT_ID ON RCRA_CME_MILESTONE (CME_ENFRC_ACT_ID);



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_PNLTY');
ALTER TABLE RCRA_CME_PNLTY MODIFY  TRANS_CODE char (1);
ALTER TABLE RCRA_CME_PNLTY MODIFY  PNLTY_TYPE_OWNER char (2);
ALTER TABLE RCRA_CME_PNLTY MODIFY  PNLTY_TYPE varchar2(3);
ALTER TABLE RCRA_CME_PNLTY MODIFY  NOTES varchar2(4000);



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_PYMT');
ALTER TABLE RCRA_CME_PYMT MODIFY  TRANS_CODE char (1);
ALTER TABLE RCRA_CME_PYMT MODIFY  NOTES varchar2(4000);






EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_RQST');
ALTER TABLE RCRA_CME_RQST MODIFY  TRANS_CODE char (1);
ALTER TABLE RCRA_CME_RQST MODIFY  RQST_AGN char (1);
ALTER TABLE RCRA_CME_RQST MODIFY  NOTES varchar2(4000);


EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_SUPP_ENVR_PRJT');
ALTER TABLE RCRA_CME_SUPP_ENVR_PRJT MODIFY  TRANS_CODE char (1);
ALTER TABLE RCRA_CME_SUPP_ENVR_PRJT MODIFY  SEP_CODE_OWNER char (2);
ALTER TABLE RCRA_CME_SUPP_ENVR_PRJT MODIFY  SEP_DESC_TXT varchar2(3);
ALTER TABLE RCRA_CME_SUPP_ENVR_PRJT MODIFY  NOTES varchar2(4000);



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_CME_VIOL_ENFRC');
ALTER TABLE RCRA_CME_VIOL_ENFRC MODIFY  TRANS_CODE char (1);
ALTER TABLE RCRA_CME_VIOL_ENFRC MODIFY  AGN_WHICH_DTRM_VIOL char (1);







EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_GIS_GEO_INFORMATION');
ALTER TABLE RCRA_GIS_GEO_INFORMATION MODIFY  AREA_MEAS_SRC_CODE varchar2(4);





EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_HD_HANDLER');
ALTER TABLE RCRA_HD_HANDLER 
ADD ( ACKNOWLEDGE_FLAG_IND char (1),
      INCLUDE_IN_NATIONAL_REPORT_IND char (1),
      LQHUW_IND char (1) ,
      HD_REPORT_CYCLE_YEAR int NULL,
      HEALTHCARE_FAC char (1) ,
      REVERSE_DISTRIBUTOR char (1) ,
      SUBPART_P_WITHDRAWAL char (1) ,
      RECYCLER_IND char (1) );

ALTER TABLE RCRA_HD_HANDLER MODIFY  CONTACT_STREET1 varchar2(50);
ALTER TABLE RCRA_HD_HANDLER MODIFY  CONTACT_STREET2 varchar2(50);
ALTER TABLE RCRA_HD_HANDLER MODIFY  PCONTACT_STREET1 varchar2(50);
ALTER TABLE RCRA_HD_HANDLER MODIFY  PCONTACT_STREET2 varchar2(50);



--EXEC DBMS_OUTPUT.PUT_LINE('Creating index IX_HD_HANDLER_HD_HBASIC_ID on RCRA_HD_HANDLER');
--CREATE INDEX IX_HD_HANDLER_HD_HBASIC_ID ON RCRA_HD_HANDLER (HD_HBASIC_ID);


EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_HD_EPISODIC_WASTE');
ALTER TABLE RCRA_HD_EPISODIC_WASTE MODIFY  SEQ_NUMBER NUMBER(10) NOT NULL;



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_HD_HBASIC');
ALTER TABLE RCRA_HD_HBASIC MODIFY  HANDLER_ID varchar2(12);





EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_HD_LQG_CONSOLIDATION');
ALTER TABLE RCRA_HD_LQG_CONSOLIDATION MODIFY  HANDLER_ID varchar2(12);




EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_HD_NAICS');
ALTER TABLE RCRA_HD_NAICS MODIFY  NAICS_SEQ varchar2 (4);



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_HD_SEC_MATERIAL_ACTIVITY');
ALTER TABLE RCRA_HD_SEC_MATERIAL_ACTIVITY MODIFY  TRANS_CODE char (1);
ALTER TABLE RCRA_HD_SEC_MATERIAL_ACTIVITY MODIFY  HSM_SEQ_NUM varchar2(4);
ALTER TABLE RCRA_HD_SEC_MATERIAL_ACTIVITY MODIFY  FAC_CODE_OWNER_NAME char (2);
ALTER TABLE RCRA_HD_SEC_MATERIAL_ACTIVITY MODIFY  FAC_TYPE_CODE char (2);
ALTER TABLE RCRA_HD_SEC_MATERIAL_ACTIVITY MODIFY  LAND_BASED_UNIT_IND char (2);
EXEC DBMS_OUTPUT.PUT_LINE('Creating primary key PK_HD_SEC_MATERIAL_ACTIVITY on RCRA_HD_SEC_MATERIAL_ACTIVITY');



EXEC DBMS_OUTPUT.PUT_LINE('Altering RCRA_RU_REPORT_UNIV');
ALTER TABLE RCRA_RU_REPORT_UNIV MODIFY  LOCATION_ZIP varchar2(14);