//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.10 at 03:49:37 PM PDT 
//


package com.windsor.node.plugin.attains.fixeddomain;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.windsor.node.plugin.common.xml.bind.annotation.adapters.StringAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for CauseDetailsDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CauseDetailsDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}CauseName"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}PollutantFlag" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}CauseComments" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}UserFlag" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}EPACauseCategory" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}Sources" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}Confidence" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}StateCauseCategory" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}EPAAddedCause" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CauseDetailsDataType", propOrder = {
    "causeName",
    "pollutantFlag",
    "causeComments",
    "userFlag",
    "epaCauseCategory",
    "sources",
    "confidence",
    "stateCauseCategory",
    "epaAddedCause"
})
@Entity(name = "CauseDetailsDataType")
@Table(name = "OWIR_CAUSE_DTLS")
@Inheritance(strategy = InheritanceType.JOINED)
public class CauseDetailsDataType
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CauseName", required = true)
    protected String causeName;
    @XmlElement(name = "PollutantFlag")
    @XmlJavaTypeAdapter(StringAdapter.class)
    protected String pollutantFlag;
    @XmlElement(name = "CauseComments")
    protected String causeComments;
    @XmlElement(name = "UserFlag")
    protected String userFlag;
    @XmlElement(name = "EPACauseCategory")
    protected String epaCauseCategory;
    @XmlElement(name = "Sources")
    protected SourcesDataType sources;
    @XmlElement(name = "Confidence")
    @XmlJavaTypeAdapter(StringAdapter.class)
    protected String confidence;
    @XmlElement(name = "StateCauseCategory")
    protected String stateCauseCategory;
    @XmlElement(name = "EPAAddedCause")
    @XmlJavaTypeAdapter(StringAdapter.class)
    protected String epaAddedCause;
    @XmlTransient
    protected String dbid;

    /**
     * Gets the value of the causeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CAUSE_NAME", length = 240)
    public String getCauseName() {
        return causeName;
    }

    /**
     * Sets the value of the causeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCauseName(String value) {
        this.causeName = value;
    }

    @Transient
    public boolean isSetCauseName() {
        return (this.causeName!= null);
    }

    /**
     * Gets the value of the pollutantFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "POLT_FLAG", columnDefinition = "char(3)", length = 3)
    public String getPollutantFlag() {
        return pollutantFlag;
    }

    /**
     * Sets the value of the pollutantFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPollutantFlag(String value) {
        this.pollutantFlag = value;
    }

    @Transient
    public boolean isSetPollutantFlag() {
        return (this.pollutantFlag!= null);
    }

    /**
     * Gets the value of the causeComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CAUSE_COMMENT", length = 4000)
    public String getCauseComments() {
        return causeComments;
    }

    /**
     * Sets the value of the causeComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCauseComments(String value) {
        this.causeComments = value;
    }

    @Transient
    public boolean isSetCauseComments() {
        return (this.causeComments!= null);
    }

    /**
     * Gets the value of the userFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "USER_FLAG", length = 15)
    public String getUserFlag() {
        return userFlag;
    }

    /**
     * Sets the value of the userFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFlag(String value) {
        this.userFlag = value;
    }

    @Transient
    public boolean isSetUserFlag() {
        return (this.userFlag!= null);
    }

    /**
     * Gets the value of the epaCauseCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "EPA_CAUSE_CATG", length = 255)
    public String getEPACauseCategory() {
        return epaCauseCategory;
    }

    /**
     * Sets the value of the epaCauseCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEPACauseCategory(String value) {
        this.epaCauseCategory = value;
    }

    @Transient
    public boolean isSetEPACauseCategory() {
        return (this.epaCauseCategory!= null);
    }

    @OneToMany(targetEntity = SourceDetailsDataType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "CAUSE_DTLS_ID", insertable = false, updatable = false)
    public List<SourceDetailsDataType> getObservedEffectDetails() {
        return (sources != null ? sources.getSourceDetails() : null);
    }

    public void setObservedEffectDetails(List<SourceDetailsDataType> list)
    {
        if(sources == null)
        {
            ObjectFactory fact = new ObjectFactory();
            setSources(fact.createSourcesDataType());
        }
        getSources().setSourceDetails(list);
    }

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link SourcesDataType }
     *     
     */
    @Transient
    public SourcesDataType getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourcesDataType }
     *     
     */
    public void setSources(SourcesDataType value) {
        this.sources = value;
    }

    @Transient
    public boolean isSetSources() {
        return (this.sources!= null);
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CONFIDENCE", columnDefinition = "6", length = 6)
    public String getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfidence(String value) {
        this.confidence = value;
    }

    @Transient
    public boolean isSetConfidence() {
        return (this.confidence!= null);
    }

    /**
     * Gets the value of the stateCauseCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "STATE_CAUSE_CATG", length = 10)
    public String getStateCauseCategory() {
        return stateCauseCategory;
    }

    /**
     * Sets the value of the stateCauseCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateCauseCategory(String value) {
        this.stateCauseCategory = value;
    }

    @Transient
    public boolean isSetStateCauseCategory() {
        return (this.stateCauseCategory!= null);
    }

    /**
     * Gets the value of the epaAddedCause property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "EPA_ADDED_CAUSE", columnDefinition = "1", length = 1)
    public String getEPAAddedCause() {
        return epaAddedCause;
    }

    /**
     * Sets the value of the epaAddedCause property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEPAAddedCause(String value) {
        this.epaAddedCause = value;
    }

    @Transient
    public boolean isSetEPAAddedCause() {
        return (this.epaAddedCause!= null);
    }

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Id
    @Column(name = "CAUSE_DTLS_ID")
    public String getDbid() {
        return dbid;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbid(String value) {
        this.dbid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof CauseDetailsDataType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CauseDetailsDataType that = ((CauseDetailsDataType) object);
        {
            String lhsCauseName;
            lhsCauseName = this.getCauseName();
            String rhsCauseName;
            rhsCauseName = that.getCauseName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "causeName", lhsCauseName), LocatorUtils.property(thatLocator, "causeName", rhsCauseName), lhsCauseName, rhsCauseName)) {
                return false;
            }
        }
        {
            String lhsPollutantFlag;
            lhsPollutantFlag = this.getPollutantFlag();
            String rhsPollutantFlag;
            rhsPollutantFlag = that.getPollutantFlag();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "pollutantFlag", lhsPollutantFlag), LocatorUtils.property(thatLocator, "pollutantFlag", rhsPollutantFlag), lhsPollutantFlag, rhsPollutantFlag)) {
                return false;
            }
        }
        {
            String lhsCauseComments;
            lhsCauseComments = this.getCauseComments();
            String rhsCauseComments;
            rhsCauseComments = that.getCauseComments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "causeComments", lhsCauseComments), LocatorUtils.property(thatLocator, "causeComments", rhsCauseComments), lhsCauseComments, rhsCauseComments)) {
                return false;
            }
        }
        {
            String lhsUserFlag;
            lhsUserFlag = this.getUserFlag();
            String rhsUserFlag;
            rhsUserFlag = that.getUserFlag();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "userFlag", lhsUserFlag), LocatorUtils.property(thatLocator, "userFlag", rhsUserFlag), lhsUserFlag, rhsUserFlag)) {
                return false;
            }
        }
        {
            String lhsEPACauseCategory;
            lhsEPACauseCategory = this.getEPACauseCategory();
            String rhsEPACauseCategory;
            rhsEPACauseCategory = that.getEPACauseCategory();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "epaCauseCategory", lhsEPACauseCategory), LocatorUtils.property(thatLocator, "epaCauseCategory", rhsEPACauseCategory), lhsEPACauseCategory, rhsEPACauseCategory)) {
                return false;
            }
        }
        {
            SourcesDataType lhsSources;
            lhsSources = this.getSources();
            SourcesDataType rhsSources;
            rhsSources = that.getSources();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "sources", lhsSources), LocatorUtils.property(thatLocator, "sources", rhsSources), lhsSources, rhsSources)) {
                return false;
            }
        }
        {
            String lhsConfidence;
            lhsConfidence = this.getConfidence();
            String rhsConfidence;
            rhsConfidence = that.getConfidence();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "confidence", lhsConfidence), LocatorUtils.property(thatLocator, "confidence", rhsConfidence), lhsConfidence, rhsConfidence)) {
                return false;
            }
        }
        {
            String lhsStateCauseCategory;
            lhsStateCauseCategory = this.getStateCauseCategory();
            String rhsStateCauseCategory;
            rhsStateCauseCategory = that.getStateCauseCategory();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "stateCauseCategory", lhsStateCauseCategory), LocatorUtils.property(thatLocator, "stateCauseCategory", rhsStateCauseCategory), lhsStateCauseCategory, rhsStateCauseCategory)) {
                return false;
            }
        }
        {
            String lhsEPAAddedCause;
            lhsEPAAddedCause = this.getEPAAddedCause();
            String rhsEPAAddedCause;
            rhsEPAAddedCause = that.getEPAAddedCause();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "epaAddedCause", lhsEPAAddedCause), LocatorUtils.property(thatLocator, "epaAddedCause", rhsEPAAddedCause), lhsEPAAddedCause, rhsEPAAddedCause)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theCauseName;
            theCauseName = this.getCauseName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "causeName", theCauseName), currentHashCode, theCauseName);
        }
        {
            String thePollutantFlag;
            thePollutantFlag = this.getPollutantFlag();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "pollutantFlag", thePollutantFlag), currentHashCode, thePollutantFlag);
        }
        {
            String theCauseComments;
            theCauseComments = this.getCauseComments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "causeComments", theCauseComments), currentHashCode, theCauseComments);
        }
        {
            String theUserFlag;
            theUserFlag = this.getUserFlag();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "userFlag", theUserFlag), currentHashCode, theUserFlag);
        }
        {
            String theEPACauseCategory;
            theEPACauseCategory = this.getEPACauseCategory();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "epaCauseCategory", theEPACauseCategory), currentHashCode, theEPACauseCategory);
        }
        {
            SourcesDataType theSources;
            theSources = this.getSources();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "sources", theSources), currentHashCode, theSources);
        }
        {
            String theConfidence;
            theConfidence = this.getConfidence();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "confidence", theConfidence), currentHashCode, theConfidence);
        }
        {
            String theStateCauseCategory;
            theStateCauseCategory = this.getStateCauseCategory();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "stateCauseCategory", theStateCauseCategory), currentHashCode, theStateCauseCategory);
        }
        {
            String theEPAAddedCause;
            theEPAAddedCause = this.getEPAAddedCause();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "epaAddedCause", theEPAAddedCause), currentHashCode, theEPAAddedCause);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
