//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.09 at 07:20:00 AM PDT 
//


package com.windsor.node.plugin.attains.fixeddomain;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDate;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ImplementationActionDetailsDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImplementationActionDetailsDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}ActionDate"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}ImplementationActionText" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImplementationActionDetailsDataType", propOrder = {
    "actionDate",
    "implementationActionText"
})
@Entity(name = "ImplementationActionDetailsDataType")
@Table(name = "OWIR_IMPL_ACT_DTLS")
@Inheritance(strategy = InheritanceType.JOINED)
public class ImplementationActionDetailsDataType
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ActionDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar actionDate;
    @XmlElement(name = "ImplementationActionText")
    protected String implementationActionText;
    @XmlTransient
    protected String dbid;

    /**
     * Gets the value of the actionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getActionDate() {
        return actionDate;
    }

    /**
     * Sets the value of the actionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActionDate(XMLGregorianCalendar value) {
        this.actionDate = value;
    }

    @Transient
    public boolean isSetActionDate() {
        return (this.actionDate!= null);
    }

    /**
     * Gets the value of the implementationActionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "IMPL_ACT_TXT", length = 255)
    public String getImplementationActionText() {
        return implementationActionText;
    }

    /**
     * Sets the value of the implementationActionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementationActionText(String value) {
        this.implementationActionText = value;
    }

    @Transient
    public boolean isSetImplementationActionText() {
        return (this.implementationActionText!= null);
    }

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Id
    @Column(name = "IMPL_ACT_DTLS_ID")
    public String getDbid() {
        return dbid;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbid(String value) {
        this.dbid = value;
    }

    @Basic
    @Column(name = "ACT_DATE")
    @Temporal(TemporalType.DATE)
    public Date getActionDateItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDate.class, this.getActionDate());
    }

    public void setActionDateItem(Date target) {
        setActionDate(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDate.class, target));
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ImplementationActionDetailsDataType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ImplementationActionDetailsDataType that = ((ImplementationActionDetailsDataType) object);
        {
            XMLGregorianCalendar lhsActionDate;
            lhsActionDate = this.getActionDate();
            XMLGregorianCalendar rhsActionDate;
            rhsActionDate = that.getActionDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "actionDate", lhsActionDate), LocatorUtils.property(thatLocator, "actionDate", rhsActionDate), lhsActionDate, rhsActionDate)) {
                return false;
            }
        }
        {
            String lhsImplementationActionText;
            lhsImplementationActionText = this.getImplementationActionText();
            String rhsImplementationActionText;
            rhsImplementationActionText = that.getImplementationActionText();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "implementationActionText", lhsImplementationActionText), LocatorUtils.property(thatLocator, "implementationActionText", rhsImplementationActionText), lhsImplementationActionText, rhsImplementationActionText)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            XMLGregorianCalendar theActionDate;
            theActionDate = this.getActionDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "actionDate", theActionDate), currentHashCode, theActionDate);
        }
        {
            String theImplementationActionText;
            theImplementationActionText = this.getImplementationActionText();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "implementationActionText", theImplementationActionText), currentHashCode, theImplementationActionText);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
