//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.09 at 07:20:00 AM PDT 
//


package com.windsor.node.plugin.attains.fixeddomain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ImplementationActionsDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImplementationActionsDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/OWIR/ATT/2}ImplementationActionDetails" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImplementationActionsDataType", propOrder = {
    "implementationActionDetails"
})
public class ImplementationActionsDataType
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ImplementationActionDetails")
    protected List<ImplementationActionDetailsDataType> implementationActionDetails;

    /**
     * Gets the value of the implementationActionDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the implementationActionDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImplementationActionDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImplementationActionDetailsDataType }
     * 
     * 
     */
    public List<ImplementationActionDetailsDataType> getImplementationActionDetails() {
        if (implementationActionDetails == null) {
            implementationActionDetails = new ArrayList<ImplementationActionDetailsDataType>();
        }
        return this.implementationActionDetails;
    }

    /**
     * 
     * 
     */
    public void setImplementationActionDetails(List<ImplementationActionDetailsDataType> implementationActionDetails) {
        this.implementationActionDetails = implementationActionDetails;
    }

    public boolean isSetImplementationActionDetails() {
        return ((this.implementationActionDetails!= null)&&(!this.implementationActionDetails.isEmpty()));
    }

    public void unsetImplementationActionDetails() {
        this.implementationActionDetails = null;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ImplementationActionsDataType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ImplementationActionsDataType that = ((ImplementationActionsDataType) object);
        {
            List<ImplementationActionDetailsDataType> lhsImplementationActionDetails;
            lhsImplementationActionDetails = (this.isSetImplementationActionDetails()?this.getImplementationActionDetails():null);
            List<ImplementationActionDetailsDataType> rhsImplementationActionDetails;
            rhsImplementationActionDetails = (that.isSetImplementationActionDetails()?that.getImplementationActionDetails():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "implementationActionDetails", lhsImplementationActionDetails), LocatorUtils.property(thatLocator, "implementationActionDetails", rhsImplementationActionDetails), lhsImplementationActionDetails, rhsImplementationActionDetails)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<ImplementationActionDetailsDataType> theImplementationActionDetails;
            theImplementationActionDetails = (this.isSetImplementationActionDetails()?this.getImplementationActionDetails():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "implementationActionDetails", theImplementationActionDetails), currentHashCode, theImplementationActionDetails);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
