CREATE TABLE RCRA_CME_CITATION ( 
	CITATION_ID          	VARCHAR2(40) NOT NULL,
	VIOL_ID              	VARCHAR2(40) NOT NULL,
	TRANS_CODE           	VARCHAR2(50) NULL,
	CITATION_NAME_SEQ_NUM	NUMBER NOT NULL,
	CITATION_NAME        	VARCHAR2(128) NULL,
	CITATION_NAME_OWNER  	VARCHAR2(255) NULL,
	CITATION_NAME_TYPE   	VARCHAR2(255) NULL,
	NOTES                	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_CSNY_DATE ( 
	CSNY_DATE_ID	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID	VARCHAR2(40) NOT NULL,
	TRANS_CODE  	VARCHAR2(50) NULL,
	SNY_DATE    	DATE NOT NULL 
	)
/

CREATE TABLE RCRA_CME_ENFRC_ACT ( 
	ENFRC_ACT_ID                 	VARCHAR2(40) NOT NULL,
	CME_FAC_SUBM_ID              	VARCHAR2(40) NOT NULL,
	TRANS_CODE                   	VARCHAR2(50) NULL,
	ENFRC_AGN_LOC_NAME           	VARCHAR2(128) NOT NULL,
	ENFRC_ACT_IDEN               	VARCHAR2(50) NOT NULL,
	ENFRC_ACT_DATE               	DATE NOT NULL,
	ENFRC_AGN_NAME               	VARCHAR2(128) NOT NULL,
	ENFRC_DOCKET_NUM             	VARCHAR2(20) NULL,
	ENFRC_ATTRY                  	VARCHAR2(255) NULL,
	CORCT_ACT_COMPT              	VARCHAR2(255) NULL,
	CNST_AGMT_FINAL_ORDER_SEQ_NUM	NUMBER NULL,
	APPEAL_INIT_DATE             	DATE NULL,
	APPEAL_RSLN_DATE             	DATE NULL,
	DISP_STAT_DATE               	DATE NULL,
	DISP_STAT_OWNER              	VARCHAR2(255) NULL,
	DISP_STAT                    	VARCHAR2(255) NULL,
	ENFRC_OWNER                  	VARCHAR2(255) NULL,
	ENFRC_TYPE                   	VARCHAR2(255) NULL,
	ENFRC_RESP_PERSON_OWNER      	VARCHAR2(255) NULL,
	ENFRC_RESP_PERSON_IDEN       	VARCHAR2(50) NULL,
	ENFRC_RESP_SUBORG_OWNER      	VARCHAR2(255) NULL,
	ENFRC_RESP_SUBORG            	VARCHAR2(255) NULL,
	NOTES                        	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_EVAL ( 
	EVAL_ID                    	VARCHAR2(40) NOT NULL,
	CME_FAC_SUBM_ID            	VARCHAR2(40) NOT NULL,
	TRANS_CODE                 	VARCHAR2(50) NULL,
	EVAL_ACT_LOC               	VARCHAR2(255) NOT NULL,
	EVAL_IDEN                  	VARCHAR2(50) NOT NULL,
	EVAL_START_DATE            	DATE NOT NULL,
	EVAL_RESP_AGN              	VARCHAR2(255) NOT NULL,
	DAY_ZERO                   	DATE NULL,
	FOUND_VIOL                 	VARCHAR2(255) NULL,
	CTZN_CPLT_IND              	VARCHAR2(255) NULL,
	MULTIMEDIA_IND             	VARCHAR2(255) NULL,
	SAMPL_IND                  	VARCHAR2(255) NULL,
	NOT_SUBTL_C_IND            	VARCHAR2(255) NULL,
	EVAL_TYPE_OWNER            	VARCHAR2(255) NULL,
	EVAL_TYPE                  	VARCHAR2(255) NULL,
	FOCUS_AREA_OWNER           	VARCHAR2(255) NULL,
	FOCUS_AREA                 	VARCHAR2(255) NULL,
	EVAL_RESP_PERSON_IDEN_OWNER	VARCHAR2(255) NULL,
	EVAL_RESP_PERSON_IDEN      	VARCHAR2(50) NULL,
	EVAL_RESP_SUBORG_OWNER     	VARCHAR2(255) NULL,
	EVAL_RESP_SUBORG           	VARCHAR2(255) NULL,
	NOTES                      	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_EVAL_COMMIT ( 
	EVAL_COMMIT_ID	VARCHAR2(40) NOT NULL,
	EVAL_ID       	VARCHAR2(40) NOT NULL,
	TRANS_CODE    	VARCHAR2(50) NULL,
	COMMIT_LEAD   	VARCHAR2(255) NOT NULL,
	COMMIT_SEQ_NUM	NUMBER NOT NULL 
	)
/

CREATE TABLE RCRA_CME_EVAL_VIOL ( 
	EVAL_VIOL_ID       	VARCHAR2(40) NOT NULL,
	EVAL_ID            	VARCHAR2(40) NOT NULL,
	TRANS_CODE         	VARCHAR2(50) NULL,
	VIOL_ACT_LOC       	VARCHAR2(255) NOT NULL,
	VIOL_SEQ_NUM       	NUMBER NOT NULL,
	AGN_WHICH_DTRM_VIOL	VARCHAR2(255) NOT NULL 
	)
/

CREATE TABLE RCRA_CME_FAC_SUBM ( 
	CME_FAC_SUBM_ID        	VARCHAR2(40) NOT NULL,
	HAZRD_WASTE_CME_SUBM_ID	VARCHAR2(40) NOT NULL,
	EPA_HDLR_ID            	VARCHAR2(255) NOT NULL 
	)
/

CREATE TABLE RCRA_CME_HAZRD_WASTE_CME_SUBM ( 
	HAZRD_WASTE_CME_SUBM_ID	VARCHAR2(40) NOT NULL 
	)
/

CREATE TABLE RCRA_CME_MEDIA ( 
	MEDIA_ID             	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID         	VARCHAR2(40) NOT NULL,
	TRANS_CODE           	VARCHAR2(50) NULL,
	MULTIMEDIA_CODE_OWNER	VARCHAR2(255) NOT NULL,
	MULTIMEDIA_CODE      	VARCHAR2(50) NOT NULL,
	NOTES                	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_MILESTONE ( 
	MILESTONE_ID            	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID            	VARCHAR2(40) NOT NULL,
	TRANS_CODE              	VARCHAR2(50) NULL,
	MILESTONE_SEQ_NUM       	NUMBER NOT NULL,
	TECH_RQMT_IDEN          	VARCHAR2(50) NULL,
	TECH_RQMT_DESC          	VARCHAR2(255) NULL,
	MILESTONE_SCHD_COMP_DATE	DATE NULL,
	MILESTONE_ACTL_COMP_DATE	DATE NULL,
	MILESTONE_DFLT_DATE     	DATE NULL,
	NOTES                   	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_PNLTY ( 
	PNLTY_ID                      	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID                  	VARCHAR2(40) NOT NULL,
	TRANS_CODE                    	VARCHAR2(50) NULL,
	PNLTY_TYPE_OWNER              	VARCHAR2(255) NOT NULL,
	PNLTY_TYPE                    	VARCHAR2(255) NOT NULL,
	CASH_CIVIL_PNLTY_SOUGHT_AMOUNT	NUMBER(14,6) NULL,
	NOTES                         	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_PYMT ( 
	PYMT_ID         	VARCHAR2(40) NOT NULL,
	PNLTY_ID        	VARCHAR2(40) NOT NULL,
	TRANS_CODE      	VARCHAR2(50) NULL,
	PYMT_SEQ_NUM    	NUMBER NOT NULL,
	PYMT_DFLT_DATE  	DATE NULL,
	SCHD_PYMT_DATE  	DATE NULL,
	SCHD_PYMT_AMOUNT	NUMBER(14,6) NULL,
	ACTL_PYMT_DATE  	DATE NULL,
	ACTL_PAID_AMOUNT	NUMBER(14,6) NULL,
	NOTES           	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_RQST ( 
	RQST_ID       	VARCHAR2(40) NOT NULL,
	EVAL_ID       	VARCHAR2(40) NOT NULL,
	TRANS_CODE    	VARCHAR2(50) NULL,
	RQST_SEQ_NUM  	NUMBER NOT NULL,
	DATE_OF_RQST  	DATE NULL,
	DATE_RESP_RCVD	DATE NULL,
	RQST_AGN      	VARCHAR2(255) NULL,
	NOTES         	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_SUPP_ENVR_PRJT ( 
	SUPP_ENVR_PRJT_ID 	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID      	VARCHAR2(40) NOT NULL,
	TRANS_CODE        	VARCHAR2(50) NULL,
	SEP_SEQ_NUM       	NUMBER NOT NULL,
	SEP_EXPND_AMOUNT  	NUMBER(14,6) NULL,
	SEP_SCHD_COMP_DATE	DATE NULL,
	SEP_ACTL_DATE     	DATE NULL,
	SEP_DFLT_DATE     	DATE NULL,
	SEP_CODE_OWNER    	VARCHAR2(255) NULL,
	SEP_DESC_TXT      	VARCHAR2(255) NULL,
	NOTES             	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_VIOL ( 
	VIOL_ID             	VARCHAR2(40) NOT NULL,
	CME_FAC_SUBM_ID     	VARCHAR2(40) NOT NULL,
	TRANS_CODE          	VARCHAR2(50) NULL,
	VIOL_ACT_LOC        	VARCHAR2(255) NOT NULL,
	VIOL_SEQ_NUM        	NUMBER NOT NULL,
	AGN_WHICH_DTRM_VIOL 	VARCHAR2(255) NOT NULL,
	VIOL_TYPE_OWNER     	VARCHAR2(255) NULL,
	VIOL_TYPE           	VARCHAR2(255) NULL,
	FORMER_CITATION_NAME	VARCHAR2(128) NULL,
	VIOL_DTRM_DATE      	DATE NULL,
	RTN_COMPL_ACTL_DATE 	DATE NULL,
	RTN_TO_COMPL_QUAL   	VARCHAR2(255) NULL,
	VIOL_RESP_AGN       	VARCHAR2(255) NULL,
	NOTES               	VARCHAR2(2000) NULL 
	)
/

CREATE TABLE RCRA_CME_VIOL_ENFRC ( 
	VIOL_ENFRC_ID      	VARCHAR2(40) NOT NULL,
	ENFRC_ACT_ID       	VARCHAR2(40) NOT NULL,
	TRANS_CODE         	VARCHAR2(50) NULL,
	VIOL_SEQ_NUM       	NUMBER NOT NULL,
	AGN_WHICH_DTRM_VIOL	VARCHAR2(255) NOT NULL,
	RTN_COMPL_SCHD_DATE	DATE NULL 
	)
/


CREATE UNIQUE INDEX PK_CITATION
	ON RCRA_CME_CITATION(CITATION_ID)
/

CREATE INDEX IX_CTTN_VL_ID
	ON RCRA_CME_CITATION(VIOL_ID)
/

CREATE UNIQUE INDEX PK_CSNY_DATE
	ON RCRA_CME_CSNY_DATE(CSNY_DATE_ID)
/

CREATE INDEX IX_CSN_DT_EN_AC_ID
	ON RCRA_CME_CSNY_DATE(ENFRC_ACT_ID)
/

CREATE UNIQUE INDEX PK_ENFRC_ACT
	ON RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
/

CREATE INDEX IX_EN_AC_CM_FC_SB
	ON RCRA_CME_ENFRC_ACT(CME_FAC_SUBM_ID)
/

CREATE INDEX IX_EVL_CM_FC_SB_ID
	ON RCRA_CME_EVAL(CME_FAC_SUBM_ID)
/

CREATE UNIQUE INDEX PK_EVAL
	ON RCRA_CME_EVAL(EVAL_ID)
/

CREATE INDEX IX_EVL_CMMT_EVL_ID
	ON RCRA_CME_EVAL_COMMIT(EVAL_ID)
/

CREATE UNIQUE INDEX PK_EVAL_COMMIT
	ON RCRA_CME_EVAL_COMMIT(EVAL_COMMIT_ID)
/

CREATE INDEX IX_EVL_VL_EVL_ID
	ON RCRA_CME_EVAL_VIOL(EVAL_ID)
/

CREATE UNIQUE INDEX PK_EVAL_VIOL
	ON RCRA_CME_EVAL_VIOL(EVAL_VIOL_ID)
/

CREATE UNIQUE INDEX PK_CME_FAC_SUBM
	ON RCRA_CME_FAC_SUBM(CME_FAC_SUBM_ID)
/

CREATE INDEX IX_CM_FC_SB_HZ_WS
	ON RCRA_CME_FAC_SUBM(HAZRD_WASTE_CME_SUBM_ID)
/

CREATE UNIQUE INDEX PK_HZR_WST_CME_SBM
	ON RCRA_CME_HAZRD_WASTE_CME_SUBM(HAZRD_WASTE_CME_SUBM_ID)
/

CREATE INDEX IX_MDA_ENFR_ACT_ID
	ON RCRA_CME_MEDIA(ENFRC_ACT_ID)
/

CREATE UNIQUE INDEX PK_MEDIA
	ON RCRA_CME_MEDIA(MEDIA_ID)
/

CREATE UNIQUE INDEX PK_MILESTONE
	ON RCRA_CME_MILESTONE(MILESTONE_ID)
/

CREATE INDEX IX_MLST_ENF_ACT_ID
	ON RCRA_CME_MILESTONE(ENFRC_ACT_ID)
/

CREATE UNIQUE INDEX PK_PNLTY
	ON RCRA_CME_PNLTY(PNLTY_ID)
/

CREATE INDEX IX_PNLT_ENF_ACT_ID
	ON RCRA_CME_PNLTY(ENFRC_ACT_ID)
/

CREATE INDEX IX_PYMT_PNLTY_ID
	ON RCRA_CME_PYMT(PNLTY_ID)
/

CREATE UNIQUE INDEX PK_PYMT
	ON RCRA_CME_PYMT(PYMT_ID)
/

CREATE INDEX IX_RQST_EVAL_ID
	ON RCRA_CME_RQST(EVAL_ID)
/

CREATE UNIQUE INDEX PK_RQST
	ON RCRA_CME_RQST(RQST_ID)
/

CREATE INDEX IX_SP_EN_PR_EN_AC
	ON RCRA_CME_SUPP_ENVR_PRJT(ENFRC_ACT_ID)
/

CREATE UNIQUE INDEX PK_SUPP_ENVR_PRJT
	ON RCRA_CME_SUPP_ENVR_PRJT(SUPP_ENVR_PRJT_ID)
/

CREATE UNIQUE INDEX PK_VIOL
	ON RCRA_CME_VIOL(VIOL_ID)
/

CREATE INDEX IX_VL_CME_FC_SB_ID
	ON RCRA_CME_VIOL(CME_FAC_SUBM_ID)
/

CREATE UNIQUE INDEX PK_VIOL_ENFRC
	ON RCRA_CME_VIOL_ENFRC(VIOL_ENFRC_ID)
/

CREATE INDEX IX_VL_ENF_EN_AC_ID
	ON RCRA_CME_VIOL_ENFRC(ENFRC_ACT_ID)
/

ALTER TABLE RCRA_CME_CITATION
	ADD ( CONSTRAINT PK_CITATION
	PRIMARY KEY (CITATION_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_CSNY_DATE
	ADD ( CONSTRAINT PK_CSNY_DATE
	PRIMARY KEY (CSNY_DATE_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_ENFRC_ACT
	ADD ( CONSTRAINT PK_ENFRC_ACT
	PRIMARY KEY (ENFRC_ACT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_EVAL
	ADD ( CONSTRAINT PK_EVAL
	PRIMARY KEY (EVAL_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_EVAL_COMMIT
	ADD ( CONSTRAINT PK_EVAL_COMMIT
	PRIMARY KEY (EVAL_COMMIT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_EVAL_VIOL
	ADD ( CONSTRAINT PK_EVAL_VIOL
	PRIMARY KEY (EVAL_VIOL_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_FAC_SUBM
	ADD ( CONSTRAINT PK_CME_FAC_SUBM
	PRIMARY KEY (CME_FAC_SUBM_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_HAZRD_WASTE_CME_SUBM
	ADD ( CONSTRAINT PK_HZR_WST_CME_SBM
	PRIMARY KEY (HAZRD_WASTE_CME_SUBM_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_MEDIA
	ADD ( CONSTRAINT PK_MEDIA
	PRIMARY KEY (MEDIA_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_MILESTONE
	ADD ( CONSTRAINT PK_MILESTONE
	PRIMARY KEY (MILESTONE_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_PNLTY
	ADD ( CONSTRAINT PK_PNLTY
	PRIMARY KEY (PNLTY_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_PYMT
	ADD ( CONSTRAINT PK_PYMT
	PRIMARY KEY (PYMT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_RQST
	ADD ( CONSTRAINT PK_RQST
	PRIMARY KEY (RQST_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_SUPP_ENVR_PRJT
	ADD ( CONSTRAINT PK_SUPP_ENVR_PRJT
	PRIMARY KEY (SUPP_ENVR_PRJT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_VIOL
	ADD ( CONSTRAINT PK_VIOL
	PRIMARY KEY (VIOL_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_VIOL_ENFRC
	ADD ( CONSTRAINT PK_VIOL_ENFRC
	PRIMARY KEY (VIOL_ENFRC_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE )
/

ALTER TABLE RCRA_CME_CITATION
	ADD ( CONSTRAINT FK_CITATION_VIOL
	FOREIGN KEY(VIOL_ID)
	REFERENCES RCRA_CME_VIOL(VIOL_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_CSNY_DATE
	ADD ( CONSTRAINT FK_CSN_DTE_ENF_ACT
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_ENFRC_ACT
	ADD ( CONSTRAINT FK_ENF_AC_CM_FC_SB
	FOREIGN KEY(CME_FAC_SUBM_ID)
	REFERENCES RCRA_CME_FAC_SUBM(CME_FAC_SUBM_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_EVAL
	ADD ( CONSTRAINT FK_EVL_CME_FC_SBM
	FOREIGN KEY(CME_FAC_SUBM_ID)
	REFERENCES RCRA_CME_FAC_SUBM(CME_FAC_SUBM_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_EVAL_COMMIT
	ADD ( CONSTRAINT FK_EVL_CMMT_EVL
	FOREIGN KEY(EVAL_ID)
	REFERENCES RCRA_CME_EVAL(EVAL_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_EVAL_VIOL
	ADD ( CONSTRAINT FK_EVAL_VIOL_EVAL
	FOREIGN KEY(EVAL_ID)
	REFERENCES RCRA_CME_EVAL(EVAL_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_FAC_SUBM
	ADD ( CONSTRAINT FK_CM_FC_SB_HZ_WS
	FOREIGN KEY(HAZRD_WASTE_CME_SUBM_ID)
	REFERENCES RCRA_CME_HAZRD_WASTE_CME_SUBM(HAZRD_WASTE_CME_SUBM_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_MEDIA
	ADD ( CONSTRAINT FK_MEDIA_ENFRC_ACT
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_MILESTONE
	ADD ( CONSTRAINT FK_MLSTN_ENFRC_ACT
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_PNLTY
	ADD ( CONSTRAINT FK_PNLTY_ENFRC_ACT
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_PYMT
	ADD ( CONSTRAINT FK_PYMT_PNLTY
	FOREIGN KEY(PNLTY_ID)
	REFERENCES RCRA_CME_PNLTY(PNLTY_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_RQST
	ADD ( CONSTRAINT FK_RQST_EVAL
	FOREIGN KEY(EVAL_ID)
	REFERENCES RCRA_CME_EVAL(EVAL_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_SUPP_ENVR_PRJT
	ADD ( CONSTRAINT FK_SPP_EN_PR_EN_AC
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_VIOL
	ADD ( CONSTRAINT FK_VL_CME_FC_SBM
	FOREIGN KEY(CME_FAC_SUBM_ID)
	REFERENCES RCRA_CME_FAC_SUBM(CME_FAC_SUBM_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

ALTER TABLE RCRA_CME_VIOL_ENFRC
	ADD ( CONSTRAINT FK_VL_ENFR_ENF_ACT
	FOREIGN KEY(ENFRC_ACT_ID)
	REFERENCES RCRA_CME_ENFRC_ACT(ENFRC_ACT_ID)
	ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

