CREATE TABLE JAVA2008.ADVISE_INDEX ( 
    EXPLAIN_REQUESTER   VARCHAR(128) NOT NULL DEFAULT '',
    EXPLAIN_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    SOURCE_NAME         VARCHAR(128) NOT NULL DEFAULT '',
    SOURCE_SCHEMA       VARCHAR(128) NOT NULL DEFAULT '',
    SOURCE_VERSION      VARCHAR(64) NOT NULL DEFAULT '',
    EXPLAIN_LEVEL       CHARACTER(1) NOT NULL DEFAULT '',
    STMTNO              INTEGER NOT NULL DEFAULT 0,
    SECTNO              INTEGER NOT NULL DEFAULT 0,
    QUERYNO             INTEGER NOT NULL DEFAULT 0,
    QUERYTAG            CHARACTER(20) NOT NULL DEFAULT '',
    NAME                VARCHAR(128) NOT NULL,
    CREATOR             VARCHAR(128) NOT NULL DEFAULT '',
    TBNAME              VARCHAR(128) NOT NULL,
    TBCREATOR           VARCHAR(128) NOT NULL DEFAULT '',
    COLNAMES            CLOB(2097152) NOT NULL,
    UNIQUERULE          CHARACTER(1) NOT NULL DEFAULT '',
    COLCOUNT            SMALLINT NOT NULL DEFAULT 0,
    IID                 SMALLINT NOT NULL DEFAULT 0,
    NLEAF               INTEGER NOT NULL DEFAULT 0,
    NLEVELS             SMALLINT NOT NULL DEFAULT 0,
    FIRSTKEYCARD        BIGINT NOT NULL DEFAULT 0,
    FULLKEYCARD         BIGINT NOT NULL DEFAULT 0,
    CLUSTERRATIO        SMALLINT NOT NULL DEFAULT 0,
    CLUSTERFACTOR       DOUBLE NOT NULL DEFAULT 0,
    USERDEFINED         SMALLINT NOT NULL DEFAULT 0,
    SYSTEM_REQUIRED     SMALLINT NOT NULL DEFAULT 0,
    CREATE_TIME         TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    STATS_TIME          TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PAGE_FETCH_PAIRS    VARCHAR(254) NOT NULL DEFAULT '',
    REMARKS             VARCHAR(254) DEFAULT '',
    DEFINER             VARCHAR(128) NOT NULL DEFAULT '',
    CONVERTED           CHARACTER(1) NOT NULL DEFAULT '',
    SEQUENTIAL_PAGES    INTEGER NOT NULL DEFAULT 0,
    DENSITY             INTEGER NOT NULL DEFAULT 0,
    FIRST2KEYCARD       BIGINT NOT NULL DEFAULT 0,
    FIRST3KEYCARD       BIGINT NOT NULL DEFAULT 0,
    FIRST4KEYCARD       BIGINT NOT NULL DEFAULT 0,
    PCTFREE             SMALLINT NOT NULL DEFAULT -1,
    UNIQUE_COLCOUNT     SMALLINT NOT NULL DEFAULT -1,
    MINPCTUSED          SMALLINT NOT NULL DEFAULT 0,
    REVERSE_SCANS       CHARACTER(1) NOT NULL DEFAULT 'N',
    USE_INDEX           CHARACTER(1),
    CREATION_TEXT       CLOB(2097152) NOT NULL DEFAULT '',
    PACKED_DESC         BLOB(1048576) 
    );

CREATE TABLE JAVA2008.ADVISE_WORKLOAD ( 
    WORKLOAD_NAME   CHARACTER(128) NOT NULL DEFAULT 'WK0',
    STATEMENT_NO    INTEGER NOT NULL DEFAULT 1,
    STATEMENT_TEXT  CLOB(2097152) NOT NULL,
    STATEMENT_TAG   VARCHAR(256) NOT NULL DEFAULT '',
    FREQUENCY       INTEGER NOT NULL DEFAULT 1,
    IMPORTANCE      DOUBLE NOT NULL DEFAULT 1,
    WEIGHT          DOUBLE NOT NULL DEFAULT 1,
    COST_BEFORE     DOUBLE,
    COST_AFTER      DOUBLE,
    COMPILABLE      CHARACTER(17) 
    );

CREATE TABLE JAVA2008.EXPLAIN_ARGUMENT ( 
    EXPLAIN_REQUESTER   VARCHAR(128) NOT NULL,
    EXPLAIN_TIME        TIMESTAMP NOT NULL,
    SOURCE_NAME         VARCHAR(128) NOT NULL,
    SOURCE_SCHEMA       VARCHAR(128) NOT NULL,
    SOURCE_VERSION      VARCHAR(64) NOT NULL,
    EXPLAIN_LEVEL       CHARACTER(1) NOT NULL,
    STMTNO              INTEGER NOT NULL,
    SECTNO              INTEGER NOT NULL,
    OPERATOR_ID         INTEGER NOT NULL,
    ARGUMENT_TYPE       CHARACTER(8) NOT NULL,
    ARGUMENT_VALUE      VARCHAR(1024),
    LONG_ARGUMENT_VALUE CLOB(2097152) 
    );

CREATE TABLE JAVA2008.EXPLAIN_INSTANCE ( 
    EXPLAIN_REQUESTER   VARCHAR(128) NOT NULL,
    EXPLAIN_TIME        TIMESTAMP NOT NULL,
    SOURCE_NAME         VARCHAR(128) NOT NULL,
    SOURCE_SCHEMA       VARCHAR(128) NOT NULL,
    SOURCE_VERSION      VARCHAR(64) NOT NULL,
    EXPLAIN_OPTION      CHARACTER(1) NOT NULL,
    SNAPSHOT_TAKEN      CHARACTER(1) NOT NULL,
    DB2_VERSION         CHARACTER(7) NOT NULL,
    SQL_TYPE            CHARACTER(1) NOT NULL,
    QUERYOPT            INTEGER NOT NULL,
    BLOCK               CHARACTER(1) NOT NULL,
    ISOLATION           CHARACTER(2) NOT NULL,
    BUFFPAGE            INTEGER NOT NULL,
    AVG_APPLS           INTEGER NOT NULL,
    SORTHEAP            INTEGER NOT NULL,
    LOCKLIST            INTEGER NOT NULL,
    MAXLOCKS            SMALLINT NOT NULL,
    LOCKS_AVAIL         INTEGER NOT NULL,
    CPU_SPEED           DOUBLE NOT NULL,
    REMARKS             VARCHAR(254),
    DBHEAP              INTEGER NOT NULL,
    COMM_SPEED          DOUBLE NOT NULL,
    PARALLELISM         CHARACTER(2) NOT NULL,
    DATAJOINER          CHARACTER(1) NOT NULL 
    );

CREATE TABLE JAVA2008.EXPLAIN_OBJECT ( 
    EXPLAIN_REQUESTER               VARCHAR(128) NOT NULL,
    EXPLAIN_TIME                    TIMESTAMP NOT NULL,
    SOURCE_NAME                     VARCHAR(128) NOT NULL,
    SOURCE_SCHEMA                   VARCHAR(128) NOT NULL,
    SOURCE_VERSION                  VARCHAR(64) NOT NULL,
    EXPLAIN_LEVEL                   CHARACTER(1) NOT NULL,
    STMTNO                          INTEGER NOT NULL,
    SECTNO                          INTEGER NOT NULL,
    OBJECT_SCHEMA                   VARCHAR(128) NOT NULL,
    OBJECT_NAME                     VARCHAR(128) NOT NULL,
    OBJECT_TYPE                     CHARACTER(2) NOT NULL,
    CREATE_TIME                     TIMESTAMP,
    STATISTICS_TIME                 TIMESTAMP,
    COLUMN_COUNT                    SMALLINT NOT NULL,
    ROW_COUNT                       BIGINT NOT NULL,
    WIDTH                           INTEGER NOT NULL,
    PAGES                           INTEGER NOT NULL,
    DISTINCT                        CHARACTER(1) NOT NULL,
    TABLESPACE_NAME                 VARCHAR(128),
    OVERHEAD                        DOUBLE NOT NULL,
    TRANSFER_RATE                   DOUBLE NOT NULL,
    PREFETCHSIZE                    INTEGER NOT NULL,
    EXTENTSIZE                      INTEGER NOT NULL,
    CLUSTER                         DOUBLE NOT NULL,
    NLEAF                           INTEGER NOT NULL,
    NLEVELS                         INTEGER NOT NULL,
    FULLKEYCARD                     BIGINT NOT NULL,
    OVERFLOW                        INTEGER NOT NULL,
    FIRSTKEYCARD                    BIGINT NOT NULL,
    FIRST2KEYCARD                   BIGINT NOT NULL,
    FIRST3KEYCARD                   BIGINT NOT NULL,
    FIRST4KEYCARD                   BIGINT NOT NULL,
    SEQUENTIAL_PAGES                INTEGER NOT NULL,
    DENSITY                         INTEGER NOT NULL,
    STATS_SRC                       CHARACTER(1) NOT NULL,
    AVERAGE_SEQUENCE_GAP            DOUBLE NOT NULL,
    AVERAGE_SEQUENCE_FETCH_GAP      DOUBLE NOT NULL,
    AVERAGE_SEQUENCE_PAGES          DOUBLE NOT NULL,
    AVERAGE_SEQUENCE_FETCH_PAGES    DOUBLE NOT NULL,
    AVERAGE_RANDOM_PAGES            DOUBLE NOT NULL,
    AVERAGE_RANDOM_FETCH_PAGES      DOUBLE NOT NULL,
    NUMRIDS                         BIGINT NOT NULL,
    NUMRIDS_DELETED                 BIGINT NOT NULL,
    NUM_EMPTY_LEAFS                 BIGINT NOT NULL,
    ACTIVE_BLOCKS                   BIGINT NOT NULL 
    );

CREATE TABLE JAVA2008.EXPLAIN_OPERATOR ( 
    EXPLAIN_REQUESTER   VARCHAR(128) NOT NULL,
    EXPLAIN_TIME        TIMESTAMP NOT NULL,
    SOURCE_NAME         VARCHAR(128) NOT NULL,
    SOURCE_SCHEMA       VARCHAR(128) NOT NULL,
    SOURCE_VERSION      VARCHAR(64) NOT NULL,
    EXPLAIN_LEVEL       CHARACTER(1) NOT NULL,
    STMTNO              INTEGER NOT NULL,
    SECTNO              INTEGER NOT NULL,
    OPERATOR_ID         INTEGER NOT NULL,
    OPERATOR_TYPE       CHARACTER(6) NOT NULL,
    TOTAL_COST          DOUBLE NOT NULL,
    IO_COST             DOUBLE NOT NULL,
    CPU_COST            DOUBLE NOT NULL,
    FIRST_ROW_COST      DOUBLE NOT NULL,
    RE_TOTAL_COST       DOUBLE NOT NULL,
    RE_IO_COST          DOUBLE NOT NULL,
    RE_CPU_COST         DOUBLE NOT NULL,
    COMM_COST           DOUBLE NOT NULL,
    FIRST_COMM_COST     DOUBLE NOT NULL,
    BUFFERS             DOUBLE NOT NULL,
    REMOTE_TOTAL_COST   DOUBLE NOT NULL,
    REMOTE_COMM_COST    DOUBLE NOT NULL 
    );

CREATE TABLE JAVA2008.EXPLAIN_PREDICATE ( 
    EXPLAIN_REQUESTER   VARCHAR(128) NOT NULL,
    EXPLAIN_TIME        TIMESTAMP NOT NULL,
    SOURCE_NAME         VARCHAR(128) NOT NULL,
    SOURCE_SCHEMA       VARCHAR(128) NOT NULL,
    SOURCE_VERSION      VARCHAR(64) NOT NULL,
    EXPLAIN_LEVEL       CHARACTER(1) NOT NULL,
    STMTNO              INTEGER NOT NULL,
    SECTNO              INTEGER NOT NULL,
    OPERATOR_ID         INTEGER NOT NULL,
    PREDICATE_ID        INTEGER NOT NULL,
    HOW_APPLIED         CHARACTER(5) NOT NULL,
    WHEN_EVALUATED      CHARACTER(3) NOT NULL,
    RELOP_TYPE          CHARACTER(2) NOT NULL,
    SUBQUERY            CHARACTER(1) NOT NULL,
    FILTER_FACTOR       DOUBLE NOT NULL,
    PREDICATE_TEXT      CLOB(2097152) 
    );

CREATE TABLE JAVA2008.EXPLAIN_STATEMENT ( 
    EXPLAIN_REQUESTER   VARCHAR(128) NOT NULL,
    EXPLAIN_TIME        TIMESTAMP NOT NULL,
    SOURCE_NAME         VARCHAR(128) NOT NULL,
    SOURCE_SCHEMA       VARCHAR(128) NOT NULL,
    SOURCE_VERSION      VARCHAR(64) NOT NULL,
    EXPLAIN_LEVEL       CHARACTER(1) NOT NULL,
    STMTNO              INTEGER NOT NULL,
    SECTNO              INTEGER NOT NULL,
    QUERYNO             INTEGER NOT NULL,
    QUERYTAG            CHARACTER(20) NOT NULL,
    STATEMENT_TYPE      CHARACTER(2) NOT NULL,
    UPDATABLE           CHARACTER(1) NOT NULL,
    DELETABLE           CHARACTER(1) NOT NULL,
    TOTAL_COST          DOUBLE NOT NULL,
    STATEMENT_TEXT      CLOB(2097152) NOT NULL,
    SNAPSHOT            BLOB(10485760),
    QUERY_DEGREE        INTEGER NOT NULL 
    );

CREATE TABLE JAVA2008.EXPLAIN_STREAM ( 
    EXPLAIN_REQUESTER   VARCHAR(128) NOT NULL,
    EXPLAIN_TIME        TIMESTAMP NOT NULL,
    SOURCE_NAME         VARCHAR(128) NOT NULL,
    SOURCE_SCHEMA       VARCHAR(128) NOT NULL,
    SOURCE_VERSION      VARCHAR(64) NOT NULL,
    EXPLAIN_LEVEL       CHARACTER(1) NOT NULL,
    STMTNO              INTEGER NOT NULL,
    SECTNO              INTEGER NOT NULL,
    STREAM_ID           INTEGER NOT NULL,
    SOURCE_TYPE         CHARACTER(1) NOT NULL,
    SOURCE_ID           INTEGER NOT NULL,
    TARGET_TYPE         CHARACTER(1) NOT NULL,
    TARGET_ID           INTEGER NOT NULL,
    OBJECT_SCHEMA       VARCHAR(128),
    OBJECT_NAME         VARCHAR(128),
    STREAM_COUNT        DOUBLE NOT NULL,
    COLUMN_COUNT        SMALLINT NOT NULL,
    PREDICATE_ID        INTEGER NOT NULL,
    COLUMN_NAMES        CLOB(2097152),
    PMID                SMALLINT NOT NULL,
    SINGLE_NODE         CHARACTER(5),
    PARTITION_COLUMNS   CLOB(2097152) 
    );

CREATE TABLE JAVA2008.NACCOUNT ( 
    ID          VARCHAR(50) NOT NULL,
    NAASACCOUNT VARCHAR(500) NOT NULL,
    ISACTIVE    CHARACTER(1) NOT NULL,
    SYSTEMROLE  VARCHAR(50) NOT NULL,
    AFFILIATION VARCHAR(50) NOT NULL,
    MODIFIEDBY  VARCHAR(50) NOT NULL,
    MODIFIEDON  DATE NOT NULL 
    );

CREATE TABLE JAVA2008.NACCOUNTPOLICY ( 
    ID          VARCHAR(50) NOT NULL,
    ACCOUNTID   VARCHAR(50) NOT NULL,
    POLICYTYPE  VARCHAR(50) NOT NULL,
    QUALIFIER   VARCHAR(500) NOT NULL,
    ISALLOWED   CHARACTER(1) NOT NULL,
    MODIFIEDBY  VARCHAR(50) NOT NULL,
    MODIFIEDON  DATE NOT NULL 
    );

CREATE TABLE JAVA2008.NACTIVITY ( 
    ID              VARCHAR(50) NOT NULL,
    ACTIVITYTYPE    VARCHAR(128) NOT NULL,
    TRANSACTIONID   VARCHAR(50),
    IP              VARCHAR(64),
    MODIFIEDBY      VARCHAR(50) NOT NULL,
    MODIFIEDON      DATE NOT NULL 
    );

CREATE TABLE JAVA2008.NACTIVITYDETAIL ( 
    ID          VARCHAR(50) NOT NULL,
    ACTIVITYID  VARCHAR(50) NOT NULL,
    DETAIL      VARCHAR(4000) NOT NULL,
    MODIFIEDON  DATE NOT NULL 
    );

CREATE TABLE JAVA2008.NCONFIG ( 
    ID          VARCHAR(255) NOT NULL,
    CONFIGVALUE VARCHAR(4000) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    MODIFIEDBY  VARCHAR(50) NOT NULL,
    MODIFIEDON  DATE NOT NULL,
    ISEDITABLE  CHARACTER(1) NOT NULL 
    );

CREATE TABLE JAVA2008.NCONNECTION ( 
    ID                  VARCHAR(50) NOT NULL,
    CODE                VARCHAR(255) NOT NULL,
    PROVIDER            VARCHAR(500) NOT NULL,
    CONNECTIONSTRING    VARCHAR(500) NOT NULL,
    MODIFIEDBY          VARCHAR(50) NOT NULL,
    MODIFIEDON          DATE NOT NULL 
    );

CREATE TABLE JAVA2008.NDOCUMENT ( 
    ID              VARCHAR(50) NOT NULL,
    TRANSACTIONID   VARCHAR(50) NOT NULL,
    DOCUMENTNAME    VARCHAR(255) NOT NULL,
    DOCUMENTTYPE    VARCHAR(255) NOT NULL,
    DOCUMENTID      VARCHAR(255) NOT NULL,
    STATUS          VARCHAR(50) NOT NULL,
    STATUSDETAIL    VARCHAR(4000),
    DOCUMENTCONTENT BLOB(1048576) 
    );

CREATE TABLE JAVA2008.NFLOW ( 
    ID          VARCHAR(50) NOT NULL,
    INFOURL     VARCHAR(500) NOT NULL,
    CONTACT     VARCHAR(255) NOT NULL,
    ISPROTECTED CHARACTER(1) NOT NULL,
    MODIFIEDBY  VARCHAR(50) NOT NULL,
    MODIFIEDON  DATE NOT NULL,
    CODE        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(500) 
    );

CREATE TABLE JAVA2008.NNOTIFICATION ( 
    ID          VARCHAR(50) NOT NULL,
    FLOWID      VARCHAR(50) NOT NULL,
    ACCOUNTID   VARCHAR(50) NOT NULL,
    ONSOLICIT   CHARACTER(1) NOT NULL,
    ONQUERY     CHARACTER(1) NOT NULL,
    ONSUBMIT    CHARACTER(1) NOT NULL,
    ONNOTIFY    CHARACTER(1) NOT NULL,
    ONSCHEDULE  CHARACTER(1) NOT NULL,
    ONDOWNLOAD  CHARACTER(1) NOT NULL,
    ONEXECUTE   CHARACTER(1) NOT NULL 
    );

CREATE TABLE JAVA2008.NPARTNER ( 
    ID          VARCHAR(50) NOT NULL,
    NAME        VARCHAR(50) NOT NULL,
    URL         VARCHAR(500) NOT NULL,
    MODIFIEDBY  VARCHAR(50) NOT NULL,
    MODIFIEDON  DATE NOT NULL,
    VERSION     VARCHAR(50) NOT NULL 
    );

CREATE TABLE JAVA2008.NPLUGIN ( 
    ID              VARCHAR(50) NOT NULL,
    FLOWID          VARCHAR(50) NOT NULL,
    MODIFIEDBY      VARCHAR(50) NOT NULL,
    MODIFIEDON      DATE NOT NULL,
    PLUGINCONTENT   BLOB(1048576) NOT NULL 
    );

CREATE TABLE JAVA2008.NREQUEST ( 
    ID              VARCHAR(50) NOT NULL,
    TRANSACTIONID   VARCHAR(50),
    SERVICEID       VARCHAR(50) NOT NULL,
    ROWINDEX        INTEGER NOT NULL,
    MAXROWCOUNT     INTEGER NOT NULL,
    REQUESTTYPE     VARCHAR(50) NOT NULL,
    MODIFIEDBY      VARCHAR(50) NOT NULL,
    MODIFIEDON      DATE NOT NULL 
    );

CREATE TABLE JAVA2008.NREQUESTARG ( 
    ID          VARCHAR(50) NOT NULL,
    REQUESTID   VARCHAR(50) NOT NULL,
    ARGKEY      VARCHAR(255) NOT NULL,
    ARGVALUE    VARCHAR(1024) NOT NULL 
    );

CREATE TABLE JAVA2008.NSCHEDULE ( 
    ID                  VARCHAR(50) NOT NULL,
    NAME                VARCHAR(50) NOT NULL,
    FLOWID              VARCHAR(50) NOT NULL,
    STARTON             DATE NOT NULL,
    ENDON               DATE NOT NULL,
    SOURCETYPE          VARCHAR(50) NOT NULL,
    SOURCEID            VARCHAR(255) NOT NULL,
    SOURCEOPERATION     VARCHAR(255),
    TARGETTYPE          VARCHAR(50),
    TARGETID            VARCHAR(255),
    LASTEXECUTIONINFO   VARCHAR(4000),
    LASTEXECUTEDON      DATE,
    NEXTRUN             DATE,
    FREQUENCYTYPE       VARCHAR(50) NOT NULL,
    FREQUENCY           INTEGER NOT NULL,
    MODIFIEDBY          VARCHAR(50) NOT NULL,
    MODIFIEDON          DATE NOT NULL,
    ISACTIVE            VARCHAR(1) NOT NULL,
    ISRUNNOW            VARCHAR(1) NOT NULL,
    EXECUTESTATUS       VARCHAR(50) NOT NULL 
    );

CREATE TABLE JAVA2008.NSCHEDULESOURCEARG ( 
    ID          VARCHAR(50) NOT NULL,
    SCHEDULEID  VARCHAR(50) NOT NULL,
    ARGKEY      VARCHAR(255) NOT NULL,
    ARGVALUE    VARCHAR(4000) NOT NULL 
    );

CREATE TABLE JAVA2008.NSERVICE ( 
    ID          VARCHAR(50) NOT NULL,
    NAME        VARCHAR(50) NOT NULL,
    FLOWID      VARCHAR(50) NOT NULL,
    ISACTIVE    CHARACTER(1) NOT NULL,
    SERVICETYPE VARCHAR(128) NOT NULL,
    IMPLEMENTOR VARCHAR(500) NOT NULL,
    AUTHLEVEL   VARCHAR(50) NOT NULL,
    MODIFIEDBY  VARCHAR(50) NOT NULL,
    MODIFIEDON  DATE NOT NULL 
    );

CREATE TABLE JAVA2008.NSERVICEARG ( 
    ID          VARCHAR(50) NOT NULL,
    SERVICEID   VARCHAR(50) NOT NULL,
    ARGKEY      VARCHAR(255) NOT NULL,
    ARGVALUE    VARCHAR(1024) NOT NULL 
    );

CREATE TABLE JAVA2008.NSERVICECONN ( 
    ID              VARCHAR(50) NOT NULL,
    SERVICEID       VARCHAR(50) NOT NULL,
    CONNECTIONID    VARCHAR(50) NOT NULL,
    KEYNAME         VARCHAR(255) NOT NULL 
    );

CREATE TABLE JAVA2008.NTRANSACTION ( 
    ID              VARCHAR(50) NOT NULL,
    FLOWID          VARCHAR(50) NOT NULL,
    NETWORKID       VARCHAR(255) NOT NULL,
    STATUS          VARCHAR(50) NOT NULL,
    MODIFIEDBY      VARCHAR(50) NOT NULL,
    MODIFIEDON      DATE NOT NULL,
    STATUSDETAIL    VARCHAR(4000),
    OPERATION       VARCHAR(255),
    WEBMETHOD       VARCHAR(50) NOT NULL 
    );

CREATE TABLE JAVA2008.NTRANSACTIONNOTIFICATION ( 
    ID              VARCHAR(50) NOT NULL,
    TRANSACTIONID   VARCHAR(50) NOT NULL,
    URI             VARCHAR(500) NOT NULL,
    TYPE            VARCHAR(50) NOT NULL 
    );

CREATE TABLE JAVA2008.NTRANSACTIONRECIPIENT ( 
    ID              VARCHAR(50) NOT NULL,
    TRANSACTIONID   VARCHAR(50) NOT NULL,
    URI             VARCHAR(500) NOT NULL 
    );


CREATE UNIQUE INDEX JAVA2008.UNQ_ACCOT_NAASACCT
    ON JAVA2008.NACCOUNT(NAASACCOUNT);

CREATE UNIQUE INDEX JAVA2008.UNQ_CONNECT_CODE
    ON JAVA2008.NCONNECTION(CODE);

CREATE UNIQUE INDEX JAVA2008.UNQ_DOC_TRANID
    ON JAVA2008.NDOCUMENT(TRANSACTIONID, DOCUMENTNAME);

CREATE UNIQUE INDEX JAVA2008.UNQ_FLOW_CODE
    ON JAVA2008.NFLOW(CODE);

CREATE UNIQUE INDEX JAVA2008.UNQ_NOTIF_FLOWACCT
    ON JAVA2008.NNOTIFICATION(FLOWID, ACCOUNTID);

CREATE UNIQUE INDEX JAVA2008.UNQ_PARTNER_NAME
    ON JAVA2008.NPARTNER(NAME);

CREATE UNIQUE INDEX JAVA2008.UNQ_SCHARG_SCHIDNM
    ON JAVA2008.NSCHEDULESOURCEARG(SCHEDULEID, ARGKEY);

CREATE UNIQUE INDEX JAVA2008.UNQ_SVC_NAMEFLOWID
    ON JAVA2008.NSERVICE(NAME, FLOWID);

CREATE UNIQUE INDEX JAVA2008.UNQ_SVC_SVCIDKEYNM
    ON JAVA2008.NSERVICECONN(SERVICEID, KEYNAME);

ALTER TABLE JAVA2008.EXPLAIN_INSTANCE
    ADD CONSTRAINT SQL090413162532120
    PRIMARY KEY (EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION);

ALTER TABLE JAVA2008.EXPLAIN_STATEMENT
    ADD CONSTRAINT SQL090413162532170
    PRIMARY KEY (EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO);

ALTER TABLE JAVA2008.NACCOUNT
    ADD CONSTRAINT SQL090413171757450
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NACCOUNTPOLICY
    ADD CONSTRAINT SQL090413171757460
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NACTIVITY
    ADD CONSTRAINT SQL090413171757480
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NCONFIG
    ADD CONSTRAINT SQL090413171757510
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NCONNECTION
    ADD CONSTRAINT SQL090413171757540
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NDOCUMENT
    ADD CONSTRAINT SQL090413171757550
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NFLOW
    ADD CONSTRAINT SQL090413171757590
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NNOTIFICATION
    ADD CONSTRAINT SQL090413171757600
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NPARTNER
    ADD CONSTRAINT SQL090413171757630
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NPLUGIN
    ADD CONSTRAINT SQL090413171757650
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NREQUEST
    ADD CONSTRAINT SQL090413171757660
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NREQUESTARG
    ADD CONSTRAINT SQL090413171757700
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NSCHEDULE
    ADD CONSTRAINT SQL090413171757710
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NSCHEDULESOURCEARG
    ADD CONSTRAINT SQL090413171757730
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NSERVICE
    ADD CONSTRAINT SQL090413171757760
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NSERVICECONN
    ADD CONSTRAINT SQL090413171757800
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NTRANSACTION
    ADD CONSTRAINT SQL090413171757820
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NTRANSACTIONNOTIFICATION
    ADD CONSTRAINT SQL090413171757850
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.NTRANSACTIONRECIPIENT
    ADD CONSTRAINT SQL090413171757870
    PRIMARY KEY (ID);

ALTER TABLE JAVA2008.EXPLAIN_ARGUMENT
    ADD CONSTRAINT SQL090413162532210
    FOREIGN KEY(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
    REFERENCES JAVA2008.EXPLAIN_STATEMENT(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.EXPLAIN_OBJECT
    ADD CONSTRAINT SQL090413162532200
    FOREIGN KEY(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
    REFERENCES JAVA2008.EXPLAIN_STATEMENT(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.EXPLAIN_OPERATOR
    ADD CONSTRAINT SQL090413162532180
    FOREIGN KEY(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
    REFERENCES JAVA2008.EXPLAIN_STATEMENT(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.EXPLAIN_PREDICATE
    ADD CONSTRAINT SQL090413162532200
    FOREIGN KEY(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
    REFERENCES JAVA2008.EXPLAIN_STATEMENT(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.EXPLAIN_STATEMENT
    ADD CONSTRAINT SQL090413162532171
    FOREIGN KEY(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION)
    REFERENCES JAVA2008.EXPLAIN_INSTANCE(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.EXPLAIN_STREAM
    ADD CONSTRAINT SQL090413162532230
    FOREIGN KEY(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
    REFERENCES JAVA2008.EXPLAIN_STATEMENT(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NACCOUNT
    ADD CONSTRAINT FK_ACCOUNT_ACCOUNT
    FOREIGN KEY(MODIFIEDBY)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NACCOUNTPOLICY
    ADD CONSTRAINT FK_ACCTPOL_ACCT
    FOREIGN KEY(MODIFIEDBY)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NACCOUNTPOLICY
    ADD CONSTRAINT FK_ACCTIDPOL_ACCT
    FOREIGN KEY(ACCOUNTID)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NACTIVITY
    ADD CONSTRAINT FK_ACT_TRANS
    FOREIGN KEY(TRANSACTIONID)
    REFERENCES JAVA2008.NTRANSACTION(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NACTIVITY
    ADD CONSTRAINT FK_ACT_ACCT
    FOREIGN KEY(MODIFIEDBY)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NACTIVITYDETAIL
    ADD CONSTRAINT FK_ACTIVDET_ACT
    FOREIGN KEY(ACTIVITYID)
    REFERENCES JAVA2008.NACTIVITY(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NCONFIG
    ADD CONSTRAINT FK_CONFIG_ACCOUNT
    FOREIGN KEY(MODIFIEDBY)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NCONNECTION
    ADD CONSTRAINT FK_CONNECT_ACCOUNT
    FOREIGN KEY(MODIFIEDBY)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NDOCUMENT
    ADD CONSTRAINT FK_DOC_TRANS
    FOREIGN KEY(TRANSACTIONID)
    REFERENCES JAVA2008.NTRANSACTION(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NFLOW
    ADD CONSTRAINT FK_FLOW_ACCOUNT
    FOREIGN KEY(MODIFIEDBY)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NNOTIFICATION
    ADD CONSTRAINT FK_NOTIF_FLOW
    FOREIGN KEY(FLOWID)
    REFERENCES JAVA2008.NFLOW(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NNOTIFICATION
    ADD CONSTRAINT FK_NOTIF_ACCT
    FOREIGN KEY(ACCOUNTID)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NPARTNER
    ADD CONSTRAINT FK_PARTNER_ACCOUNT
    FOREIGN KEY(MODIFIEDBY)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NPLUGIN
    ADD CONSTRAINT FK_NPLUGIN_NFLOW
    FOREIGN KEY(FLOWID)
    REFERENCES JAVA2008.NFLOW(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NPLUGIN
    ADD CONSTRAINT FK_NPLUGIN_NACCT
    FOREIGN KEY(MODIFIEDBY)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NREQUEST
    ADD CONSTRAINT FK_REQUEST_TRANS
    FOREIGN KEY(TRANSACTIONID)
    REFERENCES JAVA2008.NTRANSACTION(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NREQUEST
    ADD CONSTRAINT FK_REQUEST_SVC
    FOREIGN KEY(SERVICEID)
    REFERENCES JAVA2008.NSERVICE(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NREQUEST
    ADD CONSTRAINT FK_MODBY_REQ_ACCT
    FOREIGN KEY(MODIFIEDBY)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NREQUESTARG
    ADD CONSTRAINT FK_REQ_REQUEST
    FOREIGN KEY(REQUESTID)
    REFERENCES JAVA2008.NREQUEST(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NSCHEDULESOURCEARG
    ADD CONSTRAINT FK_SCHEDSRC_SCHED
    FOREIGN KEY(SCHEDULEID)
    REFERENCES JAVA2008.NSCHEDULE(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NSERVICE
    ADD CONSTRAINT FK_SERVICE_FLOW
    FOREIGN KEY(FLOWID)
    REFERENCES JAVA2008.NFLOW(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NSERVICE
    ADD CONSTRAINT FK_SERVICE_ACCOUNT
    FOREIGN KEY(MODIFIEDBY)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NSERVICEARG
    ADD CONSTRAINT FK_SVCEARG_SVC
    FOREIGN KEY(SERVICEID)
    REFERENCES JAVA2008.NSERVICE(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NSERVICECONN
    ADD CONSTRAINT FK_SVCCONN_SVC
    FOREIGN KEY(SERVICEID)
    REFERENCES JAVA2008.NSERVICE(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NSERVICECONN
    ADD CONSTRAINT FK_SVCCONN_CONN
    FOREIGN KEY(CONNECTIONID)
    REFERENCES JAVA2008.NCONNECTION(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NTRANSACTION
    ADD CONSTRAINT FK_MODBY_TRAN_ACCT
    FOREIGN KEY(MODIFIEDBY)
    REFERENCES JAVA2008.NACCOUNT(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NTRANSACTIONNOTIFICATION
    ADD CONSTRAINT FK_TRANOT_TRANS
    FOREIGN KEY(TRANSACTIONID)
    REFERENCES JAVA2008.NTRANSACTION(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

ALTER TABLE JAVA2008.NTRANSACTIONRECIPIENT
    ADD CONSTRAINT FK_TRANREC_TRANS
    FOREIGN KEY(TRANSACTIONID)
    REFERENCES JAVA2008.NTRANSACTION(ID)
    ON DELETE CASCADE 
    ON UPDATE NO ACTION ;

