CREATE TABLE "FRS_DELETEDFACILITIES" ( 
	"STATEFACILITYIDENTIFIER"	VARCHAR2(255) NOT NULL,
	"DELETEDONDATE"          	VARCHAR2(10) NOT NULL,
	PRIMARY KEY("STATEFACILITYIDENTIFIER")
	NOT DEFERRABLE
	 VALIDATE
)
/
CREATE TABLE "FRS_ENVIRONMENTALINTEREST" ( 
	"STATEFACILITYIDENTIFIER"       	VARCHAR2(255) NOT NULL,
	"INFORMATIONSYSTEMIDENTIFIER"   	VARCHAR2(255) NOT NULL,
	"ENVIRONMENTALINTERESTTYPETEXT" 	VARCHAR2(255) NOT NULL,
	"INFORMATIONSYSTEMACRONYMNAME"  	VARCHAR2(255) NULL,
	"FEDERALSTATEINTERESTINDICATOR" 	VARCHAR2(255) NULL,
	"ENVIRONMENTALINTERESTSTARTDATE"	VARCHAR2(10) NULL,
	"INTERESTSTARTDATEQUALIFIERTEXT"	VARCHAR2(255) NULL,
	"ENVIRONMENTALINTERESTENDDATE"  	VARCHAR2(10) NULL,
	"INTERESTENDDATEQUALIFIERTEXT"  	VARCHAR2(255) NULL,
	"FRSINDICATOR"                  	NUMBER(1,0) DEFAULT 0 NOT NULL,
	"DOHINDICATOR"                  	NUMBER(1,0) DEFAULT 0 NOT NULL,
	PRIMARY KEY("STATEFACILITYIDENTIFIER","INFORMATIONSYSTEMIDENTIFIER","ENVIRONMENTALINTERESTTYPETEXT")
	NOT DEFERRABLE
	 VALIDATE
)
/
CREATE TABLE "FRS_FACILITYSITE" ( 
	"STATEFACILITYIDENTIFIER"       	VARCHAR2(255) NOT NULL,
	"SOURCEOFDATA"                  	VARCHAR2(255) NULL,
	"LASTREPORTEDDATE"              	VARCHAR2(10) NOT NULL,
	"STATEFACILITYSYSTEMACRONYMNAME"	VARCHAR2(255) NOT NULL,
	"FACILITYREGISTRYIDENTIFIER"    	VARCHAR2(255) NULL,
	"FACILITYSITENAME"              	VARCHAR2(255) NULL,
	"FACILITYSITETYPENAME"          	VARCHAR2(255) NULL,
	"FEDERALFACILITYINDICATOR"      	VARCHAR2(255) NULL,
	"TRIBALLANDINDICATOR"           	VARCHAR2(255) NULL,
	"TRIBALLANDNAME"                	VARCHAR2(255) NULL,
	"CONGRESSIONALDISTRICTNUMBER"   	VARCHAR2(2) NULL,
	"LEGISLATIVEDISTRICTNUMBER"     	VARCHAR2(2) NULL,
	"HUCCODE"                       	VARCHAR2(8) NULL,
	"LOCATIONADDRESSTEXT"           	VARCHAR2(255) NULL,
	"SUPPLEMENTALLOCATIONTEXT"      	VARCHAR2(255) NULL,
	"LOCALITYNAME"                  	VARCHAR2(255) NULL,
	"COUNTYSTATEFIPSCODE"           	VARCHAR2(5) NULL,
	"COUNTYNAME"                    	VARCHAR2(255) NULL,
	"STATEUSPSCODE"                 	VARCHAR2(2) NULL,
	"STATENAME"                     	VARCHAR2(255) NULL,
	"COUNTRYNAME"                   	VARCHAR2(255) NULL,
	"LOCATIONZIPCODE"               	VARCHAR2(255) NULL,
	"LOCATIONDESCRIPTIONTEXT"       	VARCHAR2(255) NULL,
	"ALTERNATIVENAME"               	VARCHAR2(255) NULL,
	"ALTERNATIVENAMETYPETEXT"       	VARCHAR2(255) NULL,
	"MAILINGADDRESSTEXT"            	VARCHAR2(255) NULL,
	"SUPPLEMENTALADDRESSTEXT"       	VARCHAR2(255) NULL,
	"MAILINGADDRESSCITYNAME"        	VARCHAR2(255) NULL,
	"MAILINGADDRESSSTATEUSPSCODE"   	VARCHAR2(2) NULL,
	"MAILINGADDRESSSTATENAME"       	VARCHAR2(255) NULL,
	"MAILINGADDRESSCOUNTRYNAME"     	VARCHAR2(255) NULL,
	"MAILINGADDRESSZIPCODE"         	VARCHAR2(255) NULL,
	PRIMARY KEY("STATEFACILITYIDENTIFIER")
	NOT DEFERRABLE
	 VALIDATE
)
/
CREATE TABLE "FRS_GEOGRAPHICCOORDINATES" ( 
	"STATEFACILITYIDENTIFIER"       	VARCHAR2(255) NOT NULL,
	"LATITUDEMEASURE"               	NUMBER(8,6) NOT NULL,
	"LONGITUDEMEASURE"              	NUMBER(9,6) NOT NULL,
	"HORIZONTALACCURACYMEASURE"     	NUMBER(22,0) NULL,
	"HORIZONTALCOLLECTIONMETHODTEXT"	VARCHAR2(255) NULL,
	"HORIZONTALREFERENCEDATUMNAME"  	VARCHAR2(255) NULL,
	"SOURCEMAPSCALENUMBER"          	NUMBER(22,0) NULL,
	"REFERENCEPOINTTEXT"            	VARCHAR2(255) NULL,
	"DATACOLLECTIONDATE"            	VARCHAR2(10) NULL,
	"GEOMETRICTYPENAME"             	VARCHAR2(255) NULL,
	"LOCATIONCOMMENTSTEXT"          	VARCHAR2(255) NULL,
	"VERTICALCOLLECTIONMETHODTEXT"  	VARCHAR2(255) NULL,
	"VERTICALMEASURE"               	NUMBER(18,0) NULL,
	"VERTICALACCURACYMEASURE"       	NUMBER(22,0) NULL,
	"VERTICALREFERENCEDATUMNAME"    	VARCHAR2(255) NULL,
	"DATASOURCENAME"                	VARCHAR2(255) NULL,
	"COORDINATEDATASOURCENAME"      	VARCHAR2(255) NULL,
	"SUBENTITYIDENTIFIER"           	VARCHAR2(255) NULL,
	"SUBENTITYTYPENAME"             	VARCHAR2(255) NULL 
	)
/
CREATE TABLE "FRS_HORIZCOLLMETHODLOOKUP" ( 
	"DEC_CODE"       	VARCHAR2(20) NOT NULL,
	"DEC_DESCRIPTION"	VARCHAR2(80) NOT NULL,
	"EPA_DESCRIPTION"	VARCHAR2(60) NULL,
	"EPA_CODE"       	VARCHAR2(3) NULL 
	)
/
CREATE TABLE "FRS_INDIVIDUAL" ( 
	"STATEFACILITYIDENTIFIER"    	VARCHAR2(255) NOT NULL,
	"INDIVIDUALFULLNAME"         	VARCHAR2(255) NOT NULL,
	"AFFILIATIONTYPETEXT"        	VARCHAR2(255) NOT NULL,
	"AFFILIATIONSTARTDATE"       	VARCHAR2(10) NULL,
	"AFFILIATIONENDDATE"         	VARCHAR2(10) NULL,
	"EMAILADDRESSTEXT"           	VARCHAR2(255) NULL,
	"TELEPHONENUMBER"            	VARCHAR2(255) NULL,
	"PHONEEXTENSION"             	VARCHAR2(255) NULL,
	"FAXNUMBER"                  	VARCHAR2(255) NULL,
	"ALTERNATETELEPHONENUMBER"   	VARCHAR2(255) NULL,
	"INDIVIDUALTITLETEXT"        	VARCHAR2(255) NULL,
	"MAILINGADDRESSTEXT"         	VARCHAR2(255) NULL,
	"SUPPLEMENTALADDRESSTEXT"    	VARCHAR2(255) NULL,
	"MAILINGADDRESSCITYNAME"     	VARCHAR2(255) NULL,
	"MAILINGADDRESSSTATEUSPSCODE"	VARCHAR2(2) NULL,
	"MAILINGADDRESSSTATENAME"    	VARCHAR2(255) NULL,
	"MAILINGADDRESSCOUNTRYNAME"  	VARCHAR2(255) NULL,
	"MAILINGADDRESSZIPCODE"      	VARCHAR2(255) NULL 
	)
/
CREATE TABLE "FRS_NAICSCODE" ( 
	"STATEFACILITYIDENTIFIER"	VARCHAR2(255) NOT NULL,
	"NAICSCODE"              	VARCHAR2(6) NOT NULL,
	"NAICSPRIMARYINDICATOR"  	VARCHAR2(255) NULL,
	PRIMARY KEY("STATEFACILITYIDENTIFIER","NAICSCODE")
	NOT DEFERRABLE
	 VALIDATE
)
/
CREATE TABLE "FRS_ORGANIZATION" ( 
	"STATEFACILITYIDENTIFIER"    	VARCHAR2(255) NOT NULL,
	"ORGANIZATIONFORMALNAME"     	VARCHAR2(255) NOT NULL,
	"AFFILIATIONTYPETEXT"        	VARCHAR2(255) NOT NULL,
	"AFFILIATIONSTARTDATE"       	VARCHAR2(10) NULL,
	"AFFILIATIONENDDATE"         	VARCHAR2(10) NULL,
	"EMAILADDRESSTEXT"           	VARCHAR2(255) NULL,
	"TELEPHONENUMBER"            	VARCHAR2(255) NULL,
	"PHONEEXTENSION"             	VARCHAR2(255) NULL,
	"FAXNUMBER"                  	VARCHAR2(255) NULL,
	"ALTERNATETELEPHONENUMBER"   	VARCHAR2(255) NULL,
	"ORGANIZATIONDUNSNUMBER"     	VARCHAR2(9) NULL,
	"ORGANIZATIONTYPETEXT"       	VARCHAR2(255) NULL,
	"EMPLOYERIDENTIFIER"         	VARCHAR2(255) NULL,
	"STATEBUSINESSIDENTIFIER"    	VARCHAR2(255) NULL,
	"ULTIMATEPARENTNAME"         	VARCHAR2(255) NULL,
	"ULTIMATEPARENTDUNSNUMBER"   	VARCHAR2(9) NULL,
	"MAILINGADDRESSTEXT"         	VARCHAR2(255) NULL,
	"SUPPLEMENTALADDRESSTEXT"    	VARCHAR2(255) NULL,
	"MAILINGADDRESSCITYNAME"     	VARCHAR2(255) NULL,
	"MAILINGADDRESSSTATEUSPSCODE"	VARCHAR2(2) NULL,
	"MAILINGADDRESSSTATENAME"    	VARCHAR2(255) NULL,
	"MAILINGADDRESSCOUNTRYNAME"  	VARCHAR2(255) NULL,
	"MAILINGADDRESSZIPCODE"      	VARCHAR2(255) NULL 
	)
/
CREATE TABLE "FRS_SICCODE" ( 
	"STATEFACILITYIDENTIFIER"	VARCHAR2(255) NOT NULL,
	"SICCODE"                	VARCHAR2(4) NOT NULL,
	"SICPRIMARYINDICATOR"    	VARCHAR2(255) NULL,
	PRIMARY KEY("STATEFACILITYIDENTIFIER","SICCODE")
	NOT DEFERRABLE
	 VALIDATE
)
/
