#!/bin/bash
# inserts the hard-wired license file at the top
# of every file ending in ".java" in the directory
# passed as an argument.

if [ -z $1 ]; then
    echo "usage: insert_license_into_java <directory-path>"
else

# set Bash's Internal File Separator to newline
IFS='
'
# find the files, put the qualified  names into an 
# array, back up each file, then overwrite the 
# original with the license + the original content.

filenames="$( find $1 -name *.java )"
counter=0
for filename in $filenames
do
    (( counter++ ))
    echo "Inserting license at top of file $counter"
    cp $filename $filename.bak
    cat java_node_license.txt $filename.bak > $filename
    rm $filename.bak
done
echo "$counter files processed"
fi
