/* SQL Server */
/* SQL Server */
/* SQL Server */

/* This script creates the staging tables for the Beach Notification v2.2 data flow for OpenNode2 */

/*
      07.26.2010 - KJames - Added NOTIF_SUBMISSIONHISTORY to schema.
      08.13.2010 - KJames - Added NOTIF_BEACHACTIVITYMONSTATION to the script and related
                            objects to the script.   
      08.13.2010 - KJames - Removed column MONITORINGSTATIONIDENTIFIER from the
                            NOTIF_BEACHACTIVITY table.  
-- KJames 09.01.2010 - Removed relationship between NOTIF_BEACH and NOTIF_BEACHPROCEDURE.  
-- KJames 09.01.2010 - Added new table NOTIF_PROCEDURE
-- KJames 09.01.2010 - Removed PROCEDUREIDENTIFIER, PROCEDURETYPECODE, and PROCEDUREDESCRIPTION
--                     from NOTIF_BEACHPROCEDURE, these columns were moved to the newly
--                     created NOTIF_PROCEDURE table.    
-- KJames 11/05/2010 - Modified primary keys from NUMBER to GUIDS.   
-- Brensmith 4/10/2012 - Modified to accomodate schema v2.2                
*/

DROP TABLE dbo.NOTIF_YEARCOMPLETION
GO

DROP TABLE dbo.NOTIF_SUBMISSIONHISTORY
GO

DROP TABLE dbo.NOTIF_PERSONTELEPHONE
GO

DROP TABLE dbo.NOTIF_PERSONMAILINGADDRESS
GO

DROP TABLE dbo.NOTIF_PERSONELECTRONICADDRESS
GO

DROP TABLE dbo.NOTIF_PERSONBEACHROLE
GO

DROP TABLE dbo.NOTIF_PERSON
GO

DROP TABLE dbo.NOTIF_ORGELECTRONICADDR
GO

DROP TABLE dbo.NOTIF_ORGANIZATIONTELEPHONE
GO

DROP TABLE dbo.NOTIF_ORGANIZATIONMAILINGADDR
GO

DROP TABLE dbo.NOTIF_ORGANIZATIONBEACHROLE
GO

DROP TABLE dbo.NOTIF_STATECONTACT --added for Schema v2.2
GO

DROP TABLE dbo.NOTIF_ORGANIZATION
GO

DROP TABLE dbo.NOTIF_BEACHPROCEDURE
GO

DROP TABLE dbo.NOTIF_PROCEDURE
GO

DROP TABLE dbo.NOTIF_BEACHPOLLUTION
GO

DROP TABLE dbo.NOTIF_BEACHACTIVITYMONSTATION
GO

DROP TABLE dbo.NOTIF_ACTIVITYSOURCE
GO

DROP TABLE dbo.NOTIF_ACTIVITYREASON
GO

DROP TABLE dbo.NOTIF_ACTIVITYINDICATOR
GO

DROP TABLE dbo.NOTIF_BEACHACTIVITY
GO

DROP TABLE dbo.NOTIF_BEACHCRITERION --added for Schema v2.2
GO

DROP TABLE dbo.NOTIF_BEACH
GO

CREATE TABLE NOTIF_ACTIVITYINDICATOR ( 
	ID                  	VARCHAR(40) NOT NULL,
	ACTIVITY_ID         	VARCHAR(40) NOT NULL,
	INDICATORTYPE       	VARCHAR(60) NOT NULL,
	INDICATORDESCRIPTION	VARCHAR(255) NULL 
	)

CREATE TABLE NOTIF_ACTIVITYREASON ( 
	ID               	VARCHAR(40) NOT NULL,
	ACTIVITY_ID      	VARCHAR(40) NOT NULL,
	REASONTYPE       	VARCHAR(60) NOT NULL,
	REASONDESCRIPTION	VARCHAR(255) NULL 
	)

CREATE TABLE NOTIF_ACTIVITYSOURCE ( 
	ID               	VARCHAR(40) NOT NULL,
	ACTIVITY_ID      	VARCHAR(40) NOT NULL,
	SOURCETYPE       	VARCHAR(60) NOT NULL,
	SOURCEDESCRIPTION	VARCHAR(255) NULL 
	)

CREATE TABLE NOTIF_BEACH ( 
	ID                            	VARCHAR(40) NOT NULL,
	BEACHIDENTIFIER               	VARCHAR(8) NOT NULL,
	BEACHNAME                     	VARCHAR(60) NULL,
	BEACHDESCRIPTION              	VARCHAR(255) NULL,
	BEACHCOMMENT                  	VARCHAR(255) NULL,
	BEACHSTATECODE                	CHAR(2) NULL,
	BEACHFIPSCOUNTYCODE           	VARCHAR(5) NULL,
	BEACHACCESSTYPE               	VARCHAR(12) NULL,
	BEACHACCESSCOMMENT            	VARCHAR(255) NULL,
	EFFECTIVEYEAR                 	VARCHAR(4) NULL,
	EXTENTLENGTHMEASURE           	DECIMAL(16,6) NULL,
	EXTENTUNITOFMEASURE           	VARCHAR(12) NULL,
	SWIMSEASONSTARTDATE           	VARCHAR(25) NULL,
	SWIMSEASONENDDATE             	VARCHAR(25) NULL,
	SWIMSEASONLENGTH              	DECIMAL(16,6) NULL,
	SWIMSEASONUNITOFMEASURE       	VARCHAR(12) NULL,
	SWIMSEASONFREQUENCYMEASURE    	DECIMAL(16,6) NULL,
	OFFSEASONFREQUENCYMEASURE     	DECIMAL(16,6) NULL,
	MONITORINGFREQUNITOFMEASURE   	VARCHAR(255) NULL,
	MONITOREDIRREGULARLY          	VARCHAR(5) NULL,
	MONITOREDIRREGULARLYCOMMENT   	VARCHAR(255) NULL,
	BEACHTIERRANKING              	VARCHAR(1) NULL,
	BEACHACTBEACHINDICATOR        	VARCHAR(5) NULL,
	NOPOLLUTIONSOURCES            	VARCHAR(5) NULL,
	POLLUTIONSOURCESUNINVESTIGATED	VARCHAR(5) NULL,
	WATERBODYNAMECODE             	VARCHAR(25) NULL,
	WATERBODYTYPECODE             	VARCHAR(25) NULL,
	STARTLATMEASURE               	VARCHAR(25) NULL,
	STARTLONGMEASURE              	VARCHAR(25) NULL,
	ENDLATMEASURE                 	VARCHAR(25) NULL,
	ENDLONGMEASURE                	VARCHAR(25) NULL,
	SOURCEMAPSCALE                	VARCHAR(25) NULL,
	HORIZCOLLMETHOD               	VARCHAR(25) NULL,
	HORIZCOLLDATUM                	VARCHAR(25) NULL,
	BEACHDORMANTINDICATOR			VARCHAR(5) NULL,
	BEACHWEBSITE					VARCHAR(255) NULL,
	REPORTINGFREQUENCYMEASURE		DECIMAL(16,6) NULL,
	REPORTINGFREQUNITOFMEASURE		VARCHAR(9) NULL
	)

CREATE TABLE NOTIF_BEACHCRITERION (
    [ID] VARCHAR(40) NOT NULL,
    BEACH_ID VARCHAR(40) NOT NULL,
    INDICATORNAME VARCHAR(11) NOT NULL,
    WATERTYPENAME VARCHAR(6) NOT NULL,
    CRITERIONCOMMENT VARCHAR(255) NULL,
    MEASURETYPENAME VARCHAR(4) NOT NULL,
    MEASUREVALUE DECIMAL(16,6) NOT NULL,
    MEASUREUNITCODE VARCHAR(12) NOT NULL
    )

CREATE TABLE NOTIF_STATECONTACT (
    [ID] VARCHAR(40) NOT NULL,
    ORGANIZATION_ID VARCHAR(40) NOT NULL,
    AGENCYNAME VARCHAR(60) NOT NULL,
    TELEPHONENUMBER VARCHAR(12) NOT NULL,
    ELECTRONICADDR VARCHAR(255) NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL
	)

CREATE TABLE NOTIF_BEACHACTIVITY ( 
	ID                         	VARCHAR(40) NOT NULL,
	BEACH_ID                   	VARCHAR(40) NOT NULL,
	ACTIVITYTYPECODE           	VARCHAR(12) NOT NULL,
	ACTIVITYNAME               	VARCHAR(60) NOT NULL,
	ACTUALSTARTDATE            	VARCHAR(25) NOT NULL,
	ACTUALSTOPDATE             	VARCHAR(25) NOT NULL,
	ACTIVITYDESCRIPTION        	VARCHAR(255) NULL,
	ACTIVITYCOMMENT            	VARCHAR(255) NULL,
	EXTENTSTARTMEASURE         	DECIMAL(16,6) NULL,
	EXTENTLENGTHMEASURE        	DECIMAL(16,6) NULL,
	EXTENTUNITOFMEASURE        	VARCHAR(255) NULL,
	SENTTOEPA                  	CHAR(1) NULL 
	)
	
CREATE TABLE NOTIF_BEACHACTIVITYMONSTATION ( 
 ID                          VARCHAR(40) NOT NULL, 
	ACTIVITY_ID                 VARCHAR(40) NOT NULL , 
	MONITORINGSTATIONIDENTIFIER VARCHAR(65) NOT NULL
 )
	
CREATE TABLE NOTIF_BEACHPOLLUTION ( 
	ID                        	VARCHAR(40) NOT NULL,
	BEACH_ID                  	VARCHAR(40) NOT NULL,
	POLLUTIONSOURCECODE       	VARCHAR(12) NOT NULL,
	POLLUTIONSOURCEDESCRIPTION	VARCHAR(255) NULL 
	)

CREATE TABLE NOTIF_BEACHPROCEDURE ( 
	ID                  	VARCHAR(40) NOT NULL,
	BEACH_ID            	VARCHAR(40) NOT NULL,
	PROCEDURE_ID 	       VARCHAR(40)  NOT NULL
	)
 
 CREATE TABLE NOTIF_PROCEDURE ( 
 ID                   VARCHAR(40) NOT NULL,
 PROCEDUREIDENTIFIER  VARCHAR(12) NOT NULL,
 PROCEDURETYPECODE    VARCHAR(12) NOT NULL,
 PROCEDUREDESCRIPTION VARCHAR(255) NOT NULL 
 )

CREATE TABLE NOTIF_ORGANIZATION ( 
	ID                      	VARCHAR(40) NOT NULL,
	ORGANIZATIONIDENTIFIER  	VARCHAR(12) NOT NULL,
	ORGANIZATIONTYPECODE    	VARCHAR(12) NOT NULL,
	ORGANIZATIONNAME        	VARCHAR(60) NOT NULL,
	ORGANIZATIONDESCRIPTION 	VARCHAR(255) NULL,
	ORGANIZATIONABBREVIATION	VARCHAR(30) NULL 
	)

CREATE TABLE NOTIF_ORGANIZATIONBEACHROLE ( 
	ID               	VARCHAR(40) NOT NULL,
	BEACH_ID         	VARCHAR(40) NOT NULL,
	ORGANIZATION_ID  	VARCHAR(40) NOT NULL,
	ROLETYPECODE     	VARCHAR(12) NOT NULL,
	ROLEEFFECTIVEDATE	VARCHAR(25) NOT NULL,
	ROLESTATUS       	VARCHAR(8) NOT NULL 
	)

CREATE TABLE NOTIF_ORGANIZATIONMAILINGADDR ( 
	ID                      	VARCHAR(40) NOT NULL,
	ORGANIZATION_ID         	VARCHAR(40) NOT NULL,
	MAILINGADDRTYPECODE     	VARCHAR(12) NOT NULL,
	MAILINGADDRLINE1        	VARCHAR(100) NOT NULL,
	MAILINGADDRLINE2        	VARCHAR(100) NULL,
	MAILINGADDRLINE3        	VARCHAR(100) NULL,
	MAILINGADDRCITY         	VARCHAR(50) NOT NULL,
	STATECODE               	CHAR(2) NOT NULL,
	ZIPCODE                 	VARCHAR(12) NOT NULL,
	MAILINGADDREFFECTIVEDATE	VARCHAR(25) NOT NULL,
	MAILINGADDRSTATUS       	VARCHAR(8) NOT NULL 
	)

CREATE TABLE NOTIF_ORGANIZATIONTELEPHONE ( 
	ID                    	VARCHAR(40) NOT NULL,
	ORGANIZATION_ID       	VARCHAR(40) NOT NULL,
	TELEPHONETYPECODE     	VARCHAR(12) NOT NULL,
	TELEPHONENUMBER       	VARCHAR(12) NOT NULL,
	TELEPHONEEFFECTIVEDATE	VARCHAR(25) NOT NULL,
	TELEPHONESTATUS       	VARCHAR(8) NOT NULL 
	)

CREATE TABLE NOTIF_ORGELECTRONICADDR ( 
	ID                    	VARCHAR(40) NOT NULL,
	ORGANIZATION_ID       	VARCHAR(40) NOT NULL,
	ELECTRONICADDRTYPECODE	VARCHAR(12) NOT NULL,
	ELECTRONICADDR        	VARCHAR(255) NOT NULL,
	ELECTRONICADDREFFDATE 	VARCHAR(25) NOT NULL,
	ELECTRONICADDRSTATUS  	VARCHAR(8) NOT NULL 
	)

CREATE TABLE NOTIF_PERSON ( 
	ID              	VARCHAR(40) NOT NULL,
	ORGANIZATION_ID 	VARCHAR(40) NOT NULL,
	PERSONIDENTIFIER	VARCHAR(12) NOT NULL,
	PERSONSTATUS    	VARCHAR(8) NULL,
	FIRSTNAME       	VARCHAR(50) NULL,
	LASTNAME        	VARCHAR(50) NULL,
	MIDDLEINITIAL   	VARCHAR(2) NULL,
	SUFFIX          	VARCHAR(5) NULL,
	TITLE           	VARCHAR(60) NULL 
	)

CREATE TABLE NOTIF_PERSONBEACHROLE ( 
	ID               	VARCHAR(40) NOT NULL,
	BEACH_ID         	VARCHAR(40) NOT NULL,
	PERSON_ID        	VARCHAR(40) NOT NULL,
	ROLETYPECODE     	VARCHAR(12) NOT NULL,
	ROLEEFFECTIVEDATE	VARCHAR(25) NOT NULL,
	ROLESTATUS       	VARCHAR(8) NOT NULL 
	)

CREATE TABLE NOTIF_PERSONELECTRONICADDRESS ( 
	ID                            	VARCHAR(40) NOT NULL,
	PERSON_ID                     	VARCHAR(40) NOT NULL,
	ELECTRONICADDRESSTYPECODE     	VARCHAR(12) NOT NULL,
	ELECTRONICADDRESS             	VARCHAR(255) NOT NULL,
	ELECTRONICADDRESSEFFECTIVEDATE	VARCHAR(25) NOT NULL,
	ELECTRONICADDRESSSTATUS       	VARCHAR(8) NOT NULL 
	)

CREATE TABLE NOTIF_PERSONMAILINGADDRESS ( 
	ID                      	VARCHAR(40) NOT NULL,
	PERSON_ID               	VARCHAR(40) NOT NULL,
	MAILINGADDRTYPECODE     	VARCHAR(12) NOT NULL,
	MAILINGADDRLINE1        	VARCHAR(100) NOT NULL,
	MAILINGADDRLINE2        	VARCHAR(100) NULL,
	MAILINGADDRLINE3        	VARCHAR(100) NULL,
	MAILINGADDRCITY         	VARCHAR(50) NOT NULL,
	STATECODE               	CHAR(2) NOT NULL,
	ZIPCODE                 	VARCHAR(12) NOT NULL,
	MAILINGADDREFFECTIVEDATE	VARCHAR(25) NOT NULL,
	MAILINGADDRSTATUS       	VARCHAR(8) NOT NULL 
	)

CREATE TABLE NOTIF_PERSONTELEPHONE ( 
	ID                    	VARCHAR(40) NOT NULL,
	PERSON_ID             	VARCHAR(40) NOT NULL,
	TELEPHONETYPECODE     	VARCHAR(12) NOT NULL,
	TELEPHONENUMBER       	VARCHAR(12) NOT NULL,
	TELEPHONEEFFECTIVEDATE	VARCHAR(25) NOT NULL,
	TELEPHONESTATUS       	VARCHAR(8) NOT NULL 
	)

CREATE TABLE NOTIF_YEARCOMPLETION ( 
	ID                           	VARCHAR(40) NOT NULL,
	COMPLETIONYEAR               	INTEGER NOT NULL,
	NOTIFICATIONDATACOMPLETIONIND	VARCHAR(5) NULL,
	MONITORINGDATACOMPLETIONIND  	VARCHAR(5) NULL,
	LOCATIONDATACOMPLETIONIND    	VARCHAR(5) NULL 
	)

CREATE TABLE "NOTIF_SUBMISSIONHISTORY" ( 
 RECORDID               VARCHAR(40) NOT NULL,
 SCHEDULERUNDATE        DATE NOT NULL,
 TRANSACTIONID          VARCHAR(50) NOT NULL,
 PROCESSINGSTATUS       VARCHAR(50) NOT NULL 
 )

CREATE INDEX "NOTIF_ACTIVITYINDICATOR"
	ON "NOTIF_ACTIVITYINDICATOR"("ACTIVITY_ID");

CREATE INDEX "NOTIF_ACTIVITYREASON"
	ON "NOTIF_ACTIVITYREASON"("ACTIVITY_ID");

CREATE INDEX "NOTIF_ACTIVITYSOURCE"
	ON "NOTIF_ACTIVITYSOURCE"("ACTIVITY_ID");

CREATE INDEX "NOTIF_SENTTOEPA"
	ON "NOTIF_BEACHACTIVITY"("SENTTOEPA");

CREATE INDEX "NOTIF_BEACHACTIVITY"
	ON "NOTIF_BEACHACTIVITY"("BEACH_ID");

CREATE INDEX "NOTIF_BEACHACTMONITOR_IDX"
   ON "NOTIF_BEACHACTIVITYMONSTATION" ("ACTIVITY_ID");	

CREATE INDEX "NOTIF_BEACHPOLLUTION"
	ON "NOTIF_BEACHPOLLUTION"("BEACH_ID");

CREATE INDEX "NOTIF_BEACHPROCEDURE_IDX"
	ON "NOTIF_BEACHPROCEDURE"("BEACH_ID");
 
CREATE INDEX "NOTIF_PROCEDURE_IDX"
 ON "NOTIF_BEACHPROCEDURE"("PROCEDURE_ID");

CREATE INDEX "NOTIF_ORGANIZATIONBEACHROLE"
	ON "NOTIF_ORGANIZATIONBEACHROLE"("ORGANIZATION_ID");

CREATE INDEX "NOTIF_ORGANIZATIONMAILINGADDR"
	ON "NOTIF_ORGANIZATIONMAILINGADDR"("ORGANIZATION_ID");

CREATE INDEX "NOTIF_ORGANIZATIONTELEPHONE"
	ON "NOTIF_ORGANIZATIONTELEPHONE"("ORGANIZATION_ID");

CREATE INDEX "NOTIF_ORGELECTRONICADDR"
	ON "NOTIF_ORGELECTRONICADDR"("ORGANIZATION_ID");

CREATE INDEX "NOTIF_PERSON"
	ON "NOTIF_PERSON"("ORGANIZATION_ID");

CREATE INDEX "NOTIF_PERSONBEACHROLE"
	ON "NOTIF_PERSONBEACHROLE"("BEACH_ID");

CREATE INDEX "NOTIF_PERSONELECTRONICADDRESS"
	ON "NOTIF_PERSONELECTRONICADDRESS"("PERSON_ID");

CREATE INDEX "NOTIF_PERSONMAILINGADDRESS"
	ON "NOTIF_PERSONMAILINGADDRESS"("PERSON_ID");

CREATE INDEX "NOTIF_PERSONTELEPHONE"
	ON "NOTIF_PERSONTELEPHONE"("PERSON_ID");

ALTER TABLE NOTIF_ACTIVITYINDICATOR
	ADD CONSTRAINT PK_NOTIF_ACTIVITYINDICATOR
	PRIMARY KEY (ID)

ALTER TABLE NOTIF_ACTIVITYREASON
	ADD CONSTRAINT PK_NOTIF_ACTIVITYREASON
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_ACTIVITYSOURCE
	ADD CONSTRAINT PK_NOTIF_ACTIVITYSOURCE
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_BEACH
	ADD CONSTRAINT PK_NOTIF_BEACH
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_BEACHACTIVITY
	ADD CONSTRAINT PK_NOTIF_BEACHACTIVITY
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_BEACHPOLLUTION
	ADD CONSTRAINT PK_NOTIF_BEACHPOLLUTION
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_BEACHPROCEDURE
	ADD CONSTRAINT PK_NOTIF_BEACHPROCEDURE
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_PROCEDURE
	ADD CONSTRAINT PK_NOTIF_PROCEDURE
	PRIMARY KEY (ID)	
	
ALTER TABLE NOTIF_ORGANIZATION
	ADD CONSTRAINT PK_NOTIF_ORGANIZATION
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_ORGANIZATIONBEACHROLE
	ADD CONSTRAINT PK_NOTIF_ORGANIZATIONBEACHROLE
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_ORGANIZATIONMAILINGADDR
	ADD CONSTRAINT PK_NOTIF_ORGMAILINGADDR
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_ORGANIZATIONTELEPHONE
	ADD CONSTRAINT PK_NOTIF_ORGANIZATIONTELEPHONE
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_ORGELECTRONICADDR
	ADD CONSTRAINT PK_NOTIF_ORGELECTRONICADDR
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_PERSON
	ADD CONSTRAINT PK_NOTIF_PERSON
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_PERSONBEACHROLE
	ADD CONSTRAINT PK_NOTIF_PERSONBEACHROLE
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_PERSONELECTRONICADDRESS
	ADD CONSTRAINT PK_NOTIF_PERSONELECTRONICADDR
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_PERSONMAILINGADDRESS
	ADD CONSTRAINT PK_NOTIF_PERSONMAILINGADDRESS
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_PERSONTELEPHONE
	ADD CONSTRAINT PK_NOTIF_PERSONTELEPHONE
	PRIMARY KEY (ID)
	
ALTER TABLE NOTIF_YEARCOMPLETION
	ADD CONSTRAINT PK_NOTIF_YEARCOMPLETION
	PRIMARY KEY (ID)

ALTER TABLE NOTIF_BEACHACTIVITYMONSTATION
	ADD CONSTRAINT PK_NOTIF_BEACHACTMONITOR
	PRIMARY KEY (ID)

ALTER TABLE NOTIF_BEACHCRITERION
    ADD CONSTRAINT PK_NOT_BCH_CRI 
    PRIMARY KEY ([ID])

ALTER TABLE NOTIF_STATECONTACT
    ADD CONSTRAINT PK_NOT_STCNTCT 
    PRIMARY KEY ([ID])

ALTER TABLE NOTIF_ACTIVITYINDICATOR
	ADD CONSTRAINT FK_ACTIVITYINDICATOR_BEACHACT
	FOREIGN KEY(ACTIVITY_ID)
	REFERENCES NOTIF_BEACHACTIVITY(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_ACTIVITYREASON
	ADD CONSTRAINT FK_ACTIVITYREASON_BEACHACT
	FOREIGN KEY(ACTIVITY_ID)
	REFERENCES NOTIF_BEACHACTIVITY(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_ACTIVITYSOURCE
	ADD CONSTRAINT FK_ACTIVITYSOURCE_BEACHACT
	FOREIGN KEY(ACTIVITY_ID)
	REFERENCES NOTIF_BEACHACTIVITY(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_BEACHACTIVITY
	ADD CONSTRAINT FK_BEACHACTIVITY_BEACH
	FOREIGN KEY(BEACH_ID)
	REFERENCES NOTIF_BEACH(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_BEACHPOLLUTION
	ADD CONSTRAINT FK_BEACHPOLLUTION_BEACH
	FOREIGN KEY(BEACH_ID)
	REFERENCES NOTIF_BEACH(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_BEACHPROCEDURE
	ADD CONSTRAINT FK_BEACHPROCEDURE_PROCEDURE
	FOREIGN KEY(PROCEDURE_ID)
	REFERENCES NOTIF_PROCEDURE(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_ORGANIZATIONBEACHROLE
	ADD CONSTRAINT FK_ORGANIZATIONBEACHROLE_ORG
	FOREIGN KEY(ORGANIZATION_ID)
	REFERENCES NOTIF_ORGANIZATION(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_ORGANIZATIONBEACHROLE
	ADD CONSTRAINT FK_ORGANIZATIONBEACHROLE_BEACH
	FOREIGN KEY(BEACH_ID)
	REFERENCES NOTIF_BEACH(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_ORGANIZATIONMAILINGADDR
	ADD CONSTRAINT FK_ORGANIZATION_ORGMAILINGADDR
	FOREIGN KEY(ORGANIZATION_ID)
	REFERENCES NOTIF_ORGANIZATION(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_ORGANIZATIONTELEPHONE
	ADD CONSTRAINT FK_ORGANIZATIONTELEPHONE_ORG
	FOREIGN KEY(ORGANIZATION_ID)
	REFERENCES NOTIF_ORGANIZATION(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_ORGELECTRONICADDR
	ADD CONSTRAINT FK_ORGELECTRONICADDR_ORG
	FOREIGN KEY(ORGANIZATION_ID)
	REFERENCES NOTIF_ORGANIZATION(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_PERSON
	ADD CONSTRAINT FK_PERSON_ORGANIZATION
	FOREIGN KEY(ORGANIZATION_ID)
	REFERENCES NOTIF_ORGANIZATION(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_PERSONBEACHROLE
	ADD CONSTRAINT FK_PERSONBEACHROLE_PERSON
	FOREIGN KEY(PERSON_ID)
	REFERENCES NOTIF_PERSON(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_PERSONBEACHROLE
	ADD CONSTRAINT FK_PERSONBEACHROLE_BEACH
	FOREIGN KEY(BEACH_ID)
	REFERENCES NOTIF_BEACH(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_PERSONELECTRONICADDRESS
	ADD CONSTRAINT FK_PERSONELECTRONICADD_PERSON
	FOREIGN KEY(PERSON_ID)
	REFERENCES NOTIF_PERSON(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_PERSONMAILINGADDRESS
	ADD CONSTRAINT FK_PERSONMAILINGADDRESS_PERSON
	FOREIGN KEY(PERSON_ID)
	REFERENCES NOTIF_PERSON(ID)
	ON DELETE CASCADE

ALTER TABLE NOTIF_PERSONTELEPHONE
	ADD CONSTRAINT FK_PERSONTELEPHONE_PERSON
	FOREIGN KEY(PERSON_ID)
	REFERENCES NOTIF_PERSON(ID)
	ON DELETE CASCADE
	
ALTER TABLE "NOTIF_BEACHACTIVITYMONSTATION"
	ADD CONSTRAINT FK_NOT_ACT_MON
	FOREIGN KEY(ACTIVITY_ID)
	REFERENCES NOTIF_BEACHACTIVITY(ID)
	ON DELETE CASCADE
	
ALTER TABLE NOTIF_BEACHCRITERION
	ADD CONSTRAINT FK_NOT_BCH_CRI
    FOREIGN KEY(BEACH_ID)
    REFERENCES NOTIF_BEACH(ID)
	ON DELETE CASCADE
	ON UPDATE NO ACTION

ALTER TABLE NOTIF_STATECONTACT
	ADD CONSTRAINT FK_NOT_STCNTCT
    FOREIGN KEY(ORGANIZATION_ID)
    REFERENCES NOTIF_ORGANIZATION(ID)
    ON DELETE CASCADE
    ON UPDATE NO ACTION