CREATE TABLE WQX_ALTMONLOC

(

  RECORDID         VARCHAR2(50 BYTE)            NOT NULL,

  PARENTID         VARCHAR2(50 BYTE)            NOT NULL,

  MONLOCID         VARCHAR2(35 BYTE)            NOT NULL,

  MONLOCIDCONTEXT  VARCHAR2(120 BYTE)           NOT NULL

)

/





CREATE TABLE WQX_MONLOCATTACHEDBINARYOBJECT

(

  RECORDID                  VARCHAR2(50 BYTE)   NOT NULL,

  PARENTID                  VARCHAR2(50 BYTE)   NOT NULL,

  BINARYOBJECTFILE          VARCHAR2(255 BYTE)  NOT NULL,

  BINARYOBJECTFILETYPECODE  VARCHAR2(6 BYTE)    NOT NULL

)

/





CREATE TABLE WQX_PROJECT

(

  RECORDID                VARCHAR2(50 BYTE)     NOT NULL,

  PARENTID                VARCHAR2(50 BYTE)     NOT NULL,

  PROJECTID               VARCHAR2(35 BYTE)     NOT NULL,

  PROJECTNAME             VARCHAR2(120 BYTE)    NOT NULL,

  PROJECTDESC             VARCHAR2(1999 BYTE),

  SAMPLINGDESIGNTYPECODE  VARCHAR2(20 BYTE),

  QAPPAPPROVEDIND         CHAR(1 BYTE),

  QAPPAPPROVALAGENCYNAME  VARCHAR2(50 BYTE),

  WQXUPDATEDATE           DATE                  NOT NULL

)

/





CREATE TABLE WQX_ACTIVITYGROUP

(

  RECORDID               VARCHAR2(50 BYTE)      NOT NULL,

  PARENTID               VARCHAR2(50 BYTE)      NOT NULL,

  ACTIVITYGROUPID        VARCHAR2(35 BYTE)      NOT NULL,

  ACTIVITYGROUPNAME      VARCHAR2(50 BYTE)      NOT NULL,

  ACTIVITYGROUPTYPECODE  VARCHAR2(50 BYTE)      NOT NULL,

  ACTIVITYID             VARCHAR2(35 BYTE)      NOT NULL,

  WQXUPDATEDATE          DATE                   NOT NULL

)

/





CREATE TABLE WQX_ELECTRONICADDRESS

(

  RECORDID               VARCHAR2(50 BYTE)      NOT NULL,

  PARENTID               VARCHAR2(50 BYTE)      NOT NULL,

  ELECTRONICADDRESS      VARCHAR2(120 BYTE)     NOT NULL,

  ELECTRONICADDRESSTYPE  VARCHAR2(8 BYTE)

)

/





CREATE TABLE WQX_BIOLOGICALHABITATINDEX

(

  RECORDID             VARCHAR2(50 BYTE)        NOT NULL,

  PARENTID             VARCHAR2(50 BYTE)        NOT NULL,

  INDEXID              VARCHAR2(35 BYTE)        NOT NULL,

  INDEXTYPEID          VARCHAR2(35 BYTE)        NOT NULL,

  INDEXTYPEIDCONTEXT   VARCHAR2(50 BYTE)        NOT NULL,

  INDEXTYPENAME        VARCHAR2(50 BYTE)        NOT NULL,

  RESOURCETITLE        VARCHAR2(120 BYTE),

  RESOURCECREATOR      VARCHAR2(120 BYTE),

  RESOURCESUBJECT      VARCHAR2(500 BYTE),

  RESOURCEPUBLISHER    VARCHAR2(60 BYTE),

  RESOURCEDATE         VARCHAR2(10 BYTE),

  RESOURCEID           VARCHAR2(255 BYTE),

  INDEXTYPESCALE       VARCHAR2(50 BYTE),

  INDEXSCORE           VARCHAR2(10 BYTE)        NOT NULL,

  INDEXQUALIFIERCODE   VARCHAR2(5 BYTE),

  INDEXCOMMENT         VARCHAR2(4000 BYTE),

  INDEXCALCULATEDDATE  VARCHAR2(10 BYTE),

  MONLOCID             VARCHAR2(35 BYTE)        NOT NULL,

  WQXUPDATEDATE        DATE                     NOT NULL

)

/





CREATE TABLE WQX_TELEPHONIC

(

  RECORDID             VARCHAR2(50 BYTE)        NOT NULL,

  PARENTID             VARCHAR2(50 BYTE)        NOT NULL,

  TELEPHONENUMBER      VARCHAR2(15 BYTE)        NOT NULL,

  TELEPHONENUMBERTYPE  VARCHAR2(6 BYTE),

  TELEPHONEEXT         VARCHAR2(6 BYTE)

)

/





CREATE TABLE WQX_SUBMISSIONHISTORY

(

  RECORDID             VARCHAR2(50 BYTE)        NOT NULL,

  PARENTID             VARCHAR2(50 BYTE)        NOT NULL,

  SCHEDULERUNDATE      DATE                     NOT NULL,

  WQXUPDATEDATE        DATE                     NOT NULL,

  SUBMISSIONTYPE       VARCHAR2(13 BYTE)        NOT NULL,

  LOCALTRANSACTIONID   VARCHAR2(50 BYTE)        NOT NULL,

  CDXPROCESSINGSTATUS  VARCHAR2(50 BYTE)        NOT NULL

)

/





CREATE TABLE WQX_DELETES

(

  RECORDID       VARCHAR2(50 BYTE)              NOT NULL,

  PARENTID       VARCHAR2(50 BYTE)              NOT NULL,

  COMPONENT      VARCHAR2(50 BYTE)              NOT NULL,

  IDENTIFIER     VARCHAR2(50 BYTE)              NOT NULL,

  WQXUPDATEDATE  DATE                           NOT NULL

)

/





CREATE TABLE WQX_ORGADDRESS

(

  RECORDID             VARCHAR2(50 BYTE)        NOT NULL,

  PARENTID             VARCHAR2(50 BYTE)        NOT NULL,

  ADDRESSTYPE          VARCHAR2(8 BYTE),

  ADDRESS              VARCHAR2(50 BYTE)        NOT NULL,

  SUPPLEMENTALADDRESS  VARCHAR2(120 BYTE),

  LOCALITY             VARCHAR2(30 BYTE),

  STATECODE            VARCHAR2(2 BYTE),

  POSTALCODE           VARCHAR2(10 BYTE),

  COUNTRYCODE          VARCHAR2(2 BYTE),

  COUNTYCODE           VARCHAR2(3 BYTE)

)

/





CREATE TABLE WQX_MONITORINGLOCATION

(

  RECORDID                  VARCHAR2(50 BYTE)   NOT NULL,

  PARENTID                  VARCHAR2(50 BYTE)   NOT NULL,

  MONITORINGLOCATIONID      VARCHAR2(35 BYTE)   NOT NULL,

  MONLOCNAME                VARCHAR2(255 BYTE)  NOT NULL,

  MONLOCTYPE                VARCHAR2(45 BYTE)   NOT NULL,

  MONLOCDESC                VARCHAR2(1999 BYTE),

  HUCEIGHTDIGITCODE         VARCHAR2(8 BYTE),

  HUCTWELVEDIGITCODE        VARCHAR2(12 BYTE),

  TRIBALLANDIND             CHAR(1 BYTE)        NOT NULL,

  TRIBALLANDNAME            VARCHAR2(200 BYTE),

  LATITUDEMEASURE           VARCHAR2(30 BYTE)   NOT NULL,

  LONGITUDEMEASURE          VARCHAR2(30 BYTE)   NOT NULL,

  SOURCEMAPSCALE            INTEGER,

  HORIZACCURACYMEASURE      VARCHAR2(12 BYTE),

  HORIZACCURACYMEASUREUNIT  VARCHAR2(12 BYTE),

  HORIZCOLLMETHOD           VARCHAR2(150 BYTE)  NOT NULL,

  HORIZCOORDREFSYSDATUM     VARCHAR2(6 BYTE)    NOT NULL,

  VERTICALMEASURE           VARCHAR2(12 BYTE),

  VERTICALMEASUREUNIT       VARCHAR2(12 BYTE),

  VERTICALCOLLMETHOD        VARCHAR2(50 BYTE),

  VERTICALCOORDREFSYSDATUM  VARCHAR2(10 BYTE),

  COUNTRYCODE               VARCHAR2(2 BYTE),

  STATECODE                 VARCHAR2(2 BYTE),

  COUNTYCODE                VARCHAR2(3 BYTE),

  WELLTYPE                  VARCHAR2(255 BYTE),

  AQUIFERNAME               VARCHAR2(120 BYTE),

  FORMATIONTYPE             VARCHAR2(50 BYTE),

  WELLHOLEDEPTHMEASURE      VARCHAR2(12 BYTE),

  WELLHOLEDEPTHMEASUREUNIT  VARCHAR2(12 BYTE),

  WQXUPDATEDATE             DATE                NOT NULL

)

/





CREATE TABLE WQX_ACTIVITY

(

  RECORDID                        VARCHAR2(50 BYTE) NOT NULL,

  PARENTID                        VARCHAR2(50 BYTE) NOT NULL,

  ACTIVITYID                      VARCHAR2(35 BYTE) NOT NULL,

  ACTIVITYTYPECODE                VARCHAR2(70 BYTE) NOT NULL,

  ACTIVITYMEDIA                   VARCHAR2(20 BYTE) NOT NULL,

  ACTIVITYMEDIASUBDIVISION        VARCHAR2(45 BYTE),

  ACTIVITYSTARTDATE               DATE          NOT NULL,

  STARTTIME                       VARCHAR2(20 BYTE),

  STARTTIMEZONE                   VARCHAR2(4 BYTE),

  ACTIVITYENDDATE                 DATE,

  ENDTIME                         VARCHAR2(20 BYTE),

  ENDTIMEZONE                     VARCHAR2(4 BYTE),

  RELATIVEDEPTH                   VARCHAR2(15 BYTE),

  DEPTHHEIGHTMEASURE              VARCHAR2(12 BYTE),

  DEPTHHEIGHTMEASUREUNIT          VARCHAR2(12 BYTE),

  TOPDEPTHHEIGHTMEASURE           VARCHAR2(12 BYTE),

  TOPDEPTHHEIGHTMEASUREUNIT       VARCHAR2(12 BYTE),

  BOTTOMDEPTHHEIGHTMEASURE        VARCHAR2(12 BYTE),

  BOTTOMDEPTHHEIGHTMEASUREUNIT    VARCHAR2(12 BYTE),

  DEPTHALTITUDEREFPOINT           VARCHAR2(125 BYTE),

  MONLOCID                        VARCHAR2(35 BYTE),

  ACTIVITYCOMMENT                 VARCHAR2(4000 BYTE),

  LATITUDEMEASURE                 VARCHAR2(30 BYTE),

  LONGITUDEMEASURE                VARCHAR2(30 BYTE),

  SOURCEMAPSCALE                  VARCHAR2(12 BYTE),

  HORIZACCURACYMEASURE            VARCHAR2(12 BYTE),

  HORIZACCURACYMEASUREUNIT        VARCHAR2(12 BYTE),

  HORIZCOLLMETHOD                 VARCHAR2(150 BYTE),

  HORIZCOORDREFSYSDATUM           VARCHAR2(6 BYTE),

  BIOACTIVITYASSEMBLAGESAMPD      VARCHAR2(50 BYTE),

  BIOHABCOLLDURATIONMEASURE       VARCHAR2(12 BYTE),

  BIOHABCOLLDURATIONMEASUREUNIT   VARCHAR2(12 BYTE),

  BIOHABSAMPCOMP                  VARCHAR2(15 BYTE),

  BIOHABSAMPCOMPPLACEINSERIES     VARCHAR2(12 BYTE),

  BIOHABREACHLENGTHMEASURE        VARCHAR2(12 BYTE),

  BIOHABREACHLENGTHMEASUREUNIT    VARCHAR2(12 BYTE),

  BIOHABREACHWIDTHMEASURE         VARCHAR2(12 BYTE),

  BIOHABREACHWIDTHMEASUREUNIT     VARCHAR2(12 BYTE),

  BIOHABPASSCOUNT                 VARCHAR2(12 BYTE),

  BIOHABNETTYPE                   VARCHAR2(30 BYTE),

  BIOHABNETSURFACEAREAMEASURE     VARCHAR2(12 BYTE),

  BIOHABNETSURFACEMEASUREUNIT     VARCHAR2(12 BYTE),

  BIOHABNETMESHSIZEMEASURE        VARCHAR2(12 BYTE),

  BIOHABNETMESHMEASUREUNIT        VARCHAR2(12 BYTE),

  BIOHABNETBOATSPEEDMEASURE       VARCHAR2(12 BYTE),

  BIOHABNETBOATSPEEDMEASUREUNIT   VARCHAR2(12 BYTE),

  BIOHABNETCURRSPEEDMEASURE       VARCHAR2(12 BYTE),

  BIOHABNETCURRSPEEDMEASUREUNIT   VARCHAR2(12 BYTE),

  BIOACTIVITYTOXICITYTESTTYPE     VARCHAR2(7 BYTE),

  SAMPCOLLMETHODID                VARCHAR2(20 BYTE),

  SAMPCOLLMETHODIDCONTEXT         VARCHAR2(120 BYTE),

  SAMPCOLLMETHOD                  VARCHAR2(120 BYTE),

  SAMPCOLLMETHODQUALIFIER         VARCHAR2(25 BYTE),

  SAMPCOLLMETHODDESC              VARCHAR2(500 BYTE),

  SAMPCOLLEQUIPMENT               VARCHAR2(40 BYTE),

  SAMPCOLLEQUIPMENTCOMMENT        VARCHAR2(4000 BYTE),

  SAMPPREPID                      VARCHAR2(20 BYTE),

  SAMPPREPIDCONTEXT               VARCHAR2(120 BYTE),

  SAMPPREP                        VARCHAR2(120 BYTE),

  SAMPPREPQUALIFIERTYPE           VARCHAR2(25 BYTE),

  SAMPPREPDESC                    VARCHAR2(500 BYTE),

  SAMPPREPCONTTYPE                VARCHAR2(35 BYTE),

  SAMPPREPCONTCOLOR               VARCHAR2(15 BYTE),

  SAMPPREPCONTCHEMPRESERVUSED     VARCHAR2(250 BYTE),

  SAMPPREPCONTTHERMALPRESERVUSED  VARCHAR2(25 BYTE),

  SAMPPREPCONTSAMPTRANSSTORDESC   VARCHAR2(250 BYTE),

  RESULTCOUNT                     VARCHAR2(255 BYTE),

  WQXUPDATEDATE                   DATE          NOT NULL,

  TMPACTIVITYTYPE                 VARCHAR2(50 BYTE),

  TMPPROJECTID                    VARCHAR2(50 BYTE)

)

/





CREATE TABLE WQX_LABSAMPLEPREP

(

  RECORDID                 VARCHAR2(50 BYTE)    NOT NULL,

  PARENTID                 VARCHAR2(50 BYTE)    NOT NULL,

  METHODID                 VARCHAR2(20 BYTE)    NOT NULL,

  METHODIDCONTEXT          VARCHAR2(120 BYTE)   NOT NULL,

  METHODNAME               VARCHAR2(120 BYTE)   NOT NULL,

  METHODQUALIFIERTYPE      VARCHAR2(25 BYTE),

  METHODDESC               VARCHAR2(500 BYTE),

  PREPSTARTDATE            DATE,

  PREPSTARTTIME            VARCHAR2(20 BYTE),

  PREPSTARTTIMEZONECODE    VARCHAR2(4 BYTE),

  PREPENDDATE              DATE,

  PREPENDTIME              VARCHAR2(20 BYTE),

  PREPENDTIMEZONECODE      VARCHAR2(4 BYTE),

  SUBSTANCEDILUTIONFACTOR  VARCHAR2(10 BYTE)

)

/





CREATE TABLE WQX_RESULTDETECTQUANTLIMIT

(

  RECORDID                      VARCHAR2(50 BYTE) NOT NULL,

  PARENTID                      VARCHAR2(50 BYTE) NOT NULL,

  DETECTQUANTLIMITTYPE          VARCHAR2(35 BYTE) NOT NULL,

  DETECTQUANTLIMITMEASURE       VARCHAR2(12 BYTE),

  DETECTQUANTLIMITMEASUNITCODE  VARCHAR2(12 BYTE)

)

/





CREATE TABLE WQX_RESULTATTACHEDBINARYOBJECT

(

  RECORDID                  VARCHAR2(50 BYTE)   NOT NULL,

  PARENTID                  VARCHAR2(50 BYTE)   NOT NULL,

  BINARYOBJECTFILE          VARCHAR2(255 BYTE)  NOT NULL,

  BINARYOBJECTFILETYPECODE  VARCHAR2(6 BYTE)    NOT NULL

)

/





CREATE TABLE WQX_ACTIVITYMETRIC

(

  RECORDID                   VARCHAR2(50 BYTE)  NOT NULL,

  PARENTID                   VARCHAR2(50 BYTE)  NOT NULL,

  METRICTYPEID               VARCHAR2(35 BYTE)  NOT NULL,

  METRICTYPEIDCONTEXT        VARCHAR2(50 BYTE)  NOT NULL,

  METRICTYPENAME             VARCHAR2(50 BYTE),

  CITATIONRESOURCETITLE      VARCHAR2(120 BYTE),

  CITATIONRESOURCECREATOR    VARCHAR2(120 BYTE),

  CITATIONRESOURCESUBJECT    VARCHAR2(500 BYTE),

  CITATIONRESOURCEPUBLISHER  VARCHAR2(60 BYTE),

  CITATIONRESOURCEDATE       DATE,

  CITATIONRESOURCEID         VARCHAR2(255 BYTE),

  METRICTYPESCALE            VARCHAR2(50 BYTE),

  METRICTYPEFORMULADESC      VARCHAR2(50 BYTE),

  METRICVALUEMEASURE         VARCHAR2(12 BYTE),

  METRICVALUEMEASUREUNIT     VARCHAR2(12 BYTE),

  METRICSCORE                VARCHAR2(10 BYTE),

  METRICCOMMENT              VARCHAR2(4000 BYTE),

  METRICINDEXID              VARCHAR2(35 BYTE)

)

/





CREATE TABLE WQX_ACTIVITYCONDUCTINGORG

(

  RECORDID               VARCHAR2(50 BYTE)      NOT NULL,

  PARENTID               VARCHAR2(50 BYTE)      NOT NULL,

  ACTIVITYID             VARCHAR2(35 BYTE)      NOT NULL,

  ACTIVITYCONDUCTINGORG  VARCHAR2(120 BYTE)     NOT NULL

)

/





CREATE TABLE WQX_ACTATTACHEDBINARYOBJECT

(

  RECORDID                  VARCHAR2(50 BYTE)   NOT NULL,

  PARENTID                  VARCHAR2(50 BYTE)   NOT NULL,

  BINARYOBJECTFILE          VARCHAR2(255 BYTE)  NOT NULL,

  BINARYOBJECTFILETYPECODE  VARCHAR2(6 BYTE)    NOT NULL

)

/





CREATE TABLE WQX_RESULT

(

  RECORDID                        VARCHAR2(50 BYTE) NOT NULL,

  PARENTID                        VARCHAR2(50 BYTE) NOT NULL,

  DATALOGGERLINENAME              VARCHAR2(15 BYTE),

  RESULTDETECTIONCONDITION        VARCHAR2(35 BYTE),

  CHARACTERISTICNAME              VARCHAR2(120 BYTE),

  METHODSPECIATIONNAME            VARCHAR2(20 BYTE),

  RESULTSAMPFRACTION              VARCHAR2(25 BYTE),

  RESULTMEASURE                   VARCHAR2(60 BYTE),

  RESULTMEASUREUNIT               VARCHAR2(12 BYTE),

  RESULTMEASUREQUALIFIERCODE      VARCHAR2(5 BYTE),

  STATUSID                        VARCHAR2(12 BYTE),

  STATISTICALBASECODE             VARCHAR2(25 BYTE),

  VALUETYPE                       VARCHAR2(20 BYTE),

  WEIGHTBASIS                     VARCHAR2(15 BYTE),

  TIMEBASIS                       VARCHAR2(12 BYTE),

  TEMPERATUREBASIS                VARCHAR2(12 BYTE),

  PARTICLESIZEBASIS               VARCHAR2(15 BYTE),

  PRECISIONVALUE                  VARCHAR2(60 BYTE),

  BIASVALUE                       VARCHAR2(60 BYTE),

  CONFIDENCEINTERVALVALUE         VARCHAR2(15 BYTE),

  UPPERCONFIDENCELIMITVALUE       VARCHAR2(15 BYTE),

  LOWERCONFIDENCELIMITVALUE       VARCHAR2(15 BYTE),

  RESULTCOMMENT                   VARCHAR2(4000 BYTE),

  DEPTHHEIGHTMEASURE              VARCHAR2(12 BYTE),

  DEPTHHEIGHTMEASUREUNIT          VARCHAR2(12 BYTE),

  DEPTHALTITUDEREFPOINT           VARCHAR2(125 BYTE),

  RESULTSAMPPOINT                 VARCHAR2(12 BYTE),

  BIORESULTINTENT                 VARCHAR2(35 BYTE),

  BIORESULTINDIVIDUALID           VARCHAR2(4 BYTE),

  BIORESULTSUBJECTTAXONOMIC       VARCHAR2(120 BYTE),

  BIORESULTUNIDENTIFIEDSPECIESID  VARCHAR2(120 BYTE),

  BIORESULTSAMPTISSUEANATOMY      VARCHAR2(30 BYTE),

  GRPSUMMCOUNTWEIGHTMEASURE       VARCHAR2(12 BYTE),

  GRPSUMMCOUNTWEIGHTMEASUREUNIT   VARCHAR2(12 BYTE),

  TAXDETAILSCELLFORM              VARCHAR2(11 BYTE),

  TAXDETAILSCELLSHAPE             VARCHAR2(18 BYTE),

  TAXDETAILSHABITNAME             VARCHAR2(15 BYTE),

  TAXDETAILSVOLTINISM             VARCHAR2(25 BYTE),

  TAXDETAILSPOLLTOLERANCE         VARCHAR2(4 BYTE),

  TAXDETAILSPOLLTOLERANCESCALE    VARCHAR2(50 BYTE),

  TAXDETAILSTROPHICLEVEL          VARCHAR2(4 BYTE),

  TAXDETAILSFUNCFEEDINGGROUP      VARCHAR2(6 BYTE),

  CITATIONRESOURCETITLE           VARCHAR2(120 BYTE),

  CITATIONRESOURCECREATOR         VARCHAR2(120 BYTE),

  CITATIONRESOURCESUBJECT         VARCHAR2(500 BYTE),

  CITATIONRESOURCEPUBLISHER       VARCHAR2(60 BYTE),

  CITATIONRESOURCEDATE            DATE,

  CITATIONRESOURCEID              VARCHAR2(255 BYTE),

  FREQCLASSDESCCODE               VARCHAR2(50 BYTE),

  FREQCLASSDESCUNITCODE           VARCHAR2(12 BYTE),

  FREQCLASSLOWERBOUNDVALUE        VARCHAR2(8 BYTE),

  FREQCLASSUPPERBOUNDVALUE        VARCHAR2(8 BYTE),

  ANALYTICALMETHODID              VARCHAR2(20 BYTE),

  ANALYTICALMETHODIDCONTEXT       VARCHAR2(120 BYTE),

  ANALYTICALMETHODNAME            VARCHAR2(120 BYTE),

  ANALYTICALMETHODQUALIFIERTYPE   VARCHAR2(25 BYTE),

  ANALYTICALMETHODDESC            VARCHAR2(500 BYTE),

  LABNAME                         VARCHAR2(60 BYTE),

  LABANALYSISSTARTDATE            DATE,

  LABANALYSISSTARTTIME            VARCHAR2(20 BYTE),

  LABANALYSISSTARTTIMEZONECODE    VARCHAR2(4 BYTE),

  LABANALYSISENDDATE              DATE,

  LABANALYSISENDTIME              VARCHAR2(20 BYTE),

  LABANALYSISENDTIMEZONECODE      VARCHAR2(4 BYTE),

  RESULTLABCOMMENTCODE            VARCHAR2(3 BYTE),

  LABACCIND                       CHAR(1 BYTE),

  LABACCAUTHORITYNAME             VARCHAR2(20 BYTE),

  LABTAXACCIND                    CHAR(1 BYTE),

  LABTAXACCAUTHORITYNAME          VARCHAR2(20 BYTE)

)

/





CREATE TABLE WQX_ACTIVITYACTIVITYGROUP

(

  RECORDID               VARCHAR2(50 BYTE)      NOT NULL,

  ACTIVITYPARENTID       VARCHAR2(50 BYTE)      NOT NULL,

  ACTIVITYGROUPPARENTID  VARCHAR2(50 BYTE)      NOT NULL,

  ACTIVITYID             VARCHAR2(35 BYTE)      NOT NULL

)

/





CREATE TABLE WQX_PROJATTACHEDBINARYOBJECT

(

  RECORDID                  VARCHAR2(50 BYTE)   NOT NULL,

  PARENTID                  VARCHAR2(50 BYTE)   NOT NULL,

  BINARYOBJECTFILE          VARCHAR2(255 BYTE)  NOT NULL,

  BINARYOBJECTFILETYPECODE  VARCHAR2(6 BYTE)    NOT NULL

)

/





CREATE TABLE WQX_PROJECTMONLOC

(

  RECORDID                    VARCHAR2(50 BYTE) NOT NULL,

  PARENTID                    VARCHAR2(50 BYTE) NOT NULL,

  MONLOCID                    VARCHAR2(35 BYTE) NOT NULL,

  LOCWEIGHTINGFACMEASURE      VARCHAR2(12 BYTE) NOT NULL,

  LOCWEIGHTINGFACMEASUREUNIT  VARCHAR2(12 BYTE) NOT NULL,

  STATISTICALSTRATUM          VARCHAR2(15 BYTE),

  LOCATIONCATERY              VARCHAR2(50 BYTE),

  LOCATIONSTATUS              VARCHAR2(15 BYTE),

  REFLOCATIONTYPECODE         VARCHAR2(20 BYTE),

  REFLOCATIONSTARTDATE        DATE,

  REFLOCATIONENDDATE          DATE,

  RESOURCETITLE               VARCHAR2(120 BYTE),

  RESOURCECREATOR             VARCHAR2(120 BYTE),

  RESOURCESUBJECT             VARCHAR2(500 BYTE),

  RESOURCEPUBLISHER           VARCHAR2(60 BYTE),

  RESOURCEDATE                DATE,

  RESOURCEID                  VARCHAR2(255 BYTE),

  PROJMONLOCCOMMENT           VARCHAR2(4000 BYTE)

)

/





CREATE TABLE WQX_PROJECTACTIVITY

(

  RECORDID          VARCHAR2(50 BYTE)           NOT NULL,

  PROJECTPARENTID   VARCHAR2(50 BYTE)           NOT NULL,

  ACTIVITYPARENTID  VARCHAR2(50 BYTE)           NOT NULL

)

/





CREATE TABLE WQX_ORGANIZATION

(

  RECORDID       VARCHAR2(50 BYTE)              NOT NULL,

  ORGID          VARCHAR2(30 BYTE)              NOT NULL,

  ORGFORMALNAME  VARCHAR2(120 BYTE)             NOT NULL,

  ORGDESC        VARCHAR2(500 BYTE),

  TRIBALCODE     VARCHAR2(3 BYTE)

)

/





CREATE UNIQUE INDEX PK_WQX_ACTATTBINARYOBJECT ON WQX_ACTATTACHEDBINARYOBJECT

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_ACTIVITY ON WQX_ACTIVITY

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_ACTIVITYACTIVITYGROUP ON WQX_ACTIVITYACTIVITYGROUP

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_ACTIVITYCONDUCTINGORG ON WQX_ACTIVITYCONDUCTINGORG

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_ACTIVITYGROUP ON WQX_ACTIVITYGROUP

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_ACTIVITYMETRIC ON WQX_ACTIVITYMETRIC

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_ALTMONLOC ON WQX_ALTMONLOC

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_BIOLOGICALHABITATINDEX ON WQX_BIOLOGICALHABITATINDEX

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_DELETES ON WQX_DELETES

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_ELECTRONICADDRESS ON WQX_ELECTRONICADDRESS

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_LABSAMPLEPREP ON WQX_LABSAMPLEPREP

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_MONITORINGLOCATION ON WQX_MONITORINGLOCATION

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_MONLOCATTBINARYOBJECT ON WQX_MONLOCATTACHEDBINARYOBJECT

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_ORGADDRESS ON WQX_ORGADDRESS

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_ORGANIZATION ON WQX_ORGANIZATION

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_PROJATTBINARYOBJECT ON WQX_PROJATTACHEDBINARYOBJECT

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_PROJECT ON WQX_PROJECT

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_PROJECTACTIVITY ON WQX_PROJECTACTIVITY

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_PROJECTMONLOC ON WQX_PROJECTMONLOC

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_RESULT ON WQX_RESULT

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_RESULTATTBINARYOBJECT ON WQX_RESULTATTACHEDBINARYOBJECT

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_RESULTDETECTQUANTLIMIT ON WQX_RESULTDETECTQUANTLIMIT

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_SUBMISSIONHISTORY ON WQX_SUBMISSIONHISTORY

(RECORDID)

/





CREATE UNIQUE INDEX PK_WQX_TELEPHONIC ON WQX_TELEPHONIC

(RECORDID)

/





ALTER TABLE WQX_ALTMONLOC ADD (

  CONSTRAINT PK_WQX_ALTMONLOC

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_MONLOCATTACHEDBINARYOBJECT ADD (

  CONSTRAINT PK_WQX_MONLOCATTBINARYOBJECT

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_PROJECT ADD (

  CONSTRAINT PK_WQX_PROJECT

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_ACTIVITYGROUP ADD (

  CONSTRAINT PK_WQX_ACTIVITYGROUP

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_ELECTRONICADDRESS ADD (

  CONSTRAINT PK_WQX_ELECTRONICADDRESS

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_BIOLOGICALHABITATINDEX ADD (

  CONSTRAINT PK_WQX_BIOLOGICALHABITATINDEX

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_TELEPHONIC ADD (

  CONSTRAINT PK_WQX_TELEPHONIC

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_SUBMISSIONHISTORY ADD (

  CONSTRAINT PK_WQX_SUBMISSIONHISTORY

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_DELETES ADD (

  CONSTRAINT PK_WQX_DELETES

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_ORGADDRESS ADD (

  CONSTRAINT PK_WQX_ORGADDRESS

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_MONITORINGLOCATION ADD (

  CONSTRAINT PK_WQX_MONITORINGLOCATION

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_ACTIVITY ADD (

  CONSTRAINT PK_WQX_ACTIVITY

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_LABSAMPLEPREP ADD (

  CONSTRAINT PK_WQX_LABSAMPLEPREP

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_RESULTDETECTQUANTLIMIT ADD (

  CONSTRAINT PK_WQX_RESULTDETECTQUANTLIMIT

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_RESULTATTACHEDBINARYOBJECT ADD (

  CONSTRAINT PK_WQX_RESULTATTBINARYOBJECT

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_ACTIVITYMETRIC ADD (

  CONSTRAINT PK_WQX_ACTIVITYMETRIC

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_ACTIVITYCONDUCTINGORG ADD (

  CONSTRAINT PK_WQX_ACTIVITYCONDUCTINGORG

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_ACTATTACHEDBINARYOBJECT ADD (

  CONSTRAINT PK_WQX_ACTATTBINARYOBJECT

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_RESULT ADD (

  CONSTRAINT PK_WQX_RESULT

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_ACTIVITYACTIVITYGROUP ADD (

  CONSTRAINT PK_WQX_ACTIVITYACTIVITYGROUP

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_PROJATTACHEDBINARYOBJECT ADD (

  CONSTRAINT PK_WQX_PROJATTBINARYOBJECT

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_PROJECTMONLOC ADD (

  CONSTRAINT PK_WQX_PROJECTMONLOC

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_PROJECTACTIVITY ADD (

  CONSTRAINT PK_WQX_PROJECTACTIVITY

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_ORGANIZATION ADD (

  CONSTRAINT PK_WQX_ORGANIZATION

 PRIMARY KEY

 (RECORDID))

/



ALTER TABLE WQX_ALTMONLOC ADD (

  CONSTRAINT FK_MONLOC_ALTMONLOC 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_MONITORINGLOCATION (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_MONLOCATTACHEDBINARYOBJECT ADD (

  CONSTRAINT FK_MONLOC_MONLOCATTBINOBJ 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_MONITORINGLOCATION (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_PROJECT ADD (

  CONSTRAINT FK_ORG_PROJECT 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ORGANIZATION (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_ACTIVITYGROUP ADD (

  CONSTRAINT FK_ORG_ACTIVITYGROUP 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ORGANIZATION (RECORDID))

/



ALTER TABLE WQX_ELECTRONICADDRESS ADD (

  CONSTRAINT FK_ORG_ELECTRONICADDRESS 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ORGANIZATION (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_BIOLOGICALHABITATINDEX ADD (

  CONSTRAINT FK_ORG_BIOLOGICALHABITATINDEX 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ORGANIZATION (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_TELEPHONIC ADD (

  CONSTRAINT FK_ORG_TELEPHONIC 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ORGANIZATION (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_SUBMISSIONHISTORY ADD (

  CONSTRAINT FK_WQX_SUBMISSIONHIST_WQX_ORG 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ORGANIZATION (RECORDID))

/



ALTER TABLE WQX_DELETES ADD (

  CONSTRAINT FK_WQX_DELETES_WQX_ORG 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ORGANIZATION (RECORDID))

/



ALTER TABLE WQX_ORGADDRESS ADD (

  CONSTRAINT FK_ORG_ORGADDRESS 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ORGANIZATION (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_MONITORINGLOCATION ADD (

  CONSTRAINT FK_ORG_MONITORINGLOCATION 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ORGANIZATION (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_ACTIVITY ADD (

  CONSTRAINT FK_ORG_ACTIVITY 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ORGANIZATION (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_LABSAMPLEPREP ADD (

  CONSTRAINT FK_RESULT_LABSAMPLEPREP 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_RESULT (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_RESULTDETECTQUANTLIMIT ADD (

  CONSTRAINT FK_RESULT_RESULTDETQUANTLIMIT 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_RESULT (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_RESULTATTACHEDBINARYOBJECT ADD (

  CONSTRAINT FK_RESULT_RESULTATTBINOBJ 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_RESULT (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_ACTIVITYMETRIC ADD (

  CONSTRAINT FK_ACTIVITY_ACTIVITYMETRIC 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ACTIVITY (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_ACTIVITYCONDUCTINGORG ADD (

  CONSTRAINT FK_ACTIVITY_ACTCONDUCTINGORG 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ACTIVITY (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_ACTATTACHEDBINARYOBJECT ADD (

  CONSTRAINT FK_ACTIVITY_ACTATTBINOBJ 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ACTIVITY (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_RESULT ADD (

  CONSTRAINT FK_ACTIVITY_RESULT 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_ACTIVITY (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_ACTIVITYACTIVITYGROUP ADD (

  CONSTRAINT FK_ACTIVITY_ACTACTGROUP 

 FOREIGN KEY (ACTIVITYPARENTID) 

 REFERENCES WQX_ACTIVITY (RECORDID)

    ON DELETE CASCADE,

  CONSTRAINT FK_ACTIVITYGROUP_ACTACTGROUP 

 FOREIGN KEY (ACTIVITYGROUPPARENTID) 

 REFERENCES WQX_ACTIVITYGROUP (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_PROJATTACHEDBINARYOBJECT ADD (

  CONSTRAINT FK_PROJECT_PROJATTBINOBJ 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_PROJECT (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_PROJECTMONLOC ADD (

  CONSTRAINT FK_PROJECT_PROJECTMONLOC 

 FOREIGN KEY (PARENTID) 

 REFERENCES WQX_PROJECT (RECORDID)

    ON DELETE CASCADE)

/



ALTER TABLE WQX_PROJECTACTIVITY ADD (

  CONSTRAINT FK_ACTIVITY_PROJECTACTIVITY 

 FOREIGN KEY (ACTIVITYPARENTID) 

 REFERENCES WQX_ACTIVITY (RECORDID),

  CONSTRAINT FK_PROJECT_PROJECTACTIVITY 

 FOREIGN KEY (PROJECTPARENTID) 

 REFERENCES WQX_PROJECT (RECORDID)

    ON DELETE CASCADE)

/

