web:
  image: registry.east.windsor.com:5000/opennode2:latest
  ports:
    - 8080
  environment:
    - VIRTUAL_PORT=8080
    - VIRTUAL_HOST=opennode2.jenkins.east.windsor.com
    - CATALINA_OPTS=-Doracle.jdbc.timezoneAsRegion=false